{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRActionsCommandBits",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRActionsCommandBits"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRActionsCommandBits"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTRActionsCommandBits"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBits"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBits"
        }
      ],
      "role": "symbol",
      "title": "MTRActionsCommandBits",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/disableAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/disableAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsDisableAction"
        }
      ],
      "role": "symbol",
      "title": "disableAction",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/disableaction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/disableActionWithDuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableActionWithDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/disableActionWithDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsDisableActionWithDuration"
        }
      ],
      "role": "symbol",
      "title": "disableActionWithDuration",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/disableactionwithduration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/enableAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/enableAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsEnableAction"
        }
      ],
      "role": "symbol",
      "title": "enableAction",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/enableaction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/enableActionWithDuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableActionWithDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/enableActionWithDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsEnableActionWithDuration"
        }
      ],
      "role": "symbol",
      "title": "enableActionWithDuration",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/enableactionwithduration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/instantAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instantAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/instantAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsInstantAction"
        }
      ],
      "role": "symbol",
      "title": "instantAction",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/instantaction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/instantActionWithTransition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instantActionWithTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/instantActionWithTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsInstantActionWithTransition"
        }
      ],
      "role": "symbol",
      "title": "instantActionWithTransition",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/instantactionwithtransition"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/pauseAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/pauseAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsPauseAction"
        }
      ],
      "role": "symbol",
      "title": "pauseAction",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/pauseaction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/pauseActionWithDuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseActionWithDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/pauseActionWithDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsPauseActionWithDuration"
        }
      ],
      "role": "symbol",
      "title": "pauseActionWithDuration",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/pauseactionwithduration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/resumeAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumeAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/resumeAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsResumeAction"
        }
      ],
      "role": "symbol",
      "title": "resumeAction",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/resumeaction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/startAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/startAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsStartAction"
        }
      ],
      "role": "symbol",
      "title": "startAction",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/startaction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/startActionWithDuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startActionWithDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/startActionWithDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsStartActionWithDuration"
        }
      ],
      "role": "symbol",
      "title": "startActionWithDuration",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/startactionwithduration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/stopAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRActionsCommandBits",
          "text": "MTRActionsCommandBits"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/stopAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRActionsCommandBitsStopAction"
        }
      ],
      "role": "symbol",
      "title": "stopAction",
      "type": "topic",
      "url": "/documentation/matter/mtractionscommandbits/stopaction"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/disableAction",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/disableActionWithDuration",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/enableAction",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/enableActionWithDuration",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/instantAction",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/instantActionWithTransition",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/pauseAction",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/pauseActionWithDuration",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/resumeAction",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/startAction",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/startActionWithDuration",
        "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/stopAction"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRActionsCommandBits"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/disableAction",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/disableActionWithDuration",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/enableAction",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/enableActionWithDuration",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/instantAction",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/instantActionWithTransition",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/pauseAction",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/pauseActionWithDuration",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/resumeAction",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/startAction",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/startActionWithDuration",
                "doc://com.apple.matter/documentation/Matter/MTRActionsCommandBits/stopAction"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRActionsCommandBits"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1pauseAction/title",
          "value": "MTRActionsCommandBitsPauseAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1pauseAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsPauseAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1disableAction/title",
          "value": "MTRActionsCommandBitsDisableAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1disableAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsDisableAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1enableAction/title",
          "value": "MTRActionsCommandBitsEnableAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1enableAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsEnableAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1instantAction/title",
          "value": "MTRActionsCommandBitsInstantAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1instantAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsInstantAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1pauseActionWithDuration/title",
          "value": "MTRActionsCommandBitsPauseActionWithDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1pauseActionWithDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsPauseActionWithDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1enableActionWithDuration/title",
          "value": "MTRActionsCommandBitsEnableActionWithDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1enableActionWithDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsEnableActionWithDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1disableActionWithDuration/title",
          "value": "MTRActionsCommandBitsDisableActionWithDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1disableActionWithDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsDisableActionWithDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1startAction/title",
          "value": "MTRActionsCommandBitsStartAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1startAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsStartAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits/title",
          "value": "MTRActionsCommandBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1instantActionWithTransition/title",
          "value": "MTRActionsCommandBitsInstantActionWithTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1instantActionWithTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsInstantActionWithTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1stopAction/title",
          "value": "MTRActionsCommandBitsStopAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1stopAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsStopAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1startActionWithDuration/title",
          "value": "MTRActionsCommandBitsStartActionWithDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1startActionWithDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsStartActionWithDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1resumeAction/title",
          "value": "MTRActionsCommandBitsResumeAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRActionsCommandBits~1resumeAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRActionsCommandBitsResumeAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtractionscommandbits"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtractionscommandbits"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
