{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRBridgedDeviceBasicInformationColor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRBridgedDeviceBasicInformationColor"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRBridgedDeviceBasicInformationColor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRBridgedDeviceBasicInformationColor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColor"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/aqua": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aqua"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/aqua",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorAqua"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.aqua",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/aqua"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/black": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "black"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/black",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorBlack"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.black",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/black"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/blue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorBlue"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.blue",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/blue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/brass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "brass"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/brass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorBrass"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.brass",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/brass"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/chrome": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chrome"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/chrome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorChrome"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.chrome",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/chrome"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/copper": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copper"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/copper",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorCopper"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.copper",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/copper"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/fuchsia": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fuchsia"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/fuchsia",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorFuchsia"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.fuchsia",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/fuchsia"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/gold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gold"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/gold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorGold"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.gold",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/gold"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/gray": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gray"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorGray"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.gray",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/gray"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/green": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorGreen"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.green",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/green"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/lime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lime"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/lime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorLime"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.lime",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/lime"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/maroon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maroon"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/maroon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorMaroon"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.maroon",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/maroon"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/navy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/navy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorNavy"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.navy",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/navy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/nickel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nickel"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/nickel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorNickel"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.nickel",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/nickel"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/olive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "olive"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/olive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorOlive"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.olive",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/olive"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/purple": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purple"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/purple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorPurple"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.purple",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/purple"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/red": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorRed"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.red",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/red"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/silver": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "silver"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/silver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorSilver"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.silver",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/silver"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/teal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "teal"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/teal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorTeal"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.teal",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/teal"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/white": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "white"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/white",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorWhite"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.white",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/white"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/yellow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yellow"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/yellow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationColorYellow"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationColor.yellow",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationcolor/yellow"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/aqua",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/black",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/blue",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/brass",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/chrome",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/copper",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/fuchsia",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/gold",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/gray",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/green",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/lime",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/maroon",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/navy",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/nickel",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/olive",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/purple",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/red",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/silver",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/teal",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/white",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/yellow"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRBridgedDeviceBasicInformationColor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/aqua",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/black",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/blue",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/brass",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/chrome",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/copper",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/fuchsia",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/gold",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/gray",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/green",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/lime",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/maroon",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/navy",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/nickel",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/olive",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/purple",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/red",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/silver",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/teal",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/white",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationColor/yellow"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRBridgedDeviceBasicInformationColor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor/title",
          "value": "MTRBridgedDeviceBasicInformationColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1chrome/title",
          "value": "MTRBridgedDeviceBasicInformationColorChrome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1chrome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorChrome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1teal/title",
          "value": "MTRBridgedDeviceBasicInformationColorTeal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1teal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorTeal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1purple/title",
          "value": "MTRBridgedDeviceBasicInformationColorPurple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1purple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorPurple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1aqua/title",
          "value": "MTRBridgedDeviceBasicInformationColorAqua"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1aqua/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorAqua"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1white/title",
          "value": "MTRBridgedDeviceBasicInformationColorWhite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1white/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorWhite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1brass/title",
          "value": "MTRBridgedDeviceBasicInformationColorBrass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1brass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorBrass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1copper/title",
          "value": "MTRBridgedDeviceBasicInformationColorCopper"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1copper/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorCopper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1black/title",
          "value": "MTRBridgedDeviceBasicInformationColorBlack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1black/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorBlack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1olive/title",
          "value": "MTRBridgedDeviceBasicInformationColorOlive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1olive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorOlive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1nickel/title",
          "value": "MTRBridgedDeviceBasicInformationColorNickel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1nickel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorNickel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1fuchsia/title",
          "value": "MTRBridgedDeviceBasicInformationColorFuchsia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1fuchsia/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorFuchsia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1gold/title",
          "value": "MTRBridgedDeviceBasicInformationColorGold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1gold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorGold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1blue/title",
          "value": "MTRBridgedDeviceBasicInformationColorBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1navy/title",
          "value": "MTRBridgedDeviceBasicInformationColorNavy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1navy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorNavy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1green/title",
          "value": "MTRBridgedDeviceBasicInformationColorGreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorGreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1lime/title",
          "value": "MTRBridgedDeviceBasicInformationColorLime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1lime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorLime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1gray/title",
          "value": "MTRBridgedDeviceBasicInformationColorGray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorGray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1maroon/title",
          "value": "MTRBridgedDeviceBasicInformationColorMaroon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1maroon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorMaroon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1red/title",
          "value": "MTRBridgedDeviceBasicInformationColorRed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorRed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1silver/title",
          "value": "MTRBridgedDeviceBasicInformationColorSilver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1silver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorSilver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1yellow/title",
          "value": "MTRBridgedDeviceBasicInformationColorYellow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationColor~1yellow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationColorYellow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrbridgeddevicebasicinformationcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrbridgeddevicebasicinformationcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
