{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRBaseClusterOTASoftwareUpdateProvider",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRBaseClusterOtaSoftwareUpdateProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRBaseClusterOTASoftwareUpdateProvider",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRBaseClusterOTASoftwareUpdateProvider",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRBaseClusterOTASoftwareUpdateProvider",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "Please use MTRBaseClusterOTASoftwareUpdateProvider",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRBaseClusterOTASoftwareUpdateProvider",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRBaseClusterOTASoftwareUpdateProvider",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "Please use MTRBaseClusterOTASoftwareUpdateProvider",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRBaseClusterOtaSoftwareUpdateProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRBaseClusterOTASoftwareUpdateProvider"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBaseClusterOTASoftwareUpdateProvider"
        }
      ],
      "role": "symbol",
      "title": "MTRBaseClusterOTASoftwareUpdateProvider",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
        }
      ],
      "role": "symbol",
      "title": "MTRBaseClusterOtaSoftwareUpdateProvider",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/applyUpdateRequest(with:completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applyUpdateRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROtaSoftwareUpdateProviderClusterApplyUpdateRequestParams",
          "text": "MTROtaSoftwareUpdateProviderClusterApplyUpdateRequestParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROtaSoftwareUpdateProviderClusterApplyUpdateResponseParams",
          "text": "MTROtaSoftwareUpdateProviderClusterApplyUpdateResponseParams"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/applyUpdateRequest(with:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applyUpdateRequestWithParams:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "applyUpdateRequest(with:completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/applyupdaterequest(with:completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/init(device:endpoint:queue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRBaseDevice",
          "text": "MTRBaseDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/init(device:endpoint:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:endpoint:queue:"
        }
      ],
      "role": "symbol",
      "title": "init(device:endpoint:queue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/init(device:endpoint:queue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/notifyUpdateApplied(with:completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notifyUpdateApplied"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROtaSoftwareUpdateProviderClusterNotifyUpdateAppliedParams",
          "text": "MTROtaSoftwareUpdateProviderClusterNotifyUpdateAppliedParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRStatusCompletion",
          "text": "MTRStatusCompletion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/notifyUpdateApplied(with:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notifyUpdateAppliedWithParams:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "notifyUpdateApplied(with:completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/notifyupdateapplied(with:completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/queryImage(with:completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROtaSoftwareUpdateProviderClusterQueryImageParams",
          "text": "MTROtaSoftwareUpdateProviderClusterQueryImageParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams",
          "text": "MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/queryImage(with:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queryImageWithParams:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "queryImage(with:completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/queryimage(with:completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAcceptedCommandList(completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAcceptedCommandList(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/readattributeacceptedcommandlist(completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAcceptedCommandList(withAttributeCache:endpoint:queue:completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAttributeCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRAttributeCacheContainer",
          "text": "MTRAttributeCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAcceptedCommandList(withAttributeCache:endpoint:queue:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithAttributeCache:endpoint:queue:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(withAttributeCache:endpoint:queue:completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/readattributeacceptedcommandlist(withattributecache:endpoint:queue:completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAttributeList(completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAttributeList(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/readattributeattributelist(completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAttributeList(withAttributeCache:endpoint:queue:completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAttributeCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRAttributeCacheContainer",
          "text": "MTRAttributeCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAttributeList(withAttributeCache:endpoint:queue:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithAttributeCache:endpoint:queue:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(withAttributeCache:endpoint:queue:completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/readattributeattributelist(withattributecache:endpoint:queue:completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeClusterRevision(completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeClusterRevision(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/readattributeclusterrevision(completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeClusterRevision(withAttributeCache:endpoint:queue:completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAttributeCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRAttributeCacheContainer",
          "text": "MTRAttributeCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeClusterRevision(withAttributeCache:endpoint:queue:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithAttributeCache:endpoint:queue:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(withAttributeCache:endpoint:queue:completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/readattributeclusterrevision(withattributecache:endpoint:queue:completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeFeatureMap(completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeFeatureMap(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/readattributefeaturemap(completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeFeatureMap(withAttributeCache:endpoint:queue:completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAttributeCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRAttributeCacheContainer",
          "text": "MTRAttributeCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeFeatureMap(withAttributeCache:endpoint:queue:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithAttributeCache:endpoint:queue:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(withAttributeCache:endpoint:queue:completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/readattributefeaturemap(withattributecache:endpoint:queue:completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeGeneratedCommandList(completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeGeneratedCommandList(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/readattributegeneratedcommandlist(completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeGeneratedCommandList(withAttributeCache:endpoint:queue:completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAttributeCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRAttributeCacheContainer",
          "text": "MTRAttributeCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeGeneratedCommandList(withAttributeCache:endpoint:queue:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithAttributeCache:endpoint:queue:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(withAttributeCache:endpoint:queue:completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/readattributegeneratedcommandlist(withattributecache:endpoint:queue:completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeAcceptedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMinInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maxInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "params"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeAcceptedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeAcceptedCommandListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeAcceptedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/subscribeattributeacceptedcommandlist(withmininterval:maxinterval:params:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeAttributeList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMinInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maxInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "params"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeAttributeList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeAttributeListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeAttributeList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/subscribeattributeattributelist(withmininterval:maxinterval:params:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeClusterRevision(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMinInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maxInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "params"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeClusterRevision(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeClusterRevisionWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeClusterRevision(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/subscribeattributeclusterrevision(withmininterval:maxinterval:params:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeFeatureMap(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMinInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maxInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "params"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeFeatureMap(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeFeatureMapWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeFeatureMap(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/subscribeattributefeaturemap(withmininterval:maxinterval:params:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeGeneratedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMinInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maxInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "params"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeGeneratedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeGeneratedCommandListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeGeneratedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync/subscribeattributegeneratedcommandlist(withmininterval:maxinterval:params:subscriptionestablished:reporthandler:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/init(device:endpoint:queue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/applyUpdateRequest(with:completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/notifyUpdateApplied(with:completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/queryImage(with:completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAcceptedCommandList(completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAttributeList(completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeClusterRevision(completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeFeatureMap(completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeGeneratedCommandList(completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeAcceptedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeAttributeList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeClusterRevision(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeFeatureMap(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeGeneratedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Methods",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAcceptedCommandList(withAttributeCache:endpoint:queue:completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAttributeList(withAttributeCache:endpoint:queue:completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeClusterRevision(withAttributeCache:endpoint:queue:completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeFeatureMap(withAttributeCache:endpoint:queue:completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeGeneratedCommandList(withAttributeCache:endpoint:queue:completionHandler:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRBaseClusterOtaSoftwareUpdateProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/init(device:endpoint:queue:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/applyUpdateRequest(with:completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/notifyUpdateApplied(with:completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/queryImage(with:completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAcceptedCommandList(completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAttributeList(completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeClusterRevision(completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeFeatureMap(completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeGeneratedCommandList(completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeAcceptedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeAttributeList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeClusterRevision(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeFeatureMap(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/subscribeAttributeGeneratedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAcceptedCommandList(withAttributeCache:endpoint:queue:completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeAttributeList(withAttributeCache:endpoint:queue:completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeClusterRevision(withAttributeCache:endpoint:queue:completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeFeatureMap(withAttributeCache:endpoint:queue:completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync/readAttributeGeneratedCommandList(withAttributeCache:endpoint:queue:completionHandler:)"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRBaseClusterOTASoftwareUpdateProvider",
                    "text": "MTRBaseClusterOTASoftwareUpdateProvider"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRBaseClusterOTASoftwareUpdateProvider",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1queryImage(with:completionHandler:)/title",
          "value": "queryImageWithParams:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1queryImage(with:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "queryImageWithParams:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeAcceptedCommandList(completionHandler:)/title",
          "value": "readAttributeAcceptedCommandListWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeAcceptedCommandList(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1applyUpdateRequest(with:completionHandler:)/title",
          "value": "applyUpdateRequestWithParams:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1applyUpdateRequest(with:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applyUpdateRequestWithParams:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1subscribeAttributeClusterRevision(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeClusterRevisionWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1subscribeAttributeClusterRevision(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeClusterRevisionWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeFeatureMap(withAttributeCache:endpoint:queue:completionHandler:)/title",
          "value": "readAttributeFeatureMapWithAttributeCache:endpoint:queue:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeFeatureMap(withAttributeCache:endpoint:queue:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithAttributeCache:endpoint:queue:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeGeneratedCommandList(withAttributeCache:endpoint:queue:completionHandler:)/title",
          "value": "readAttributeGeneratedCommandListWithAttributeCache:endpoint:queue:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeGeneratedCommandList(withAttributeCache:endpoint:queue:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithAttributeCache:endpoint:queue:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1subscribeAttributeFeatureMap(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeFeatureMapWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1subscribeAttributeFeatureMap(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeFeatureMapWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1subscribeAttributeGeneratedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeGeneratedCommandListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1subscribeAttributeGeneratedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeGeneratedCommandListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeAcceptedCommandList(withAttributeCache:endpoint:queue:completionHandler:)/title",
          "value": "readAttributeAcceptedCommandListWithAttributeCache:endpoint:queue:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeAcceptedCommandList(withAttributeCache:endpoint:queue:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithAttributeCache:endpoint:queue:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit/title",
          "value": "MTRBaseClusterOTASoftwareUpdateProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOTASoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOTASoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeFeatureMap(completionHandler:)/title",
          "value": "readAttributeFeatureMapWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeFeatureMap(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeClusterRevision(completionHandler:)/title",
          "value": "readAttributeClusterRevisionWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeClusterRevision(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync/title",
          "value": "MTRBaseClusterOtaSoftwareUpdateProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1subscribeAttributeAttributeList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeAttributeListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1subscribeAttributeAttributeList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeAttributeListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeAttributeList(completionHandler:)/title",
          "value": "readAttributeAttributeListWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeAttributeList(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeClusterRevision(withAttributeCache:endpoint:queue:completionHandler:)/title",
          "value": "readAttributeClusterRevisionWithAttributeCache:endpoint:queue:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeClusterRevision(withAttributeCache:endpoint:queue:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithAttributeCache:endpoint:queue:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeAttributeList(withAttributeCache:endpoint:queue:completionHandler:)/title",
          "value": "readAttributeAttributeListWithAttributeCache:endpoint:queue:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeAttributeList(withAttributeCache:endpoint:queue:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithAttributeCache:endpoint:queue:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeGeneratedCommandList(completionHandler:)/title",
          "value": "readAttributeGeneratedCommandListWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1readAttributeGeneratedCommandList(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1subscribeAttributeAcceptedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeAcceptedCommandListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1subscribeAttributeAcceptedCommandList(withMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeAcceptedCommandListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1notifyUpdateApplied(with:completionHandler:)/title",
          "value": "notifyUpdateAppliedWithParams:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1notifyUpdateApplied(with:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "notifyUpdateAppliedWithParams:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1init(device:endpoint:queue:)/title",
          "value": "initWithDevice:endpoint:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync~1init(device:endpoint:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:endpoint:queue:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
