{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRBasicInformationColor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRBasicInformationColor"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRBasicInformationColor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRBasicInformationColor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColor"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/aqua": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aqua"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/aqua",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorAqua"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.aqua",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/aqua"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/black": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "black"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/black",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorBlack"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.black",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/black"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/blue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorBlue"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.blue",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/blue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/brass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "brass"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/brass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorBrass"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.brass",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/brass"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/chrome": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chrome"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/chrome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorChrome"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.chrome",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/chrome"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/copper": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copper"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/copper",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorCopper"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.copper",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/copper"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/fuchsia": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fuchsia"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/fuchsia",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorFuchsia"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.fuchsia",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/fuchsia"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/gold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gold"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/gold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorGold"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.gold",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/gold"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/gray": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gray"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorGray"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.gray",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/gray"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/green": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorGreen"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.green",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/green"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/lime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lime"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/lime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorLime"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.lime",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/lime"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/maroon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maroon"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/maroon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorMaroon"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.maroon",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/maroon"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/navy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/navy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorNavy"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.navy",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/navy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/nickel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nickel"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/nickel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorNickel"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.nickel",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/nickel"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/olive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "olive"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/olive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorOlive"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.olive",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/olive"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/purple": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purple"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/purple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorPurple"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.purple",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/purple"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/red": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorRed"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.red",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/red"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/silver": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "silver"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/silver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorSilver"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.silver",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/silver"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/teal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "teal"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/teal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorTeal"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.teal",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/teal"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/white": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "white"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/white",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorWhite"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.white",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/white"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/yellow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yellow"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/yellow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBasicInformationColorYellow"
        }
      ],
      "role": "symbol",
      "title": "MTRBasicInformationColor.yellow",
      "type": "topic",
      "url": "/documentation/matter/mtrbasicinformationcolor/yellow"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/aqua",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/black",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/blue",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/brass",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/chrome",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/copper",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/fuchsia",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/gold",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/gray",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/green",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/lime",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/maroon",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/navy",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/nickel",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/olive",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/purple",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/red",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/silver",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/teal",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/white",
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/yellow"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRBasicInformationColor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/aqua",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/black",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/blue",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/brass",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/chrome",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/copper",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/fuchsia",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/gold",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/gray",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/green",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/lime",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/maroon",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/navy",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/nickel",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/olive",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/purple",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/red",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/silver",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/teal",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/white",
                "doc://com.apple.matter/documentation/Matter/MTRBasicInformationColor/yellow"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRBasicInformationColor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1purple/title",
          "value": "MTRBasicInformationColorPurple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1purple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorPurple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1maroon/title",
          "value": "MTRBasicInformationColorMaroon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1maroon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorMaroon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1nickel/title",
          "value": "MTRBasicInformationColorNickel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1nickel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorNickel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor/title",
          "value": "MTRBasicInformationColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1white/title",
          "value": "MTRBasicInformationColorWhite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1white/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorWhite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1aqua/title",
          "value": "MTRBasicInformationColorAqua"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1aqua/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorAqua"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1silver/title",
          "value": "MTRBasicInformationColorSilver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1silver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorSilver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1blue/title",
          "value": "MTRBasicInformationColorBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1yellow/title",
          "value": "MTRBasicInformationColorYellow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1yellow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorYellow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1navy/title",
          "value": "MTRBasicInformationColorNavy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1navy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorNavy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1olive/title",
          "value": "MTRBasicInformationColorOlive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1olive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorOlive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1red/title",
          "value": "MTRBasicInformationColorRed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorRed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1brass/title",
          "value": "MTRBasicInformationColorBrass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1brass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorBrass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1gold/title",
          "value": "MTRBasicInformationColorGold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1gold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorGold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1fuchsia/title",
          "value": "MTRBasicInformationColorFuchsia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1fuchsia/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorFuchsia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1copper/title",
          "value": "MTRBasicInformationColorCopper"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1copper/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorCopper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1teal/title",
          "value": "MTRBasicInformationColorTeal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1teal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorTeal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1black/title",
          "value": "MTRBasicInformationColorBlack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1black/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorBlack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1green/title",
          "value": "MTRBasicInformationColorGreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorGreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1lime/title",
          "value": "MTRBasicInformationColorLime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1lime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorLime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1chrome/title",
          "value": "MTRBasicInformationColorChrome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1chrome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorChrome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1gray/title",
          "value": "MTRBasicInformationColorGray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBasicInformationColor~1gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBasicInformationColorGray"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrbasicinformationcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrbasicinformationcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
