{
  "abstract": [
    {
      "text": "Cluster Commissioner Control",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRBaseClusterCommissionerControl",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRBaseClusterCommissionerControl"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRBaseClusterCommissionerControl"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRBaseClusterCommissionerControl"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRBaseClusterCommissionerControl"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Supports the ability for clients to request the commissioning of themselves or other nodes onto a fabric which the cluster server can commission onto.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl": {
      "abstract": [
        {
          "text": "Cluster Commissioner Control",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRBaseClusterCommissionerControl"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBaseClusterCommissionerControl"
        }
      ],
      "role": "symbol",
      "title": "MTRBaseClusterCommissionerControl",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/commissionNode(with:completion:)": {
      "abstract": [
        {
          "text": "Command CommissionNode",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commissionNode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRCommissionerControlClusterCommissionNodeParams",
          "text": "MTRCommissionerControlClusterCommissionNodeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRCommissionerControlClusterReverseOpenCommissioningWindowParams",
          "text": "MTRCommissionerControlClusterReverseOpenCommissioningWindowParams"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/commissionNode(with:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commissionNodeWithParams:completion:"
        }
      ],
      "role": "symbol",
      "title": "commissionNode(with:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/commissionnode(with:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/init(device:endpointID:queue:)": {
      "abstract": [
        {
          "text": "For all instance methods (reads, writes, commands) that take a completion,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the completion will be called on the provided queue.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRBaseDevice",
          "text": "MTRBaseDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpointID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/init(device:endpointID:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:endpointID:queue:"
        }
      ],
      "role": "symbol",
      "title": "init(device:endpointID:queue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/init(device:endpointid:queue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAcceptedCommandList(completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAcceptedCommandList(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributeacceptedcommandlist(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributeacceptedcommandlist(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAttributeList(completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAttributeList(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributeattributelist(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributeattributelist(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeClusterRevision(completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeClusterRevision(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributeclusterrevision(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributeclusterrevision(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeFeatureMap(completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeFeatureMap(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributefeaturemap(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributefeaturemap(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeGeneratedCommandList(completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeGeneratedCommandList(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributegeneratedcommandlist(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributegeneratedcommandlist(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeSupportedDeviceCategories(completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeSupportedDeviceCategories"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeSupportedDeviceCategories(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeSupportedDeviceCategoriesWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeSupportedDeviceCategories(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributesupporteddevicecategories(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeSupportedDeviceCategories(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeSupportedDeviceCategories"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeSupportedDeviceCategories(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeSupportedDeviceCategoriesWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeSupportedDeviceCategories(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/readattributesupporteddevicecategories(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/requestCommissioningApproval(with:completion:)": {
      "abstract": [
        {
          "text": "Command RequestCommissioningApproval",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestCommissioningApproval"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRCommissionerControlClusterRequestCommissioningApprovalParams",
          "text": "MTRCommissionerControlClusterRequestCommissioningApprovalParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRStatusCompletion",
          "text": "MTRStatusCompletion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/requestCommissioningApproval(with:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestCommissioningApprovalWithParams:completion:"
        }
      ],
      "role": "symbol",
      "title": "requestCommissioningApproval(with:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/requestcommissioningapproval(with:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeAcceptedCommandListWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/subscribeattributeacceptedcommandlist(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeAttributeListWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/subscribeattributeattributelist(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeClusterRevisionWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/subscribeattributeclusterrevision(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeFeatureMapWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/subscribeattributefeaturemap(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeGeneratedCommandListWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/subscribeattributegeneratedcommandlist(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeSupportedDeviceCategories(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeSupportedDeviceCategories"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeSupportedDeviceCategories(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeSupportedDeviceCategoriesWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeSupportedDeviceCategories(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclustercommissionercontrol/subscribeattributesupporteddevicecategories(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGenericBaseCluster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGenericBaseCluster"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericBaseCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGenericBaseCluster"
        }
      ],
      "role": "symbol",
      "title": "MTRGenericBaseCluster",
      "type": "topic",
      "url": "/documentation/matter/mtrgenericbasecluster"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGenericBaseCluster"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/init(device:endpointID:queue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/commissionNode(with:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAcceptedCommandList(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAttributeList(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeClusterRevision(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeFeatureMap(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeGeneratedCommandList(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeSupportedDeviceCategories(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/requestCommissioningApproval(with:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeSupportedDeviceCategories(with:subscriptionEstablished:reportHandler:)"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeSupportedDeviceCategories(withClusterStateCache:endpoint:queue:completion:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRBaseClusterCommissionerControl"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterCommissionerControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterCommissionerControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/commissionNode(with:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/init(device:endpointID:queue:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAcceptedCommandList(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAttributeList(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeClusterRevision(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeFeatureMap(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeGeneratedCommandList(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeSupportedDeviceCategories(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/requestCommissioningApproval(with:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/subscribeAttributeSupportedDeviceCategories(with:subscriptionEstablished:reportHandler:)"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterCommissionerControl/readAttributeSupportedDeviceCategories(withClusterStateCache:endpoint:queue:completion:)"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGenericBaseCluster"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRBaseClusterCommissionerControl"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericBaseCluster",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRGenericBaseCluster",
                    "text": "MTRGenericBaseCluster"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeClusterRevisionWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeClusterRevisionWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeAcceptedCommandListWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeAcceptedCommandList(completion:)/title",
          "value": "readAttributeAcceptedCommandListWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeAcceptedCommandList(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1init(device:endpointID:queue:)/title",
          "value": "initWithDevice:endpointID:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1init(device:endpointID:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:endpointID:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeGeneratedCommandList(completion:)/title",
          "value": "readAttributeGeneratedCommandListWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeGeneratedCommandList(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeAttributeList(completion:)/title",
          "value": "readAttributeAttributeListWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeAttributeList(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeGeneratedCommandListWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeSupportedDeviceCategories(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeSupportedDeviceCategoriesWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeSupportedDeviceCategories(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeSupportedDeviceCategoriesWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeAttributeListWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeFeatureMapWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericBaseCluster/title",
          "value": "MTRGenericBaseCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericBaseCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericBaseCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericBaseCluster/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericBaseCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeAttributeListWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeAttributeListWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeSupportedDeviceCategories(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeSupportedDeviceCategoriesWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeSupportedDeviceCategories(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeSupportedDeviceCategoriesWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeAcceptedCommandListWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeAcceptedCommandListWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl/title",
          "value": "MTRBaseClusterCommissionerControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterCommissionerControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterCommissionerControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeSupportedDeviceCategories(completion:)/title",
          "value": "readAttributeSupportedDeviceCategoriesWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeSupportedDeviceCategories(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeSupportedDeviceCategoriesWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeClusterRevision(completion:)/title",
          "value": "readAttributeClusterRevisionWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeClusterRevision(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeGeneratedCommandListWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeGeneratedCommandListWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeClusterRevisionWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeFeatureMapWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeFeatureMapWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeFeatureMap(completion:)/title",
          "value": "readAttributeFeatureMapWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1readAttributeFeatureMap(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1requestCommissioningApproval(with:completion:)/title",
          "value": "requestCommissioningApprovalWithParams:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1requestCommissioningApproval(with:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestCommissioningApprovalWithParams:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1commissionNode(with:completion:)/title",
          "value": "commissionNodeWithParams:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterCommissionerControl~1commissionNode(with:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "commissionNodeWithParams:completion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrbaseclustercommissionercontrol"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrbaseclustercommissionercontrol"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
