{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRBridgedDeviceBasicInformationProductFinish",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRBridgedDeviceBasicInformationProductFinish"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRBridgedDeviceBasicInformationProductFinish"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRBridgedDeviceBasicInformationProductFinish"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinish"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationProductFinish"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationProductFinish"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationProductFinish",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationproductfinish"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/fabric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabric"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/fabric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationProductFinishFabric"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationProductFinish.fabric",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationproductfinish/fabric"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationproductfinish/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/matte": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matte"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/matte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationProductFinishMatte"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationProductFinish.matte",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationproductfinish/matte"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/other": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationProductFinishOther"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationProductFinish.other",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationproductfinish/other"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/polished": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "polished"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/polished",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationProductFinishPolished"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationProductFinish.polished",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationproductfinish/polished"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/rugged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rugged"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/rugged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationProductFinishRugged"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationProductFinish.rugged",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationproductfinish/rugged"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/satin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "satin"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/satin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBridgedDeviceBasicInformationProductFinishSatin"
        }
      ],
      "role": "symbol",
      "title": "MTRBridgedDeviceBasicInformationProductFinish.satin",
      "type": "topic",
      "url": "/documentation/matter/mtrbridgeddevicebasicinformationproductfinish/satin"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/fabric",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/matte",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/other",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/polished",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/rugged",
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/satin"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRBridgedDeviceBasicInformationProductFinish"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/fabric",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/matte",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/other",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/polished",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/rugged",
                "doc://com.apple.matter/documentation/Matter/MTRBridgedDeviceBasicInformationProductFinish/satin"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRBridgedDeviceBasicInformationProductFinish"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1rugged/title",
          "value": "MTRBridgedDeviceBasicInformationProductFinishRugged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1rugged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinishRugged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1fabric/title",
          "value": "MTRBridgedDeviceBasicInformationProductFinishFabric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1fabric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinishFabric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1satin/title",
          "value": "MTRBridgedDeviceBasicInformationProductFinishSatin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1satin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinishSatin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1matte/title",
          "value": "MTRBridgedDeviceBasicInformationProductFinishMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1matte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinishMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1polished/title",
          "value": "MTRBridgedDeviceBasicInformationProductFinishPolished"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1polished/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinishPolished"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1other/title",
          "value": "MTRBridgedDeviceBasicInformationProductFinishOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinishOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish/title",
          "value": "MTRBridgedDeviceBasicInformationProductFinish"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBridgedDeviceBasicInformationProductFinish/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBridgedDeviceBasicInformationProductFinish"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrbridgeddevicebasicinformationproductfinish"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrbridgeddevicebasicinformationproductfinish"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
