{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRBaseClusterOTASoftwareUpdateProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRBaseClusterOTASoftwareUpdateProvider"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRBaseClusterOTASoftwareUpdateProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRBaseClusterOTASoftwareUpdateProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOTASoftwareUpdateProvider"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRBaseClusterOTASoftwareUpdateProvider"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBaseClusterOTASoftwareUpdateProvider"
        }
      ],
      "role": "symbol",
      "title": "MTRBaseClusterOTASoftwareUpdateProvider",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/applyUpdateRequest(with:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applyUpdateRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROTASoftwareUpdateProviderClusterApplyUpdateRequestParams",
          "text": "MTROTASoftwareUpdateProviderClusterApplyUpdateRequestParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROTASoftwareUpdateProviderClusterApplyUpdateResponseParams",
          "text": "MTROTASoftwareUpdateProviderClusterApplyUpdateResponseParams"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/applyUpdateRequest(with:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applyUpdateRequestWithParams:completion:"
        }
      ],
      "role": "symbol",
      "title": "applyUpdateRequest(with:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/applyupdaterequest(with:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/init(device:endpointID:queue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRBaseDevice",
          "text": "MTRBaseDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpointID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/init(device:endpointID:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:endpointID:queue:"
        }
      ],
      "role": "symbol",
      "title": "init(device:endpointID:queue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/init(device:endpointid:queue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/notifyUpdateApplied(with:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notifyUpdateApplied"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROTASoftwareUpdateProviderClusterNotifyUpdateAppliedParams",
          "text": "MTROTASoftwareUpdateProviderClusterNotifyUpdateAppliedParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRStatusCompletion",
          "text": "MTRStatusCompletion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/notifyUpdateApplied(with:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notifyUpdateAppliedWithParams:completion:"
        }
      ],
      "role": "symbol",
      "title": "notifyUpdateApplied(with:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/notifyupdateapplied(with:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/queryImage(with:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROTASoftwareUpdateProviderClusterQueryImageParams",
          "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROTASoftwareUpdateProviderClusterQueryImageResponseParams",
          "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/queryImage(with:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queryImageWithParams:completion:"
        }
      ],
      "role": "symbol",
      "title": "queryImage(with:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/queryimage(with:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAcceptedCommandList(completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAcceptedCommandList(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/readattributeacceptedcommandlist(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/readattributeacceptedcommandlist(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAttributeList(completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAttributeList(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/readattributeattributelist(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/readattributeattributelist(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeClusterRevision(completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeClusterRevision(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/readattributeclusterrevision(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/readattributeclusterrevision(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeFeatureMap(completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeFeatureMap(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/readattributefeaturemap(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/readattributefeaturemap(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeGeneratedCommandList(completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeGeneratedCommandList(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/readattributegeneratedcommandlist(completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withClusterStateCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRClusterStateCacheContainer",
          "text": "MTRClusterStateCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithClusterStateCache:endpoint:queue:completion:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/readattributegeneratedcommandlist(withclusterstatecache:endpoint:queue:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeAcceptedCommandListWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/subscribeattributeacceptedcommandlist(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeAttributeListWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/subscribeattributeattributelist(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeClusterRevisionWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/subscribeattributeclusterrevision(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeFeatureMapWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/subscribeattributefeaturemap(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribeAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSubscribeParams",
          "text": "MTRSubscribeParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRSubscriptionEstablishedHandler",
          "text": "MTRSubscriptionEstablishedHandler"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reportHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeAttributeGeneratedCommandListWithParams:subscriptionEstablished:reportHandler:"
        }
      ],
      "role": "symbol",
      "title": "subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit/subscribeattributegeneratedcommandlist(with:subscriptionestablished:reporthandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
        }
      ],
      "role": "symbol",
      "title": "MTRBaseClusterOtaSoftwareUpdateProvider",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-2vync"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGenericBaseCluster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGenericBaseCluster"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericBaseCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGenericBaseCluster"
        }
      ],
      "role": "symbol",
      "title": "MTRGenericBaseCluster",
      "type": "topic",
      "url": "/documentation/matter/mtrgenericbasecluster"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGenericBaseCluster"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/init(device:endpointID:queue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/applyUpdateRequest(with:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/notifyUpdateApplied(with:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/queryImage(with:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAcceptedCommandList(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAttributeList(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeClusterRevision(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeFeatureMap(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeGeneratedCommandList(completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Methods",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRBaseClusterOTASoftwareUpdateProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOTASoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOTASoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/init(device:endpointID:queue:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/applyUpdateRequest(with:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/notifyUpdateApplied(with:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/queryImage(with:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAcceptedCommandList(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAttributeList(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeClusterRevision(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeFeatureMap(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeGeneratedCommandList(completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOTASoftwareUpdateProvider-8bnit/readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGenericBaseCluster"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterOtaSoftwareUpdateProvider-2vync"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRBaseClusterOTASoftwareUpdateProvider"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericBaseCluster",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRGenericBaseCluster",
                    "text": "MTRGenericBaseCluster"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeAcceptedCommandList(completion:)/title",
          "value": "readAttributeAcceptedCommandListWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeAcceptedCommandList(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeAcceptedCommandListWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeAcceptedCommandList(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeFeatureMap(completion:)/title",
          "value": "readAttributeFeatureMapWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeFeatureMap(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1queryImage(with:completion:)/title",
          "value": "queryImageWithParams:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1queryImage(with:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "queryImageWithParams:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1notifyUpdateApplied(with:completion:)/title",
          "value": "notifyUpdateAppliedWithParams:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1notifyUpdateApplied(with:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "notifyUpdateAppliedWithParams:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeClusterRevision(completion:)/title",
          "value": "readAttributeClusterRevisionWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeClusterRevision(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeClusterRevisionWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeClusterRevision(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeGeneratedCommandList(completion:)/title",
          "value": "readAttributeGeneratedCommandListWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeGeneratedCommandList(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit/title",
          "value": "MTRBaseClusterOTASoftwareUpdateProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOTASoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOTASoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeAttributeListWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1subscribeAttributeAttributeList(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeAttributeListWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeGeneratedCommandListWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeGeneratedCommandList(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1init(device:endpointID:queue:)/title",
          "value": "initWithDevice:endpointID:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1init(device:endpointID:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:endpointID:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeFeatureMapWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1subscribeAttributeFeatureMap(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeFeatureMapWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeAttributeListWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeAttributeList(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericBaseCluster/title",
          "value": "MTRGenericBaseCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericBaseCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericBaseCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericBaseCluster/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericBaseCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)/title",
          "value": "readAttributeFeatureMapWithClusterStateCache:endpoint:queue:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeFeatureMap(withClusterStateCache:endpoint:queue:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithClusterStateCache:endpoint:queue:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeClusterRevisionWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1subscribeAttributeClusterRevision(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeClusterRevisionWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeAttributeList(completion:)/title",
          "value": "readAttributeAttributeListWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1readAttributeAttributeList(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync/title",
          "value": "MTRBaseClusterOtaSoftwareUpdateProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOtaSoftwareUpdateProvider-2vync/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterOtaSoftwareUpdateProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeAcceptedCommandListWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1subscribeAttributeAcceptedCommandList(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeAcceptedCommandListWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1applyUpdateRequest(with:completion:)/title",
          "value": "applyUpdateRequestWithParams:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1applyUpdateRequest(with:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applyUpdateRequestWithParams:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)/title",
          "value": "subscribeAttributeGeneratedCommandListWithParams:subscriptionEstablished:reportHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterOTASoftwareUpdateProvider-8bnit~1subscribeAttributeGeneratedCommandList(with:subscriptionEstablished:reportHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscribeAttributeGeneratedCommandListWithParams:subscriptionEstablished:reportHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrbaseclusterotasoftwareupdateprovider-8bnit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
