{
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRClusterWakeOnLAN",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRClusterWakeOnLAN"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRClusterWakeOnLAN"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRClusterWakeOnLAN"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRClusterWakeOnLAN"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRClusterWakeOnLAN"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRClusterWakeOnLAN"
        }
      ],
      "role": "symbol",
      "title": "MTRClusterWakeOnLAN",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterwakeonlan-6dyo6"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/init(device:endpointID:queue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRDevice",
          "text": "MTRDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpointID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/init(device:endpointID:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:endpointID:queue:"
        }
      ],
      "role": "symbol",
      "title": "init(device:endpointID:queue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterwakeonlan-6dyo6/init(device:endpointid:queue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeAcceptedCommandList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeAcceptedCommandList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterwakeonlan-6dyo6/readattributeacceptedcommandlist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeAttributeList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeAttributeList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterwakeonlan-6dyo6/readattributeattributelist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeClusterRevision(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeClusterRevision(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterwakeonlan-6dyo6/readattributeclusterrevision(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeFeatureMap(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeFeatureMap(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterwakeonlan-6dyo6/readattributefeaturemap(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeGeneratedCommandList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeGeneratedCommandList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterwakeonlan-6dyo6/readattributegeneratedcommandlist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeLinkLocalAddress(with:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeLinkLocalAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeLinkLocalAddress(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeLinkLocalAddressWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeLinkLocalAddress(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterwakeonlan-6dyo6/readattributelinklocaladdress(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeMACAddress(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeMACAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeMACAddress(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeMACAddressWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeMACAddress(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterwakeonlan-6dyo6/readattributemacaddress(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLan-6e8me": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRClusterWakeOnLan"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLan-6e8me",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRClusterWakeOnLan"
        }
      ],
      "role": "symbol",
      "title": "MTRClusterWakeOnLan",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterwakeonlan-6e8me"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGenericCluster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGenericCluster"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGenericCluster"
        }
      ],
      "role": "symbol",
      "title": "MTRGenericCluster",
      "type": "topic",
      "url": "/documentation/matter/mtrgenericcluster"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGenericCluster"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLan-6e8me"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/init(device:endpointID:queue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeAcceptedCommandList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeAttributeList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeClusterRevision(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeFeatureMap(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeGeneratedCommandList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeMACAddress(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeLinkLocalAddress(with:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRClusterWakeOnLAN"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterWakeOnLAN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterWakeOnLAN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/init(device:endpointID:queue:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeAcceptedCommandList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeAttributeList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeClusterRevision(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeFeatureMap(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeGeneratedCommandList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeMACAddress(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLAN-6dyo6/readAttributeLinkLocalAddress(with:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGenericCluster"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterWakeOnLan-6e8me"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRClusterWakeOnLAN"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericCluster",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRGenericCluster",
                    "text": "MTRGenericCluster"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeClusterRevision(with:)/title",
          "value": "readAttributeClusterRevisionWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeClusterRevision(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeGeneratedCommandList(with:)/title",
          "value": "readAttributeGeneratedCommandListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeGeneratedCommandList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeFeatureMap(with:)/title",
          "value": "readAttributeFeatureMapWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeFeatureMap(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeLinkLocalAddress(with:)/title",
          "value": "readAttributeLinkLocalAddressWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeLinkLocalAddress(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeLinkLocalAddressWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeAcceptedCommandList(with:)/title",
          "value": "readAttributeAcceptedCommandListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeAcceptedCommandList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/title",
          "value": "MTRGenericCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6/title",
          "value": "MTRClusterWakeOnLAN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterWakeOnLAN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterWakeOnLAN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeMACAddress(with:)/title",
          "value": "readAttributeMACAddressWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeMACAddress(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeMACAddressWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1init(device:endpointID:queue:)/title",
          "value": "initWithDevice:endpointID:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1init(device:endpointID:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:endpointID:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeAttributeList(with:)/title",
          "value": "readAttributeAttributeListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLAN-6dyo6~1readAttributeAttributeList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLan-6e8me/title",
          "value": "MTRClusterWakeOnLan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLan-6e8me/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterWakeOnLan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterWakeOnLan-6e8me/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterWakeOnLan"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrclusterwakeonlan-6dyo6"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrclusterwakeonlan-6dyo6"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
