{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRClusterOTASoftwareUpdateRequestor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRClusterOTASoftwareUpdateRequestor"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRClusterOTASoftwareUpdateRequestor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRClusterOTASoftwareUpdateRequestor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRClusterOTASoftwareUpdateRequestor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRClusterOTASoftwareUpdateRequestor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRClusterOTASoftwareUpdateRequestor"
        }
      ],
      "role": "symbol",
      "title": "MTRClusterOTASoftwareUpdateRequestor",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/announceOTAProvider(with:expectedValues:expectedValueInterval:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "announceOTAProvider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTROTASoftwareUpdateRequestorClusterAnnounceOTAProviderParams",
          "text": "MTROTASoftwareUpdateRequestorClusterAnnounceOTAProviderParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "expectedValues"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]]?, "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRStatusCompletion",
          "text": "MTRStatusCompletion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/announceOTAProvider(with:expectedValues:expectedValueInterval:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "announceOTAProviderWithParams:expectedValues:expectedValueInterval:completion:"
        }
      ],
      "role": "symbol",
      "title": "announceOTAProvider(with:expectedValues:expectedValueInterval:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/announceotaprovider(with:expectedvalues:expectedvalueinterval:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/init(device:endpointID:queue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRDevice",
          "text": "MTRDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpointID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/init(device:endpointID:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:endpointID:queue:"
        }
      ],
      "role": "symbol",
      "title": "init(device:endpointID:queue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/init(device:endpointid:queue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeAcceptedCommandList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeAcceptedCommandList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/readattributeacceptedcommandlist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeAttributeList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeAttributeList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/readattributeattributelist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeClusterRevision(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeClusterRevision(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/readattributeclusterrevision(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeDefaultOTAProviders(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeDefaultOTAProviders"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeDefaultOTAProviders(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeDefaultOTAProvidersWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeDefaultOTAProviders(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/readattributedefaultotaproviders(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeFeatureMap(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeFeatureMap(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/readattributefeaturemap(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeGeneratedCommandList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeGeneratedCommandList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/readattributegeneratedcommandlist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdatePossible(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeUpdatePossible"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdatePossible(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeUpdatePossibleWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeUpdatePossible(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/readattributeupdatepossible(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdateState(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeUpdateState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdateState(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeUpdateStateWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeUpdateState(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/readattributeupdatestate(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdateStateProgress(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeUpdateStateProgress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdateStateProgress(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeUpdateStateProgressWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeUpdateStateProgress(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/readattributeupdatestateprogress(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeAttributeDefaultOTAProviders"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeAttributeDefaultOTAProvidersWithValue:expectedValueInterval:"
        }
      ],
      "role": "symbol",
      "title": "writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/writeattributedefaultotaproviders(withvalue:expectedvalueinterval:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:params:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeAttributeDefaultOTAProviders"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "params"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRWriteParams",
          "text": "MTRWriteParams"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:params:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeAttributeDefaultOTAProvidersWithValue:expectedValueInterval:params:"
        }
      ],
      "role": "symbol",
      "title": "writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:params:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao/writeattributedefaultotaproviders(withvalue:expectedvalueinterval:params:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterOtaSoftwareUpdateRequestor-22dfp": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRClusterOtaSoftwareUpdateRequestor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterOtaSoftwareUpdateRequestor-22dfp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRClusterOtaSoftwareUpdateRequestor"
        }
      ],
      "role": "symbol",
      "title": "MTRClusterOtaSoftwareUpdateRequestor",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterotasoftwareupdaterequestor-22dfp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGenericCluster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGenericCluster"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGenericCluster"
        }
      ],
      "role": "symbol",
      "title": "MTRGenericCluster",
      "type": "topic",
      "url": "/documentation/matter/mtrgenericcluster"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGenericCluster"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterOtaSoftwareUpdateRequestor-22dfp"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/init(device:endpointID:queue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/announceOTAProvider(with:expectedValues:expectedValueInterval:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeAcceptedCommandList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeAttributeList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeClusterRevision(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeDefaultOTAProviders(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeFeatureMap(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeGeneratedCommandList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdatePossible(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdateState(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdateStateProgress(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:params:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRClusterOTASoftwareUpdateRequestor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterOTASoftwareUpdateRequestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterOTASoftwareUpdateRequestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/init(device:endpointID:queue:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/announceOTAProvider(with:expectedValues:expectedValueInterval:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeAcceptedCommandList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeAttributeList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeClusterRevision(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeDefaultOTAProviders(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeFeatureMap(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeGeneratedCommandList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdatePossible(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdateState(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/readAttributeUpdateStateProgress(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterOTASoftwareUpdateRequestor-5qeao/writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:params:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGenericCluster"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterOtaSoftwareUpdateRequestor-22dfp"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRClusterOTASoftwareUpdateRequestor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericCluster",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRGenericCluster",
                    "text": "MTRGenericCluster"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeAcceptedCommandList(with:)/title",
          "value": "readAttributeAcceptedCommandListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeAcceptedCommandList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeUpdateStateProgress(with:)/title",
          "value": "readAttributeUpdateStateProgressWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeUpdateStateProgress(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeUpdateStateProgressWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1init(device:endpointID:queue:)/title",
          "value": "initWithDevice:endpointID:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1init(device:endpointID:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:endpointID:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:params:)/title",
          "value": "writeAttributeDefaultOTAProvidersWithValue:expectedValueInterval:params:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:params:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeAttributeDefaultOTAProvidersWithValue:expectedValueInterval:params:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeGeneratedCommandList(with:)/title",
          "value": "readAttributeGeneratedCommandListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeGeneratedCommandList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao/title",
          "value": "MTRClusterOTASoftwareUpdateRequestor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterOTASoftwareUpdateRequestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterOTASoftwareUpdateRequestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeUpdatePossible(with:)/title",
          "value": "readAttributeUpdatePossibleWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeUpdatePossible(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeUpdatePossibleWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOtaSoftwareUpdateRequestor-22dfp/title",
          "value": "MTRClusterOtaSoftwareUpdateRequestor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOtaSoftwareUpdateRequestor-22dfp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterOtaSoftwareUpdateRequestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOtaSoftwareUpdateRequestor-22dfp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterOtaSoftwareUpdateRequestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1announceOTAProvider(with:expectedValues:expectedValueInterval:completion:)/title",
          "value": "announceOTAProviderWithParams:expectedValues:expectedValueInterval:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1announceOTAProvider(with:expectedValues:expectedValueInterval:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "announceOTAProviderWithParams:expectedValues:expectedValueInterval:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeClusterRevision(with:)/title",
          "value": "readAttributeClusterRevisionWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeClusterRevision(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeDefaultOTAProviders(with:)/title",
          "value": "readAttributeDefaultOTAProvidersWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeDefaultOTAProviders(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeDefaultOTAProvidersWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:)/title",
          "value": "writeAttributeDefaultOTAProvidersWithValue:expectedValueInterval:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1writeAttributeDefaultOTAProviders(withValue:expectedValueInterval:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeAttributeDefaultOTAProvidersWithValue:expectedValueInterval:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/title",
          "value": "MTRGenericCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeFeatureMap(with:)/title",
          "value": "readAttributeFeatureMapWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeFeatureMap(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeUpdateState(with:)/title",
          "value": "readAttributeUpdateStateWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeUpdateState(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeUpdateStateWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeAttributeList(with:)/title",
          "value": "readAttributeAttributeListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterOTASoftwareUpdateRequestor-5qeao~1readAttributeAttributeList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithParams:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrclusterotasoftwareupdaterequestor-5qeao"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
