{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRClusterSmokeCOAlarm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRClusterSmokeCOAlarm"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRClusterSmokeCOAlarm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRClusterSmokeCOAlarm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRClusterSmokeCOAlarm"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRClusterSmokeCOAlarm"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRClusterSmokeCOAlarm"
        }
      ],
      "role": "symbol",
      "title": "MTRClusterSmokeCOAlarm",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/init(device:endpointID:queue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRDevice",
          "text": "MTRDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpointID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/init(device:endpointID:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:endpointID:queue:"
        }
      ],
      "role": "symbol",
      "title": "init(device:endpointID:queue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/init(device:endpointid:queue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeAcceptedCommandList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeAcceptedCommandList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributeacceptedcommandlist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeAttributeList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeAttributeList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributeattributelist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeBatteryAlert(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeBatteryAlert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeBatteryAlert(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeBatteryAlertWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeBatteryAlert(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributebatteryalert(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeCOState(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeCOState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeCOState(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeCOStateWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeCOState(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributecostate(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeClusterRevision(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeClusterRevision(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributeclusterrevision(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeContaminationState(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeContaminationState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeContaminationState(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeContaminationStateWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeContaminationState(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributecontaminationstate(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeDeviceMuted(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeDeviceMuted"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeDeviceMuted(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeDeviceMutedWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeDeviceMuted(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributedevicemuted(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeEndOfServiceAlert(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeEndOfServiceAlert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeEndOfServiceAlert(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeEndOfServiceAlertWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeEndOfServiceAlert(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributeendofservicealert(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeExpiryDate(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeExpiryDate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeExpiryDate(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeExpiryDateWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeExpiryDate(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributeexpirydate(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeExpressedState(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeExpressedState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeExpressedState(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeExpressedStateWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeExpressedState(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributeexpressedstate(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeFeatureMap(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeFeatureMap(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributefeaturemap(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeGeneratedCommandList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeGeneratedCommandList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributegeneratedcommandlist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeHardwareFaultAlert(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeHardwareFaultAlert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeHardwareFaultAlert(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeHardwareFaultAlertWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeHardwareFaultAlert(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributehardwarefaultalert(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeInterconnectCOAlarm(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeInterconnectCOAlarm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeInterconnectCOAlarm(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeInterconnectCOAlarmWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeInterconnectCOAlarm(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributeinterconnectcoalarm(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeInterconnectSmoke(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeInterconnectSmoke"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeInterconnectSmoke(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeInterconnectSmokeAlarmWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeInterconnectSmoke(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributeinterconnectsmoke(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeSmokeSensitivityLevel(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeSmokeSensitivityLevel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeSmokeSensitivityLevel(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeSmokeSensitivityLevelWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeSmokeSensitivityLevel(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributesmokesensitivitylevel(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeSmokeState(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeSmokeState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeSmokeState(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeSmokeStateWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeSmokeState(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributesmokestate(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeTestInProgress(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeTestInProgress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeTestInProgress(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeTestInProgressWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeTestInProgress(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/readattributetestinprogress(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/selfTestRequest(with:expectedValues:expectedValueInterval:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selfTestRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRSmokeCOAlarmClusterSelfTestRequestParams",
          "text": "MTRSmokeCOAlarmClusterSelfTestRequestParams"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "expectedValues"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]]?, "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRStatusCompletion",
          "text": "MTRStatusCompletion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/selfTestRequest(with:expectedValues:expectedValueInterval:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selfTestRequestWithParams:expectedValues:expectedValueInterval:completion:"
        }
      ],
      "role": "symbol",
      "title": "selfTestRequest(with:expectedValues:expectedValueInterval:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/selftestrequest(with:expectedvalues:expectedvalueinterval:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/selfTestRequest(withExpectedValues:expectedValueInterval:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selfTestRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withExpectedValues"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]]?, "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRStatusCompletion",
          "text": "MTRStatusCompletion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/selfTestRequest(withExpectedValues:expectedValueInterval:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selfTestRequestWithExpectedValues:expectedValueInterval:completion:"
        }
      ],
      "role": "symbol",
      "title": "selfTestRequest(withExpectedValues:expectedValueInterval:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/selftestrequest(withexpectedvalues:expectedvalueinterval:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeAttributeSmokeSensitivityLevel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeAttributeSmokeSensitivityLevelWithValue:expectedValueInterval:"
        }
      ],
      "role": "symbol",
      "title": "writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/writeattributesmokesensitivitylevel(withvalue:expectedvalueinterval:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:params:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeAttributeSmokeSensitivityLevel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "params"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRWriteParams",
          "text": "MTRWriteParams"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:params:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeAttributeSmokeSensitivityLevelWithValue:expectedValueInterval:params:"
        }
      ],
      "role": "symbol",
      "title": "writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:params:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustersmokecoalarm/writeattributesmokesensitivitylevel(withvalue:expectedvalueinterval:params:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGenericCluster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGenericCluster"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGenericCluster"
        }
      ],
      "role": "symbol",
      "title": "MTRGenericCluster",
      "type": "topic",
      "url": "/documentation/matter/mtrgenericcluster"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGenericCluster"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/init(device:endpointID:queue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeAcceptedCommandList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeAttributeList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeBatteryAlert(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeCOState(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeClusterRevision(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeContaminationState(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeDeviceMuted(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeEndOfServiceAlert(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeExpiryDate(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeExpressedState(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeFeatureMap(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeGeneratedCommandList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeHardwareFaultAlert(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeInterconnectCOAlarm(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeInterconnectSmoke(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeSmokeSensitivityLevel(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeSmokeState(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeTestInProgress(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/selfTestRequest(with:expectedValues:expectedValueInterval:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/selfTestRequest(withExpectedValues:expectedValueInterval:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:params:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRClusterSmokeCOAlarm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterSmokeCOAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterSmokeCOAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/init(device:endpointID:queue:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeAcceptedCommandList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeAttributeList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeBatteryAlert(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeCOState(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeClusterRevision(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeContaminationState(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeDeviceMuted(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeEndOfServiceAlert(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeExpiryDate(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeExpressedState(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeFeatureMap(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeGeneratedCommandList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeHardwareFaultAlert(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeInterconnectCOAlarm(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeInterconnectSmoke(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeSmokeSensitivityLevel(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeSmokeState(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/readAttributeTestInProgress(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/selfTestRequest(with:expectedValues:expectedValueInterval:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/selfTestRequest(withExpectedValues:expectedValueInterval:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterSmokeCOAlarm/writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:params:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGenericCluster"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRClusterSmokeCOAlarm"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericCluster",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRGenericCluster",
                    "text": "MTRGenericCluster"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:)/title",
          "value": "writeAttributeSmokeSensitivityLevelWithValue:expectedValueInterval:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeAttributeSmokeSensitivityLevelWithValue:expectedValueInterval:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1init(device:endpointID:queue:)/title",
          "value": "initWithDevice:endpointID:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1init(device:endpointID:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:endpointID:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeBatteryAlert(with:)/title",
          "value": "readAttributeBatteryAlertWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeBatteryAlert(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeBatteryAlertWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeHardwareFaultAlert(with:)/title",
          "value": "readAttributeHardwareFaultAlertWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeHardwareFaultAlert(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeHardwareFaultAlertWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeAttributeList(with:)/title",
          "value": "readAttributeAttributeListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeAttributeList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:params:)/title",
          "value": "writeAttributeSmokeSensitivityLevelWithValue:expectedValueInterval:params:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1writeAttributeSmokeSensitivityLevel(withValue:expectedValueInterval:params:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeAttributeSmokeSensitivityLevelWithValue:expectedValueInterval:params:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeFeatureMap(with:)/title",
          "value": "readAttributeFeatureMapWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeFeatureMap(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1selfTestRequest(with:expectedValues:expectedValueInterval:completion:)/title",
          "value": "selfTestRequestWithParams:expectedValues:expectedValueInterval:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1selfTestRequest(with:expectedValues:expectedValueInterval:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selfTestRequestWithParams:expectedValues:expectedValueInterval:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/title",
          "value": "MTRGenericCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeEndOfServiceAlert(with:)/title",
          "value": "readAttributeEndOfServiceAlertWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeEndOfServiceAlert(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeEndOfServiceAlertWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeTestInProgress(with:)/title",
          "value": "readAttributeTestInProgressWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeTestInProgress(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeTestInProgressWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeContaminationState(with:)/title",
          "value": "readAttributeContaminationStateWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeContaminationState(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeContaminationStateWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeSmokeState(with:)/title",
          "value": "readAttributeSmokeStateWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeSmokeState(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeSmokeStateWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeSmokeSensitivityLevel(with:)/title",
          "value": "readAttributeSmokeSensitivityLevelWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeSmokeSensitivityLevel(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeSmokeSensitivityLevelWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm/title",
          "value": "MTRClusterSmokeCOAlarm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterSmokeCOAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterSmokeCOAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1selfTestRequest(withExpectedValues:expectedValueInterval:completion:)/title",
          "value": "selfTestRequestWithExpectedValues:expectedValueInterval:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1selfTestRequest(withExpectedValues:expectedValueInterval:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selfTestRequestWithExpectedValues:expectedValueInterval:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeInterconnectSmoke(with:)/title",
          "value": "readAttributeInterconnectSmokeAlarmWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeInterconnectSmoke(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeInterconnectSmokeAlarmWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeGeneratedCommandList(with:)/title",
          "value": "readAttributeGeneratedCommandListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeGeneratedCommandList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeExpressedState(with:)/title",
          "value": "readAttributeExpressedStateWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeExpressedState(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeExpressedStateWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeAcceptedCommandList(with:)/title",
          "value": "readAttributeAcceptedCommandListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeAcceptedCommandList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeDeviceMuted(with:)/title",
          "value": "readAttributeDeviceMutedWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeDeviceMuted(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeDeviceMutedWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeInterconnectCOAlarm(with:)/title",
          "value": "readAttributeInterconnectCOAlarmWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeInterconnectCOAlarm(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeInterconnectCOAlarmWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeExpiryDate(with:)/title",
          "value": "readAttributeExpiryDateWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeExpiryDate(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeExpiryDateWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeClusterRevision(with:)/title",
          "value": "readAttributeClusterRevisionWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeClusterRevision(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeCOState(with:)/title",
          "value": "readAttributeCOStateWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterSmokeCOAlarm~1readAttributeCOState(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeCOStateWithParams:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrclustersmokecoalarm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrclustersmokecoalarm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
