{
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRContentLauncherParameter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRContentLauncherParameter"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRContentLauncherParameter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRContentLauncherParameter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameter"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameter"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameter"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/actor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/actor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterActor"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.actor",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/actor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/any": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterAny"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.any",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/any"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/channel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channel"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/channel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterChannel"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.channel",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/channel"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/character": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "character"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/character",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterCharacter"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.character",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/character"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/director": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "director"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/director",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterDirector"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.director",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/director"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/episode": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "episode"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/episode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterEpisode"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.episode",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/episode"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/event": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "event"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/event",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterEvent"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.event",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/event"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/franchise": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "franchise"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/franchise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterFranchise"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.franchise",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/franchise"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/genre": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genre"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/genre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterGenre"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.genre",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/genre"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/league": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "league"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/league",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterLeague"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.league",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/league"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/popularity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popularity"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/popularity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterPopularity"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.popularity",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/popularity"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/provider": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/provider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterProvider"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.provider",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/provider"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/season": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "season"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/season",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterSeason"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.season",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/season"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/sport": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sport"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/sport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterSport"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.sport",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/sport"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/sportsTeam": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sportsTeam"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/sportsTeam",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterSportsTeam"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.sportsTeam",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/sportsteam"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/type": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterType"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.type",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/type"
    },
    "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/video": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "video"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRContentLauncherParameterVideo"
        }
      ],
      "role": "symbol",
      "title": "MTRContentLauncherParameter.video",
      "type": "topic",
      "url": "/documentation/matter/mtrcontentlauncherparameter/video"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/actor",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/channel",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/character",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/director",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/event",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/franchise",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/genre",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/league",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/popularity",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/provider",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/sport",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/sportsTeam",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/type",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/video",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/any",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/episode",
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/season"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRContentLauncherParameter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/actor",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/channel",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/character",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/director",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/event",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/franchise",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/genre",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/league",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/popularity",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/provider",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/sport",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/sportsTeam",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/type",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/video",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/any",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/episode",
                "doc://com.apple.matter/documentation/Matter/MTRContentLauncherParameter/season"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRContentLauncherParameter"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1actor/title",
          "value": "MTRContentLauncherParameterActor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1actor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterActor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1genre/title",
          "value": "MTRContentLauncherParameterGenre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1genre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterGenre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1league/title",
          "value": "MTRContentLauncherParameterLeague"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1league/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterLeague"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1popularity/title",
          "value": "MTRContentLauncherParameterPopularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1popularity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterPopularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1character/title",
          "value": "MTRContentLauncherParameterCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1character/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1event/title",
          "value": "MTRContentLauncherParameterEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1event/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1type/title",
          "value": "MTRContentLauncherParameterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1franchise/title",
          "value": "MTRContentLauncherParameterFranchise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1franchise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterFranchise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1sport/title",
          "value": "MTRContentLauncherParameterSport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1sport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterSport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1season/title",
          "value": "MTRContentLauncherParameterSeason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1season/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterSeason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter/title",
          "value": "MTRContentLauncherParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1video/title",
          "value": "MTRContentLauncherParameterVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1any/title",
          "value": "MTRContentLauncherParameterAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1sportsTeam/title",
          "value": "MTRContentLauncherParameterSportsTeam"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1sportsTeam/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterSportsTeam"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1channel/title",
          "value": "MTRContentLauncherParameterChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1channel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1episode/title",
          "value": "MTRContentLauncherParameterEpisode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1episode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterEpisode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1provider/title",
          "value": "MTRContentLauncherParameterProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1provider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1director/title",
          "value": "MTRContentLauncherParameterDirector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRContentLauncherParameter~1director/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRContentLauncherParameterDirector"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrcontentlauncherparameter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrcontentlauncherparameter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
