{
  "abstract": [
    {
      "text": "Cluster Laundry Washer Controls",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "This cluster supports remotely monitoring and controlling the different types of functionality available to a washing device, such as a washing machine.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRClusterLaundryWasherControls",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRClusterLaundryWasherControls"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRClusterLaundryWasherControls"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRClusterLaundryWasherControls"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRClusterLaundryWasherControls"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls": {
      "abstract": [
        {
          "text": "Cluster Laundry Washer Controls",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "This cluster supports remotely monitoring and controlling the different types of functionality available to a washing device, such as a washing machine.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRClusterLaundryWasherControls"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRClusterLaundryWasherControls"
        }
      ],
      "role": "symbol",
      "title": "MTRClusterLaundryWasherControls",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/init(device:endpointID:queue:)": {
      "abstract": [
        {
          "text": "The queue is currently unused, but may be used in the future for calling completions",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "for command invocations if commands are added to this cluster.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRDevice",
          "text": "MTRDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpointID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/init(device:endpointID:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:endpointID:queue:"
        }
      ],
      "role": "symbol",
      "title": "init(device:endpointID:queue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/init(device:endpointid:queue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeAcceptedCommandList(with:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeAcceptedCommandList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/readattributeacceptedcommandlist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeAttributeList(with:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeAttributeList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/readattributeattributelist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeClusterRevision(with:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeClusterRevision(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/readattributeclusterrevision(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeFeatureMap(with:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeFeatureMap(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/readattributefeaturemap(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeGeneratedCommandList(with:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeGeneratedCommandList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/readattributegeneratedcommandlist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeNumberOfRinses(with:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeNumberOfRinses"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeNumberOfRinses(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeNumberOfRinsesWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeNumberOfRinses(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/readattributenumberofrinses(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSpinSpeedCurrent(with:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeSpinSpeedCurrent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSpinSpeedCurrent(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeSpinSpeedCurrentWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeSpinSpeedCurrent(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/readattributespinspeedcurrent(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSpinSpeeds(with:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeSpinSpeeds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSpinSpeeds(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeSpinSpeedsWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeSpinSpeeds(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/readattributespinspeeds(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSupportedRinses(with:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeSupportedRinses"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSupportedRinses(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeSupportedRinsesWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeSupportedRinses(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/readattributesupportedrinses(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeNumberOfRinses(withValue:expectedValueInterval:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeAttributeNumberOfRinses"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeNumberOfRinses(withValue:expectedValueInterval:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeAttributeNumberOfRinsesWithValue:expectedValueInterval:"
        }
      ],
      "role": "symbol",
      "title": "writeAttributeNumberOfRinses(withValue:expectedValueInterval:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/writeattributenumberofrinses(withvalue:expectedvalueinterval:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeNumberOfRinses(withValue:expectedValueInterval:params:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeAttributeNumberOfRinses"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "params"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRWriteParams",
          "text": "MTRWriteParams"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeNumberOfRinses(withValue:expectedValueInterval:params:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeAttributeNumberOfRinsesWithValue:expectedValueInterval:params:"
        }
      ],
      "role": "symbol",
      "title": "writeAttributeNumberOfRinses(withValue:expectedValueInterval:params:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/writeattributenumberofrinses(withvalue:expectedvalueinterval:params:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeAttributeSpinSpeedCurrent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeAttributeSpinSpeedCurrentWithValue:expectedValueInterval:"
        }
      ],
      "role": "symbol",
      "title": "writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/writeattributespinspeedcurrent(withvalue:expectedvalueinterval:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:params:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeAttributeSpinSpeedCurrent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "params"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRWriteParams",
          "text": "MTRWriteParams"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:params:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeAttributeSpinSpeedCurrentWithValue:expectedValueInterval:params:"
        }
      ],
      "role": "symbol",
      "title": "writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:params:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterlaundrywashercontrols/writeattributespinspeedcurrent(withvalue:expectedvalueinterval:params:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGenericCluster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGenericCluster"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGenericCluster"
        }
      ],
      "role": "symbol",
      "title": "MTRGenericCluster",
      "type": "topic",
      "url": "/documentation/matter/mtrgenericcluster"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGenericCluster"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/init(device:endpointID:queue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeAcceptedCommandList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeAttributeList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeClusterRevision(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeFeatureMap(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeGeneratedCommandList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeNumberOfRinses(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSpinSpeedCurrent(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSpinSpeeds(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSupportedRinses(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeNumberOfRinses(withValue:expectedValueInterval:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeNumberOfRinses(withValue:expectedValueInterval:params:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:params:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRClusterLaundryWasherControls"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterLaundryWasherControls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterLaundryWasherControls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/init(device:endpointID:queue:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeAcceptedCommandList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeAttributeList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeClusterRevision(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeFeatureMap(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeGeneratedCommandList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeNumberOfRinses(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSpinSpeedCurrent(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSpinSpeeds(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/readAttributeSupportedRinses(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeNumberOfRinses(withValue:expectedValueInterval:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeNumberOfRinses(withValue:expectedValueInterval:params:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterLaundryWasherControls/writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:params:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGenericCluster"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRClusterLaundryWasherControls"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericCluster",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRGenericCluster",
                    "text": "MTRGenericCluster"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeGeneratedCommandList(with:)/title",
          "value": "readAttributeGeneratedCommandListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeGeneratedCommandList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeSupportedRinses(with:)/title",
          "value": "readAttributeSupportedRinsesWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeSupportedRinses(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeSupportedRinsesWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/title",
          "value": "MTRGenericCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeClusterRevision(with:)/title",
          "value": "readAttributeClusterRevisionWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeClusterRevision(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeAttributeList(with:)/title",
          "value": "readAttributeAttributeListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeAttributeList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:params:)/title",
          "value": "writeAttributeSpinSpeedCurrentWithValue:expectedValueInterval:params:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:params:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeAttributeSpinSpeedCurrentWithValue:expectedValueInterval:params:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1writeAttributeNumberOfRinses(withValue:expectedValueInterval:params:)/title",
          "value": "writeAttributeNumberOfRinsesWithValue:expectedValueInterval:params:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1writeAttributeNumberOfRinses(withValue:expectedValueInterval:params:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeAttributeNumberOfRinsesWithValue:expectedValueInterval:params:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1init(device:endpointID:queue:)/title",
          "value": "initWithDevice:endpointID:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1init(device:endpointID:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:endpointID:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeNumberOfRinses(with:)/title",
          "value": "readAttributeNumberOfRinsesWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeNumberOfRinses(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeNumberOfRinsesWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeAcceptedCommandList(with:)/title",
          "value": "readAttributeAcceptedCommandListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeAcceptedCommandList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls/title",
          "value": "MTRClusterLaundryWasherControls"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterLaundryWasherControls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterLaundryWasherControls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeSpinSpeedCurrent(with:)/title",
          "value": "readAttributeSpinSpeedCurrentWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeSpinSpeedCurrent(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeSpinSpeedCurrentWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeFeatureMap(with:)/title",
          "value": "readAttributeFeatureMapWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeFeatureMap(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1writeAttributeNumberOfRinses(withValue:expectedValueInterval:)/title",
          "value": "writeAttributeNumberOfRinsesWithValue:expectedValueInterval:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1writeAttributeNumberOfRinses(withValue:expectedValueInterval:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeAttributeNumberOfRinsesWithValue:expectedValueInterval:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:)/title",
          "value": "writeAttributeSpinSpeedCurrentWithValue:expectedValueInterval:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1writeAttributeSpinSpeedCurrent(withValue:expectedValueInterval:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeAttributeSpinSpeedCurrentWithValue:expectedValueInterval:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeSpinSpeeds(with:)/title",
          "value": "readAttributeSpinSpeedsWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterLaundryWasherControls~1readAttributeSpinSpeeds(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeSpinSpeedsWithParams:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrclusterlaundrywashercontrols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrclusterlaundrywashercontrols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
