{
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRClusterGeneralDiagnostics",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRClusterGeneralDiagnostics"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRClusterGeneralDiagnostics"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRClusterGeneralDiagnostics"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRClusterGeneralDiagnostics"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRClusterGeneralDiagnostics"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRClusterGeneralDiagnostics"
        }
      ],
      "role": "symbol",
      "title": "MTRClusterGeneralDiagnostics",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/init(device:endpoint:queue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRDevice",
          "text": "MTRDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/init(device:endpoint:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:endpoint:queue:"
        }
      ],
      "role": "symbol",
      "title": "init(device:endpoint:queue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/init(device:endpoint:queue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/init(device:endpointID:queue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRDevice",
          "text": "MTRDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpointID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/init(device:endpointID:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:endpointID:queue:"
        }
      ],
      "role": "symbol",
      "title": "init(device:endpointID:queue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/init(device:endpointid:queue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/payloadTestRequest(with:expectedValues:expectedValueInterval:completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payloadTestRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRGeneralDiagnosticsClusterPayloadTestRequestParams",
          "text": "MTRGeneralDiagnosticsClusterPayloadTestRequestParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "expectedValues"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]]?, "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRGeneralDiagnosticsClusterPayloadTestResponseParams",
          "text": "MTRGeneralDiagnosticsClusterPayloadTestResponseParams"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/payloadTestRequest(with:expectedValues:expectedValueInterval:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "payloadTestRequestWithParams:expectedValues:expectedValueInterval:completion:"
        }
      ],
      "role": "symbol",
      "title": "payloadTestRequest(with:expectedValues:expectedValueInterval:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/payloadtestrequest(with:expectedvalues:expectedvalueinterval:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeAcceptedCommandList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeAcceptedCommandList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAcceptedCommandListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAcceptedCommandList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributeacceptedcommandlist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveHardwareFaults(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeActiveHardwareFaults"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveHardwareFaults(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeActiveHardwareFaultsWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeActiveHardwareFaults(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributeactivehardwarefaults(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveNetworkFaults(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeActiveNetworkFaults"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveNetworkFaults(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeActiveNetworkFaultsWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeActiveNetworkFaults(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributeactivenetworkfaults(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveRadioFaults(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeActiveRadioFaults"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveRadioFaults(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeActiveRadioFaultsWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeActiveRadioFaults(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributeactiveradiofaults(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeAttributeList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeAttributeList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeAttributeList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeAttributeListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeAttributeList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributeattributelist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeBootReason(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeBootReason"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeBootReason(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeBootReasonWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeBootReason(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributebootreason(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeBootReasons(with:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeBootReasons"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeBootReasons(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeBootReasonsWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeBootReasons(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributebootreasons(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeClusterRevision(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeClusterRevision(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeClusterRevisionWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeClusterRevision(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributeclusterrevision(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeFeatureMap(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeFeatureMap(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeFeatureMapWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeFeatureMap(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributefeaturemap(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeGeneratedCommandList(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeGeneratedCommandList(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeGeneratedCommandListWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeGeneratedCommandList(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributegeneratedcommandlist(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeNetworkInterfaces(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeNetworkInterfaces"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeNetworkInterfaces(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeNetworkInterfacesWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeNetworkInterfaces(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributenetworkinterfaces(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeRebootCount(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeRebootCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeRebootCount(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeRebootCountWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeRebootCount(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributerebootcount(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeTestEventTriggersEnabled(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeTestEventTriggersEnabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeTestEventTriggersEnabled(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeTestEventTriggersEnabledWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeTestEventTriggersEnabled(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributetesteventtriggersenabled(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeTotalOperationalHours(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeTotalOperationalHours"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeTotalOperationalHours(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeTotalOperationalHoursWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeTotalOperationalHours(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributetotaloperationalhours(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeUpTime(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeUpTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRReadParams",
          "text": "MTRReadParams"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeUpTime(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeUpTimeWithParams:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeUpTime(with:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/readattributeuptime(with:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/testEventTrigger(with:expectedValues:expectedValueInterval:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testEventTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRGeneralDiagnosticsClusterTestEventTriggerParams",
          "text": "MTRGeneralDiagnosticsClusterTestEventTriggerParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "expectedValues"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]]?, "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRStatusCompletion",
          "text": "MTRStatusCompletion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/testEventTrigger(with:expectedValues:expectedValueInterval:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testEventTriggerWithParams:expectedValues:expectedValueInterval:completion:"
        }
      ],
      "role": "symbol",
      "title": "testEventTrigger(with:expectedValues:expectedValueInterval:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/testeventtrigger(with:expectedvalues:expectedvalueinterval:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/testEventTrigger(with:expectedValues:expectedValueInterval:completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testEventTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRGeneralDiagnosticsClusterTestEventTriggerParams",
          "text": "MTRGeneralDiagnosticsClusterTestEventTriggerParams"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "expectedValues"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]]?, "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRStatusCompletion",
          "text": "MTRStatusCompletion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/testEventTrigger(with:expectedValues:expectedValueInterval:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testEventTriggerWithParams:expectedValues:expectedValueInterval:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "testEventTrigger(with:expectedValues:expectedValueInterval:completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/testeventtrigger(with:expectedvalues:expectedvalueinterval:completionhandler:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/timeSnapshot(with:expectedValues:expectedValueInterval:completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeSnapshot"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRGeneralDiagnosticsClusterTimeSnapshotParams",
          "text": "MTRGeneralDiagnosticsClusterTimeSnapshotParams"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "expectedValues"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]]?, "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRGeneralDiagnosticsClusterTimeSnapshotResponseParams",
          "text": "MTRGeneralDiagnosticsClusterTimeSnapshotResponseParams"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/timeSnapshot(with:expectedValues:expectedValueInterval:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeSnapshotWithParams:expectedValues:expectedValueInterval:completion:"
        }
      ],
      "role": "symbol",
      "title": "timeSnapshot(with:expectedValues:expectedValueInterval:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/timesnapshot(with:expectedvalues:expectedvalueinterval:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/timeSnapshot(withExpectedValues:expectedValueInterval:completion:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeSnapshot"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withExpectedValues"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]]?, "
        },
        {
          "kind": "externalParam",
          "text": "expectedValueInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRGeneralDiagnosticsClusterTimeSnapshotResponseParams",
          "text": "MTRGeneralDiagnosticsClusterTimeSnapshotResponseParams"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/timeSnapshot(withExpectedValues:expectedValueInterval:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeSnapshotWithExpectedValues:expectedValueInterval:completion:"
        }
      ],
      "role": "symbol",
      "title": "timeSnapshot(withExpectedValues:expectedValueInterval:completion:)",
      "type": "topic",
      "url": "/documentation/matter/mtrclustergeneraldiagnostics/timesnapshot(withexpectedvalues:expectedvalueinterval:completion:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGenericCluster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGenericCluster"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGenericCluster"
        }
      ],
      "role": "symbol",
      "title": "MTRGenericCluster",
      "type": "topic",
      "url": "/documentation/matter/mtrgenericcluster"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGenericCluster"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/init(device:endpoint:queue:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/init(device:endpointID:queue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeAcceptedCommandList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveHardwareFaults(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveNetworkFaults(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveRadioFaults(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeAttributeList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeBootReason(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeBootReasons(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeClusterRevision(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeFeatureMap(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeGeneratedCommandList(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeNetworkInterfaces(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeRebootCount(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeTestEventTriggersEnabled(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeTotalOperationalHours(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeUpTime(with:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/testEventTrigger(with:expectedValues:expectedValueInterval:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/testEventTrigger(with:expectedValues:expectedValueInterval:completionHandler:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/payloadTestRequest(with:expectedValues:expectedValueInterval:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/timeSnapshot(with:expectedValues:expectedValueInterval:completion:)",
        "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/timeSnapshot(withExpectedValues:expectedValueInterval:completion:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRClusterGeneralDiagnostics"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterGeneralDiagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterGeneralDiagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/init(device:endpoint:queue:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/init(device:endpointID:queue:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeAcceptedCommandList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveHardwareFaults(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveNetworkFaults(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeActiveRadioFaults(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeAttributeList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeBootReason(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeBootReasons(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeClusterRevision(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeFeatureMap(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeGeneratedCommandList(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeNetworkInterfaces(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeRebootCount(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeTestEventTriggersEnabled(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeTotalOperationalHours(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/readAttributeUpTime(with:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/testEventTrigger(with:expectedValues:expectedValueInterval:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/testEventTrigger(with:expectedValues:expectedValueInterval:completionHandler:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/payloadTestRequest(with:expectedValues:expectedValueInterval:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/timeSnapshot(with:expectedValues:expectedValueInterval:completion:)",
                "doc://com.apple.matter/documentation/Matter/MTRClusterGeneralDiagnostics/timeSnapshot(withExpectedValues:expectedValueInterval:completion:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGenericCluster"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRClusterGeneralDiagnostics"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRGenericCluster",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRGenericCluster",
                    "text": "MTRGenericCluster"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeClusterRevision(with:)/title",
          "value": "readAttributeClusterRevisionWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeClusterRevision(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeClusterRevisionWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeNetworkInterfaces(with:)/title",
          "value": "readAttributeNetworkInterfacesWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeNetworkInterfaces(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeNetworkInterfacesWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeBootReasons(with:)/title",
          "value": "readAttributeBootReasonsWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeBootReasons(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeBootReasonsWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1timeSnapshot(with:expectedValues:expectedValueInterval:completion:)/title",
          "value": "timeSnapshotWithParams:expectedValues:expectedValueInterval:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1timeSnapshot(with:expectedValues:expectedValueInterval:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "timeSnapshotWithParams:expectedValues:expectedValueInterval:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1testEventTrigger(with:expectedValues:expectedValueInterval:completionHandler:)/title",
          "value": "testEventTriggerWithParams:expectedValues:expectedValueInterval:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1testEventTrigger(with:expectedValues:expectedValueInterval:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testEventTriggerWithParams:expectedValues:expectedValueInterval:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1init(device:endpoint:queue:)/title",
          "value": "initWithDevice:endpoint:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1init(device:endpoint:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:endpoint:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeActiveHardwareFaults(with:)/title",
          "value": "readAttributeActiveHardwareFaultsWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeActiveHardwareFaults(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeActiveHardwareFaultsWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics/title",
          "value": "MTRClusterGeneralDiagnostics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterGeneralDiagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterGeneralDiagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/title",
          "value": "MTRGenericCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGenericCluster/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGenericCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeActiveRadioFaults(with:)/title",
          "value": "readAttributeActiveRadioFaultsWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeActiveRadioFaults(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeActiveRadioFaultsWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeActiveNetworkFaults(with:)/title",
          "value": "readAttributeActiveNetworkFaultsWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeActiveNetworkFaults(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeActiveNetworkFaultsWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1timeSnapshot(withExpectedValues:expectedValueInterval:completion:)/title",
          "value": "timeSnapshotWithExpectedValues:expectedValueInterval:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1timeSnapshot(withExpectedValues:expectedValueInterval:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "timeSnapshotWithExpectedValues:expectedValueInterval:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeUpTime(with:)/title",
          "value": "readAttributeUpTimeWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeUpTime(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeUpTimeWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1init(device:endpointID:queue:)/title",
          "value": "initWithDevice:endpointID:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1init(device:endpointID:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:endpointID:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeBootReason(with:)/title",
          "value": "readAttributeBootReasonWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeBootReason(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeBootReasonWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeTotalOperationalHours(with:)/title",
          "value": "readAttributeTotalOperationalHoursWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeTotalOperationalHours(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeTotalOperationalHoursWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeGeneratedCommandList(with:)/title",
          "value": "readAttributeGeneratedCommandListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeGeneratedCommandList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeGeneratedCommandListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeFeatureMap(with:)/title",
          "value": "readAttributeFeatureMapWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeFeatureMap(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeFeatureMapWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1payloadTestRequest(with:expectedValues:expectedValueInterval:completion:)/title",
          "value": "payloadTestRequestWithParams:expectedValues:expectedValueInterval:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1payloadTestRequest(with:expectedValues:expectedValueInterval:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "payloadTestRequestWithParams:expectedValues:expectedValueInterval:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1testEventTrigger(with:expectedValues:expectedValueInterval:completion:)/title",
          "value": "testEventTriggerWithParams:expectedValues:expectedValueInterval:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1testEventTrigger(with:expectedValues:expectedValueInterval:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testEventTriggerWithParams:expectedValues:expectedValueInterval:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeAttributeList(with:)/title",
          "value": "readAttributeAttributeListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeAttributeList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAttributeListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeAcceptedCommandList(with:)/title",
          "value": "readAttributeAcceptedCommandListWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeAcceptedCommandList(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeAcceptedCommandListWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeRebootCount(with:)/title",
          "value": "readAttributeRebootCountWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeRebootCount(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeRebootCountWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeTestEventTriggersEnabled(with:)/title",
          "value": "readAttributeTestEventTriggersEnabledWithParams:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterGeneralDiagnostics~1readAttributeTestEventTriggersEnabled(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAttributeTestEventTriggersEnabledWithParams:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrclustergeneraldiagnostics"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrclustergeneraldiagnostics"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
