{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRCarbonMonoxideConcentrationMeasurementLevelValue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
        }
      ],
      "role": "symbol",
      "title": "MTRCarbonMonoxideConcentrationMeasurementLevelValue",
      "type": "topic",
      "url": "/documentation/matter/mtrcarbonmonoxideconcentrationmeasurementlevelvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/critical": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "critical"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/critical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValueCritical"
        }
      ],
      "role": "symbol",
      "title": "MTRCarbonMonoxideConcentrationMeasurementLevelValue.critical",
      "type": "topic",
      "url": "/documentation/matter/mtrcarbonmonoxideconcentrationmeasurementlevelvalue/critical"
    },
    "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/high": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValueHigh"
        }
      ],
      "role": "symbol",
      "title": "MTRCarbonMonoxideConcentrationMeasurementLevelValue.high",
      "type": "topic",
      "url": "/documentation/matter/mtrcarbonmonoxideconcentrationmeasurementlevelvalue/high"
    },
    "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrcarbonmonoxideconcentrationmeasurementlevelvalue/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/low": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValueLow"
        }
      ],
      "role": "symbol",
      "title": "MTRCarbonMonoxideConcentrationMeasurementLevelValue.low",
      "type": "topic",
      "url": "/documentation/matter/mtrcarbonmonoxideconcentrationmeasurementlevelvalue/low"
    },
    "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/medium": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValueMedium"
        }
      ],
      "role": "symbol",
      "title": "MTRCarbonMonoxideConcentrationMeasurementLevelValue.medium",
      "type": "topic",
      "url": "/documentation/matter/mtrcarbonmonoxideconcentrationmeasurementlevelvalue/medium"
    },
    "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValueUnknown"
        }
      ],
      "role": "symbol",
      "title": "MTRCarbonMonoxideConcentrationMeasurementLevelValue.unknown",
      "type": "topic",
      "url": "/documentation/matter/mtrcarbonmonoxideconcentrationmeasurementlevelvalue/unknown"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/critical",
        "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/high",
        "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/low",
        "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/medium",
        "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/unknown"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/critical",
                "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/high",
                "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/low",
                "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/medium",
                "doc://com.apple.matter/documentation/Matter/MTRCarbonMonoxideConcentrationMeasurementLevelValue/unknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue~1high/title",
          "value": "MTRCarbonMonoxideConcentrationMeasurementLevelValueHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValueHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue~1unknown/title",
          "value": "MTRCarbonMonoxideConcentrationMeasurementLevelValueUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValueUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue~1low/title",
          "value": "MTRCarbonMonoxideConcentrationMeasurementLevelValueLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValueLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue~1critical/title",
          "value": "MTRCarbonMonoxideConcentrationMeasurementLevelValueCritical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue~1critical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValueCritical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue/title",
          "value": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue~1medium/title",
          "value": "MTRCarbonMonoxideConcentrationMeasurementLevelValueMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCarbonMonoxideConcentrationMeasurementLevelValue~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCarbonMonoxideConcentrationMeasurementLevelValueMedium"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrcarbonmonoxideconcentrationmeasurementlevelvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrcarbonmonoxideconcentrationmeasurementlevelvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
