{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRDoorLockOperationSource",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDoorLockDlOperationSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDoorLockDlOperationSource"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDoorLockDlOperationSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRDoorLockOperationSource",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRDoorLockOperationSource",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRDoorLockOperationSource",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "Please use MTRDoorLockOperationSource",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRDoorLockOperationSource",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRDoorLockOperationSource",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "Please use MTRDoorLockOperationSource",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRDoorLockDlOperationSource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSource"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSource"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/RFID": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RFID"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/RFID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSourceRFID"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource.RFID",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/rfid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/auto": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSourceAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/biometric": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometric"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/biometric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSourceBiometric"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource.biometric",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/biometric"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/button": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "button"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/button",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSourceButton"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource.button",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/button"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/keypad": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/keypad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSourceKeypad"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource.keypad",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/keypad"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/manual": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manual"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/manual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSourceManual"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource.manual",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/manual"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/proprietaryRemote": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proprietaryRemote"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/proprietaryRemote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSourceProprietaryRemote"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource.proprietaryRemote",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/proprietaryremote"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/remote": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remote"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/remote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSourceRemote"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource.remote",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/remote"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/schedule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "schedule"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/schedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSourceSchedule"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource.schedule",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/schedule"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/unspecified": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlOperationSourceUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlOperationSource.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdloperationsource/unspecified"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/RFID",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/auto",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/biometric",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/button",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/keypad",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/manual",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/proprietaryRemote",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/remote",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/schedule",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/unspecified"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDoorLockDlOperationSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/RFID",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/auto",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/biometric",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/button",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/keypad",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/manual",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/proprietaryRemote",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/remote",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/schedule",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlOperationSource/unspecified"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDoorLockDlOperationSource"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRDoorLockOperationSource",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1keypad/title",
          "value": "MTRDoorLockDlOperationSourceKeypad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1keypad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSourceKeypad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1remote/title",
          "value": "MTRDoorLockDlOperationSourceRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1remote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSourceRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1button/title",
          "value": "MTRDoorLockDlOperationSourceButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1button/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSourceButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1unspecified/title",
          "value": "MTRDoorLockDlOperationSourceUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSourceUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1proprietaryRemote/title",
          "value": "MTRDoorLockDlOperationSourceProprietaryRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1proprietaryRemote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSourceProprietaryRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1schedule/title",
          "value": "MTRDoorLockDlOperationSourceSchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1schedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSourceSchedule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1manual/title",
          "value": "MTRDoorLockDlOperationSourceManual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1manual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSourceManual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource/title",
          "value": "MTRDoorLockDlOperationSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1biometric/title",
          "value": "MTRDoorLockDlOperationSourceBiometric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1biometric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSourceBiometric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1auto/title",
          "value": "MTRDoorLockDlOperationSourceAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSourceAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1RFID/title",
          "value": "MTRDoorLockDlOperationSourceRFID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlOperationSource~1RFID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlOperationSourceRFID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdoorlockdloperationsource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdoorlockdloperationsource"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
