{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDoorLockDlManualOperationEventMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDoorLockDlManualOperationEventMask"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDoorLockDlManualOperationEventMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTRDoorLockDlManualOperationEventMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMask"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlManualOperationEventMask",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/autoLock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/autoLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskAutoLock"
        }
      ],
      "role": "symbol",
      "title": "autoLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/autolock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/keyLock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/keyLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskKeyLock"
        }
      ],
      "role": "symbol",
      "title": "keyLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/keylock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/keyUnlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyUnlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/keyUnlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskKeyUnlock"
        }
      ],
      "role": "symbol",
      "title": "keyUnlock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/keyunlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/manualLock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manualLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/manualLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskManualLock"
        }
      ],
      "role": "symbol",
      "title": "manualLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/manuallock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/manualUnlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manualUnlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/manualUnlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskManualUnlock"
        }
      ],
      "role": "symbol",
      "title": "manualUnlock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/manualunlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/oneTouchLock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneTouchLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/oneTouchLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskOneTouchLock"
        }
      ],
      "role": "symbol",
      "title": "oneTouchLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/onetouchlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/scheduleLock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/scheduleLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskScheduleLock"
        }
      ],
      "role": "symbol",
      "title": "scheduleLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/schedulelock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/scheduleUnlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleUnlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/scheduleUnlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskScheduleUnlock"
        }
      ],
      "role": "symbol",
      "title": "scheduleUnlock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/scheduleunlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/thumbturnLock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbturnLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/thumbturnLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskThumbturnLock"
        }
      ],
      "role": "symbol",
      "title": "thumbturnLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/thumbturnlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/thumbturnUnlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbturnUnlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/thumbturnUnlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskThumbturnUnlock"
        }
      ],
      "role": "symbol",
      "title": "thumbturnUnlock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/thumbturnunlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockDlManualOperationEventMask",
          "text": "MTRDoorLockDlManualOperationEventMask"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlManualOperationEventMaskUnknown"
        }
      ],
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlmanualoperationeventmask/unknown"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/autoLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/keyLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/keyUnlock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/manualLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/manualUnlock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/oneTouchLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/scheduleLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/scheduleUnlock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/thumbturnLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/thumbturnUnlock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/unknown"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDoorLockDlManualOperationEventMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/autoLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/keyLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/keyUnlock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/manualLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/manualUnlock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/oneTouchLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/scheduleLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/scheduleUnlock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/thumbturnLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/thumbturnUnlock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlManualOperationEventMask/unknown"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDoorLockDlManualOperationEventMask"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask/title",
          "value": "MTRDoorLockDlManualOperationEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1keyUnlock/title",
          "value": "MTRDoorLockDlManualOperationEventMaskKeyUnlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1keyUnlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskKeyUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1scheduleUnlock/title",
          "value": "MTRDoorLockDlManualOperationEventMaskScheduleUnlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1scheduleUnlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskScheduleUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1thumbturnUnlock/title",
          "value": "MTRDoorLockDlManualOperationEventMaskThumbturnUnlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1thumbturnUnlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskThumbturnUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1keyLock/title",
          "value": "MTRDoorLockDlManualOperationEventMaskKeyLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1keyLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskKeyLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1unknown/title",
          "value": "MTRDoorLockDlManualOperationEventMaskUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1scheduleLock/title",
          "value": "MTRDoorLockDlManualOperationEventMaskScheduleLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1scheduleLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskScheduleLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1thumbturnLock/title",
          "value": "MTRDoorLockDlManualOperationEventMaskThumbturnLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1thumbturnLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskThumbturnLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1manualLock/title",
          "value": "MTRDoorLockDlManualOperationEventMaskManualLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1manualLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskManualLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1autoLock/title",
          "value": "MTRDoorLockDlManualOperationEventMaskAutoLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1autoLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskAutoLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1manualUnlock/title",
          "value": "MTRDoorLockDlManualOperationEventMaskManualUnlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1manualUnlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskManualUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1oneTouchLock/title",
          "value": "MTRDoorLockDlManualOperationEventMaskOneTouchLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlManualOperationEventMask~1oneTouchLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlManualOperationEventMaskOneTouchLock"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdoorlockdlmanualoperationeventmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdoorlockdlmanualoperationeventmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
