{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDoorLockLockDataType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDoorLockLockDataType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDoorLockLockDataType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRDoorLockLockDataType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataType"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/PIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PIN"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/PIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypePIN"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.PIN",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/pin"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/RFID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RFID"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/RFID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeRFID"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.RFID",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/rfid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroCredentialIssuerKey": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aliroCredentialIssuerKey"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroCredentialIssuerKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeAliroCredentialIssuerKey"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.aliroCredentialIssuerKey",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/alirocredentialissuerkey"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroEvictableEndpointKey": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aliroEvictableEndpointKey"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroEvictableEndpointKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeAliroEvictableEndpointKey"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.aliroEvictableEndpointKey",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/aliroevictableendpointkey"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroNonEvictableEndpointKey": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aliroNonEvictableEndpointKey"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroNonEvictableEndpointKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeAliroNonEvictableEndpointKey"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.aliroNonEvictableEndpointKey",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/alirononevictableendpointkey"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/face": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "face"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/face",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeFace"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.face",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/face"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/fingerVein": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fingerVein"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/fingerVein",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeFingerVein"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.fingerVein",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/fingervein"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/fingerprint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fingerprint"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/fingerprint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeFingerprint"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.fingerprint",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/fingerprint"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/holidaySchedule": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "holidaySchedule"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/holidaySchedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeHolidaySchedule"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.holidaySchedule",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/holidayschedule"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/programmingCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "programmingCode"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/programmingCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeProgrammingCode"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.programmingCode",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/programmingcode"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/unspecified"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/userIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userIndex"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/userIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeUserIndex"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.userIndex",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/userindex"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/weekDaySchedule": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weekDaySchedule"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/weekDaySchedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeWeekDaySchedule"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.weekDaySchedule",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/weekdayschedule"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/yearDaySchedule": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yearDaySchedule"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/yearDaySchedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockLockDataTypeYearDaySchedule"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockLockDataType.yearDaySchedule",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlocklockdatatype/yeardayschedule"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/PIN",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/RFID",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/face",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/fingerVein",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/fingerprint",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/holidaySchedule",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/programmingCode",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/unspecified",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/userIndex",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/weekDaySchedule",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/yearDaySchedule",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroCredentialIssuerKey",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroEvictableEndpointKey",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroNonEvictableEndpointKey"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDoorLockLockDataType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/PIN",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/RFID",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/face",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/fingerVein",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/fingerprint",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/holidaySchedule",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/programmingCode",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/unspecified",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/userIndex",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/weekDaySchedule",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/yearDaySchedule",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroCredentialIssuerKey",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroEvictableEndpointKey",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockLockDataType/aliroNonEvictableEndpointKey"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDoorLockLockDataType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1fingerprint/title",
          "value": "MTRDoorLockLockDataTypeFingerprint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1fingerprint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeFingerprint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType/title",
          "value": "MTRDoorLockLockDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1face/title",
          "value": "MTRDoorLockLockDataTypeFace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1face/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeFace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1aliroEvictableEndpointKey/title",
          "value": "MTRDoorLockLockDataTypeAliroEvictableEndpointKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1aliroEvictableEndpointKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeAliroEvictableEndpointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1yearDaySchedule/title",
          "value": "MTRDoorLockLockDataTypeYearDaySchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1yearDaySchedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeYearDaySchedule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1RFID/title",
          "value": "MTRDoorLockLockDataTypeRFID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1RFID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeRFID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1holidaySchedule/title",
          "value": "MTRDoorLockLockDataTypeHolidaySchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1holidaySchedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeHolidaySchedule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1aliroNonEvictableEndpointKey/title",
          "value": "MTRDoorLockLockDataTypeAliroNonEvictableEndpointKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1aliroNonEvictableEndpointKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeAliroNonEvictableEndpointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1programmingCode/title",
          "value": "MTRDoorLockLockDataTypeProgrammingCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1programmingCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeProgrammingCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1fingerVein/title",
          "value": "MTRDoorLockLockDataTypeFingerVein"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1fingerVein/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeFingerVein"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1PIN/title",
          "value": "MTRDoorLockLockDataTypePIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1PIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypePIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1unspecified/title",
          "value": "MTRDoorLockLockDataTypeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1userIndex/title",
          "value": "MTRDoorLockLockDataTypeUserIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1userIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeUserIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1aliroCredentialIssuerKey/title",
          "value": "MTRDoorLockLockDataTypeAliroCredentialIssuerKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1aliroCredentialIssuerKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeAliroCredentialIssuerKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1weekDaySchedule/title",
          "value": "MTRDoorLockLockDataTypeWeekDaySchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockLockDataType~1weekDaySchedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockLockDataTypeWeekDaySchedule"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdoorlocklockdatatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdoorlocklockdatatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
