{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRDoorLockAlarmCode",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDoorLockDlAlarmCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDoorLockDlAlarmCode"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDoorLockDlAlarmCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRDoorLockAlarmCode",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRDoorLockAlarmCode",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRDoorLockAlarmCode",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "Please use MTRDoorLockAlarmCode",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRDoorLockAlarmCode",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRDoorLockAlarmCode",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "Please use MTRDoorLockAlarmCode",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRDoorLockDlAlarmCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlAlarmCode"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlAlarmCode"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlAlarmCode",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlalarmcode"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/doorAjar": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doorAjar"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/doorAjar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlAlarmCodeDoorAjar"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlAlarmCode.doorAjar",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlalarmcode/doorajar"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/doorForcedOpen": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doorForcedOpen"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/doorForcedOpen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlAlarmCodeDoorForcedOpen"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlAlarmCode.doorForcedOpen",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlalarmcode/doorforcedopen"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/forcedUser": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forcedUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/forcedUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlAlarmCodeForcedUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlAlarmCode.forcedUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlalarmcode/forceduser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/frontEsceutcheonRemoved": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontEsceutcheonRemoved"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/frontEsceutcheonRemoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlAlarmCodeFrontEsceutcheonRemoved"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlAlarmCode.frontEsceutcheonRemoved",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlalarmcode/frontesceutcheonremoved"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlalarmcode/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockFactoryReset": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockFactoryReset"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockFactoryReset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlAlarmCodeLockFactoryReset"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlAlarmCode.lockFactoryReset",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlalarmcode/lockfactoryreset"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockJammed": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockJammed"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockJammed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlAlarmCodeLockJammed"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlAlarmCode.lockJammed",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlalarmcode/lockjammed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockRadioPowerCycled": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockRadioPowerCycled"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockRadioPowerCycled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlAlarmCodeLockRadioPowerCycled"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlAlarmCode.lockRadioPowerCycled",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlalarmcode/lockradiopowercycled"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/wrongCodeEntryLimit": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wrongCodeEntryLimit"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/wrongCodeEntryLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockDlAlarmCodeWrongCodeEntryLimit"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockDlAlarmCode.wrongCodeEntryLimit",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockdlalarmcode/wrongcodeentrylimit"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/doorAjar",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/doorForcedOpen",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/forcedUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/frontEsceutcheonRemoved",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockFactoryReset",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockJammed",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockRadioPowerCycled",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/wrongCodeEntryLimit"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDoorLockDlAlarmCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/doorAjar",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/doorForcedOpen",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/forcedUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/frontEsceutcheonRemoved",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockFactoryReset",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockJammed",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/lockRadioPowerCycled",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockDlAlarmCode/wrongCodeEntryLimit"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDoorLockDlAlarmCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRDoorLockAlarmCode",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1frontEsceutcheonRemoved/title",
          "value": "MTRDoorLockDlAlarmCodeFrontEsceutcheonRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1frontEsceutcheonRemoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCodeFrontEsceutcheonRemoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode/title",
          "value": "MTRDoorLockDlAlarmCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1doorForcedOpen/title",
          "value": "MTRDoorLockDlAlarmCodeDoorForcedOpen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1doorForcedOpen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCodeDoorForcedOpen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1lockRadioPowerCycled/title",
          "value": "MTRDoorLockDlAlarmCodeLockRadioPowerCycled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1lockRadioPowerCycled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCodeLockRadioPowerCycled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1lockJammed/title",
          "value": "MTRDoorLockDlAlarmCodeLockJammed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1lockJammed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCodeLockJammed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1lockFactoryReset/title",
          "value": "MTRDoorLockDlAlarmCodeLockFactoryReset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1lockFactoryReset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCodeLockFactoryReset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1wrongCodeEntryLimit/title",
          "value": "MTRDoorLockDlAlarmCodeWrongCodeEntryLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1wrongCodeEntryLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCodeWrongCodeEntryLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1doorAjar/title",
          "value": "MTRDoorLockDlAlarmCodeDoorAjar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1doorAjar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCodeDoorAjar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1forcedUser/title",
          "value": "MTRDoorLockDlAlarmCodeForcedUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockDlAlarmCode~1forcedUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockDlAlarmCodeForcedUser"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdoorlockdlalarmcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdoorlockdlalarmcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
