{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDeviceEnergyManagementModeModeTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDeviceEnergyManagementModeModeTag"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDeviceEnergyManagementModeModeTag"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRDeviceEnergyManagementModeModeTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTag"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTag"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/auto": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/day": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "day"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/day",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagDay"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.day",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/day"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/deviceOptimization": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOptimization"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/deviceOptimization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagDeviceOptimization"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.deviceOptimization",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/deviceoptimization"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/gridOptimization": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gridOptimization"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/gridOptimization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagGridOptimization"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.gridOptimization",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/gridoptimization"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/localOptimization": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localOptimization"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/localOptimization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagLocalOptimization"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.localOptimization",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/localoptimization"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/lowEnergy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowEnergy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/lowEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagLowEnergy"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.lowEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/lowenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/lowNoise": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowNoise"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/lowNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagLowNoise"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.lowNoise",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/lownoise"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/max": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagMax"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.max",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/max"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/min": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagMin"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.min",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/min"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/night": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "night"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/night",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagNight"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.night",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/night"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/noOptimization": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noOptimization"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/noOptimization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagNoOptimization"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.noOptimization",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/nooptimization"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/quick": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quick"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/quick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagQuick"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.quick",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/quick"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/quiet": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quiet"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/quiet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagQuiet"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.quiet",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/quiet"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/vacation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vacation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/vacation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementModeModeTagVacation"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementModeModeTag.vacation",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementmodemodetag/vacation"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/auto",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/day",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/deviceOptimization",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/gridOptimization",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/localOptimization",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/lowEnergy",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/lowNoise",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/max",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/min",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/night",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/noOptimization",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/quick",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/quiet",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/vacation"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDeviceEnergyManagementModeModeTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/auto",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/day",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/deviceOptimization",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/gridOptimization",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/localOptimization",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/lowEnergy",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/lowNoise",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/max",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/min",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/night",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/noOptimization",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/quick",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/quiet",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementModeModeTag/vacation"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDeviceEnergyManagementModeModeTag"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1vacation/title",
          "value": "MTRDeviceEnergyManagementModeModeTagVacation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1vacation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagVacation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1day/title",
          "value": "MTRDeviceEnergyManagementModeModeTagDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1day/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag/title",
          "value": "MTRDeviceEnergyManagementModeModeTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1lowEnergy/title",
          "value": "MTRDeviceEnergyManagementModeModeTagLowEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1lowEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagLowEnergy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1auto/title",
          "value": "MTRDeviceEnergyManagementModeModeTagAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1localOptimization/title",
          "value": "MTRDeviceEnergyManagementModeModeTagLocalOptimization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1localOptimization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagLocalOptimization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1min/title",
          "value": "MTRDeviceEnergyManagementModeModeTagMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1night/title",
          "value": "MTRDeviceEnergyManagementModeModeTagNight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1night/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagNight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1gridOptimization/title",
          "value": "MTRDeviceEnergyManagementModeModeTagGridOptimization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1gridOptimization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagGridOptimization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1lowNoise/title",
          "value": "MTRDeviceEnergyManagementModeModeTagLowNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1lowNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagLowNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1noOptimization/title",
          "value": "MTRDeviceEnergyManagementModeModeTagNoOptimization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1noOptimization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagNoOptimization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1max/title",
          "value": "MTRDeviceEnergyManagementModeModeTagMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1quiet/title",
          "value": "MTRDeviceEnergyManagementModeModeTagQuiet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1quiet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagQuiet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1quick/title",
          "value": "MTRDeviceEnergyManagementModeModeTagQuick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1quick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagQuick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1deviceOptimization/title",
          "value": "MTRDeviceEnergyManagementModeModeTagDeviceOptimization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementModeModeTag~1deviceOptimization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementModeModeTagDeviceOptimization"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdeviceenergymanagementmodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdeviceenergymanagementmodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
