{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDoorLockUserType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDoorLockUserType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDoorLockUserType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRDoorLockUserType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserType"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/disposableUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disposableUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/disposableUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeDisposableUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.disposableUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/disposableuser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/expiringUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expiringUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/expiringUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeExpiringUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.expiringUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/expiringuser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/forcedUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forcedUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/forcedUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeForcedUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.forcedUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/forceduser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/masterUser": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "masterUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockUserType",
          "text": "MTRDoorLockUserType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/masterUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeMasterUser"
        }
      ],
      "role": "symbol",
      "title": "masterUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/masteruser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/nonAccessUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonAccessUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/nonAccessUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeNonAccessUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.nonAccessUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/nonaccessuser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/notSupported": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeNotSupported"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.notSupported",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/notsupported"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/programmingUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "programmingUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/programmingUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeProgrammingUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.programmingUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/programminguser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/remoteOnlyUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteOnlyUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/remoteOnlyUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeRemoteOnlyUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.remoteOnlyUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/remoteonlyuser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/scheduleRestrictedUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleRestrictedUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/scheduleRestrictedUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeScheduleRestrictedUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.scheduleRestrictedUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/schedulerestricteduser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/unrestricted": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unrestricted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockUserType",
          "text": "MTRDoorLockUserType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/unrestricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeUnrestricted"
        }
      ],
      "role": "symbol",
      "title": "unrestricted",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/unrestricted"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/unrestrictedUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unrestrictedUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/unrestrictedUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeUnrestrictedUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.unrestrictedUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/unrestricteduser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/weekDayScheduleUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weekDayScheduleUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/weekDayScheduleUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeWeekDayScheduleUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.weekDayScheduleUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/weekdayscheduleuser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/yearDayScheduleUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yearDayScheduleUser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/yearDayScheduleUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockUserTypeYearDayScheduleUser"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockUserType.yearDayScheduleUser",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockusertype/yeardayscheduleuser"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/disposableUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/expiringUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/forcedUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/nonAccessUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/notSupported",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/programmingUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/remoteOnlyUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/scheduleRestrictedUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/unrestrictedUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/weekDayScheduleUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/yearDayScheduleUser"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/masterUser",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/unrestricted"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDoorLockUserType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/disposableUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/expiringUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/forcedUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/nonAccessUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/notSupported",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/programmingUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/remoteOnlyUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/scheduleRestrictedUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/unrestrictedUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/weekDayScheduleUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/yearDayScheduleUser"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/masterUser",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockUserType/unrestricted"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDoorLockUserType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1remoteOnlyUser/title",
          "value": "MTRDoorLockUserTypeRemoteOnlyUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1remoteOnlyUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeRemoteOnlyUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1expiringUser/title",
          "value": "MTRDoorLockUserTypeExpiringUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1expiringUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeExpiringUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1nonAccessUser/title",
          "value": "MTRDoorLockUserTypeNonAccessUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1nonAccessUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeNonAccessUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1unrestrictedUser/title",
          "value": "MTRDoorLockUserTypeUnrestrictedUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1unrestrictedUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeUnrestrictedUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1programmingUser/title",
          "value": "MTRDoorLockUserTypeProgrammingUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1programmingUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeProgrammingUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1forcedUser/title",
          "value": "MTRDoorLockUserTypeForcedUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1forcedUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeForcedUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1yearDayScheduleUser/title",
          "value": "MTRDoorLockUserTypeYearDayScheduleUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1yearDayScheduleUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeYearDayScheduleUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1notSupported/title",
          "value": "MTRDoorLockUserTypeNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1unrestricted/title",
          "value": "MTRDoorLockUserTypeUnrestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1unrestricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeUnrestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType/title",
          "value": "MTRDoorLockUserType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1weekDayScheduleUser/title",
          "value": "MTRDoorLockUserTypeWeekDayScheduleUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1weekDayScheduleUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeWeekDayScheduleUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1masterUser/title",
          "value": "MTRDoorLockUserTypeMasterUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1masterUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeMasterUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1scheduleRestrictedUser/title",
          "value": "MTRDoorLockUserTypeScheduleRestrictedUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1scheduleRestrictedUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeScheduleRestrictedUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1disposableUser/title",
          "value": "MTRDoorLockUserTypeDisposableUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockUserType~1disposableUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockUserTypeDisposableUser"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdoorlockusertype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdoorlockusertype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
