{
  "abstract": [
    {
      "text": "Class that configures how MTRDevice objects persist their attributes to storage, so as to not",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "overwhelm the underlying storage system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRDeviceStorageBehaviorConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDeviceStorageBehaviorConfiguration"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDeviceStorageBehaviorConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRDeviceStorageBehaviorConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDeviceStorageBehaviorConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration": {
      "abstract": [
        {
          "text": "Class that configures how MTRDevice objects persist their attributes to storage, so as to not",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "overwhelm the underlying storage system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceStorageBehaviorConfiguration"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceStorageBehaviorConfiguration"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceStorageBehaviorConfiguration",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/deviceReportingExcessivelyIntervalThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceReportingExcessivelyIntervalThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/deviceReportingExcessivelyIntervalThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceReportingExcessivelyIntervalThreshold"
        }
      ],
      "role": "symbol",
      "title": "deviceReportingExcessivelyIntervalThreshold",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/devicereportingexcessivelyintervalthreshold"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/disableStorageBehaviorOptimization": {
      "abstract": [
        {
          "text": "If disableStorageBehaviorOptimization is set to YES, then all the waiting mechanism as described above",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableStorageBehaviorOptimization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/disableStorageBehaviorOptimization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableStorageBehaviorOptimization"
        }
      ],
      "role": "symbol",
      "title": "disableStorageBehaviorOptimization",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/disablestoragebehavioroptimization"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/init(reportToPersistenceDelayTime:reportToPersistenceDelayTimeMax:recentReportTimesMaxCount:timeBetweenReportsTooShortThreshold:timeBetweenReportsTooShortMinThreshold:reportToPersistenceDelayMaxMultiplier:deviceReportingExcessivelyIntervalThreshold:)": {
      "abstract": [
        {
          "text": "Create configuration with specified values. See description below for details, and the list of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "properties below for valid ranges of these values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reportToPersistenceDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reportToPersistenceDelayTimeMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "recentReportTimesMaxCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeBetweenReportsTooShortThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeBetweenReportsTooShortMinThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reportToPersistenceDelayMaxMultiplier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deviceReportingExcessivelyIntervalThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/init(reportToPersistenceDelayTime:reportToPersistenceDelayTimeMax:recentReportTimesMaxCount:timeBetweenReportsTooShortThreshold:timeBetweenReportsTooShortMinThreshold:reportToPersistenceDelayMaxMultiplier:deviceReportingExcessivelyIntervalThreshold:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurationWithReportToPersistenceDelayTime:reportToPersistenceDelayTimeMax:recentReportTimesMaxCount:timeBetweenReportsTooShortThreshold:timeBetweenReportsTooShortMinThreshold:reportToPersistenceDelayMaxMultiplier:deviceReportingExcessivelyIntervalThreshold:"
        }
      ],
      "role": "symbol",
      "title": "init(reportToPersistenceDelayTime:reportToPersistenceDelayTimeMax:recentReportTimesMaxCount:timeBetweenReportsTooShortThreshold:timeBetweenReportsTooShortMinThreshold:reportToPersistenceDelayMaxMultiplier:deviceReportingExcessivelyIntervalThreshold:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/init(reporttopersistencedelaytime:reporttopersistencedelaytimemax:recentreporttimesmaxcount:timebetweenreportstooshortthreshold:timebetweenreportstooshortminthreshold:reporttopersistencedelaymaxmultiplier:devicereportingexcessivelyintervalt-6xgqf"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/recentReportTimesMaxCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recentReportTimesMaxCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/recentReportTimesMaxCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recentReportTimesMaxCount"
        }
      ],
      "role": "symbol",
      "title": "recentReportTimesMaxCount",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/recentreporttimesmaxcount"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayMaxMultiplier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportToPersistenceDelayMaxMultiplier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayMaxMultiplier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportToPersistenceDelayMaxMultiplier"
        }
      ],
      "role": "symbol",
      "title": "reportToPersistenceDelayMaxMultiplier",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/reporttopersistencedelaymaxmultiplier"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayTime": {
      "abstract": [
        {
          "text": "If any of these properties are set to be out of the documented limits, these default values will",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "be used to replace all of them:",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportToPersistenceDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportToPersistenceDelayTime"
        }
      ],
      "role": "symbol",
      "title": "reportToPersistenceDelayTime",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/reporttopersistencedelaytime"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayTimeMax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportToPersistenceDelayTimeMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayTimeMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportToPersistenceDelayTimeMax"
        }
      ],
      "role": "symbol",
      "title": "reportToPersistenceDelayTimeMax",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/reporttopersistencedelaytimemax"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/timeBetweenReportsTooShortMinThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeBetweenReportsTooShortMinThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/timeBetweenReportsTooShortMinThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeBetweenReportsTooShortMinThreshold"
        }
      ],
      "role": "symbol",
      "title": "timeBetweenReportsTooShortMinThreshold",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/timebetweenreportstooshortminthreshold"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/timeBetweenReportsTooShortThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeBetweenReportsTooShortThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/timeBetweenReportsTooShortThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeBetweenReportsTooShortThreshold"
        }
      ],
      "role": "symbol",
      "title": "timeBetweenReportsTooShortThreshold",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/timebetweenreportstooshortthreshold"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/withDefaultStorageBehavior()": {
      "abstract": [
        {
          "text": "Create configuration with a default set of values. See description below for details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withDefaultStorageBehavior"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/withDefaultStorageBehavior()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurationWithDefaultStorageBehavior"
        }
      ],
      "role": "symbol",
      "title": "withDefaultStorageBehavior()",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/withdefaultstoragebehavior()"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/withStorageBehaviorOptimizationDisabled()": {
      "abstract": [
        {
          "text": "Create configuration that disables storage behavior optimizations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withStorageBehaviorOptimizationDisabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/withStorageBehaviorOptimizationDisabled()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurationWithStorageBehaviorOptimizationDisabled"
        }
      ],
      "role": "symbol",
      "title": "withStorageBehaviorOptimizationDisabled()",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicestoragebehaviorconfiguration/withstoragebehavioroptimizationdisabled()"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/init(reportToPersistenceDelayTime:reportToPersistenceDelayTimeMax:recentReportTimesMaxCount:timeBetweenReportsTooShortThreshold:timeBetweenReportsTooShortMinThreshold:reportToPersistenceDelayMaxMultiplier:deviceReportingExcessivelyIntervalThreshold:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/deviceReportingExcessivelyIntervalThreshold",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/disableStorageBehaviorOptimization",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/recentReportTimesMaxCount",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayMaxMultiplier",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayTime",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayTimeMax",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/timeBetweenReportsTooShortMinThreshold",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/timeBetweenReportsTooShortThreshold"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/withDefaultStorageBehavior()",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/withStorageBehaviorOptimizationDisabled()"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDeviceStorageBehaviorConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceStorageBehaviorConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceStorageBehaviorConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/deviceReportingExcessivelyIntervalThreshold",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/disableStorageBehaviorOptimization",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/recentReportTimesMaxCount",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayMaxMultiplier",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayTime",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/reportToPersistenceDelayTimeMax",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/timeBetweenReportsTooShortMinThreshold",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/timeBetweenReportsTooShortThreshold"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/init(reportToPersistenceDelayTime:reportToPersistenceDelayTimeMax:recentReportTimesMaxCount:timeBetweenReportsTooShortThreshold:timeBetweenReportsTooShortMinThreshold:reportToPersistenceDelayMaxMultiplier:deviceReportingExcessivelyIntervalThreshold:)",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/withDefaultStorageBehavior()",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceStorageBehaviorConfiguration/withStorageBehaviorOptimizationDisabled()"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDeviceStorageBehaviorConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration/title",
          "value": "MTRDeviceStorageBehaviorConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceStorageBehaviorConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceStorageBehaviorConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1withStorageBehaviorOptimizationDisabled()/title",
          "value": "configurationWithStorageBehaviorOptimizationDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1withStorageBehaviorOptimizationDisabled()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "configurationWithStorageBehaviorOptimizationDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1timeBetweenReportsTooShortMinThreshold/title",
          "value": "timeBetweenReportsTooShortMinThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1timeBetweenReportsTooShortMinThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeBetweenReportsTooShortMinThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1disableStorageBehaviorOptimization/title",
          "value": "disableStorageBehaviorOptimization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1disableStorageBehaviorOptimization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disableStorageBehaviorOptimization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1timeBetweenReportsTooShortThreshold/title",
          "value": "timeBetweenReportsTooShortThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1timeBetweenReportsTooShortThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeBetweenReportsTooShortThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1deviceReportingExcessivelyIntervalThreshold/title",
          "value": "deviceReportingExcessivelyIntervalThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1deviceReportingExcessivelyIntervalThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceReportingExcessivelyIntervalThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1reportToPersistenceDelayTime/title",
          "value": "reportToPersistenceDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1reportToPersistenceDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportToPersistenceDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1reportToPersistenceDelayMaxMultiplier/title",
          "value": "reportToPersistenceDelayMaxMultiplier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1reportToPersistenceDelayMaxMultiplier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportToPersistenceDelayMaxMultiplier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1reportToPersistenceDelayTimeMax/title",
          "value": "reportToPersistenceDelayTimeMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1reportToPersistenceDelayTimeMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportToPersistenceDelayTimeMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1init(reportToPersistenceDelayTime:reportToPersistenceDelayTimeMax:recentReportTimesMaxCount:timeBetweenReportsTooShortThreshold:timeBetweenReportsTooShortMinThreshold:reportToPersistenceDelayMaxMultiplier:deviceReportingExcessivelyIntervalThreshold:)/title",
          "value": "configurationWithReportToPersistenceDelayTime:reportToPersistenceDelayTimeMax:recentReportTimesMaxCount:timeBetweenReportsTooShortThreshold:timeBetweenReportsTooShortMinThreshold:reportToPersistenceDelayMaxMultiplier:deviceReportingExcessivelyIntervalThreshold:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1init(reportToPersistenceDelayTime:reportToPersistenceDelayTimeMax:recentReportTimesMaxCount:timeBetweenReportsTooShortThreshold:timeBetweenReportsTooShortMinThreshold:reportToPersistenceDelayMaxMultiplier:deviceReportingExcessivelyIntervalThreshold:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "configurationWithReportToPersistenceDelayTime:reportToPersistenceDelayTimeMax:recentReportTimesMaxCount:timeBetweenReportsTooShortThreshold:timeBetweenReportsTooShortMinThreshold:reportToPersistenceDelayMaxMultiplier:deviceReportingExcessivelyIntervalThreshold:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1withDefaultStorageBehavior()/title",
          "value": "configurationWithDefaultStorageBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1withDefaultStorageBehavior()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "configurationWithDefaultStorageBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1recentReportTimesMaxCount/title",
          "value": "recentReportTimesMaxCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceStorageBehaviorConfiguration~1recentReportTimesMaxCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recentReportTimesMaxCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdevicestoragebehaviorconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdevicestoragebehaviorconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
