{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDoorLockOperationSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDoorLockOperationSource"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDoorLockOperationSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRDoorLockOperationSource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSource"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSource"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/RFID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RFID"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/RFID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceRFID"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.RFID",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/rfid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/aliro": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aliro"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/aliro",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceAliro"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.aliro",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/aliro"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/auto": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/biometric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometric"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/biometric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceBiometric"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.biometric",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/biometric"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/button": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "button"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/button",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceButton"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.button",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/button"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/keypad": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/keypad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceKeypad"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.keypad",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/keypad"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/manual": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manual"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/manual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceManual"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.manual",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/manual"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/proprietaryRemote": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proprietaryRemote"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/proprietaryRemote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceProprietaryRemote"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.proprietaryRemote",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/proprietaryremote"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/remote": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remote"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/remote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceRemote"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.remote",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/remote"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/schedule": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "schedule"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/schedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceSchedule"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.schedule",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/schedule"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationSourceUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationSource.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationsource/unspecified"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/RFID",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/auto",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/biometric",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/button",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/keypad",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/manual",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/proprietaryRemote",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/remote",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/schedule",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/unspecified",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/aliro"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDoorLockOperationSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/RFID",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/auto",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/biometric",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/button",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/keypad",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/manual",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/proprietaryRemote",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/remote",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/schedule",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/unspecified",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationSource/aliro"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDoorLockOperationSource"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1proprietaryRemote/title",
          "value": "MTRDoorLockOperationSourceProprietaryRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1proprietaryRemote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceProprietaryRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1manual/title",
          "value": "MTRDoorLockOperationSourceManual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1manual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceManual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1biometric/title",
          "value": "MTRDoorLockOperationSourceBiometric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1biometric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceBiometric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1RFID/title",
          "value": "MTRDoorLockOperationSourceRFID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1RFID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceRFID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1unspecified/title",
          "value": "MTRDoorLockOperationSourceUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1keypad/title",
          "value": "MTRDoorLockOperationSourceKeypad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1keypad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceKeypad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1auto/title",
          "value": "MTRDoorLockOperationSourceAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1button/title",
          "value": "MTRDoorLockOperationSourceButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1button/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1aliro/title",
          "value": "MTRDoorLockOperationSourceAliro"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1aliro/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceAliro"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource/title",
          "value": "MTRDoorLockOperationSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1remote/title",
          "value": "MTRDoorLockOperationSourceRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1remote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1schedule/title",
          "value": "MTRDoorLockOperationSourceSchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationSource~1schedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationSourceSchedule"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdoorlockoperationsource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdoorlockoperationsource"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
