{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRDeviceEnergyManagementClusterSlotStruct",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDeviceEnergyManagementClusterSlotStruct"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDeviceEnergyManagementClusterSlotStruct"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRDeviceEnergyManagementClusterSlotStruct"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementClusterSlotStruct"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementClusterSlotStruct"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementClusterSlotStruct"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementClusterSlotStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/costs": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "costs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/costs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "costs"
        }
      ],
      "role": "symbol",
      "title": "costs",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/costs"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/defaultDuration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/defaultDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultDuration"
        }
      ],
      "role": "symbol",
      "title": "defaultDuration",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/defaultduration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/elapsedSlotTime": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elapsedSlotTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/elapsedSlotTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elapsedSlotTime"
        }
      ],
      "role": "symbol",
      "title": "elapsedSlotTime",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/elapsedslottime"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/manufacturerESAState": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manufacturerESAState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/manufacturerESAState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manufacturerESAState"
        }
      ],
      "role": "symbol",
      "title": "manufacturerESAState",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/manufactureresastate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxDuration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxDuration"
        }
      ],
      "role": "symbol",
      "title": "maxDuration",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/maxduration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxDurationAdjustment": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxDurationAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxDurationAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxDurationAdjustment"
        }
      ],
      "role": "symbol",
      "title": "maxDurationAdjustment",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/maxdurationadjustment"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPauseDuration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxPauseDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPauseDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxPauseDuration"
        }
      ],
      "role": "symbol",
      "title": "maxPauseDuration",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/maxpauseduration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPower": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxPower"
        }
      ],
      "role": "symbol",
      "title": "maxPower",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/maxpower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPowerAdjustment": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxPowerAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPowerAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxPowerAdjustment"
        }
      ],
      "role": "symbol",
      "title": "maxPowerAdjustment",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/maxpoweradjustment"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minDuration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minDuration"
        }
      ],
      "role": "symbol",
      "title": "minDuration",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/minduration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minDurationAdjustment": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minDurationAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minDurationAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minDurationAdjustment"
        }
      ],
      "role": "symbol",
      "title": "minDurationAdjustment",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/mindurationadjustment"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPauseDuration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minPauseDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPauseDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minPauseDuration"
        }
      ],
      "role": "symbol",
      "title": "minPauseDuration",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/minpauseduration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPower": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minPower"
        }
      ],
      "role": "symbol",
      "title": "minPower",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/minpower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPowerAdjustment": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minPowerAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPowerAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minPowerAdjustment"
        }
      ],
      "role": "symbol",
      "title": "minPowerAdjustment",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/minpoweradjustment"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/nominalEnergy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nominalEnergy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/nominalEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nominalEnergy"
        }
      ],
      "role": "symbol",
      "title": "nominalEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/nominalenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/nominalPower": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nominalPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/nominalPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nominalPower"
        }
      ],
      "role": "symbol",
      "title": "nominalPower",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/nominalpower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/remainingSlotTime": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remainingSlotTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/remainingSlotTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remainingSlotTime"
        }
      ],
      "role": "symbol",
      "title": "remainingSlotTime",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/remainingslottime"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/slotIsPausable": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slotIsPausable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/slotIsPausable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "slotIsPausable"
        }
      ],
      "role": "symbol",
      "title": "slotIsPausable",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct/slotispausable"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/costs",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/defaultDuration",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/elapsedSlotTime",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/manufacturerESAState",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxDuration",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxDurationAdjustment",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPauseDuration",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPower",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPowerAdjustment",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minDuration",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minDurationAdjustment",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPauseDuration",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPower",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPowerAdjustment",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/nominalEnergy",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/nominalPower",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/remainingSlotTime",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/slotIsPausable"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDeviceEnergyManagementClusterSlotStruct"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementClusterSlotStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementClusterSlotStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/costs",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/defaultDuration",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/elapsedSlotTime",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/manufacturerESAState",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxDuration",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxDurationAdjustment",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPauseDuration",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPower",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/maxPowerAdjustment",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minDuration",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minDurationAdjustment",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPauseDuration",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPower",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/minPowerAdjustment",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/nominalEnergy",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/nominalPower",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/remainingSlotTime",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementClusterSlotStruct/slotIsPausable"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDeviceEnergyManagementClusterSlotStruct"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1costs/title",
          "value": "costs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1costs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "costs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1defaultDuration/title",
          "value": "defaultDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1defaultDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1minDuration/title",
          "value": "minDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1minDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1nominalEnergy/title",
          "value": "nominalEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1nominalEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nominalEnergy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1slotIsPausable/title",
          "value": "slotIsPausable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1slotIsPausable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "slotIsPausable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1minPauseDuration/title",
          "value": "minPauseDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1minPauseDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minPauseDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1manufacturerESAState/title",
          "value": "manufacturerESAState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1manufacturerESAState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "manufacturerESAState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1minPowerAdjustment/title",
          "value": "minPowerAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1minPowerAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minPowerAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1nominalPower/title",
          "value": "nominalPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1nominalPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nominalPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1maxPauseDuration/title",
          "value": "maxPauseDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1maxPauseDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxPauseDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct/title",
          "value": "MTRDeviceEnergyManagementClusterSlotStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementClusterSlotStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementClusterSlotStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1elapsedSlotTime/title",
          "value": "elapsedSlotTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1elapsedSlotTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "elapsedSlotTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1maxDurationAdjustment/title",
          "value": "maxDurationAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1maxDurationAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxDurationAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1maxPower/title",
          "value": "maxPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1maxPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1minPower/title",
          "value": "minPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1minPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1maxPowerAdjustment/title",
          "value": "maxPowerAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1maxPowerAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxPowerAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1minDurationAdjustment/title",
          "value": "minDurationAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1minDurationAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minDurationAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1remainingSlotTime/title",
          "value": "remainingSlotTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1remainingSlotTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remainingSlotTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1maxDuration/title",
          "value": "maxDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementClusterSlotStruct~1maxDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxDuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdeviceenergymanagementclusterslotstruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
