{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDeviceEnergyManagementESAType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDeviceEnergyManagementESAType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDeviceEnergyManagementESAType"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRDeviceEnergyManagementESAType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESAType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESAType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESAType"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/EVSE": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EVSE"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/EVSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeEVSE"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.EVSE",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/evse"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/batteryStorage": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batteryStorage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/batteryStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeBatteryStorage"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.batteryStorage",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/batterystorage"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/cooking": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cooking"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/cooking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeCooking"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.cooking",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/cooking"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/dishwasher": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dishwasher"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/dishwasher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeDishwasher"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.dishwasher",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/dishwasher"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/fridgeFreezer": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fridgeFreezer"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/fridgeFreezer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeFridgeFreezer"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.fridgeFreezer",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/fridgefreezer"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/homeWaterPump": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeWaterPump"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/homeWaterPump",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeHomeWaterPump"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.homeWaterPump",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/homewaterpump"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/irrigationWaterPump": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "irrigationWaterPump"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/irrigationWaterPump",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeIrrigationWaterPump"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.irrigationWaterPump",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/irrigationwaterpump"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/other": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeOther"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.other",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/other"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/poolPump": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "poolPump"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/poolPump",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypePoolPump"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.poolPump",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/poolpump"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/solarPV": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "solarPV"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/solarPV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeSolarPV"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.solarPV",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/solarpv"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceCooling": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spaceCooling"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceCooling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeSpaceCooling"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.spaceCooling",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/spacecooling"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceHeating": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spaceHeating"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceHeating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeSpaceHeating"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.spaceHeating",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/spaceheating"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceHeatingCooling": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spaceHeatingCooling"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceHeatingCooling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeSpaceHeatingCooling"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.spaceHeatingCooling",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/spaceheatingcooling"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/washingMachine": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "washingMachine"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/washingMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeWashingMachine"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.washingMachine",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/washingmachine"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/waterHeating": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waterHeating"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/waterHeating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceEnergyManagementESATypeWaterHeating"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceEnergyManagementESAType.waterHeating",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceenergymanagementesatype/waterheating"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/EVSE",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/batteryStorage",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/cooking",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/dishwasher",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/fridgeFreezer",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/homeWaterPump",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/irrigationWaterPump",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/other",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/poolPump",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/solarPV",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceCooling",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceHeating",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceHeatingCooling",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/washingMachine",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/waterHeating"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDeviceEnergyManagementESAType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESAType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESAType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/EVSE",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/batteryStorage",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/cooking",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/dishwasher",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/fridgeFreezer",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/homeWaterPump",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/irrigationWaterPump",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/other",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/poolPump",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/solarPV",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceCooling",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceHeating",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/spaceHeatingCooling",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/washingMachine",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceEnergyManagementESAType/waterHeating"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDeviceEnergyManagementESAType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1EVSE/title",
          "value": "MTRDeviceEnergyManagementESATypeEVSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1EVSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeEVSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1spaceHeatingCooling/title",
          "value": "MTRDeviceEnergyManagementESATypeSpaceHeatingCooling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1spaceHeatingCooling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeSpaceHeatingCooling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1waterHeating/title",
          "value": "MTRDeviceEnergyManagementESATypeWaterHeating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1waterHeating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeWaterHeating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1dishwasher/title",
          "value": "MTRDeviceEnergyManagementESATypeDishwasher"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1dishwasher/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeDishwasher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1washingMachine/title",
          "value": "MTRDeviceEnergyManagementESATypeWashingMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1washingMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeWashingMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1cooking/title",
          "value": "MTRDeviceEnergyManagementESATypeCooking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1cooking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeCooking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType/title",
          "value": "MTRDeviceEnergyManagementESAType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESAType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESAType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1other/title",
          "value": "MTRDeviceEnergyManagementESATypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1solarPV/title",
          "value": "MTRDeviceEnergyManagementESATypeSolarPV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1solarPV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeSolarPV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1batteryStorage/title",
          "value": "MTRDeviceEnergyManagementESATypeBatteryStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1batteryStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeBatteryStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1spaceHeating/title",
          "value": "MTRDeviceEnergyManagementESATypeSpaceHeating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1spaceHeating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeSpaceHeating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1fridgeFreezer/title",
          "value": "MTRDeviceEnergyManagementESATypeFridgeFreezer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1fridgeFreezer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeFridgeFreezer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1poolPump/title",
          "value": "MTRDeviceEnergyManagementESATypePoolPump"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1poolPump/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypePoolPump"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1spaceCooling/title",
          "value": "MTRDeviceEnergyManagementESATypeSpaceCooling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1spaceCooling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeSpaceCooling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1irrigationWaterPump/title",
          "value": "MTRDeviceEnergyManagementESATypeIrrigationWaterPump"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1irrigationWaterPump/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeIrrigationWaterPump"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1homeWaterPump/title",
          "value": "MTRDeviceEnergyManagementESATypeHomeWaterPump"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceEnergyManagementESAType~1homeWaterPump/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceEnergyManagementESATypeHomeWaterPump"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdeviceenergymanagementesatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdeviceenergymanagementesatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
