{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This enum is unused and will be removed",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDoorLockOperationEventCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDoorLockOperationEventCode"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDoorLockOperationEventCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "This enum is unused and will be removed",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "This enum is unused and will be removed",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "This enum is unused and will be removed",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "This enum is unused and will be removed",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "This enum is unused and will be removed",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "This enum is unused and will be removed",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "This enum is unused and will be removed",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRDoorLockOperationEventCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCode"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCode"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/autoLock": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoLock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/autoLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeAutoLock"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.autoLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/autolock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/keyLock": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyLock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/keyLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeKeyLock"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.keyLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/keylock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/keyUnlock": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyUnlock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/keyUnlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeKeyUnlock"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.keyUnlock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/keyunlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lock": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeLock"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.lock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/lock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lockInvalidPinOrId": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockInvalidPinOrId"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lockInvalidPinOrId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeLockInvalidPinOrId"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.lockInvalidPinOrId",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/lockinvalidpinorid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lockInvalidSchedule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockInvalidSchedule"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lockInvalidSchedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeLockInvalidSchedule"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.lockInvalidSchedule",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/lockinvalidschedule"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/manualLock": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manualLock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/manualLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeManualLock"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.manualLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/manuallock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/manualUnlock": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manualUnlock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/manualUnlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeManualUnlock"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.manualUnlock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/manualunlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/oneTouchLock": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneTouchLock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/oneTouchLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeOneTouchLock"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.oneTouchLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/onetouchlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/scheduleLock": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleLock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/scheduleLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeScheduleLock"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.scheduleLock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/schedulelock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/scheduleUnlock": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleUnlock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/scheduleUnlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeScheduleUnlock"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.scheduleUnlock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/scheduleunlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unknownOrMfgSpecific": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownOrMfgSpecific"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unknownOrMfgSpecific",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeUnknownOrMfgSpecific"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.unknownOrMfgSpecific",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/unknownormfgspecific"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlock": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeUnlock"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.unlock",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/unlock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlockInvalidPinOrId": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlockInvalidPinOrId"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlockInvalidPinOrId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeUnlockInvalidPinOrId"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.unlockInvalidPinOrId",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/unlockinvalidpinorid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlockInvalidSchedule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlockInvalidSchedule"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlockInvalidSchedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockOperationEventCodeUnlockInvalidSchedule"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockOperationEventCode.unlockInvalidSchedule",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockoperationeventcode/unlockinvalidschedule"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/autoLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/keyLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/keyUnlock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lockInvalidPinOrId",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lockInvalidSchedule",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/manualLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/manualUnlock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/oneTouchLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/scheduleLock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/scheduleUnlock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unknownOrMfgSpecific",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlock",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlockInvalidPinOrId",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlockInvalidSchedule"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDoorLockOperationEventCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/autoLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/keyLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/keyUnlock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lockInvalidPinOrId",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/lockInvalidSchedule",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/manualLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/manualUnlock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/oneTouchLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/scheduleLock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/scheduleUnlock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unknownOrMfgSpecific",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlock",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlockInvalidPinOrId",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockOperationEventCode/unlockInvalidSchedule"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDoorLockOperationEventCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This enum is unused and will be removed",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1keyLock/title",
          "value": "MTRDoorLockOperationEventCodeKeyLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1keyLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeKeyLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1scheduleLock/title",
          "value": "MTRDoorLockOperationEventCodeScheduleLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1scheduleLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeScheduleLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1lock/title",
          "value": "MTRDoorLockOperationEventCodeLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1lock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1unlockInvalidPinOrId/title",
          "value": "MTRDoorLockOperationEventCodeUnlockInvalidPinOrId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1unlockInvalidPinOrId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeUnlockInvalidPinOrId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode/title",
          "value": "MTRDoorLockOperationEventCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1oneTouchLock/title",
          "value": "MTRDoorLockOperationEventCodeOneTouchLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1oneTouchLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeOneTouchLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1unlock/title",
          "value": "MTRDoorLockOperationEventCodeUnlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1unlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1autoLock/title",
          "value": "MTRDoorLockOperationEventCodeAutoLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1autoLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeAutoLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1manualUnlock/title",
          "value": "MTRDoorLockOperationEventCodeManualUnlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1manualUnlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeManualUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1manualLock/title",
          "value": "MTRDoorLockOperationEventCodeManualLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1manualLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeManualLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1keyUnlock/title",
          "value": "MTRDoorLockOperationEventCodeKeyUnlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1keyUnlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeKeyUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1unlockInvalidSchedule/title",
          "value": "MTRDoorLockOperationEventCodeUnlockInvalidSchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1unlockInvalidSchedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeUnlockInvalidSchedule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1lockInvalidPinOrId/title",
          "value": "MTRDoorLockOperationEventCodeLockInvalidPinOrId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1lockInvalidPinOrId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeLockInvalidPinOrId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1lockInvalidSchedule/title",
          "value": "MTRDoorLockOperationEventCodeLockInvalidSchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1lockInvalidSchedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeLockInvalidSchedule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1scheduleUnlock/title",
          "value": "MTRDoorLockOperationEventCodeScheduleUnlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1scheduleUnlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeScheduleUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1unknownOrMfgSpecific/title",
          "value": "MTRDoorLockOperationEventCodeUnknownOrMfgSpecific"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockOperationEventCode~1unknownOrMfgSpecific/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockOperationEventCodeUnknownOrMfgSpecific"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdoorlockoperationeventcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdoorlockoperationeventcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
