{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDoorLockCredentialType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDoorLockCredentialType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDoorLockCredentialType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRDoorLockCredentialType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialType"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockCredentialType",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/PIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PIN"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/PIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialTypePIN"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockCredentialType.PIN",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype/pin"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/RFID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RFID"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/RFID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialTypeRFID"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockCredentialType.RFID",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype/rfid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroCredentialIssuerKey": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aliroCredentialIssuerKey"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroCredentialIssuerKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialTypeAliroCredentialIssuerKey"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockCredentialType.aliroCredentialIssuerKey",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype/alirocredentialissuerkey"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroEvictableEndpointKey": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aliroEvictableEndpointKey"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroEvictableEndpointKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialTypeAliroEvictableEndpointKey"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockCredentialType.aliroEvictableEndpointKey",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype/aliroevictableendpointkey"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroNonEvictableEndpointKey": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aliroNonEvictableEndpointKey"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroNonEvictableEndpointKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialTypeAliroNonEvictableEndpointKey"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockCredentialType.aliroNonEvictableEndpointKey",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype/alirononevictableendpointkey"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/face": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "face"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/face",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialTypeFace"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockCredentialType.face",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype/face"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/fingerVein": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fingerVein"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/fingerVein",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialTypeFingerVein"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockCredentialType.fingerVein",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype/fingervein"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/fingerprint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fingerprint"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/fingerprint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialTypeFingerprint"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockCredentialType.fingerprint",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype/fingerprint"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/programmingPIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "programmingPIN"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/programmingPIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockCredentialTypeProgrammingPIN"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockCredentialType.programmingPIN",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockcredentialtype/programmingpin"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/PIN",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/RFID",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/face",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/fingerVein",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/fingerprint",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/programmingPIN",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroCredentialIssuerKey",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroEvictableEndpointKey",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroNonEvictableEndpointKey"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDoorLockCredentialType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/PIN",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/RFID",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/face",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/fingerVein",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/fingerprint",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/programmingPIN",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroCredentialIssuerKey",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroEvictableEndpointKey",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockCredentialType/aliroNonEvictableEndpointKey"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDoorLockCredentialType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1fingerVein/title",
          "value": "MTRDoorLockCredentialTypeFingerVein"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1fingerVein/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialTypeFingerVein"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1programmingPIN/title",
          "value": "MTRDoorLockCredentialTypeProgrammingPIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1programmingPIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialTypeProgrammingPIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1aliroEvictableEndpointKey/title",
          "value": "MTRDoorLockCredentialTypeAliroEvictableEndpointKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1aliroEvictableEndpointKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialTypeAliroEvictableEndpointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType/title",
          "value": "MTRDoorLockCredentialType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1fingerprint/title",
          "value": "MTRDoorLockCredentialTypeFingerprint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1fingerprint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialTypeFingerprint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1PIN/title",
          "value": "MTRDoorLockCredentialTypePIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1PIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialTypePIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1aliroCredentialIssuerKey/title",
          "value": "MTRDoorLockCredentialTypeAliroCredentialIssuerKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1aliroCredentialIssuerKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialTypeAliroCredentialIssuerKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1aliroNonEvictableEndpointKey/title",
          "value": "MTRDoorLockCredentialTypeAliroNonEvictableEndpointKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1aliroNonEvictableEndpointKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialTypeAliroNonEvictableEndpointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1RFID/title",
          "value": "MTRDoorLockCredentialTypeRFID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1RFID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialTypeRFID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1face/title",
          "value": "MTRDoorLockCredentialTypeFace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockCredentialType~1face/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockCredentialTypeFace"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdoorlockcredentialtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdoorlockcredentialtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
