{
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDataTypeLandmarkTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDataTypeLandmarkTag"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDataTypeLandmarkTag"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRDataTypeLandmarkTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTag"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTag"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/airConditioner": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airConditioner"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/airConditioner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagAirConditioner"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.airConditioner",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/airconditioner"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/airPurifier": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airPurifier"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/airPurifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagAirPurifier"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.airPurifier",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/airpurifier"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/backDoor": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backDoor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/backDoor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagBackDoor"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.backDoor",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/backdoor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/barStool": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barStool"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/barStool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagBarStool"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.barStool",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/barstool"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bathMat": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bathMat"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bathMat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagBathMat"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.bathMat",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/bathmat"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bathtub": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bathtub"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bathtub",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagBathtub"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.bathtub",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/bathtub"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bed": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bed"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagBed"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.bed",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/bed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bookshelf": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bookshelf"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bookshelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagBookshelf"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.bookshelf",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/bookshelf"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/chair": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chair"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/chair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagChair"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.chair",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/chair"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/christmasTree": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "christmasTree"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/christmasTree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagChristmasTree"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.christmasTree",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/christmastree"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/coatRack": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coatRack"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/coatRack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagCoatRack"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.coatRack",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/coatrack"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/coffeeTable": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coffeeTable"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/coffeeTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagCoffeeTable"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.coffeeTable",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/coffeetable"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/cookingRange": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cookingRange"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/cookingRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagCookingRange"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.cookingRange",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/cookingrange"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/couch": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couch"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/couch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagCouch"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.couch",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/couch"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/countertop": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "countertop"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/countertop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagCountertop"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.countertop",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/countertop"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/cradle": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cradle"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/cradle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagCradle"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.cradle",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/cradle"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/crib": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crib"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/crib",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagCrib"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.crib",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/crib"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/desk": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "desk"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/desk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagDesk"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.desk",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/desk"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/diningTable": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diningTable"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/diningTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagDiningTable"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.diningTable",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/diningtable"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/dishwasher": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dishwasher"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/dishwasher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagDishwasher"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.dishwasher",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/dishwasher"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/door": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "door"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/door",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagDoor"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.door",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/door"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/dresser": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dresser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/dresser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagDresser"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.dresser",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/dresser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/fan": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fan"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/fan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagFan"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.fan",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/fan"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/fireplace": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fireplace"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/fireplace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagFireplace"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.fireplace",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/fireplace"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/freezer": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freezer"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/freezer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagFreezer"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.freezer",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/freezer"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/frontDoor": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontDoor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/frontDoor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagFrontDoor"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.frontDoor",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/frontdoor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/highChair": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highChair"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/highChair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagHighChair"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.highChair",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/highchair"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/kitchenIsland": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kitchenIsland"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/kitchenIsland",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagKitchenIsland"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.kitchenIsland",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/kitchenisland"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/lamp": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lamp"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/lamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagLamp"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.lamp",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/lamp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/laundryDryer": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "laundryDryer"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/laundryDryer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagLaundryDryer"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.laundryDryer",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/laundrydryer"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/laundryWasher": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "laundryWasher"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/laundryWasher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagLaundryWasher"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.laundryWasher",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/laundrywasher"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/litterBox": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "litterBox"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/litterBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagLitterBox"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.litterBox",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/litterbox"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/mirror": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mirror"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/mirror",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagMirror"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.mirror",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/mirror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/nightstand": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nightstand"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/nightstand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagNightstand"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.nightstand",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/nightstand"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/oven": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oven"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/oven",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagOven"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.oven",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/oven"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petBed": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "petBed"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petBed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagPetBed"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.petBed",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/petbed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petBowl": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "petBowl"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petBowl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagPetBowl"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.petBowl",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/petbowl"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petCrate": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "petCrate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petCrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagPetCrate"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.petCrate",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/petcrate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/refrigerator": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refrigerator"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/refrigerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagRefrigerator"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.refrigerator",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/refrigerator"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/scratchingPost": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scratchingPost"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/scratchingPost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagScratchingPost"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.scratchingPost",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/scratchingpost"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/shoeRack": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shoeRack"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/shoeRack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagShoeRack"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.shoeRack",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/shoerack"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/shower": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shower"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/shower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagShower"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.shower",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/shower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sideDoor": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sideDoor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sideDoor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagSideDoor"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.sideDoor",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/sidedoor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sink": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sink"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagSink"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.sink",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/sink"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sofa": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sofa"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sofa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagSofa"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.sofa",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/sofa"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/stove": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stove"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/stove",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagStove"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.stove",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/stove"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/table": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "table"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/table",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagTable"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.table",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/table"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/toilet": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toilet"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/toilet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagToilet"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.toilet",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/toilet"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/trashCan": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trashCan"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/trashCan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagTrashCan"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.trashCan",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/trashcan"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/window": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "window"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/window",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagWindow"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.window",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/window"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/wineCooler": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wineCooler"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/wineCooler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataTypeLandmarkTagWineCooler"
        }
      ],
      "role": "symbol",
      "title": "MTRDataTypeLandmarkTag.wineCooler",
      "type": "topic",
      "url": "/documentation/matter/mtrdatatypelandmarktag/winecooler"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/airConditioner",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/airPurifier",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/backDoor",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/barStool",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bathMat",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bathtub",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bed",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bookshelf",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/chair",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/christmasTree",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/coatRack",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/coffeeTable",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/cookingRange",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/couch",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/countertop",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/cradle",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/crib",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/desk",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/diningTable",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/dishwasher",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/door",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/dresser",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/fan",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/fireplace",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/freezer",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/frontDoor",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/highChair",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/kitchenIsland",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/lamp",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/laundryDryer",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/laundryWasher",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/litterBox",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/mirror",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/nightstand",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/oven",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petBed",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petBowl",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petCrate",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/refrigerator",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/scratchingPost",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/shoeRack",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/shower",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sideDoor",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sink",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sofa",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/stove",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/table",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/toilet",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/trashCan",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/window",
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/wineCooler"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDataTypeLandmarkTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/airConditioner",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/airPurifier",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/backDoor",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/barStool",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bathMat",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bathtub",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bed",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/bookshelf",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/chair",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/christmasTree",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/coatRack",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/coffeeTable",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/cookingRange",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/couch",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/countertop",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/cradle",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/crib",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/desk",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/diningTable",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/dishwasher",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/door",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/dresser",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/fan",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/fireplace",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/freezer",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/frontDoor",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/highChair",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/kitchenIsland",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/lamp",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/laundryDryer",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/laundryWasher",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/litterBox",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/mirror",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/nightstand",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/oven",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petBed",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petBowl",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/petCrate",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/refrigerator",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/scratchingPost",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/shoeRack",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/shower",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sideDoor",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sink",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/sofa",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/stove",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/table",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/toilet",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/trashCan",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/window",
                "doc://com.apple.matter/documentation/Matter/MTRDataTypeLandmarkTag/wineCooler"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDataTypeLandmarkTag"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1sideDoor/title",
          "value": "MTRDataTypeLandmarkTagSideDoor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1sideDoor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagSideDoor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1couch/title",
          "value": "MTRDataTypeLandmarkTagCouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1couch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagCouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1diningTable/title",
          "value": "MTRDataTypeLandmarkTagDiningTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1diningTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagDiningTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1shoeRack/title",
          "value": "MTRDataTypeLandmarkTagShoeRack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1shoeRack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagShoeRack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1nightstand/title",
          "value": "MTRDataTypeLandmarkTagNightstand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1nightstand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagNightstand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1door/title",
          "value": "MTRDataTypeLandmarkTagDoor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1door/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagDoor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1crib/title",
          "value": "MTRDataTypeLandmarkTagCrib"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1crib/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagCrib"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1chair/title",
          "value": "MTRDataTypeLandmarkTagChair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1chair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagChair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1fan/title",
          "value": "MTRDataTypeLandmarkTagFan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1fan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagFan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1frontDoor/title",
          "value": "MTRDataTypeLandmarkTagFrontDoor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1frontDoor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagFrontDoor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1barStool/title",
          "value": "MTRDataTypeLandmarkTagBarStool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1barStool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagBarStool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1countertop/title",
          "value": "MTRDataTypeLandmarkTagCountertop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1countertop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagCountertop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1petBowl/title",
          "value": "MTRDataTypeLandmarkTagPetBowl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1petBowl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagPetBowl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1petBed/title",
          "value": "MTRDataTypeLandmarkTagPetBed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1petBed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagPetBed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1bathtub/title",
          "value": "MTRDataTypeLandmarkTagBathtub"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1bathtub/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagBathtub"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1scratchingPost/title",
          "value": "MTRDataTypeLandmarkTagScratchingPost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1scratchingPost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagScratchingPost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1petCrate/title",
          "value": "MTRDataTypeLandmarkTagPetCrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1petCrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagPetCrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1laundryWasher/title",
          "value": "MTRDataTypeLandmarkTagLaundryWasher"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1laundryWasher/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagLaundryWasher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1kitchenIsland/title",
          "value": "MTRDataTypeLandmarkTagKitchenIsland"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1kitchenIsland/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagKitchenIsland"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1dresser/title",
          "value": "MTRDataTypeLandmarkTagDresser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1dresser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagDresser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1christmasTree/title",
          "value": "MTRDataTypeLandmarkTagChristmasTree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1christmasTree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagChristmasTree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1refrigerator/title",
          "value": "MTRDataTypeLandmarkTagRefrigerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1refrigerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagRefrigerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1shower/title",
          "value": "MTRDataTypeLandmarkTagShower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1shower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagShower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1desk/title",
          "value": "MTRDataTypeLandmarkTagDesk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1desk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagDesk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1bookshelf/title",
          "value": "MTRDataTypeLandmarkTagBookshelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1bookshelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagBookshelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1sink/title",
          "value": "MTRDataTypeLandmarkTagSink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1sink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagSink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1freezer/title",
          "value": "MTRDataTypeLandmarkTagFreezer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1freezer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagFreezer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1litterBox/title",
          "value": "MTRDataTypeLandmarkTagLitterBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1litterBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagLitterBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1dishwasher/title",
          "value": "MTRDataTypeLandmarkTagDishwasher"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1dishwasher/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagDishwasher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1toilet/title",
          "value": "MTRDataTypeLandmarkTagToilet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1toilet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagToilet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1laundryDryer/title",
          "value": "MTRDataTypeLandmarkTagLaundryDryer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1laundryDryer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagLaundryDryer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1sofa/title",
          "value": "MTRDataTypeLandmarkTagSofa"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1sofa/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagSofa"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1cradle/title",
          "value": "MTRDataTypeLandmarkTagCradle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1cradle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagCradle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1fireplace/title",
          "value": "MTRDataTypeLandmarkTagFireplace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1fireplace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagFireplace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1airConditioner/title",
          "value": "MTRDataTypeLandmarkTagAirConditioner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1airConditioner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagAirConditioner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1bed/title",
          "value": "MTRDataTypeLandmarkTagBed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1bed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagBed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1wineCooler/title",
          "value": "MTRDataTypeLandmarkTagWineCooler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1wineCooler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagWineCooler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag/title",
          "value": "MTRDataTypeLandmarkTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1window/title",
          "value": "MTRDataTypeLandmarkTagWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1window/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1mirror/title",
          "value": "MTRDataTypeLandmarkTagMirror"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1mirror/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagMirror"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1coffeeTable/title",
          "value": "MTRDataTypeLandmarkTagCoffeeTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1coffeeTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagCoffeeTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1lamp/title",
          "value": "MTRDataTypeLandmarkTagLamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1lamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagLamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1trashCan/title",
          "value": "MTRDataTypeLandmarkTagTrashCan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1trashCan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagTrashCan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1airPurifier/title",
          "value": "MTRDataTypeLandmarkTagAirPurifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1airPurifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagAirPurifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1coatRack/title",
          "value": "MTRDataTypeLandmarkTagCoatRack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1coatRack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagCoatRack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1oven/title",
          "value": "MTRDataTypeLandmarkTagOven"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1oven/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagOven"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1highChair/title",
          "value": "MTRDataTypeLandmarkTagHighChair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1highChair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagHighChair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1stove/title",
          "value": "MTRDataTypeLandmarkTagStove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1stove/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagStove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1bathMat/title",
          "value": "MTRDataTypeLandmarkTagBathMat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1bathMat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagBathMat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1cookingRange/title",
          "value": "MTRDataTypeLandmarkTagCookingRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1cookingRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagCookingRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1table/title",
          "value": "MTRDataTypeLandmarkTagTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1table/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1backDoor/title",
          "value": "MTRDataTypeLandmarkTagBackDoor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataTypeLandmarkTag~1backDoor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataTypeLandmarkTagBackDoor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdatatypelandmarktag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdatatypelandmarktag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
