{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRDoorLockFeature",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRDoorLockFeature"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRDoorLockFeature"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTRDoorLockFeature"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeature"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeature"
        }
      ],
      "role": "symbol",
      "title": "MTRDoorLockFeature",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/aliroBLEUWB": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aliroBLEUWB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/aliroBLEUWB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureAliroBLEUWB"
        }
      ],
      "role": "symbol",
      "title": "aliroBLEUWB",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/alirobleuwb"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/aliroProvisioning": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aliroProvisioning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/aliroProvisioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureAliroProvisioning"
        }
      ],
      "role": "symbol",
      "title": "aliroProvisioning",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/aliroprovisioning"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/credentialsOTA": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credentialsOTA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/credentialsOTA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureCredentialsOTA"
        }
      ],
      "role": "symbol",
      "title": "credentialsOTA",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/credentialsota"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/credentialsOverTheAirAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credentialsOverTheAirAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/credentialsOverTheAirAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureCredentialsOverTheAirAccess"
        }
      ],
      "role": "symbol",
      "title": "credentialsOverTheAirAccess",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/credentialsovertheairaccess"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/doorPositionSensor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doorPositionSensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/doorPositionSensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureDoorPositionSensor"
        }
      ],
      "role": "symbol",
      "title": "doorPositionSensor",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/doorpositionsensor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/faceCredentials": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceCredentials"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/faceCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureFaceCredentials"
        }
      ],
      "role": "symbol",
      "title": "faceCredentials",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/facecredentials"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/fingerCredentials": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fingerCredentials"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/fingerCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureFingerCredentials"
        }
      ],
      "role": "symbol",
      "title": "fingerCredentials",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/fingercredentials"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/holidaySchedules": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "holidaySchedules"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/holidaySchedules",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureHolidaySchedules"
        }
      ],
      "role": "symbol",
      "title": "holidaySchedules",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/holidayschedules"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/logging": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logging"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/logging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureLogging"
        }
      ],
      "role": "symbol",
      "title": "logging",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/logging"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/notification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/notification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureNotification"
        }
      ],
      "role": "symbol",
      "title": "notification",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/notification"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/notifications": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notifications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/notifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureNotifications"
        }
      ],
      "role": "symbol",
      "title": "notifications",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/notifications"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/pinCredential": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pinCredential"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/pinCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeaturePINCredential"
        }
      ],
      "role": "symbol",
      "title": "pinCredential",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/pincredential"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/pinCredentials": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pinCredentials"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/pinCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeaturePINCredentials"
        }
      ],
      "role": "symbol",
      "title": "pinCredentials",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/pincredentials"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/rfidCredential": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfidCredential"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/rfidCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureRFIDCredential"
        }
      ],
      "role": "symbol",
      "title": "rfidCredential",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/rfidcredential"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/rfidCredentials": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfidCredentials"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/rfidCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureRFIDCredentials"
        }
      ],
      "role": "symbol",
      "title": "rfidCredentials",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/rfidcredentials"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/unbolt": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unbolt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/unbolt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureUnbolt"
        }
      ],
      "role": "symbol",
      "title": "unbolt",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/unbolt"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/user": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "user"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/user",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureUser"
        }
      ],
      "role": "symbol",
      "title": "user",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/user"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/usersManagement": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usersManagement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/usersManagement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureUsersManagement"
        }
      ],
      "role": "symbol",
      "title": "usersManagement",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/usersmanagement"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/weekDayAccessSchedules": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weekDayAccessSchedules"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/weekDayAccessSchedules",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureWeekDayAccessSchedules"
        }
      ],
      "role": "symbol",
      "title": "weekDayAccessSchedules",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/weekdayaccessschedules"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/weekDaySchedules": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weekDaySchedules"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/weekDaySchedules",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureWeekDaySchedules"
        }
      ],
      "role": "symbol",
      "title": "weekDaySchedules",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/weekdayschedules"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/yearDayAccessSchedules": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yearDayAccessSchedules"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/yearDayAccessSchedules",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureYearDayAccessSchedules"
        }
      ],
      "role": "symbol",
      "title": "yearDayAccessSchedules",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/yeardayaccessschedules"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/yearDaySchedules": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yearDaySchedules"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRDoorLockFeature",
          "text": "MTRDoorLockFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/yearDaySchedules",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDoorLockFeatureYearDaySchedules"
        }
      ],
      "role": "symbol",
      "title": "yearDaySchedules",
      "type": "topic",
      "url": "/documentation/matter/mtrdoorlockfeature/yeardayschedules"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/credentialsOTA",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/credentialsOverTheAirAccess",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/doorPositionSensor",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/faceCredentials",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/fingerCredentials",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/holidaySchedules",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/logging",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/notification",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/notifications",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/pinCredential",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/pinCredentials",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/rfidCredential",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/rfidCredentials",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/user",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/usersManagement",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/weekDayAccessSchedules",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/weekDaySchedules",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/yearDayAccessSchedules",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/yearDaySchedules",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/aliroBLEUWB",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/aliroProvisioning",
        "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/unbolt"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRDoorLockFeature"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/credentialsOTA",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/credentialsOverTheAirAccess",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/doorPositionSensor",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/faceCredentials",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/fingerCredentials",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/holidaySchedules",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/logging",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/notification",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/notifications",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/pinCredential",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/pinCredentials",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/rfidCredential",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/rfidCredentials",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/user",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/usersManagement",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/weekDayAccessSchedules",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/weekDaySchedules",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/yearDayAccessSchedules",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/yearDaySchedules"
              ],
              "title": "Type Properties"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/aliroBLEUWB",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/aliroProvisioning",
                "doc://com.apple.matter/documentation/Matter/MTRDoorLockFeature/unbolt"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRDoorLockFeature"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1aliroBLEUWB/title",
          "value": "MTRDoorLockFeatureAliroBLEUWB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1aliroBLEUWB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureAliroBLEUWB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1user/title",
          "value": "MTRDoorLockFeatureUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1user/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1credentialsOverTheAirAccess/title",
          "value": "MTRDoorLockFeatureCredentialsOverTheAirAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1credentialsOverTheAirAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureCredentialsOverTheAirAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1pinCredential/title",
          "value": "MTRDoorLockFeaturePINCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1pinCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeaturePINCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1yearDaySchedules/title",
          "value": "MTRDoorLockFeatureYearDaySchedules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1yearDaySchedules/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureYearDaySchedules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1weekDaySchedules/title",
          "value": "MTRDoorLockFeatureWeekDaySchedules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1weekDaySchedules/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureWeekDaySchedules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature/title",
          "value": "MTRDoorLockFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1rfidCredential/title",
          "value": "MTRDoorLockFeatureRFIDCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1rfidCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureRFIDCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1unbolt/title",
          "value": "MTRDoorLockFeatureUnbolt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1unbolt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureUnbolt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1weekDayAccessSchedules/title",
          "value": "MTRDoorLockFeatureWeekDayAccessSchedules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1weekDayAccessSchedules/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureWeekDayAccessSchedules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1pinCredentials/title",
          "value": "MTRDoorLockFeaturePINCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1pinCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeaturePINCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1doorPositionSensor/title",
          "value": "MTRDoorLockFeatureDoorPositionSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1doorPositionSensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureDoorPositionSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1aliroProvisioning/title",
          "value": "MTRDoorLockFeatureAliroProvisioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1aliroProvisioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureAliroProvisioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1usersManagement/title",
          "value": "MTRDoorLockFeatureUsersManagement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1usersManagement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureUsersManagement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1rfidCredentials/title",
          "value": "MTRDoorLockFeatureRFIDCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1rfidCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureRFIDCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1credentialsOTA/title",
          "value": "MTRDoorLockFeatureCredentialsOTA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1credentialsOTA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureCredentialsOTA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1fingerCredentials/title",
          "value": "MTRDoorLockFeatureFingerCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1fingerCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureFingerCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1holidaySchedules/title",
          "value": "MTRDoorLockFeatureHolidaySchedules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1holidaySchedules/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureHolidaySchedules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1yearDayAccessSchedules/title",
          "value": "MTRDoorLockFeatureYearDayAccessSchedules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1yearDayAccessSchedules/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureYearDayAccessSchedules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1logging/title",
          "value": "MTRDoorLockFeatureLogging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1logging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureLogging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1notifications/title",
          "value": "MTRDoorLockFeatureNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1notifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1notification/title",
          "value": "MTRDoorLockFeatureNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1notification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1faceCredentials/title",
          "value": "MTRDoorLockFeatureFaceCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDoorLockFeature~1faceCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDoorLockFeatureFaceCredentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdoorlockfeature"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdoorlockfeature"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
