{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRElectricalPowerMeasurementMeasurementType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRElectricalPowerMeasurementMeasurementType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRElectricalPowerMeasurementMeasurementType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRElectricalPowerMeasurementMeasurementType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementType"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/activeCurrent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/activeCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeActiveCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.activeCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/activecurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/activePower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activePower"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/activePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeActivePower"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.activePower",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/activepower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/apparentCurrent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apparentCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/apparentCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeApparentCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.apparentCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/apparentcurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/apparentPower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apparentPower"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/apparentPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeApparentPower"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.apparentPower",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/apparentpower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/electricalEnergy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "electricalEnergy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/electricalEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeElectricalEnergy"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.electricalEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/electricalenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/frequency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frequency"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/frequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeFrequency"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.frequency",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/frequency"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/neutralCurrent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "neutralCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/neutralCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeNeutralCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.neutralCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/neutralcurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/powerFactor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerFactor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/powerFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypePowerFactor"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.powerFactor",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/powerfactor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/reactiveCurrent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reactiveCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/reactiveCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeReactiveCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.reactiveCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/reactivecurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/reactivePower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reactivePower"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/reactivePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeReactivePower"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.reactivePower",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/reactivepower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsCurrent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rmsCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeRMSCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.rmsCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/rmscurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsPower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rmsPower"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeRMSPower"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.rmsPower",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/rmspower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsVoltage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rmsVoltage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsVoltage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeRMSVoltage"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.rmsVoltage",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/rmsvoltage"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/unspecified"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/voltage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voltage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/voltage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementMeasurementTypeVoltage"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementMeasurementType.voltage",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype/voltage"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/activeCurrent",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/activePower",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/apparentCurrent",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/apparentPower",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/electricalEnergy",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/frequency",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/neutralCurrent",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/powerFactor",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/reactiveCurrent",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/reactivePower",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsCurrent",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsPower",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsVoltage",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/unspecified",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/voltage"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRElectricalPowerMeasurementMeasurementType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/activeCurrent",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/activePower",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/apparentCurrent",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/apparentPower",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/electricalEnergy",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/frequency",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/neutralCurrent",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/powerFactor",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/reactiveCurrent",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/reactivePower",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsCurrent",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsPower",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/rmsVoltage",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/unspecified",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementMeasurementType/voltage"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRElectricalPowerMeasurementMeasurementType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1voltage/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeVoltage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1voltage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeVoltage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1activeCurrent/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeActiveCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1activeCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeActiveCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType/title",
          "value": "MTRElectricalPowerMeasurementMeasurementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1activePower/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeActivePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1activePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeActivePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1apparentCurrent/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeApparentCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1apparentCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeApparentCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1frequency/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1frequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1unspecified/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1rmsPower/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeRMSPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1rmsPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeRMSPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1electricalEnergy/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeElectricalEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1electricalEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeElectricalEnergy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1rmsCurrent/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeRMSCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1rmsCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeRMSCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1rmsVoltage/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeRMSVoltage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1rmsVoltage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeRMSVoltage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1apparentPower/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeApparentPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1apparentPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeApparentPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1powerFactor/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypePowerFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1powerFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypePowerFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1reactiveCurrent/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeReactiveCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1reactiveCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeReactiveCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1reactivePower/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeReactivePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1reactivePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeReactivePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1neutralCurrent/title",
          "value": "MTRElectricalPowerMeasurementMeasurementTypeNeutralCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementMeasurementType~1neutralCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementMeasurementTypeNeutralCurrent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrelectricalpowermeasurementmeasurementtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
