{
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTREnergyEVSEFaultState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTREnergyEVSEFaultState"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTREnergyEVSEFaultState"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTREnergyEVSEFaultState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultState"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultState"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/contactDryFailure": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contactDryFailure"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/contactDryFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateContactDryFailure"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.contactDryFailure",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/contactdryfailure"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/contactWetFailure": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contactWetFailure"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/contactWetFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateContactWetFailure"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.contactWetFailure",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/contactwetfailure"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/emergencyStop": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emergencyStop"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/emergencyStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateEmergencyStop"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.emergencyStop",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/emergencystop"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/evDisconnected": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evDisconnected"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/evDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateEVDisconnected"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.evDisconnected",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/evdisconnected"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/groundFault": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groundFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/groundFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateGroundFault"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.groundFault",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/groundfault"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/liveNeutralSwap": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "liveNeutralSwap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/liveNeutralSwap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateLiveNeutralSwap"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.liveNeutralSwap",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/liveneutralswap"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/meterFailure": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meterFailure"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/meterFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateMeterFailure"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.meterFailure",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/meterfailure"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/noError": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/noError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateNoError"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.noError",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/noerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/other": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateOther"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.other",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/other"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overCurrent": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateOverCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.overCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/overcurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overTemperature": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overTemperature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateOverTemperature"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.overTemperature",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/overtemperature"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overVoltage": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overVoltage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overVoltage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateOverVoltage"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.overVoltage",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/overvoltage"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/pilotShortCircuit": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pilotShortCircuit"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/pilotShortCircuit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStatePilotShortCircuit"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.pilotShortCircuit",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/pilotshortcircuit"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/powerLoss": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerLoss"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/powerLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStatePowerLoss"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.powerLoss",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/powerloss"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/powerQuality": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerQuality"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/powerQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStatePowerQuality"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.powerQuality",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/powerquality"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/underVoltage": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underVoltage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/underVoltage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateUnderVoltage"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.underVoltage",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/undervoltage"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/wrongPowerSupply": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wrongPowerSupply"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/wrongPowerSupply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEFaultStateWrongPowerSupply"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEFaultState.wrongPowerSupply",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsefaultstate/wrongpowersupply"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/contactDryFailure",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/contactWetFailure",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/emergencyStop",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/evDisconnected",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/groundFault",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/liveNeutralSwap",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/meterFailure",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/noError",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/other",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overCurrent",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overTemperature",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overVoltage",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/pilotShortCircuit",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/powerLoss",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/powerQuality",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/underVoltage",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/wrongPowerSupply"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTREnergyEVSEFaultState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/contactDryFailure",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/contactWetFailure",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/emergencyStop",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/evDisconnected",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/groundFault",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/liveNeutralSwap",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/meterFailure",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/noError",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/other",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overCurrent",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overTemperature",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/overVoltage",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/pilotShortCircuit",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/powerLoss",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/powerQuality",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/underVoltage",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEFaultState/wrongPowerSupply"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTREnergyEVSEFaultState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1evDisconnected/title",
          "value": "MTREnergyEVSEFaultStateEVDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1evDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateEVDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1contactDryFailure/title",
          "value": "MTREnergyEVSEFaultStateContactDryFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1contactDryFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateContactDryFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1other/title",
          "value": "MTREnergyEVSEFaultStateOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1overVoltage/title",
          "value": "MTREnergyEVSEFaultStateOverVoltage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1overVoltage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateOverVoltage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1liveNeutralSwap/title",
          "value": "MTREnergyEVSEFaultStateLiveNeutralSwap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1liveNeutralSwap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateLiveNeutralSwap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1contactWetFailure/title",
          "value": "MTREnergyEVSEFaultStateContactWetFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1contactWetFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateContactWetFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState/title",
          "value": "MTREnergyEVSEFaultState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1wrongPowerSupply/title",
          "value": "MTREnergyEVSEFaultStateWrongPowerSupply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1wrongPowerSupply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateWrongPowerSupply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1powerLoss/title",
          "value": "MTREnergyEVSEFaultStatePowerLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1powerLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStatePowerLoss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1meterFailure/title",
          "value": "MTREnergyEVSEFaultStateMeterFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1meterFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateMeterFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1underVoltage/title",
          "value": "MTREnergyEVSEFaultStateUnderVoltage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1underVoltage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateUnderVoltage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1powerQuality/title",
          "value": "MTREnergyEVSEFaultStatePowerQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1powerQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStatePowerQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1groundFault/title",
          "value": "MTREnergyEVSEFaultStateGroundFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1groundFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateGroundFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1pilotShortCircuit/title",
          "value": "MTREnergyEVSEFaultStatePilotShortCircuit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1pilotShortCircuit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStatePilotShortCircuit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1noError/title",
          "value": "MTREnergyEVSEFaultStateNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1noError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateNoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1overTemperature/title",
          "value": "MTREnergyEVSEFaultStateOverTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1overTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateOverTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1overCurrent/title",
          "value": "MTREnergyEVSEFaultStateOverCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1overCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateOverCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1emergencyStop/title",
          "value": "MTREnergyEVSEFaultStateEmergencyStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEFaultState~1emergencyStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEFaultStateEmergencyStop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrenergyevsefaultstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrenergyevsefaultstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
