{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTREthernetNetworkDiagnosticsPHYRate",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTREthernetNetworkDiagnosticsPHYRateType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTREthernetNetworkDiagnosticsPHYRateType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTREthernetNetworkDiagnosticsPHYRateType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTREthernetNetworkDiagnosticsPHYRate",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTREthernetNetworkDiagnosticsPHYRate",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTREthernetNetworkDiagnosticsPHYRate",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "Please use MTREthernetNetworkDiagnosticsPHYRate",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTREthernetNetworkDiagnosticsPHYRate",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTREthernetNetworkDiagnosticsPHYRate",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "Please use MTREthernetNetworkDiagnosticsPHYRate",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTREthernetNetworkDiagnosticsPHYRateType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type1000M": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type1000M"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type1000M",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType1000M"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType.type1000M",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/type1000m"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type100G": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type100G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type100G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType100G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType.type100G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/type100g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type100M": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type100M"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type100M",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType100M"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType.type100M",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/type100m"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type10G": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type10G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type10G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType10G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType.type10G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/type10g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type10M": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type10M"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type10M",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType10M"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType.type10M",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/type10m"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type200G": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type200G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type200G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType200G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType.type200G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/type200g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type25G": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type25G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type25G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType25G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType.type25G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/type25g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type400G": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type400G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type400G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType400G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType.type400G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/type400g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type40G": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type40G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type40G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType40G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType.type40G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/type40g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type5G": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type5G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type5G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateType5G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRateType.type5G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype/type5g"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type1000M",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type100G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type100M",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type10G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type10M",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type200G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type25G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type400G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type40G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type5G"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type1000M",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type100G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type100M",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type10G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type10M",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type200G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type25G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type400G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type40G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRateType/type5G"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTREthernetNetworkDiagnosticsPHYRateType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTREthernetNetworkDiagnosticsPHYRate",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type400G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType400G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type400G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType400G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type25G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType25G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type25G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType25G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type100G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType100G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type100G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType100G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type10G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType10G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type10G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType10G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type5G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType5G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type5G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType5G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type100M/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType100M"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type100M/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType100M"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type10M/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType10M"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type10M/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType10M"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type40G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType40G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type40G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType40G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type200G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType200G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type200G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType200G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type1000M/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateType1000M"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRateType~1type1000M/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateType1000M"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrethernetnetworkdiagnosticsphyratetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
