{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This command has been removed",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "deprecated",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.2",
        "introducedAt": "16.1",
        "message": "This command has been removed",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.2",
        "introducedAt": "16.1",
        "message": "This command has been removed",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.2",
        "introducedAt": "16.1",
        "message": "This command has been removed",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.2",
        "introducedAt": "13.0",
        "message": "This command has been removed",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.2",
        "introducedAt": "16.1",
        "message": "This command has been removed",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.2",
        "introducedAt": "1.0",
        "message": "This command has been removed",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.2",
        "introducedAt": "9.1",
        "message": "This command has been removed",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/attributeId": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributeId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/attributeId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributeId"
        }
      ],
      "role": "symbol",
      "title": "attributeId",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams/attributeid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/init(responseValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "responseValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/init(responseValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithResponseValue:error:"
        }
      ],
      "role": "symbol",
      "title": "init(responseValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams/init(responsevalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/intervals": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intervals"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/intervals",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intervals"
        }
      ],
      "role": "symbol",
      "title": "intervals",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams/intervals"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/numberOfIntervalsDelivered": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfIntervalsDelivered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/numberOfIntervalsDelivered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfIntervalsDelivered"
        }
      ],
      "role": "symbol",
      "title": "numberOfIntervalsDelivered",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams/numberofintervalsdelivered"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/profileIntervalPeriod": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "profileIntervalPeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/profileIntervalPeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "profileIntervalPeriod"
        }
      ],
      "role": "symbol",
      "title": "profileIntervalPeriod",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams/profileintervalperiod"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/startTime": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/startTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTime"
        }
      ],
      "role": "symbol",
      "title": "startTime",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams/starttime"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/status": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams/status"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/timedInvokeTimeoutMs": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedInvokeTimeoutMs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/timedInvokeTimeoutMs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timedInvokeTimeoutMs"
        }
      ],
      "role": "symbol",
      "title": "timedInvokeTimeoutMs",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams/timedinvoketimeoutms"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/init(responseValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/attributeId",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/intervals",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/numberOfIntervalsDelivered",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/profileIntervalPeriod",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/startTime",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/status",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/timedInvokeTimeoutMs"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.2",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.2",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.2",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.2",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.2",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.2",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.2",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/init(responseValue:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/attributeId",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/intervals",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/numberOfIntervalsDelivered",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/profileIntervalPeriod",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/startTime",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/status",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/timedInvokeTimeoutMs"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This command has been removed",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1attributeId/title",
          "value": "attributeId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1attributeId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributeId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1intervals/title",
          "value": "intervals"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1intervals/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "intervals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1numberOfIntervalsDelivered/title",
          "value": "numberOfIntervalsDelivered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1numberOfIntervalsDelivered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfIntervalsDelivered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1status/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1timedInvokeTimeoutMs/title",
          "value": "timedInvokeTimeoutMs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1timedInvokeTimeoutMs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timedInvokeTimeoutMs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/title",
          "value": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1startTime/title",
          "value": "startTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1startTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1init(responseValue:)/title",
          "value": "initWithResponseValue:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1init(responseValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithResponseValue:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1profileIntervalPeriod/title",
          "value": "profileIntervalPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams~1profileIntervalPeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "profileIntervalPeriod"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrelectricalmeasurementclustergetmeasurementprofileresponsecommandparams"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
