{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC12MTRErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRError"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTRError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRError"
        }
      ],
      "role": "symbol",
      "title": "MTRError",
      "type": "topic",
      "url": "/documentation/matter/mtrerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/accessDenied": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/accessDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessDenied",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/accessdenied"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/bufferTooSmall": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bufferTooSmall"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/bufferTooSmall",
      "kind": "symbol",
      "role": "symbol",
      "title": "bufferTooSmall",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/buffertoosmall"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/busy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "busy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/busy",
      "kind": "symbol",
      "role": "symbol",
      "title": "busy",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/busy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/cancelled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/cancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "cancelled",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/cancelled"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/dnssdUnauthorized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dnssdUnauthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/dnssdUnauthorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "dnssdUnauthorized",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/dnssdunauthorized"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/errordomain"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/fabricExists": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricExists"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/fabricExists",
      "kind": "symbol",
      "role": "symbol",
      "title": "fabricExists",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/fabricexists"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/generalError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/generalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "generalError",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/generalerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/integrityCheckFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integrityCheckFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/integrityCheckFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "integrityCheckFailed",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/integritycheckfailed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/invalidArgument": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/invalidArgument",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidArgument",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/invalidargument"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/invalidIntegerValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidIntegerValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/invalidIntegerValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidIntegerValue",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/invalidintegervalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/invalidMessageLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidMessageLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/invalidMessageLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidMessageLength",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/invalidmessagelength"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/invalidState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/invalidState",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidState",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/invalidstate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/invalidStringLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidStringLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/invalidStringLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidStringLength",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/invalidstringlength"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/notFound": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/notFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "notFound",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/notfound"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/schemaMismatch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "schemaMismatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/schemaMismatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "schemaMismatch",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/schemamismatch"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/timeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/timeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeout",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/timeout"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/tlvDecodeFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tlvDecodeFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/tlvDecodeFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "tlvDecodeFailed",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/tlvdecodefailed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/unknownSchema": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownSchema"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/unknownSchema",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownSchema",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/unknownschema"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/wrongAddressType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wrongAddressType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MTRErrorCodeLeV",
          "text": "MTRError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/wrongAddressType",
      "kind": "symbol",
      "role": "symbol",
      "title": "wrongAddressType",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/wrongaddresstype"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRError/bufferTooSmall",
        "doc://com.apple.matter/documentation/Matter/MTRError/cancelled",
        "doc://com.apple.matter/documentation/Matter/MTRError/dnssdUnauthorized",
        "doc://com.apple.matter/documentation/Matter/MTRError/fabricExists",
        "doc://com.apple.matter/documentation/Matter/MTRError/generalError",
        "doc://com.apple.matter/documentation/Matter/MTRError/integrityCheckFailed",
        "doc://com.apple.matter/documentation/Matter/MTRError/invalidArgument",
        "doc://com.apple.matter/documentation/Matter/MTRError/invalidIntegerValue",
        "doc://com.apple.matter/documentation/Matter/MTRError/invalidMessageLength",
        "doc://com.apple.matter/documentation/Matter/MTRError/invalidState",
        "doc://com.apple.matter/documentation/Matter/MTRError/invalidStringLength",
        "doc://com.apple.matter/documentation/Matter/MTRError/schemaMismatch",
        "doc://com.apple.matter/documentation/Matter/MTRError/timeout",
        "doc://com.apple.matter/documentation/Matter/MTRError/tlvDecodeFailed",
        "doc://com.apple.matter/documentation/Matter/MTRError/unknownSchema",
        "doc://com.apple.matter/documentation/Matter/MTRError/wrongAddressType",
        "doc://com.apple.matter/documentation/Matter/MTRError/accessDenied",
        "doc://com.apple.matter/documentation/Matter/MTRError/busy",
        "doc://com.apple.matter/documentation/Matter/MTRError/errorDomain",
        "doc://com.apple.matter/documentation/Matter/MTRError/notFound"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRError/Code"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code/title",
          "value": "MTRErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
