{
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTREnergyEVSEModeModeTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTREnergyEVSEModeModeTag"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTREnergyEVSEModeModeTag"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTREnergyEVSEModeModeTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTag"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTag"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/V2X": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "V2X"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/V2X",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagV2X"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.V2X",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/v2x"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/auto": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagAuto"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/day": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "day"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/day",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagDay"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.day",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/day"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/lowEnergy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowEnergy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/lowEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagLowEnergy"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.lowEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/lowenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/lowNoise": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowNoise"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/lowNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagLowNoise"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.lowNoise",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/lownoise"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/manual": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manual"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/manual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagManual"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.manual",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/manual"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/max": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagMax"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.max",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/max"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/min": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagMin"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.min",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/min"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/night": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "night"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/night",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagNight"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.night",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/night"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/quick": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quick"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/quick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagQuick"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.quick",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/quick"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/quiet": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quiet"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/quiet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagQuiet"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.quiet",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/quiet"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/solarCharging": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "solarCharging"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/solarCharging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagSolarCharging"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.solarCharging",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/solarcharging"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/timeOfUse": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeOfUse"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/timeOfUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagTimeOfUse"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.timeOfUse",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/timeofuse"
    },
    "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/vacation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vacation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/vacation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREnergyEVSEModeModeTagVacation"
        }
      ],
      "role": "symbol",
      "title": "MTREnergyEVSEModeModeTag.vacation",
      "type": "topic",
      "url": "/documentation/matter/mtrenergyevsemodemodetag/vacation"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/V2X",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/auto",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/day",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/lowEnergy",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/lowNoise",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/manual",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/max",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/min",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/night",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/quick",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/quiet",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/solarCharging",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/timeOfUse",
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/vacation"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTREnergyEVSEModeModeTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/V2X",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/auto",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/day",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/lowEnergy",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/lowNoise",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/manual",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/max",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/min",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/night",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/quick",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/quiet",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/solarCharging",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/timeOfUse",
                "doc://com.apple.matter/documentation/Matter/MTREnergyEVSEModeModeTag/vacation"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTREnergyEVSEModeModeTag"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag/title",
          "value": "MTREnergyEVSEModeModeTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1lowEnergy/title",
          "value": "MTREnergyEVSEModeModeTagLowEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1lowEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagLowEnergy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1auto/title",
          "value": "MTREnergyEVSEModeModeTagAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1timeOfUse/title",
          "value": "MTREnergyEVSEModeModeTagTimeOfUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1timeOfUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagTimeOfUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1day/title",
          "value": "MTREnergyEVSEModeModeTagDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1day/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1quick/title",
          "value": "MTREnergyEVSEModeModeTagQuick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1quick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagQuick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1lowNoise/title",
          "value": "MTREnergyEVSEModeModeTagLowNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1lowNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagLowNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1vacation/title",
          "value": "MTREnergyEVSEModeModeTagVacation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1vacation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagVacation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1V2X/title",
          "value": "MTREnergyEVSEModeModeTagV2X"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1V2X/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagV2X"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1min/title",
          "value": "MTREnergyEVSEModeModeTagMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1solarCharging/title",
          "value": "MTREnergyEVSEModeModeTagSolarCharging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1solarCharging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagSolarCharging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1quiet/title",
          "value": "MTREnergyEVSEModeModeTagQuiet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1quiet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagQuiet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1night/title",
          "value": "MTREnergyEVSEModeModeTagNight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1night/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagNight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1max/title",
          "value": "MTREnergyEVSEModeModeTagMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1manual/title",
          "value": "MTREnergyEVSEModeModeTagManual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREnergyEVSEModeModeTag~1manual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREnergyEVSEModeModeTagManual"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrenergyevsemodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrenergyevsemodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
