{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTREthernetNetworkDiagnosticsPHYRate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTREthernetNetworkDiagnosticsPHYRate"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTREthernetNetworkDiagnosticsPHYRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTREthernetNetworkDiagnosticsPHYRate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRate"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate100G": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate100G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate100G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateRate100G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate.rate100G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/rate100g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate100M": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate100M"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate100M",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateRate100M"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate.rate100M",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/rate100m"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate10G": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate10G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate10G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateRate10G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate.rate10G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/rate10g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate10M": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate10M"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate10M",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateRate10M"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate.rate10M",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/rate10m"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate1G": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate1G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate1G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateRate1G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate.rate1G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/rate1g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate200G": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate200G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate200G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateRate200G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate.rate200G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/rate200g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate25G": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate25G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate25G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateRate25G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate.rate25G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/rate25g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate400G": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate400G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate400G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateRate400G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate.rate400G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/rate400g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate40G": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate40G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate40G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateRate40G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate.rate40G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/rate40g"
    },
    "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate5G": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate5G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate5G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREthernetNetworkDiagnosticsPHYRateRate5G"
        }
      ],
      "role": "symbol",
      "title": "MTREthernetNetworkDiagnosticsPHYRate.rate5G",
      "type": "topic",
      "url": "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate/rate5g"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate100G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate100M",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate10G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate10M",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate1G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate200G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate25G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate400G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate40G",
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate5G"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate100G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate100M",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate10G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate10M",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate1G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate200G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate25G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate400G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate40G",
                "doc://com.apple.matter/documentation/Matter/MTREthernetNetworkDiagnosticsPHYRate/rate5G"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTREthernetNetworkDiagnosticsPHYRate"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate200G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateRate200G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate200G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateRate200G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate1G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateRate1G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate1G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateRate1G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate10M/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateRate10M"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate10M/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateRate10M"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate400G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateRate400G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate400G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateRate400G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate40G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateRate40G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate40G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateRate40G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate10G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateRate10G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate10G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateRate10G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate5G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateRate5G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate5G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateRate5G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate25G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateRate25G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate25G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateRate25G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate100G/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateRate100G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate100G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateRate100G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate100M/title",
          "value": "MTREthernetNetworkDiagnosticsPHYRateRate100M"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREthernetNetworkDiagnosticsPHYRate~1rate100M/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREthernetNetworkDiagnosticsPHYRateRate100M"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrethernetnetworkdiagnosticsphyrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
