{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRElectricalPowerMeasurementClusterMeasurementRangeStruct",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/endSystime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endSystime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/endSystime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endSystime"
        }
      ],
      "role": "symbol",
      "title": "endSystime",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/endsystime"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/endTimestamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/endTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endTimestamp"
        }
      ],
      "role": "symbol",
      "title": "endTimestamp",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/endtimestamp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/max": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "role": "symbol",
      "title": "max",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/max"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/maxSystime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxSystime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/maxSystime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxSystime"
        }
      ],
      "role": "symbol",
      "title": "maxSystime",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/maxsystime"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/maxTimestamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/maxTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxTimestamp"
        }
      ],
      "role": "symbol",
      "title": "maxTimestamp",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/maxtimestamp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/measurementType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measurementType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/measurementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measurementType"
        }
      ],
      "role": "symbol",
      "title": "measurementType",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/measurementtype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/min": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "role": "symbol",
      "title": "min",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/min"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/minSystime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minSystime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/minSystime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minSystime"
        }
      ],
      "role": "symbol",
      "title": "minSystime",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/minsystime"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/minTimestamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/minTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minTimestamp"
        }
      ],
      "role": "symbol",
      "title": "minTimestamp",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/mintimestamp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/startSystime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startSystime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/startSystime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startSystime"
        }
      ],
      "role": "symbol",
      "title": "startSystime",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/startsystime"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/startTimestamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/startTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTimestamp"
        }
      ],
      "role": "symbol",
      "title": "startTimestamp",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct/starttimestamp"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/endSystime",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/endTimestamp",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/max",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/maxSystime",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/maxTimestamp",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/measurementType",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/min",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/minSystime",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/minTimestamp",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/startSystime",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/startTimestamp"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/endSystime",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/endTimestamp",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/max",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/maxSystime",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/maxTimestamp",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/measurementType",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/min",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/minSystime",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/minTimestamp",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/startSystime",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/startTimestamp"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1endSystime/title",
          "value": "endSystime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1endSystime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endSystime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1startSystime/title",
          "value": "startSystime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1startSystime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startSystime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1max/title",
          "value": "max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1maxSystime/title",
          "value": "maxSystime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1maxSystime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxSystime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1minTimestamp/title",
          "value": "minTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1minTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1maxTimestamp/title",
          "value": "maxTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1maxTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1endTimestamp/title",
          "value": "endTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1endTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/title",
          "value": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalPowerMeasurementClusterMeasurementRangeStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1measurementType/title",
          "value": "measurementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1measurementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "measurementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1minSystime/title",
          "value": "minSystime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1minSystime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minSystime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1startTimestamp/title",
          "value": "startTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1startTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1min/title",
          "value": "min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalPowerMeasurementClusterMeasurementRangeStruct~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrelectricalpowermeasurementclustermeasurementrangestruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
