{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRElectricalEnergyMeasurementMeasurementType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRElectricalEnergyMeasurementMeasurementType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRElectricalEnergyMeasurementMeasurementType"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRElectricalEnergyMeasurementMeasurementType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementType"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/activeCurrent": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/activeCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeActiveCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.activeCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/activecurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/activePower": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activePower"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/activePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeActivePower"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.activePower",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/activepower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/apparentCurrent": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apparentCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/apparentCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeApparentCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.apparentCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/apparentcurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/apparentPower": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apparentPower"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/apparentPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeApparentPower"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.apparentPower",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/apparentpower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/electricalEnergy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "electricalEnergy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/electricalEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeElectricalEnergy"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.electricalEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/electricalenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/frequency": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frequency"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/frequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeFrequency"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.frequency",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/frequency"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/neutralCurrent": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "neutralCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/neutralCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeNeutralCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.neutralCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/neutralcurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/powerFactor": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerFactor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/powerFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypePowerFactor"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.powerFactor",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/powerfactor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/reactiveCurrent": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reactiveCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/reactiveCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeReactiveCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.reactiveCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/reactivecurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/reactivePower": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reactivePower"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/reactivePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeReactivePower"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.reactivePower",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/reactivepower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsCurrent": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rmsCurrent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeRMSCurrent"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.rmsCurrent",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/rmscurrent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsPower": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rmsPower"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeRMSPower"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.rmsPower",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/rmspower"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsVoltage": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rmsVoltage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsVoltage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeRMSVoltage"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.rmsVoltage",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/rmsvoltage"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/unspecified": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/unspecified"
    },
    "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/voltage": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voltage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/voltage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRElectricalEnergyMeasurementMeasurementTypeVoltage"
        }
      ],
      "role": "symbol",
      "title": "MTRElectricalEnergyMeasurementMeasurementType.voltage",
      "type": "topic",
      "url": "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype/voltage"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/activeCurrent",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/activePower",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/apparentCurrent",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/apparentPower",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/electricalEnergy",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/frequency",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/neutralCurrent",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/powerFactor",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/reactiveCurrent",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/reactivePower",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsCurrent",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsPower",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsVoltage",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/unspecified",
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/voltage"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/activeCurrent",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/activePower",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/apparentCurrent",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/apparentPower",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/electricalEnergy",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/frequency",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/neutralCurrent",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/powerFactor",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/reactiveCurrent",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/reactivePower",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsCurrent",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsPower",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/rmsVoltage",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/unspecified",
                "doc://com.apple.matter/documentation/Matter/MTRElectricalEnergyMeasurementMeasurementType/voltage"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRElectricalEnergyMeasurementMeasurementType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1activePower/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeActivePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1activePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeActivePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1voltage/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeVoltage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1voltage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeVoltage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1rmsVoltage/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeRMSVoltage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1rmsVoltage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeRMSVoltage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1rmsCurrent/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeRMSCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1rmsCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeRMSCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1neutralCurrent/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeNeutralCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1neutralCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeNeutralCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1unspecified/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1activeCurrent/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeActiveCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1activeCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeActiveCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1frequency/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1frequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1electricalEnergy/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeElectricalEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1electricalEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeElectricalEnergy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1reactiveCurrent/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeReactiveCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1reactiveCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeReactiveCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1powerFactor/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypePowerFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1powerFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypePowerFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1apparentCurrent/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeApparentCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1apparentCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeApparentCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1apparentPower/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeApparentPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1apparentPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeApparentPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1reactivePower/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeReactivePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1reactivePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeReactivePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1rmsPower/title",
          "value": "MTRElectricalEnergyMeasurementMeasurementTypeRMSPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRElectricalEnergyMeasurementMeasurementType~1rmsPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRElectricalEnergyMeasurementMeasurementTypeRMSPower"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrelectricalenergymeasurementmeasurementtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
