{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRFanControlFanModeSequence",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRFanControlFanModeSequenceType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRFanControlFanModeSequenceType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRFanControlFanModeSequenceType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.1",
        "message": "Please use MTRFanControlFanModeSequence",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.1",
        "message": "Please use MTRFanControlFanModeSequence",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.1",
        "message": "Please use MTRFanControlFanModeSequence",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.0",
        "message": "Please use MTRFanControlFanModeSequence",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.1",
        "message": "Please use MTRFanControlFanModeSequence",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRFanControlFanModeSequence",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "9.1",
        "message": "Please use MTRFanControlFanModeSequence",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRFanControlFanModeSequenceType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceType"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequenceType",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequencetype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequencetype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowHigh": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offLowHigh"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceTypeOffLowHigh"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequenceType.offLowHigh",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequencetype/offlowhigh"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowHighAuto": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offLowHighAuto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowHighAuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceTypeOffLowHighAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequenceType.offLowHighAuto",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequencetype/offlowhighauto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowMedHigh": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offLowMedHigh"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowMedHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceTypeOffLowMedHigh"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequenceType.offLowMedHigh",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequencetype/offlowmedhigh"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowMedHighAuto": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offLowMedHighAuto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowMedHighAuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceTypeOffLowMedHighAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequenceType.offLowMedHighAuto",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequencetype/offlowmedhighauto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offOn": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offOn"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offOn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceTypeOffOn"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequenceType.offOn",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequencetype/offon"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offOnAuto": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offOnAuto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offOnAuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceTypeOffOnAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequenceType.offOnAuto",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequencetype/offonauto"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowHigh",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowHighAuto",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowMedHigh",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowMedHighAuto",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offOn",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offOnAuto"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRFanControlFanModeSequenceType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowHigh",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowHighAuto",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowMedHigh",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offLowMedHighAuto",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offOn",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequenceType/offOnAuto"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRFanControlFanModeSequenceType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRFanControlFanModeSequence",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType/title",
          "value": "MTRFanControlFanModeSequenceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offLowMedHigh/title",
          "value": "MTRFanControlFanModeSequenceTypeOffLowMedHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offLowMedHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceTypeOffLowMedHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offLowMedHighAuto/title",
          "value": "MTRFanControlFanModeSequenceTypeOffLowMedHighAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offLowMedHighAuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceTypeOffLowMedHighAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offOnAuto/title",
          "value": "MTRFanControlFanModeSequenceTypeOffOnAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offOnAuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceTypeOffOnAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offLowHighAuto/title",
          "value": "MTRFanControlFanModeSequenceTypeOffLowHighAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offLowHighAuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceTypeOffLowHighAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offOn/title",
          "value": "MTRFanControlFanModeSequenceTypeOffOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offOn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceTypeOffOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offLowHigh/title",
          "value": "MTRFanControlFanModeSequenceTypeOffLowHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequenceType~1offLowHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceTypeOffLowHigh"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrfancontrolfanmodesequencetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrfancontrolfanmodesequencetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
