{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRFanControlFanModeSequence",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRFanControlFanModeSequence"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRFanControlFanModeSequence"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRFanControlFanModeSequence"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequence"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequence"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequence"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequence",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequence"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequence/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offHigh": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offHigh"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceOffHigh"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequence.offHigh",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequence/offhigh"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offHighAuto": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offHighAuto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offHighAuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceOffHighAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequence.offHighAuto",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequence/offhighauto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowHigh": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offLowHigh"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceOffLowHigh"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequence.offLowHigh",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequence/offlowhigh"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowHighAuto": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offLowHighAuto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowHighAuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceOffLowHighAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequence.offLowHighAuto",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequence/offlowhighauto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowMedHigh": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offLowMedHigh"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowMedHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceOffLowMedHigh"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequence.offLowMedHigh",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequence/offlowmedhigh"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowMedHighAuto": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offLowMedHighAuto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowMedHighAuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceOffLowMedHighAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRFanControlFanModeSequence.offLowMedHighAuto",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequence/offlowmedhighauto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offOn": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offOn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRFanControlFanModeSequence",
          "text": "MTRFanControlFanModeSequence"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offOn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceOffOn"
        }
      ],
      "role": "symbol",
      "title": "offOn",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequence/offon"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offOnAuto": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offOnAuto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRFanControlFanModeSequence",
          "text": "MTRFanControlFanModeSequence"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offOnAuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFanControlFanModeSequenceOffOnAuto"
        }
      ],
      "role": "symbol",
      "title": "offOnAuto",
      "type": "topic",
      "url": "/documentation/matter/mtrfancontrolfanmodesequence/offonauto"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offHigh",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offHighAuto",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowHigh",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowHighAuto",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowMedHigh",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowMedHighAuto"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offOn",
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offOnAuto"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRFanControlFanModeSequence"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offHigh",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offHighAuto",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowHigh",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowHighAuto",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowMedHigh",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offLowMedHighAuto"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offOn",
                "doc://com.apple.matter/documentation/Matter/MTRFanControlFanModeSequence/offOnAuto"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRFanControlFanModeSequence"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offOn/title",
          "value": "MTRFanControlFanModeSequenceOffOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offOn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceOffOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offOnAuto/title",
          "value": "MTRFanControlFanModeSequenceOffOnAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offOnAuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceOffOnAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offHighAuto/title",
          "value": "MTRFanControlFanModeSequenceOffHighAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offHighAuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceOffHighAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offLowMedHigh/title",
          "value": "MTRFanControlFanModeSequenceOffLowMedHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offLowMedHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceOffLowMedHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offLowHigh/title",
          "value": "MTRFanControlFanModeSequenceOffLowHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offLowHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceOffLowHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offLowMedHighAuto/title",
          "value": "MTRFanControlFanModeSequenceOffLowMedHighAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offLowMedHighAuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceOffLowMedHighAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence/title",
          "value": "MTRFanControlFanModeSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offHigh/title",
          "value": "MTRFanControlFanModeSequenceOffHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceOffHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offLowHighAuto/title",
          "value": "MTRFanControlFanModeSequenceOffLowHighAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFanControlFanModeSequence~1offLowHighAuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFanControlFanModeSequenceOffLowHighAuto"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrfancontrolfanmodesequence"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrfancontrolfanmodesequence"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
