{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRGeneralDiagnosticsHardwareFault",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRGeneralDiagnosticsHardwareFaultType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRGeneralDiagnosticsHardwareFaultType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRGeneralDiagnosticsHardwareFaultType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRGeneralDiagnosticsHardwareFault",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRGeneralDiagnosticsHardwareFault",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRGeneralDiagnosticsHardwareFault",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "Please use MTRGeneralDiagnosticsHardwareFault",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRGeneralDiagnosticsHardwareFault",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRGeneralDiagnosticsHardwareFault",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "Please use MTRGeneralDiagnosticsHardwareFault",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRGeneralDiagnosticsHardwareFaultType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultType"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/audioOutputFault": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioOutputFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/audioOutputFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypeAudioOutputFault"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.audioOutputFault",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/audiooutputfault"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/nonResettableOverTemp": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonResettableOverTemp"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/nonResettableOverTemp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypeNonResettableOverTemp"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.nonResettableOverTemp",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/nonresettableovertemp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/nonVolatileMemoryError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonVolatileMemoryError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/nonVolatileMemoryError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypeNonVolatileMemoryError"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.nonVolatileMemoryError",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/nonvolatilememoryerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/powerSource": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/powerSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypePowerSource"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.powerSource",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/powersource"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/radio": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "radio"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/radio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypeRadio"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.radio",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/radio"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/resettableOverTemp": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resettableOverTemp"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/resettableOverTemp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypeResettableOverTemp"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.resettableOverTemp",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/resettableovertemp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/sensor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/sensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypeSensor"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.sensor",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/sensor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/tamperDetected": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tamperDetected"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/tamperDetected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypeTamperDetected"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.tamperDetected",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/tamperdetected"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/unspecified": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/unspecified"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/userInterfaceFault": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/userInterfaceFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypeUserInterfaceFault"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.userInterfaceFault",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/userinterfacefault"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/visualDisplayFault": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visualDisplayFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/visualDisplayFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTypeVisualDisplayFault"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFaultType.visualDisplayFault",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype/visualdisplayfault"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/audioOutputFault",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/nonResettableOverTemp",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/nonVolatileMemoryError",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/powerSource",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/radio",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/resettableOverTemp",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/sensor",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/tamperDetected",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/unspecified",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/userInterfaceFault",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/visualDisplayFault"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/audioOutputFault",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/nonResettableOverTemp",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/nonVolatileMemoryError",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/powerSource",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/radio",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/resettableOverTemp",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/sensor",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/tamperDetected",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/unspecified",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/userInterfaceFault",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFaultType/visualDisplayFault"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRGeneralDiagnosticsHardwareFaultType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRGeneralDiagnosticsHardwareFault",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1userInterfaceFault/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypeUserInterfaceFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1userInterfaceFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypeUserInterfaceFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1unspecified/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1sensor/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypeSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1sensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypeSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1visualDisplayFault/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypeVisualDisplayFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1visualDisplayFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypeVisualDisplayFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1resettableOverTemp/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypeResettableOverTemp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1resettableOverTemp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypeResettableOverTemp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1nonVolatileMemoryError/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypeNonVolatileMemoryError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1nonVolatileMemoryError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypeNonVolatileMemoryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1audioOutputFault/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypeAudioOutputFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1audioOutputFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypeAudioOutputFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1radio/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypeRadio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1radio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypeRadio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1tamperDetected/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypeTamperDetected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1tamperDetected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypeTamperDetected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1nonResettableOverTemp/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypeNonResettableOverTemp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1nonResettableOverTemp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypeNonResettableOverTemp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1powerSource/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTypePowerSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFaultType~1powerSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTypePowerSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrgeneraldiagnosticshardwarefaulttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
