{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRGeneralDiagnosticsHardwareFault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRGeneralDiagnosticsHardwareFault"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRGeneralDiagnosticsHardwareFault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRGeneralDiagnosticsHardwareFault"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFault"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFault"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/audioOutputFault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioOutputFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/audioOutputFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultAudioOutputFault"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.audioOutputFault",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/audiooutputfault"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/nonResettableOverTemp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonResettableOverTemp"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/nonResettableOverTemp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultNonResettableOverTemp"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.nonResettableOverTemp",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/nonresettableovertemp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/nonVolatileMemoryError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonVolatileMemoryError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/nonVolatileMemoryError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultNonVolatileMemoryError"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.nonVolatileMemoryError",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/nonvolatilememoryerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/powerSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/powerSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultPowerSource"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.powerSource",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/powersource"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/radio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "radio"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/radio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultRadio"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.radio",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/radio"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/resettableOverTemp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resettableOverTemp"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/resettableOverTemp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultResettableOverTemp"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.resettableOverTemp",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/resettableovertemp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/sensor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/sensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultSensor"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.sensor",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/sensor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/tamperDetected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tamperDetected"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/tamperDetected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultTamperDetected"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.tamperDetected",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/tamperdetected"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/unspecified"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/userInterfaceFault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/userInterfaceFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultUserInterfaceFault"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.userInterfaceFault",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/userinterfacefault"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/visualDisplayFault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visualDisplayFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/visualDisplayFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsHardwareFaultVisualDisplayFault"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsHardwareFault.visualDisplayFault",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticshardwarefault/visualdisplayfault"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/audioOutputFault",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/nonResettableOverTemp",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/nonVolatileMemoryError",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/powerSource",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/radio",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/resettableOverTemp",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/sensor",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/tamperDetected",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/unspecified",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/userInterfaceFault",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/visualDisplayFault"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRGeneralDiagnosticsHardwareFault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/audioOutputFault",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/nonResettableOverTemp",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/nonVolatileMemoryError",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/powerSource",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/radio",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/resettableOverTemp",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/sensor",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/tamperDetected",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/unspecified",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/userInterfaceFault",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsHardwareFault/visualDisplayFault"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRGeneralDiagnosticsHardwareFault"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1tamperDetected/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultTamperDetected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1tamperDetected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultTamperDetected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1sensor/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1sensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1nonResettableOverTemp/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultNonResettableOverTemp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1nonResettableOverTemp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultNonResettableOverTemp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1resettableOverTemp/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultResettableOverTemp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1resettableOverTemp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultResettableOverTemp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1userInterfaceFault/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultUserInterfaceFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1userInterfaceFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultUserInterfaceFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1unspecified/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1powerSource/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultPowerSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1powerSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultPowerSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1visualDisplayFault/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultVisualDisplayFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1visualDisplayFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultVisualDisplayFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1radio/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultRadio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1radio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultRadio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1audioOutputFault/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultAudioOutputFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1audioOutputFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultAudioOutputFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault/title",
          "value": "MTRGeneralDiagnosticsHardwareFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1nonVolatileMemoryError/title",
          "value": "MTRGeneralDiagnosticsHardwareFaultNonVolatileMemoryError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsHardwareFault~1nonVolatileMemoryError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsHardwareFaultNonVolatileMemoryError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrgeneraldiagnosticshardwarefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrgeneraldiagnosticshardwarefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
