{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRGeneralDiagnosticsClusterNetworkInterface",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRGeneralDiagnosticsClusterNetworkInterfaceType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRGeneralDiagnosticsClusterNetworkInterface",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRGeneralDiagnosticsClusterNetworkInterface",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRGeneralDiagnosticsClusterNetworkInterface",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "Please use MTRGeneralDiagnosticsClusterNetworkInterface",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRGeneralDiagnosticsClusterNetworkInterface",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRGeneralDiagnosticsClusterNetworkInterface",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "Please use MTRGeneralDiagnosticsClusterNetworkInterface",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsClusterNetworkInterface"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsClusterNetworkInterface"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsClusterNetworkInterface",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterface"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
        }
      ],
      "role": "symbol",
      "title": "MTRGeneralDiagnosticsClusterNetworkInterfaceType",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/hardwareAddress": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardwareAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/hardwareAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hardwareAddress"
        }
      ],
      "role": "symbol",
      "title": "hardwareAddress",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype/hardwareaddress"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/iPv4Addresses": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iPv4Addresses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/iPv4Addresses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iPv4Addresses"
        }
      ],
      "role": "symbol",
      "title": "iPv4Addresses",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype/ipv4addresses"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/iPv6Addresses": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iPv6Addresses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/iPv6Addresses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iPv6Addresses"
        }
      ],
      "role": "symbol",
      "title": "iPv6Addresses",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype/ipv6addresses"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/isOperational": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isOperational"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/isOperational",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isOperational"
        }
      ],
      "role": "symbol",
      "title": "isOperational",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype/isoperational"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/name": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype/name"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/offPremiseServicesReachableIPv4": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offPremiseServicesReachableIPv4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/offPremiseServicesReachableIPv4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "offPremiseServicesReachableIPv4"
        }
      ],
      "role": "symbol",
      "title": "offPremiseServicesReachableIPv4",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype/offpremiseservicesreachableipv4"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/offPremiseServicesReachableIPv6": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offPremiseServicesReachableIPv6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/offPremiseServicesReachableIPv6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "offPremiseServicesReachableIPv6"
        }
      ],
      "role": "symbol",
      "title": "offPremiseServicesReachableIPv6",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype/offpremiseservicesreachableipv6"
    },
    "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/type": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype/type"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterface"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/hardwareAddress",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/iPv4Addresses",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/iPv6Addresses",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/isOperational",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/name",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/offPremiseServicesReachableIPv4",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/offPremiseServicesReachableIPv6",
        "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/type"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/hardwareAddress",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/iPv4Addresses",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/iPv6Addresses",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/isOperational",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/name",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/offPremiseServicesReachableIPv4",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/offPremiseServicesReachableIPv6",
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterfaceType/type"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterface"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRGeneralDiagnosticsClusterNetworkInterface",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRGeneralDiagnosticsClusterNetworkInterface",
                    "text": "MTRGeneralDiagnosticsClusterNetworkInterface"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRGeneralDiagnosticsClusterNetworkInterface",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1isOperational/title",
          "value": "isOperational"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1isOperational/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isOperational"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1hardwareAddress/title",
          "value": "hardwareAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1hardwareAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hardwareAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1offPremiseServicesReachableIPv6/title",
          "value": "offPremiseServicesReachableIPv6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1offPremiseServicesReachableIPv6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "offPremiseServicesReachableIPv6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1iPv6Addresses/title",
          "value": "iPv6Addresses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1iPv6Addresses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iPv6Addresses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType/title",
          "value": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsClusterNetworkInterfaceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1iPv4Addresses/title",
          "value": "iPv4Addresses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1iPv4Addresses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iPv4Addresses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterface/title",
          "value": "MTRGeneralDiagnosticsClusterNetworkInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsClusterNetworkInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRGeneralDiagnosticsClusterNetworkInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1offPremiseServicesReachableIPv4/title",
          "value": "offPremiseServicesReachableIPv4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRGeneralDiagnosticsClusterNetworkInterfaceType~1offPremiseServicesReachableIPv4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "offPremiseServicesReachableIPv4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrgeneraldiagnosticsclusternetworkinterfacetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
