{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRInteractionError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC23MTRInteractionErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRInteractionError"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRInteractionError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTRInteractionError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRInteractionError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRInteractionError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionError"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/busy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "busy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/busy",
      "kind": "symbol",
      "role": "symbol",
      "title": "busy",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/busy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/constraintError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraintError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/constraintError",
      "kind": "symbol",
      "role": "symbol",
      "title": "constraintError",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/constrainterror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/dataVersionMismatch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataVersionMismatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/dataVersionMismatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataVersionMismatch",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/dataversionmismatch"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/errordomain"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/failsafeRequired": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failsafeRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/failsafeRequired",
      "kind": "symbol",
      "role": "symbol",
      "title": "failsafeRequired",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/failsaferequired"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/failure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/failure",
      "kind": "symbol",
      "role": "symbol",
      "title": "failure",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/failure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidAction",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/invalidaction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidCommand",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidCommand",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/invalidcommand"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidDataType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidDataType",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidDataType",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/invaliddatatype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidInState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidInState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidInState",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidInState",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/invalidinstate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidSubscription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSubscription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidSubscription",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidSubscription",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/invalidsubscription"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/needsTimedInteraction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needsTimedInteraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/needsTimedInteraction",
      "kind": "symbol",
      "role": "symbol",
      "title": "needsTimedInteraction",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/needstimedinteraction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/noCommandResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCommandResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/noCommandResponse",
      "kind": "symbol",
      "role": "symbol",
      "title": "noCommandResponse",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/nocommandresponse"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/noUpstreamSubscription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noUpstreamSubscription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/noUpstreamSubscription",
      "kind": "symbol",
      "role": "symbol",
      "title": "noUpstreamSubscription",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/noupstreamsubscription"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/notFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/notFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "notFound",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/notfound"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/pathsExhausted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pathsExhausted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/pathsExhausted",
      "kind": "symbol",
      "role": "symbol",
      "title": "pathsExhausted",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/pathsexhausted"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/resourceExhausted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceExhausted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/resourceExhausted",
      "kind": "symbol",
      "role": "symbol",
      "title": "resourceExhausted",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/resourceexhausted"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/timedRequestMismatch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedRequestMismatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/timedRequestMismatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "timedRequestMismatch",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/timedrequestmismatch"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/timeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/timeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeout",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/timeout"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unreportableAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unreportableAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unreportableAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "unreportableAttribute",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/unreportableattribute"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedAccess",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedAccess",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/unsupportedaccess"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedAttribute",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/unsupportedattribute"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedCluster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedCluster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedCluster",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedCluster",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/unsupportedcluster"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedCommand",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedCommand",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/unsupportedcommand"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedEndpoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedEndpoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedEndpoint",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/unsupportedendpoint"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedEvent",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/unsupportedevent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedRead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedRead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedRead",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedRead",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/unsupportedread"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedWrite": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedWrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23MTRInteractionErrorCodeLeV",
          "text": "MTRInteractionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRInteractionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedWrite",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedWrite",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/unsupportedwrite"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/busy",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/constraintError",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/dataVersionMismatch",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/failsafeRequired",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/failure",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidAction",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidCommand",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidDataType",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidInState",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/invalidSubscription",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/needsTimedInteraction",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/noCommandResponse",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/noUpstreamSubscription",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/notFound",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/pathsExhausted",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/resourceExhausted",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/timedRequestMismatch",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/timeout",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unreportableAttribute",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedAccess",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedAttribute",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedCluster",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedCommand",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedEndpoint",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedEvent",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedRead",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/unsupportedWrite",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/errorDomain"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code/title",
          "value": "MTRInteractionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrinteractionerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
