{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRICDManagementUserActiveModeTriggerBitmap"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRICDManagementUserActiveModeTriggerBitmap"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTRICDManagementUserActiveModeTriggerBitmap"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmap"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "role": "symbol",
      "title": "MTRICDManagementUserActiveModeTriggerBitmap",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensor": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actuateSensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensor"
        }
      ],
      "role": "symbol",
      "title": "actuateSensor",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/actuatesensor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorLightsBlink": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actuateSensorLightsBlink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorLightsBlink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensorLightsBlink"
        }
      ],
      "role": "symbol",
      "title": "actuateSensorLightsBlink",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/actuatesensorlightsblink"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorSeconds": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actuateSensorSeconds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensorSeconds"
        }
      ],
      "role": "symbol",
      "title": "actuateSensorSeconds",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/actuatesensorseconds"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorTimes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actuateSensorTimes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorTimes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensorTimes"
        }
      ],
      "role": "symbol",
      "title": "actuateSensorTimes",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/actuatesensortimes"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/appDefinedButton": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appDefinedButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/appDefinedButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapAppDefinedButton"
        }
      ],
      "role": "symbol",
      "title": "appDefinedButton",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/appdefinedbutton"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/customInstruction": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customInstruction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/customInstruction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapCustomInstruction"
        }
      ],
      "role": "symbol",
      "title": "customInstruction",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/custominstruction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/deviceManual": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceManual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/deviceManual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapDeviceManual"
        }
      ],
      "role": "symbol",
      "title": "deviceManual",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/devicemanual"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/powerCycle": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerCycle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/powerCycle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapPowerCycle"
        }
      ],
      "role": "symbol",
      "title": "powerCycle",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/powercycle"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButton": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapResetButton"
        }
      ],
      "role": "symbol",
      "title": "resetButton",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/resetbutton"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonLightsBlink": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetButtonLightsBlink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonLightsBlink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapResetButtonLightsBlink"
        }
      ],
      "role": "symbol",
      "title": "resetButtonLightsBlink",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/resetbuttonlightsblink"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonSeconds": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetButtonSeconds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapResetButtonSeconds"
        }
      ],
      "role": "symbol",
      "title": "resetButtonSeconds",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/resetbuttonseconds"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonTimes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetButtonTimes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonTimes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapResetButtonTimes"
        }
      ],
      "role": "symbol",
      "title": "resetButtonTimes",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/resetbuttontimes"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/settingsMenu": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "settingsMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/settingsMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapSettingsMenu"
        }
      ],
      "role": "symbol",
      "title": "settingsMenu",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/settingsmenu"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButton": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setupButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapSetupButton"
        }
      ],
      "role": "symbol",
      "title": "setupButton",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/setupbutton"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonLightsBlink": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setupButtonLightsBlink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonLightsBlink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapSetupButtonLightsBlink"
        }
      ],
      "role": "symbol",
      "title": "setupButtonLightsBlink",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/setupbuttonlightsblink"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonSeconds": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setupButtonSeconds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapSetupButtonSeconds"
        }
      ],
      "role": "symbol",
      "title": "setupButtonSeconds",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/setupbuttonseconds"
    },
    "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonTimes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setupButtonTimes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRICDManagementUserActiveModeTriggerBitmap",
          "text": "MTRICDManagementUserActiveModeTriggerBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonTimes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRICDManagementUserActiveModeTriggerBitmapSetupButtonTimes"
        }
      ],
      "role": "symbol",
      "title": "setupButtonTimes",
      "type": "topic",
      "url": "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap/setupbuttontimes"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensor",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorLightsBlink",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorSeconds",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorTimes",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/appDefinedButton",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/customInstruction",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/deviceManual",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/powerCycle",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButton",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonLightsBlink",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonSeconds",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonTimes",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/settingsMenu",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButton",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonLightsBlink",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonSeconds",
        "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonTimes"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmap"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensor",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorLightsBlink",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorSeconds",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/actuateSensorTimes",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/appDefinedButton",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/customInstruction",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/deviceManual",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/powerCycle",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButton",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonLightsBlink",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonSeconds",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/resetButtonTimes",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/settingsMenu",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButton",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonLightsBlink",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonSeconds",
                "doc://com.apple.matter/documentation/Matter/MTRICDManagementUserActiveModeTriggerBitmap/setupButtonTimes"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRICDManagementUserActiveModeTriggerBitmap"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1settingsMenu/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapSettingsMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1settingsMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapSettingsMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1appDefinedButton/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapAppDefinedButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1appDefinedButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapAppDefinedButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1setupButtonSeconds/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapSetupButtonSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1setupButtonSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapSetupButtonSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1resetButton/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapResetButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1resetButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapResetButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1powerCycle/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapPowerCycle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1powerCycle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapPowerCycle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1resetButtonSeconds/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapResetButtonSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1resetButtonSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapResetButtonSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1setupButton/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapSetupButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1setupButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapSetupButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1actuateSensorSeconds/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensorSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1actuateSensorSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensorSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1resetButtonTimes/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapResetButtonTimes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1resetButtonTimes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapResetButtonTimes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1deviceManual/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapDeviceManual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1deviceManual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapDeviceManual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1setupButtonLightsBlink/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapSetupButtonLightsBlink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1setupButtonLightsBlink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapSetupButtonLightsBlink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1resetButtonLightsBlink/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapResetButtonLightsBlink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1resetButtonLightsBlink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapResetButtonLightsBlink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1setupButtonTimes/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapSetupButtonTimes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1setupButtonTimes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapSetupButtonTimes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1actuateSensorTimes/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensorTimes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1actuateSensorTimes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensorTimes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1actuateSensor/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1actuateSensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1actuateSensorLightsBlink/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensorLightsBlink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1actuateSensorLightsBlink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapActuateSensorLightsBlink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1customInstruction/title",
          "value": "MTRICDManagementUserActiveModeTriggerBitmapCustomInstruction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRICDManagementUserActiveModeTriggerBitmap~1customInstruction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRICDManagementUserActiveModeTriggerBitmapCustomInstruction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtricdmanagementuseractivemodetriggerbitmap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
