{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRLaundryWasherModeModeTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRLaundryWasherModeModeTag"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRLaundryWasherModeModeTag"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRLaundryWasherModeModeTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTag"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTag"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/auto": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/day": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "day"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/day",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagDay"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.day",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/day"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/delicate": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delicate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/delicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagDelicate"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.delicate",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/delicate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/heavy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heavy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/heavy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagHeavy"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.heavy",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/heavy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/lowEnergy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowEnergy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/lowEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagLowEnergy"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.lowEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/lowenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/lowNoise": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowNoise"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/lowNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagLowNoise"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.lowNoise",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/lownoise"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/max": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagMax"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.max",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/max"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/min": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagMin"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.min",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/min"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/night": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "night"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/night",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagNight"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.night",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/night"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/normal": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagNormal"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.normal",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/normal"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/quick": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quick"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/quick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagQuick"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.quick",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/quick"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/quiet": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quiet"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/quiet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagQuiet"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.quiet",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/quiet"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/vacation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vacation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/vacation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagVacation"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.vacation",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/vacation"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/whites": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whites"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/whites",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLaundryWasherModeModeTagWhites"
        }
      ],
      "role": "symbol",
      "title": "MTRLaundryWasherModeModeTag.whites",
      "type": "topic",
      "url": "/documentation/matter/mtrlaundrywashermodemodetag/whites"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/auto",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/day",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/delicate",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/heavy",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/lowEnergy",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/lowNoise",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/max",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/min",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/night",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/normal",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/quick",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/quiet",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/vacation",
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/whites"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRLaundryWasherModeModeTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/auto",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/day",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/delicate",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/heavy",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/lowEnergy",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/lowNoise",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/max",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/min",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/night",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/normal",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/quick",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/quiet",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/vacation",
                "doc://com.apple.matter/documentation/Matter/MTRLaundryWasherModeModeTag/whites"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRLaundryWasherModeModeTag"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1quick/title",
          "value": "MTRLaundryWasherModeModeTagQuick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1quick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagQuick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1max/title",
          "value": "MTRLaundryWasherModeModeTagMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1auto/title",
          "value": "MTRLaundryWasherModeModeTagAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1lowEnergy/title",
          "value": "MTRLaundryWasherModeModeTagLowEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1lowEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagLowEnergy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1vacation/title",
          "value": "MTRLaundryWasherModeModeTagVacation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1vacation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagVacation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1normal/title",
          "value": "MTRLaundryWasherModeModeTagNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1heavy/title",
          "value": "MTRLaundryWasherModeModeTagHeavy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1heavy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagHeavy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1whites/title",
          "value": "MTRLaundryWasherModeModeTagWhites"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1whites/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagWhites"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag/title",
          "value": "MTRLaundryWasherModeModeTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1min/title",
          "value": "MTRLaundryWasherModeModeTagMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1lowNoise/title",
          "value": "MTRLaundryWasherModeModeTagLowNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1lowNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagLowNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1delicate/title",
          "value": "MTRLaundryWasherModeModeTagDelicate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1delicate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagDelicate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1day/title",
          "value": "MTRLaundryWasherModeModeTagDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1day/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1quiet/title",
          "value": "MTRLaundryWasherModeModeTagQuiet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1quiet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagQuiet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1night/title",
          "value": "MTRLaundryWasherModeModeTagNight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLaundryWasherModeModeTag~1night/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLaundryWasherModeModeTagNight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrlaundrywashermodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrlaundrywashermodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
