{
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRMediaPlaybackCharacteristic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRMediaPlaybackCharacteristic"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRMediaPlaybackCharacteristic"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRMediaPlaybackCharacteristic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristic"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristic"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/alternate": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alternate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/alternate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicAlternate"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.alternate",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/alternate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/caption": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caption"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/caption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicCaption"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.caption",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/caption"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/commentary": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commentary"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/commentary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicCommentary"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.commentary",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/commentary"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/describesVideo": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "describesVideo"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/describesVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicDescribesVideo"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.describesVideo",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/describesvideo"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/description": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "description"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/description",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicDescription"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.description",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/description"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/dubbedTranslation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dubbedTranslation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/dubbedTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicDubbedTranslation"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.dubbedTranslation",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/dubbedtranslation"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/easyToRead": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "easyToRead"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/easyToRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicEasyToRead"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.easyToRead",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/easytoread"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/emergency": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emergency"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/emergency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicEmergency"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.emergency",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/emergency"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/enhancedAudioIntelligibility": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enhancedAudioIntelligibility"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/enhancedAudioIntelligibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicEnhancedAudioIntelligibility"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.enhancedAudioIntelligibility",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/enhancedaudiointelligibility"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/forcedSubtitles": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forcedSubtitles"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/forcedSubtitles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicForcedSubtitles"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.forcedSubtitles",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/forcedsubtitles"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/frameBased": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameBased"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/frameBased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicFrameBased"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.frameBased",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/framebased"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/karaoke": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "karaoke"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/karaoke",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicKaraoke"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.karaoke",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/karaoke"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/mainProgram": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mainProgram"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/mainProgram",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicMainProgram"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.mainProgram",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/mainprogram"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/metadata": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicMetadata"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.metadata",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/metadata"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/originalContent": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "originalContent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/originalContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicOriginalContent"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.originalContent",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/originalcontent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/subtitle": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitle"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/subtitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicSubtitle"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.subtitle",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/subtitle"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/supplementary": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supplementary"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/supplementary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicSupplementary"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.supplementary",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/supplementary"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/voiceOverTranslation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceOverTranslation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/voiceOverTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaPlaybackCharacteristicVoiceOverTranslation"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaPlaybackCharacteristic.voiceOverTranslation",
      "type": "topic",
      "url": "/documentation/matter/mtrmediaplaybackcharacteristic/voiceovertranslation"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/alternate",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/caption",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/commentary",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/describesVideo",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/description",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/dubbedTranslation",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/easyToRead",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/emergency",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/enhancedAudioIntelligibility",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/forcedSubtitles",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/frameBased",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/karaoke",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/mainProgram",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/metadata",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/originalContent",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/subtitle",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/supplementary",
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/voiceOverTranslation"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRMediaPlaybackCharacteristic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/alternate",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/caption",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/commentary",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/describesVideo",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/description",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/dubbedTranslation",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/easyToRead",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/emergency",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/enhancedAudioIntelligibility",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/forcedSubtitles",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/frameBased",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/karaoke",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/mainProgram",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/metadata",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/originalContent",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/subtitle",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/supplementary",
                "doc://com.apple.matter/documentation/Matter/MTRMediaPlaybackCharacteristic/voiceOverTranslation"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRMediaPlaybackCharacteristic"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1description/title",
          "value": "MTRMediaPlaybackCharacteristicDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1description/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1mainProgram/title",
          "value": "MTRMediaPlaybackCharacteristicMainProgram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1mainProgram/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicMainProgram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1caption/title",
          "value": "MTRMediaPlaybackCharacteristicCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1caption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1emergency/title",
          "value": "MTRMediaPlaybackCharacteristicEmergency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1emergency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicEmergency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1forcedSubtitles/title",
          "value": "MTRMediaPlaybackCharacteristicForcedSubtitles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1forcedSubtitles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicForcedSubtitles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1originalContent/title",
          "value": "MTRMediaPlaybackCharacteristicOriginalContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1originalContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicOriginalContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic/title",
          "value": "MTRMediaPlaybackCharacteristic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1dubbedTranslation/title",
          "value": "MTRMediaPlaybackCharacteristicDubbedTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1dubbedTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicDubbedTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1easyToRead/title",
          "value": "MTRMediaPlaybackCharacteristicEasyToRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1easyToRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicEasyToRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1metadata/title",
          "value": "MTRMediaPlaybackCharacteristicMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1frameBased/title",
          "value": "MTRMediaPlaybackCharacteristicFrameBased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1frameBased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicFrameBased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1commentary/title",
          "value": "MTRMediaPlaybackCharacteristicCommentary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1commentary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicCommentary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1karaoke/title",
          "value": "MTRMediaPlaybackCharacteristicKaraoke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1karaoke/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicKaraoke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1alternate/title",
          "value": "MTRMediaPlaybackCharacteristicAlternate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1alternate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicAlternate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1subtitle/title",
          "value": "MTRMediaPlaybackCharacteristicSubtitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1subtitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicSubtitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1supplementary/title",
          "value": "MTRMediaPlaybackCharacteristicSupplementary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1supplementary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicSupplementary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1describesVideo/title",
          "value": "MTRMediaPlaybackCharacteristicDescribesVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1describesVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicDescribesVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1enhancedAudioIntelligibility/title",
          "value": "MTRMediaPlaybackCharacteristicEnhancedAudioIntelligibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1enhancedAudioIntelligibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicEnhancedAudioIntelligibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1voiceOverTranslation/title",
          "value": "MTRMediaPlaybackCharacteristicVoiceOverTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaPlaybackCharacteristic~1voiceOverTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaPlaybackCharacteristicVoiceOverTranslation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrmediaplaybackcharacteristic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrmediaplaybackcharacteristic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
