{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRMicrowaveOvenModeModeTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRMicrowaveOvenModeModeTag"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRMicrowaveOvenModeModeTag"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRMicrowaveOvenModeModeTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTag"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTag"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/auto": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/day": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "day"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/day",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagDay"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.day",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/day"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/defrost": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defrost"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/defrost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagDefrost"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.defrost",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/defrost"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/lowEnergy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowEnergy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/lowEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagLowEnergy"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.lowEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/lowenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/lowNoise": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowNoise"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/lowNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagLowNoise"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.lowNoise",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/lownoise"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/max": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagMax"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.max",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/max"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/min": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagMin"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.min",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/min"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/night": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "night"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/night",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagNight"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.night",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/night"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/normal": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagNormal"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.normal",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/normal"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/quick": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quick"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/quick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagQuick"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.quick",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/quick"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/quiet": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quiet"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/quiet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagQuiet"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.quiet",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/quiet"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/vacation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vacation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/vacation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMicrowaveOvenModeModeTagVacation"
        }
      ],
      "role": "symbol",
      "title": "MTRMicrowaveOvenModeModeTag.vacation",
      "type": "topic",
      "url": "/documentation/matter/mtrmicrowaveovenmodemodetag/vacation"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/auto",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/day",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/defrost",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/lowEnergy",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/lowNoise",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/max",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/min",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/night",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/normal",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/quick",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/quiet",
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/vacation"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRMicrowaveOvenModeModeTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/auto",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/day",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/defrost",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/lowEnergy",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/lowNoise",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/max",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/min",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/night",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/normal",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/quick",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/quiet",
                "doc://com.apple.matter/documentation/Matter/MTRMicrowaveOvenModeModeTag/vacation"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRMicrowaveOvenModeModeTag"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1normal/title",
          "value": "MTRMicrowaveOvenModeModeTagNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1max/title",
          "value": "MTRMicrowaveOvenModeModeTagMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1min/title",
          "value": "MTRMicrowaveOvenModeModeTagMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1vacation/title",
          "value": "MTRMicrowaveOvenModeModeTagVacation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1vacation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagVacation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1lowNoise/title",
          "value": "MTRMicrowaveOvenModeModeTagLowNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1lowNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagLowNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1auto/title",
          "value": "MTRMicrowaveOvenModeModeTagAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1defrost/title",
          "value": "MTRMicrowaveOvenModeModeTagDefrost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1defrost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagDefrost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag/title",
          "value": "MTRMicrowaveOvenModeModeTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1quiet/title",
          "value": "MTRMicrowaveOvenModeModeTagQuiet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1quiet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagQuiet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1night/title",
          "value": "MTRMicrowaveOvenModeModeTagNight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1night/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagNight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1day/title",
          "value": "MTRMicrowaveOvenModeModeTagDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1day/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1lowEnergy/title",
          "value": "MTRMicrowaveOvenModeModeTagLowEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1lowEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagLowEnergy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1quick/title",
          "value": "MTRMicrowaveOvenModeModeTagQuick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMicrowaveOvenModeModeTag~1quick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMicrowaveOvenModeModeTagQuick"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrmicrowaveovenmodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrmicrowaveovenmodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
