{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRMediaInputInputType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRMediaInputInputType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRMediaInputInputType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRMediaInputInputType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputType"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/HDMI-swift.enum.case": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HDMI"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/HDMI-swift.enum.case",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeHDMI"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.HDMI",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/hdmi-swift.enum.case"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/SCART-swift.enum.case": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCART"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/SCART-swift.enum.case",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeSCART"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.SCART",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/scart-swift.enum.case"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/USB-swift.enum.case": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "USB"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/USB-swift.enum.case",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeUSB"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.USB",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/usb-swift.enum.case"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/aux": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aux"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/aux",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeAux"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.aux",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/aux"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/coax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coax"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/coax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeCoax"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.coax",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/coax"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/composite": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composite"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/composite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeComposite"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.composite",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/composite"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/hdmi-swift.type.property": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hdmi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRMediaInputInputType",
          "text": "MTRMediaInputInputType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/hdmi-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeHdmi"
        }
      ],
      "role": "symbol",
      "title": "hdmi",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/hdmi-swift.type.property"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/input": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "input"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/input",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeInput"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.input",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/input"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/internal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/internal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeInternal"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.internal",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/internal"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/line": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/line",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeLine"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.line",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/line"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/optical": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optical"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/optical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeOptical"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.optical",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/optical"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/other": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeOther"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.other",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/other"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/scart-swift.type.property": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRMediaInputInputType",
          "text": "MTRMediaInputInputType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/scart-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeScart"
        }
      ],
      "role": "symbol",
      "title": "scart",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/scart-swift.type.property"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/usb-swift.type.property": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRMediaInputInputType",
          "text": "MTRMediaInputInputType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/usb-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeUsb"
        }
      ],
      "role": "symbol",
      "title": "usb",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/usb-swift.type.property"
    },
    "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/video": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "video"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRMediaInputInputTypeVideo"
        }
      ],
      "role": "symbol",
      "title": "MTRMediaInputInputType.video",
      "type": "topic",
      "url": "/documentation/matter/mtrmediainputinputtype/video"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/HDMI-swift.enum.case",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/SCART-swift.enum.case",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/USB-swift.enum.case",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/aux",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/coax",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/composite",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/input",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/internal",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/line",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/optical",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/other",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/video"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/hdmi-swift.type.property",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/scart-swift.type.property",
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/usb-swift.type.property"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRMediaInputInputType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/HDMI-swift.enum.case",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/SCART-swift.enum.case",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/USB-swift.enum.case",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/aux",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/coax",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/composite",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/input",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/internal",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/line",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/optical",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/other",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/video"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/hdmi-swift.type.property",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/scart-swift.type.property",
                "doc://com.apple.matter/documentation/Matter/MTRMediaInputInputType/usb-swift.type.property"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRMediaInputInputType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1internal/title",
          "value": "MTRMediaInputInputTypeInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1internal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1input/title",
          "value": "MTRMediaInputInputTypeInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1input/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1SCART-swift.enum.case/title",
          "value": "MTRMediaInputInputTypeSCART"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1SCART-swift.enum.case/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeSCART"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1HDMI-swift.enum.case/title",
          "value": "MTRMediaInputInputTypeHDMI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1HDMI-swift.enum.case/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeHDMI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1scart-swift.type.property/title",
          "value": "MTRMediaInputInputTypeScart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1scart-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeScart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1aux/title",
          "value": "MTRMediaInputInputTypeAux"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1aux/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeAux"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1video/title",
          "value": "MTRMediaInputInputTypeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1composite/title",
          "value": "MTRMediaInputInputTypeComposite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1composite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeComposite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1optical/title",
          "value": "MTRMediaInputInputTypeOptical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1optical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeOptical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1coax/title",
          "value": "MTRMediaInputInputTypeCoax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1coax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeCoax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1other/title",
          "value": "MTRMediaInputInputTypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1hdmi-swift.type.property/title",
          "value": "MTRMediaInputInputTypeHdmi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1hdmi-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeHdmi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1USB-swift.enum.case/title",
          "value": "MTRMediaInputInputTypeUSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1USB-swift.enum.case/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeUSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1usb-swift.type.property/title",
          "value": "MTRMediaInputInputTypeUsb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1usb-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeUsb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1line/title",
          "value": "MTRMediaInputInputTypeLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType~1line/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputTypeLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType/title",
          "value": "MTRMediaInputInputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRMediaInputInputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRMediaInputInputType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrmediainputinputtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrmediainputinputtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
