{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRNetworkCommissioningStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRNetworkCommissioningStatus"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRNetworkCommissioningStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRNetworkCommissioningStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatus"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/authFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authFailure"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/authFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusAuthFailure"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.authFailure",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/authfailure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/boundsExceeded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundsExceeded"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/boundsExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusBoundsExceeded"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.boundsExceeded",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/boundsexceeded"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/duplicateNetworkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateNetworkID"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/duplicateNetworkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusDuplicateNetworkID"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.duplicateNetworkID",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/duplicatenetworkid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/ipBindFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ipBindFailed"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/ipBindFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusIPBindFailed"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.ipBindFailed",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/ipbindfailed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/ipv6Failed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ipv6Failed"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/ipv6Failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusIPV6Failed"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.ipv6Failed",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/ipv6failed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/networkIDNotFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkIDNotFound"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/networkIDNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusNetworkIDNotFound"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.networkIDNotFound",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/networkidnotfound"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/networkNotFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkNotFound"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/networkNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusNetworkNotFound"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.networkNotFound",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/networknotfound"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/otherConnectionFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherConnectionFailure"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/otherConnectionFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusOtherConnectionFailure"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.otherConnectionFailure",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/otherconnectionfailure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/outOfRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfRange"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/outOfRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusOutOfRange"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.outOfRange",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/outofrange"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/regulatoryError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regulatoryError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/regulatoryError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusRegulatoryError"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.regulatoryError",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/regulatoryerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/success": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusSuccess"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.success",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/success"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/unknownError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/unknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusUnknownError"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.unknownError",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/unknownerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/unsupportedSecurity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedSecurity"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/unsupportedSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningStatusUnsupportedSecurity"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningStatus.unsupportedSecurity",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningstatus/unsupportedsecurity"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/authFailure",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/boundsExceeded",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/duplicateNetworkID",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/ipBindFailed",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/ipv6Failed",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/networkIDNotFound",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/networkNotFound",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/otherConnectionFailure",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/outOfRange",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/regulatoryError",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/success",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/unknownError",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/unsupportedSecurity"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRNetworkCommissioningStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/authFailure",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/boundsExceeded",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/duplicateNetworkID",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/ipBindFailed",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/ipv6Failed",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/networkIDNotFound",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/networkNotFound",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/otherConnectionFailure",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/outOfRange",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/regulatoryError",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/success",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/unknownError",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningStatus/unsupportedSecurity"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRNetworkCommissioningStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1authFailure/title",
          "value": "MTRNetworkCommissioningStatusAuthFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1authFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusAuthFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1ipv6Failed/title",
          "value": "MTRNetworkCommissioningStatusIPV6Failed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1ipv6Failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusIPV6Failed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1success/title",
          "value": "MTRNetworkCommissioningStatusSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1duplicateNetworkID/title",
          "value": "MTRNetworkCommissioningStatusDuplicateNetworkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1duplicateNetworkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusDuplicateNetworkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1boundsExceeded/title",
          "value": "MTRNetworkCommissioningStatusBoundsExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1boundsExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusBoundsExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1networkIDNotFound/title",
          "value": "MTRNetworkCommissioningStatusNetworkIDNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1networkIDNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusNetworkIDNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1unsupportedSecurity/title",
          "value": "MTRNetworkCommissioningStatusUnsupportedSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1unsupportedSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusUnsupportedSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1unknownError/title",
          "value": "MTRNetworkCommissioningStatusUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1unknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1regulatoryError/title",
          "value": "MTRNetworkCommissioningStatusRegulatoryError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1regulatoryError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusRegulatoryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1networkNotFound/title",
          "value": "MTRNetworkCommissioningStatusNetworkNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1networkNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusNetworkNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1otherConnectionFailure/title",
          "value": "MTRNetworkCommissioningStatusOtherConnectionFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1otherConnectionFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusOtherConnectionFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1outOfRange/title",
          "value": "MTRNetworkCommissioningStatusOutOfRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1outOfRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusOutOfRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1ipBindFailed/title",
          "value": "MTRNetworkCommissioningStatusIPBindFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus~1ipBindFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatusIPBindFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus/title",
          "value": "MTRNetworkCommissioningStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrnetworkcommissioningstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrnetworkcommissioningstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
