{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRNetworkCommissioningClusterWiFiInterfaceScanResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.1",
        "message": "Please use MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.1",
        "message": "Please use MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.1",
        "message": "Please use MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.0",
        "message": "Please use MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.1",
        "message": "Please use MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "9.1",
        "message": "Please use MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningclusterwifiinterfacescanresult"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/bssid": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bssid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/bssid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bssid"
        }
      ],
      "role": "symbol",
      "title": "bssid",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningclusterwifiinterfacescanresult/bssid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/channel": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/channel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channel"
        }
      ],
      "role": "symbol",
      "title": "channel",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningclusterwifiinterfacescanresult/channel"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/rssi": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rssi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/rssi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rssi"
        }
      ],
      "role": "symbol",
      "title": "rssi",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningclusterwifiinterfacescanresult/rssi"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/security": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "security"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/security",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "security"
        }
      ],
      "role": "symbol",
      "title": "security",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningclusterwifiinterfacescanresult/security"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/ssid": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ssid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/ssid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ssid"
        }
      ],
      "role": "symbol",
      "title": "ssid",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningclusterwifiinterfacescanresult/ssid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/wiFiBand": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wiFiBand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/wiFiBand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wiFiBand"
        }
      ],
      "role": "symbol",
      "title": "wiFiBand",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningclusterwifiinterfacescanresult/wifiband"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct"
        }
      ],
      "role": "symbol",
      "title": "MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrnetworkcommissioningclusterwifiinterfacescanresultstruct"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/bssid",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/channel",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/rssi",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/security",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/ssid",
        "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/wiFiBand"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/bssid",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/channel",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/rssi",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/security",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/ssid",
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResult/wiFiBand"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
                    "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1rssi/title",
          "value": "rssi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1rssi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rssi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1ssid/title",
          "value": "ssid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1ssid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ssid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct/title",
          "value": "MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1bssid/title",
          "value": "bssid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1bssid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bssid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1channel/title",
          "value": "channel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1channel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "channel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult/title",
          "value": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNetworkCommissioningClusterWiFiInterfaceScanResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1security/title",
          "value": "security"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1security/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "security"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1wiFiBand/title",
          "value": "wiFiBand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNetworkCommissioningClusterWiFiInterfaceScanResult~1wiFiBand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wiFiBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrnetworkcommissioningclusterwifiinterfacescanresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrnetworkcommissioningclusterwifiinterfacescanresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
