{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTROTASoftwareUpdateRequestorUpdateState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTROTASoftwareUpdateRequestorUpdateState"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTROTASoftwareUpdateRequestorUpdateState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTROTASoftwareUpdateRequestorUpdateState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateState"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateState"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateRequestorUpdateState",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/applying": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applying"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/applying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateStateApplying"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateRequestorUpdateState.applying",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate/applying"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnApply": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delayedOnApply"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnApply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateStateDelayedOnApply"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateRequestorUpdateState.delayedOnApply",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate/delayedonapply"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnQuery": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delayedOnQuery"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateStateDelayedOnQuery"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateRequestorUpdateState.delayedOnQuery",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate/delayedonquery"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnUserConsent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delayedOnUserConsent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnUserConsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateStateDelayedOnUserConsent"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateRequestorUpdateState.delayedOnUserConsent",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate/delayedonuserconsent"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/downloading": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloading"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/downloading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateStateDownloading"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateRequestorUpdateState.downloading",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate/downloading"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/idle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idle"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/idle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateStateIdle"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateRequestorUpdateState.idle",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate/idle"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/querying": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "querying"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/querying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateStateQuerying"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateRequestorUpdateState.querying",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate/querying"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/rollingBack": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollingBack"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/rollingBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateStateRollingBack"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateRequestorUpdateState.rollingBack",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate/rollingback"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateRequestorUpdateStateUnknown"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateRequestorUpdateState.unknown",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate/unknown"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/applying",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnApply",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnQuery",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnUserConsent",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/downloading",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/idle",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/querying",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/rollingBack",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/unknown"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/applying",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnApply",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnQuery",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/delayedOnUserConsent",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/downloading",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/idle",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/querying",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/rollingBack",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateRequestorUpdateState/unknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTROTASoftwareUpdateRequestorUpdateState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1querying/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateStateQuerying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1querying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateStateQuerying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1rollingBack/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateStateRollingBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1rollingBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateStateRollingBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1unknown/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateStateUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateStateUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1delayedOnUserConsent/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateStateDelayedOnUserConsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1delayedOnUserConsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateStateDelayedOnUserConsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1idle/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateStateIdle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1idle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateStateIdle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1downloading/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateStateDownloading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1downloading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateStateDownloading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1applying/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateStateApplying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1applying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateStateApplying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1delayedOnQuery/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateStateDelayedOnQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1delayedOnQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateStateDelayedOnQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1delayedOnApply/title",
          "value": "MTROTASoftwareUpdateRequestorUpdateStateDelayedOnApply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateRequestorUpdateState~1delayedOnApply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateRequestorUpdateStateDelayedOnApply"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrotasoftwareupdaterequestorupdatestate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
