{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTROTASoftwareUpdateRequestorUpdateState",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTROtaSoftwareUpdateRequestorOTAUpdateState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTROTASoftwareUpdateRequestorUpdateState",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTROTASoftwareUpdateRequestorUpdateState",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTROTASoftwareUpdateRequestorUpdateState",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "Please use MTROTASoftwareUpdateRequestorUpdateState",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTROTASoftwareUpdateRequestorUpdateState",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTROTASoftwareUpdateRequestorUpdateState",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "Please use MTROTASoftwareUpdateRequestorUpdateState",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/applying": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applying"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/applying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateApplying"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState.applying",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur/applying"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnApply": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delayedOnApply"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnApply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDelayedOnApply"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState.delayedOnApply",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur/delayedonapply"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnQuery": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delayedOnQuery"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDelayedOnQuery"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState.delayedOnQuery",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur/delayedonquery"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnUserConsent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delayedOnUserConsent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnUserConsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDelayedOnUserConsent"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState.delayedOnUserConsent",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur/delayedonuserconsent"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/downloading": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloading"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/downloading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDownloading"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState.downloading",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur/downloading"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/idle": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idle"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/idle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateIdle"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState.idle",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur/idle"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/querying": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "querying"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/querying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateQuerying"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState.querying",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur/querying"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/rollingBack": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollingBack"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/rollingBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateRollingBack"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState.rollingBack",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur/rollingback"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/unknown": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateUnknown"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateRequestorOTAUpdateState.unknown",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur/unknown"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/applying",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnApply",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnQuery",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnUserConsent",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/downloading",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/idle",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/querying",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/rollingBack",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/unknown"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/applying",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnApply",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnQuery",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/delayedOnUserConsent",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/downloading",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/idle",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/querying",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/rollingBack",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/unknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTROTASoftwareUpdateRequestorUpdateState",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1delayedOnApply/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDelayedOnApply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1delayedOnApply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDelayedOnApply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1delayedOnQuery/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDelayedOnQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1delayedOnQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDelayedOnQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1rollingBack/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateStateRollingBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1rollingBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateRollingBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1delayedOnUserConsent/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDelayedOnUserConsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1delayedOnUserConsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDelayedOnUserConsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1idle/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateStateIdle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1idle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateIdle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1downloading/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDownloading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1downloading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateDownloading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1unknown/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateStateUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1querying/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateStateQuerying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1querying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateQuerying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1applying/title",
          "value": "MTROtaSoftwareUpdateRequestorOTAUpdateStateApplying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateRequestorOTAUpdateState-18cur~1applying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateRequestorOTAUpdateStateApplying"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrotasoftwareupdaterequestorotaupdatestate-18cur"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
