{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTROperationalCredentialsNodeOperationalCertStatus",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTROperationalCredentialsOperationalCertStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTROperationalCredentialsOperationalCertStatus"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTROperationalCredentialsOperationalCertStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTROperationalCredentialsNodeOperationalCertStatus",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTROperationalCredentialsNodeOperationalCertStatus",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTROperationalCredentialsNodeOperationalCertStatus",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "Please use MTROperationalCredentialsNodeOperationalCertStatus",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTROperationalCredentialsNodeOperationalCertStatus",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTROperationalCredentialsNodeOperationalCertStatus",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "Please use MTROperationalCredentialsNodeOperationalCertStatus",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTROperationalCredentialsOperationalCertStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatus"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/SUCCESS": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SUCCESS"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/SUCCESS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatusSUCCESS"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus.SUCCESS",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/success"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/fabricConflict": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricConflict"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/fabricConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatusFabricConflict"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus.fabricConflict",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/fabricconflict"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidAdminSubject": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAdminSubject"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidAdminSubject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatusInvalidAdminSubject"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus.invalidAdminSubject",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/invalidadminsubject"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidFabricIndex": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFabricIndex"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidFabricIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatusInvalidFabricIndex"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus.invalidFabricIndex",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/invalidfabricindex"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidNOC": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNOC"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidNOC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatusInvalidNOC"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus.invalidNOC",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/invalidnoc"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidNodeOpId": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNodeOpId"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidNodeOpId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatusInvalidNodeOpId"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus.invalidNodeOpId",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/invalidnodeopid"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidPublicKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPublicKey"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidPublicKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatusInvalidPublicKey"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus.invalidPublicKey",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/invalidpublickey"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/labelConflict": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "labelConflict"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/labelConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatusLabelConflict"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus.labelConflict",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/labelconflict"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/missingCsr": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingCsr"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/missingCsr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatusMissingCsr"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus.missingCsr",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/missingcsr"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/tableFull": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableFull"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/tableFull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsOperationalCertStatusTableFull"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsOperationalCertStatus.tableFull",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsoperationalcertstatus/tablefull"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/SUCCESS",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/fabricConflict",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidAdminSubject",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidFabricIndex",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidNOC",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidNodeOpId",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidPublicKey",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/labelConflict",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/missingCsr",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/tableFull"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTROperationalCredentialsOperationalCertStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/SUCCESS",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/fabricConflict",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidAdminSubject",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidFabricIndex",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidNOC",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidNodeOpId",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/invalidPublicKey",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/labelConflict",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/missingCsr",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsOperationalCertStatus/tableFull"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTROperationalCredentialsOperationalCertStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTROperationalCredentialsNodeOperationalCertStatus",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus/title",
          "value": "MTROperationalCredentialsOperationalCertStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1invalidNOC/title",
          "value": "MTROperationalCredentialsOperationalCertStatusInvalidNOC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1invalidNOC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatusInvalidNOC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1invalidNodeOpId/title",
          "value": "MTROperationalCredentialsOperationalCertStatusInvalidNodeOpId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1invalidNodeOpId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatusInvalidNodeOpId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1tableFull/title",
          "value": "MTROperationalCredentialsOperationalCertStatusTableFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1tableFull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatusTableFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1SUCCESS/title",
          "value": "MTROperationalCredentialsOperationalCertStatusSUCCESS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1SUCCESS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatusSUCCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1labelConflict/title",
          "value": "MTROperationalCredentialsOperationalCertStatusLabelConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1labelConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatusLabelConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1fabricConflict/title",
          "value": "MTROperationalCredentialsOperationalCertStatusFabricConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1fabricConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatusFabricConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1invalidAdminSubject/title",
          "value": "MTROperationalCredentialsOperationalCertStatusInvalidAdminSubject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1invalidAdminSubject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatusInvalidAdminSubject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1missingCsr/title",
          "value": "MTROperationalCredentialsOperationalCertStatusMissingCsr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1missingCsr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatusMissingCsr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1invalidPublicKey/title",
          "value": "MTROperationalCredentialsOperationalCertStatusInvalidPublicKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1invalidPublicKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatusInvalidPublicKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1invalidFabricIndex/title",
          "value": "MTROperationalCredentialsOperationalCertStatusInvalidFabricIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsOperationalCertStatus~1invalidFabricIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsOperationalCertStatusInvalidFabricIndex"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtroperationalcredentialsoperationalcertstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtroperationalcredentialsoperationalcertstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
