{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTROzoneConcentrationMeasurementMeasurementUnit",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTROzoneConcentrationMeasurementMeasurementUnit"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTROzoneConcentrationMeasurementMeasurementUnit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTROzoneConcentrationMeasurementMeasurementUnit"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnit"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROzoneConcentrationMeasurementMeasurementUnit"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROzoneConcentrationMeasurementMeasurementUnit"
        }
      ],
      "role": "symbol",
      "title": "MTROzoneConcentrationMeasurementMeasurementUnit",
      "type": "topic",
      "url": "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit"
    },
    "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/BQM3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BQM3"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/BQM3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROzoneConcentrationMeasurementMeasurementUnitBQM3"
        }
      ],
      "role": "symbol",
      "title": "MTROzoneConcentrationMeasurementMeasurementUnit.BQM3",
      "type": "topic",
      "url": "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit/bqm3"
    },
    "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/MGM3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MGM3"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/MGM3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROzoneConcentrationMeasurementMeasurementUnitMGM3"
        }
      ],
      "role": "symbol",
      "title": "MTROzoneConcentrationMeasurementMeasurementUnit.MGM3",
      "type": "topic",
      "url": "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit/mgm3"
    },
    "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/NGM3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NGM3"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/NGM3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROzoneConcentrationMeasurementMeasurementUnitNGM3"
        }
      ],
      "role": "symbol",
      "title": "MTROzoneConcentrationMeasurementMeasurementUnit.NGM3",
      "type": "topic",
      "url": "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit/ngm3"
    },
    "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PM3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PM3"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PM3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROzoneConcentrationMeasurementMeasurementUnitPM3"
        }
      ],
      "role": "symbol",
      "title": "MTROzoneConcentrationMeasurementMeasurementUnit.PM3",
      "type": "topic",
      "url": "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit/pm3"
    },
    "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PPB"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROzoneConcentrationMeasurementMeasurementUnitPPB"
        }
      ],
      "role": "symbol",
      "title": "MTROzoneConcentrationMeasurementMeasurementUnit.PPB",
      "type": "topic",
      "url": "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit/ppb"
    },
    "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PPM"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROzoneConcentrationMeasurementMeasurementUnitPPM"
        }
      ],
      "role": "symbol",
      "title": "MTROzoneConcentrationMeasurementMeasurementUnit.PPM",
      "type": "topic",
      "url": "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit/ppm"
    },
    "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PPT"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROzoneConcentrationMeasurementMeasurementUnitPPT"
        }
      ],
      "role": "symbol",
      "title": "MTROzoneConcentrationMeasurementMeasurementUnit.PPT",
      "type": "topic",
      "url": "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit/ppt"
    },
    "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/UGM3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UGM3"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/UGM3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROzoneConcentrationMeasurementMeasurementUnitUGM3"
        }
      ],
      "role": "symbol",
      "title": "MTROzoneConcentrationMeasurementMeasurementUnit.UGM3",
      "type": "topic",
      "url": "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit/ugm3"
    },
    "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/BQM3",
        "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/MGM3",
        "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/NGM3",
        "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PM3",
        "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPB",
        "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPM",
        "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPT",
        "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/UGM3"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTROzoneConcentrationMeasurementMeasurementUnit"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/BQM3",
                "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/MGM3",
                "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/NGM3",
                "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PM3",
                "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPB",
                "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPM",
                "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/PPT",
                "doc://com.apple.matter/documentation/Matter/MTROzoneConcentrationMeasurementMeasurementUnit/UGM3"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTROzoneConcentrationMeasurementMeasurementUnit"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1PPT/title",
          "value": "MTROzoneConcentrationMeasurementMeasurementUnitPPT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1PPT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnitPPT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1BQM3/title",
          "value": "MTROzoneConcentrationMeasurementMeasurementUnitBQM3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1BQM3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnitBQM3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1PPM/title",
          "value": "MTROzoneConcentrationMeasurementMeasurementUnitPPM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1PPM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnitPPM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1MGM3/title",
          "value": "MTROzoneConcentrationMeasurementMeasurementUnitMGM3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1MGM3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnitMGM3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1NGM3/title",
          "value": "MTROzoneConcentrationMeasurementMeasurementUnitNGM3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1NGM3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnitNGM3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit/title",
          "value": "MTROzoneConcentrationMeasurementMeasurementUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1PPB/title",
          "value": "MTROzoneConcentrationMeasurementMeasurementUnitPPB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1PPB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnitPPB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1UGM3/title",
          "value": "MTROzoneConcentrationMeasurementMeasurementUnitUGM3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1UGM3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnitUGM3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1PM3/title",
          "value": "MTROzoneConcentrationMeasurementMeasurementUnitPM3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROzoneConcentrationMeasurementMeasurementUnit~1PM3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROzoneConcentrationMeasurementMeasurementUnitPM3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrozoneconcentrationmeasurementmeasurementunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
