{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTROTAImageDigestType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTROTAImageDigestType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTROTAImageDigestType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTROTAImageDigestType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestType"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha256"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha256"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha256",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha256"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_120": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha256_120"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_120",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha256_120"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha256_120",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha256_120"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_128": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha256_128"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_128",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha256_128"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha256_128",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha256_128"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha256_32"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha256_32"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha256_32",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha256_32"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_64": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha256_64"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha256_64"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha256_64",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha256_64"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_96": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha256_96"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_96",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha256_96"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha256_96",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha256_96"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha384": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha384"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha384"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha384",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha384"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_224": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha3_224"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_224",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha3_224"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha3_224",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha3_224"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha3_256"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha3_256"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha3_256",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha3_256"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_384": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha3_384"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha3_384"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha3_384",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha3_384"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_512": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha3_512"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_512",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha3_512"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha3_512",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha3_512"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha512": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sha512"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha512",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAImageDigestTypeSha512"
        }
      ],
      "role": "symbol",
      "title": "MTROTAImageDigestType.sha512",
      "type": "topic",
      "url": "/documentation/matter/mtrotaimagedigesttype/sha512"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_120",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_128",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_32",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_64",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_96",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha384",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_224",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_256",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_384",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_512",
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha512"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTROTAImageDigestType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_120",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_128",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_32",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_64",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha256_96",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha384",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_224",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_256",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_384",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha3_512",
                "doc://com.apple.matter/documentation/Matter/MTROTAImageDigestType/sha512"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTROTAImageDigestType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256_128/title",
          "value": "MTROTAImageDigestTypeSha256_128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256_128/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha256_128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256_96/title",
          "value": "MTROTAImageDigestTypeSha256_96"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256_96/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha256_96"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha384/title",
          "value": "MTROTAImageDigestTypeSha384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha3_384/title",
          "value": "MTROTAImageDigestTypeSha3_384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha3_384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha3_384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha512/title",
          "value": "MTROTAImageDigestTypeSha512"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha512/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha512"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha3_512/title",
          "value": "MTROTAImageDigestTypeSha3_512"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha3_512/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha3_512"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256_64/title",
          "value": "MTROTAImageDigestTypeSha256_64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256_64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha256_64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha3_256/title",
          "value": "MTROTAImageDigestTypeSha3_256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha3_256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha3_256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256/title",
          "value": "MTROTAImageDigestTypeSha256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType/title",
          "value": "MTROTAImageDigestType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256_32/title",
          "value": "MTROTAImageDigestTypeSha256_32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256_32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha256_32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256_120/title",
          "value": "MTROTAImageDigestTypeSha256_120"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha256_120/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha256_120"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha3_224/title",
          "value": "MTROTAImageDigestTypeSha3_224"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAImageDigestType~1sha3_224/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAImageDigestTypeSha3_224"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrotaimagedigesttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrotaimagedigesttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
