{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTROTASoftwareUpdateProviderClusterQueryImageResponseParams",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/delayedActionTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delayedActionTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/delayedActionTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delayedActionTime"
        }
      ],
      "role": "symbol",
      "title": "delayedActionTime",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt/delayedactiontime"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/imageURI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageURI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/imageURI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageURI"
        }
      ],
      "role": "symbol",
      "title": "imageURI",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt/imageuri"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/init(responseValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "responseValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/init(responseValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithResponseValue:error:"
        }
      ],
      "role": "symbol",
      "title": "init(responseValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt/init(responsevalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/metadataForRequestor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataForRequestor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/metadataForRequestor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataForRequestor"
        }
      ],
      "role": "symbol",
      "title": "metadataForRequestor",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt/metadataforrequestor"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/softwareVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/softwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softwareVersion"
        }
      ],
      "role": "symbol",
      "title": "softwareVersion",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt/softwareversion"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/softwareVersionString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softwareVersionString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/softwareVersionString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softwareVersionString"
        }
      ],
      "role": "symbol",
      "title": "softwareVersionString",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt/softwareversionstring"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/status": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt/status"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/timedInvokeTimeoutMs": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedInvokeTimeoutMs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/timedInvokeTimeoutMs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timedInvokeTimeoutMs"
        }
      ],
      "role": "symbol",
      "title": "timedInvokeTimeoutMs",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt/timedinvoketimeoutms"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/updateToken": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/updateToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateToken"
        }
      ],
      "role": "symbol",
      "title": "updateToken",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt/updatetoken"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/userConsentNeeded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userConsentNeeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/userConsentNeeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userConsentNeeded"
        }
      ],
      "role": "symbol",
      "title": "userConsentNeeded",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt/userconsentneeded"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams-48oao": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams-48oao",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-48oao"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams-48oao"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/init(responseValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/delayedActionTime",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/imageURI",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/metadataForRequestor",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/softwareVersion",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/softwareVersionString",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/status",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/timedInvokeTimeoutMs",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/updateToken",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/userConsentNeeded"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/delayedActionTime",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/imageURI",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/metadataForRequestor",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/softwareVersion",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/softwareVersionString",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/status",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/timedInvokeTimeoutMs",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/updateToken",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/userConsentNeeded"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/init(responseValue:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams-48oao"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1softwareVersionString/title",
          "value": "softwareVersionString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1softwareVersionString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "softwareVersionString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1timedInvokeTimeoutMs/title",
          "value": "timedInvokeTimeoutMs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1timedInvokeTimeoutMs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timedInvokeTimeoutMs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1updateToken/title",
          "value": "updateToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1updateToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "updateToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1imageURI/title",
          "value": "imageURI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1imageURI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageURI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/title",
          "value": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateProviderClusterQueryImageResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1userConsentNeeded/title",
          "value": "userConsentNeeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1userConsentNeeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userConsentNeeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1delayedActionTime/title",
          "value": "delayedActionTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1delayedActionTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delayedActionTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1status/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1softwareVersion/title",
          "value": "softwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1softwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "softwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1init(responseValue:)/title",
          "value": "initWithResponseValue:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1init(responseValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithResponseValue:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1metadataForRequestor/title",
          "value": "metadataForRequestor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageResponseParams-6wuvt~1metadataForRequestor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadataForRequestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams-48oao/title",
          "value": "MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams-48oao/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams-48oao/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageresponseparams-6wuvt"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
