{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTROperationalCredentialsNodeOperationalCertStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTROperationalCredentialsNodeOperationalCertStatus"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTROperationalCredentialsNodeOperationalCertStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTROperationalCredentialsNodeOperationalCertStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatus"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/OK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OK"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/OK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatusOK"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus.OK",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/ok"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/fabricConflict": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricConflict"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/fabricConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatusFabricConflict"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus.fabricConflict",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/fabricconflict"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidAdminSubject": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAdminSubject"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidAdminSubject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatusInvalidAdminSubject"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus.invalidAdminSubject",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/invalidadminsubject"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidFabricIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFabricIndex"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidFabricIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatusInvalidFabricIndex"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus.invalidFabricIndex",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/invalidfabricindex"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidNOC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNOC"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidNOC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatusInvalidNOC"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus.invalidNOC",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/invalidnoc"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidNodeOpId": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNodeOpId"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidNodeOpId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatusInvalidNodeOpId"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus.invalidNodeOpId",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/invalidnodeopid"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidPublicKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPublicKey"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidPublicKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatusInvalidPublicKey"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus.invalidPublicKey",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/invalidpublickey"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/labelConflict": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "labelConflict"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/labelConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatusLabelConflict"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus.labelConflict",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/labelconflict"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/missingCsr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingCsr"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/missingCsr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatusMissingCsr"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus.missingCsr",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/missingcsr"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/tableFull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableFull"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/tableFull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsNodeOperationalCertStatusTableFull"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsNodeOperationalCertStatus.tableFull",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus/tablefull"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/OK",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/fabricConflict",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidAdminSubject",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidFabricIndex",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidNOC",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidNodeOpId",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidPublicKey",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/labelConflict",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/missingCsr",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/tableFull"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/OK",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/fabricConflict",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidAdminSubject",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidFabricIndex",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidNOC",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidNodeOpId",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/invalidPublicKey",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/labelConflict",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/missingCsr",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsNodeOperationalCertStatus/tableFull"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTROperationalCredentialsNodeOperationalCertStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1missingCsr/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatusMissingCsr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1missingCsr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatusMissingCsr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1OK/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatusOK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1OK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatusOK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1fabricConflict/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatusFabricConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1fabricConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatusFabricConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1invalidPublicKey/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatusInvalidPublicKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1invalidPublicKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatusInvalidPublicKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1invalidAdminSubject/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatusInvalidAdminSubject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1invalidAdminSubject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatusInvalidAdminSubject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1labelConflict/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatusLabelConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1labelConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatusLabelConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1invalidNodeOpId/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatusInvalidNodeOpId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1invalidNodeOpId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatusInvalidNodeOpId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1tableFull/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatusTableFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1tableFull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatusTableFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1invalidNOC/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatusInvalidNOC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1invalidNOC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatusInvalidNOC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1invalidFabricIndex/title",
          "value": "MTROperationalCredentialsNodeOperationalCertStatusInvalidFabricIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsNodeOperationalCertStatus~1invalidFabricIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsNodeOperationalCertStatusInvalidFabricIndex"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtroperationalcredentialsnodeoperationalcertstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
