{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTROvenModeModeTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTROvenModeModeTag"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTROvenModeModeTag"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTROvenModeModeTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTag"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTag"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/auto": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagAuto"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/bake": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bake"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/bake",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagBake"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.bake",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/bake"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/clean": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clean"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/clean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagClean"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.clean",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/clean"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convection": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convection"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagConvection"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.convection",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/convection"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convectionBake": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convectionBake"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convectionBake",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagConvectionBake"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.convectionBake",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/convectionbake"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convectionRoast": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convectionRoast"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convectionRoast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagConvectionRoast"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.convectionRoast",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/convectionroast"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/day": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "day"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/day",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagDay"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.day",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/day"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/grill": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grill"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/grill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagGrill"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.grill",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/grill"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/lowEnergy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowEnergy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/lowEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagLowEnergy"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.lowEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/lowenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/lowNoise": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowNoise"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/lowNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagLowNoise"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.lowNoise",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/lownoise"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/max": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagMax"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.max",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/max"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/min": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagMin"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.min",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/min"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/night": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "night"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/night",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagNight"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.night",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/night"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/proofing": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proofing"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/proofing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagProofing"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.proofing",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/proofing"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/quick": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quick"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/quick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagQuick"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.quick",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/quick"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/quiet": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quiet"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/quiet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagQuiet"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.quiet",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/quiet"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/roast": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roast"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/roast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagRoast"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.roast",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/roast"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/vacation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vacation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/vacation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagVacation"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.vacation",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/vacation"
    },
    "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/warming": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "warming"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/warming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROvenModeModeTagWarming"
        }
      ],
      "role": "symbol",
      "title": "MTROvenModeModeTag.warming",
      "type": "topic",
      "url": "/documentation/matter/mtrovenmodemodetag/warming"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/auto",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/bake",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/clean",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convection",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convectionBake",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convectionRoast",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/day",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/grill",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/lowEnergy",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/lowNoise",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/max",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/min",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/night",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/proofing",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/quick",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/quiet",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/roast",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/vacation",
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/warming"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTROvenModeModeTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/auto",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/bake",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/clean",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convection",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convectionBake",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/convectionRoast",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/day",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/grill",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/lowEnergy",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/lowNoise",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/max",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/min",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/night",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/proofing",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/quick",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/quiet",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/roast",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/vacation",
                "doc://com.apple.matter/documentation/Matter/MTROvenModeModeTag/warming"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTROvenModeModeTag"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1day/title",
          "value": "MTROvenModeModeTagDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1day/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1proofing/title",
          "value": "MTROvenModeModeTagProofing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1proofing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagProofing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1night/title",
          "value": "MTROvenModeModeTagNight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1night/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagNight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag/title",
          "value": "MTROvenModeModeTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1quick/title",
          "value": "MTROvenModeModeTagQuick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1quick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagQuick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1lowNoise/title",
          "value": "MTROvenModeModeTagLowNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1lowNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagLowNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1max/title",
          "value": "MTROvenModeModeTagMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1roast/title",
          "value": "MTROvenModeModeTagRoast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1roast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagRoast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1convectionRoast/title",
          "value": "MTROvenModeModeTagConvectionRoast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1convectionRoast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagConvectionRoast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1convectionBake/title",
          "value": "MTROvenModeModeTagConvectionBake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1convectionBake/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagConvectionBake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1quiet/title",
          "value": "MTROvenModeModeTagQuiet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1quiet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagQuiet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1min/title",
          "value": "MTROvenModeModeTagMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1bake/title",
          "value": "MTROvenModeModeTagBake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1bake/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagBake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1vacation/title",
          "value": "MTROvenModeModeTagVacation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1vacation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagVacation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1convection/title",
          "value": "MTROvenModeModeTagConvection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1convection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagConvection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1warming/title",
          "value": "MTROvenModeModeTagWarming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1warming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagWarming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1lowEnergy/title",
          "value": "MTROvenModeModeTagLowEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1lowEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagLowEnergy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1auto/title",
          "value": "MTROvenModeModeTagAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1grill/title",
          "value": "MTROvenModeModeTagGrill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1grill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagGrill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1clean/title",
          "value": "MTROvenModeModeTagClean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROvenModeModeTag~1clean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROvenModeModeTagClean"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrovenmodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrovenmodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
