{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTROTASoftwareUpdateProviderClusterQueryImageParams",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
        }
      ],
      "role": "symbol",
      "title": "MTROTASoftwareUpdateProviderClusterQueryImageParams",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/hardwareVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/hardwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hardwareVersion"
        }
      ],
      "role": "symbol",
      "title": "hardwareVersion",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/hardwareversion"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/location": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/location"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/metadataForProvider": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataForProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/metadataForProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataForProvider"
        }
      ],
      "role": "symbol",
      "title": "metadataForProvider",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/metadataforprovider"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/productID-9dqyi": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/productID-9dqyi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "productID"
        }
      ],
      "role": "symbol",
      "title": "productID",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/productid-9dqyi"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/productId-9dqxm": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/productId-9dqxm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "productId"
        }
      ],
      "role": "symbol",
      "title": "productId",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/productid-9dqxm"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/protocolsSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "protocolsSupported"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/protocolsSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "protocolsSupported"
        }
      ],
      "role": "symbol",
      "title": "protocolsSupported",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/protocolssupported"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/requestorCanConsent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestorCanConsent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/requestorCanConsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestorCanConsent"
        }
      ],
      "role": "symbol",
      "title": "requestorCanConsent",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/requestorcanconsent"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/serverSideProcessingTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverSideProcessingTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/serverSideProcessingTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serverSideProcessingTimeout"
        }
      ],
      "role": "symbol",
      "title": "serverSideProcessingTimeout",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/serversideprocessingtimeout"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/softwareVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/softwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softwareVersion"
        }
      ],
      "role": "symbol",
      "title": "softwareVersion",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/softwareversion"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/timedInvokeTimeoutMs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedInvokeTimeoutMs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/timedInvokeTimeoutMs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timedInvokeTimeoutMs"
        }
      ],
      "role": "symbol",
      "title": "timedInvokeTimeoutMs",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/timedinvoketimeoutms"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/vendorID-6cv55": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/vendorID-6cv55",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorID"
        }
      ],
      "role": "symbol",
      "title": "vendorID",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/vendorid-6cv55"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/vendorId-6cv49": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/vendorId-6cv49",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorId"
        }
      ],
      "role": "symbol",
      "title": "vendorId",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b/vendorid-6cv49"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateProviderClusterQueryImageParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROtaSoftwareUpdateProviderClusterQueryImageParams"
        }
      ],
      "role": "symbol",
      "title": "MTROtaSoftwareUpdateProviderClusterQueryImageParams",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-zidv"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/hardwareVersion": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/hardwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hardwareVersion"
        }
      ],
      "role": "symbol",
      "title": "hardwareVersion",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-zidv/hardwareversion"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/location": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-zidv/location"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/metadataForProvider": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataForProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/metadataForProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataForProvider"
        }
      ],
      "role": "symbol",
      "title": "metadataForProvider",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-zidv/metadataforprovider"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/protocolsSupported": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "protocolsSupported"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/protocolsSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "protocolsSupported"
        }
      ],
      "role": "symbol",
      "title": "protocolsSupported",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-zidv/protocolssupported"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/requestorCanConsent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestorCanConsent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/requestorCanConsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestorCanConsent"
        }
      ],
      "role": "symbol",
      "title": "requestorCanConsent",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-zidv/requestorcanconsent"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/serverSideProcessingTimeout": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverSideProcessingTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/serverSideProcessingTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serverSideProcessingTimeout"
        }
      ],
      "role": "symbol",
      "title": "serverSideProcessingTimeout",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-zidv/serversideprocessingtimeout"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/softwareVersion": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/softwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softwareVersion"
        }
      ],
      "role": "symbol",
      "title": "softwareVersion",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-zidv/softwareversion"
    },
    "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/timedInvokeTimeoutMs": {
      "abstract": [
        {
          "text": "Controls whether the command is a timed command (using Timed Invoke).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedInvokeTimeoutMs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/timedInvokeTimeoutMs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timedInvokeTimeoutMs"
        }
      ],
      "role": "symbol",
      "title": "timedInvokeTimeoutMs",
      "type": "topic",
      "url": "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-zidv/timedinvoketimeoutms"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/hardwareVersion",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/location",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/metadataForProvider",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/productID-9dqyi",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/productId-9dqxm",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/protocolsSupported",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/requestorCanConsent",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/serverSideProcessingTimeout",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/softwareVersion",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/timedInvokeTimeoutMs",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/vendorID-6cv55",
        "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/vendorId-6cv49",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/hardwareVersion",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/location",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/metadataForProvider",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/protocolsSupported",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/requestorCanConsent",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/serverSideProcessingTimeout",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/softwareVersion",
        "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/timedInvokeTimeoutMs"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/hardwareVersion",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/location",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/metadataForProvider",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/productID-9dqyi",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/productId-9dqxm",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/protocolsSupported",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/requestorCanConsent",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/serverSideProcessingTimeout",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/softwareVersion",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/timedInvokeTimeoutMs",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/vendorID-6cv55",
                "doc://com.apple.matter/documentation/Matter/MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/vendorId-6cv49",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/hardwareVersion",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/location",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/metadataForProvider",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/protocolsSupported",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/requestorCanConsent",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/serverSideProcessingTimeout",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/softwareVersion",
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/timedInvokeTimeoutMs"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1productId-9dqxm/title",
          "value": "productId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1productId-9dqxm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "productId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1requestorCanConsent/title",
          "value": "requestorCanConsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1requestorCanConsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestorCanConsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1location/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1vendorId-6cv49/title",
          "value": "vendorId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1vendorId-6cv49/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1serverSideProcessingTimeout/title",
          "value": "serverSideProcessingTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1serverSideProcessingTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serverSideProcessingTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1vendorID-6cv55/title",
          "value": "vendorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1vendorID-6cv55/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1timedInvokeTimeoutMs/title",
          "value": "timedInvokeTimeoutMs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1timedInvokeTimeoutMs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timedInvokeTimeoutMs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1softwareVersion/title",
          "value": "softwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1softwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "softwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1metadataForProvider/title",
          "value": "metadataForProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1metadataForProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadataForProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/title",
          "value": "MTROtaSoftwareUpdateProviderClusterQueryImageParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateProviderClusterQueryImageParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROtaSoftwareUpdateProviderClusterQueryImageParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1softwareVersion/title",
          "value": "softwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1softwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "softwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1protocolsSupported/title",
          "value": "protocolsSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1protocolsSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "protocolsSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1requestorCanConsent/title",
          "value": "requestorCanConsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1requestorCanConsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestorCanConsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/title",
          "value": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTASoftwareUpdateProviderClusterQueryImageParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1hardwareVersion/title",
          "value": "hardwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1hardwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hardwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1hardwareVersion/title",
          "value": "hardwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1hardwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hardwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1metadataForProvider/title",
          "value": "metadataForProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1metadataForProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadataForProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1location/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1productID-9dqyi/title",
          "value": "productID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1productID-9dqyi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "productID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1serverSideProcessingTimeout/title",
          "value": "serverSideProcessingTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTASoftwareUpdateProviderClusterQueryImageParams-8z02b~1serverSideProcessingTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serverSideProcessingTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1timedInvokeTimeoutMs/title",
          "value": "timedInvokeTimeoutMs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1timedInvokeTimeoutMs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timedInvokeTimeoutMs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1protocolsSupported/title",
          "value": "protocolsSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROtaSoftwareUpdateProviderClusterQueryImageParams-zidv~1protocolsSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "protocolsSupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrotasoftwareupdateproviderclusterqueryimageparams-8z02b"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
