{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTROperationalCredentialsClusterFabricDescriptorStruct",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTROperationalCredentialsClusterFabricDescriptorStruct"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTROperationalCredentialsClusterFabricDescriptorStruct"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTROperationalCredentialsClusterFabricDescriptorStruct"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsClusterFabricDescriptorStruct"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsClusterFabricDescriptor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsClusterFabricDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsClusterFabricDescriptor",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptor"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsClusterFabricDescriptorStruct"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCredentialsClusterFabricDescriptorStruct"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCredentialsClusterFabricDescriptorStruct",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricID-5teul": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricID-5teul",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fabricID"
        }
      ],
      "role": "symbol",
      "title": "fabricID",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct/fabricid-5teul"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricId-5tetp": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricId-5tetp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fabricId"
        }
      ],
      "role": "symbol",
      "title": "fabricId",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct/fabricid-5tetp"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fabricIndex"
        }
      ],
      "role": "symbol",
      "title": "fabricIndex",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct/fabricindex"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/label": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "label"
        }
      ],
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct/label"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/nodeID-3hsb0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nodeID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/nodeID-3hsb0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nodeID"
        }
      ],
      "role": "symbol",
      "title": "nodeID",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct/nodeid-3hsb0"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/nodeId-3hsbw": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nodeId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/nodeId-3hsbw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nodeId"
        }
      ],
      "role": "symbol",
      "title": "nodeId",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct/nodeid-3hsbw"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/rootPublicKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rootPublicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/rootPublicKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rootPublicKey"
        }
      ],
      "role": "symbol",
      "title": "rootPublicKey",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct/rootpublickey"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/vendorID-3iay9": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/vendorID-3iay9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorID"
        }
      ],
      "role": "symbol",
      "title": "vendorID",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct/vendorid-3iay9"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/vendorId-3iaxd": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/vendorId-3iaxd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorId"
        }
      ],
      "role": "symbol",
      "title": "vendorId",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct/vendorid-3iaxd"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptor"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricID-5teul",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricId-5tetp",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricIndex",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/label",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/nodeID-3hsb0",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/nodeId-3hsbw",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/rootPublicKey",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/vendorID-3iay9",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/vendorId-3iaxd"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTROperationalCredentialsClusterFabricDescriptorStruct"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsClusterFabricDescriptorStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsClusterFabricDescriptorStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricID-5teul",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricId-5tetp",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/fabricIndex",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/label",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/nodeID-3hsb0",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/nodeId-3hsbw",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/rootPublicKey",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/vendorID-3iay9",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptorStruct/vendorId-3iaxd"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTROperationalCredentialsClusterFabricDescriptor"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTROperationalCredentialsClusterFabricDescriptorStruct"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1fabricId-5tetp/title",
          "value": "fabricId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1fabricId-5tetp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fabricId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1nodeID-3hsb0/title",
          "value": "nodeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1nodeID-3hsb0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nodeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1fabricIndex/title",
          "value": "fabricIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1fabricIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fabricIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1rootPublicKey/title",
          "value": "rootPublicKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1rootPublicKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rootPublicKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1nodeId-3hsbw/title",
          "value": "nodeId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1nodeId-3hsbw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nodeId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1vendorId-3iaxd/title",
          "value": "vendorId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1vendorId-3iaxd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1vendorID-3iay9/title",
          "value": "vendorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1vendorID-3iay9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1fabricID-5teul/title",
          "value": "fabricID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1fabricID-5teul/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fabricID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct/title",
          "value": "MTROperationalCredentialsClusterFabricDescriptorStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsClusterFabricDescriptorStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsClusterFabricDescriptorStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1label/title",
          "value": "label"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptorStruct~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "label"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptor/title",
          "value": "MTROperationalCredentialsClusterFabricDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsClusterFabricDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCredentialsClusterFabricDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCredentialsClusterFabricDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtroperationalcredentialsclusterfabricdescriptorstruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
