{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRPumpConfigurationAndControlFeature",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRPumpConfigurationAndControlPumpFeature",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRPumpConfigurationAndControlPumpFeature"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRPumpConfigurationAndControlPumpFeature"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.4",
        "message": "Please use MTRPumpConfigurationAndControlFeature",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.4",
        "message": "Please use MTRPumpConfigurationAndControlFeature",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.4",
        "message": "Please use MTRPumpConfigurationAndControlFeature",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.3",
        "message": "Please use MTRPumpConfigurationAndControlFeature",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.4",
        "message": "Please use MTRPumpConfigurationAndControlFeature",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRPumpConfigurationAndControlFeature",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "9.4",
        "message": "Please use MTRPumpConfigurationAndControlFeature",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTRPumpConfigurationAndControlPumpFeature"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeature"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpFeature"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlPumpFeature",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/automatic": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpFeature",
          "text": "MTRPumpConfigurationAndControlPumpFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpFeatureAutomatic"
        }
      ],
      "role": "symbol",
      "title": "automatic",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature/automatic"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/compensatedPressure": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compensatedPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpFeature",
          "text": "MTRPumpConfigurationAndControlPumpFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/compensatedPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpFeatureCompensatedPressure"
        }
      ],
      "role": "symbol",
      "title": "compensatedPressure",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature/compensatedpressure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantFlow": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantFlow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpFeature",
          "text": "MTRPumpConfigurationAndControlPumpFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpFeatureConstantFlow"
        }
      ],
      "role": "symbol",
      "title": "constantFlow",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature/constantflow"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantPressure": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpFeature",
          "text": "MTRPumpConfigurationAndControlPumpFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpFeatureConstantPressure"
        }
      ],
      "role": "symbol",
      "title": "constantPressure",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature/constantpressure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantSpeed": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpFeature",
          "text": "MTRPumpConfigurationAndControlPumpFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpFeatureConstantSpeed"
        }
      ],
      "role": "symbol",
      "title": "constantSpeed",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature/constantspeed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantTemperature": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantTemperature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpFeature",
          "text": "MTRPumpConfigurationAndControlPumpFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpFeatureConstantTemperature"
        }
      ],
      "role": "symbol",
      "title": "constantTemperature",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature/constanttemperature"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/local": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "local"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpFeature",
          "text": "MTRPumpConfigurationAndControlPumpFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/local",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpFeatureLocal"
        }
      ],
      "role": "symbol",
      "title": "local",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature/local"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/localOperation": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpFeature",
          "text": "MTRPumpConfigurationAndControlPumpFeature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/localOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpFeatureLocalOperation"
        }
      ],
      "role": "symbol",
      "title": "localOperation",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature/localoperation"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/automatic",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/compensatedPressure",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantFlow",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantPressure",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantSpeed",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantTemperature",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/local",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/localOperation"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRPumpConfigurationAndControlPumpFeature"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/automatic",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/compensatedPressure",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantFlow",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantPressure",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantSpeed",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/constantTemperature",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/local",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpFeature/localOperation"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRPumpConfigurationAndControlPumpFeature"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRPumpConfigurationAndControlFeature",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1constantTemperature/title",
          "value": "MTRPumpConfigurationAndControlPumpFeatureConstantTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1constantTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeatureConstantTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1constantSpeed/title",
          "value": "MTRPumpConfigurationAndControlPumpFeatureConstantSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1constantSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeatureConstantSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature/title",
          "value": "MTRPumpConfigurationAndControlPumpFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1local/title",
          "value": "MTRPumpConfigurationAndControlPumpFeatureLocal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1local/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeatureLocal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1compensatedPressure/title",
          "value": "MTRPumpConfigurationAndControlPumpFeatureCompensatedPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1compensatedPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeatureCompensatedPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1localOperation/title",
          "value": "MTRPumpConfigurationAndControlPumpFeatureLocalOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1localOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeatureLocalOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1constantPressure/title",
          "value": "MTRPumpConfigurationAndControlPumpFeatureConstantPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1constantPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeatureConstantPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1automatic/title",
          "value": "MTRPumpConfigurationAndControlPumpFeatureAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeatureAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1constantFlow/title",
          "value": "MTRPumpConfigurationAndControlPumpFeatureConstantFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpFeature~1constantFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpFeatureConstantFlow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrpumpconfigurationandcontrolpumpfeature"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
