{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRPowerSourceBatChargeFault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRPowerSourceBatChargeFault"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRPowerSourceBatChargeFault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRPowerSourceBatChargeFault"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFault"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFault"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/ambientTooCold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambientTooCold"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/ambientTooCold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultAmbientTooCold"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.ambientTooCold",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/ambienttoocold"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/ambientTooHot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambientTooHot"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/ambientTooHot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultAmbientTooHot"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.ambientTooHot",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/ambienttoohot"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryAbsent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batteryAbsent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryAbsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultBatteryAbsent"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.batteryAbsent",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/batteryabsent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryOverVoltage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batteryOverVoltage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryOverVoltage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultBatteryOverVoltage"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.batteryOverVoltage",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/batteryovervoltage"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryTooCold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batteryTooCold"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryTooCold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultBatteryTooCold"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.batteryTooCold",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/batterytoocold"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryTooHot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batteryTooHot"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryTooHot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultBatteryTooHot"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.batteryTooHot",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/batterytoohot"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryUnderVoltage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batteryUnderVoltage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryUnderVoltage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultBatteryUnderVoltage"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.batteryUnderVoltage",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/batteryundervoltage"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/chargerOverVoltage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chargerOverVoltage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/chargerOverVoltage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultChargerOverVoltage"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.chargerOverVoltage",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/chargerovervoltage"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/chargerUnderVoltage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chargerUnderVoltage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/chargerUnderVoltage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultChargerUnderVoltage"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.chargerUnderVoltage",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/chargerundervoltage"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/safetyTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "safetyTimeout"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/safetyTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultSafetyTimeout"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.safetyTimeout",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/safetytimeout"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/unspecfied": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecfied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPowerSourceBatChargeFault",
          "text": "MTRPowerSourceBatChargeFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/unspecfied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultUnspecfied"
        }
      ],
      "role": "symbol",
      "title": "unspecfied",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/unspecfied"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatChargeFaultUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatChargeFault.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatchargefault/unspecified"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/ambientTooCold",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/ambientTooHot",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryAbsent",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryOverVoltage",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryTooCold",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryTooHot",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryUnderVoltage",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/chargerOverVoltage",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/chargerUnderVoltage",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/safetyTimeout",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/unspecified"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/unspecfied"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRPowerSourceBatChargeFault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/ambientTooCold",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/ambientTooHot",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryAbsent",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryOverVoltage",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryTooCold",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryTooHot",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/batteryUnderVoltage",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/chargerOverVoltage",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/chargerUnderVoltage",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/safetyTimeout",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/unspecified"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatChargeFault/unspecfied"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRPowerSourceBatChargeFault"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1safetyTimeout/title",
          "value": "MTRPowerSourceBatChargeFaultSafetyTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1safetyTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultSafetyTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1unspecfied/title",
          "value": "MTRPowerSourceBatChargeFaultUnspecfied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1unspecfied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultUnspecfied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1chargerUnderVoltage/title",
          "value": "MTRPowerSourceBatChargeFaultChargerUnderVoltage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1chargerUnderVoltage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultChargerUnderVoltage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1batteryAbsent/title",
          "value": "MTRPowerSourceBatChargeFaultBatteryAbsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1batteryAbsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultBatteryAbsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1batteryTooHot/title",
          "value": "MTRPowerSourceBatChargeFaultBatteryTooHot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1batteryTooHot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultBatteryTooHot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1ambientTooCold/title",
          "value": "MTRPowerSourceBatChargeFaultAmbientTooCold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1ambientTooCold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultAmbientTooCold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1chargerOverVoltage/title",
          "value": "MTRPowerSourceBatChargeFaultChargerOverVoltage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1chargerOverVoltage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultChargerOverVoltage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1batteryOverVoltage/title",
          "value": "MTRPowerSourceBatChargeFaultBatteryOverVoltage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1batteryOverVoltage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultBatteryOverVoltage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1batteryUnderVoltage/title",
          "value": "MTRPowerSourceBatChargeFaultBatteryUnderVoltage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1batteryUnderVoltage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultBatteryUnderVoltage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault/title",
          "value": "MTRPowerSourceBatChargeFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1batteryTooCold/title",
          "value": "MTRPowerSourceBatChargeFaultBatteryTooCold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1batteryTooCold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultBatteryTooCold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1ambientTooHot/title",
          "value": "MTRPowerSourceBatChargeFaultAmbientTooHot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1ambientTooHot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultAmbientTooHot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1unspecified/title",
          "value": "MTRPowerSourceBatChargeFaultUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatChargeFault~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatChargeFaultUnspecified"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrpowersourcebatchargefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrpowersourcebatchargefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
