{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRPumpConfigurationAndControlControlMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRPumpConfigurationAndControlControlMode"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRPumpConfigurationAndControlControlMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRPumpConfigurationAndControlControlMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlControlMode"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlControlMode"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlControlMode",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolcontrolmode"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/automatic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlControlModeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlControlMode.automatic",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolcontrolmode/automatic"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantFlow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantFlow"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlControlModeConstantFlow"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlControlMode.constantFlow",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolcontrolmode/constantflow"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantPressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantPressure"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlControlModeConstantPressure"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlControlMode.constantPressure",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolcontrolmode/constantpressure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantSpeed"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlControlModeConstantSpeed"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlControlMode.constantSpeed",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolcontrolmode/constantspeed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantTemperature": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantTemperature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlControlModeConstantTemperature"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlControlMode.constantTemperature",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolcontrolmode/constanttemperature"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolcontrolmode/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/proportionalPressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proportionalPressure"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/proportionalPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlControlModeProportionalPressure"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlControlMode.proportionalPressure",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolcontrolmode/proportionalpressure"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/automatic",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantFlow",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantPressure",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantSpeed",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantTemperature",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/proportionalPressure"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.5",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRPumpConfigurationAndControlControlMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/automatic",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantFlow",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantPressure",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantSpeed",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/constantTemperature",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlControlMode/proportionalPressure"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRPumpConfigurationAndControlControlMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1constantPressure/title",
          "value": "MTRPumpConfigurationAndControlControlModeConstantPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1constantPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlModeConstantPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1constantFlow/title",
          "value": "MTRPumpConfigurationAndControlControlModeConstantFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1constantFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlModeConstantFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1proportionalPressure/title",
          "value": "MTRPumpConfigurationAndControlControlModeProportionalPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1proportionalPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlModeProportionalPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1automatic/title",
          "value": "MTRPumpConfigurationAndControlControlModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1constantSpeed/title",
          "value": "MTRPumpConfigurationAndControlControlModeConstantSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1constantSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlModeConstantSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1constantTemperature/title",
          "value": "MTRPumpConfigurationAndControlControlModeConstantTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode~1constantTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlModeConstantTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode/title",
          "value": "MTRPumpConfigurationAndControlControlMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlControlMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlControlMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrpumpconfigurationandcontrolcontrolmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrpumpconfigurationandcontrolcontrolmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
