{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRPumpConfigurationAndControlControlMode",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRPumpConfigurationAndControlPumpControlMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRPumpConfigurationAndControlPumpControlMode"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRPumpConfigurationAndControlPumpControlMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.5",
        "introducedAt": "16.1",
        "message": "Please use MTRPumpConfigurationAndControlControlMode",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.5",
        "introducedAt": "16.1",
        "message": "Please use MTRPumpConfigurationAndControlControlMode",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.5",
        "introducedAt": "16.1",
        "message": "Please use MTRPumpConfigurationAndControlControlMode",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.4",
        "introducedAt": "13.0",
        "message": "Please use MTRPumpConfigurationAndControlControlMode",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.5",
        "introducedAt": "16.1",
        "message": "Please use MTRPumpConfigurationAndControlControlMode",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRPumpConfigurationAndControlControlMode",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.5",
        "introducedAt": "9.1",
        "message": "Please use MTRPumpConfigurationAndControlControlMode",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRPumpConfigurationAndControlPumpControlMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpControlMode"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpControlMode"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlPumpControlMode",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpcontrolmode"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/automatic": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpControlModeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlPumpControlMode.automatic",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpcontrolmode/automatic"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantFlow": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantFlow"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpControlModeConstantFlow"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlPumpControlMode.constantFlow",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpcontrolmode/constantflow"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantPressure": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantPressure"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpControlModeConstantPressure"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlPumpControlMode.constantPressure",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpcontrolmode/constantpressure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantSpeed": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantSpeed"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpControlModeConstantSpeed"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlPumpControlMode.constantSpeed",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpcontrolmode/constantspeed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantTemperature": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constantTemperature"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpControlModeConstantTemperature"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlPumpControlMode.constantTemperature",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpcontrolmode/constanttemperature"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpcontrolmode/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/proportionalPressure": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proportionalPressure"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/proportionalPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpControlModeProportionalPressure"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlPumpControlMode.proportionalPressure",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpcontrolmode/proportionalpressure"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/automatic",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantFlow",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantPressure",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantSpeed",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantTemperature",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/proportionalPressure"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.5",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.5",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.5",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.4",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.5",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.5",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRPumpConfigurationAndControlPumpControlMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/automatic",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantFlow",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantPressure",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantSpeed",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/constantTemperature",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpControlMode/proportionalPressure"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRPumpConfigurationAndControlPumpControlMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRPumpConfigurationAndControlControlMode",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1proportionalPressure/title",
          "value": "MTRPumpConfigurationAndControlPumpControlModeProportionalPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1proportionalPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlModeProportionalPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1automatic/title",
          "value": "MTRPumpConfigurationAndControlPumpControlModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1constantPressure/title",
          "value": "MTRPumpConfigurationAndControlPumpControlModeConstantPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1constantPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlModeConstantPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1constantSpeed/title",
          "value": "MTRPumpConfigurationAndControlPumpControlModeConstantSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1constantSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlModeConstantSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode/title",
          "value": "MTRPumpConfigurationAndControlPumpControlMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1constantFlow/title",
          "value": "MTRPumpConfigurationAndControlPumpControlModeConstantFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1constantFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlModeConstantFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1constantTemperature/title",
          "value": "MTRPumpConfigurationAndControlPumpControlModeConstantTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpControlMode~1constantTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpControlModeConstantTemperature"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrpumpconfigurationandcontrolpumpcontrolmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrpumpconfigurationandcontrolpumpcontrolmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
