{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRPowerSourceBatApprovedChemistry",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRPowerSourceBatApprovedChemistry"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRPowerSourceBatApprovedChemistry"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRPowerSourceBatApprovedChemistry"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistry"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistry"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistry"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/alkaline": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alkaline"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/alkaline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryAlkaline"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.alkaline",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/alkaline"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/leadAcid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leadAcid"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/leadAcid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLeadAcid"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.leadAcid",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/leadacid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCarbonFluoride": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumCarbonFluoride"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCarbonFluoride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumCarbonFluoride"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumCarbonFluoride",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumcarbonfluoride"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumChromiumOxide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumChromiumOxide"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumChromiumOxide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumChromiumOxide"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumChromiumOxide",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumchromiumoxide"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCobaltOxide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumCobaltOxide"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCobaltOxide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumCobaltOxide"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumCobaltOxide",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumcobaltoxide"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCopperOxide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumCopperOxide"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCopperOxide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumCopperOxide"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumCopperOxide",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumcopperoxide"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumIon"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumIon"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumIon",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumion"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIonPolymer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumIonPolymer"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIonPolymer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumIonPolymer"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumIonPolymer",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumionpolymer"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIronDisulfide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumIronDisulfide"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIronDisulfide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumIronDisulfide"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumIronDisulfide",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumirondisulfide"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIronPhosphate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumIronPhosphate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIronPhosphate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumIronPhosphate"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumIronPhosphate",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumironphosphate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumManganeseDioxide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumManganeseDioxide"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumManganeseDioxide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumManganeseDioxide"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumManganeseDioxide",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiummanganesedioxide"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumSulfur": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumSulfur"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumSulfur",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumSulfur"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumSulfur",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumsulfur"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumThionylChloride": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumThionylChloride"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumThionylChloride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumThionylChloride"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumThionylChloride",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumthionylchloride"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumTitanate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lithiumTitanate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumTitanate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryLithiumTitanate"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.lithiumTitanate",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/lithiumtitanate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/magnesium": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magnesium"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/magnesium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryMagnesium"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.magnesium",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/magnesium"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/mercuryOxide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mercuryOxide"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/mercuryOxide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryMercuryOxide"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.mercuryOxide",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/mercuryoxide"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelCadmium": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nickelCadmium"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelCadmium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryNickelCadmium"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.nickelCadmium",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/nickelcadmium"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelHydrogen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nickelHydrogen"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelHydrogen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryNickelHydrogen"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.nickelHydrogen",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/nickelhydrogen"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelIron": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nickelIron"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelIron",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryNickelIron"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.nickelIron",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/nickeliron"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelMetalHydride": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nickelMetalHydride"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelMetalHydride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryNickelMetalHydride"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.nickelMetalHydride",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/nickelmetalhydride"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelOxyhydride": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nickelOxyhydride"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelOxyhydride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryNickelOxyhydride"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.nickelOxyhydride",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/nickeloxyhydride"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelZinc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nickelZinc"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelZinc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryNickelZinc"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.nickelZinc",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/nickelzinc"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/silverOxide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "silverOxide"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/silverOxide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistrySilverOxide"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.silverOxide",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/silveroxide"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/silverZinc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "silverZinc"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/silverZinc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistrySilverZinc"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.silverZinc",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/silverzinc"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/sodiumIon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sodiumIon"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/sodiumIon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistrySodiumIon"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.sodiumIon",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/sodiumion"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/sodiumSulfur": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sodiumSulfur"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/sodiumSulfur",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistrySodiumSulfur"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.sodiumSulfur",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/sodiumsulfur"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/unspecified"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincAir": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zincAir"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincAir",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryZincAir"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.zincAir",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/zincair"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincBromide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zincBromide"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincBromide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryZincBromide"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.zincBromide",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/zincbromide"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincCarbon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zincCarbon"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincCarbon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryZincCarbon"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.zincCarbon",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/zinccarbon"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincCerium": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zincCerium"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincCerium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryZincCerium"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.zincCerium",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/zinccerium"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincChloride": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zincChloride"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincChloride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryZincChloride"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.zincChloride",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/zincchloride"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincManganeseDioxide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zincManganeseDioxide"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincManganeseDioxide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPowerSourceBatApprovedChemistryZincManganeseDioxide"
        }
      ],
      "role": "symbol",
      "title": "MTRPowerSourceBatApprovedChemistry.zincManganeseDioxide",
      "type": "topic",
      "url": "/documentation/matter/mtrpowersourcebatapprovedchemistry/zincmanganesedioxide"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/alkaline",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/leadAcid",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCarbonFluoride",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumChromiumOxide",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCobaltOxide",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCopperOxide",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIon",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIonPolymer",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIronDisulfide",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIronPhosphate",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumManganeseDioxide",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumSulfur",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumThionylChloride",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumTitanate",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/magnesium",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/mercuryOxide",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelCadmium",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelHydrogen",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelIron",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelMetalHydride",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelOxyhydride",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelZinc",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/silverOxide",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/silverZinc",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/sodiumIon",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/sodiumSulfur",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/unspecified",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincAir",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincBromide",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincCarbon",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincCerium",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincChloride",
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincManganeseDioxide"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.5",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRPowerSourceBatApprovedChemistry"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/alkaline",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/leadAcid",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCarbonFluoride",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumChromiumOxide",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCobaltOxide",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumCopperOxide",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIon",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIonPolymer",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIronDisulfide",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumIronPhosphate",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumManganeseDioxide",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumSulfur",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumThionylChloride",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/lithiumTitanate",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/magnesium",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/mercuryOxide",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelCadmium",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelHydrogen",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelIron",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelMetalHydride",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelOxyhydride",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/nickelZinc",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/silverOxide",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/silverZinc",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/sodiumIon",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/sodiumSulfur",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/unspecified",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincAir",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincBromide",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincCarbon",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincCerium",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincChloride",
                "doc://com.apple.matter/documentation/Matter/MTRPowerSourceBatApprovedChemistry/zincManganeseDioxide"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRPowerSourceBatApprovedChemistry"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelOxyhydride/title",
          "value": "MTRPowerSourceBatApprovedChemistryNickelOxyhydride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelOxyhydride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryNickelOxyhydride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincCarbon/title",
          "value": "MTRPowerSourceBatApprovedChemistryZincCarbon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincCarbon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryZincCarbon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelHydrogen/title",
          "value": "MTRPowerSourceBatApprovedChemistryNickelHydrogen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelHydrogen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryNickelHydrogen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumChromiumOxide/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumChromiumOxide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumChromiumOxide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumChromiumOxide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1mercuryOxide/title",
          "value": "MTRPowerSourceBatApprovedChemistryMercuryOxide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1mercuryOxide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryMercuryOxide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelIron/title",
          "value": "MTRPowerSourceBatApprovedChemistryNickelIron"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelIron/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryNickelIron"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumThionylChloride/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumThionylChloride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumThionylChloride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumThionylChloride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry/title",
          "value": "MTRPowerSourceBatApprovedChemistry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1sodiumSulfur/title",
          "value": "MTRPowerSourceBatApprovedChemistrySodiumSulfur"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1sodiumSulfur/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistrySodiumSulfur"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1magnesium/title",
          "value": "MTRPowerSourceBatApprovedChemistryMagnesium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1magnesium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryMagnesium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumCarbonFluoride/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumCarbonFluoride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumCarbonFluoride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumCarbonFluoride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1sodiumIon/title",
          "value": "MTRPowerSourceBatApprovedChemistrySodiumIon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1sodiumIon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistrySodiumIon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelZinc/title",
          "value": "MTRPowerSourceBatApprovedChemistryNickelZinc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelZinc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryNickelZinc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumIronDisulfide/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumIronDisulfide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumIronDisulfide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumIronDisulfide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumIon/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumIon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumIon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumIon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincChloride/title",
          "value": "MTRPowerSourceBatApprovedChemistryZincChloride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincChloride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryZincChloride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1unspecified/title",
          "value": "MTRPowerSourceBatApprovedChemistryUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelMetalHydride/title",
          "value": "MTRPowerSourceBatApprovedChemistryNickelMetalHydride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelMetalHydride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryNickelMetalHydride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelCadmium/title",
          "value": "MTRPowerSourceBatApprovedChemistryNickelCadmium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1nickelCadmium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryNickelCadmium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumManganeseDioxide/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumManganeseDioxide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumManganeseDioxide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumManganeseDioxide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumCobaltOxide/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumCobaltOxide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumCobaltOxide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumCobaltOxide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumIonPolymer/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumIonPolymer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumIonPolymer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumIonPolymer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1alkaline/title",
          "value": "MTRPowerSourceBatApprovedChemistryAlkaline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1alkaline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryAlkaline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumSulfur/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumSulfur"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumSulfur/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumSulfur"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincCerium/title",
          "value": "MTRPowerSourceBatApprovedChemistryZincCerium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincCerium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryZincCerium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1leadAcid/title",
          "value": "MTRPowerSourceBatApprovedChemistryLeadAcid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1leadAcid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLeadAcid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumIronPhosphate/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumIronPhosphate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumIronPhosphate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumIronPhosphate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincBromide/title",
          "value": "MTRPowerSourceBatApprovedChemistryZincBromide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincBromide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryZincBromide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumCopperOxide/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumCopperOxide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumCopperOxide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumCopperOxide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincAir/title",
          "value": "MTRPowerSourceBatApprovedChemistryZincAir"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincAir/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryZincAir"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1silverOxide/title",
          "value": "MTRPowerSourceBatApprovedChemistrySilverOxide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1silverOxide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistrySilverOxide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1silverZinc/title",
          "value": "MTRPowerSourceBatApprovedChemistrySilverZinc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1silverZinc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistrySilverZinc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincManganeseDioxide/title",
          "value": "MTRPowerSourceBatApprovedChemistryZincManganeseDioxide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1zincManganeseDioxide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryZincManganeseDioxide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumTitanate/title",
          "value": "MTRPowerSourceBatApprovedChemistryLithiumTitanate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPowerSourceBatApprovedChemistry~1lithiumTitanate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPowerSourceBatApprovedChemistryLithiumTitanate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrpowersourcebatapprovedchemistry"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrpowersourcebatapprovedchemistry"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
