{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTRPumpConfigurationAndControlPumpStatusBitmap"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "role": "symbol",
      "title": "MTRPumpConfigurationAndControlPumpStatusBitmap",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/deviceFault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/deviceFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmapDeviceFault"
        }
      ],
      "role": "symbol",
      "title": "deviceFault",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/devicefault"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/localOverride": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localOverride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/localOverride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmapLocalOverride"
        }
      ],
      "role": "symbol",
      "title": "localOverride",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/localoverride"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remoteFlow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteFlow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remoteFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmapRemoteFlow"
        }
      ],
      "role": "symbol",
      "title": "remoteFlow",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/remoteflow"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remotePressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remotePressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remotePressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmapRemotePressure"
        }
      ],
      "role": "symbol",
      "title": "remotePressure",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/remotepressure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remoteTemperature": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteTemperature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remoteTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmapRemoteTemperature"
        }
      ],
      "role": "symbol",
      "title": "remoteTemperature",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/remotetemperature"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/running": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "running"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/running",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmapRunning"
        }
      ],
      "role": "symbol",
      "title": "running",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/running"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/speedHigh": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speedHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/speedHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmapSpeedHigh"
        }
      ],
      "role": "symbol",
      "title": "speedHigh",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/speedhigh"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/speedLow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speedLow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/speedLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmapSpeedLow"
        }
      ],
      "role": "symbol",
      "title": "speedLow",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/speedlow"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/supplyFault-8wst8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supplyFault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/supplyFault-8wst8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmapSupplyFault"
        }
      ],
      "role": "symbol",
      "title": "supplyFault",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/supplyfault-8wst8"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/supplyfault-7n9s7": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supplyfault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRPumpConfigurationAndControlPumpStatusBitmap",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/supplyfault-7n9s7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPumpConfigurationAndControlPumpStatusBitmapSupplyfault"
        }
      ],
      "role": "symbol",
      "title": "supplyfault",
      "type": "topic",
      "url": "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap/supplyfault-7n9s7"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/deviceFault",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/localOverride",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remoteFlow",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remotePressure",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remoteTemperature",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/running",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/speedHigh",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/speedLow",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/supplyFault-8wst8",
        "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/supplyfault-7n9s7"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.5",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/deviceFault",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/localOverride",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remoteFlow",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remotePressure",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/remoteTemperature",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/running",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/speedHigh",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/speedLow",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/supplyFault-8wst8",
                "doc://com.apple.matter/documentation/Matter/MTRPumpConfigurationAndControlPumpStatusBitmap/supplyfault-7n9s7"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1remotePressure/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmapRemotePressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1remotePressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmapRemotePressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1remoteTemperature/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmapRemoteTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1remoteTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmapRemoteTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1remoteFlow/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmapRemoteFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1remoteFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmapRemoteFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1supplyfault-7n9s7/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmapSupplyfault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1supplyfault-7n9s7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmapSupplyfault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1speedLow/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmapSpeedLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1speedLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmapSpeedLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1deviceFault/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmapDeviceFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1deviceFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmapDeviceFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1localOverride/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmapLocalOverride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1localOverride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmapLocalOverride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1supplyFault-8wst8/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmapSupplyFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1supplyFault-8wst8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmapSupplyFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1speedHigh/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmapSpeedHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1speedHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmapSpeedHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1running/title",
          "value": "MTRPumpConfigurationAndControlPumpStatusBitmapRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPumpConfigurationAndControlPumpStatusBitmap~1running/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPumpConfigurationAndControlPumpStatusBitmapRunning"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrpumpconfigurationandcontrolpumpstatusbitmap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
