{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRRVCCleanModeModeTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRRVCCleanModeModeTag"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRRVCCleanModeModeTag"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRRVCCleanModeModeTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTag"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTag"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/auto": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/day": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "day"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/day",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagDay"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.day",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/day"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/deepClean": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deepClean"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/deepClean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagDeepClean"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.deepClean",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/deepclean"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/lowEnergy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowEnergy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/lowEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagLowEnergy"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.lowEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/lowenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/lowNoise": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowNoise"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/lowNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagLowNoise"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.lowNoise",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/lownoise"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/max": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagMax"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.max",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/max"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/min": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagMin"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.min",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/min"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/mop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mop"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/mop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagMop"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.mop",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/mop"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/night": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "night"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/night",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagNight"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.night",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/night"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/quick": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quick"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/quick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagQuick"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.quick",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/quick"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/quiet": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quiet"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/quiet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagQuiet"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.quiet",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/quiet"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/vacation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vacation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/vacation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagVacation"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.vacation",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/vacation"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/vacuum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vacuum"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/vacuum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCCleanModeModeTagVacuum"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCCleanModeModeTag.vacuum",
      "type": "topic",
      "url": "/documentation/matter/mtrrvccleanmodemodetag/vacuum"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/deepClean",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/mop",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/vacuum",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/auto",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/day",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/lowEnergy",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/lowNoise",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/max",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/min",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/night",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/quick",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/quiet",
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/vacation"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRRVCCleanModeModeTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/deepClean",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/mop",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/vacuum",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/auto",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/day",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/lowEnergy",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/lowNoise",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/max",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/min",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/night",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/quick",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/quiet",
                "doc://com.apple.matter/documentation/Matter/MTRRVCCleanModeModeTag/vacation"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRRVCCleanModeModeTag"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1max/title",
          "value": "MTRRVCCleanModeModeTagMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1deepClean/title",
          "value": "MTRRVCCleanModeModeTagDeepClean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1deepClean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagDeepClean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1quick/title",
          "value": "MTRRVCCleanModeModeTagQuick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1quick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagQuick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1auto/title",
          "value": "MTRRVCCleanModeModeTagAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1min/title",
          "value": "MTRRVCCleanModeModeTagMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1quiet/title",
          "value": "MTRRVCCleanModeModeTagQuiet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1quiet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagQuiet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1vacuum/title",
          "value": "MTRRVCCleanModeModeTagVacuum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1vacuum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagVacuum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1day/title",
          "value": "MTRRVCCleanModeModeTagDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1day/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1mop/title",
          "value": "MTRRVCCleanModeModeTagMop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1mop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagMop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1night/title",
          "value": "MTRRVCCleanModeModeTagNight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1night/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagNight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag/title",
          "value": "MTRRVCCleanModeModeTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1lowNoise/title",
          "value": "MTRRVCCleanModeModeTagLowNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1lowNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagLowNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1vacation/title",
          "value": "MTRRVCCleanModeModeTagVacation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1vacation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagVacation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1lowEnergy/title",
          "value": "MTRRVCCleanModeModeTagLowEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCCleanModeModeTag~1lowEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCCleanModeModeTagLowEnergy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrrvccleanmodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrrvccleanmodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
