{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRRVCRunModeStatusCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRRVCRunModeStatusCode"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRRVCRunModeStatusCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRRVCRunModeStatusCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRRVCRunModeStatusCode"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCRunModeStatusCode"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCRunModeStatusCode",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcrunmodestatuscode"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/batteryLow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batteryLow"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/batteryLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCRunModeStatusCodeBatteryLow"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCRunModeStatusCode.batteryLow",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcrunmodestatuscode/batterylow"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/dustBinFull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dustBinFull"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/dustBinFull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCRunModeStatusCodeDustBinFull"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCRunModeStatusCode.dustBinFull",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcrunmodestatuscode/dustbinfull"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/dustBinMissing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dustBinMissing"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/dustBinMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCRunModeStatusCodeDustBinMissing"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCRunModeStatusCode.dustBinMissing",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcrunmodestatuscode/dustbinmissing"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcrunmodestatuscode/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/mopCleaningPadMissing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mopCleaningPadMissing"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/mopCleaningPadMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCRunModeStatusCodeMopCleaningPadMissing"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCRunModeStatusCode.mopCleaningPadMissing",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcrunmodestatuscode/mopcleaningpadmissing"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/stuck": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stuck"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/stuck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCRunModeStatusCodeStuck"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCRunModeStatusCode.stuck",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcrunmodestatuscode/stuck"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankEmpty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waterTankEmpty"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankEmpty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCRunModeStatusCodeWaterTankEmpty"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCRunModeStatusCode.waterTankEmpty",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcrunmodestatuscode/watertankempty"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankLidOpen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waterTankLidOpen"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankLidOpen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCRunModeStatusCodeWaterTankLidOpen"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCRunModeStatusCode.waterTankLidOpen",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcrunmodestatuscode/watertanklidopen"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankMissing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waterTankMissing"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCRunModeStatusCodeWaterTankMissing"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCRunModeStatusCode.waterTankMissing",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcrunmodestatuscode/watertankmissing"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/batteryLow",
        "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/dustBinFull",
        "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/dustBinMissing",
        "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/mopCleaningPadMissing",
        "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/stuck",
        "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankEmpty",
        "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankLidOpen",
        "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankMissing"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRRVCRunModeStatusCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/batteryLow",
                "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/dustBinFull",
                "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/dustBinMissing",
                "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/mopCleaningPadMissing",
                "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/stuck",
                "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankEmpty",
                "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankLidOpen",
                "doc://com.apple.matter/documentation/Matter/MTRRVCRunModeStatusCode/waterTankMissing"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRRVCRunModeStatusCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1dustBinFull/title",
          "value": "MTRRVCRunModeStatusCodeDustBinFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1dustBinFull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCodeDustBinFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode/title",
          "value": "MTRRVCRunModeStatusCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1dustBinMissing/title",
          "value": "MTRRVCRunModeStatusCodeDustBinMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1dustBinMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCodeDustBinMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1waterTankLidOpen/title",
          "value": "MTRRVCRunModeStatusCodeWaterTankLidOpen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1waterTankLidOpen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCodeWaterTankLidOpen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1batteryLow/title",
          "value": "MTRRVCRunModeStatusCodeBatteryLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1batteryLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCodeBatteryLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1waterTankMissing/title",
          "value": "MTRRVCRunModeStatusCodeWaterTankMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1waterTankMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCodeWaterTankMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1waterTankEmpty/title",
          "value": "MTRRVCRunModeStatusCodeWaterTankEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1waterTankEmpty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCodeWaterTankEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1mopCleaningPadMissing/title",
          "value": "MTRRVCRunModeStatusCodeMopCleaningPadMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1mopCleaningPadMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCodeMopCleaningPadMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1stuck/title",
          "value": "MTRRVCRunModeStatusCodeStuck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCRunModeStatusCode~1stuck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCRunModeStatusCodeStuck"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrrvcrunmodestatuscode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrrvcrunmodestatuscode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
