{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRRVCOperationalStateErrorState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRRVCOperationalStateErrorState"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRRVCOperationalStateErrorState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRRVCOperationalStateErrorState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorState"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorState"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/commandInvalidInState": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commandInvalidInState"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/commandInvalidInState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateCommandInvalidInState"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.commandInvalidInState",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/commandinvalidinstate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/dustBinFull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dustBinFull"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/dustBinFull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateDustBinFull"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.dustBinFull",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/dustbinfull"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/dustBinMissing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dustBinMissing"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/dustBinMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateDustBinMissing"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.dustBinMissing",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/dustbinmissing"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/failedToFindChargingDock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToFindChargingDock"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/failedToFindChargingDock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateFailedToFindChargingDock"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.failedToFindChargingDock",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/failedtofindchargingdock"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/mopCleaningPadMissing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mopCleaningPadMissing"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/mopCleaningPadMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateMopCleaningPadMissing"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.mopCleaningPadMissing",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/mopcleaningpadmissing"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/noError": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/noError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateNoError"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.noError",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/noerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/stuck": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stuck"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/stuck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateStuck"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.stuck",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/stuck"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/unableToCompleteOperation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unableToCompleteOperation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/unableToCompleteOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateUnableToCompleteOperation"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.unableToCompleteOperation",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/unabletocompleteoperation"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/unableToStartOrResume": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unableToStartOrResume"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/unableToStartOrResume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateUnableToStartOrResume"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.unableToStartOrResume",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/unabletostartorresume"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankEmpty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waterTankEmpty"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankEmpty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateWaterTankEmpty"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.waterTankEmpty",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/watertankempty"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankLidOpen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waterTankLidOpen"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankLidOpen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateWaterTankLidOpen"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.waterTankLidOpen",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/watertanklidopen"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankMissing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waterTankMissing"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRVCOperationalStateErrorStateWaterTankMissing"
        }
      ],
      "role": "symbol",
      "title": "MTRRVCOperationalStateErrorState.waterTankMissing",
      "type": "topic",
      "url": "/documentation/matter/mtrrvcoperationalstateerrorstate/watertankmissing"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/dustBinFull",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/dustBinMissing",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/failedToFindChargingDock",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/mopCleaningPadMissing",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/stuck",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankEmpty",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankLidOpen",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankMissing",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/commandInvalidInState",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/noError",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/unableToCompleteOperation",
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/unableToStartOrResume"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRRVCOperationalStateErrorState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/dustBinFull",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/dustBinMissing",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/failedToFindChargingDock",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/mopCleaningPadMissing",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/stuck",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankEmpty",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankLidOpen",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/waterTankMissing",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/commandInvalidInState",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/noError",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/unableToCompleteOperation",
                "doc://com.apple.matter/documentation/Matter/MTRRVCOperationalStateErrorState/unableToStartOrResume"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRRVCOperationalStateErrorState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1noError/title",
          "value": "MTRRVCOperationalStateErrorStateNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1noError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateNoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1dustBinFull/title",
          "value": "MTRRVCOperationalStateErrorStateDustBinFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1dustBinFull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateDustBinFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1stuck/title",
          "value": "MTRRVCOperationalStateErrorStateStuck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1stuck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateStuck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1waterTankEmpty/title",
          "value": "MTRRVCOperationalStateErrorStateWaterTankEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1waterTankEmpty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateWaterTankEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1unableToStartOrResume/title",
          "value": "MTRRVCOperationalStateErrorStateUnableToStartOrResume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1unableToStartOrResume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateUnableToStartOrResume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1dustBinMissing/title",
          "value": "MTRRVCOperationalStateErrorStateDustBinMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1dustBinMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateDustBinMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1waterTankMissing/title",
          "value": "MTRRVCOperationalStateErrorStateWaterTankMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1waterTankMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateWaterTankMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1commandInvalidInState/title",
          "value": "MTRRVCOperationalStateErrorStateCommandInvalidInState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1commandInvalidInState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateCommandInvalidInState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1waterTankLidOpen/title",
          "value": "MTRRVCOperationalStateErrorStateWaterTankLidOpen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1waterTankLidOpen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateWaterTankLidOpen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState/title",
          "value": "MTRRVCOperationalStateErrorState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1mopCleaningPadMissing/title",
          "value": "MTRRVCOperationalStateErrorStateMopCleaningPadMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1mopCleaningPadMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateMopCleaningPadMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1unableToCompleteOperation/title",
          "value": "MTRRVCOperationalStateErrorStateUnableToCompleteOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1unableToCompleteOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateUnableToCompleteOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1failedToFindChargingDock/title",
          "value": "MTRRVCOperationalStateErrorStateFailedToFindChargingDock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRVCOperationalStateErrorState~1failedToFindChargingDock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRVCOperationalStateErrorStateFailedToFindChargingDock"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrrvcoperationalstateerrorstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrrvcoperationalstateerrorstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
