{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/auto": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/day": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "day"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/day",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagDay"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.day",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/day"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/lowEnergy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowEnergy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/lowEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagLowEnergy"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.lowEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/lowenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/lowNoise": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowNoise"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/lowNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagLowNoise"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.lowNoise",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/lownoise"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/max": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagMax"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.max",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/max"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/min": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagMin"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.min",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/min"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/night": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "night"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/night",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagNight"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.night",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/night"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/quick": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quick"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/quick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagQuick"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.quick",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/quick"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/quiet": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quiet"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/quiet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagQuiet"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.quiet",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/quiet"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/rapidCool": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rapidCool"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/rapidCool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagRapidCool"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.rapidCool",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/rapidcool"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/rapidFreeze": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rapidFreeze"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/rapidFreeze",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagRapidFreeze"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.rapidFreeze",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/rapidfreeze"
    },
    "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/vacation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vacation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/vacation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagVacation"
        }
      ],
      "role": "symbol",
      "title": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag.vacation",
      "type": "topic",
      "url": "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag/vacation"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/auto",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/day",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/lowEnergy",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/lowNoise",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/max",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/min",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/night",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/quick",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/quiet",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/rapidCool",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/rapidFreeze",
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/vacation"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/auto",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/day",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/lowEnergy",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/lowNoise",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/max",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/min",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/night",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/quick",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/quiet",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/rapidCool",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/rapidFreeze",
                "doc://com.apple.matter/documentation/Matter/MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/vacation"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1auto/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1lowEnergy/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagLowEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1lowEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagLowEnergy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1vacation/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagVacation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1vacation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagVacation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1night/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagNight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1night/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagNight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1rapidCool/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagRapidCool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1rapidCool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagRapidCool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1day/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1day/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1rapidFreeze/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagRapidFreeze"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1rapidFreeze/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagRapidFreeze"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1quick/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagQuick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1quick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagQuick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1lowNoise/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagLowNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1lowNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagLowNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1min/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1quiet/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagQuiet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1quiet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagQuiet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1max/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTagMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/title",
          "value": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRRefrigeratorAndTemperatureControlledCabinetModeModeTag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrrefrigeratorandtemperaturecontrolledcabinetmodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
