{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRSmokeCOAlarmExpressedState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRSmokeCOAlarmExpressedState"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRSmokeCOAlarmExpressedState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRSmokeCOAlarmExpressedState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedState"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedState"
        }
      ],
      "role": "symbol",
      "title": "MTRSmokeCOAlarmExpressedState",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/batteryAlert": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batteryAlert"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/batteryAlert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedStateBatteryAlert"
        }
      ],
      "role": "symbol",
      "title": "MTRSmokeCOAlarmExpressedState.batteryAlert",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate/batteryalert"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/coAlarm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coAlarm"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/coAlarm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedStateCOAlarm"
        }
      ],
      "role": "symbol",
      "title": "MTRSmokeCOAlarmExpressedState.coAlarm",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate/coalarm"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/endOfService": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endOfService"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/endOfService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedStateEndOfService"
        }
      ],
      "role": "symbol",
      "title": "MTRSmokeCOAlarmExpressedState.endOfService",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate/endofservice"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/hardwareFault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardwareFault"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/hardwareFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedStateHardwareFault"
        }
      ],
      "role": "symbol",
      "title": "MTRSmokeCOAlarmExpressedState.hardwareFault",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate/hardwarefault"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/interconnectCO": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interconnectCO"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/interconnectCO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedStateInterconnectCO"
        }
      ],
      "role": "symbol",
      "title": "MTRSmokeCOAlarmExpressedState.interconnectCO",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate/interconnectco"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/interconnectSmoke": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interconnectSmoke"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/interconnectSmoke",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedStateInterconnectSmoke"
        }
      ],
      "role": "symbol",
      "title": "MTRSmokeCOAlarmExpressedState.interconnectSmoke",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate/interconnectsmoke"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/normal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedStateNormal"
        }
      ],
      "role": "symbol",
      "title": "MTRSmokeCOAlarmExpressedState.normal",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate/normal"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/smokeAlarm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smokeAlarm"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/smokeAlarm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedStateSmokeAlarm"
        }
      ],
      "role": "symbol",
      "title": "MTRSmokeCOAlarmExpressedState.smokeAlarm",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate/smokealarm"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/testing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testing"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/testing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSmokeCOAlarmExpressedStateTesting"
        }
      ],
      "role": "symbol",
      "title": "MTRSmokeCOAlarmExpressedState.testing",
      "type": "topic",
      "url": "/documentation/matter/mtrsmokecoalarmexpressedstate/testing"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/batteryAlert",
        "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/coAlarm",
        "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/endOfService",
        "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/hardwareFault",
        "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/interconnectCO",
        "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/interconnectSmoke",
        "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/normal",
        "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/smokeAlarm",
        "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/testing"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRSmokeCOAlarmExpressedState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/batteryAlert",
                "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/coAlarm",
                "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/endOfService",
                "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/hardwareFault",
                "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/interconnectCO",
                "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/interconnectSmoke",
                "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/normal",
                "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/smokeAlarm",
                "doc://com.apple.matter/documentation/Matter/MTRSmokeCOAlarmExpressedState/testing"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRSmokeCOAlarmExpressedState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1batteryAlert/title",
          "value": "MTRSmokeCOAlarmExpressedStateBatteryAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1batteryAlert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedStateBatteryAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState/title",
          "value": "MTRSmokeCOAlarmExpressedState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1smokeAlarm/title",
          "value": "MTRSmokeCOAlarmExpressedStateSmokeAlarm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1smokeAlarm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedStateSmokeAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1normal/title",
          "value": "MTRSmokeCOAlarmExpressedStateNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedStateNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1hardwareFault/title",
          "value": "MTRSmokeCOAlarmExpressedStateHardwareFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1hardwareFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedStateHardwareFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1interconnectSmoke/title",
          "value": "MTRSmokeCOAlarmExpressedStateInterconnectSmoke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1interconnectSmoke/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedStateInterconnectSmoke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1coAlarm/title",
          "value": "MTRSmokeCOAlarmExpressedStateCOAlarm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1coAlarm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedStateCOAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1endOfService/title",
          "value": "MTRSmokeCOAlarmExpressedStateEndOfService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1endOfService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedStateEndOfService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1interconnectCO/title",
          "value": "MTRSmokeCOAlarmExpressedStateInterconnectCO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1interconnectCO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedStateInterconnectCO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1testing/title",
          "value": "MTRSmokeCOAlarmExpressedStateTesting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSmokeCOAlarmExpressedState~1testing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSmokeCOAlarmExpressedStateTesting"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrsmokecoalarmexpressedstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrsmokecoalarmexpressedstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
