{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRServerAttribute"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRServerAttribute",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRServerAttribute"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRServerAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRServerAttribute"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRServerAttribute"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRServerAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRServerAttribute"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRServerAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRServerAttribute"
        }
      ],
      "role": "symbol",
      "title": "MTRServerAttribute",
      "type": "topic",
      "url": "/documentation/matter/mtrserverattribute"
    },
    "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/attributeID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributeID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/attributeID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributeID"
        }
      ],
      "role": "symbol",
      "title": "attributeID",
      "type": "topic",
      "url": "/documentation/matter/mtrserverattribute/attributeid"
    },
    "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/init(readonlyAttributeWithID:initialValue:requiredPrivilege:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "readonlyAttributeWithID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "initialValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "requiredPrivilege"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRAccessControlEntryPrivilege",
          "text": "MTRAccessControlEntryPrivilege"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/init(readonlyAttributeWithID:initialValue:requiredPrivilege:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initReadonlyAttributeWithID:initialValue:requiredPrivilege:"
        }
      ],
      "role": "symbol",
      "title": "init(readonlyAttributeWithID:initialValue:requiredPrivilege:)",
      "type": "topic",
      "url": "/documentation/matter/mtrserverattribute/init(readonlyattributewithid:initialvalue:requiredprivilege:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/isWritable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/isWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writable"
        }
      ],
      "role": "symbol",
      "title": "isWritable",
      "type": "topic",
      "url": "/documentation/matter/mtrserverattribute/iswritable"
    },
    "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/newFeatureMapAttribute(withInitialValue:)": {
      "abstract": [
        {
          "text": "Create an attribute description for a FeatureMap attribute with the provided",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "value (expected to be an unsigned integer representing the value of the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "bitmap). This will automatically set requiredPrivilege to the right value",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "for FeatureMap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newFeatureMapAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withInitialValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/newFeatureMapAttribute(withInitialValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newFeatureMapAttributeWithInitialValue:"
        }
      ],
      "role": "symbol",
      "title": "newFeatureMapAttribute(withInitialValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrserverattribute/newfeaturemapattribute(withinitialvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/requiredReadPrivilege": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiredReadPrivilege"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRAccessControlEntryPrivilege",
          "text": "MTRAccessControlEntryPrivilege"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/requiredReadPrivilege",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiredReadPrivilege"
        }
      ],
      "role": "symbol",
      "title": "requiredReadPrivilege",
      "type": "topic",
      "url": "/documentation/matter/mtrserverattribute/requiredreadprivilege"
    },
    "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/setValue(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setValue"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/setValue(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setValue:"
        }
      ],
      "role": "symbol",
      "title": "setValue(_:)",
      "type": "topic",
      "url": "/documentation/matter/mtrserverattribute/setvalue(_:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/value": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/matter/mtrserverattribute/value"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/init(readonlyAttributeWithID:initialValue:requiredPrivilege:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/attributeID",
        "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/isWritable",
        "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/requiredReadPrivilege",
        "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/value"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/setValue(_:)"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/newFeatureMapAttribute(withInitialValue:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRServerAttribute"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRServerAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRServerAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/init(readonlyAttributeWithID:initialValue:requiredPrivilege:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/attributeID",
                "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/isWritable",
                "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/requiredReadPrivilege",
                "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/value"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/setValue(_:)"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRServerAttribute/newFeatureMapAttribute(withInitialValue:)"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRServerAttribute"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute/title",
          "value": "MTRServerAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRServerAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRServerAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1setValue(_:)/title",
          "value": "setValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1setValue(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1attributeID/title",
          "value": "attributeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1attributeID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1requiredReadPrivilege/title",
          "value": "requiredReadPrivilege"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1requiredReadPrivilege/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiredReadPrivilege"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1newFeatureMapAttribute(withInitialValue:)/title",
          "value": "newFeatureMapAttributeWithInitialValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1newFeatureMapAttribute(withInitialValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "newFeatureMapAttributeWithInitialValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1isWritable/title",
          "value": "writable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1isWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "writable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1init(readonlyAttributeWithID:initialValue:requiredPrivilege:)/title",
          "value": "initReadonlyAttributeWithID:initialValue:requiredPrivilege:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1init(readonlyAttributeWithID:initialValue:requiredPrivilege:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initReadonlyAttributeWithID:initialValue:requiredPrivilege:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1value/title",
          "value": "value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRServerAttribute~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "value"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrserverattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrserverattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
