{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRUnitTestingClusterNullablesAndOptionalsStruct",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRTestClusterClusterNullablesAndOptionalsStruct",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRTestClusterClusterNullablesAndOptionalsStruct"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRTestClusterClusterNullablesAndOptionalsStruct"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRUnitTestingClusterNullablesAndOptionalsStruct",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRUnitTestingClusterNullablesAndOptionalsStruct",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRUnitTestingClusterNullablesAndOptionalsStruct",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "Please use MTRUnitTestingClusterNullablesAndOptionalsStruct",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use MTRUnitTestingClusterNullablesAndOptionalsStruct",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRUnitTestingClusterNullablesAndOptionalsStruct",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "Please use MTRUnitTestingClusterNullablesAndOptionalsStruct",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRTestClusterClusterNullablesAndOptionalsStruct"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRTestClusterClusterNullablesAndOptionalsStruct"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRTestClusterClusterNullablesAndOptionalsStruct"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTestClusterClusterNullablesAndOptionalsStruct"
        }
      ],
      "role": "symbol",
      "title": "MTRTestClusterClusterNullablesAndOptionalsStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableInt": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableInt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableInt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableInt"
        }
      ],
      "role": "symbol",
      "title": "nullableInt",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/nullableint"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableList"
        }
      ],
      "role": "symbol",
      "title": "nullableList",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/nullablelist"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalInt": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalInt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalInt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalInt"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalInt",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/nullableoptionalint"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalList"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalList",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/nullableoptionallist"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalString": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalString"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalString",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/nullableoptionalstring"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalStruct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalStruct"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRTestClusterClusterSimpleStruct",
          "text": "MTRTestClusterClusterSimpleStruct"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalStruct"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/nullableoptionalstruct"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableString": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableString"
        }
      ],
      "role": "symbol",
      "title": "nullableString",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/nullablestring"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableStruct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableStruct"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRTestClusterClusterSimpleStruct",
          "text": "MTRTestClusterClusterSimpleStruct"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableStruct"
        }
      ],
      "role": "symbol",
      "title": "nullableStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/nullablestruct"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalInt": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalInt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalInt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalInt"
        }
      ],
      "role": "symbol",
      "title": "optionalInt",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/optionalint"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalList"
        }
      ],
      "role": "symbol",
      "title": "optionalList",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/optionallist"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalString": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalString"
        }
      ],
      "role": "symbol",
      "title": "optionalString",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/optionalstring"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalStruct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalStruct"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRTestClusterClusterSimpleStruct",
          "text": "MTRTestClusterClusterSimpleStruct"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalStruct"
        }
      ],
      "role": "symbol",
      "title": "optionalStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct/optionalstruct"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterNullablesAndOptionalsStruct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRUnitTestingClusterNullablesAndOptionalsStruct"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterNullablesAndOptionalsStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRUnitTestingClusterNullablesAndOptionalsStruct"
        }
      ],
      "role": "symbol",
      "title": "MTRUnitTestingClusterNullablesAndOptionalsStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclusternullablesandoptionalsstruct"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterNullablesAndOptionalsStruct"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableInt",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableList",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalInt",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalList",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalString",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalStruct",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableString",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableStruct",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalInt",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalList",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalString",
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalStruct"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRTestClusterClusterNullablesAndOptionalsStruct"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTestClusterClusterNullablesAndOptionalsStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTestClusterClusterNullablesAndOptionalsStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableInt",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableList",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalInt",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalList",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalString",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableOptionalStruct",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableString",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/nullableStruct",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalInt",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalList",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalString",
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterNullablesAndOptionalsStruct/optionalStruct"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterNullablesAndOptionalsStruct"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRTestClusterClusterNullablesAndOptionalsStruct"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterNullablesAndOptionalsStruct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRUnitTestingClusterNullablesAndOptionalsStruct",
                    "text": "MTRUnitTestingClusterNullablesAndOptionalsStruct"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRUnitTestingClusterNullablesAndOptionalsStruct",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableOptionalStruct/title",
          "value": "nullableOptionalStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableOptionalStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1optionalString/title",
          "value": "optionalString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1optionalString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1optionalStruct/title",
          "value": "optionalStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1optionalStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableInt/title",
          "value": "nullableInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableInt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterNullablesAndOptionalsStruct/title",
          "value": "MTRUnitTestingClusterNullablesAndOptionalsStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterNullablesAndOptionalsStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterNullablesAndOptionalsStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterNullablesAndOptionalsStruct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterNullablesAndOptionalsStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1optionalList/title",
          "value": "optionalList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1optionalList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1optionalInt/title",
          "value": "optionalInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1optionalInt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableList/title",
          "value": "nullableList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct/title",
          "value": "MTRTestClusterClusterNullablesAndOptionalsStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTestClusterClusterNullablesAndOptionalsStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTestClusterClusterNullablesAndOptionalsStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableStruct/title",
          "value": "nullableStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableOptionalInt/title",
          "value": "nullableOptionalInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableOptionalInt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableOptionalList/title",
          "value": "nullableOptionalList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableOptionalList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableOptionalString/title",
          "value": "nullableOptionalString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableOptionalString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableString/title",
          "value": "nullableString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterNullablesAndOptionalsStruct~1nullableString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableString"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrtestclusterclusternullablesandoptionalsstruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
