{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRThermostatControlSequenceOfOperation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRThermostatControlSequenceOfOperation"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRThermostatControlSequenceOfOperation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRThermostatControlSequenceOfOperation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRThermostatControlSequenceOfOperation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatControlSequenceOfOperation"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatControlSequenceOfOperation",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatcontrolsequenceofoperation"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingAndHeating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coolingAndHeating"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingAndHeating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatControlSequenceOfOperationCoolingAndHeating"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatControlSequenceOfOperation.coolingAndHeating",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatcontrolsequenceofoperation/coolingandheating"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingAndHeatingWithReheat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coolingAndHeatingWithReheat"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingAndHeatingWithReheat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatControlSequenceOfOperationCoolingAndHeatingWithReheat"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatControlSequenceOfOperation.coolingAndHeatingWithReheat",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatcontrolsequenceofoperation/coolingandheatingwithreheat"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coolingOnly"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatControlSequenceOfOperationCoolingOnly"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatControlSequenceOfOperation.coolingOnly",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatcontrolsequenceofoperation/coolingonly"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingWithReheat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coolingWithReheat"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingWithReheat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatControlSequenceOfOperationCoolingWithReheat"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatControlSequenceOfOperation.coolingWithReheat",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatcontrolsequenceofoperation/coolingwithreheat"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/heatingOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heatingOnly"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/heatingOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatControlSequenceOfOperationHeatingOnly"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatControlSequenceOfOperation.heatingOnly",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatcontrolsequenceofoperation/heatingonly"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/heatingWithReheat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heatingWithReheat"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/heatingWithReheat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatControlSequenceOfOperationHeatingWithReheat"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatControlSequenceOfOperation.heatingWithReheat",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatcontrolsequenceofoperation/heatingwithreheat"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatcontrolsequenceofoperation/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingAndHeating",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingAndHeatingWithReheat",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingOnly",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingWithReheat",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/heatingOnly",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/heatingWithReheat"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRThermostatControlSequenceOfOperation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingAndHeating",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingAndHeatingWithReheat",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingOnly",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/coolingWithReheat",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/heatingOnly",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatControlSequenceOfOperation/heatingWithReheat"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRThermostatControlSequenceOfOperation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation/title",
          "value": "MTRThermostatControlSequenceOfOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1coolingOnly/title",
          "value": "MTRThermostatControlSequenceOfOperationCoolingOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1coolingOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperationCoolingOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1coolingAndHeating/title",
          "value": "MTRThermostatControlSequenceOfOperationCoolingAndHeating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1coolingAndHeating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperationCoolingAndHeating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1coolingWithReheat/title",
          "value": "MTRThermostatControlSequenceOfOperationCoolingWithReheat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1coolingWithReheat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperationCoolingWithReheat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1heatingOnly/title",
          "value": "MTRThermostatControlSequenceOfOperationHeatingOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1heatingOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperationHeatingOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1heatingWithReheat/title",
          "value": "MTRThermostatControlSequenceOfOperationHeatingWithReheat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1heatingWithReheat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperationHeatingWithReheat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1coolingAndHeatingWithReheat/title",
          "value": "MTRThermostatControlSequenceOfOperationCoolingAndHeatingWithReheat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatControlSequenceOfOperation~1coolingAndHeatingWithReheat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatControlSequenceOfOperationCoolingAndHeatingWithReheat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrthermostatcontrolsequenceofoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrthermostatcontrolsequenceofoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
