{
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRTimeFormatLocalizationCalendarType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRTimeFormatLocalizationCalendarType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRTimeFormatLocalizationCalendarType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRTimeFormatLocalizationCalendarType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarType"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/buddhist": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buddhist"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/buddhist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeBuddhist"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.buddhist",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/buddhist"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/chinese": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chinese"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/chinese",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeChinese"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.chinese",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/chinese"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/coptic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coptic"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/coptic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeCoptic"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.coptic",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/coptic"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/ethiopian": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ethiopian"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/ethiopian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeEthiopian"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.ethiopian",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/ethiopian"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/gregorian": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gregorian"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/gregorian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeGregorian"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.gregorian",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/gregorian"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/hebrew": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hebrew"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/hebrew",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeHebrew"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.hebrew",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/hebrew"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/indian": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indian"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/indian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeIndian"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.indian",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/indian"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/islamic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "islamic"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/islamic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeIslamic"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.islamic",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/islamic"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/japanese": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "japanese"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/japanese",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeJapanese"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.japanese",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/japanese"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/korean": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "korean"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/korean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeKorean"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.korean",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/korean"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/persian": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persian"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/persian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypePersian"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.persian",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/persian"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/taiwanese": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "taiwanese"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/taiwanese",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeTaiwanese"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.taiwanese",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/taiwanese"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/useActiveLocale": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useActiveLocale"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/useActiveLocale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeFormatLocalizationCalendarTypeUseActiveLocale"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeFormatLocalizationCalendarType.useActiveLocale",
      "type": "topic",
      "url": "/documentation/matter/mtrtimeformatlocalizationcalendartype/useactivelocale"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/buddhist",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/chinese",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/coptic",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/ethiopian",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/gregorian",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/hebrew",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/indian",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/islamic",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/japanese",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/korean",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/persian",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/taiwanese",
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/useActiveLocale"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRTimeFormatLocalizationCalendarType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/buddhist",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/chinese",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/coptic",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/ethiopian",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/gregorian",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/hebrew",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/indian",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/islamic",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/japanese",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/korean",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/persian",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/taiwanese",
                "doc://com.apple.matter/documentation/Matter/MTRTimeFormatLocalizationCalendarType/useActiveLocale"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRTimeFormatLocalizationCalendarType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1chinese/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeChinese"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1chinese/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeChinese"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1korean/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeKorean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1korean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeKorean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1indian/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeIndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1indian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeIndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1coptic/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeCoptic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1coptic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeCoptic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1persian/title",
          "value": "MTRTimeFormatLocalizationCalendarTypePersian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1persian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypePersian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1useActiveLocale/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeUseActiveLocale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1useActiveLocale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeUseActiveLocale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1gregorian/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeGregorian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1gregorian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeGregorian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType/title",
          "value": "MTRTimeFormatLocalizationCalendarType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1islamic/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeIslamic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1islamic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeIslamic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1japanese/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeJapanese"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1japanese/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeJapanese"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1hebrew/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeHebrew"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1hebrew/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeHebrew"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1taiwanese/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeTaiwanese"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1taiwanese/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeTaiwanese"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1buddhist/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeBuddhist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1buddhist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeBuddhist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1ethiopian/title",
          "value": "MTRTimeFormatLocalizationCalendarTypeEthiopian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeFormatLocalizationCalendarType~1ethiopian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeFormatLocalizationCalendarTypeEthiopian"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrtimeformatlocalizationcalendartype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrtimeformatlocalizationcalendartype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
