{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRThreadNetworkDiagnosticsClusterNeighborTableStruct",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTable": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsClusterNeighborTable"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsClusterNeighborTable"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsClusterNeighborTable",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortable"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/age": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "age"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/age",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "age"
        }
      ],
      "role": "symbol",
      "title": "age",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/age"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/averageRssi": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "averageRssi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/averageRssi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "averageRssi"
        }
      ],
      "role": "symbol",
      "title": "averageRssi",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/averagerssi"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/extAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/extAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extAddress"
        }
      ],
      "role": "symbol",
      "title": "extAddress",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/extaddress"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/frameErrorRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameErrorRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/frameErrorRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frameErrorRate"
        }
      ],
      "role": "symbol",
      "title": "frameErrorRate",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/frameerrorrate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/fullNetworkData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullNetworkData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/fullNetworkData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fullNetworkData"
        }
      ],
      "role": "symbol",
      "title": "fullNetworkData",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/fullnetworkdata"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/fullThreadDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullThreadDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/fullThreadDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fullThreadDevice"
        }
      ],
      "role": "symbol",
      "title": "fullThreadDevice",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/fullthreaddevice"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/isChild": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isChild"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/isChild",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isChild"
        }
      ],
      "role": "symbol",
      "title": "isChild",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/ischild"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/lastRssi": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastRssi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/lastRssi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastRssi"
        }
      ],
      "role": "symbol",
      "title": "lastRssi",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/lastrssi"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/linkFrameCounter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkFrameCounter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/linkFrameCounter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linkFrameCounter"
        }
      ],
      "role": "symbol",
      "title": "linkFrameCounter",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/linkframecounter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/lqi": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lqi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/lqi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lqi"
        }
      ],
      "role": "symbol",
      "title": "lqi",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/lqi"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/messageErrorRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageErrorRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/messageErrorRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "messageErrorRate"
        }
      ],
      "role": "symbol",
      "title": "messageErrorRate",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/messageerrorrate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/mleFrameCounter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mleFrameCounter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/mleFrameCounter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mleFrameCounter"
        }
      ],
      "role": "symbol",
      "title": "mleFrameCounter",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/mleframecounter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/rloc16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rloc16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/rloc16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rloc16"
        }
      ],
      "role": "symbol",
      "title": "rloc16",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/rloc16"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/rxOnWhenIdle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rxOnWhenIdle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/rxOnWhenIdle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rxOnWhenIdle"
        }
      ],
      "role": "symbol",
      "title": "rxOnWhenIdle",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct/rxonwhenidle"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTable"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/age",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/averageRssi",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/extAddress",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/frameErrorRate",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/fullNetworkData",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/fullThreadDevice",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/isChild",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/lastRssi",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/linkFrameCounter",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/lqi",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/messageErrorRate",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/mleFrameCounter",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/rloc16",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/rxOnWhenIdle"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/age",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/averageRssi",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/extAddress",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/frameErrorRate",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/fullNetworkData",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/fullThreadDevice",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/isChild",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/lastRssi",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/linkFrameCounter",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/lqi",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/messageErrorRate",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/mleFrameCounter",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/rloc16",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/rxOnWhenIdle"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterNeighborTable"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1mleFrameCounter/title",
          "value": "mleFrameCounter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1mleFrameCounter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mleFrameCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1messageErrorRate/title",
          "value": "messageErrorRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1messageErrorRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "messageErrorRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1frameErrorRate/title",
          "value": "frameErrorRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1frameErrorRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frameErrorRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1fullNetworkData/title",
          "value": "fullNetworkData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1fullNetworkData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fullNetworkData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTable/title",
          "value": "MTRThreadNetworkDiagnosticsClusterNeighborTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterNeighborTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterNeighborTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1lqi/title",
          "value": "lqi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1lqi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lqi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1rloc16/title",
          "value": "rloc16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1rloc16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rloc16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1fullThreadDevice/title",
          "value": "fullThreadDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1fullThreadDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fullThreadDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1isChild/title",
          "value": "isChild"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1isChild/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isChild"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1lastRssi/title",
          "value": "lastRssi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1lastRssi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastRssi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/title",
          "value": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterNeighborTableStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1extAddress/title",
          "value": "extAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1extAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1age/title",
          "value": "age"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1age/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "age"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1averageRssi/title",
          "value": "averageRssi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1averageRssi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "averageRssi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1linkFrameCounter/title",
          "value": "linkFrameCounter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1linkFrameCounter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "linkFrameCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1rxOnWhenIdle/title",
          "value": "rxOnWhenIdle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterNeighborTableStruct~1rxOnWhenIdle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rxOnWhenIdle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrthreadnetworkdiagnosticsclusterneighbortablestruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
