{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRThreadNetworkDiagnosticsClusterRouteTableStruct",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTable": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsClusterRouteTable"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsClusterRouteTable"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsClusterRouteTable",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetable"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/age": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "age"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/age",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "age"
        }
      ],
      "role": "symbol",
      "title": "age",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct/age"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/allocated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/allocated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allocated"
        }
      ],
      "role": "symbol",
      "title": "allocated",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct/allocated"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/extAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/extAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extAddress"
        }
      ],
      "role": "symbol",
      "title": "extAddress",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct/extaddress"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/linkEstablished": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/linkEstablished",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linkEstablished"
        }
      ],
      "role": "symbol",
      "title": "linkEstablished",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct/linkestablished"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/lqiIn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lqiIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/lqiIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lqiIn"
        }
      ],
      "role": "symbol",
      "title": "lqiIn",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct/lqiin"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/lqiOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lqiOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/lqiOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lqiOut"
        }
      ],
      "role": "symbol",
      "title": "lqiOut",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct/lqiout"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/nextHop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextHop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/nextHop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextHop"
        }
      ],
      "role": "symbol",
      "title": "nextHop",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct/nexthop"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/pathCost": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pathCost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/pathCost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pathCost"
        }
      ],
      "role": "symbol",
      "title": "pathCost",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct/pathcost"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/rloc16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rloc16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/rloc16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rloc16"
        }
      ],
      "role": "symbol",
      "title": "rloc16",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct/rloc16"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/routerId": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routerId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/routerId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routerId"
        }
      ],
      "role": "symbol",
      "title": "routerId",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct/routerid"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTable"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/age",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/allocated",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/extAddress",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/linkEstablished",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/lqiIn",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/lqiOut",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/nextHop",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/pathCost",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/rloc16",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/routerId"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/age",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/allocated",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/extAddress",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/linkEstablished",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/lqiIn",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/lqiOut",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/nextHop",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/pathCost",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/rloc16",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTableStruct/routerId"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterRouteTable"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTable/title",
          "value": "MTRThreadNetworkDiagnosticsClusterRouteTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterRouteTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterRouteTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1rloc16/title",
          "value": "rloc16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1rloc16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rloc16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1extAddress/title",
          "value": "extAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1extAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1allocated/title",
          "value": "allocated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1allocated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allocated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1lqiIn/title",
          "value": "lqiIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1lqiIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lqiIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1routerId/title",
          "value": "routerId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1routerId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "routerId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1age/title",
          "value": "age"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1age/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "age"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1nextHop/title",
          "value": "nextHop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1nextHop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nextHop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1linkEstablished/title",
          "value": "linkEstablished"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1linkEstablished/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "linkEstablished"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1pathCost/title",
          "value": "pathCost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1pathCost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pathCost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct/title",
          "value": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterRouteTableStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1lqiOut/title",
          "value": "lqiOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterRouteTableStruct~1lqiOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lqiOut"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrthreadnetworkdiagnosticsclusterroutetablestruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
