{
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRTimeSynchronizationTimeSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRTimeSynchronizationTimeSource"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRTimeSynchronizationTimeSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRTimeSynchronizationTimeSource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSource"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/GNSS-swift.enum.case": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GNSS"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/GNSS-swift.enum.case",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceGNSS"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.GNSS",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/gnss-swift.enum.case"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/PTP-swift.enum.case": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTP"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/PTP-swift.enum.case",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourcePTP"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.PTP",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/ptp-swift.enum.case"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/admin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "admin"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/admin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceAdmin"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.admin",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/admin"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/cloudSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/cloudSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceCloudSource"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.cloudSource",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/cloudsource"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricNtp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricNtp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricNtp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceFabricNtp"
        }
      ],
      "role": "symbol",
      "title": "fabricNtp",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/fabricntp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricNtpNts": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricNtpNts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricNtpNts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceFabricNtpNts"
        }
      ],
      "role": "symbol",
      "title": "fabricNtpNts",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/fabricntpnts"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricSntp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricSntp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricSntp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceFabricSntp"
        }
      ],
      "role": "symbol",
      "title": "fabricSntp",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/fabricsntp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricSntpNts": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricSntpNts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricSntpNts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceFabricSntpNts"
        }
      ],
      "role": "symbol",
      "title": "fabricSntpNts",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/fabricsntpnts"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/gnss-swift.type.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gnss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/gnss-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceGnss"
        }
      ],
      "role": "symbol",
      "title": "gnss",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/gnss-swift.type.property"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterNTP": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matterNTP"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterNTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceMatterNTP"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.matterNTP",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/matterntp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterNTPNTS": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matterNTPNTS"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterNTPNTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceMatterNTPNTS"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.matterNTPNTS",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/matterntpnts"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterSNTP": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matterSNTP"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterSNTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceMatterSNTP"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.matterSNTP",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/mattersntp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterSNTPNTS": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matterSNTPNTS"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterSNTPNTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceMatterSNTPNTS"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.matterSNTPNTS",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/mattersntpnts"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNTP-swift.enum.case": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixedNTP"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNTP-swift.enum.case",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceMixedNTP"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.mixedNTP",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/mixedntp-swift.enum.case"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNTPNTS-swift.enum.case": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixedNTPNTS"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNTPNTS-swift.enum.case",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceMixedNTPNTS"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.mixedNTPNTS",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/mixedntpnts-swift.enum.case"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNtp-swift.type.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixedNtp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNtp-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceMixedNtp"
        }
      ],
      "role": "symbol",
      "title": "mixedNtp",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/mixedntp-swift.type.property"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNtpNts-swift.type.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixedNtpNts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNtpNts-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceMixedNtpNts"
        }
      ],
      "role": "symbol",
      "title": "mixedNtpNts",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/mixedntpnts-swift.type.property"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nodeTimeCluster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nodeTimeCluster"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nodeTimeCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceNodeTimeCluster"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.nodeTimeCluster",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/nodetimecluster"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricNtp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonFabricNtp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricNtp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceNonFabricNtp"
        }
      ],
      "role": "symbol",
      "title": "nonFabricNtp",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/nonfabricntp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricNtpNts": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonFabricNtpNts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricNtpNts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceNonFabricNtpNts"
        }
      ],
      "role": "symbol",
      "title": "nonFabricNtpNts",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/nonfabricntpnts"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricSntp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonFabricSntp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricSntp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceNonFabricSntp"
        }
      ],
      "role": "symbol",
      "title": "nonFabricSntp",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/nonfabricsntp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricSntpNts": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonFabricSntpNts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricSntpNts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceNonFabricSntpNts"
        }
      ],
      "role": "symbol",
      "title": "nonFabricSntpNts",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/nonfabricsntpnts"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterNTP": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonMatterNTP"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterNTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceNonMatterNTP"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.nonMatterNTP",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/nonmatterntp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterNTPNTS": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonMatterNTPNTS"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterNTPNTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceNonMatterNTPNTS"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.nonMatterNTPNTS",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/nonmatterntpnts"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterSNTP": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonMatterSNTP"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterSNTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceNonMatterSNTP"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.nonMatterSNTP",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/nonmattersntp"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterSNTPNTS": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonMatterSNTPNTS"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterSNTPNTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceNonMatterSNTPNTS"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.nonMatterSNTPNTS",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/nonmattersntpnts"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceNone"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.none",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/none"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/ptp-swift.type.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ptp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRTimeSynchronizationTimeSource",
          "text": "MTRTimeSynchronizationTimeSource"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/ptp-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourcePtp"
        }
      ],
      "role": "symbol",
      "title": "ptp",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/ptp-swift.type.property"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTimeSynchronizationTimeSourceUnknown"
        }
      ],
      "role": "symbol",
      "title": "MTRTimeSynchronizationTimeSource.unknown",
      "type": "topic",
      "url": "/documentation/matter/mtrtimesynchronizationtimesource/unknown"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/admin",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/cloudSource",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nodeTimeCluster",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/none",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/unknown",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/GNSS-swift.enum.case",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/PTP-swift.enum.case",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterNTP",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterNTPNTS",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterSNTP",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterSNTPNTS",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNTP-swift.enum.case",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNTPNTS-swift.enum.case",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterNTP",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterNTPNTS",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterSNTP",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterSNTPNTS"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricNtp",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricNtpNts",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricSntp",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricSntpNts",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/gnss-swift.type.property",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNtp-swift.type.property",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNtpNts-swift.type.property",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricNtp",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricNtpNts",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricSntp",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricSntpNts",
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/ptp-swift.type.property"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRTimeSynchronizationTimeSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/admin",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/cloudSource",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nodeTimeCluster",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/none",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/unknown",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/GNSS-swift.enum.case",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/PTP-swift.enum.case",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterNTP",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterNTPNTS",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterSNTP",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/matterSNTPNTS",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNTP-swift.enum.case",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNTPNTS-swift.enum.case",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterNTP",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterNTPNTS",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterSNTP",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonMatterSNTPNTS"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricNtp",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricNtpNts",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricSntp",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/fabricSntpNts",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/gnss-swift.type.property",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNtp-swift.type.property",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/mixedNtpNts-swift.type.property",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricNtp",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricNtpNts",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricSntp",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/nonFabricSntpNts",
                "doc://com.apple.matter/documentation/Matter/MTRTimeSynchronizationTimeSource/ptp-swift.type.property"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRTimeSynchronizationTimeSource"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1matterSNTP/title",
          "value": "MTRTimeSynchronizationTimeSourceMatterSNTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1matterSNTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceMatterSNTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1mixedNtpNts-swift.type.property/title",
          "value": "MTRTimeSynchronizationTimeSourceMixedNtpNts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1mixedNtpNts-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceMixedNtpNts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1matterNTPNTS/title",
          "value": "MTRTimeSynchronizationTimeSourceMatterNTPNTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1matterNTPNTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceMatterNTPNTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonFabricNtpNts/title",
          "value": "MTRTimeSynchronizationTimeSourceNonFabricNtpNts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonFabricNtpNts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceNonFabricNtpNts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1gnss-swift.type.property/title",
          "value": "MTRTimeSynchronizationTimeSourceGnss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1gnss-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceGnss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonFabricSntp/title",
          "value": "MTRTimeSynchronizationTimeSourceNonFabricSntp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonFabricSntp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceNonFabricSntp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1fabricNtpNts/title",
          "value": "MTRTimeSynchronizationTimeSourceFabricNtpNts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1fabricNtpNts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceFabricNtpNts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1mixedNTP-swift.enum.case/title",
          "value": "MTRTimeSynchronizationTimeSourceMixedNTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1mixedNTP-swift.enum.case/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceMixedNTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1mixedNTPNTS-swift.enum.case/title",
          "value": "MTRTimeSynchronizationTimeSourceMixedNTPNTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1mixedNTPNTS-swift.enum.case/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceMixedNTPNTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1GNSS-swift.enum.case/title",
          "value": "MTRTimeSynchronizationTimeSourceGNSS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1GNSS-swift.enum.case/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceGNSS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1PTP-swift.enum.case/title",
          "value": "MTRTimeSynchronizationTimeSourcePTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1PTP-swift.enum.case/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourcePTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1fabricSntpNts/title",
          "value": "MTRTimeSynchronizationTimeSourceFabricSntpNts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1fabricSntpNts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceFabricSntpNts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1none/title",
          "value": "MTRTimeSynchronizationTimeSourceNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1unknown/title",
          "value": "MTRTimeSynchronizationTimeSourceUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1cloudSource/title",
          "value": "MTRTimeSynchronizationTimeSourceCloudSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1cloudSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceCloudSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource/title",
          "value": "MTRTimeSynchronizationTimeSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nodeTimeCluster/title",
          "value": "MTRTimeSynchronizationTimeSourceNodeTimeCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nodeTimeCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceNodeTimeCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1admin/title",
          "value": "MTRTimeSynchronizationTimeSourceAdmin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1admin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceAdmin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonFabricSntpNts/title",
          "value": "MTRTimeSynchronizationTimeSourceNonFabricSntpNts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonFabricSntpNts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceNonFabricSntpNts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1fabricNtp/title",
          "value": "MTRTimeSynchronizationTimeSourceFabricNtp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1fabricNtp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceFabricNtp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonMatterNTP/title",
          "value": "MTRTimeSynchronizationTimeSourceNonMatterNTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonMatterNTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceNonMatterNTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1fabricSntp/title",
          "value": "MTRTimeSynchronizationTimeSourceFabricSntp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1fabricSntp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceFabricSntp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1mixedNtp-swift.type.property/title",
          "value": "MTRTimeSynchronizationTimeSourceMixedNtp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1mixedNtp-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceMixedNtp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonMatterNTPNTS/title",
          "value": "MTRTimeSynchronizationTimeSourceNonMatterNTPNTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonMatterNTPNTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceNonMatterNTPNTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1matterSNTPNTS/title",
          "value": "MTRTimeSynchronizationTimeSourceMatterSNTPNTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1matterSNTPNTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceMatterSNTPNTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonMatterSNTPNTS/title",
          "value": "MTRTimeSynchronizationTimeSourceNonMatterSNTPNTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonMatterSNTPNTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceNonMatterSNTPNTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1ptp-swift.type.property/title",
          "value": "MTRTimeSynchronizationTimeSourcePtp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1ptp-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourcePtp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1matterNTP/title",
          "value": "MTRTimeSynchronizationTimeSourceMatterNTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1matterNTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceMatterNTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonFabricNtp/title",
          "value": "MTRTimeSynchronizationTimeSourceNonFabricNtp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonFabricNtp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceNonFabricNtp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonMatterSNTP/title",
          "value": "MTRTimeSynchronizationTimeSourceNonMatterSNTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTimeSynchronizationTimeSource~1nonMatterSNTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTimeSynchronizationTimeSourceNonMatterSNTP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrtimesynchronizationtimesource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrtimesynchronizationtimesource"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
