{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRThreadNetworkDiagnosticsRoutingRole",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRThreadNetworkDiagnosticsRoutingRole"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRThreadNetworkDiagnosticsRoutingRole"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRThreadNetworkDiagnosticsRoutingRole"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRole"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsRoutingRole"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsRoutingRole"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsRoutingRole",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/REED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "REED"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/REED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsRoutingRoleREED"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsRoutingRole.REED",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole/reed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/endDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endDevice"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/endDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsRoutingRoleEndDevice"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsRoutingRole.endDevice",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole/enddevice"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/leader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leader"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/leader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsRoutingRoleLeader"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsRoutingRole.leader",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole/leader"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/router": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "router"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/router",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsRoutingRoleRouter"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsRoutingRole.router",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole/router"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/sleepyEndDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepyEndDevice"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/sleepyEndDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsRoutingRoleSleepyEndDevice"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsRoutingRole.sleepyEndDevice",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole/sleepyenddevice"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/unassigned": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unassigned"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/unassigned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsRoutingRoleUnassigned"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsRoutingRole.unassigned",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole/unassigned"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsRoutingRoleUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsRoutingRole.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole/unspecified"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/REED",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/endDevice",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/leader",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/router",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/sleepyEndDevice",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/unassigned",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/unspecified"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRThreadNetworkDiagnosticsRoutingRole"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/REED",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/endDevice",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/leader",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/router",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/sleepyEndDevice",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/unassigned",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsRoutingRole/unspecified"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRThreadNetworkDiagnosticsRoutingRole"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1unassigned/title",
          "value": "MTRThreadNetworkDiagnosticsRoutingRoleUnassigned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1unassigned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRoleUnassigned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1router/title",
          "value": "MTRThreadNetworkDiagnosticsRoutingRoleRouter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1router/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRoleRouter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole/title",
          "value": "MTRThreadNetworkDiagnosticsRoutingRole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1sleepyEndDevice/title",
          "value": "MTRThreadNetworkDiagnosticsRoutingRoleSleepyEndDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1sleepyEndDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRoleSleepyEndDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1leader/title",
          "value": "MTRThreadNetworkDiagnosticsRoutingRoleLeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1leader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRoleLeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1endDevice/title",
          "value": "MTRThreadNetworkDiagnosticsRoutingRoleEndDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1endDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRoleEndDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1REED/title",
          "value": "MTRThreadNetworkDiagnosticsRoutingRoleREED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1REED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRoleREED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1unspecified/title",
          "value": "MTRThreadNetworkDiagnosticsRoutingRoleUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsRoutingRole~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsRoutingRoleUnspecified"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrthreadnetworkdiagnosticsroutingrole"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
