{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/activeTimestampPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeTimestampPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/activeTimestampPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activeTimestampPresent"
        }
      ],
      "role": "symbol",
      "title": "activeTimestampPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/activetimestamppresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/channelMaskPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelMaskPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/channelMaskPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelMaskPresent"
        }
      ],
      "role": "symbol",
      "title": "channelMaskPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/channelmaskpresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/channelPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/channelPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelPresent"
        }
      ],
      "role": "symbol",
      "title": "channelPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/channelpresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/delayPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delayPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/delayPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delayPresent"
        }
      ],
      "role": "symbol",
      "title": "delayPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/delaypresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/extendedPanIdPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedPanIdPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/extendedPanIdPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedPanIdPresent"
        }
      ],
      "role": "symbol",
      "title": "extendedPanIdPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/extendedpanidpresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/masterKeyPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "masterKeyPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/masterKeyPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "masterKeyPresent"
        }
      ],
      "role": "symbol",
      "title": "masterKeyPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/masterkeypresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/meshLocalPrefixPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meshLocalPrefixPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/meshLocalPrefixPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "meshLocalPrefixPresent"
        }
      ],
      "role": "symbol",
      "title": "meshLocalPrefixPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/meshlocalprefixpresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/networkNamePresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkNamePresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/networkNamePresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkNamePresent"
        }
      ],
      "role": "symbol",
      "title": "networkNamePresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/networknamepresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/panIdPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panIdPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/panIdPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panIdPresent"
        }
      ],
      "role": "symbol",
      "title": "panIdPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/panidpresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/pendingTimestampPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pendingTimestampPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/pendingTimestampPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pendingTimestampPresent"
        }
      ],
      "role": "symbol",
      "title": "pendingTimestampPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/pendingtimestamppresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/pskcPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pskcPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/pskcPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pskcPresent"
        }
      ],
      "role": "symbol",
      "title": "pskcPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/pskcpresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/securityPolicyPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securityPolicyPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/securityPolicyPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "securityPolicyPresent"
        }
      ],
      "role": "symbol",
      "title": "securityPolicyPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents/securitypolicypresent"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/activeTimestampPresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/channelMaskPresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/channelPresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/delayPresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/extendedPanIdPresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/masterKeyPresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/meshLocalPrefixPresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/networkNamePresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/panIdPresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/pendingTimestampPresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/pskcPresent",
        "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/securityPolicyPresent"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/activeTimestampPresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/channelMaskPresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/channelPresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/delayPresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/extendedPanIdPresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/masterKeyPresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/meshLocalPrefixPresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/networkNamePresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/panIdPresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/pendingTimestampPresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/pskcPresent",
                "doc://com.apple.matter/documentation/Matter/MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/securityPolicyPresent"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1pendingTimestampPresent/title",
          "value": "pendingTimestampPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1pendingTimestampPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pendingTimestampPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1extendedPanIdPresent/title",
          "value": "extendedPanIdPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1extendedPanIdPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedPanIdPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1masterKeyPresent/title",
          "value": "masterKeyPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1masterKeyPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "masterKeyPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1networkNamePresent/title",
          "value": "networkNamePresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1networkNamePresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkNamePresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/title",
          "value": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1securityPolicyPresent/title",
          "value": "securityPolicyPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1securityPolicyPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "securityPolicyPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1delayPresent/title",
          "value": "delayPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1delayPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delayPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1meshLocalPrefixPresent/title",
          "value": "meshLocalPrefixPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1meshLocalPrefixPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "meshLocalPrefixPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1channelMaskPresent/title",
          "value": "channelMaskPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1channelMaskPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "channelMaskPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1pskcPresent/title",
          "value": "pskcPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1pskcPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pskcPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1activeTimestampPresent/title",
          "value": "activeTimestampPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1activeTimestampPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activeTimestampPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1panIdPresent/title",
          "value": "panIdPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1panIdPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "panIdPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1channelPresent/title",
          "value": "channelPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents~1channelPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "channelPresent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrthreadnetworkdiagnosticsclusteroperationaldatasetcomponents"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
