{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRThermostatSystemMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRThermostatSystemMode"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRThermostatSystemMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRThermostatSystemMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemMode"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemMode"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatSystemMode",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/auto": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemModeAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatSystemMode.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/cool": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cool"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/cool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemModeCool"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatSystemMode.cool",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/cool"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/dry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dry"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/dry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemModeDry"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatSystemMode.dry",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/dry"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/emergencyHeat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emergencyHeat"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/emergencyHeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemModeEmergencyHeat"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatSystemMode.emergencyHeat",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/emergencyheat"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/emergencyHeating": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emergencyHeating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRThermostatSystemMode",
          "text": "MTRThermostatSystemMode"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/emergencyHeating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemModeEmergencyHeating"
        }
      ],
      "role": "symbol",
      "title": "emergencyHeating",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/emergencyheating"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/fanOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fanOnly"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/fanOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemModeFanOnly"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatSystemMode.fanOnly",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/fanonly"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/heat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heat"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/heat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemModeHeat"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatSystemMode.heat",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/heat"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/off": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "off"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/off",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemModeOff"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatSystemMode.off",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/off"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/precooling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "precooling"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/precooling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemModePrecooling"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatSystemMode.precooling",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/precooling"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/sleep": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleep"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/sleep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThermostatSystemModeSleep"
        }
      ],
      "role": "symbol",
      "title": "MTRThermostatSystemMode.sleep",
      "type": "topic",
      "url": "/documentation/matter/mtrthermostatsystemmode/sleep"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/auto",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/cool",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/dry",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/emergencyHeat",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/fanOnly",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/heat",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/off",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/precooling",
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/sleep"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/emergencyHeating"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRThermostatSystemMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/auto",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/cool",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/dry",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/emergencyHeat",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/fanOnly",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/heat",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/off",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/precooling",
                "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/sleep"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRThermostatSystemMode/emergencyHeating"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRThermostatSystemMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1emergencyHeat/title",
          "value": "MTRThermostatSystemModeEmergencyHeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1emergencyHeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemModeEmergencyHeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1dry/title",
          "value": "MTRThermostatSystemModeDry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1dry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemModeDry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1sleep/title",
          "value": "MTRThermostatSystemModeSleep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1sleep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemModeSleep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1off/title",
          "value": "MTRThermostatSystemModeOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1off/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemModeOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1auto/title",
          "value": "MTRThermostatSystemModeAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemModeAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1cool/title",
          "value": "MTRThermostatSystemModeCool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1cool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemModeCool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1fanOnly/title",
          "value": "MTRThermostatSystemModeFanOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1fanOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemModeFanOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1heat/title",
          "value": "MTRThermostatSystemModeHeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1heat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemModeHeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode/title",
          "value": "MTRThermostatSystemMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1precooling/title",
          "value": "MTRThermostatSystemModePrecooling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1precooling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemModePrecooling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1emergencyHeating/title",
          "value": "MTRThermostatSystemModeEmergencyHeating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThermostatSystemMode~1emergencyHeating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThermostatSystemModeEmergencyHeating"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrthermostatsystemmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrthermostatsystemmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
