{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRUnitTestingClusterTestComplexNullableOptionalResponseParams",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterTestComplexNullableOptionalResponseParams": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRTestClusterClusterTestComplexNullableOptionalResponseParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterTestComplexNullableOptionalResponseParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTestClusterClusterTestComplexNullableOptionalResponseParams"
        }
      ],
      "role": "symbol",
      "title": "MTRTestClusterClusterTestComplexNullableOptionalResponseParams",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclustertestcomplexnullableoptionalresponseparams"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
        }
      ],
      "role": "symbol",
      "title": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/init(responseValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "responseValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/init(responseValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithResponseValue:error:"
        }
      ],
      "role": "symbol",
      "title": "init(responseValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/init(responsevalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableIntValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableIntValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableIntValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableIntValue"
        }
      ],
      "role": "symbol",
      "title": "nullableIntValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableintvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableIntWasNull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableIntWasNull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableIntWasNull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableIntWasNull"
        }
      ],
      "role": "symbol",
      "title": "nullableIntWasNull",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableintwasnull"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableListValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableListValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableListValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableListValue"
        }
      ],
      "role": "symbol",
      "title": "nullableListValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullablelistvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableListWasNull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableListWasNull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableListWasNull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableListWasNull"
        }
      ],
      "role": "symbol",
      "title": "nullableListWasNull",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullablelistwasnull"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalIntValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalIntValue"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalIntValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionalintvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntWasNull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalIntWasNull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntWasNull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalIntWasNull"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalIntWasNull",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionalintwasnull"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntWasPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalIntWasPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntWasPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalIntWasPresent"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalIntWasPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionalintwaspresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalListValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalListValue"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalListValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionallistvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListWasNull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalListWasNull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListWasNull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalListWasNull"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalListWasNull",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionallistwasnull"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListWasPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalListWasPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListWasPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalListWasPresent"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalListWasPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionallistwaspresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalStringValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalStringValue"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalStringValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionalstringvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringWasNull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalStringWasNull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringWasNull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalStringWasNull"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalStringWasNull",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionalstringwasnull"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringWasPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalStringWasPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringWasPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalStringWasPresent"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalStringWasPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionalstringwaspresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalStructValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRUnitTestingClusterSimpleStruct",
          "text": "MTRUnitTestingClusterSimpleStruct"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalStructValue"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalStructValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionalstructvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructWasNull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalStructWasNull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructWasNull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalStructWasNull"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalStructWasNull",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionalstructwasnull"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructWasPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalStructWasPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructWasPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalStructWasPresent"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalStructWasPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullableoptionalstructwaspresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStringValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableStringValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStringValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableStringValue"
        }
      ],
      "role": "symbol",
      "title": "nullableStringValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullablestringvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStringWasNull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableStringWasNull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStringWasNull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableStringWasNull"
        }
      ],
      "role": "symbol",
      "title": "nullableStringWasNull",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullablestringwasnull"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStructValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableStructValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRUnitTestingClusterSimpleStruct",
          "text": "MTRUnitTestingClusterSimpleStruct"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStructValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableStructValue"
        }
      ],
      "role": "symbol",
      "title": "nullableStructValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullablestructvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStructWasNull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableStructWasNull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStructWasNull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableStructWasNull"
        }
      ],
      "role": "symbol",
      "title": "nullableStructWasNull",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/nullablestructwasnull"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalIntValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalIntValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalIntValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalIntValue"
        }
      ],
      "role": "symbol",
      "title": "optionalIntValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/optionalintvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalIntWasPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalIntWasPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalIntWasPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalIntWasPresent"
        }
      ],
      "role": "symbol",
      "title": "optionalIntWasPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/optionalintwaspresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalListValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalListValue"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalListValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalListValue"
        }
      ],
      "role": "symbol",
      "title": "optionalListValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/optionallistvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalListWasPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalListWasPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalListWasPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalListWasPresent"
        }
      ],
      "role": "symbol",
      "title": "optionalListWasPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/optionallistwaspresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStringValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalStringValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStringValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalStringValue"
        }
      ],
      "role": "symbol",
      "title": "optionalStringValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/optionalstringvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStringWasPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalStringWasPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStringWasPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalStringWasPresent"
        }
      ],
      "role": "symbol",
      "title": "optionalStringWasPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/optionalstringwaspresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStructValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalStructValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRUnitTestingClusterSimpleStruct",
          "text": "MTRUnitTestingClusterSimpleStruct"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStructValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalStructValue"
        }
      ],
      "role": "symbol",
      "title": "optionalStructValue",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/optionalstructvalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStructWasPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalStructWasPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStructWasPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalStructWasPresent"
        }
      ],
      "role": "symbol",
      "title": "optionalStructWasPresent",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/optionalstructwaspresent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/timedInvokeTimeoutMs": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedInvokeTimeoutMs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/timedInvokeTimeoutMs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timedInvokeTimeoutMs"
        }
      ],
      "role": "symbol",
      "title": "timedInvokeTimeoutMs",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams/timedinvoketimeoutms"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterTestComplexNullableOptionalResponseParams"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/init(responseValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableIntValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableIntWasNull",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableListValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableListWasNull",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntWasNull",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntWasPresent",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListWasNull",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListWasPresent",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringWasNull",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringWasPresent",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructWasNull",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructWasPresent",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStringValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStringWasNull",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStructValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStructWasNull",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalIntValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalIntWasPresent",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalListValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalListWasPresent",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStringValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStringWasPresent",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStructValue",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStructWasPresent",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/timedInvokeTimeoutMs"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/init(responseValue:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableIntValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableIntWasNull",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableListValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableListWasNull",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntWasNull",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalIntWasPresent",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListWasNull",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalListWasPresent",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringWasNull",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStringWasPresent",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructWasNull",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableOptionalStructWasPresent",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStringValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStringWasNull",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStructValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/nullableStructWasNull",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalIntValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalIntWasPresent",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalListValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalListWasPresent",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStringValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStringWasPresent",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStructValue",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/optionalStructWasPresent",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/timedInvokeTimeoutMs"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterTestComplexNullableOptionalResponseParams"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableStructWasNull/title",
          "value": "nullableStructWasNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableStructWasNull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableStructWasNull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalListWasPresent/title",
          "value": "optionalListWasPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalListWasPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalListWasPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableIntValue/title",
          "value": "nullableIntValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableIntValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableIntValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStructValue/title",
          "value": "nullableOptionalStructValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStructValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalStructValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableListValue/title",
          "value": "nullableListValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableListValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableListValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalListValue/title",
          "value": "optionalListValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalListValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalListValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStructWasPresent/title",
          "value": "nullableOptionalStructWasPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStructWasPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalStructWasPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalStringWasPresent/title",
          "value": "optionalStringWasPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalStringWasPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalStringWasPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalStructWasPresent/title",
          "value": "optionalStructWasPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalStructWasPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalStructWasPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableStructValue/title",
          "value": "nullableStructValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableStructValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableStructValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableStringValue/title",
          "value": "nullableStringValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableStringValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableStringValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStructWasNull/title",
          "value": "nullableOptionalStructWasNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStructWasNull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalStructWasNull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalIntValue/title",
          "value": "nullableOptionalIntValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalIntValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalIntValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalStructValue/title",
          "value": "optionalStructValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalStructValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalStructValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1init(responseValue:)/title",
          "value": "initWithResponseValue:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1init(responseValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithResponseValue:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/title",
          "value": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterTestComplexNullableOptionalResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableListWasNull/title",
          "value": "nullableListWasNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableListWasNull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableListWasNull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterTestComplexNullableOptionalResponseParams/title",
          "value": "MTRTestClusterClusterTestComplexNullableOptionalResponseParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterTestComplexNullableOptionalResponseParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTestClusterClusterTestComplexNullableOptionalResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterTestComplexNullableOptionalResponseParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTestClusterClusterTestComplexNullableOptionalResponseParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalListValue/title",
          "value": "nullableOptionalListValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalListValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalListValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalStringValue/title",
          "value": "optionalStringValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalStringValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalStringValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalListWasPresent/title",
          "value": "nullableOptionalListWasPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalListWasPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalListWasPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1timedInvokeTimeoutMs/title",
          "value": "timedInvokeTimeoutMs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1timedInvokeTimeoutMs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timedInvokeTimeoutMs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalIntWasPresent/title",
          "value": "nullableOptionalIntWasPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalIntWasPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalIntWasPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStringValue/title",
          "value": "nullableOptionalStringValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStringValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalStringValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStringWasNull/title",
          "value": "nullableOptionalStringWasNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStringWasNull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalStringWasNull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableStringWasNull/title",
          "value": "nullableStringWasNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableStringWasNull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableStringWasNull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableIntWasNull/title",
          "value": "nullableIntWasNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableIntWasNull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableIntWasNull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalListWasNull/title",
          "value": "nullableOptionalListWasNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalListWasNull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalListWasNull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStringWasPresent/title",
          "value": "nullableOptionalStringWasPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalStringWasPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalStringWasPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalIntValue/title",
          "value": "optionalIntValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalIntValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalIntValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalIntWasPresent/title",
          "value": "optionalIntWasPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1optionalIntWasPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalIntWasPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalIntWasNull/title",
          "value": "nullableOptionalIntWasNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestComplexNullableOptionalResponseParams~1nullableOptionalIntWasNull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalIntWasNull"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrunittestingclustertestcomplexnullableoptionalresponseparams"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
