{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRUnitTestingClusterTestFabricScoped",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRUnitTestingClusterTestFabricScoped"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRUnitTestingClusterTestFabricScoped"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTRUnitTestingClusterTestFabricScoped"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterTestFabricScoped"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterTestFabricScoped": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRTestClusterClusterTestFabricScoped"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterTestFabricScoped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRTestClusterClusterTestFabricScoped"
        }
      ],
      "role": "symbol",
      "title": "MTRTestClusterClusterTestFabricScoped",
      "type": "topic",
      "url": "/documentation/matter/mtrtestclusterclustertestfabricscoped"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRUnitTestingClusterTestFabricScoped"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRUnitTestingClusterTestFabricScoped"
        }
      ],
      "role": "symbol",
      "title": "MTRUnitTestingClusterTestFabricScoped",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestfabricscoped"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fabricIndex"
        }
      ],
      "role": "symbol",
      "title": "fabricIndex",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestfabricscoped/fabricindex"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveCharString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricSensitiveCharString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveCharString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fabricSensitiveCharString"
        }
      ],
      "role": "symbol",
      "title": "fabricSensitiveCharString",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestfabricscoped/fabricsensitivecharstring"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveInt8u": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricSensitiveInt8u"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveInt8u",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fabricSensitiveInt8u"
        }
      ],
      "role": "symbol",
      "title": "fabricSensitiveInt8u",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestfabricscoped/fabricsensitiveint8u"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveInt8uList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricSensitiveInt8uList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveInt8uList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fabricSensitiveInt8uList"
        }
      ],
      "role": "symbol",
      "title": "fabricSensitiveInt8uList",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestfabricscoped/fabricsensitiveint8ulist"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveStruct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricSensitiveStruct"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRUnitTestingClusterSimpleStruct",
          "text": "MTRUnitTestingClusterSimpleStruct"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fabricSensitiveStruct"
        }
      ],
      "role": "symbol",
      "title": "fabricSensitiveStruct",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestfabricscoped/fabricsensitivestruct"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/nullableFabricSensitiveInt8u": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableFabricSensitiveInt8u"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/nullableFabricSensitiveInt8u",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableFabricSensitiveInt8u"
        }
      ],
      "role": "symbol",
      "title": "nullableFabricSensitiveInt8u",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestfabricscoped/nullablefabricsensitiveint8u"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/nullableOptionalFabricSensitiveInt8u": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullableOptionalFabricSensitiveInt8u"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/nullableOptionalFabricSensitiveInt8u",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nullableOptionalFabricSensitiveInt8u"
        }
      ],
      "role": "symbol",
      "title": "nullableOptionalFabricSensitiveInt8u",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestfabricscoped/nullableoptionalfabricsensitiveint8u"
    },
    "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/optionalFabricSensitiveInt8u": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalFabricSensitiveInt8u"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/optionalFabricSensitiveInt8u",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalFabricSensitiveInt8u"
        }
      ],
      "role": "symbol",
      "title": "optionalFabricSensitiveInt8u",
      "type": "topic",
      "url": "/documentation/matter/mtrunittestingclustertestfabricscoped/optionalfabricsensitiveint8u"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterTestFabricScoped"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricIndex",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveCharString",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveInt8u",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveInt8uList",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveStruct",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/nullableFabricSensitiveInt8u",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/nullableOptionalFabricSensitiveInt8u",
        "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/optionalFabricSensitiveInt8u"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRUnitTestingClusterTestFabricScoped"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterTestFabricScoped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterTestFabricScoped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricIndex",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveCharString",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveInt8u",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveInt8uList",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/fabricSensitiveStruct",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/nullableFabricSensitiveInt8u",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/nullableOptionalFabricSensitiveInt8u",
                "doc://com.apple.matter/documentation/Matter/MTRUnitTestingClusterTestFabricScoped/optionalFabricSensitiveInt8u"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRTestClusterClusterTestFabricScoped"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRUnitTestingClusterTestFabricScoped"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterTestFabricScoped/title",
          "value": "MTRTestClusterClusterTestFabricScoped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterTestFabricScoped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTestClusterClusterTestFabricScoped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRTestClusterClusterTestFabricScoped/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRTestClusterClusterTestFabricScoped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1fabricSensitiveInt8u/title",
          "value": "fabricSensitiveInt8u"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1fabricSensitiveInt8u/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fabricSensitiveInt8u"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped/title",
          "value": "MTRUnitTestingClusterTestFabricScoped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterTestFabricScoped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRUnitTestingClusterTestFabricScoped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1fabricSensitiveStruct/title",
          "value": "fabricSensitiveStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1fabricSensitiveStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fabricSensitiveStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1fabricSensitiveInt8uList/title",
          "value": "fabricSensitiveInt8uList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1fabricSensitiveInt8uList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fabricSensitiveInt8uList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1optionalFabricSensitiveInt8u/title",
          "value": "optionalFabricSensitiveInt8u"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1optionalFabricSensitiveInt8u/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionalFabricSensitiveInt8u"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1fabricIndex/title",
          "value": "fabricIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1fabricIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fabricIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1nullableOptionalFabricSensitiveInt8u/title",
          "value": "nullableOptionalFabricSensitiveInt8u"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1nullableOptionalFabricSensitiveInt8u/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableOptionalFabricSensitiveInt8u"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1fabricSensitiveCharString/title",
          "value": "fabricSensitiveCharString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1fabricSensitiveCharString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fabricSensitiveCharString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1nullableFabricSensitiveInt8u/title",
          "value": "nullableFabricSensitiveInt8u"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRUnitTestingClusterTestFabricScoped~1nullableFabricSensitiveInt8u/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nullableFabricSensitiveInt8u"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrunittestingclustertestfabricscoped"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrunittestingclustertestfabricscoped"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
