{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRValveConfigurationAndControlValveFaultBitmap",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRValveConfigurationAndControlValveFaultBitmap"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRValveConfigurationAndControlValveFaultBitmap"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.6",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTRValveConfigurationAndControlValveFaultBitmap"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmap"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRValveConfigurationAndControlValveFaultBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRValveConfigurationAndControlValveFaultBitmap"
        }
      ],
      "role": "symbol",
      "title": "MTRValveConfigurationAndControlValveFaultBitmap",
      "type": "topic",
      "url": "/documentation/matter/mtrvalveconfigurationandcontrolvalvefaultbitmap"
    },
    "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/blocked": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blocked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRValveConfigurationAndControlValveFaultBitmap",
          "text": "MTRValveConfigurationAndControlValveFaultBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/blocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRValveConfigurationAndControlValveFaultBitmapBlocked"
        }
      ],
      "role": "symbol",
      "title": "blocked",
      "type": "topic",
      "url": "/documentation/matter/mtrvalveconfigurationandcontrolvalvefaultbitmap/blocked"
    },
    "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/currentExceeded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentExceeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRValveConfigurationAndControlValveFaultBitmap",
          "text": "MTRValveConfigurationAndControlValveFaultBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/currentExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRValveConfigurationAndControlValveFaultBitmapCurrentExceeded"
        }
      ],
      "role": "symbol",
      "title": "currentExceeded",
      "type": "topic",
      "url": "/documentation/matter/mtrvalveconfigurationandcontrolvalvefaultbitmap/currentexceeded"
    },
    "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/generalFault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generalFault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRValveConfigurationAndControlValveFaultBitmap",
          "text": "MTRValveConfigurationAndControlValveFaultBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/generalFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRValveConfigurationAndControlValveFaultBitmapGeneralFault"
        }
      ],
      "role": "symbol",
      "title": "generalFault",
      "type": "topic",
      "url": "/documentation/matter/mtrvalveconfigurationandcontrolvalvefaultbitmap/generalfault"
    },
    "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrvalveconfigurationandcontrolvalvefaultbitmap/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/leaking": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leaking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRValveConfigurationAndControlValveFaultBitmap",
          "text": "MTRValveConfigurationAndControlValveFaultBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/leaking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRValveConfigurationAndControlValveFaultBitmapLeaking"
        }
      ],
      "role": "symbol",
      "title": "leaking",
      "type": "topic",
      "url": "/documentation/matter/mtrvalveconfigurationandcontrolvalvefaultbitmap/leaking"
    },
    "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/notConnected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRValveConfigurationAndControlValveFaultBitmap",
          "text": "MTRValveConfigurationAndControlValveFaultBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/notConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRValveConfigurationAndControlValveFaultBitmapNotConnected"
        }
      ],
      "role": "symbol",
      "title": "notConnected",
      "type": "topic",
      "url": "/documentation/matter/mtrvalveconfigurationandcontrolvalvefaultbitmap/notconnected"
    },
    "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/shortCircuit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shortCircuit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRValveConfigurationAndControlValveFaultBitmap",
          "text": "MTRValveConfigurationAndControlValveFaultBitmap"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/shortCircuit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRValveConfigurationAndControlValveFaultBitmapShortCircuit"
        }
      ],
      "role": "symbol",
      "title": "shortCircuit",
      "type": "topic",
      "url": "/documentation/matter/mtrvalveconfigurationandcontrolvalvefaultbitmap/shortcircuit"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/blocked",
        "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/currentExceeded",
        "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/generalFault",
        "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/leaking",
        "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/notConnected",
        "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/shortCircuit"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.6",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRValveConfigurationAndControlValveFaultBitmap"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/blocked",
                "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/currentExceeded",
                "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/generalFault",
                "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/leaking",
                "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/notConnected",
                "doc://com.apple.matter/documentation/Matter/MTRValveConfigurationAndControlValveFaultBitmap/shortCircuit"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRValveConfigurationAndControlValveFaultBitmap"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1leaking/title",
          "value": "MTRValveConfigurationAndControlValveFaultBitmapLeaking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1leaking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmapLeaking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1notConnected/title",
          "value": "MTRValveConfigurationAndControlValveFaultBitmapNotConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1notConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmapNotConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1currentExceeded/title",
          "value": "MTRValveConfigurationAndControlValveFaultBitmapCurrentExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1currentExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmapCurrentExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1generalFault/title",
          "value": "MTRValveConfigurationAndControlValveFaultBitmapGeneralFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1generalFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmapGeneralFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1blocked/title",
          "value": "MTRValveConfigurationAndControlValveFaultBitmapBlocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1blocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmapBlocked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap/title",
          "value": "MTRValveConfigurationAndControlValveFaultBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1shortCircuit/title",
          "value": "MTRValveConfigurationAndControlValveFaultBitmapShortCircuit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRValveConfigurationAndControlValveFaultBitmap~1shortCircuit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRValveConfigurationAndControlValveFaultBitmapShortCircuit"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrvalveconfigurationandcontrolvalvefaultbitmap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrvalveconfigurationandcontrolvalvefaultbitmap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
