{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRWindowCoveringEndProductType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRWindowCoveringEndProductType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRWindowCoveringEndProductType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRWindowCoveringEndProductType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductType"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/awningTerracePatio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "awningTerracePatio"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/awningTerracePatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeAwningTerracePatio"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.awningTerracePatio",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/awningterracepatio"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/awningVerticalScreen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "awningVerticalScreen"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/awningVerticalScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeAwningVerticalScreen"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.awningVerticalScreen",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/awningverticalscreen"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/balloonShade": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "balloonShade"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/balloonShade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeBalloonShade"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.balloonShade",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/balloonshade"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/cellularShade": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cellularShade"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/cellularShade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeCellularShade"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.cellularShade",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/cellularshade"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/centralCurtain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centralCurtain"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/centralCurtain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeCentralCurtain"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.centralCurtain",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/centralcurtain"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/exteriorVenetianBlind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exteriorVenetianBlind"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/exteriorVenetianBlind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeExteriorVenetianBlind"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.exteriorVenetianBlind",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/exteriorvenetianblind"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/exteriorVerticalScreen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exteriorVerticalScreen"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/exteriorVerticalScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeExteriorVerticalScreen"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.exteriorVerticalScreen",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/exteriorverticalscreen"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/interiorBlind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interiorBlind"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/interiorBlind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeInteriorBlind"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.interiorBlind",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/interiorblind"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/interiorVenetianBlind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interiorVenetianBlind"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/interiorVenetianBlind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeInteriorVenetianBlind"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.interiorVenetianBlind",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/interiorvenetianblind"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/lateralLeftCurtain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lateralLeftCurtain"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/lateralLeftCurtain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeLateralLeftCurtain"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.lateralLeftCurtain",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/lateralleftcurtain"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/lateralRightCurtain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lateralRightCurtain"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/lateralRightCurtain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeLateralRightCurtain"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.lateralRightCurtain",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/lateralrightcurtain"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/layeredShade": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layeredShade"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/layeredShade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeLayeredShade"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.layeredShade",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/layeredshade"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/layeredShade2D": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layeredShade2D"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/layeredShade2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeLayeredShade2D"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.layeredShade2D",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/layeredshade2d"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/pleatedShade": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pleatedShade"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/pleatedShade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypePleatedShade"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.pleatedShade",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/pleatedshade"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/rollerShade": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollerShade"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/rollerShade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeRollerShade"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.rollerShade",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/rollershade"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/rollerShutter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollerShutter"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/rollerShutter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeRollerShutter"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.rollerShutter",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/rollershutter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/romanShade": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "romanShade"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/romanShade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeRomanShade"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.romanShade",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/romanshade"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/sheerShade": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sheerShade"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/sheerShade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeSheerShade"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.sheerShade",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/sheershade"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/slidingShutter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slidingShutter"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/slidingShutter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeSlidingShutter"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.slidingShutter",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/slidingshutter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/swingingShutter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swingingShutter"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/swingingShutter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeSwingingShutter"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.swingingShutter",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/swingingshutter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/tiltOnlyInteriorBlind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tiltOnlyInteriorBlind"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/tiltOnlyInteriorBlind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeTiltOnlyInteriorBlind"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.tiltOnlyInteriorBlind",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/tiltonlyinteriorblind"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/tiltOnlyPergola": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tiltOnlyPergola"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/tiltOnlyPergola",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeTiltOnlyPergola"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.tiltOnlyPergola",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/tiltonlypergola"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.unknown",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/unknown"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/verticalBlindStripCurtain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalBlindStripCurtain"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/verticalBlindStripCurtain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeVerticalBlindStripCurtain"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.verticalBlindStripCurtain",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/verticalblindstripcurtain"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/wovenWood": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wovenWood"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/wovenWood",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringEndProductTypeWovenWood"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringEndProductType.wovenWood",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringendproducttype/wovenwood"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/awningTerracePatio",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/awningVerticalScreen",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/balloonShade",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/cellularShade",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/centralCurtain",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/exteriorVenetianBlind",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/exteriorVerticalScreen",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/interiorBlind",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/interiorVenetianBlind",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/lateralLeftCurtain",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/lateralRightCurtain",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/layeredShade",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/layeredShade2D",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/pleatedShade",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/rollerShade",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/rollerShutter",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/romanShade",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/sheerShade",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/slidingShutter",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/swingingShutter",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/tiltOnlyInteriorBlind",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/tiltOnlyPergola",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/unknown",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/verticalBlindStripCurtain",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/wovenWood"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRWindowCoveringEndProductType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/awningTerracePatio",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/awningVerticalScreen",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/balloonShade",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/cellularShade",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/centralCurtain",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/exteriorVenetianBlind",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/exteriorVerticalScreen",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/interiorBlind",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/interiorVenetianBlind",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/lateralLeftCurtain",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/lateralRightCurtain",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/layeredShade",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/layeredShade2D",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/pleatedShade",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/rollerShade",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/rollerShutter",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/romanShade",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/sheerShade",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/slidingShutter",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/swingingShutter",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/tiltOnlyInteriorBlind",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/tiltOnlyPergola",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/unknown",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/verticalBlindStripCurtain",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringEndProductType/wovenWood"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRWindowCoveringEndProductType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1slidingShutter/title",
          "value": "MTRWindowCoveringEndProductTypeSlidingShutter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1slidingShutter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeSlidingShutter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1interiorVenetianBlind/title",
          "value": "MTRWindowCoveringEndProductTypeInteriorVenetianBlind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1interiorVenetianBlind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeInteriorVenetianBlind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1layeredShade/title",
          "value": "MTRWindowCoveringEndProductTypeLayeredShade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1layeredShade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeLayeredShade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1awningTerracePatio/title",
          "value": "MTRWindowCoveringEndProductTypeAwningTerracePatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1awningTerracePatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeAwningTerracePatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1cellularShade/title",
          "value": "MTRWindowCoveringEndProductTypeCellularShade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1cellularShade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeCellularShade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1interiorBlind/title",
          "value": "MTRWindowCoveringEndProductTypeInteriorBlind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1interiorBlind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeInteriorBlind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1exteriorVerticalScreen/title",
          "value": "MTRWindowCoveringEndProductTypeExteriorVerticalScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1exteriorVerticalScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeExteriorVerticalScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1rollerShutter/title",
          "value": "MTRWindowCoveringEndProductTypeRollerShutter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1rollerShutter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeRollerShutter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1tiltOnlyPergola/title",
          "value": "MTRWindowCoveringEndProductTypeTiltOnlyPergola"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1tiltOnlyPergola/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeTiltOnlyPergola"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1romanShade/title",
          "value": "MTRWindowCoveringEndProductTypeRomanShade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1romanShade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeRomanShade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1lateralLeftCurtain/title",
          "value": "MTRWindowCoveringEndProductTypeLateralLeftCurtain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1lateralLeftCurtain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeLateralLeftCurtain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1swingingShutter/title",
          "value": "MTRWindowCoveringEndProductTypeSwingingShutter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1swingingShutter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeSwingingShutter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1unknown/title",
          "value": "MTRWindowCoveringEndProductTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1centralCurtain/title",
          "value": "MTRWindowCoveringEndProductTypeCentralCurtain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1centralCurtain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeCentralCurtain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1awningVerticalScreen/title",
          "value": "MTRWindowCoveringEndProductTypeAwningVerticalScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1awningVerticalScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeAwningVerticalScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1pleatedShade/title",
          "value": "MTRWindowCoveringEndProductTypePleatedShade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1pleatedShade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypePleatedShade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType/title",
          "value": "MTRWindowCoveringEndProductType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1rollerShade/title",
          "value": "MTRWindowCoveringEndProductTypeRollerShade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1rollerShade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeRollerShade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1verticalBlindStripCurtain/title",
          "value": "MTRWindowCoveringEndProductTypeVerticalBlindStripCurtain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1verticalBlindStripCurtain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeVerticalBlindStripCurtain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1balloonShade/title",
          "value": "MTRWindowCoveringEndProductTypeBalloonShade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1balloonShade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeBalloonShade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1layeredShade2D/title",
          "value": "MTRWindowCoveringEndProductTypeLayeredShade2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1layeredShade2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeLayeredShade2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1wovenWood/title",
          "value": "MTRWindowCoveringEndProductTypeWovenWood"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1wovenWood/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeWovenWood"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1tiltOnlyInteriorBlind/title",
          "value": "MTRWindowCoveringEndProductTypeTiltOnlyInteriorBlind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1tiltOnlyInteriorBlind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeTiltOnlyInteriorBlind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1exteriorVenetianBlind/title",
          "value": "MTRWindowCoveringEndProductTypeExteriorVenetianBlind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1exteriorVenetianBlind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeExteriorVenetianBlind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1lateralRightCurtain/title",
          "value": "MTRWindowCoveringEndProductTypeLateralRightCurtain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1lateralRightCurtain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeLateralRightCurtain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1sheerShade/title",
          "value": "MTRWindowCoveringEndProductTypeSheerShade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringEndProductType~1sheerShade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringEndProductTypeSheerShade"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrwindowcoveringendproducttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrwindowcoveringendproducttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
