{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRWiFiNetworkDiagnosticsWiFiVersion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRWiFiNetworkDiagnosticsWiFiVersion"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRWiFiNetworkDiagnosticsWiFiVersion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.5",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRWiFiNetworkDiagnosticsWiFiVersion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersion"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersion"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersion"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersion",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversion"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/a": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "a"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionA"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersion.a",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversion/a"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ac": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ac"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionAc"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersion.ac",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversion/ac"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ah": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ah"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ah",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionAh"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersion.ah",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversion/ah"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ax"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionAx"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersion.ax",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversion/ax"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/b": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "b"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionB"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersion.b",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversion/b"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/g": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "g"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionG"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersion.g",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversion/g"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversion/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/n": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "n"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionN"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersion.n",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversion/n"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/a",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ac",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ah",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ax",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/b",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/g",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/n"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.5",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.5",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/a",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ac",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ah",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/ax",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/b",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/g",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersion/n"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRWiFiNetworkDiagnosticsWiFiVersion"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1b/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1b/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1g/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1ax/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionAx"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1ax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionAx"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1ah/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionAh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1ah/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionAh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1a/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1a/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1ac/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionAc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1ac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionAc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1n/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersion~1n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrwifinetworkdiagnosticswifiversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrwifinetworkdiagnosticswifiversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
