{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRWiFiNetworkDiagnosticsSecurityType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRWiFiNetworkDiagnosticsSecurityType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRWiFiNetworkDiagnosticsSecurityType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRWiFiNetworkDiagnosticsSecurityType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsSecurityType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsSecurityType"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsSecurityType",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticssecuritytype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WEP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WEP"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsSecurityTypeWEP"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsSecurityType.WEP",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticssecuritytype/wep"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WPA"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsSecurityTypeWPA"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsSecurityType.WPA",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticssecuritytype/wpa"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WPA2"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsSecurityTypeWPA2"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsSecurityType.WPA2",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticssecuritytype/wpa2"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WPA3"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsSecurityTypeWPA3"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsSecurityType.WPA3",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticssecuritytype/wpa3"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticssecuritytype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsSecurityTypeNone"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsSecurityType.none",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticssecuritytype/none"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsSecurityTypeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsSecurityType.unspecified",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticssecuritytype/unspecified"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WEP",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA2",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA3",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/none",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/unspecified"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRWiFiNetworkDiagnosticsSecurityType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WEP",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA2",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/WPA3",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/none",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsSecurityType/unspecified"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRWiFiNetworkDiagnosticsSecurityType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1WEP/title",
          "value": "MTRWiFiNetworkDiagnosticsSecurityTypeWEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1WEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityTypeWEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType/title",
          "value": "MTRWiFiNetworkDiagnosticsSecurityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1unspecified/title",
          "value": "MTRWiFiNetworkDiagnosticsSecurityTypeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityTypeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1WPA/title",
          "value": "MTRWiFiNetworkDiagnosticsSecurityTypeWPA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1WPA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityTypeWPA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1WPA3/title",
          "value": "MTRWiFiNetworkDiagnosticsSecurityTypeWPA3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1WPA3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityTypeWPA3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1WPA2/title",
          "value": "MTRWiFiNetworkDiagnosticsSecurityTypeWPA2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1WPA2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityTypeWPA2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1none/title",
          "value": "MTRWiFiNetworkDiagnosticsSecurityTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsSecurityType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsSecurityTypeNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrwifinetworkdiagnosticssecuritytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrwifinetworkdiagnosticssecuritytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
