{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRWindowCoveringSafetyStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRWindowCoveringSafetyStatus"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRWindowCoveringSafetyStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTRWindowCoveringSafetyStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringSafetyStatus",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/failedCommunication": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedCommunication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/failedCommunication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusFailedCommunication"
        }
      ],
      "role": "symbol",
      "title": "failedCommunication",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/failedcommunication"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/hardwareFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardwareFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/hardwareFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusHardwareFailure"
        }
      ],
      "role": "symbol",
      "title": "hardwareFailure",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/hardwarefailure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/manualOperation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manualOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/manualOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusManualOperation"
        }
      ],
      "role": "symbol",
      "title": "manualOperation",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/manualoperation"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/motorJammed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motorJammed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/motorJammed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusMotorJammed"
        }
      ],
      "role": "symbol",
      "title": "motorJammed",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/motorjammed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/obstacleDetected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "obstacleDetected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/obstacleDetected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusObstacleDetected"
        }
      ],
      "role": "symbol",
      "title": "obstacleDetected",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/obstacledetected"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/positionFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "positionFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/positionFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusPositionFailure"
        }
      ],
      "role": "symbol",
      "title": "positionFailure",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/positionfailure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/power": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "power"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/power",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusPower"
        }
      ],
      "role": "symbol",
      "title": "power",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/power"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/protection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "protection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/protection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusProtection"
        }
      ],
      "role": "symbol",
      "title": "protection",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/protection"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/remoteLockout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteLockout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/remoteLockout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusRemoteLockout"
        }
      ],
      "role": "symbol",
      "title": "remoteLockout",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/remotelockout"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/stopInput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/stopInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusStopInput"
        }
      ],
      "role": "symbol",
      "title": "stopInput",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/stopinput"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/tamperDetection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tamperDetection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/tamperDetection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusTamperDetection"
        }
      ],
      "role": "symbol",
      "title": "tamperDetection",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/tamperdetection"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/thermalProtection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thermalProtection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWindowCoveringSafetyStatus",
          "text": "MTRWindowCoveringSafetyStatus"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/thermalProtection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringSafetyStatusThermalProtection"
        }
      ],
      "role": "symbol",
      "title": "thermalProtection",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringsafetystatus/thermalprotection"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/failedCommunication",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/hardwareFailure",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/manualOperation",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/motorJammed",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/obstacleDetected",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/positionFailure",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/power",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/protection",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/remoteLockout",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/stopInput",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/tamperDetection",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/thermalProtection"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRWindowCoveringSafetyStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/failedCommunication",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/hardwareFailure",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/manualOperation",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/motorJammed",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/obstacleDetected",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/positionFailure",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/power",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/protection",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/remoteLockout",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/stopInput",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/tamperDetection",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringSafetyStatus/thermalProtection"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRWindowCoveringSafetyStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1manualOperation/title",
          "value": "MTRWindowCoveringSafetyStatusManualOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1manualOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusManualOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus/title",
          "value": "MTRWindowCoveringSafetyStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1obstacleDetected/title",
          "value": "MTRWindowCoveringSafetyStatusObstacleDetected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1obstacleDetected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusObstacleDetected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1tamperDetection/title",
          "value": "MTRWindowCoveringSafetyStatusTamperDetection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1tamperDetection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusTamperDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1stopInput/title",
          "value": "MTRWindowCoveringSafetyStatusStopInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1stopInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusStopInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1remoteLockout/title",
          "value": "MTRWindowCoveringSafetyStatusRemoteLockout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1remoteLockout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusRemoteLockout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1motorJammed/title",
          "value": "MTRWindowCoveringSafetyStatusMotorJammed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1motorJammed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusMotorJammed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1thermalProtection/title",
          "value": "MTRWindowCoveringSafetyStatusThermalProtection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1thermalProtection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusThermalProtection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1hardwareFailure/title",
          "value": "MTRWindowCoveringSafetyStatusHardwareFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1hardwareFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusHardwareFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1power/title",
          "value": "MTRWindowCoveringSafetyStatusPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1power/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1positionFailure/title",
          "value": "MTRWindowCoveringSafetyStatusPositionFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1positionFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusPositionFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1protection/title",
          "value": "MTRWindowCoveringSafetyStatusProtection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1protection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusProtection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1failedCommunication/title",
          "value": "MTRWindowCoveringSafetyStatusFailedCommunication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringSafetyStatus~1failedCommunication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringSafetyStatusFailedCommunication"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrwindowcoveringsafetystatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrwindowcoveringsafetystatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
