{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use MTRWiFiNetworkDiagnosticsWiFiVersion",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRWiFiNetworkDiagnosticsWiFiVersionType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.5",
        "introducedAt": "16.1",
        "message": "Please use MTRWiFiNetworkDiagnosticsWiFiVersion",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.5",
        "introducedAt": "16.1",
        "message": "Please use MTRWiFiNetworkDiagnosticsWiFiVersion",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.5",
        "introducedAt": "16.1",
        "message": "Please use MTRWiFiNetworkDiagnosticsWiFiVersion",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.4",
        "introducedAt": "13.0",
        "message": "Please use MTRWiFiNetworkDiagnosticsWiFiVersion",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.5",
        "introducedAt": "16.1",
        "message": "Please use MTRWiFiNetworkDiagnosticsWiFiVersion",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use MTRWiFiNetworkDiagnosticsWiFiVersion",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.5",
        "introducedAt": "9.1",
        "message": "Please use MTRWiFiNetworkDiagnosticsWiFiVersion",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersionType",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/A": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "A"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/A",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeA"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersionType.A",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/a"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/B": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "B"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/B",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeB"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersionType.B",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/b"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/G": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "G"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeG"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersionType.G",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/g"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/N": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "N"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/N",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeN"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersionType.N",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/n"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/ac": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ac"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/ac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeAc"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersionType.ac",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/ac"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/ax": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ax"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/ax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeAx"
        }
      ],
      "role": "symbol",
      "title": "MTRWiFiNetworkDiagnosticsWiFiVersionType.ax",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/ax"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211a": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type80211a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWiFiNetworkDiagnosticsWiFiVersionType",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211a"
        }
      ],
      "role": "symbol",
      "title": "type80211a",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/type80211a"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211ac": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type80211ac"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWiFiNetworkDiagnosticsWiFiVersionType",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211ac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211ac"
        }
      ],
      "role": "symbol",
      "title": "type80211ac",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/type80211ac"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211ax": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type80211ax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWiFiNetworkDiagnosticsWiFiVersionType",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211ax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211ax"
        }
      ],
      "role": "symbol",
      "title": "type80211ax",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/type80211ax"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211b": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type80211b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWiFiNetworkDiagnosticsWiFiVersionType",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211b"
        }
      ],
      "role": "symbol",
      "title": "type80211b",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/type80211b"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211g": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type80211g"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWiFiNetworkDiagnosticsWiFiVersionType",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211g"
        }
      ],
      "role": "symbol",
      "title": "type80211g",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/type80211g"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211n": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type80211n"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRWiFiNetworkDiagnosticsWiFiVersionType",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211n"
        }
      ],
      "role": "symbol",
      "title": "type80211n",
      "type": "topic",
      "url": "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype/type80211n"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/A",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/B",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/G",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/N",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/ac",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/ax"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211a",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211ac",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211ax",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211b",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211g",
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211n"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.5",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.5",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.5",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.4",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.5",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.5",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/A",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/B",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/G",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/N",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/ac",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/ax"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211a",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211ac",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211ax",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211b",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211g",
                "doc://com.apple.matter/documentation/Matter/MTRWiFiNetworkDiagnosticsWiFiVersionType/type80211n"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use MTRWiFiNetworkDiagnosticsWiFiVersion",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211ax/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211ax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211ax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211ax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1B/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1B/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211ac/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211ac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211ac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211ac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1N/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1N/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1A/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1A/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211g/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211g"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211g"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1ax/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeAx"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1ax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeAx"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211b/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211b"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211b/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211b"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1G/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1ac/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeAc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1ac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionTypeAc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211a/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211a"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211a/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211a"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211n/title",
          "value": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211n"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWiFiNetworkDiagnosticsWiFiVersionType~1type80211n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWiFiNetworkDiagnosticsWiFiVersionType80211n"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrwifinetworkdiagnosticswifiversiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
