{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRWindowCoveringType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRWindowCoveringType"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRWindowCoveringType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRWindowCoveringType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringType"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/awning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "awning"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/awning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeAwning"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.awning",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/awning"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/drapery": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drapery"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/drapery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeDrapery"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.drapery",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/drapery"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/projectorScreen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectorScreen"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/projectorScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeProjectorScreen"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.projectorScreen",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/projectorscreen"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShade": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollerShade"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeRollerShade"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.rollerShade",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/rollershade"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShade2Motor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollerShade2Motor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShade2Motor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeRollerShade2Motor"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.rollerShade2Motor",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/rollershade2motor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShadeExterior": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollerShadeExterior"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShadeExterior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeRollerShadeExterior"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.rollerShadeExterior",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/rollershadeexterior"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShadeExterior2Motor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollerShadeExterior2Motor"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShadeExterior2Motor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeRollerShadeExterior2Motor"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.rollerShadeExterior2Motor",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/rollershadeexterior2motor"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/shutter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shutter"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/shutter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeShutter"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.shutter",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/shutter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/tiltBlindLiftAndTilt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tiltBlindLiftAndTilt"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/tiltBlindLiftAndTilt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeTiltBlindLiftAndTilt"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.tiltBlindLiftAndTilt",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/tiltblindliftandtilt"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/tiltBlindTiltOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tiltBlindTiltOnly"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/tiltBlindTiltOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeTiltBlindTiltOnly"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.tiltBlindTiltOnly",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/tiltblindtiltonly"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWindowCoveringTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "MTRWindowCoveringType.unknown",
      "type": "topic",
      "url": "/documentation/matter/mtrwindowcoveringtype/unknown"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/awning",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/drapery",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/projectorScreen",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShade",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShade2Motor",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShadeExterior",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShadeExterior2Motor",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/shutter",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/tiltBlindLiftAndTilt",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/tiltBlindTiltOnly",
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/unknown"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRWindowCoveringType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/awning",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/drapery",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/projectorScreen",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShade",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShade2Motor",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShadeExterior",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/rollerShadeExterior2Motor",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/shutter",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/tiltBlindLiftAndTilt",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/tiltBlindTiltOnly",
                "doc://com.apple.matter/documentation/Matter/MTRWindowCoveringType/unknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRWindowCoveringType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1drapery/title",
          "value": "MTRWindowCoveringTypeDrapery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1drapery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeDrapery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType/title",
          "value": "MTRWindowCoveringType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1rollerShadeExterior/title",
          "value": "MTRWindowCoveringTypeRollerShadeExterior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1rollerShadeExterior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeRollerShadeExterior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1unknown/title",
          "value": "MTRWindowCoveringTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1projectorScreen/title",
          "value": "MTRWindowCoveringTypeProjectorScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1projectorScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeProjectorScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1tiltBlindTiltOnly/title",
          "value": "MTRWindowCoveringTypeTiltBlindTiltOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1tiltBlindTiltOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeTiltBlindTiltOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1rollerShadeExterior2Motor/title",
          "value": "MTRWindowCoveringTypeRollerShadeExterior2Motor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1rollerShadeExterior2Motor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeRollerShadeExterior2Motor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1tiltBlindLiftAndTilt/title",
          "value": "MTRWindowCoveringTypeTiltBlindLiftAndTilt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1tiltBlindLiftAndTilt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeTiltBlindLiftAndTilt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1rollerShade/title",
          "value": "MTRWindowCoveringTypeRollerShade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1rollerShade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeRollerShade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1awning/title",
          "value": "MTRWindowCoveringTypeAwning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1awning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeAwning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1shutter/title",
          "value": "MTRWindowCoveringTypeShutter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1shutter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeShutter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1rollerShade2Motor/title",
          "value": "MTRWindowCoveringTypeRollerShade2Motor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWindowCoveringType~1rollerShade2Motor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWindowCoveringTypeRollerShade2Motor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrwindowcoveringtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrwindowcoveringtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
