{
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRWaterHeaterModeModeTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRWaterHeaterModeModeTag"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRWaterHeaterModeModeTag"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRWaterHeaterModeModeTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTag"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTag"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/auto": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagAuto"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.auto",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/auto"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/day": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "day"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/day",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagDay"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.day",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/day"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/lowEnergy": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowEnergy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/lowEnergy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagLowEnergy"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.lowEnergy",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/lowenergy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/lowNoise": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowNoise"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/lowNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagLowNoise"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.lowNoise",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/lownoise"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/manual": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manual"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/manual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagManual"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.manual",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/manual"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/max": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagMax"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.max",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/max"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/min": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagMin"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.min",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/min"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/night": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "night"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/night",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagNight"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.night",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/night"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/off": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "off"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/off",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagOff"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.off",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/off"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/quick": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quick"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/quick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagQuick"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.quick",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/quick"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/quiet": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quiet"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/quiet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagQuiet"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.quiet",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/quiet"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/timed": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timed"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/timed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagTimed"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.timed",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/timed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/vacation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vacation"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/vacation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWaterHeaterModeModeTagVacation"
        }
      ],
      "role": "symbol",
      "title": "MTRWaterHeaterModeModeTag.vacation",
      "type": "topic",
      "url": "/documentation/matter/mtrwaterheatermodemodetag/vacation"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/auto",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/day",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/lowEnergy",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/lowNoise",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/manual",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/max",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/min",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/night",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/off",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/quick",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/quiet",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/timed",
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/vacation"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRWaterHeaterModeModeTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/auto",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/day",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/lowEnergy",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/lowNoise",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/manual",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/max",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/min",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/night",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/off",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/quick",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/quiet",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/timed",
                "doc://com.apple.matter/documentation/Matter/MTRWaterHeaterModeModeTag/vacation"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRWaterHeaterModeModeTag"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1lowEnergy/title",
          "value": "MTRWaterHeaterModeModeTagLowEnergy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1lowEnergy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagLowEnergy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1vacation/title",
          "value": "MTRWaterHeaterModeModeTagVacation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1vacation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagVacation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1max/title",
          "value": "MTRWaterHeaterModeModeTagMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1night/title",
          "value": "MTRWaterHeaterModeModeTagNight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1night/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagNight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1off/title",
          "value": "MTRWaterHeaterModeModeTagOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1off/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1min/title",
          "value": "MTRWaterHeaterModeModeTagMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag/title",
          "value": "MTRWaterHeaterModeModeTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1timed/title",
          "value": "MTRWaterHeaterModeModeTagTimed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1timed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagTimed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1auto/title",
          "value": "MTRWaterHeaterModeModeTagAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1day/title",
          "value": "MTRWaterHeaterModeModeTagDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1day/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1quiet/title",
          "value": "MTRWaterHeaterModeModeTagQuiet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1quiet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagQuiet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1quick/title",
          "value": "MTRWaterHeaterModeModeTagQuick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1quick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagQuick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1lowNoise/title",
          "value": "MTRWaterHeaterModeModeTagLowNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1lowNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagLowNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1manual/title",
          "value": "MTRWaterHeaterModeModeTagManual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWaterHeaterModeModeTag~1manual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWaterHeaterModeModeTagManual"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrwaterheatermodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrwaterheatermodemodetag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
