{"abstract":[{"text":"The earliest date for which to return results.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"earliestBookingDateForResults","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DateV","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]},{"content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"When building the list of reservation time slots, do not include time slots that occur before the date specified by this property."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/earliestBookingDateForResults","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"earliestBookingDateForResults","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"Intents"}],"platforms":[{"introducedAt":"10.0","name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"10.0","name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false,"beta":false}],"navigatorTitle":[{"text":"earliestBookingDateForResults","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)INGetAvailableRestaurantReservationBookingsIntent(py)earliestBookingDateForResults","title":"earliestBookingDateForResults"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/intents/ingetavailablerestaurantreservationbookingsintent/earliestbookingdateforresults"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/intents/ingetavailablerestaurantreservationbookingsintent/earliestbookingdateforresults"]}],"seeAlsoSections":[{"title":"Getting the Time Slot Constraints","identifiers":["doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/latestBookingDateForResults","doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/maximumNumberOfResults"],"anchor":"Getting-the-Time-Slot-Constraints","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sirikit/documentation/Intents","doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSDate":{"url":"/documentation/foundation/nsdate","title":"NSDate","fragments":[{"text":"class ","kind":"text"},{"text":"NSDate","kind":"identifier"}],"abstract":[{"type":"text","text":"A representation of a specific point in time, for use when you need reference semantics or other Foundation-specific behavior."}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSDate","kind":"symbol","role":"symbol"},"doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent":{"kind":"symbol","title":"INGetAvailableRestaurantReservationBookingsIntent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGetAvailableRestaurantReservationBookingsIntent"}],"abstract":[{"type":"text","text":"A request for the time slots available for making a reservation."}],"navigatorTitle":[{"kind":"identifier","text":"INGetAvailableRestaurantReservationBookingsIntent"}],"url":"/documentation/intents/ingetavailablerestaurantreservationbookingsintent","identifier":"doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/s:10Foundation4DateV":{"type":"topic","url":"/documentation/foundation/date","title":"Date","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DateV","role":"symbol","fragments":[{"text":"struct ","kind":"text"},{"kind":"identifier","text":"Date"}],"abstract":[{"type":"text","text":"A specific point in time, independent of any calendar or time zone."}],"kind":"symbol"},"doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/maximumNumberOfResults":{"url":"/documentation/intents/ingetavailablerestaurantreservationbookingsintent/maximumnumberofresults","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/maximumNumberOfResults","title":"maximumNumberOfResults","navigatorTitle":[{"text":"maximumNumberOfResults","kind":"identifier"}],"abstract":[{"text":"The maximum number of reservation results to return.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/earliestBookingDateForResults":{"kind":"symbol","title":"earliestBookingDateForResults","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"earliestBookingDateForResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/earliestBookingDateForResults","type":"topic","url":"/documentation/intents/ingetavailablerestaurantreservationbookingsintent/earliestbookingdateforresults","abstract":[{"type":"text","text":"The earliest date for which to return results."}],"navigatorTitle":[{"kind":"identifier","text":"earliestBookingDateForResults"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/latestBookingDateForResults":{"kind":"symbol","title":"latestBookingDateForResults","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestBookingDateForResults"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/latestBookingDateForResults","type":"topic","url":"/documentation/intents/ingetavailablerestaurantreservationbookingsintent/latestbookingdateforresults","abstract":[{"text":"The latest date for which to return results.","type":"text"}],"navigatorTitle":[{"text":"latestBookingDateForResults","kind":"identifier"}],"role":"symbol"},"doc://com.apple.sirikit/documentation/Intents":{"role":"collection","identifier":"doc://com.apple.sirikit/documentation/Intents","url":"/documentation/intents","type":"topic","title":"Intents","abstract":[{"type":"text","text":"Empower people to customize interactions for your app on their device."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"10.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"10.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false}]},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"earliestBookingDateForResults","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"earliestBookingDateForResults","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sirikit/documentation/Intents","doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/latestBookingDateForResults","doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingsIntent/maximumNumberOfResults"],"anchor":"Getting-the-Time-Slot-Constraints","title":"Getting the Time Slot Constraints"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSDate","preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"earliestBookingDateForResults"},{"kind":"text","text":";"}],"languages":["occ"]},{"platforms":["macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"atomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"earliestBookingDateForResults","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSDate/abstract","value":[{"type":"text","text":"A representation of a specific point in time, independent of any calendar or time zone."}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingsIntent/title","value":"INGetAvailableRestaurantReservationBookingsIntent","op":"replace"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingsIntent/fragments","value":[{"kind":"identifier","text":"INGetAvailableRestaurantReservationBookingsIntent"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingsIntent/navigatorTitle","value":[{"text":"INGetAvailableRestaurantReservationBookingsIntent","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingsIntent~1maximumNumberOfResults/title","value":"maximumNumberOfResults","op":"replace"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingsIntent~1maximumNumberOfResults/fragments","value":[{"kind":"identifier","text":"maximumNumberOfResults"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingsIntent~1earliestBookingDateForResults/title","value":"earliestBookingDateForResults","op":"replace"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingsIntent~1earliestBookingDateForResults/fragments","value":[{"text":"earliestBookingDateForResults","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingsIntent~1latestBookingDateForResults/title","value":"latestBookingDateForResults","op":"replace"},{"value":[{"kind":"identifier","text":"latestBookingDateForResults"}],"op":"replace","path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingsIntent~1latestBookingDateForResults/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}