{
  "abstract": [
    {
      "text": "A behavior that adds the new scene to the requesting scene’s collection and activate it, or attempts to join a compatible collection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/preferred"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UISceneCollectionJoinBehavior@UISceneCollectionJoinBehaviorPreferred",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "preferred"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISceneCollectionJoinBehaviorPreferred"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UISceneCollectionJoinBehavior.preferred"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "preferred"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions/requestingScene",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is set, this behavior adds the new scene to its collection and activates it. Otherwise, the scene attempts to join a compatible collection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions/requestingScene": {
      "abstract": [
        {
          "text": "The scene object that requested the activation of a different scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestingScene"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions/requestingScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestingScene"
        }
      ],
      "role": "symbol",
      "title": "requestingScene",
      "type": "topic",
      "url": "/documentation/uikit/uiscene/activationrequestoptions/requestingscene"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior": {
      "abstract": [
        {
          "text": "A set of behaviors that specify how a new scene joins a scene collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISceneCollectionJoinBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneCollectionJoinBehavior"
        }
      ],
      "role": "symbol",
      "title": "UISceneCollectionJoinBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uiscenecollectionjoinbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/automatic": {
      "abstract": [
        {
          "text": "A behavior that uses the system preferences for joining collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneCollectionJoinBehaviorAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UISceneCollectionJoinBehavior.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uiscenecollectionjoinbehavior/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/disallowed": {
      "abstract": [
        {
          "text": "A behavior that creates a new collection for the new scene, ignoring system preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disallowed"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/disallowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneCollectionJoinBehaviorDisallowed"
        }
      ],
      "role": "symbol",
      "title": "UISceneCollectionJoinBehavior.disallowed",
      "type": "topic",
      "url": "/documentation/uikit/uiscenecollectionjoinbehavior/disallowed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/preferred": {
      "abstract": [
        {
          "text": "A behavior that adds the new scene to the requesting scene’s collection and activate it, or attempts to join a compatible collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferred"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/preferred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneCollectionJoinBehaviorPreferred"
        }
      ],
      "role": "symbol",
      "title": "UISceneCollectionJoinBehavior.preferred",
      "type": "topic",
      "url": "/documentation/uikit/uiscenecollectionjoinbehavior/preferred"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/preferredWithoutActivating": {
      "abstract": [
        {
          "text": "A behavior that adds the new scene to the requesting scene’s collection without activating it, or attempts to join a compatible collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredWithoutActivating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/preferredWithoutActivating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneCollectionJoinBehaviorPreferredWithoutActivating"
        }
      ],
      "role": "symbol",
      "title": "UISceneCollectionJoinBehavior.preferredWithoutActivating",
      "type": "topic",
      "url": "/documentation/uikit/uiscenecollectionjoinbehavior/preferredwithoutactivating"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/preferredWithoutActivating",
        "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/disallowed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISceneCollectionJoinBehaviorPreferred"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneCollectionJoinBehaviorPreferred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/preferredWithoutActivating",
                "doc://com.apple.uikit/documentation/UIKit/UISceneCollectionJoinBehavior/disallowed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UISceneCollectionJoinBehaviorPreferred"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior/title",
          "value": "UISceneCollectionJoinBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneCollectionJoinBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneCollectionJoinBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior~1disallowed/title",
          "value": "UISceneCollectionJoinBehaviorDisallowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior~1disallowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneCollectionJoinBehaviorDisallowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior~1automatic/title",
          "value": "UISceneCollectionJoinBehaviorAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneCollectionJoinBehaviorAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions~1requestingScene/title",
          "value": "requestingScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions~1requestingScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestingScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior~1preferred/title",
          "value": "UISceneCollectionJoinBehaviorPreferred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior~1preferred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneCollectionJoinBehaviorPreferred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior~1preferredWithoutActivating/title",
          "value": "UISceneCollectionJoinBehaviorPreferredWithoutActivating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneCollectionJoinBehavior~1preferredWithoutActivating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneCollectionJoinBehaviorPreferredWithoutActivating"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiscenecollectionjoinbehavior/preferred"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiscenecollectionjoinbehavior/preferred"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
