{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cinematic/documentation/Cinematic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Cinematic Constants"
  },
  "references": {
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCinematicErrorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNCinematicErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCinematicErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNCinematicErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CNCinematicErrorDomain",
      "type": "topic",
      "url": "/documentation/cinematic/cncinematicerrordomain"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cinematic Data Types",
      "type": "topic",
      "url": "/documentation/cinematic/cinematic-data-types"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cinematic Enumerations",
      "type": "topic",
      "url": "/documentation/cinematic/cinematic-enumerations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-enumerations",
        "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNCinematicErrorDomain"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/CNCinematicErrorDomain"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-enumerations",
                "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNCinematicErrorDomain/title",
          "value": "CNCinematicErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNCinematicErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNCinematicErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic/cinematic-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cinematic/cinematic-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
