{
  "abstract": [
    {
      "text": "A structure that represents a detected subject, face, torso or pet at a particular time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cinematic/documentation/Cinematic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNDetection",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CNDetection"
      }
    ],
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNDetection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CNDetection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNDetection"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Specifies the type, distance bounds, and time of the detection. Detections obtained from the Cinematic script include a unique number that can tracks the detection over time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Some types of detections also include a unique group number that associates related detections (for example, the face and torso of the same person).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc": {
      "abstract": [
        {
          "text": "An object representing a discrete detection track composed of individual detections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNCustomDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cncustomdetectiontrack-891hc"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class": {
      "abstract": [
        {
          "text": "An object that represents a decision to focus on a particular detection, or group of detections, at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDecision",
      "type": "topic",
      "url": "/documentation/cinematic/cndecision-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class": {
      "abstract": [
        {
          "text": "A structure that represents a detected subject, face, torso or pet at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/accessibilityLabelForDetectionType:": {
      "abstract": [
        {
          "text": "A localized accessibility label converting a specific detection type into a broad category such as a person, pet, and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLabelForDetectionType:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/accessibilityLabelForDetectionType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityLabelForDetectionType:"
        }
      ],
      "role": "symbol",
      "title": "accessibilityLabelForDetectionType:",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/accessibilitylabelfordetectiontype:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionGroupID": {
      "abstract": [
        {
          "text": "A unique number representing the detection to focus on if this is a group decision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "detectionGroupID"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionGroupID",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectionGroupID",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/detectiongroupid"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionID": {
      "abstract": [
        {
          "text": "An unique identifier assigned by the Cinematic script to all detections of the same subject and detection type across time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "detectionID"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionID",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectionID",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/detectionid"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionType": {
      "abstract": [
        {
          "text": "The type of object detected, such as the face, torso, cat, dog, and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "detectionType"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionType",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectionType",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/detectiontype"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/disparityInNormalizedRect:sourceDisparity:detectionType:priorDisparity:": {
      "abstract": [
        {
          "text": "Determines the disparity to use to focus on the object in the rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "disparityInNormalizedRect:sourceDisparity:detectionType:priorDisparity:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/disparityInNormalizedRect:sourceDisparity:detectionType:priorDisparity:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disparityInNormalizedRect:sourceDisparity:detectionType:priorDisparity:"
        }
      ],
      "role": "symbol",
      "title": "disparityInNormalizedRect:sourceDisparity:detectionType:priorDisparity:",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/disparityinnormalizedrect:sourcedisparity:detectiontype:priordisparity:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/focusDisparity": {
      "abstract": [
        {
          "text": "The disparity to use in order to focus on the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "focusDisparity"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/focusDisparity",
      "kind": "symbol",
      "role": "symbol",
      "title": "focusDisparity",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/focusdisparity"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/initWithTime:detectionType:normalizedRect:focusDisparity:": {
      "abstract": [
        {
          "text": "Creates a Cinematic detection of a subject.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTime:detectionType:normalizedRect:focusDisparity:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/initWithTime:detectionType:normalizedRect:focusDisparity:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTime:detectionType:normalizedRect:focusDisparity:"
        }
      ],
      "role": "symbol",
      "title": "initWithTime:detectionType:normalizedRect:focusDisparity:",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/initwithtime:detectiontype:normalizedrect:focusdisparity:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/isValidDetectionGroupID:": {
      "abstract": [
        {
          "text": "Determines whether a given detection group ID is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "isValidDetectionGroupID:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/isValidDetectionGroupID:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isValidDetectionGroupID:"
        }
      ],
      "role": "symbol",
      "title": "isValidDetectionGroupID:",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/isvaliddetectiongroupid:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/isValidDetectionID:": {
      "abstract": [
        {
          "text": "Determines whether a given detection ID is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "isValidDetectionID:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/isValidDetectionID:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isValidDetectionID:"
        }
      ],
      "role": "symbol",
      "title": "isValidDetectionID:",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/isvaliddetectionid:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/normalizedRect": {
      "abstract": [
        {
          "text": "The rectangle within the image where the object occurs, normalized such that (0.0, 0.0) is the top-left and (1.0, 1.0) is the bottom-right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "normalizedRect"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/normalizedRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "normalizedRect",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/normalizedrect"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/time": {
      "abstract": [
        {
          "text": "The first presentation time which the subject should be in focus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "time"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/time",
      "kind": "symbol",
      "role": "symbol",
      "title": "time",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/time"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g": {
      "abstract": [
        {
          "text": "An object representing a series of detections of the same subject over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType": {
      "abstract": [
        {
          "text": "The type of object detected, such as face, torso, cat, dog and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2": {
      "abstract": [
        {
          "text": "An object representing the fixed detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNFixedDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-5aei2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g",
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2",
        "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType"
      ],
      "title": "Editing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionGroupID",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionID",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionType",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/focusDisparity",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/normalizedRect",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/time"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/initWithTime:detectionType:normalizedRect:focusDisparity:"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/accessibilityLabelForDetectionType:",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/disparityInNormalizedRect:sourceDisparity:detectionType:priorDisparity:",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/isValidDetectionGroupID:",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/isValidDetectionID:"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/title",
          "value": "CNDetectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic/cndetection-c.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
