{
  "abstract": [
    {
      "text": "The type of object detected, such as face, torso, cat, dog and so on.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cinematic/documentation/Cinematic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CNDetectionType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNDetectionType"
      }
    ],
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNDetectionType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CNDetectionType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc": {
      "abstract": [
        {
          "text": "An object representing a discrete detection track composed of individual detections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNCustomDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cncustomdetectiontrack-891hc"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-9a2zo": {
      "abstract": [
        {
          "text": "An object representing a discrete detection track composed of individual detections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-9a2zo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "role": "symbol",
      "title": "CNCustomDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cncustomdetectiontrack-9a2zo"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class": {
      "abstract": [
        {
          "text": "An object that represents a decision to focus on a particular detection, or group of detections, at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDecision",
      "type": "topic",
      "url": "/documentation/cinematic/cndecision-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-swift.struct": {
      "abstract": [
        {
          "text": "An object that represents a decision to focus on a particular detection, or group of detections, at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "role": "symbol",
      "title": "CNDecision",
      "type": "topic",
      "url": "/documentation/cinematic/cndecision-swift.struct"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class": {
      "abstract": [
        {
          "text": "A structure that represents a detected subject, face, torso or pet at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a detected subject, face, torso or pet at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "role": "symbol",
      "title": "CNDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-swift.struct"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-2bxtd": {
      "abstract": [
        {
          "text": "An object representing a series of detections of the same subject over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-2bxtd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-2bxtd"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g": {
      "abstract": [
        {
          "text": "An object representing a series of detections of the same subject over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType": {
      "abstract": [
        {
          "text": "The type of object detected, such as face, torso, cat, dog and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/autoFocus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoFocus"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/autoFocus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeAutoFocus"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.autoFocus",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/autofocus"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/catBody": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "catBody"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/catBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeCatBody"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.catBody",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/catbody"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/catHead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "catHead"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/catHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeCatHead"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.catHead",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/cathead"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/custom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/custom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeCustom"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.custom",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/custom"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/dogBody": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dogBody"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/dogBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeDogBody"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.dogBody",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/dogbody"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/dogHead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dogHead"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/dogHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeDogHead"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.dogHead",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/doghead"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/fixedFocus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixedFocus"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/fixedFocus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeFixedFocus"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.fixedFocus",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/fixedfocus"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanFace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "humanFace"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanFace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeHumanFace"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.humanFace",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/humanface"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanHead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "humanHead"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeHumanHead"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.humanHead",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/humanhead"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanTorso": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "humanTorso"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanTorso",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeHumanTorso"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.humanTorso",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/humantorso"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/init(rawvalue:)"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/sportsBall": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sportsBall"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/sportsBall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeSportsBall"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.sportsBall",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/sportsball"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType.unknown",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype/unknown"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2": {
      "abstract": [
        {
          "text": "An object representing the fixed detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNFixedDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-5aei2"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw": {
      "abstract": [
        {
          "text": "An object representing the fixed detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "role": "symbol",
      "title": "CNFixedDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-93rrw"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-swift.struct",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-swift.struct",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-2bxtd",
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw",
        "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-9a2zo"
      ],
      "title": "Editing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/autoFocus",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/catBody",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/catHead",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/custom",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/dogBody",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/dogHead",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/fixedFocus",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanFace",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanHead",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanTorso",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/sportsBall",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/unknown"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNDetectionType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cinematic/documentation/Cinematic"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/autoFocus",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/catBody",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/catHead",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/custom",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/dogBody",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/dogHead",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/fixedFocus",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanFace",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanHead",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/humanTorso",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/sportsBall",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType/unknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Editing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g",
                "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2",
                "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc"
              ],
              "title": "Editing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNDetectionType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1dogHead/title",
          "value": "CNDetectionTypeDogHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1dogHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeDogHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1custom/title",
          "value": "CNDetectionTypeCustom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1custom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeCustom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1humanTorso/title",
          "value": "CNDetectionTypeHumanTorso"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1humanTorso/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeHumanTorso"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/title",
          "value": "CNDetectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1catHead/title",
          "value": "CNDetectionTypeCatHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1catHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeCatHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1sportsBall/title",
          "value": "CNDetectionTypeSportsBall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1sportsBall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeSportsBall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1humanHead/title",
          "value": "CNDetectionTypeHumanHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1humanHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeHumanHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1catBody/title",
          "value": "CNDetectionTypeCatBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1catBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeCatBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1humanFace/title",
          "value": "CNDetectionTypeHumanFace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1humanFace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeHumanFace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1fixedFocus/title",
          "value": "CNDetectionTypeFixedFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1fixedFocus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeFixedFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1unknown/title",
          "value": "CNDetectionTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1autoFocus/title",
          "value": "CNDetectionTypeAutoFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1autoFocus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeAutoFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1dogBody/title",
          "value": "CNDetectionTypeDogBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType~1dogBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionTypeDogBody"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic/cndetectiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cinematic/cndetectiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
