{
  "abstract": [
    {
      "text": "An object representing a series of detections of the same subject over time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cinematic/documentation/Cinematic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNDetectionTrack",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CNDetectionTrack"
      }
    ],
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNDetectionTrack"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CNDetectionTrack"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNDetectionTrack"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc": {
      "abstract": [
        {
          "text": "An object representing a discrete detection track composed of individual detections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNCustomDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cncustomdetectiontrack-891hc"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class": {
      "abstract": [
        {
          "text": "An object that represents a decision to focus on a particular detection, or group of detections, at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDecision",
      "type": "topic",
      "url": "/documentation/cinematic/cndecision-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class": {
      "abstract": [
        {
          "text": "A structure that represents a detected subject, face, torso or pet at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g": {
      "abstract": [
        {
          "text": "An object representing a series of detections of the same subject over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionAtOrBeforeTime:": {
      "abstract": [
        {
          "text": "Returns the array of detections in the detection track before a given time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "detectionAtOrBeforeTime:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionAtOrBeforeTime:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detectionAtOrBeforeTime:"
        }
      ],
      "role": "symbol",
      "title": "detectionAtOrBeforeTime:",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g/detectionatorbeforetime:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionGroupID": {
      "abstract": [
        {
          "text": "The detection group ID of the subject detected by the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "detectionGroupID"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionGroupID",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectionGroupID",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g/detectiongroupid"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionID": {
      "abstract": [
        {
          "text": "The unique ID of the subject detected during this track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "detectionID"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionID",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectionID",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g/detectionid"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionNearestTime:": {
      "abstract": [
        {
          "text": "Returns the array of detections in the detection track nearest a given time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "detectionNearestTime:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionNearestTime:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detectionNearestTime:"
        }
      ],
      "role": "symbol",
      "title": "detectionNearestTime:",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g/detectionnearesttime:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionType": {
      "abstract": [
        {
          "text": "The type of object that’s detected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "detectionType"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionType",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectionType",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g/detectiontype"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionsInTimeRange:": {
      "abstract": [
        {
          "text": "Returns the array of detections in the detection track within the given time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "detectionsInTimeRange:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionsInTimeRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detectionsInTimeRange:"
        }
      ],
      "role": "symbol",
      "title": "detectionsInTimeRange:",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g/detectionsintimerange:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/discrete": {
      "abstract": [
        {
          "text": "A flag determining if the detection track has discrete detections, otherwise continuous.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "discrete"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/discrete",
      "kind": "symbol",
      "role": "symbol",
      "title": "discrete",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g/discrete"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/userCreated": {
      "abstract": [
        {
          "text": "A flag indicating if the client created the detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "userCreated"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/userCreated",
      "kind": "symbol",
      "role": "symbol",
      "title": "userCreated",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g/usercreated"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType": {
      "abstract": [
        {
          "text": "The type of object detected, such as face, torso, cat, dog and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2": {
      "abstract": [
        {
          "text": "An object representing the fixed detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNFixedDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-5aei2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc",
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class",
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2",
        "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType"
      ],
      "title": "Editing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionGroupID",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionID",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionType",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/discrete",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/userCreated"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionAtOrBeforeTime:",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionNearestTime:",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g/detectionsInTimeRange:"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/title",
          "value": "CNDetectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic/cndetectiontrack-61x7g"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
