{
  "abstract": [
    {
      "text": "An object representing the fixed detection track.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cinematic/documentation/Cinematic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNFixedDetectionTrack",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CNFixedDetectionTrack"
      }
    ],
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNFixedDetectionTrack"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CNFixedDetectionTrack"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNFixedDetectionTrack"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CNDetectionTrack",
              "text": "CNDetectionTrack"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc": {
      "abstract": [
        {
          "text": "An object representing a discrete detection track composed of individual detections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNCustomDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cncustomdetectiontrack-891hc"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class": {
      "abstract": [
        {
          "text": "An object that represents a decision to focus on a particular detection, or group of detections, at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDecision",
      "type": "topic",
      "url": "/documentation/cinematic/cndecision-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class": {
      "abstract": [
        {
          "text": "A structure that represents a detected subject, face, torso or pet at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g": {
      "abstract": [
        {
          "text": "An object representing a series of detections of the same subject over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType": {
      "abstract": [
        {
          "text": "The type of object detected, such as face, torso, cat, dog and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2": {
      "abstract": [
        {
          "text": "An object representing the fixed detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNFixedDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-5aei2"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/focusDisparity": {
      "abstract": [
        {
          "text": "The disparity to use in order to focus on the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "focusDisparity"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/focusDisparity",
      "kind": "symbol",
      "role": "symbol",
      "title": "focusDisparity",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-5aei2/focusdisparity"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/initWithFocusDisparity:": {
      "abstract": [
        {
          "text": "Creates a detection track with fixed focus at the given disparity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithFocusDisparity:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/initWithFocusDisparity:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFocusDisparity:"
        }
      ],
      "role": "symbol",
      "title": "initWithFocusDisparity:",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-5aei2/initwithfocusdisparity:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/initWithOriginalDetection:": {
      "abstract": [
        {
          "text": "Creates a detection track with fixed focus at the disparity of an existing detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithOriginalDetection:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/initWithOriginalDetection:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOriginalDetection:"
        }
      ],
      "role": "symbol",
      "title": "initWithOriginalDetection:",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-5aei2/initwithoriginaldetection:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/originalDetection": {
      "abstract": [
        {
          "text": "The original detection based on the fixed detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "originalDetection"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/originalDetection",
      "kind": "symbol",
      "role": "symbol",
      "title": "originalDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-5aei2/originaldetection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g",
        "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType"
      ],
      "title": "Editing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/focusDisparity",
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/originalDetection"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/initWithFocusDisparity:",
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2/initWithOriginalDetection:"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/title",
          "value": "CNDetectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic/cnfixeddetectiontrack-5aei2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
