{
  "abstract": [
    {
      "text": "An object representing the fixed detection track.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cinematic/documentation/Cinematic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9Cinematic21CNFixedDetectionTrackC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNFixedDetectionTrack"
      }
    ],
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNFixedDetectionTrack"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CNFixedDetectionTrack"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNFixedDetectionTrack"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-9a2zo": {
      "abstract": [
        {
          "text": "An object representing a discrete detection track composed of individual detections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-9a2zo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "role": "symbol",
      "title": "CNCustomDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cncustomdetectiontrack-9a2zo"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-swift.struct": {
      "abstract": [
        {
          "text": "An object that represents a decision to focus on a particular detection, or group of detections, at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "role": "symbol",
      "title": "CNDecision",
      "type": "topic",
      "url": "/documentation/cinematic/cndecision-swift.struct"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a detected subject, face, torso or pet at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "role": "symbol",
      "title": "CNDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-swift.struct"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-2bxtd": {
      "abstract": [
        {
          "text": "An object representing a series of detections of the same subject over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-2bxtd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-2bxtd"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType": {
      "abstract": [
        {
          "text": "The type of object detected, such as face, torso, cat, dog and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw": {
      "abstract": [
        {
          "text": "An object representing the fixed detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "role": "symbol",
      "title": "CNFixedDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-93rrw"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/focusDisparity": {
      "abstract": [
        {
          "text": "The disparity to use in order to focus on the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusDisparity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/focusDisparity",
      "kind": "symbol",
      "role": "symbol",
      "title": "focusDisparity",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-93rrw/focusdisparity"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/init(focusDisparity:)": {
      "abstract": [
        {
          "text": "Creates a detection track with fixed focus at the given disparity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "focusDisparity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/init(focusDisparity:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(focusDisparity:)",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-93rrw/init(focusdisparity:)"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/init(originalDetection:)": {
      "abstract": [
        {
          "text": "Creates a detection track with fixed focus at the disparity of an existing detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "originalDetection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9Cinematic11CNDetectionV",
          "text": "CNDetection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/init(originalDetection:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(originalDetection:)",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-93rrw/init(originaldetection:)"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/originalDetection": {
      "abstract": [
        {
          "text": "The original detection based on the fixed detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "originalDetection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9Cinematic11CNDetectionV",
          "text": "CNDetection"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/originalDetection",
      "kind": "symbol",
      "role": "symbol",
      "title": "originalDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-93rrw/originaldetection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-2bxtd"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-swift.struct",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-swift.struct",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-2bxtd",
        "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-9a2zo",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType"
      ],
      "title": "Editing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/init(focusDisparity:)",
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/init(originalDetection:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/focusDisparity",
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw/originalDetection"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/title",
          "value": "CNDetectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic/cnfixeddetectiontrack-93rrw"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
