{
  "abstract": [
    {
      "text": "Play and edit Cinematic mode video with an adjustable depth of field and focus points.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cinematic/documentation/Cinematic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cinematic/documentation/Cinematic/playing-and-editing-cinematic-mode-video"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Playing and editing Cinematic mode video"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC23 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc23/10137/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "9aea6c9ac3f7/PlayingAndEditingCinematicModeVideo.zip": {
      "checksum": "9aea6c9ac3f7d5458a2a986fbff841baee927d3e65ec7836a006538c26fe8f41105200574641c4db44bffcc247604dd0394b584dec1162f84868396590531536",
      "identifier": "9aea6c9ac3f7/PlayingAndEditingCinematicModeVideo.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/9aea6c9ac3f7/PlayingAndEditingCinematicModeVideo.zip"
    },
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNScript-1ispe": {
      "abstract": [
        {
          "text": "A collection of focus decisions, focus transitions, detections, and detection tracks associated with a movie captured in Cinematic mode and methods to change them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNScript"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNScript-1ispe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNScript"
        }
      ],
      "role": "symbol",
      "title": "CNScript",
      "type": "topic",
      "url": "/documentation/cinematic/cnscript-1ispe"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNScript-9e1zn": {
      "abstract": [
        {
          "text": "A collection of focus decisions, focus transitions, detections, and detection tracks associated with a movie captured in Cinematic mode and methods to change them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNScript"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNScript-9e1zn",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNScript",
      "type": "topic",
      "url": "/documentation/cinematic/cnscript-9e1zn"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNScriptChanges": {
      "abstract": [
        {
          "text": "An object that represents a snapshot of the changes made to a movie script, including the added user decisions and detection tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNScriptChanges"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNScriptChanges",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNScriptChanges",
      "type": "topic",
      "url": "/documentation/cinematic/cnscriptchanges"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNScriptFrame": {
      "abstract": [
        {
          "text": "An object that represents what to focus on, and where to focus, in a given movie frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNScriptFrame"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNScriptFrame",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNScriptFrame",
      "type": "topic",
      "url": "/documentation/cinematic/cnscriptframe"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/wwdc23/10137/": {
      "identifier": "https://developer.apple.com/wwdc23/10137/",
      "title": "10137: Support Cinematic mode videos in your app",
      "titleInlineContent": [
        {
          "text": "10137: Support Cinematic mode videos in your app",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc23/10137/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "9aea6c9ac3f7/PlayingAndEditingCinematicModeVideo.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNScript-1ispe"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/CNScript-9e1zn",
                "doc://com.apple.cinematic/documentation/Cinematic/CNScriptChanges",
                "doc://com.apple.cinematic/documentation/Cinematic/CNScriptFrame"
              ],
              "title": "Essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic/playing-and-editing-cinematic-mode-video"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cinematic/playing-and-editing-cinematic-mode-video"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
