{
  "abstract": [
    {
      "text": "Depth-value accuracy in which the framework is less confident.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/low"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ARConfidenceLevel@ARConfidenceLevelLow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "low"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARConfidenceLevelLow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ARConfidenceLevel.low"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "low"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel": {
      "abstract": [
        {
          "text": "Degrees to which the framework is confident about depth-data accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARConfidenceLevel"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARConfidenceLevel"
        }
      ],
      "role": "symbol",
      "title": "ARConfidenceLevel",
      "type": "topic",
      "url": "/documentation/arkit/arconfidencelevel"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/high": {
      "abstract": [
        {
          "text": "Depth-value accuracy in which the framework is fairly confident.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARConfidenceLevelHigh"
        }
      ],
      "role": "symbol",
      "title": "ARConfidenceLevel.high",
      "type": "topic",
      "url": "/documentation/arkit/arconfidencelevel/high"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/low": {
      "abstract": [
        {
          "text": "Depth-value accuracy in which the framework is less confident.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARConfidenceLevelLow"
        }
      ],
      "role": "symbol",
      "title": "ARConfidenceLevel.low",
      "type": "topic",
      "url": "/documentation/arkit/arconfidencelevel/low"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/medium": {
      "abstract": [
        {
          "text": "Depth-value accuracy in which the framework is moderately confident.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARConfidenceLevelMedium"
        }
      ],
      "role": "symbol",
      "title": "ARConfidenceLevel.medium",
      "type": "topic",
      "url": "/documentation/arkit/arconfidencelevel/medium"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Levels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/medium",
        "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/high"
      ],
      "title": "Levels"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARConfidenceLevelLow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARConfidenceLevelLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Levels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/medium",
                "doc://com.apple.arkit/documentation/ARKit/ARConfidenceLevel/high"
              ],
              "title": "Levels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ARConfidenceLevelLow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfidenceLevel~1medium/title",
          "value": "ARConfidenceLevelMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfidenceLevel~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARConfidenceLevelMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfidenceLevel~1high/title",
          "value": "ARConfidenceLevelHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfidenceLevel~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARConfidenceLevelHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfidenceLevel/title",
          "value": "ARConfidenceLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfidenceLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARConfidenceLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfidenceLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARConfidenceLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfidenceLevel~1low/title",
          "value": "ARConfidenceLevelLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfidenceLevel~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARConfidenceLevelLow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arconfidencelevel/low"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arconfidencelevel/low"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
