{
  "abstract": [
    {
      "text": "Optional pointer to a FFENVELOPE structure that describes the envelope to be used by this effect. Not all effect types use envelopes. If no envelope is to be applied, the member should be set to NULL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/lpEnvelope"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@FFEFFECT@FI@lpEnvelope",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lpEnvelope"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@PFFENVELOPE",
        "text": "PFFENVELOPE"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "lpEnvelope"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "lpEnvelope"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lpEnvelope"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFENVELOPE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PFFENVELOPE",
              "text": "PFFENVELOPE"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT": {
      "abstract": [
        {
          "text": "UsUsed by the FFDeviceCreateEffect method to initialize a new effect object. It is also used by the FFEffectSetParameters and FFEffectGetParameters functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFFECT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFFECT"
        }
      ],
      "role": "symbol",
      "title": "FFEFFECT",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/cAxes": {
      "abstract": [
        {
          "text": "Number of axes involved in the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cAxes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/cAxes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cAxes"
        }
      ],
      "role": "symbol",
      "title": "cAxes",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/caxes"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/cbTypeSpecificParams": {
      "abstract": [
        {
          "text": "Number of bytes of additional type-specific parameters for the corresponding effect type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cbTypeSpecificParams"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/cbTypeSpecificParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cbTypeSpecificParams"
        }
      ],
      "role": "symbol",
      "title": "cbTypeSpecificParams",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/cbtypespecificparams"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwDuration": {
      "abstract": [
        {
          "text": "The total duration of the effect, in microseconds. If this value is FF_INFINITE, the effect has infinite duration. If an envelope has been applied to the effect, the attack is applied, followed by an infinite sustain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwDuration"
        }
      ],
      "role": "symbol",
      "title": "dwDuration",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/dwduration"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwFlags": {
      "abstract": [
        {
          "text": "Flags associated with an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwFlags"
        }
      ],
      "role": "symbol",
      "title": "dwFlags",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/dwflags"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwGain": {
      "abstract": [
        {
          "text": "The gain to be applied to the effect, in the range from 0 through 10,000. The gain is a scaling factor applied to all magnitudes of the effect and its envelope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwGain"
        }
      ],
      "role": "symbol",
      "title": "dwGain",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/dwgain"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwSamplePeriod": {
      "abstract": [
        {
          "text": "The period at which the device should play back the effect, in microseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwSamplePeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwSamplePeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwSamplePeriod"
        }
      ],
      "role": "symbol",
      "title": "dwSamplePeriod",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/dwsampleperiod"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwSize": {
      "abstract": [
        {
          "text": "Size, in bytes, of this structure. This member must be initialized before the structure is used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwSize"
        }
      ],
      "role": "symbol",
      "title": "dwSize",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/dwsize"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwStartDelay": {
      "abstract": [
        {
          "text": "Time (in microseconds) that the device should wait after a FFEffectStart call before playing the effect. If this value is 0, effect playback begins immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwStartDelay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwStartDelay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwStartDelay"
        }
      ],
      "role": "symbol",
      "title": "dwStartDelay",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/dwstartdelay"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwTriggerButton": {
      "abstract": [
        {
          "text": "The identifier or offset of the button to be used to trigger playback of the effect. The FFJOFS_* flags must be used to specify the value. If this member is set to FFEB_NOTRIGGER, no trigger button is associated with the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwTriggerButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwTriggerButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwTriggerButton"
        }
      ],
      "role": "symbol",
      "title": "dwTriggerButton",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/dwtriggerbutton"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwTriggerRepeatInterval": {
      "abstract": [
        {
          "text": "The interval, in microseconds, between the end of one playback and the start of the next when the effect is triggered by a button press and the button is held down. Setting this value to FF_INFINITE suppresses repetition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwTriggerRepeatInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwTriggerRepeatInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwTriggerRepeatInterval"
        }
      ],
      "role": "symbol",
      "title": "dwTriggerRepeatInterval",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/dwtriggerrepeatinterval"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/lpEnvelope": {
      "abstract": [
        {
          "text": "Optional pointer to a FFENVELOPE structure that describes the envelope to be used by this effect. Not all effect types use envelopes. If no envelope is to be applied, the member should be set to NULL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lpEnvelope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PFFENVELOPE",
          "text": "PFFENVELOPE"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/lpEnvelope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lpEnvelope"
        }
      ],
      "role": "symbol",
      "title": "lpEnvelope",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/lpenvelope"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/lpvTypeSpecificParams": {
      "abstract": [
        {
          "text": "A pointer to type-specific parameters, or NULL if there are no type-specific parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lpvTypeSpecificParams"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/lpvTypeSpecificParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lpvTypeSpecificParams"
        }
      ],
      "role": "symbol",
      "title": "lpvTypeSpecificParams",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/lpvtypespecificparams"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/rgdwAxes": {
      "abstract": [
        {
          "text": "Pointer to a DWORD array (of ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "cAxes",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " elements) containing identifiers or offsets identifying the axes to which the effect is to be applied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgdwAxes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LPDWORD",
          "text": "LPDWORD"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/rgdwAxes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rgdwAxes"
        }
      ],
      "role": "symbol",
      "title": "rgdwAxes",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/rgdwaxes"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/rglDirection": {
      "abstract": [
        {
          "text": "Pointer to a LONG array (of ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "cAxes",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " elements) containing either Cartesian coordinates, polar coordinates, or spherical coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rglDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LPLONG",
          "text": "LPLONG"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/rglDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rglDirection"
        }
      ],
      "role": "symbol",
      "title": "rglDirection",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect/rgldirection"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFENVELOPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PFFENVELOPE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFENVELOPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PFFENVELOPE"
        }
      ],
      "role": "symbol",
      "title": "PFFENVELOPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/pffenvelope"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/cAxes",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/cbTypeSpecificParams",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwDuration",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwFlags",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwGain",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwSamplePeriod",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwSize",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwStartDelay",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwTriggerButton",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwTriggerRepeatInterval",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/lpvTypeSpecificParams",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/rgdwAxes",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/rglDirection"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "lpEnvelope"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lpEnvelope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/cAxes",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/cbTypeSpecificParams",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwDuration",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwFlags",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwGain",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwSamplePeriod",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwSize",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwStartDelay",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwTriggerButton",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/dwTriggerRepeatInterval",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/lpvTypeSpecificParams",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/rgdwAxes",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT/rglDirection"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFENVELOPE",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@PFFENVELOPE",
                    "text": "PFFENVELOPE"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "lpEnvelope"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwFlags/title",
          "value": "dwFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/title",
          "value": "FFEFFECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwStartDelay/title",
          "value": "dwStartDelay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwStartDelay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwStartDelay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwSamplePeriod/title",
          "value": "dwSamplePeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwSamplePeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwSamplePeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1lpEnvelope/title",
          "value": "lpEnvelope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1lpEnvelope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lpEnvelope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwTriggerRepeatInterval/title",
          "value": "dwTriggerRepeatInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwTriggerRepeatInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwTriggerRepeatInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1lpvTypeSpecificParams/title",
          "value": "lpvTypeSpecificParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1lpvTypeSpecificParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lpvTypeSpecificParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1rgdwAxes/title",
          "value": "rgdwAxes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1rgdwAxes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rgdwAxes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwDuration/title",
          "value": "dwDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwSize/title",
          "value": "dwSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwTriggerButton/title",
          "value": "dwTriggerButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwTriggerButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwTriggerButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1cbTypeSpecificParams/title",
          "value": "cbTypeSpecificParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1cbTypeSpecificParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cbTypeSpecificParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwGain/title",
          "value": "dwGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1dwGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1rglDirection/title",
          "value": "rglDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1rglDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rglDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1cAxes/title",
          "value": "cAxes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT~1cAxes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cAxes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFENVELOPE/title",
          "value": "PFFENVELOPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFENVELOPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFENVELOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFENVELOPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFENVELOPE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffeffect/lpenvelope"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffeffect/lpenvelope"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
