{
  "abstract": [
    {
      "text": "Cancels a previously registered time observer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline/removeTimeObserver:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVPlayerItemIntegratedTimeline(im)removeTimeObserver:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "removeTimeObserver:"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "removeTimeObserver:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "removeTimeObserver:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "removeTimeObserver:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)AVPlayerItemIntegratedTimelineObserver",
              "text": "id<AVPlayerItemIntegratedTimelineObserver>"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "observer"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline": {
      "abstract": [
        {
          "text": "An object that models the timeline and playback sequence of a primary player item and scheduled interstitial events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemIntegratedTimeline"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemIntegratedTimeline"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemIntegratedTimeline",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemintegratedtimeline"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline/addBoundaryTimeObserverForSegment:offsetsIntoSegment:queue:usingBlock:": {
      "abstract": [
        {
          "text": "Requests invocation of a block when traversing an offset in a segment during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addBoundaryTimeObserverForSegment:offsetsIntoSegment:queue:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline/addBoundaryTimeObserverForSegment:offsetsIntoSegment:queue:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addBoundaryTimeObserverForSegment:offsetsIntoSegment:queue:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "addBoundaryTimeObserverForSegment:offsetsIntoSegment:queue:usingBlock:",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemintegratedtimeline/addboundarytimeobserverforsegment:offsetsintosegment:queue:usingblock:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline/addPeriodicTimeObserverForInterval:queue:usingBlock:": {
      "abstract": [
        {
          "text": "Requests invocation of a block during playback to report changing time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addPeriodicTimeObserverForInterval:queue:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline/addPeriodicTimeObserverForInterval:queue:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPeriodicTimeObserverForInterval:queue:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "addPeriodicTimeObserverForInterval:queue:usingBlock:",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemintegratedtimeline/addperiodictimeobserverforinterval:queue:usingblock:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline/removeTimeObserver:": {
      "abstract": [
        {
          "text": "Cancels a previously registered time observer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeTimeObserver:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline/removeTimeObserver:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeTimeObserver:"
        }
      ],
      "role": "symbol",
      "title": "removeTimeObserver:",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemintegratedtimeline/removetimeobserver:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimelineObserver": {
      "abstract": [
        {
          "text": "A protocol for objects that perform timeline observations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemIntegratedTimelineObserver"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimelineObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemIntegratedTimelineObserver"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemIntegratedTimelineObserver",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemintegratedtimelineobserver"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Observing-time-changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline/addPeriodicTimeObserverForInterval:queue:usingBlock:",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline/addBoundaryTimeObserverForSegment:offsetsIntoSegment:queue:usingBlock:",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemIntegratedTimelineObserver"
      ],
      "title": "Observing time changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemIntegratedTimelineObserver/title",
          "value": "AVPlayerItemIntegratedTimelineObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemIntegratedTimelineObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemIntegratedTimelineObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemIntegratedTimelineObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemIntegratedTimelineObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemIntegratedTimeline/title",
          "value": "AVPlayerItemIntegratedTimeline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemIntegratedTimeline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemIntegratedTimeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemIntegratedTimeline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemIntegratedTimeline"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avplayeritemintegratedtimeline/removetimeobserver:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
