{
  "abstract": [
    {
      "text": "Specifies that access control is used for key exchange.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeyKeyExchange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@LAAccessControlOperation@LAAccessControlOperationUseKeyKeyExchange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "useKeyKeyExchange"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LAAccessControlOperationUseKeyKeyExchange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "LAAccessControlOperation.useKeyKeyExchange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "useKeyKeyExchange"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation": {
      "abstract": [
        {
          "text": "Operations to be evaluated for access control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAAccessControlOperation"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAAccessControlOperation"
        }
      ],
      "role": "symbol",
      "title": "LAAccessControlOperation",
      "type": "topic",
      "url": "/documentation/localauthentication/laaccesscontroloperation"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/createItem": {
      "abstract": [
        {
          "text": "Specifies that access control is used for item creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createItem"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/createItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAAccessControlOperationCreateItem"
        }
      ],
      "role": "symbol",
      "title": "LAAccessControlOperation.createItem",
      "type": "topic",
      "url": "/documentation/localauthentication/laaccesscontroloperation/createitem"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/createKey": {
      "abstract": [
        {
          "text": "Specifies that access control is used for key creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createKey"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/createKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAAccessControlOperationCreateKey"
        }
      ],
      "role": "symbol",
      "title": "LAAccessControlOperation.createKey",
      "type": "topic",
      "url": "/documentation/localauthentication/laaccesscontroloperation/createkey"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useItem": {
      "abstract": [
        {
          "text": "Specifies that access control is used for accessing an existing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useItem"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAAccessControlOperationUseItem"
        }
      ],
      "role": "symbol",
      "title": "LAAccessControlOperation.useItem",
      "type": "topic",
      "url": "/documentation/localauthentication/laaccesscontroloperation/useitem"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeyDecrypt": {
      "abstract": [
        {
          "text": "Specifies that access control is used for data decryption using existing key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useKeyDecrypt"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeyDecrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAAccessControlOperationUseKeyDecrypt"
        }
      ],
      "role": "symbol",
      "title": "LAAccessControlOperation.useKeyDecrypt",
      "type": "topic",
      "url": "/documentation/localauthentication/laaccesscontroloperation/usekeydecrypt"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeyKeyExchange": {
      "abstract": [
        {
          "text": "Specifies that access control is used for key exchange.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useKeyKeyExchange"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeyKeyExchange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAAccessControlOperationUseKeyKeyExchange"
        }
      ],
      "role": "symbol",
      "title": "LAAccessControlOperation.useKeyKeyExchange",
      "type": "topic",
      "url": "/documentation/localauthentication/laaccesscontroloperation/usekeykeyexchange"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeySign": {
      "abstract": [
        {
          "text": "Specifies that access control is used for accessing an existing key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useKeySign"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeySign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAAccessControlOperationUseKeySign"
        }
      ],
      "role": "symbol",
      "title": "LAAccessControlOperation.useKeySign",
      "type": "topic",
      "url": "/documentation/localauthentication/laaccesscontroloperation/usekeysign"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/createItem",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useItem",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/createKey",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeySign",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeyDecrypt"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LAAccessControlOperationUseKeyKeyExchange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperationUseKeyKeyExchange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/createItem",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useItem",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/createKey",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeySign",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation/useKeyDecrypt"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "LAAccessControlOperationUseKeyKeyExchange"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1useKeySign/title",
          "value": "LAAccessControlOperationUseKeySign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1useKeySign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperationUseKeySign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1useKeyDecrypt/title",
          "value": "LAAccessControlOperationUseKeyDecrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1useKeyDecrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperationUseKeyDecrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1createItem/title",
          "value": "LAAccessControlOperationCreateItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1createItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperationCreateItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1createKey/title",
          "value": "LAAccessControlOperationCreateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1createKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperationCreateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1useItem/title",
          "value": "LAAccessControlOperationUseItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1useItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperationUseItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1useKeyKeyExchange/title",
          "value": "LAAccessControlOperationUseKeyKeyExchange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation~1useKeyKeyExchange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperationUseKeyKeyExchange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation/title",
          "value": "LAAccessControlOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/laaccesscontroloperation/usekeykeyexchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/laaccesscontroloperation/usekeykeyexchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
