{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/MPMovieLoadStateUnknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPMovieLoadState@MPMovieLoadStateUnknown",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MPMovieLoadStateUnknown"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMovieLoadStateUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "MPMovieLoadStateUnknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadStateUnknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The load state is not known.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState": {
      "abstract": [
        {
          "text": "Constants describing the network load state of the movie player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieLoadState"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieLoadState"
        }
      ],
      "role": "symbol",
      "title": "MPMovieLoadState",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieloadstate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/MPMovieLoadStateUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMovieLoadStateUnknown"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/MPMovieLoadStateUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMovieLoadStateUnknown",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieloadstate/mpmovieloadstateunknown"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/playable": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMovieLoadState",
          "text": "MPMovieLoadState"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/playable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieLoadStatePlayable"
        }
      ],
      "role": "symbol",
      "title": "playable",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieloadstate/playable"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/playthroughOK": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playthroughOK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMovieLoadState",
          "text": "MPMovieLoadState"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/playthroughOK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieLoadStatePlaythroughOK"
        }
      ],
      "role": "symbol",
      "title": "playthroughOK",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieloadstate/playthroughok"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/stalled": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stalled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMovieLoadState",
          "text": "MPMovieLoadState"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/stalled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieLoadStateStalled"
        }
      ],
      "role": "symbol",
      "title": "stalled",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieloadstate/stalled"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/playable",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/playthroughOK",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState/stalled"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState~1stalled/title",
          "value": "MPMovieLoadStateStalled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState~1stalled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadStateStalled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/title",
          "value": "MPMovieLoadState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState~1playthroughOK/title",
          "value": "MPMovieLoadStatePlaythroughOK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState~1playthroughOK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadStatePlaythroughOK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState~1playable/title",
          "value": "MPMovieLoadStatePlayable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState~1playable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadStatePlayable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmovieloadstate/mpmovieloadstateunknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
