{
  "abstract": [
    {
      "text": "Enable a private key to be used in signing a block of data or verifying a signed block.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/privateKeyUsage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecAccessControlCreateFlags@kSecAccessControlPrivateKeyUsage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "privateKeyUsage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
        "text": "SecAccessControlCreateFlags"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSecAccessControlPrivateKeyUsage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.1",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "privateKeyUsage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "privateKeyUsage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
              "text": "SecAccessControlCreateFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.security/documentation/Security/protecting-keys-with-the-secure-enclave"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This option can be combined with any other access control flags.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You typically use this constraint when you create a key pair and store the private key inside a device’s Secure Enclave (by specifying the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecAttrTokenID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attribute with a value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecAttrTokenIDSecureEnclave",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). This makes the private key available for use in signing and verification tasks that happen inside the Secure Enclave with calls to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyRawSign(_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyRawVerify(_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions. An attempt to use this constraint while generating a key pair outside the Secure Enclave fails. Similarly, an attempt to sign a block with a private key generated without this constraint inside the Secure Enclave fails.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags": {
      "abstract": [
        {
          "text": "Access control constants that dictate how a keychain item may be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "role": "symbol",
      "title": "SecAccessControlCreateFlags",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/privateKeyUsage": {
      "abstract": [
        {
          "text": "Enable a private key to be used in signing a block of data or verifying a signed block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "privateKeyUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/privateKeyUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlPrivateKeyUsage"
        }
      ],
      "role": "symbol",
      "title": "privateKeyUsage",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/privatekeyusage"
    },
    "doc://com.apple.security/documentation/Security/SecKeyRawSign(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Generates a digital signature for a block of data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyRawSign"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecPadding",
          "text": "SecPadding"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyRawSign(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyRawSign"
        }
      ],
      "role": "symbol",
      "title": "SecKeyRawSign(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seckeyrawsign(_:_:_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeyRawVerify(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Verifies a digital signature.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyRawVerify"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecPadding",
          "text": "SecPadding"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyRawVerify(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyRawVerify"
        }
      ],
      "role": "symbol",
      "title": "SecKeyRawVerify(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seckeyrawverify(_:_:_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrTokenID": {
      "abstract": [
        {
          "text": "A key whose value indicates that a cryptographic key is in an external store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrTokenID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrTokenID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrTokenID"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrTokenID",
      "type": "topic",
      "url": "/documentation/security/ksecattrtokenid"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrTokenIDSecureEnclave": {
      "abstract": [
        {
          "text": "Specifies an item should be stored in the device’s Secure Enclave.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrTokenIDSecureEnclave"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrTokenIDSecureEnclave",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrTokenIDSecureEnclave"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrTokenIDSecureEnclave",
      "type": "topic",
      "url": "/documentation/security/ksecattrtokenidsecureenclave"
    },
    "doc://com.apple.security/documentation/Security/protecting-keys-with-the-secure-enclave": {
      "abstract": [
        {
          "text": "Create an extra layer of security for your private keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/protecting-keys-with-the-secure-enclave",
      "kind": "article",
      "role": "article",
      "title": "Protecting keys with the Secure Enclave",
      "type": "topic",
      "url": "/documentation/security/protecting-keys-with-the-secure-enclave"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.1",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSecAccessControlPrivateKeyUsage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlPrivateKeyUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security",
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSecAccessControlPrivateKeyUsage"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1privateKeyUsage/title",
          "value": "kSecAccessControlPrivateKeyUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1privateKeyUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlPrivateKeyUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyRawSign(_:_:_:_:_:_:)/title",
          "value": "SecKeyRawSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyRawSign(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyRawSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrTokenIDSecureEnclave/title",
          "value": "kSecAttrTokenIDSecureEnclave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrTokenIDSecureEnclave/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrTokenIDSecureEnclave"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrTokenID/title",
          "value": "kSecAttrTokenID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrTokenID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrTokenID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags/title",
          "value": "SecAccessControlCreateFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessControlCreateFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessControlCreateFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyRawVerify(_:_:_:_:_:_:)/title",
          "value": "SecKeyRawVerify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyRawVerify(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyRawVerify"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secaccesscontrolcreateflags/privatekeyusage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secaccesscontrolcreateflags/privatekeyusage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
