{"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIStepper"]]},"seeAlsoSections":[{"anchor":"Customizing-appearance","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIStepper/backgroundImage(for:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/setBackgroundImage(_:for:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/decrementImage(for:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/setDecrementImage(_:for:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/dividerImage(forLeftSegmentState:rightSegmentState:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/setDividerImage(_:forLeftSegmentState:rightSegmentState:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/incrementImage(for:)"],"title":"Customizing appearance"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setIncrementImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","text":"State","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to use for the increment glyph."}]}]},{"name":"state","content":[{"type":"paragraph","inlineContent":[{"text":"The control state.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The image you specify is used as a template image to create the final control. If you don’t specify a custom image, a plus (","type":"text"},{"type":"codeVoice","code":"+"},{"text":") glyph is used.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Sets the image to use for the increment glyph of the control."}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIStepper/setIncrementImage(_:for:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIncrementImage"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"title":"setIncrementImage(_:for:)","externalID":"c:objc(cs)UIStepper(im)setIncrementImage:forState:","modules":[{"name":"UIKit"}],"navigatorTitle":[{"kind":"identifier","text":"setIncrementImage:forState:"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","platforms":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false,"introducedAt":"6.0"},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"6.0"},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.1"},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uistepper/setincrementimage(_:for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uistepper/setincrementimage(_:for:)"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIControl":{"navigatorTitle":[{"text":"UIControl","kind":"identifier"}],"title":"UIControl","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControl","kind":"identifier"}],"abstract":[{"type":"text","text":"The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions."}],"url":"/documentation/uikit/uicontrol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIStepper/setBackgroundImage(_:for:)":{"type":"topic","url":"/documentation/uikit/uistepper/setbackgroundimage(_:for:)","title":"setBackgroundImage(_:for:)","abstract":[{"text":"Sets the background image for the control when it’s in the specified state.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBackgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIStepper/setBackgroundImage(_:for:)","navigatorTitle":[{"text":"setBackgroundImage:forState:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIStepper/backgroundImage(for:)":{"abstract":[{"text":"Returns the background image associated with the specified control state.","type":"text"}],"title":"backgroundImage(for:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIStepper/backgroundImage(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"backgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"backgroundImageForState:"}],"role":"symbol","url":"/documentation/uikit/uistepper/backgroundimage(for:)","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIStepper/decrementImage(for:)":{"type":"topic","url":"/documentation/uikit/uistepper/decrementimage(for:)","title":"decrementImage(for:)","abstract":[{"text":"Returns the image used for the decrement glyph of the control.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decrementImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIStepper/decrementImage(for:)","navigatorTitle":[{"text":"decrementImageForState:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIStepper/dividerImage(forLeftSegmentState:rightSegmentState:)":{"type":"topic","url":"/documentation/uikit/uistepper/dividerimage(forleftsegmentstate:rightsegmentstate:)","title":"dividerImage(forLeftSegmentState:rightSegmentState:)","abstract":[{"text":"Returns the divider image for the given combination of left and right states.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dividerImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forLeftSegmentState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rightSegmentState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIStepper/dividerImage(forLeftSegmentState:rightSegmentState:)","navigatorTitle":[{"text":"dividerImageForLeftSegmentState:rightSegmentState:","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIStepper/setIncrementImage(_:for:)":{"type":"topic","url":"/documentation/uikit/uistepper/setincrementimage(_:for:)","title":"setIncrementImage(_:for:)","abstract":[{"text":"Sets the image to use for the increment glyph of the control.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setIncrementImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIStepper/setIncrementImage(_:for:)","navigatorTitle":[{"text":"setIncrementImage:forState:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIStepper/setDividerImage(_:forLeftSegmentState:rightSegmentState:)":{"type":"topic","url":"/documentation/uikit/uistepper/setdividerimage(_:forleftsegmentstate:rightsegmentstate:)","title":"setDividerImage(_:forLeftSegmentState:rightSegmentState:)","abstract":[{"text":"Sets the image to use for the given combination of left and right states.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDividerImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forLeftSegmentState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rightSegmentState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIStepper/setDividerImage(_:forLeftSegmentState:rightSegmentState:)","navigatorTitle":[{"text":"setDividerImage:forLeftSegmentState:rightSegmentState:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"State"}],"title":"UIControl.State","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/state-swift.struct","abstract":[{"type":"text","text":"Constants describing the state of a control."}]},"doc://com.apple.uikit/documentation/UIKit/UIStepper/setDecrementImage(_:for:)":{"abstract":[{"text":"Sets the image to use for the decrement glyph of the control.","type":"text"}],"title":"setDecrementImage(_:for:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIStepper/setDecrementImage(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDecrementImage"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?, "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setDecrementImage:forState:","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/uistepper/setdecrementimage(_:for:)","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIStepper/incrementImage(for:)":{"type":"topic","url":"/documentation/uikit/uistepper/incrementimage(for:)","title":"incrementImage(for:)","abstract":[{"text":"Returns the image used for the increment glyph of the control.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incrementImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIStepper/incrementImage(for:)","navigatorTitle":[{"text":"incrementImageForState:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIStepper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIStepper"}],"type":"topic","title":"UIStepper","url":"/documentation/uikit/uistepper","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIStepper","navigatorTitle":[{"kind":"identifier","text":"UIStepper"}],"abstract":[{"type":"text","text":"A control for incrementing or decrementing a value."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"name":"iOS","introducedAt":"6.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"6.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","deprecated":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"setIncrementImage:forState:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setIncrementImage:forState:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIStepper"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Customizing appearance","anchor":"Customizing-appearance","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIStepper/backgroundImage(for:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/setBackgroundImage(_:for:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/decrementImage(for:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/setDecrementImage(_:for:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/dividerImage(forLeftSegmentState:rightSegmentState:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/setDividerImage(_:forLeftSegmentState:rightSegmentState:)","doc://com.apple.uikit/documentation/UIKit/UIStepper/incrementImage(for:)"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setIncrementImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forState:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","text":"UIControlState","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The image to use for the increment glyph."}],"type":"paragraph"}]},{"name":"state","content":[{"inlineContent":[{"type":"text","text":"The control state."}],"type":"paragraph"}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title","value":"UIControl"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments","value":[{"text":"UIControl","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle","value":[{"text":"UIControl","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1setBackgroundImage(_:for:)/title","value":"setBackgroundImage:forState:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1setBackgroundImage(_:for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setBackgroundImage:forState:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1backgroundImage(for:)/title","value":"backgroundImageForState:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1backgroundImage(for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backgroundImageForState:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1decrementImage(for:)/title","value":"decrementImageForState:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1decrementImage(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"decrementImageForState:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1dividerImage(forLeftSegmentState:rightSegmentState:)/title","value":"dividerImageForLeftSegmentState:rightSegmentState:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1dividerImage(forLeftSegmentState:rightSegmentState:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"dividerImageForLeftSegmentState:rightSegmentState:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1setIncrementImage(_:for:)/title","value":"setIncrementImage:forState:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1setIncrementImage(_:for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setIncrementImage:forState:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1setDividerImage(_:forLeftSegmentState:rightSegmentState:)/title","value":"setDividerImage:forLeftSegmentState:rightSegmentState:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1setDividerImage(_:forLeftSegmentState:rightSegmentState:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setDividerImage:forLeftSegmentState:rightSegmentState:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/title","value":"UIControlState"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/fragments","value":[{"text":"UIControlState","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/navigatorTitle","value":[{"kind":"identifier","text":"UIControlState"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1setDecrementImage(_:for:)/title","value":"setDecrementImage:forState:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1setDecrementImage(_:for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDecrementImage:forState:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","value":"UIImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","value":[{"kind":"identifier","text":"UIImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","value":[{"kind":"identifier","text":"UIImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1incrementImage(for:)/title","value":"incrementImageForState:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper~1incrementImage(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"incrementImageForState:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper/title","value":"UIStepper"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper/fragments","value":[{"kind":"identifier","text":"UIStepper"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStepper/navigatorTitle","value":[{"text":"UIStepper","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}