{
  "abstract": [
    {
      "text": "After attempting to authenticate, the Hotspot Helper app determined that it can’t perform the authentication. This result is only valid in response to commands of type ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/authenticate",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " and ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/presentUI",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/unsupportedNetwork"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEHotspotHelperResult@kNEHotspotHelperResultUnsupportedNetwork",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unsupportedNetwork"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kNEHotspotHelperResultUnsupportedNetwork"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEHotspotHelperResult.unsupportedNetwork"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unsupportedNetwork"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/authenticate": {
      "abstract": [
        {
          "text": "Authenticate to the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticate"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/authenticate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperCommandTypeAuthenticate"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType.authenticate",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype/authenticate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/maintain": {
      "abstract": [
        {
          "text": "Maintain the connection to the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maintain"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/maintain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperCommandTypeMaintain"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType.maintain",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype/maintain"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/presentUI": {
      "abstract": [
        {
          "text": "Present user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentUI"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/presentUI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperCommandTypePresentUI"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType.presentUI",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype/presentui"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotHelperResult"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotHelperResult"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperResult",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelperresult"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/authenticationRequired": {
      "abstract": [
        {
          "text": "The network requires authentication again. This result is only valid in response to a command with type ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/maintain",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationRequired"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/authenticationRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperResultAuthenticationRequired"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperResult.authenticationRequired",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelperresult/authenticationrequired"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/commandNotRecognized": {
      "abstract": [
        {
          "text": "The helper did not recognize the command type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commandNotRecognized"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/commandNotRecognized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperResultCommandNotRecognized"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperResult.commandNotRecognized",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelperresult/commandnotrecognized"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/failure": {
      "abstract": [
        {
          "text": "The command failed to be handled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperResultFailure"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperResult.failure",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelperresult/failure"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/success": {
      "abstract": [
        {
          "text": "The command was handled successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperResultSuccess"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperResult.success",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelperresult/success"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/temporaryFailure": {
      "abstract": [
        {
          "text": "The Hotspot Helper app determined that it is temporarily unable to perform the authentication. This result is only valid in response to commands of type ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/authenticate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/presentUI",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "temporaryFailure"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/temporaryFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperResultTemporaryFailure"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperResult.temporaryFailure",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelperresult/temporaryfailure"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/uiRequired": {
      "abstract": [
        {
          "text": "The operation requires user interaction. This result is only valid in response to a command with type ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/authenticate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uiRequired"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/uiRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperResultUIRequired"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperResult.uiRequired",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelperresult/uirequired"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/unsupportedNetwork": {
      "abstract": [
        {
          "text": "After attempting to authenticate, the Hotspot Helper app determined that it can’t perform the authentication. This result is only valid in response to commands of type ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/authenticate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/presentUI",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedNetwork"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/unsupportedNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperResultUnsupportedNetwork"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperResult.unsupportedNetwork",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelperresult/unsupportednetwork"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/success",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/failure",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/uiRequired",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/commandNotRecognized",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/authenticationRequired",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/temporaryFailure"
      ],
      "title": "Results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kNEHotspotHelperResultUnsupportedNetwork"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperResultUnsupportedNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/success",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/failure",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/uiRequired",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/commandNotRecognized",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/authenticationRequired",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperResult/temporaryFailure"
              ],
              "title": "Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kNEHotspotHelperResultUnsupportedNetwork"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1commandNotRecognized/title",
          "value": "kNEHotspotHelperResultCommandNotRecognized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1commandNotRecognized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperResultCommandNotRecognized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1maintain/title",
          "value": "kNEHotspotHelperCommandTypeMaintain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1maintain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypeMaintain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1failure/title",
          "value": "kNEHotspotHelperResultFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperResultFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1uiRequired/title",
          "value": "kNEHotspotHelperResultUIRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1uiRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperResultUIRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1presentUI/title",
          "value": "kNEHotspotHelperCommandTypePresentUI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1presentUI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypePresentUI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult/title",
          "value": "NEHotspotHelperResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotHelperResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotHelperResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1authenticate/title",
          "value": "kNEHotspotHelperCommandTypeAuthenticate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1authenticate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypeAuthenticate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1unsupportedNetwork/title",
          "value": "kNEHotspotHelperResultUnsupportedNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1unsupportedNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperResultUnsupportedNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1success/title",
          "value": "kNEHotspotHelperResultSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperResultSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1authenticationRequired/title",
          "value": "kNEHotspotHelperResultAuthenticationRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1authenticationRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperResultAuthenticationRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1temporaryFailure/title",
          "value": "kNEHotspotHelperResultTemporaryFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperResult~1temporaryFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperResultTemporaryFailure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nehotspothelperresult/unsupportednetwork"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nehotspothelperresult/unsupportednetwork"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
