{
  "abstract": [
    {
      "text": "A Discover payment card.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/discover"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "PassKit",
    "externalID": "c:@PKPaymentNetworkDiscover",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "discover"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@PKPaymentNetwork",
        "text": "PKPaymentNetwork"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentNetworkDiscover"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "discover"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "discover"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PKPaymentNetwork",
              "text": "PKPaymentNetwork"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork": {
      "abstract": [
        {
          "text": "A type that represents a payment method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetwork"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentNetwork",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/amex": {
      "abstract": [
        {
          "text": "An American Express payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/amex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkAmex"
        }
      ],
      "role": "symbol",
      "title": "amex",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/amex"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancomat": {
      "abstract": [
        {
          "text": "A Bancomat payment card.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bancomat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancomat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkBancomat"
        }
      ],
      "role": "symbol",
      "title": "bancomat",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/bancomat"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancontact": {
      "abstract": [
        {
          "text": "A Bancontact payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bancontact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancontact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkBancontact"
        }
      ],
      "role": "symbol",
      "title": "bancontact",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/bancontact"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bankAxept": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bankAxept"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bankAxept",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkBankAxept"
        }
      ],
      "role": "symbol",
      "title": "bankAxept",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/bankaxept"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/barcode": {
      "abstract": [
        {
          "text": "A QR code to use for payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barcode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/barcode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkBarcode"
        }
      ],
      "role": "symbol",
      "title": "barcode",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/barcode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaire": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carteBancaire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaire",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkCarteBancaire"
        }
      ],
      "role": "symbol",
      "title": "carteBancaire",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/cartebancaire"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/cartesBancaires": {
      "abstract": [
        {
          "text": "A Cartes Bancaires payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cartesBancaires"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/cartesBancaires",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkCartesBancaires"
        }
      ],
      "role": "symbol",
      "title": "cartesBancaires",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/cartesbancaires"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/chinaUnionPay": {
      "abstract": [
        {
          "text": "A China Union Pay payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chinaUnionPay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/chinaUnionPay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkChinaUnionPay"
        }
      ],
      "role": "symbol",
      "title": "chinaUnionPay",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/chinaunionpay"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/dankort": {
      "abstract": [
        {
          "text": "The Dankort payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dankort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/dankort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkDankort"
        }
      ],
      "role": "symbol",
      "title": "dankort",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/dankort"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/discover": {
      "abstract": [
        {
          "text": "A Discover payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discover"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/discover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkDiscover"
        }
      ],
      "role": "symbol",
      "title": "discover",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/discover"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/eftpos": {
      "abstract": [
        {
          "text": "The electronic funds transfer at point of sale (EFTPOS) payment method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eftpos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/eftpos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkEftpos"
        }
      ],
      "role": "symbol",
      "title": "eftpos",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/eftpos"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/electron": {
      "abstract": [
        {
          "text": "An Electron debit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "electron"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/electron",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkElectron"
        }
      ],
      "role": "symbol",
      "title": "electron",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/electron"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/elo": {
      "abstract": [
        {
          "text": "The Elo payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/elo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkElo"
        }
      ],
      "role": "symbol",
      "title": "elo",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/elo"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/girocard": {
      "abstract": [
        {
          "text": "A Girocard payment method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "girocard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/girocard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkGirocard"
        }
      ],
      "role": "symbol",
      "title": "girocard",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/girocard"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/idCredit": {
      "abstract": [
        {
          "text": "An iD payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idCredit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/idCredit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkIDCredit"
        }
      ],
      "role": "symbol",
      "title": "idCredit",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/idcredit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/interac": {
      "abstract": [
        {
          "text": "The Interac payment method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interac"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/interac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkInterac"
        }
      ],
      "role": "symbol",
      "title": "interac",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/interac"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Payment-networks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/amex",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancomat",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancontact",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bankAxept",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/barcode",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaire",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/cartesBancaires",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/chinaUnionPay",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/dankort",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/eftpos",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/electron",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/elo",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/girocard",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/idCredit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/interac"
      ],
      "title": "Payment networks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentNetworkDiscover"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkDiscover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Payment-networks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/amex",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancomat",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancontact",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bankAxept",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/barcode",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaire",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/cartesBancaires",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/chinaUnionPay",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/dankort",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/eftpos",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/electron",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/elo",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/girocard",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/idCredit",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/interac"
              ],
              "title": "Payment networks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@PKPaymentNetwork",
                    "text": "PKPaymentNetwork"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKPaymentNetworkDiscover"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1girocard/title",
          "value": "PKPaymentNetworkGirocard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1girocard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkGirocard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1discover/title",
          "value": "PKPaymentNetworkDiscover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1discover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkDiscover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1cartesBancaires/title",
          "value": "PKPaymentNetworkCartesBancaires"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1cartesBancaires/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkCartesBancaires"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1interac/title",
          "value": "PKPaymentNetworkInterac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1interac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkInterac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1carteBancaire/title",
          "value": "PKPaymentNetworkCarteBancaire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1carteBancaire/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkCarteBancaire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork/title",
          "value": "PKPaymentNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1barcode/title",
          "value": "PKPaymentNetworkBarcode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1barcode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkBarcode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bancontact/title",
          "value": "PKPaymentNetworkBancontact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bancontact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkBancontact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1idCredit/title",
          "value": "PKPaymentNetworkIDCredit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1idCredit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkIDCredit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bankAxept/title",
          "value": "PKPaymentNetworkBankAxept"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bankAxept/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkBankAxept"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bancomat/title",
          "value": "PKPaymentNetworkBancomat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bancomat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkBancomat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1elo/title",
          "value": "PKPaymentNetworkElo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1elo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkElo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1electron/title",
          "value": "PKPaymentNetworkElectron"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1electron/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkElectron"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1amex/title",
          "value": "PKPaymentNetworkAmex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1amex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkAmex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1chinaUnionPay/title",
          "value": "PKPaymentNetworkChinaUnionPay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1chinaUnionPay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkChinaUnionPay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1eftpos/title",
          "value": "PKPaymentNetworkEftpos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1eftpos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkEftpos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1dankort/title",
          "value": "PKPaymentNetworkDankort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1dankort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkDankort"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentnetwork/discover"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentnetwork/discover"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
