{
  "abstract": [
    {
      "text": "The call directory extension isn’t enabled by the system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/extensionDisabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CXErrorCodeCallDirectoryManagerError@CXErrorCodeCallDirectoryManagerErrorExtensionDisabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "extensionDisabled"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXErrorCodeCallDirectoryManagerErrorExtensionDisabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CXErrorCodeCallDirectoryManagerError.Code.extensionDisabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "extensionDisabled"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct": {
      "abstract": [
        {
          "text": "Errors when interacting with a call directory manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes the CallKit framework returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/currentlyLoading": {
      "abstract": [
        {
          "text": "The call directory manager is loading the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentlyLoading"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/currentlyLoading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorCurrentlyLoading"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.currentlyLoading",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/currentlyloading"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/duplicateEntries": {
      "abstract": [
        {
          "text": "There are duplicate entries in the call directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateEntries"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/duplicateEntries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorDuplicateEntries"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.duplicateEntries",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/duplicateentries"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/entriesOutOfOrder": {
      "abstract": [
        {
          "text": "The entries in the call directory are out of order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entriesOutOfOrder"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/entriesOutOfOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorEntriesOutOfOrder"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.entriesOutOfOrder",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/entriesoutoforder"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/extensionDisabled": {
      "abstract": [
        {
          "text": "The call directory extension isn’t enabled by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionDisabled"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/extensionDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorExtensionDisabled"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.extensionDisabled",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/extensiondisabled"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/loadingInterrupted": {
      "abstract": [
        {
          "text": "The call directory manager was interrupted while loading the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadingInterrupted"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/loadingInterrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorLoadingInterrupted"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.loadingInterrupted",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/loadinginterrupted"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/maximumEntriesExceeded": {
      "abstract": [
        {
          "text": "There are too many entries in the call directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumEntriesExceeded"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/maximumEntriesExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorMaximumEntriesExceeded"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.maximumEntriesExceeded",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/maximumentriesexceeded"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/noExtensionFound": {
      "abstract": [
        {
          "text": "The call directory manager could not find a corresponding app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noExtensionFound"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/noExtensionFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorNoExtensionFound"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.noExtensionFound",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/noextensionfound"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unexpectedIncrementalRemoval": {
      "abstract": [
        {
          "text": "A request occurred before confirming incremental loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedIncrementalRemoval"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unexpectedIncrementalRemoval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorUnexpectedIncrementalRemoval"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.unexpectedIncrementalRemoval",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/unexpectedincrementalremoval"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.unknown",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unknown",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/noExtensionFound",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/currentlyLoading",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/loadingInterrupted",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/entriesOutOfOrder",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/duplicateEntries",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/maximumEntriesExceeded",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unexpectedIncrementalRemoval"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorExtensionDisabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorExtensionDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unknown",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/noExtensionFound",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/currentlyLoading",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/loadingInterrupted",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/entriesOutOfOrder",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/duplicateEntries",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/maximumEntriesExceeded",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unexpectedIncrementalRemoval"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CXErrorCodeCallDirectoryManagerErrorExtensionDisabled"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1duplicateEntries/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorDuplicateEntries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1duplicateEntries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorDuplicateEntries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1currentlyLoading/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorCurrentlyLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1currentlyLoading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorCurrentlyLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1maximumEntriesExceeded/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorMaximumEntriesExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1maximumEntriesExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorMaximumEntriesExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1unknown/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1entriesOutOfOrder/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorEntriesOutOfOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1entriesOutOfOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorEntriesOutOfOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1extensionDisabled/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorExtensionDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1extensionDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorExtensionDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/title",
          "value": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1noExtensionFound/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorNoExtensionFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1noExtensionFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorNoExtensionFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1loadingInterrupted/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorLoadingInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1loadingInterrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorLoadingInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1unexpectedIncrementalRemoval/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorUnexpectedIncrementalRemoval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1unexpectedIncrementalRemoval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorUnexpectedIncrementalRemoval"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/extensiondisabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/extensiondisabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
