{
  "abstract": [
    {
      "text": "Initializes the magnetic field to the specified set of values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField/init(field:accuracy:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So25CMCalibratedMagneticFielda5field8accuracyABSo010CMMagneticC0a_So0fC19CalibrationAccuracyVtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "field"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CMMagneticField",
        "text": "CMMagneticField"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "accuracy"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CMMagneticFieldCalibrationAccuracy",
        "text": "CMMagneticFieldCalibrationAccuracy"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(field:accuracy:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "field"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticField",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMMagneticField",
              "text": "CMMagneticField"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "accuracy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CMMagneticFieldCalibrationAccuracy",
              "text": "CMMagneticFieldCalibrationAccuracy"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField": {
      "abstract": [
        {
          "text": "Calibrated magnetic field data and an estimate of the accuracy of the calibration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMCalibratedMagneticField"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMCalibratedMagneticField"
        }
      ],
      "role": "symbol",
      "title": "CMCalibratedMagneticField",
      "type": "topic",
      "url": "/documentation/coremotion/cmcalibratedmagneticfield"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField/init()": {
      "abstract": [
        {
          "text": "Initializes the magnetic field to a set of default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/coremotion/cmcalibratedmagneticfield/init()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField/init(field:accuracy:)": {
      "abstract": [
        {
          "text": "Initializes the magnetic field to the specified set of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "field"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMMagneticField",
          "text": "CMMagneticField"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMMagneticFieldCalibrationAccuracy",
          "text": "CMMagneticFieldCalibrationAccuracy"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField/init(field:accuracy:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(field:accuracy:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmcalibratedmagneticfield/init(field:accuracy:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticField": {
      "abstract": [
        {
          "text": "A structure containing 3-axis magnetometer data",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMagneticField"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticField"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticField",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfield"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy": {
      "abstract": [
        {
          "text": "Indicates the calibration accuracy of a magnetic field estimate",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracy"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField/init()"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMCalibratedMagneticField/title",
          "value": "CMCalibratedMagneticField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMCalibratedMagneticField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMCalibratedMagneticField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMCalibratedMagneticField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMCalibratedMagneticField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy/title",
          "value": "CMMagneticFieldCalibrationAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticField/title",
          "value": "CMMagneticField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticField"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmcalibratedmagneticfield/init(field:accuracy:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
