{
  "abstract": [
    {
      "text": "An option that pauses playback and resumes at the beginning.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE",
        "doc://com.apple.phase/documentation/PHASE/PHASECullOption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtZero"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHASECullOption@PHASECullOptionSleepWakeAtZero",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sleepWakeAtZero"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASECullOptionSleepWakeAtZero"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHASECullOption.sleepWakeAtZero"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sleepWakeAtZero"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECullOption": {
      "abstract": [
        {
          "text": "The actions the engine takes when it culls sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASECullOption"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECullOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECullOption"
        }
      ],
      "role": "symbol",
      "title": "PHASECullOption",
      "type": "topic",
      "url": "/documentation/phase/phaseculloption"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECullOption/doNotCull": {
      "abstract": [
        {
          "text": "An option that indicates the framework takes no action to cull sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doNotCull"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECullOption/doNotCull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECullOptionDoNotCull"
        }
      ],
      "role": "symbol",
      "title": "PHASECullOption.doNotCull",
      "type": "topic",
      "url": "/documentation/phase/phaseculloption/donotcull"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtRandomOffset": {
      "abstract": [
        {
          "text": "An option that pauses playback and resumes at a random position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepWakeAtRandomOffset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtRandomOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECullOptionSleepWakeAtRandomOffset"
        }
      ],
      "role": "symbol",
      "title": "PHASECullOption.sleepWakeAtRandomOffset",
      "type": "topic",
      "url": "/documentation/phase/phaseculloption/sleepwakeatrandomoffset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtRealtimeOffset": {
      "abstract": [
        {
          "text": "An option that pauses playback and resumes where it left off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepWakeAtRealtimeOffset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtRealtimeOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECullOptionSleepWakeAtRealtimeOffset"
        }
      ],
      "role": "symbol",
      "title": "PHASECullOption.sleepWakeAtRealtimeOffset",
      "type": "topic",
      "url": "/documentation/phase/phaseculloption/sleepwakeatrealtimeoffset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtZero": {
      "abstract": [
        {
          "text": "An option that pauses playback and resumes at the beginning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepWakeAtZero"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtZero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECullOptionSleepWakeAtZero"
        }
      ],
      "role": "symbol",
      "title": "PHASECullOption.sleepWakeAtZero",
      "type": "topic",
      "url": "/documentation/phase/phaseculloption/sleepwakeatzero"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECullOption/terminate": {
      "abstract": [
        {
          "text": "An option that culls sound by stopping playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "terminate"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECullOption/terminate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECullOptionTerminate"
        }
      ],
      "role": "symbol",
      "title": "PHASECullOption.terminate",
      "type": "topic",
      "url": "/documentation/phase/phaseculloption/terminate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASECullOption/terminate",
        "doc://com.apple.phase/documentation/PHASE/PHASECullOption/doNotCull",
        "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtRealtimeOffset",
        "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtRandomOffset"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASECullOptionSleepWakeAtZero"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECullOptionSleepWakeAtZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE",
                "doc://com.apple.phase/documentation/PHASE/PHASECullOption"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASECullOption/terminate",
                "doc://com.apple.phase/documentation/PHASE/PHASECullOption/doNotCull",
                "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtRealtimeOffset",
                "doc://com.apple.phase/documentation/PHASE/PHASECullOption/sleepWakeAtRandomOffset"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHASECullOptionSleepWakeAtZero"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption~1sleepWakeAtZero/title",
          "value": "PHASECullOptionSleepWakeAtZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption~1sleepWakeAtZero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECullOptionSleepWakeAtZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption~1sleepWakeAtRandomOffset/title",
          "value": "PHASECullOptionSleepWakeAtRandomOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption~1sleepWakeAtRandomOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECullOptionSleepWakeAtRandomOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption/title",
          "value": "PHASECullOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECullOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECullOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption~1terminate/title",
          "value": "PHASECullOptionTerminate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption~1terminate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECullOptionTerminate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption~1doNotCull/title",
          "value": "PHASECullOptionDoNotCull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption~1doNotCull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECullOptionDoNotCull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption~1sleepWakeAtRealtimeOffset/title",
          "value": "PHASECullOptionSleepWakeAtRealtimeOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECullOption~1sleepWakeAtRealtimeOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECullOptionSleepWakeAtRealtimeOffset"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phaseculloption/sleepwakeatzero"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phaseculloption/sleepwakeatzero"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
