{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDidBeginDocumentFind"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification","identifier":"doc://com.externally.resolved.symbol/s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDidBeginDocumentFind"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)PDFDocumentDelegate(im)documentDidBeginDocumentFind:","title":"documentDidBeginDocumentFind(_:)","platforms":[{"introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"10.10","unavailable":false,"beta":false,"deprecated":false,"name":"macOS"},{"introducedAt":"9.0","unavailable":false,"beta":false,"deprecated":false,"name":"tvOS"},{"introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"}],"navigatorTitle":[{"kind":"identifier","text":"documentDidBeginDocumentFind:"}],"modules":[{"name":"PDFKit"}],"roleHeading":"Instance Method"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/pdfkit/pdfdocumentdelegate/documentdidbegindocumentfind(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/pdfkit/pdfdocumentdelegate/documentdidbegindocumentfind(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate"]]},"abstract":[{"type":"text","text":"Called when the "},{"type":"codeVoice","code":"PDFDocumentDidBeginFindNotification"},{"type":"text","text":" notification is posted."}],"seeAlsoSections":[{"generated":true,"title":"Getting Document Search Notifications","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)"],"anchor":"Getting-Document-Search-Notifications"}],"references":{"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)":{"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdocumentdelegate/didmatchstring(_:)","abstract":[{"type":"text","text":"Called for every match found during a find operation."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didMatchString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PDFSelection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PDFSelection"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)","title":"didMatchString(_:)","role":"symbol","navigatorTitle":[{"text":"didMatchString:","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)":{"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdocumentdelegate/documentdidbegindocumentfind(_:)","abstract":[{"text":"Called when the ","type":"text"},{"code":"PDFDocumentDidBeginFindNotification","type":"codeVoice"},{"text":" notification is posted.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidBeginDocumentFind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)","title":"documentDidBeginDocumentFind(_:)","role":"symbol","navigatorTitle":[{"text":"documentDidBeginDocumentFind:","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)":{"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdocumentdelegate/documentdidbeginpagefind(_:)","abstract":[{"type":"text","text":"Called when the "},{"type":"codeVoice","code":"PDFDocumentDidBeginPageFindNotification"},{"text":" notification is posted.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidBeginPageFind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)","title":"documentDidBeginPageFind(_:)","role":"symbol","navigatorTitle":[{"text":"documentDidBeginPageFind:","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)":{"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidEndPageFind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentDidEndPageFind:","kind":"identifier"}],"kind":"symbol","title":"documentDidEndPageFind(_:)","role":"symbol","abstract":[{"type":"text","text":"Called when the "},{"type":"codeVoice","code":"PDFDocumentDidEndPageFindNotification"},{"text":" notification is posted.","type":"text"}],"type":"topic","url":"/documentation/pdfkit/pdfdocumentdelegate/documentdidendpagefind(_:)"},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.externally.resolved.symbol/s:10Foundation12NotificationV":{"type":"topic","kind":"symbol","url":"/documentation/foundation/notification","abstract":[{"text":"A container for information broadcast through a notification center to all registered observers. ","type":"text"}],"fragments":[{"kind":"text","text":"struct "},{"text":"Notification","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation12NotificationV","title":"Notification","role":"symbol"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)":{"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdocumentdelegate/documentdidfindmatch(_:)","abstract":[{"text":"Called when the ","type":"text"},{"code":"PDFDocumentDidFindMatchNotification","type":"codeVoice"},{"text":" notification is posted.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidFindMatch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)","title":"documentDidFindMatch(_:)","role":"symbol","navigatorTitle":[{"text":"documentDidFindMatch:","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)":{"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdocumentdelegate/documentdidenddocumentfind(_:)","abstract":[{"type":"text","text":"Called when the "},{"type":"codeVoice","code":"PDFDocumentDidEndFindNotification"},{"type":"text","text":" notification is posted."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidEndDocumentFind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)","title":"documentDidEndDocumentFind(_:)","role":"symbol","navigatorTitle":[{"text":"documentDidEndDocumentFind:","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate":{"title":"PDFDocumentDelegate","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate","navigatorTitle":[{"text":"PDFDocumentDelegate","kind":"identifier"}],"url":"/documentation/pdfkit/pdfdocumentdelegate","role":"symbol","abstract":[{"text":"The delegate for the ","type":"text"},{"code":"PDFDocument","type":"codeVoice"},{"text":" object.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFDocumentDelegate","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"11.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"11.0"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"11.0"},{"beta":false,"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.4"},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"documentDidBeginDocumentFind:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentDidBeginDocumentFind:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Getting Document Search Notifications","generated":true,"identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)"],"anchor":"Getting-Document-Search-Notifications"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentDidBeginDocumentFind:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","text":"NSNotification"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"notification"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1didMatchString(_:)/title","value":"didMatchString:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1didMatchString(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"didMatchString:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginDocumentFind(_:)/title","value":"documentDidBeginDocumentFind:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginDocumentFind(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentDidBeginDocumentFind:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginPageFind(_:)/title","value":"documentDidBeginPageFind:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginPageFind(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentDidBeginPageFind:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndPageFind(_:)/title","value":"documentDidEndPageFind:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndPageFind(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentDidEndPageFind:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidFindMatch(_:)/title","value":"documentDidFindMatch:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidFindMatch(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentDidFindMatch:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndDocumentFind(_:)/title","value":"documentDidEndDocumentFind:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndDocumentFind(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentDidEndDocumentFind:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate/title","value":"PDFDocumentDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate/fragments","value":[{"text":"PDFDocumentDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate/navigatorTitle","value":[{"kind":"identifier","text":"PDFDocumentDelegate"}],"op":"replace"}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}