{"sections":[],"kind":"symbol","variants":[{"paths":["/documentation/pdfkit/pdfdocumentdelegate/documentdidenddocumentfind(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/pdfkit/pdfdocumentdelegate/documentdidenddocumentfind(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)"},"metadata":{"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidEndDocumentFind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[{"deprecated":false,"name":"iOS","introducedAt":"8.0","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"8.0","beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"8.0","beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"introducedAt":"10.10","beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"introducedAt":"9.0","beta":false,"unavailable":false},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"}],"title":"documentDidEndDocumentFind(_:)","externalID":"c:objc(pl)PDFDocumentDelegate(im)documentDidEndDocumentFind:","navigatorTitle":[{"text":"documentDidEndDocumentFind:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"PDFKit"}]},"abstract":[{"type":"text","text":"Called when the "},{"code":"PDFDocumentDidEndFindNotification","type":"codeVoice"},{"type":"text","text":" notification is posted."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDidEndDocumentFind"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"notification"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation12NotificationV","identifier":"doc://com.externally.resolved.symbol/s:10Foundation12NotificationV","kind":"typeIdentifier","text":"Notification"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)"],"anchor":"Getting-Document-Search-Notifications","title":"Getting Document Search Notifications"}],"references":{"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate":{"title":"PDFDocumentDelegate","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate","navigatorTitle":[{"text":"PDFDocumentDelegate","kind":"identifier"}],"url":"/documentation/pdfkit/pdfdocumentdelegate","role":"symbol","abstract":[{"text":"The delegate for the ","type":"text"},{"code":"PDFDocument","type":"codeVoice"},{"text":" object.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFDocumentDelegate","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)":{"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdocumentdelegate/documentdidenddocumentfind(_:)","abstract":[{"type":"text","text":"Called when the "},{"type":"codeVoice","code":"PDFDocumentDidEndFindNotification"},{"type":"text","text":" notification is posted."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidEndDocumentFind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)","title":"documentDidEndDocumentFind(_:)","role":"symbol","navigatorTitle":[{"text":"documentDidEndDocumentFind:","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)":{"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdocumentdelegate/documentdidfindmatch(_:)","abstract":[{"text":"Called when the ","type":"text"},{"code":"PDFDocumentDidFindMatchNotification","type":"codeVoice"},{"text":" notification is posted.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidFindMatch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)","title":"documentDidFindMatch(_:)","role":"symbol","navigatorTitle":[{"text":"documentDidFindMatch:","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)":{"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdocumentdelegate/documentdidbegindocumentfind(_:)","abstract":[{"text":"Called when the ","type":"text"},{"code":"PDFDocumentDidBeginFindNotification","type":"codeVoice"},{"text":" notification is posted.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidBeginDocumentFind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)","title":"documentDidBeginDocumentFind(_:)","role":"symbol","navigatorTitle":[{"text":"documentDidBeginDocumentFind:","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)":{"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidEndPageFind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentDidEndPageFind:","kind":"identifier"}],"kind":"symbol","title":"documentDidEndPageFind(_:)","role":"symbol","abstract":[{"type":"text","text":"Called when the "},{"type":"codeVoice","code":"PDFDocumentDidEndPageFindNotification"},{"text":" notification is posted.","type":"text"}],"type":"topic","url":"/documentation/pdfkit/pdfdocumentdelegate/documentdidendpagefind(_:)"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)":{"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdocumentdelegate/documentdidbeginpagefind(_:)","abstract":[{"type":"text","text":"Called when the "},{"type":"codeVoice","code":"PDFDocumentDidBeginPageFindNotification"},{"text":" notification is posted.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidBeginPageFind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)","title":"documentDidBeginPageFind(_:)","role":"symbol","navigatorTitle":[{"text":"documentDidBeginPageFind:","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)":{"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdocumentdelegate/didmatchstring(_:)","abstract":[{"type":"text","text":"Called for every match found during a find operation."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didMatchString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PDFSelection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PDFSelection"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)","title":"didMatchString(_:)","role":"symbol","navigatorTitle":[{"text":"didMatchString:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:10Foundation12NotificationV":{"type":"topic","kind":"symbol","url":"/documentation/foundation/notification","abstract":[{"text":"A container for information broadcast through a notification center to all registered observers. ","type":"text"}],"fragments":[{"kind":"text","text":"struct "},{"text":"Notification","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation12NotificationV","title":"Notification","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"iOS","introducedAt":"11.0","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","introducedAt":"11.0","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"11.0","beta":false,"unavailable":false},{"introducedAt":"10.4","deprecated":false,"unavailable":false,"beta":false,"name":"macOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"path":"/metadata/title","value":"documentDidEndDocumentFind:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentDidEndDocumentFind:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Getting Document Search Notifications","anchor":"Getting-Document-Search-Notifications","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"documentDidEndDocumentFind:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":" *) ","kind":"text"},{"text":"notification","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"PDFDocumentDelegate","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate/title"},{"value":[{"kind":"identifier","text":"PDFDocumentDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate/fragments"},{"value":[{"text":"PDFDocumentDelegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate/navigatorTitle"},{"value":"documentDidEndDocumentFind:","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndDocumentFind(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"documentDidEndDocumentFind:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndDocumentFind(_:)/fragments"},{"value":"documentDidFindMatch:","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidFindMatch(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"documentDidFindMatch:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidFindMatch(_:)/fragments"},{"value":"documentDidBeginDocumentFind:","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginDocumentFind(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"documentDidBeginDocumentFind:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginDocumentFind(_:)/fragments"},{"value":"documentDidEndPageFind:","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndPageFind(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentDidEndPageFind:"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndPageFind(_:)/fragments"},{"value":"documentDidBeginPageFind:","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginPageFind(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"documentDidBeginPageFind:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginPageFind(_:)/fragments"},{"value":"didMatchString:","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1didMatchString(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMatchString:"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1didMatchString(_:)/fragments"}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}