{
  "abstract": [
    {
      "text": "The middle finger’s distal interphalangeal (DIP) joint.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation",
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleDIP"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@VNHumanHandPoseObservationJointNameMiddleDIP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "middleDIP"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
        "text": "VNHumanHandPoseObservation"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
        "text": "JointName"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNHumanHandPoseObservationJointNameMiddleDIP"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "middleDIP"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "middleDIP"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
              "text": "VNHumanHandPoseObservation"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
              "text": "JointName"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation": {
      "abstract": [
        {
          "text": "An observation that provides the hand points the analysis recognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanHandPoseObservation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName": {
      "abstract": [
        {
          "text": "The supported joint names for the hand pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "role": "symbol",
      "title": "VNHumanHandPoseObservation.JointName",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation/jointname"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleDIP": {
      "abstract": [
        {
          "text": "The middle finger’s distal interphalangeal (DIP) joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "middleDIP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
          "text": "VNHumanHandPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleDIP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservationJointNameMiddleDIP"
        }
      ],
      "role": "symbol",
      "title": "middleDIP",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation/jointname/middledip"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleMCP": {
      "abstract": [
        {
          "text": "The middle finger’s metacarpophalangeal (MCP) joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "middleMCP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
          "text": "VNHumanHandPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleMCP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservationJointNameMiddleMCP"
        }
      ],
      "role": "symbol",
      "title": "middleMCP",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation/jointname/middlemcp"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middlePIP": {
      "abstract": [
        {
          "text": "The middle finger’s proximal interphalangeal (PIP) joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "middlePIP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
          "text": "VNHumanHandPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middlePIP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservationJointNameMiddlePIP"
        }
      ],
      "role": "symbol",
      "title": "middlePIP",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation/jointname/middlepip"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleTip": {
      "abstract": [
        {
          "text": "The tip of the middle finger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "middleTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
          "text": "VNHumanHandPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservationJointNameMiddleTip"
        }
      ],
      "role": "symbol",
      "title": "middleTip",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation/jointname/middletip"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Middle",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleTip",
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middlePIP",
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleMCP"
      ],
      "title": "Middle"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNHumanHandPoseObservationJointNameMiddleDIP"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointNameMiddleDIP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Middle",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleTip",
                "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middlePIP",
                "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/middleMCP"
              ],
              "title": "Middle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
                    "text": "VNHumanHandPoseObservationJointName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNHumanHandPoseObservationJointNameMiddleDIP"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName/title",
          "value": "VNHumanHandPoseObservationJointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1middlePIP/title",
          "value": "VNHumanHandPoseObservationJointNameMiddlePIP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1middlePIP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointNameMiddlePIP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1middleTip/title",
          "value": "VNHumanHandPoseObservationJointNameMiddleTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1middleTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointNameMiddleTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1middleDIP/title",
          "value": "VNHumanHandPoseObservationJointNameMiddleDIP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1middleDIP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointNameMiddleDIP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1middleMCP/title",
          "value": "VNHumanHandPoseObservationJointNameMiddleMCP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1middleMCP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointNameMiddleMCP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation/title",
          "value": "VNHumanHandPoseObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnhumanhandposeobservation/jointname/middledip"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnhumanhandposeobservation/jointname/middledip"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
