{
  "abstract": [
    {
      "text": "The tip of the thumb.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation",
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbTip"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@VNHumanHandPoseObservationJointNameThumbTip",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "thumbTip"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
        "text": "VNHumanHandPoseObservation"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
        "text": "JointName"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNHumanHandPoseObservationJointNameThumbTip"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "thumbTip"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "thumbTip"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
              "text": "VNHumanHandPoseObservation"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
              "text": "JointName"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation": {
      "abstract": [
        {
          "text": "An observation that provides the hand points the analysis recognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanHandPoseObservation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName": {
      "abstract": [
        {
          "text": "The supported joint names for the hand pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "role": "symbol",
      "title": "VNHumanHandPoseObservation.JointName",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation/jointname"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbCMC": {
      "abstract": [
        {
          "text": "The thumb’s carpometacarpal (CMC) joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbCMC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
          "text": "VNHumanHandPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbCMC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservationJointNameThumbCMC"
        }
      ],
      "role": "symbol",
      "title": "thumbCMC",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation/jointname/thumbcmc"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbIP": {
      "abstract": [
        {
          "text": "The thumb’s interphalangeal (IP) joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbIP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
          "text": "VNHumanHandPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbIP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservationJointNameThumbIP"
        }
      ],
      "role": "symbol",
      "title": "thumbIP",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation/jointname/thumbip"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbMP": {
      "abstract": [
        {
          "text": "The thumb’s metacarpophalangeal (MP) joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbMP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
          "text": "VNHumanHandPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbMP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservationJointNameThumbMP"
        }
      ],
      "role": "symbol",
      "title": "thumbMP",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation/jointname/thumbmp"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbTip": {
      "abstract": [
        {
          "text": "The tip of the thumb.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanHandPoseObservation",
          "text": "VNHumanHandPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservationJointNameThumbTip"
        }
      ],
      "role": "symbol",
      "title": "thumbTip",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation/jointname/thumbtip"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Thumb",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbIP",
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbMP",
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbCMC"
      ],
      "title": "Thumb"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNHumanHandPoseObservationJointNameThumbTip"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointNameThumbTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Thumb",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbIP",
                "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbMP",
                "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName/thumbCMC"
              ],
              "title": "Thumb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation/JointName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VNHumanHandPoseObservationJointName",
                    "text": "VNHumanHandPoseObservationJointName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNHumanHandPoseObservationJointNameThumbTip"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1thumbMP/title",
          "value": "VNHumanHandPoseObservationJointNameThumbMP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1thumbMP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointNameThumbMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1thumbIP/title",
          "value": "VNHumanHandPoseObservationJointNameThumbIP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1thumbIP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointNameThumbIP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1thumbTip/title",
          "value": "VNHumanHandPoseObservationJointNameThumbTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1thumbTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointNameThumbTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation/title",
          "value": "VNHumanHandPoseObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1thumbCMC/title",
          "value": "VNHumanHandPoseObservationJointNameThumbCMC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName~1thumbCMC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointNameThumbCMC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName/title",
          "value": "VNHumanHandPoseObservationJointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation~1JointName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservationJointName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnhumanhandposeobservation/jointname/thumbtip"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnhumanhandposeobservation/jointname/thumbtip"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
