{
  "abstract": [
    {
      "text": "Dark brown to black skin that never burns and tans profusely.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/VI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKFitzpatrickSkinType@HKFitzpatrickSkinTypeVI",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VI"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKFitzpatrickSkinTypeVI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKFitzpatrickSkinType.VI"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VI"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType": {
      "abstract": [
        {
          "text": "Categories representing the user’s skin type based on the Fitzpatrick scale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinType"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/I": {
      "abstract": [
        {
          "text": "Pale white skin that always burns easily in the sun and never tans.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "I"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/I",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeI"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType.I",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype/i"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/II": {
      "abstract": [
        {
          "text": "White skin that burns easily and tans minimally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "II"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/II",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeII"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType.II",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype/ii"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/III": {
      "abstract": [
        {
          "text": "White to light brown skin that burns moderately and tans uniformly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "III"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/III",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeIII"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType.III",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype/iii"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/IV": {
      "abstract": [
        {
          "text": "Beige-olive, lightly tanned skin that burns minimally and tans moderately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IV"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/IV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeIV"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType.IV",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype/iv"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/V": {
      "abstract": [
        {
          "text": "Brown skin that rarely burns and tans profusely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "V"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/V",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeV"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType.V",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype/v"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/VI": {
      "abstract": [
        {
          "text": "Dark brown to black skin that never burns and tans profusely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VI"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/VI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeVI"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType.VI",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype/vi"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/notSet": {
      "abstract": [
        {
          "text": "Either the user’s skin type is not set, or the user has not granted your app permission to read the skin type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSet"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/notSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeNotSet"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType.notSet",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype/notset"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/notSet",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/I",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/II",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/III",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/IV",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/V"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKFitzpatrickSkinTypeVI"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeVI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/notSet",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/I",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/II",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/III",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/IV",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType/V"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKFitzpatrickSkinTypeVI"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/title",
          "value": "HKFitzpatrickSkinType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1V/title",
          "value": "HKFitzpatrickSkinTypeV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1V/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1VI/title",
          "value": "HKFitzpatrickSkinTypeVI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1VI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeVI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1I/title",
          "value": "HKFitzpatrickSkinTypeI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1I/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1IV/title",
          "value": "HKFitzpatrickSkinTypeIV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1IV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeIV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1notSet/title",
          "value": "HKFitzpatrickSkinTypeNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1notSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1II/title",
          "value": "HKFitzpatrickSkinTypeII"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1II/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeII"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1III/title",
          "value": "HKFitzpatrickSkinTypeIII"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType~1III/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeIII"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkfitzpatrickskintype/vi"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkfitzpatrickskintype/vi"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
