{
  "abstract": [
    {
      "text": "Requests a custom curve value for the current progress value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animation(_:valueForProgress:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAnimationDelegate(im)animation:valueForProgress:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "animation"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSAnimation",
        "text": "NSAnimation"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "valueForProgress"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSAnimation",
        "text": "NSAnimation"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSAnimationProgress",
        "text": "Progress"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "animation:valueForProgress:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "animation(_:valueForProgress:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "nonisolated"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "animation"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "animation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSAnimation",
              "text": "NSAnimation"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "valueForProgress"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "progress"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSAnimation",
              "text": "NSAnimation"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Progress",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAnimationProgress",
              "text": "Progress"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "code": "NSAnimation",
                  "type": "codeVoice"
                },
                {
                  "text": " object that is running.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "animation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "float",
                  "type": "codeVoice"
                },
                {
                  "text": " value (typed as ",
                  "type": "text"
                },
                {
                  "code": "NSAnimationProgress",
                  "type": "codeVoice"
                },
                {
                  "text": ") that indicates a progress mark of ",
                  "type": "text"
                },
                {
                  "code": "animation",
                  "type": "codeVoice"
                },
                {
                  "text": ". This value is always between 0.0 and 1.0.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "progress"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "float",
              "type": "codeVoice"
            },
            {
              "text": " value representing a custom curve.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The delegate can compute and return a custom curve value for the given progress value.  If the delegate does not implement this method, ",
              "type": "text"
            },
            {
              "code": "NSAnimation",
              "type": "codeVoice"
            },
            {
              "text": " computes the current curve value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The animation:valueForProgress: message is sent to the delegate when an ",
              "type": "text"
            },
            {
              "code": "NSAnimation",
              "type": "codeVoice"
            },
            {
              "text": " object receives a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/currentValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " message. The value the delegate returns is used as the value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/currentValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "; if there is no delegate, or it doesn’t implement animation:valueForProgress:, ",
              "type": "text"
            },
            {
              "code": "NSAnimation",
              "type": "codeVoice"
            },
            {
              "text": " computes and returns the current value. ",
              "type": "text"
            },
            {
              "code": "NSAnimation",
              "type": "codeVoice"
            },
            {
              "text": " does not invoke ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/currentValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "itself, but subclasses might.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "See the description of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/currentValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimation": {
      "abstract": [
        {
          "text": "An object that manages the timing and progress of animations in the user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAnimation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAnimation"
        }
      ],
      "role": "symbol",
      "title": "NSAnimation",
      "type": "topic",
      "url": "/documentation/appkit/nsanimation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Progress": {
      "abstract": [
        {
          "text": "The animation progress, as a floating-point number between ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Progress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Progress"
        }
      ],
      "role": "symbol",
      "title": "NSAnimation.Progress",
      "type": "topic",
      "url": "/documentation/appkit/nsanimation/progress"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimation/currentValue": {
      "abstract": [
        {
          "text": "The current value of the animation effect, based on the current progress",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/currentValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentValue"
        }
      ],
      "role": "symbol",
      "title": "currentValue",
      "type": "topic",
      "url": "/documentation/appkit/nsanimation/currentvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods implemented by delegates of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAnimationDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAnimationDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSAnimationDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsanimationdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animation(_:valueForProgress:)": {
      "abstract": [
        {
          "text": "Requests a custom curve value for the current progress value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAnimation",
          "text": "NSAnimation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "valueForProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAnimation",
          "text": "NSAnimation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAnimationProgress",
          "text": "Progress"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animation(_:valueForProgress:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animation:valueForProgress:"
        }
      ],
      "role": "symbol",
      "title": "animation(_:valueForProgress:)",
      "type": "topic",
      "url": "/documentation/appkit/nsanimationdelegate/animation(_:valueforprogress:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationDidEnd(_:)": {
      "abstract": [
        {
          "text": "Sent to the delegate when the specified animation completes its run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animationDidEnd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAnimation",
          "text": "NSAnimation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationDidEnd(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animationDidEnd:"
        }
      ],
      "role": "symbol",
      "title": "animationDidEnd(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsanimationdelegate/animationdidend(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationDidStop(_:)": {
      "abstract": [
        {
          "text": "Sent to the delegate when the specified animation is stopped before it completes its run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animationDidStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAnimation",
          "text": "NSAnimation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationDidStop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animationDidStop:"
        }
      ],
      "role": "symbol",
      "title": "animationDidStop(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsanimationdelegate/animationdidstop(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationShouldStart(_:)": {
      "abstract": [
        {
          "text": "Sent to the delegate just after an animation is started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animationShouldStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAnimation",
          "text": "NSAnimation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationShouldStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animationShouldStart:"
        }
      ],
      "role": "symbol",
      "title": "animationShouldStart(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsanimationdelegate/animationshouldstart(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAnimation/currentValue"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Controlling-and-Monitoring-an-Animation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationDidEnd(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationDidStop(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationShouldStart(_:)"
      ],
      "title": "Controlling and Monitoring an Animation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "animation:valueForProgress:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "animation:valueForProgress:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAnimation/currentValue"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Controlling-and-Monitoring-an-Animation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationDidEnd(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationDidStop(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSAnimationDelegate/animationShouldStart(_:)"
              ],
              "title": "Controlling and Monitoring an Animation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "animation:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSAnimation",
                    "text": "NSAnimation"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "animation"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "valueForProgress:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Progress",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSAnimationProgress",
                    "text": "NSAnimationProgress"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "progress"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "code": "NSAnimation",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object that is running.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "animation"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "code": "float",
                        "type": "codeVoice"
                      },
                      {
                        "text": " value (typed as ",
                        "type": "text"
                      },
                      {
                        "code": "NSAnimationProgress",
                        "type": "codeVoice"
                      },
                      {
                        "text": ") that indicates a progress mark of ",
                        "type": "text"
                      },
                      {
                        "code": "animation",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". This value is always between 0.0 and 1.0.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "progress"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A ",
                    "type": "text"
                  },
                  {
                    "code": "float",
                    "type": "codeVoice"
                  },
                  {
                    "text": " value representing a custom curve.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1currentValue/title",
          "value": "currentValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1currentValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate~1animationDidEnd(_:)/title",
          "value": "animationDidEnd:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate~1animationDidEnd(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "animationDidEnd:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation/title",
          "value": "NSAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate~1animation(_:valueForProgress:)/title",
          "value": "animation:valueForProgress:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate~1animation(_:valueForProgress:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "animation:valueForProgress:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate~1animationDidStop(_:)/title",
          "value": "animationDidStop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate~1animationDidStop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "animationDidStop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate~1animationShouldStart(_:)/title",
          "value": "animationShouldStart:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate~1animationShouldStart(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "animationShouldStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1Progress/title",
          "value": "NSAnimationProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1Progress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1Progress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate/title",
          "value": "NSAnimationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsanimationdelegate/animation(_:valueforprogress:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsanimationdelegate/animation(_:valueforprogress:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
