{
  "abstract": [
    {
      "text": "An invocation option that specifies that the test starts taking measurements when the ",
      "type": "text"
    },
    {
      "code": "startMeasuring()",
      "type": "codeVoice"
    },
    {
      "text": " function is called.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions",
        "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct/manuallyStart"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCTMeasurementInvocationOptions@XCTMeasurementInvocationManuallyStart",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "manuallyStart"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
        "text": "XCTMeasureOptions"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@XCTMeasurementInvocationOptions",
        "text": "InvocationOptions"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTMeasurementInvocationManuallyStart"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "manuallyStart"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "manuallyStart"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
              "text": "XCTMeasureOptions"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@XCTMeasurementInvocationOptions",
              "text": "InvocationOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions": {
      "abstract": [
        {
          "text": "Options to control the gathering of performance measurements during tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTMeasureOptions"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTMeasureOptions"
        }
      ],
      "role": "symbol",
      "title": "XCTMeasureOptions",
      "type": "topic",
      "url": "/documentation/xctest/xctmeasureoptions"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct": {
      "abstract": [
        {
          "text": "Test measurement options that control how measurement starts and stops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InvocationOptions"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InvocationOptions"
        }
      ],
      "role": "symbol",
      "title": "XCTMeasureOptions.InvocationOptions",
      "type": "topic",
      "url": "/documentation/xctest/xctmeasureoptions/invocationoptions-swift.struct"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct/manuallyStart": {
      "abstract": [
        {
          "text": "An invocation option that specifies that the test starts taking measurements when the ",
          "type": "text"
        },
        {
          "code": "startMeasuring()",
          "type": "codeVoice"
        },
        {
          "text": " function is called.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manuallyStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
          "text": "XCTMeasureOptions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTMeasurementInvocationOptions",
          "text": "InvocationOptions"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct/manuallyStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTMeasurementInvocationManuallyStart"
        }
      ],
      "role": "symbol",
      "title": "manuallyStart",
      "type": "topic",
      "url": "/documentation/xctest/xctmeasureoptions/invocationoptions-swift.struct/manuallystart"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct/manuallyStop": {
      "abstract": [
        {
          "text": "An invocation option that specifies that the test stops taking measurements when the ",
          "type": "text"
        },
        {
          "code": "stopMeasuring()",
          "type": "codeVoice"
        },
        {
          "text": " function is called.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manuallyStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
          "text": "XCTMeasureOptions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTMeasurementInvocationOptions",
          "text": "InvocationOptions"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct/manuallyStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTMeasurementInvocationManuallyStop"
        }
      ],
      "role": "symbol",
      "title": "manuallyStop",
      "type": "topic",
      "url": "/documentation/xctest/xctmeasureoptions/invocationoptions-swift.struct/manuallystop"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measurement-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct/manuallyStop"
      ],
      "title": "Measurement Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTMeasurementInvocationManuallyStart"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasurementInvocationManuallyStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measurement-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct/manuallyStop"
              ],
              "title": "Measurement Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "XCTMeasurementInvocationManuallyStart"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions/title",
          "value": "XCTMeasureOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasureOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasureOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions~1InvocationOptions-swift.struct~1manuallyStop/title",
          "value": "XCTMeasurementInvocationManuallyStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions~1InvocationOptions-swift.struct~1manuallyStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasurementInvocationManuallyStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions~1InvocationOptions-swift.struct/title",
          "value": "XCTMeasurementInvocationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions~1InvocationOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasurementInvocationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions~1InvocationOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasurementInvocationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions~1InvocationOptions-swift.struct~1manuallyStart/title",
          "value": "XCTMeasurementInvocationManuallyStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions~1InvocationOptions-swift.struct~1manuallyStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasurementInvocationManuallyStart"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctmeasureoptions/invocationoptions-swift.struct/manuallystart"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctmeasureoptions/invocationoptions-swift.struct/manuallystart"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
