{
  "abstract": [
    {
      "text": "A flag that indicates that the rate scalar is valid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/rateScalarValid"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioTimeStampFlags@kAudioTimeStampRateScalarValid",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rateScalarValid"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AudioTimeStampFlags",
        "text": "AudioTimeStampFlags"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioTimeStampRateScalarValid"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "rateScalarValid"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rateScalarValid"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AudioTimeStampFlags",
              "text": "AudioTimeStampFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags": {
      "abstract": [
        {
          "text": "A structure that represents flags for a timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioTimeStampFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioTimeStampFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestampflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/hostTimeValid": {
      "abstract": [
        {
          "text": "A flag that indicates that the host time is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostTimeValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioTimeStampFlags",
          "text": "AudioTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/hostTimeValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioTimeStampHostTimeValid"
        }
      ],
      "role": "symbol",
      "title": "hostTimeValid",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestampflags/hosttimevalid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/kAudioTimeStampNothingValid": {
      "abstract": [
        {
          "text": "A flag that indicates no fields are valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioTimeStampNothingValid"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/kAudioTimeStampNothingValid",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioTimeStampNothingValid",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestampflags/kaudiotimestampnothingvalid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/rateScalarValid": {
      "abstract": [
        {
          "text": "A flag that indicates that the rate scalar is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rateScalarValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioTimeStampFlags",
          "text": "AudioTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/rateScalarValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioTimeStampRateScalarValid"
        }
      ],
      "role": "symbol",
      "title": "rateScalarValid",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestampflags/ratescalarvalid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/sampleHostTimeValid": {
      "abstract": [
        {
          "text": "A flag that indicates that the sample frame time and the host time are valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleHostTimeValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioTimeStampFlags",
          "text": "AudioTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/sampleHostTimeValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioTimeStampSampleHostTimeValid"
        }
      ],
      "role": "symbol",
      "title": "sampleHostTimeValid",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestampflags/samplehosttimevalid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/sampleTimeValid": {
      "abstract": [
        {
          "text": "A flag that indicates that the sample frame time is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleTimeValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioTimeStampFlags",
          "text": "AudioTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/sampleTimeValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioTimeStampSampleTimeValid"
        }
      ],
      "role": "symbol",
      "title": "sampleTimeValid",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestampflags/sampletimevalid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/smpteTimeValid": {
      "abstract": [
        {
          "text": "A flag that indicates that the SMPTE time is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smpteTimeValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioTimeStampFlags",
          "text": "AudioTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/smpteTimeValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioTimeStampSMPTETimeValid"
        }
      ],
      "role": "symbol",
      "title": "smpteTimeValid",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestampflags/smptetimevalid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/wordClockTimeValid": {
      "abstract": [
        {
          "text": "A flag that indicates that the word clock time is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wordClockTimeValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioTimeStampFlags",
          "text": "AudioTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/wordClockTimeValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioTimeStampWordClockTimeValid"
        }
      ],
      "role": "symbol",
      "title": "wordClockTimeValid",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestampflags/wordclocktimevalid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/hostTimeValid",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/sampleHostTimeValid",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/sampleTimeValid",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/smpteTimeValid",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/wordClockTimeValid"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioTimeStampRateScalarValid"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioTimeStampRateScalarValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/kAudioTimeStampNothingValid",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/hostTimeValid",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/sampleHostTimeValid",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/sampleTimeValid",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/smpteTimeValid",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags/wordClockTimeValid"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioTimeStampRateScalarValid"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1smpteTimeValid/title",
          "value": "kAudioTimeStampSMPTETimeValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1smpteTimeValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioTimeStampSMPTETimeValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1wordClockTimeValid/title",
          "value": "kAudioTimeStampWordClockTimeValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1wordClockTimeValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioTimeStampWordClockTimeValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1sampleTimeValid/title",
          "value": "kAudioTimeStampSampleTimeValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1sampleTimeValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioTimeStampSampleTimeValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1hostTimeValid/title",
          "value": "kAudioTimeStampHostTimeValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1hostTimeValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioTimeStampHostTimeValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1sampleHostTimeValid/title",
          "value": "kAudioTimeStampSampleHostTimeValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1sampleHostTimeValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioTimeStampSampleHostTimeValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1rateScalarValid/title",
          "value": "kAudioTimeStampRateScalarValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags~1rateScalarValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioTimeStampRateScalarValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags/title",
          "value": "AudioTimeStampFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioTimeStampFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioTimeStampFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audiotimestampflags/ratescalarvalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audiotimestampflags/ratescalarvalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
