{
  "abstract": [
    {
      "text": "An event that indicates a finished send operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didSendChanges"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CKSyncEngineEventType@CKSyncEngineEventTypeDidSendChanges",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "didSendChanges"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKSyncEngineEventTypeDidSendChanges"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CKSyncEngineEventType.didSendChanges"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didSendChanges"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType": {
      "abstract": [
        {
          "text": "Describes an event that occurs during a sync operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventType"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/accountChange": {
      "abstract": [
        {
          "text": "An event indicating a change to the device’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountChange"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/accountChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeAccountChange"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.accountChange",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/accountchange"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didFetchChanges": {
      "abstract": [
        {
          "text": "An event that indicates the database fetch is done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFetchChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didFetchChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeDidFetchChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.didFetchChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/didfetchchanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didFetchRecordZoneChanges": {
      "abstract": [
        {
          "text": "An event that indicates the record zone fetch is done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFetchRecordZoneChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didFetchRecordZoneChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeDidFetchRecordZoneChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.didFetchRecordZoneChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/didfetchrecordzonechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didSendChanges": {
      "abstract": [
        {
          "text": "An event that indicates a finished send operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didSendChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didSendChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeDidSendChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.didSendChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/didsendchanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/fetchedDatabaseChanges": {
      "abstract": [
        {
          "text": "An event indicating there are fetched database changes to process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchedDatabaseChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/fetchedDatabaseChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeFetchedDatabaseChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.fetchedDatabaseChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/fetcheddatabasechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/fetchedRecordZoneChanges": {
      "abstract": [
        {
          "text": "An event indicating there are fetched record zone changes to process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchedRecordZoneChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/fetchedRecordZoneChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeFetchedRecordZoneChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.fetchedRecordZoneChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/fetchedrecordzonechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/sentDatabaseChanges": {
      "abstract": [
        {
          "text": "An event indicating a sent batch of database changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentDatabaseChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/sentDatabaseChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeSentDatabaseChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.sentDatabaseChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/sentdatabasechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/sentRecordZoneChanges": {
      "abstract": [
        {
          "text": "An event indicating a sent batch of record zone changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentRecordZoneChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/sentRecordZoneChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeSentRecordZoneChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.sentRecordZoneChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/sentrecordzonechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/stateUpdate": {
      "abstract": [
        {
          "text": "An event indicating an update to the sync engine’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateUpdate"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/stateUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeStateUpdate"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.stateUpdate",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/stateupdate"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willFetchChanges": {
      "abstract": [
        {
          "text": "An event indicating an imminent database fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willFetchChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willFetchChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeWillFetchChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.willFetchChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/willfetchchanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willFetchRecordZoneChanges": {
      "abstract": [
        {
          "text": "An event indicating an imminent fetch of changes in a record zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willFetchRecordZoneChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willFetchRecordZoneChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeWillFetchRecordZoneChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.willFetchRecordZoneChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/willfetchrecordzonechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willSendChanges": {
      "abstract": [
        {
          "text": "An event indicating an imminent send of local changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willSendChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willSendChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventTypeWillSendChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType.willSendChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype/willsendchanges"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Event-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/stateUpdate",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/accountChange",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/fetchedDatabaseChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/fetchedRecordZoneChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/sentDatabaseChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/sentRecordZoneChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willFetchChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willFetchRecordZoneChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didFetchRecordZoneChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didFetchChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willSendChanges"
      ],
      "title": "Event types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKSyncEngineEventTypeDidSendChanges"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeDidSendChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Event-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/stateUpdate",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/accountChange",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/fetchedDatabaseChanges",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/fetchedRecordZoneChanges",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/sentDatabaseChanges",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/sentRecordZoneChanges",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willFetchChanges",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willFetchRecordZoneChanges",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didFetchRecordZoneChanges",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/didFetchChanges",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType/willSendChanges"
              ],
              "title": "Event types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CKSyncEngineEventTypeDidSendChanges"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1willFetchChanges/title",
          "value": "CKSyncEngineEventTypeWillFetchChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1willFetchChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeWillFetchChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1sentRecordZoneChanges/title",
          "value": "CKSyncEngineEventTypeSentRecordZoneChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1sentRecordZoneChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeSentRecordZoneChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1didSendChanges/title",
          "value": "CKSyncEngineEventTypeDidSendChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1didSendChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeDidSendChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1fetchedDatabaseChanges/title",
          "value": "CKSyncEngineEventTypeFetchedDatabaseChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1fetchedDatabaseChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeFetchedDatabaseChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1stateUpdate/title",
          "value": "CKSyncEngineEventTypeStateUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1stateUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeStateUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1accountChange/title",
          "value": "CKSyncEngineEventTypeAccountChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1accountChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeAccountChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1sentDatabaseChanges/title",
          "value": "CKSyncEngineEventTypeSentDatabaseChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1sentDatabaseChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeSentDatabaseChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1willSendChanges/title",
          "value": "CKSyncEngineEventTypeWillSendChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1willSendChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeWillSendChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1didFetchChanges/title",
          "value": "CKSyncEngineEventTypeDidFetchChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1didFetchChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeDidFetchChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1fetchedRecordZoneChanges/title",
          "value": "CKSyncEngineEventTypeFetchedRecordZoneChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1fetchedRecordZoneChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeFetchedRecordZoneChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1didFetchRecordZoneChanges/title",
          "value": "CKSyncEngineEventTypeDidFetchRecordZoneChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1didFetchRecordZoneChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeDidFetchRecordZoneChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1willFetchRecordZoneChanges/title",
          "value": "CKSyncEngineEventTypeWillFetchRecordZoneChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType~1willFetchRecordZoneChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventTypeWillFetchRecordZoneChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType/title",
          "value": "CKSyncEngineEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksyncengineeventtype/didsendchanges"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/cksyncengineeventtype/didsendchanges"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
