{
  "abstract": [
    {
      "text": "Dismisses the current configuration view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.social/documentation/Social",
        "doc://com.apple.social/documentation/Social/SLComposeServiceViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.social/documentation/Social/SLComposeServiceViewController/popConfigurationViewController()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SLComposeServiceViewController(im)popConfigurationViewController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "popConfigurationViewController"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Social"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "popConfigurationViewController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "popConfigurationViewController()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "popConfigurationViewController"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can call this method to dismiss the configuration view controller in response to a user action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.social/documentation/Social": {
      "abstract": [
        {
          "text": "Post content to supported social networking services, using standard system interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social",
      "kind": "symbol",
      "role": "collection",
      "title": "Social",
      "type": "topic",
      "url": "/documentation/social"
    },
    "doc://com.apple.social/documentation/Social/SLComposeServiceViewController": {
      "abstract": [
        {
          "text": "A view controller that you present from your share app extension, allowing the user to compose social media posts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLComposeServiceViewController"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeServiceViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeServiceViewController"
        }
      ],
      "role": "symbol",
      "title": "SLComposeServiceViewController",
      "type": "topic",
      "url": "/documentation/social/slcomposeserviceviewcontroller"
    },
    "doc://com.apple.social/documentation/Social/SLComposeServiceViewController/popConfigurationViewController()": {
      "abstract": [
        {
          "text": "Dismisses the current configuration view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popConfigurationViewController"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeServiceViewController/popConfigurationViewController()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popConfigurationViewController"
        }
      ],
      "role": "symbol",
      "title": "popConfigurationViewController()",
      "type": "topic",
      "url": "/documentation/social/slcomposeserviceviewcontroller/popconfigurationviewcontroller()"
    },
    "doc://com.apple.social/documentation/Social/SLComposeServiceViewController/pushConfigurationViewController(_:)": {
      "abstract": [
        {
          "text": "Presents a configuration view controller that lets the user configure the post.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushConfigurationViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeServiceViewController/pushConfigurationViewController(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pushConfigurationViewController:"
        }
      ],
      "role": "symbol",
      "title": "pushConfigurationViewController(_:)",
      "type": "topic",
      "url": "/documentation/social/slcomposeserviceviewcontroller/pushconfigurationviewcontroller(_:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presenting-the-View-Controller",
      "generated": true,
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLComposeServiceViewController/pushConfigurationViewController(_:)"
      ],
      "title": "Presenting the View Controller"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "popConfigurationViewController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popConfigurationViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.social/documentation/Social",
                "doc://com.apple.social/documentation/Social/SLComposeServiceViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presenting-the-View-Controller",
              "generated": true,
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLComposeServiceViewController/pushConfigurationViewController(_:)"
              ],
              "title": "Presenting the View Controller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "popConfigurationViewController"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeServiceViewController/title",
          "value": "SLComposeServiceViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeServiceViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeServiceViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeServiceViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeServiceViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeServiceViewController~1popConfigurationViewController()/title",
          "value": "popConfigurationViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeServiceViewController~1popConfigurationViewController()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popConfigurationViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeServiceViewController~1pushConfigurationViewController(_:)/title",
          "value": "pushConfigurationViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeServiceViewController~1pushConfigurationViewController(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pushConfigurationViewController:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/social/slcomposeserviceviewcontroller/popconfigurationviewcontroller()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/social/slcomposeserviceviewcontroller/popconfigurationviewcontroller()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
