{
  "abstract": [
    {
      "text": "Tells the delegate the user updated the shortcut.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/IntentsUI",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INUIEditVoiceShortcutViewControllerDelegate(im)editVoiceShortcutViewController:didUpdateVoiceShortcut:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "editVoiceShortcutViewController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
        "text": "INUIEditVoiceShortcutViewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didUpdate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INVoiceShortcut",
        "text": "INVoiceShortcut"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "error"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?)"
      }
    ],
    "modules": [
      {
        "name": "IntentsUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "editVoiceShortcutViewController(_:didUpdate:error:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
              "text": "INUIEditVoiceShortcutViewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didUpdate"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "voiceShortcut"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INVoiceShortcut",
              "text": "INVoiceShortcut"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The view controller calling this method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "controller"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The updated shortcut; otherwise, ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " when an error occurred updating the shortcut.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "voiceShortcut"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A error object when an error occurred updating the shortcut; otherwise, ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system calls this method after the user re-records the invocation phrase for the shortcut. If your app displays the phrase, the app should update its screen to show the new phrase by retrieving the phrase text from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut/invocationPhrase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property on voiceShortcut.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut": {
      "abstract": [
        {
          "text": "A shortcut the user added to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVoiceShortcut"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVoiceShortcut"
        }
      ],
      "role": "symbol",
      "title": "INVoiceShortcut",
      "type": "topic",
      "url": "/documentation/intents/invoiceshortcut"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut/invocationPhrase": {
      "abstract": [
        {
          "text": "The phrase the user speaks to invoke the shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invocationPhrase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut/invocationPhrase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invocationPhrase"
        }
      ],
      "role": "symbol",
      "title": "invocationPhrase",
      "type": "topic",
      "url": "/documentation/intents/invoiceshortcut/invocationphrase"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI": {
      "abstract": [
        {
          "text": "Customize content in the interface for Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IntentsUI",
      "type": "topic",
      "url": "/documentation/intentsui"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController": {
      "abstract": [
        {
          "text": "A view controller that lets the user edit or remove an existing shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewController"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewController"
        }
      ],
      "role": "symbol",
      "title": "INUIEditVoiceShortcutViewController",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontroller"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate": {
      "abstract": [
        {
          "text": "The protocol an object implements to receive notifications from the view controller that edits or removes a shortcut in Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "INUIEditVoiceShortcutViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)": {
      "abstract": [
        {
          "text": "Tells the delegate the user deleted the shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
          "text": "INUIEditVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDeleteVoiceShortcutWithIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontroller(_:diddeletevoiceshortcutwithidentifier:)"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)": {
      "abstract": [
        {
          "text": "Tells the delegate the user updated the shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
          "text": "INUIEditVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INVoiceShortcut",
          "text": "INVoiceShortcut"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "editVoiceShortcutViewController(_:didUpdate:error:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontroller(_:didupdate:error:)"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Shortcut-Changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)"
      ],
      "title": "Handling Shortcut Changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/IntentsUI",
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Shortcut-Changes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)"
              ],
              "title": "Handling Shortcut Changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "editVoiceShortcutViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
                    "text": "INUIEditVoiceShortcutViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "controller"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didUpdateVoiceShortcut:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INVoiceShortcut",
                    "text": "INVoiceShortcut"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "voiceShortcut"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The view controller calling this method.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "controller"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The updated shortcut; otherwise, ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " when an error occurred updating the shortcut.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "voiceShortcut"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A error object when an error occurred updating the shortcut; otherwise, ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)/title",
          "value": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut~1invocationPhrase/title",
          "value": "invocationPhrase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut~1invocationPhrase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "invocationPhrase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController/title",
          "value": "INUIEditVoiceShortcutViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/title",
          "value": "INVoiceShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didUpdate:error:)/title",
          "value": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didUpdate:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate/title",
          "value": "INUIEditVoiceShortcutViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewControllerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontroller(_:didupdate:error:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontroller(_:didupdate:error:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
