{
  "abstract": [
    {
      "text": "Tells the delegate the user deleted the shortcut.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/IntentsUI",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INUIEditVoiceShortcutViewControllerDelegate(im)editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "editVoiceShortcutViewController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
        "text": "INUIEditVoiceShortcutViewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didDeleteVoiceShortcutWithIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4UUIDV",
        "text": "UUID"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IntentsUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
              "text": "INUIEditVoiceShortcutViewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didDeleteVoiceShortcutWithIdentifier"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "deletedVoiceShortcutIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4UUIDV",
              "text": "UUID"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The view controller calling this method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "controller"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identifier of the shortcut that the user deleted.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "deletedVoiceShortcutIdentifier"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After the user deletes a shortcut, the shortcut is no longer available to Siri. Your app should reflect this change by displaying an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the view for the action. The button lets the user know the action doesn’t have a shortcut, and provides the option to add one.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI": {
      "abstract": [
        {
          "text": "Customize content in the interface for Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IntentsUI",
      "type": "topic",
      "url": "/documentation/intentsui"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton": {
      "abstract": [
        {
          "text": "A button that allows the user to add or edit a shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButton"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButton"
        }
      ],
      "role": "symbol",
      "title": "INUIAddVoiceShortcutButton",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutbutton"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController": {
      "abstract": [
        {
          "text": "A view controller that lets the user edit or remove an existing shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewController"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewController"
        }
      ],
      "role": "symbol",
      "title": "INUIEditVoiceShortcutViewController",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontroller"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate": {
      "abstract": [
        {
          "text": "The protocol an object implements to receive notifications from the view controller that edits or removes a shortcut in Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "INUIEditVoiceShortcutViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)": {
      "abstract": [
        {
          "text": "Tells the delegate the user deleted the shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
          "text": "INUIEditVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDeleteVoiceShortcutWithIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontroller(_:diddeletevoiceshortcutwithidentifier:)"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)": {
      "abstract": [
        {
          "text": "Tells the delegate the user updated the shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
          "text": "INUIEditVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INVoiceShortcut",
          "text": "INVoiceShortcut"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "editVoiceShortcutViewController(_:didUpdate:error:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontroller(_:didupdate:error:)"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV": {
      "abstract": [
        {
          "text": "A universally unique value to identify types, interfaces, and other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UUID",
      "type": "topic",
      "url": "/documentation/foundation/uuid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Shortcut-Changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)"
      ],
      "title": "Handling Shortcut Changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/IntentsUI",
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Shortcut-Changes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)"
              ],
              "title": "Handling Shortcut Changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "editVoiceShortcutViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
                    "text": "INUIEditVoiceShortcutViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "controller"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didDeleteVoiceShortcutWithIdentifier:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSUUID",
                    "text": "NSUUID"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "deletedVoiceShortcutIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The view controller calling this method.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "controller"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The identifier of the shortcut that the user deleted.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "deletedVoiceShortcutIdentifier"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController/title",
          "value": "INUIEditVoiceShortcutViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didUpdate:error:)/title",
          "value": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didUpdate:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)/title",
          "value": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/title",
          "value": "INUIAddVoiceShortcutButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate/title",
          "value": "INUIEditVoiceShortcutViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewControllerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontroller(_:diddeletevoiceshortcutwithidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontroller(_:diddeletevoiceshortcutwithidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
