{
  "abstract": [
    {
      "text": "The subadministrative area (such as a county or other region) in a postal address.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts",
        "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/subAdministrativeArea"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNMutablePostalAddress(py)subAdministrativeArea",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "subAdministrativeArea"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "subAdministrativeArea"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "subAdministrativeArea"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "subAdministrativeArea"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress": {
      "abstract": [
        {
          "text": "A mutable representation of the postal address for a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNMutablePostalAddress"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNMutablePostalAddress"
        }
      ],
      "role": "symbol",
      "title": "CNMutablePostalAddress",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablepostaladdress"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/city": {
      "abstract": [
        {
          "text": "The city name of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "city"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/city",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "city"
        }
      ],
      "role": "symbol",
      "title": "city",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablepostaladdress/city"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/country": {
      "abstract": [
        {
          "text": "The country or region name of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "country"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/country",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "country"
        }
      ],
      "role": "symbol",
      "title": "country",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablepostaladdress/country"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/isoCountryCode": {
      "abstract": [
        {
          "text": "The ISO country code, using the ISO 3166-1 alpha-2 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isoCountryCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/isoCountryCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ISOCountryCode"
        }
      ],
      "role": "symbol",
      "title": "isoCountryCode",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablepostaladdress/isocountrycode"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/postalCode": {
      "abstract": [
        {
          "text": "The postal code of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/postalCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postalCode"
        }
      ],
      "role": "symbol",
      "title": "postalCode",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablepostaladdress/postalcode"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/state": {
      "abstract": [
        {
          "text": "The state name of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/state",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablepostaladdress/state"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/street": {
      "abstract": [
        {
          "text": "The street name of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "street"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/street",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "street"
        }
      ],
      "role": "symbol",
      "title": "street",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablepostaladdress/street"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/subAdministrativeArea": {
      "abstract": [
        {
          "text": "The subadministrative area (such as a county or other region) in a postal address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subAdministrativeArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/subAdministrativeArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subAdministrativeArea"
        }
      ],
      "role": "symbol",
      "title": "subAdministrativeArea",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablepostaladdress/subadministrativearea"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/subLocality": {
      "abstract": [
        {
          "text": "Additional information associated with the location, typically defined at the city or town level, in a postal address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subLocality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/subLocality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subLocality"
        }
      ],
      "role": "symbol",
      "title": "subLocality",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablepostaladdress/sublocality"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modifying-the-Parts-of-a-Postal-Address",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/street",
        "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/city",
        "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/state",
        "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/postalCode",
        "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/country",
        "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/isoCountryCode",
        "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/subLocality"
      ],
      "title": "Modifying the Parts of a Postal Address"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "subAdministrativeArea"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subAdministrativeArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts",
                "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Modifying-the-Parts-of-a-Postal-Address",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/street",
                "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/city",
                "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/state",
                "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/postalCode",
                "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/country",
                "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/isoCountryCode",
                "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress/subLocality"
              ],
              "title": "Modifying the Parts of a Postal Address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "subAdministrativeArea"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "subAdministrativeArea"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1city/title",
          "value": "city"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1city/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "city"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1subAdministrativeArea/title",
          "value": "subAdministrativeArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1subAdministrativeArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subAdministrativeArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1subLocality/title",
          "value": "subLocality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1subLocality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subLocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1postalCode/title",
          "value": "postalCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1postalCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postalCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1country/title",
          "value": "country"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1country/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "country"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress/title",
          "value": "CNMutablePostalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNMutablePostalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNMutablePostalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1state/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1state/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1isoCountryCode/title",
          "value": "ISOCountryCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1isoCountryCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ISOCountryCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1street/title",
          "value": "street"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress~1street/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "street"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnmutablepostaladdress/subadministrativearea"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnmutablepostaladdress/subadministrativearea"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
