{
  "abstract": [
    {
      "text": "Sets the cancellation handler block for the dispatch source with the specified quality-of-service class and work item options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(qos:flags:handler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Dispatch",
    "externalID": "s:So18OS_dispatch_sourceP8DispatchE16setCancelHandler3qos5flags7handleryAC0D3QoSV_AC0D13WorkItemFlagsVyyXLSgtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setCancelHandler"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "qos"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:8Dispatch0A3QoSV",
        "text": "DispatchQoS"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "flags"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:8Dispatch0A13WorkItemFlagsV",
        "text": "DispatchWorkItemFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "handler"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "Self"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So18OS_dispatch_sourceP8DispatchE0D13SourceHandlera",
        "text": "DispatchSourceHandler"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setCancelHandler(qos:flags:handler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setCancelHandler"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "qos"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:8Dispatch0A3QoSV",
              "text": "DispatchQoS"
            },
            {
              "kind": "text",
              "text": " = .unspecified, "
            },
            {
              "kind": "externalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItemFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:8Dispatch0A13WorkItemFlagsV",
              "text": "DispatchWorkItemFlags"
            },
            {
              "kind": "text",
              "text": " = [], "
            },
            {
              "kind": "externalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "Self"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/DispatchSourceHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So18OS_dispatch_sourceP8DispatchE0D13SourceHandlera",
              "text": "DispatchSourceHandler"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The quality-of-service to apply to the handler block.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "qos"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Configuration flags for the work item. For a list of possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItemFlags",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The event handler block to submit to the source’s target queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "handler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The cancellation handler (if specified) is submitted to the source’s target queue in response to a call to a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/cancel()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method once the system has released all references to the source’s underlying handle and the source’s event handler block has returned.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To safely close a file descriptor or destroy a Mach port, a cancellation handler is required for that descriptor or port. Closing the descriptor or port before the cancellation handler runs can result in a race condition. If a new descriptor is allocated with the same value as the recently closed descriptor while the source’s event handler is still running, the event handler may read/write data using the wrong descriptor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS": {
      "abstract": [
        {
          "text": "The quality of service, or the execution priority, to apply to tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchQoS"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchQoS"
        }
      ],
      "role": "symbol",
      "title": "DispatchQoS",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqos"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol": {
      "abstract": [
        {
          "text": "Defines a common set of properties and methods that are shared with all dispatch source types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceProtocol",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/DispatchSourceHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceHandler"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/DispatchSourceHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceHandler"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceProtocol.DispatchSourceHandler",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/dispatchsourcehandler"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/cancel()": {
      "abstract": [
        {
          "text": "Asynchronously cancels the dispatch source, preventing any further invocation of its event handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/cancel()",
      "kind": "symbol",
      "role": "symbol",
      "title": "cancel()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/cancel()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/isCancelled": {
      "abstract": [
        {
          "text": "Returns a Boolean indicating whether the given dispatch source has been canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/isCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isCancelled",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/iscancelled"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(handler:)": {
      "abstract": [
        {
          "text": "Sets the cancellation handler block for the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCancelHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A8WorkItemC",
          "text": "DispatchWorkItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setCancelHandler(handler:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/setcancelhandler(handler:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(qos:flags:handler:)": {
      "abstract": [
        {
          "text": "Sets the cancellation handler block for the dispatch source with the specified quality-of-service class and work item options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCancelHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "qos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV",
          "text": "DispatchQoS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A13WorkItemFlagsV",
          "text": "DispatchWorkItemFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18OS_dispatch_sourceP8DispatchE0D13SourceHandlera",
          "text": "DispatchSourceHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(qos:flags:handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setCancelHandler(qos:flags:handler:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/setcancelhandler(qos:flags:handler:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItemFlags": {
      "abstract": [
        {
          "text": "A set of behaviors for a work item, such as its quality-of-service class and whether to create a barrier or spawn a new detached thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchWorkItemFlags"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItemFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchWorkItemFlags"
        }
      ],
      "role": "symbol",
      "title": "DispatchWorkItemFlags",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchworkitemflags"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Canceling-a-Dispatch-Source",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/cancel()",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/isCancelled",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(handler:)"
      ],
      "title": "Canceling a Dispatch Source"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/title",
          "value": "OS_dispatch_source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatchsourceprotocol/setcancelhandler(qos:flags:handler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
