{
  "abstract": [
    {
      "text": "An enumeration to denote body text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/body"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHProjectTextElementType@PHProjectTextElementTypeBody",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "body"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHProjectTextElementTypeBody"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHProjectTextElement.ElementType.body"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "body"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement": {
      "abstract": [
        {
          "text": "An element that represents text within project section content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectTextElement"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTextElement"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTextElement",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttextelement"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType": {
      "abstract": [
        {
          "text": "An enumeration of the type of text element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTextElement.ElementType",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttextelement/elementtype"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/body": {
      "abstract": [
        {
          "text": "An enumeration to denote body text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "body"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/body",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTextElementTypeBody"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTextElement.ElementType.body",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttextelement/elementtype/body"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/subtitle": {
      "abstract": [
        {
          "text": "An enumeration to denote subtitle text in the header view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitle"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/subtitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTextElementTypeSubtitle"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTextElement.ElementType.subtitle",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttextelement/elementtype/subtitle"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/title": {
      "abstract": [
        {
          "text": "An enumeration to denote title text in the header view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTextElementTypeTitle"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTextElement.ElementType.title",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttextelement/elementtype/title"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types-of-Text-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/title",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/subtitle"
      ],
      "title": "Types of Text Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHProjectTextElementTypeBody"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTextElementTypeBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/PhotosUI",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Types-of-Text-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/title",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement/ElementType/subtitle"
              ],
              "title": "Types of Text Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHProjectTextElementTypeBody"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement~1ElementType~1title/title",
          "value": "PHProjectTextElementTypeTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement~1ElementType~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTextElementTypeTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement~1ElementType/title",
          "value": "PHProjectTextElementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement~1ElementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTextElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement~1ElementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTextElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement~1ElementType~1body/title",
          "value": "PHProjectTextElementTypeBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement~1ElementType~1body/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTextElementTypeBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement~1ElementType~1subtitle/title",
          "value": "PHProjectTextElementTypeSubtitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement~1ElementType~1subtitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTextElementTypeSubtitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement/title",
          "value": "PHProjectTextElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTextElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTextElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phprojecttextelement/elementtype/body"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui/phprojecttextelement/elementtype/body"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
