{
  "abstract": [
    {
      "text": "The directions a user can pan (or move) a map displayed on the CarPlay screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CarPlay",
    "externalID": "c:@E@CPPanDirection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PanDirection"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PanDirection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CPMapTemplate.PanDirection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PanDirection"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate": {
      "abstract": [
        {
          "text": "A template that displays a navigation overlay that your app draws on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection": {
      "abstract": [
        {
          "text": "The directions a user can pan (or move) a map displayed on the CarPlay screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PanDirection"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplate.PanDirection",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/down": {
      "abstract": [
        {
          "text": "The user panned the map downward.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPanDirectionDown"
        }
      ],
      "role": "symbol",
      "title": "down",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection/down"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initializes a pan direction using the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection/init(rawvalue:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/left": {
      "abstract": [
        {
          "text": "The user panned the map to the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPanDirectionLeft"
        }
      ],
      "role": "symbol",
      "title": "left",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection/left"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/right": {
      "abstract": [
        {
          "text": "The user panned the map to the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPanDirectionRight"
        }
      ],
      "role": "symbol",
      "title": "right",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection/right"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/up": {
      "abstract": [
        {
          "text": "The user panned the map upward.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPanDirectionUp"
        }
      ],
      "role": "symbol",
      "title": "up",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection/up"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the pan gesture ended with the specified velocity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didEndPanGestureWithVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:didEndPanGestureWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:didEndPanGestureWithVelocity:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:didendpangesturewithvelocity:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the pan gesture changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdatePanGestureWithTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:didUpdatePanGestureWithTranslation:velocity:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:didupdatepangesturewithtranslation:velocity:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user is starting to pan the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "panBeganWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:panBeganWithDirection:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:panBeganWith:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panbeganwith:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user stopped panning the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "panEndedWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:panEndedWithDirection:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:panEndedWith:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panendedwith:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user is panning in a certain direction on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "panWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:panWithDirection:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:panWith:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panwith:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the pan gesture has started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateDidBeginPanGesture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateDidBeginPanGesture:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateDidBeginPanGesture(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatedidbeginpangesture(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the panning interface is no longer visible on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateDidDismissPanningInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateDidDismissPanningInterface:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateDidDismissPanningInterface(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatediddismisspanninginterface(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the panning interface is visible on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateDidShowPanningInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateDidShowPanningInterface:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateDidShowPanningInterface(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatedidshowpanninginterface(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the panning interface will disappear from the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateWillDismissPanningInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateWillDismissPanningInterface:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateWillDismissPanningInterface(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatewilldismisspanninginterface(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPPanDirection/CPPanDirectionNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CPPanDirectionNone"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPanDirection/CPPanDirectionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "CPPanDirectionNone",
      "type": "topic",
      "url": "/documentation/carplay/cppandirection/cppandirectionnone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Panning-the-Map",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)"
      ],
      "title": "Panning the Map"
    }
  ],
  "topicSections": [
    {
      "anchor": "Pan-Directions",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/down",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/left",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/right",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/up"
      ],
      "title": "Pan Directions"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPPanDirection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Pan-Directions",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPPanDirection/CPPanDirectionNone",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/down",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/left",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/right",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/up"
              ],
              "title": "Pan Directions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Panning-the-Map",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)"
              ],
              "title": "Panning the Map"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPPanDirection"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidShowPanningInterface(_:)/title",
          "value": "mapTemplateDidShowPanningInterface:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidShowPanningInterface(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateDidShowPanningInterface:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/title",
          "value": "CPPanDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panEndedWith:)/title",
          "value": "mapTemplate:panEndedWithDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panEndedWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:panEndedWithDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panWith:)/title",
          "value": "mapTemplate:panWithDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:panWithDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateWillDismissPanningInterface(_:)/title",
          "value": "mapTemplateWillDismissPanningInterface:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateWillDismissPanningInterface(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateWillDismissPanningInterface:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/title",
          "value": "CPMapTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidBeginPanGesture(_:)/title",
          "value": "mapTemplateDidBeginPanGesture:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidBeginPanGesture(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateDidBeginPanGesture:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didEndPanGestureWithVelocity:)/title",
          "value": "mapTemplate:didEndPanGestureWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didEndPanGestureWithVelocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:didEndPanGestureWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1left/title",
          "value": "CPPanDirectionLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirectionLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1up/title",
          "value": "CPPanDirectionUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirectionUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panBeganWith:)/title",
          "value": "mapTemplate:panBeganWithDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panBeganWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:panBeganWithDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidDismissPanningInterface(_:)/title",
          "value": "mapTemplateDidDismissPanningInterface:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidDismissPanningInterface(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateDidDismissPanningInterface:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1down/title",
          "value": "CPPanDirectionDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirectionDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)/title",
          "value": "mapTemplate:didUpdatePanGestureWithTranslation:velocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:didUpdatePanGestureWithTranslation:velocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1right/title",
          "value": "CPPanDirectionRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirectionRight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpmaptemplate/pandirection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpmaptemplate/pandirection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
