{
  "abstract": [
    {
      "text": "Displays the previews for a collection of trips, with a single selected trip.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showTripPreviews(_:selectedTrip:textConfiguration:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPMapTemplate(im)showTripPreviews:selectedTrip:textConfiguration:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "showTripPreviews"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPTrip",
        "text": "CPTrip"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "selectedTrip"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPTrip",
        "text": "CPTrip"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "textConfiguration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPTripPreviewTextConfiguration",
        "text": "CPTripPreviewTextConfiguration"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "showTripPreviews:selectedTrip:textConfiguration:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "showTripPreviews(_:selectedTrip:textConfiguration:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "showTripPreviews"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tripPreviews"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrip",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPTrip",
              "text": "CPTrip"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "selectedTrip"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrip",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPTrip",
              "text": "CPTrip"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "textConfiguration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTripPreviewTextConfiguration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPTripPreviewTextConfiguration",
              "text": "CPTripPreviewTextConfiguration"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of trips to preview.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tripPreviews"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The trip to select when CarPlay presents the list of trip previews.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "selectedTrip"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A configuration object that contains the various titles a trip preview button can display.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "textConfiguration"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to display upcoming trips or multiple trip options, such as search results. Trip previews can appear over an active navigation session. Provide an array of up to twelve ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrip",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects to preview. If the array contains more objects, CarPlay displays only the first twelve.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The trip you want to select must be a member of the ",
              "type": "text"
            },
            {
              "code": "tripPreviews",
              "type": "codeVoice"
            },
            {
              "text": " array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate": {
      "abstract": [
        {
          "text": "A template that displays a navigation overlay that your app draws on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/hideTripPreviews()": {
      "abstract": [
        {
          "text": "Hides the display of trip previews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hideTripPreviews"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/hideTripPreviews()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hideTripPreviews"
        }
      ],
      "role": "symbol",
      "title": "hideTripPreviews()",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/hidetrippreviews()"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showRouteChoicesPreview(for:textConfiguration:)": {
      "abstract": [
        {
          "text": "Displays the route choices for a single trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showRouteChoicesPreview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTrip",
          "text": "CPTrip"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "textConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTripPreviewTextConfiguration",
          "text": "CPTripPreviewTextConfiguration"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showRouteChoicesPreview(for:textConfiguration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showRouteChoicesPreviewForTrip:textConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "showRouteChoicesPreview(for:textConfiguration:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/showroutechoicespreview(for:textconfiguration:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showTripPreviews(_:selectedTrip:textConfiguration:)": {
      "abstract": [
        {
          "text": "Displays the previews for a collection of trips, with a single selected trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showTripPreviews"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTrip",
          "text": "CPTrip"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "selectedTrip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTrip",
          "text": "CPTrip"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "textConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTripPreviewTextConfiguration",
          "text": "CPTripPreviewTextConfiguration"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showTripPreviews(_:selectedTrip:textConfiguration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showTripPreviews:selectedTrip:textConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "showTripPreviews(_:selectedTrip:textConfiguration:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/showtrippreviews(_:selectedtrip:textconfiguration:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showTripPreviews(_:textConfiguration:)": {
      "abstract": [
        {
          "text": "Displays the preview for one or more trips, and allows route selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showTripPreviews"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTrip",
          "text": "CPTrip"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "textConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTripPreviewTextConfiguration",
          "text": "CPTripPreviewTextConfiguration"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showTripPreviews(_:textConfiguration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showTripPreviews:textConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "showTripPreviews(_:textConfiguration:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/showtrippreviews(_:textconfiguration:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTrip": {
      "abstract": [
        {
          "text": "An object that represents a journey between an origin and a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTrip"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTrip"
        }
      ],
      "role": "symbol",
      "title": "CPTrip",
      "type": "topic",
      "url": "/documentation/carplay/cptrip"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTripPreviewTextConfiguration": {
      "abstract": [
        {
          "text": "A configuration object for changing the button titles on a trip preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTripPreviewTextConfiguration"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTripPreviewTextConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTripPreviewTextConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CPTripPreviewTextConfiguration",
      "type": "topic",
      "url": "/documentation/carplay/cptrippreviewtextconfiguration"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Displaying-Trip-Previews",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showTripPreviews(_:textConfiguration:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/hideTripPreviews()",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showRouteChoicesPreview(for:textConfiguration:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPTripPreviewTextConfiguration"
      ],
      "title": "Displaying Trip Previews"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "showTripPreviews:selectedTrip:textConfiguration:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showTripPreviews:selectedTrip:textConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Displaying-Trip-Previews",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showTripPreviews(_:textConfiguration:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/hideTripPreviews()",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/showRouteChoicesPreview(for:textConfiguration:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPTripPreviewTextConfiguration"
              ],
              "title": "Displaying Trip Previews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "showTripPreviews:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<CPTrip *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "tripPreviews"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "selectedTrip:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrip",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPTrip",
                    "text": "CPTrip"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "selectedTrip"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "textConfiguration:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTripPreviewTextConfiguration",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPTripPreviewTextConfiguration",
                    "text": "CPTripPreviewTextConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "textConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of trips to preview.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "tripPreviews"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The trip to select when CarPlay presents the list of trip previews.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "selectedTrip"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A configuration object that contains the various titles a trip preview button can display.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "textConfiguration"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1showRouteChoicesPreview(for:textConfiguration:)/title",
          "value": "showRouteChoicesPreviewForTrip:textConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1showRouteChoicesPreview(for:textConfiguration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showRouteChoicesPreviewForTrip:textConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1hideTripPreviews()/title",
          "value": "hideTripPreviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1hideTripPreviews()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hideTripPreviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/title",
          "value": "CPMapTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1showTripPreviews(_:selectedTrip:textConfiguration:)/title",
          "value": "showTripPreviews:selectedTrip:textConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1showTripPreviews(_:selectedTrip:textConfiguration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showTripPreviews:selectedTrip:textConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTripPreviewTextConfiguration/title",
          "value": "CPTripPreviewTextConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTripPreviewTextConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPreviewTextConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTripPreviewTextConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPreviewTextConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1showTripPreviews(_:textConfiguration:)/title",
          "value": "showTripPreviews:textConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1showTripPreviews(_:textConfiguration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showTripPreviews:textConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip/title",
          "value": "CPTrip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTrip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTrip"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpmaptemplate/showtrippreviews(_:selectedtrip:textconfiguration:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpmaptemplate/showtrippreviews(_:selectedtrip:textconfiguration:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
