{
  "abstract": [
    {
      "text": "Updates travel estimates, such as arrival time and the remaining time and distance for a trip.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/updateEstimates(_:for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPMapTemplate(im)updateTravelEstimates:forTrip:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "updateEstimates"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPTravelEstimates",
        "text": "CPTravelEstimates"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPTrip",
        "text": "CPTrip"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "updateTravelEstimates:forTrip:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "updateEstimates(_:for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "updateEstimates"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "estimates"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTravelEstimates",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPTravelEstimates",
              "text": "CPTravelEstimates"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "trip"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrip",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPTrip",
              "text": "CPTrip"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The updated travel estimates.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "estimates"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A trip preview or the active trip.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "trip"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The updated trip uses the default time-remaining color. To change the color, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/update(_:for:with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method instead of calling this method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate": {
      "abstract": [
        {
          "text": "A template that displays a navigation overlay that your app draws on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/tripEstimateStyle": {
      "abstract": [
        {
          "text": "The style that the map template uses when displaying trip estimates during active nagivation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tripEstimateStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPTripEstimateStyle",
          "text": "CPTripEstimateStyle"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/tripEstimateStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tripEstimateStyle"
        }
      ],
      "role": "symbol",
      "title": "tripEstimateStyle",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/tripestimatestyle"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/update(_:for:with:)": {
      "abstract": [
        {
          "text": "Updates travel estimates, such as arrival time and the remaining time and distance for a trip, with the specified time-remaining color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTravelEstimates",
          "text": "CPTravelEstimates"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTrip",
          "text": "CPTrip"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPTimeRemainingColor",
          "text": "CPTimeRemainingColor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/update(_:for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateTravelEstimates:forTrip:withTimeRemainingColor:"
        }
      ],
      "role": "symbol",
      "title": "update(_:for:with:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/update(_:for:with:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/updateEstimates(_:for:)": {
      "abstract": [
        {
          "text": "Updates travel estimates, such as arrival time and the remaining time and distance for a trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateEstimates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTravelEstimates",
          "text": "CPTravelEstimates"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTrip",
          "text": "CPTrip"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/updateEstimates(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateTravelEstimates:forTrip:"
        }
      ],
      "role": "symbol",
      "title": "updateEstimates(_:for:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/updateestimates(_:for:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor": {
      "abstract": [
        {
          "text": "The color the system uses when displaying the time remaining for a trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColor"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColor"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTravelEstimates": {
      "abstract": [
        {
          "text": "An object that describes the time and distance remaining for a maneuver in a navigation session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTravelEstimates"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTravelEstimates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTravelEstimates"
        }
      ],
      "role": "symbol",
      "title": "CPTravelEstimates",
      "type": "topic",
      "url": "/documentation/carplay/cptravelestimates"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTrip": {
      "abstract": [
        {
          "text": "An object that represents a journey between an origin and a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTrip"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTrip"
        }
      ],
      "role": "symbol",
      "title": "CPTrip",
      "type": "topic",
      "url": "/documentation/carplay/cptrip"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTripEstimateStyle": {
      "abstract": [
        {
          "text": "The set of display styles for trip estimates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTripEstimateStyle"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTripEstimateStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTripEstimateStyle"
        }
      ],
      "role": "symbol",
      "title": "CPTripEstimateStyle",
      "type": "topic",
      "url": "/documentation/carplay/cptripestimatestyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-Trip-Estimates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/update(_:for:with:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/tripEstimateStyle",
        "doc://com.apple.carplay/documentation/CarPlay/CPTripEstimateStyle"
      ],
      "title": "Providing Trip Estimates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "updateTravelEstimates:forTrip:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateTravelEstimates:forTrip:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-Trip-Estimates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/update(_:for:with:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/tripEstimateStyle",
                "doc://com.apple.carplay/documentation/CarPlay/CPTripEstimateStyle"
              ],
              "title": "Providing Trip Estimates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "updateTravelEstimates:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTravelEstimates",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPTravelEstimates",
                    "text": "CPTravelEstimates"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "estimates"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forTrip:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrip",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPTrip",
                    "text": "CPTrip"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "trip"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The updated travel estimates.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "estimates"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A trip preview or the active trip.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "trip"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1updateEstimates(_:for:)/title",
          "value": "updateTravelEstimates:forTrip:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1updateEstimates(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateTravelEstimates:forTrip:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip/title",
          "value": "CPTrip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTrip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTrip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1update(_:for:with:)/title",
          "value": "updateTravelEstimates:forTrip:withTimeRemainingColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1update(_:for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateTravelEstimates:forTrip:withTimeRemainingColor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTravelEstimates/title",
          "value": "CPTravelEstimates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTravelEstimates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTravelEstimates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTravelEstimates/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTravelEstimates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1tripEstimateStyle/title",
          "value": "tripEstimateStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1tripEstimateStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tripEstimateStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/title",
          "value": "CPMapTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor/title",
          "value": "CPTimeRemainingColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTripEstimateStyle/title",
          "value": "CPTripEstimateStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTripEstimateStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripEstimateStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTripEstimateStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripEstimateStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpmaptemplate/updateestimates(_:for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpmaptemplate/updateestimates(_:for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
