{
  "abstract": [
    {
      "text": "Adds an empty track to a composition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/addMutableTrack(withMediaType:preferredTrackID:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVMutableComposition(im)addMutableTrackWithMediaType:preferredTrackID:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "addMutableTrack"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withMediaType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMediaType",
        "text": "AVMediaType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "preferredTrackID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMPersistentTrackID",
        "text": "CMPersistentTrackID"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVMutableCompositionTrack",
        "text": "AVMutableCompositionTrack"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "addMutableTrackWithMediaType:preferredTrackID:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "addMutableTrack(withMediaType:preferredTrackID:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "addMutableTrack"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withMediaType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "mediaType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMediaType",
              "text": "AVMediaType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "preferredTrackID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMPersistentTrackID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMPersistentTrackID",
              "text": "CMPersistentTrackID"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCompositionTrack",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVMutableCompositionTrack",
              "text": "AVMutableCompositionTrack"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The media type of the new track.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mediaType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The preferred track ID for the new track. The system generates a unique ID if the value you specify isn’t available. If you don’t need to specify a preferred track ID, pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreMedia/kCMPersistentTrackID_Invalid",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", and the system generates an appropriate identifier.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "preferredTrackID"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new mutable composition track.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType": {
      "abstract": [
        {
          "text": "An identifier for various media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMediaType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaType"
        }
      ],
      "role": "symbol",
      "title": "AVMediaType",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediatype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition": {
      "abstract": [
        {
          "text": "An object that you use to create a new composition from existing assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableComposition"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableComposition"
        }
      ],
      "role": "symbol",
      "title": "AVMutableComposition",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecomposition"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/addMutableTrack(withMediaType:preferredTrackID:)": {
      "abstract": [
        {
          "text": "Adds an empty track to a composition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addMutableTrack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaType",
          "text": "AVMediaType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "preferredTrackID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPersistentTrackID",
          "text": "CMPersistentTrackID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMutableCompositionTrack",
          "text": "AVMutableCompositionTrack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/addMutableTrack(withMediaType:preferredTrackID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addMutableTrackWithMediaType:preferredTrackID:"
        }
      ],
      "role": "symbol",
      "title": "addMutableTrack(withMediaType:preferredTrackID:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecomposition/addmutabletrack(withmediatype:preferredtrackid:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/mutableTrack(compatibleWith:)": {
      "abstract": [
        {
          "text": "Returns a composition track into which you can insert any time range of the specified asset track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mutableTrack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "compatibleWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMutableCompositionTrack",
          "text": "AVMutableCompositionTrack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/mutableTrack(compatibleWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mutableTrackCompatibleWithTrack:"
        }
      ],
      "role": "symbol",
      "title": "mutableTrack(compatibleWith:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecomposition/mutabletrack(compatiblewith:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/removeTrack(_:)": {
      "abstract": [
        {
          "text": "Removes a specified track from the composition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTrack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCompositionTrack",
          "text": "AVCompositionTrack"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/removeTrack(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeTrack:"
        }
      ],
      "role": "symbol",
      "title": "removeTrack(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecomposition/removetrack(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCompositionTrack": {
      "abstract": [
        {
          "text": "A mutable track in a composition that you use to insert, remove, and scale track segments without affecting their low-level representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableCompositionTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCompositionTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableCompositionTrack"
        }
      ],
      "role": "symbol",
      "title": "AVMutableCompositionTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecompositiontrack"
    },
    "doc://com.apple.documentation/documentation/CoreMedia/kCMPersistentTrackID_Invalid": {
      "abstract": [
        {
          "text": "Indicates an invalid track ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPersistentTrackID_Invalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPersistentTrackID",
          "text": "CMPersistentTrackID"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/kCMPersistentTrackID_Invalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMPersistentTrackID_Invalid",
      "type": "topic",
      "url": "/documentation/CoreMedia/kCMPersistentTrackID_Invalid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CMPersistentTrackID": {
      "abstract": [
        {
          "text": "A datatype that represents a persistent track identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPersistentTrackID"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CMPersistentTrackID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMPersistentTrackID",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMPersistentTrackID"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Composition-Tracks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/mutableTrack(compatibleWith:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/removeTrack(_:)"
      ],
      "title": "Managing Composition Tracks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "addMutableTrackWithMediaType:preferredTrackID:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addMutableTrackWithMediaType:preferredTrackID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Composition-Tracks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/mutableTrack(compatibleWith:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableComposition/removeTrack(_:)"
              ],
              "title": "Managing Composition Tracks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCompositionTrack",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVMutableCompositionTrack",
                    "text": "AVMutableCompositionTrack"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "addMutableTrackWithMediaType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMediaType",
                    "text": "AVMediaType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "mediaType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "preferredTrackID:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CMPersistentTrackID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMPersistentTrackID",
                    "text": "CMPersistentTrackID"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "preferredTrackID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The media type of the new track.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "mediaType"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The preferred track ID for the new track. The system generates a unique ID if the value you specify isn’t available. If you don’t need to specify a preferred track ID, pass ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/CoreMedia/kCMPersistentTrackID_Invalid",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", and the system generates an appropriate identifier.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "preferredTrackID"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new mutable composition track.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableComposition/title",
          "value": "AVMutableComposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableComposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableComposition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableComposition~1addMutableTrack(withMediaType:preferredTrackID:)/title",
          "value": "addMutableTrackWithMediaType:preferredTrackID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableComposition~1addMutableTrack(withMediaType:preferredTrackID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addMutableTrackWithMediaType:preferredTrackID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCompositionTrack/title",
          "value": "AVMutableCompositionTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCompositionTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCompositionTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType/title",
          "value": "AVMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMPersistentTrackID/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@int32_t",
              "text": "int32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMPersistentTrackID"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableComposition~1mutableTrack(compatibleWith:)/title",
          "value": "mutableTrackCompatibleWithTrack:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableComposition~1mutableTrack(compatibleWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mutableTrackCompatibleWithTrack:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableComposition~1removeTrack(_:)/title",
          "value": "removeTrack:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableComposition~1removeTrack(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeTrack:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1kCMPersistentTrackID_Invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPersistentTrackID_Invalid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmutablecomposition/addmutabletrack(withmediatype:preferredtrackid:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmutablecomposition/addmutabletrack(withmediatype:preferredtrackid:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
