{
  "abstract": [
    {
      "text": "A response that tells the system to play the item immediately, interrupting any currently playing media.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/now"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INPlaybackQueueLocation@INPlaybackQueueLocationNow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "now"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPlaybackQueueLocationNow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INPlaybackQueueLocation.now"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "now"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation": {
      "abstract": [
        {
          "text": "Constants that describe the playback queue location for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocation"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackQueueLocation",
      "type": "topic",
      "url": "/documentation/intents/inplaybackqueuelocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/later": {
      "abstract": [
        {
          "text": "A response that tells the system to add the media item to the end of the playback queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "later"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/later",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocationLater"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackQueueLocation.later",
      "type": "topic",
      "url": "/documentation/intents/inplaybackqueuelocation/later"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/next": {
      "abstract": [
        {
          "text": "A response that tells the system to play the media item after the currently playing media item finishes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "next"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/next",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocationNext"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackQueueLocation.next",
      "type": "topic",
      "url": "/documentation/intents/inplaybackqueuelocation/next"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/now": {
      "abstract": [
        {
          "text": "A response that tells the system to play the item immediately, interrupting any currently playing media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "now"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/now",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocationNow"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackQueueLocation.now",
      "type": "topic",
      "url": "/documentation/intents/inplaybackqueuelocation/now"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/unknown": {
      "abstract": [
        {
          "text": "A response that indicates the system doesn’t know where to place the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocationUnknown"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackQueueLocation.unknown",
      "type": "topic",
      "url": "/documentation/intents/inplaybackqueuelocation/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/next",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/later"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPlaybackQueueLocationNow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocationNow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/next",
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation/later"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INPlaybackQueueLocationNow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/title",
          "value": "INPlaybackQueueLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation~1next/title",
          "value": "INPlaybackQueueLocationNext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation~1next/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocationNext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation~1now/title",
          "value": "INPlaybackQueueLocationNow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation~1now/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocationNow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation~1unknown/title",
          "value": "INPlaybackQueueLocationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation~1later/title",
          "value": "INPlaybackQueueLocationLater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation~1later/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocationLater"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inplaybackqueuelocation/now"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inplaybackqueuelocation/now"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
