{
  "abstract": [
    {
      "text": "The conversion value is invalid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidConversionValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKANError@SKANErrorInvalidConversionValue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidConversionValue"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKANErrorInvalidConversionValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKANError.Code.invalidConversionValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidConversionValue"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps provide a conversion value when calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork/updatePostbackConversionValue(_:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork/updateConversionValue(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Check that the conversion value you provide is within the allowed range.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct": {
      "abstract": [
        {
          "text": "An error that an ad network attribution operation returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKANError"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANError"
        }
      ],
      "role": "symbol",
      "title": "SKANError",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Constants that indicate the type of error for an ad network attribution operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/adNetworkIdMissing": {
      "abstract": [
        {
          "text": "The ad network identifier in the ad impression doesn’t match the value in the information property list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adNetworkIdMissing"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/adNetworkIdMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorAdNetworkIdMissing"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.adNetworkIdMissing",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/adnetworkidmissing"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionMissingRequiredValue": {
      "abstract": [
        {
          "text": "A required value is missing from a view-through ad impression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "impressionMissingRequiredValue"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionMissingRequiredValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorImpressionMissingRequiredValue"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.impressionMissingRequiredValue",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/impressionmissingrequiredvalue"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionNotFound": {
      "abstract": [
        {
          "text": "The system can’t find the ad impression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "impressionNotFound"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorImpressionNotFound"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.impressionNotFound",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/impressionnotfound"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionTooShort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "impressionTooShort"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionTooShort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorImpressionTooShort"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.impressionTooShort",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/impressiontooshort"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidAdvertisedAppId": {
      "abstract": [
        {
          "text": "The App Store ID of the advertised app is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAdvertisedAppId"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidAdvertisedAppId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorInvalidAdvertisedAppId"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.invalidAdvertisedAppId",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/invalidadvertisedappid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidCampaignId": {
      "abstract": [
        {
          "text": "The campaign identifier that you provided is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCampaignId"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidCampaignId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorInvalidCampaignId"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.invalidCampaignId",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/invalidcampaignid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidConversionValue": {
      "abstract": [
        {
          "text": "The conversion value is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConversionValue"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidConversionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorInvalidConversionValue"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.invalidConversionValue",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/invalidconversionvalue"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidSourceAppId": {
      "abstract": [
        {
          "text": "The App Store ID of the app displaying the ad is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceAppId"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidSourceAppId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorInvalidSourceAppId"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.invalidSourceAppId",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/invalidsourceappid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidVersion": {
      "abstract": [
        {
          "text": "The SKAdNetwork version number is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVersion"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorInvalidVersion"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.invalidVersion",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/invalidversion"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/mismatchedSourceAppId": {
      "abstract": [
        {
          "text": "The source app identifier in the ad impression doesn’t match the app identifier in the source app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mismatchedSourceAppId"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/mismatchedSourceAppId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorMismatchedSourceAppId"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.mismatchedSourceAppId",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/mismatchedsourceappid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.unknown",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/unknown"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unsupported": {
      "abstract": [
        {
          "text": "Your app attempted to use functionality that isn’t supported in the specified version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorUnsupported"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.unsupported",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/unsupported"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork/updateConversionValue(_:)": {
      "abstract": [
        {
          "text": "Updates the conversion value and verifies the first launch of an app installed as a result of an ad.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateConversionValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork/updateConversionValue(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateConversionValue:"
        }
      ],
      "role": "symbol",
      "title": "updateConversionValue(_:)",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork/updateconversionvalue(_:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork/updatePostbackConversionValue(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Verifies the first launch of an advertised app and, on subsequent calls, updates the conversion value or calls a completion handler if the update fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updatePostbackConversionValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork/updatePostbackConversionValue(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updatePostbackConversionValue:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "updatePostbackConversionValue(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork/updatepostbackconversionvalue(_:completionhandler:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/adNetworkIdMissing",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionMissingRequiredValue",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionNotFound",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionTooShort",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidAdvertisedAppId",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidCampaignId",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidSourceAppId",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidVersion",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/mismatchedSourceAppId",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unknown",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unsupported"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKANErrorInvalidConversionValue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidConversionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/adNetworkIdMissing",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionMissingRequiredValue",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionNotFound",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionTooShort",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidAdvertisedAppId",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidCampaignId",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidSourceAppId",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidVersion",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/mismatchedSourceAppId",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unknown",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unsupported"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKANErrorInvalidConversionValue"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidVersion/title",
          "value": "SKANErrorInvalidVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1unknown/title",
          "value": "SKANErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork~1updateConversionValue(_:)/title",
          "value": "updateConversionValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork~1updateConversionValue(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "updateConversionValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionMissingRequiredValue/title",
          "value": "SKANErrorImpressionMissingRequiredValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionMissingRequiredValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorImpressionMissingRequiredValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1adNetworkIdMissing/title",
          "value": "SKANErrorAdNetworkIdMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1adNetworkIdMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorAdNetworkIdMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code/title",
          "value": "SKANError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidConversionValue/title",
          "value": "SKANErrorInvalidConversionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidConversionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidConversionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionTooShort/title",
          "value": "SKANErrorImpressionTooShort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionTooShort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorImpressionTooShort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidSourceAppId/title",
          "value": "SKANErrorInvalidSourceAppId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidSourceAppId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidSourceAppId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1unsupported/title",
          "value": "SKANErrorUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionNotFound/title",
          "value": "SKANErrorImpressionNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorImpressionNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork~1updatePostbackConversionValue(_:completionHandler:)/title",
          "value": "updatePostbackConversionValue:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork~1updatePostbackConversionValue(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "updatePostbackConversionValue:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidAdvertisedAppId/title",
          "value": "SKANErrorInvalidAdvertisedAppId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidAdvertisedAppId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidAdvertisedAppId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1mismatchedSourceAppId/title",
          "value": "SKANErrorMismatchedSourceAppId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1mismatchedSourceAppId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorMismatchedSourceAppId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidCampaignId/title",
          "value": "SKANErrorInvalidCampaignId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidCampaignId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidCampaignId"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skanerror-swift.struct/code/invalidconversionvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skanerror-swift.struct/code/invalidconversionvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
