{
  "abstract": [
    {
      "text": "Starts browsing for peers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser/startBrowsingForPeers()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MCNearbyServiceBrowser(im)startBrowsingForPeers",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "startBrowsingForPeers"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Multipeer Connectivity"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "startBrowsingForPeers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "startBrowsingForPeers()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "startBrowsingForPeers"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After this method is called (until you call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser/stopBrowsingForPeers()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), the framework calls your delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowserDelegate/browser(_:foundPeer:withDiscoveryInfo:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowserDelegate/browser(_:lostPeer:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods as new peers are found and lost.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity": {
      "abstract": [
        {
          "text": "Support peer-to-peer connectivity and the discovery of nearby devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Multipeer Connectivity",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser": {
      "abstract": [
        {
          "text": "Searches (by service type) for services offered by nearby devices using infrastructure Wi-Fi, peer-to-peer Wi-Fi, and Bluetooth (in iOS) or Ethernet (in macOS and tvOS), and provides the ability to easily invite those devices to a Multipeer Connectivity session (",
          "type": "text"
        },
        {
          "code": "MCSession",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCNearbyServiceBrowser"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCNearbyServiceBrowser"
        }
      ],
      "role": "symbol",
      "title": "MCNearbyServiceBrowser",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcnearbyservicebrowser"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser/startBrowsingForPeers()": {
      "abstract": [
        {
          "text": "Starts browsing for peers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startBrowsingForPeers"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser/startBrowsingForPeers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startBrowsingForPeers"
        }
      ],
      "role": "symbol",
      "title": "startBrowsingForPeers()",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcnearbyservicebrowser/startbrowsingforpeers()"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser/stopBrowsingForPeers()": {
      "abstract": [
        {
          "text": "Stops browsing for peers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopBrowsingForPeers"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser/stopBrowsingForPeers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopBrowsingForPeers"
        }
      ],
      "role": "symbol",
      "title": "stopBrowsingForPeers()",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcnearbyservicebrowser/stopbrowsingforpeers()"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowserDelegate/browser(_:foundPeer:withDiscoveryInfo:)": {
      "abstract": [
        {
          "text": "Called when a nearby peer is found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "browser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MCNearbyServiceBrowser",
          "text": "MCNearbyServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "foundPeer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MCPeerID",
          "text": "MCPeerID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withDiscoveryInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowserDelegate/browser(_:foundPeer:withDiscoveryInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "browser:foundPeer:withDiscoveryInfo:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "browser(_:foundPeer:withDiscoveryInfo:)",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcnearbyservicebrowserdelegate/browser(_:foundpeer:withdiscoveryinfo:)"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowserDelegate/browser(_:lostPeer:)": {
      "abstract": [
        {
          "text": "Called when a nearby peer is lost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "browser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MCNearbyServiceBrowser",
          "text": "MCNearbyServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "lostPeer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MCPeerID",
          "text": "MCPeerID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowserDelegate/browser(_:lostPeer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "browser:lostPeer:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "browser(_:lostPeer:)",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcnearbyservicebrowserdelegate/browser(_:lostpeer:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Browsing-for-Peers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser/stopBrowsingForPeers()"
      ],
      "title": "Browsing for Peers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "startBrowsingForPeers"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startBrowsingForPeers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Browsing-for-Peers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCNearbyServiceBrowser/stopBrowsingForPeers()"
              ],
              "title": "Browsing for Peers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "startBrowsingForPeers"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowser~1startBrowsingForPeers()/title",
          "value": "startBrowsingForPeers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowser~1startBrowsingForPeers()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startBrowsingForPeers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowser/title",
          "value": "MCNearbyServiceBrowser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCNearbyServiceBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MCNearbyServiceBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowserDelegate~1browser(_:lostPeer:)/title",
          "value": "browser:lostPeer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowserDelegate~1browser(_:lostPeer:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "browser:lostPeer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowserDelegate~1browser(_:foundPeer:withDiscoveryInfo:)/title",
          "value": "browser:foundPeer:withDiscoveryInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowserDelegate~1browser(_:foundPeer:withDiscoveryInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "browser:foundPeer:withDiscoveryInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowser~1stopBrowsingForPeers()/title",
          "value": "stopBrowsingForPeers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowser~1stopBrowsingForPeers()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopBrowsingForPeers"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/multipeerconnectivity/mcnearbyservicebrowser/startbrowsingforpeers()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/multipeerconnectivity/mcnearbyservicebrowser/startbrowsingforpeers()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
