{
  "abstract": [
    {
      "text": "Specifies that the visible title of the Return key is ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "Send",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/send"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIReturnKeyType@UIReturnKeySend",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "send"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIReturnKeySend"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIReturnKeyType.send"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "send"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType": {
      "abstract": [
        {
          "text": "Constants that specify the text string that displays in the Return key of a keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIReturnKeyType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyType"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/continue": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Continue",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`continue`"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/continue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyContinue"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.continue",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/continue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "return",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyDefault"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.default",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/default"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/done": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Done",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "done"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/done",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyDone"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.done",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/done"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/emergencyCall": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Emergency Call",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emergencyCall"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/emergencyCall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyEmergencyCall"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.emergencyCall",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/emergencycall"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/go": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Go",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "go"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/go",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyGo"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.go",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/go"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/google": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Google",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "google"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/google",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyGoogle"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.google",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/google"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/join": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Join",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "join"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/join",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyJoin"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.join",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/join"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/next": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Next",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "next"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/next",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyNext"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.next",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/next"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/route": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Route",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "route"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/route",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyRoute"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.route",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/route"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/search": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Search",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeySearch"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.search",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/search"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/send": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Send",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/send",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeySend"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.send",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/send"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/yahoo": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Yahoo",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yahoo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/yahoo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyYahoo"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.yahoo",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/yahoo"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/go",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/google",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/join",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/next",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/route",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/search",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/yahoo",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/done",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/emergencyCall",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/continue"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIReturnKeySend"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeySend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/go",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/google",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/join",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/next",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/route",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/search",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/yahoo",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/done",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/emergencyCall",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/continue"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIReturnKeySend"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1done/title",
          "value": "UIReturnKeyDone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1done/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyDone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1route/title",
          "value": "UIReturnKeyRoute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1route/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1go/title",
          "value": "UIReturnKeyGo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1go/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyGo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1next/title",
          "value": "UIReturnKeyNext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1next/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyNext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1continue/title",
          "value": "UIReturnKeyContinue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1continue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyContinue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1google/title",
          "value": "UIReturnKeyGoogle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1google/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyGoogle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1join/title",
          "value": "UIReturnKeyJoin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1join/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyJoin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1yahoo/title",
          "value": "UIReturnKeyYahoo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1yahoo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyYahoo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/title",
          "value": "UIReturnKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1default/title",
          "value": "UIReturnKeyDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1search/title",
          "value": "UIReturnKeySearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeySearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1send/title",
          "value": "UIReturnKeySend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1send/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeySend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1emergencyCall/title",
          "value": "UIReturnKeyEmergencyCall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1emergencyCall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyEmergencyCall"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uireturnkeytype/send"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uireturnkeytype/send"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
