{
  "abstract": [
    {
      "text": "An array containing the types of files the session can write.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/supportedFileTypes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVAssetExportSession(py)supportedFileTypes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "supportedFileTypes"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVFileType",
        "text": "AVFileType"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "supportedFileTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "supportedFileTypes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "supportedFileTypes"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVFileType",
              "text": "AVFileType"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession": {
      "abstract": [
        {
          "text": "An object that exports assets in a format that you specify using an export preset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportSession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportSession"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportSession",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/allowsParallelizedExport": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the session can parallelize its export operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsParallelizedExport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/allowsParallelizedExport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsParallelizedExport"
        }
      ],
      "role": "symbol",
      "title": "allowsParallelizedExport",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/allowsparallelizedexport"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/canPerformMultiplePassesOverSourceMediaData": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the export session can perform multiple passes over the source media to achieve better results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerformMultiplePassesOverSourceMediaData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/canPerformMultiplePassesOverSourceMediaData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformMultiplePassesOverSourceMediaData"
        }
      ],
      "role": "symbol",
      "title": "canPerformMultiplePassesOverSourceMediaData",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/canperformmultiplepassesoversourcemediadata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/directoryForTemporaryFiles": {
      "abstract": [
        {
          "text": "A directory suitable to store temporary files that the export process generates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directoryForTemporaryFiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/directoryForTemporaryFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "directoryForTemporaryFiles"
        }
      ],
      "role": "symbol",
      "title": "directoryForTemporaryFiles",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/directoryfortemporaryfiles"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/fileLengthLimit": {
      "abstract": [
        {
          "text": "The file length that the output of the session must not exceed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileLengthLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/fileLengthLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileLengthLimit"
        }
      ],
      "role": "symbol",
      "title": "fileLengthLimit",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/filelengthlimit"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/outputFileType": {
      "abstract": [
        {
          "text": "The file type of the output an asset export session writes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputFileType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/outputFileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputFileType"
        }
      ],
      "role": "symbol",
      "title": "outputFileType",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/outputfiletype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/outputURL": {
      "abstract": [
        {
          "text": "A URL where an asset export session writes its output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/outputURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputURL"
        }
      ],
      "role": "symbol",
      "title": "outputURL",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/outputurl"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/shouldOptimizeForNetworkUse": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to optimize the movie for network use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldOptimizeForNetworkUse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/shouldOptimizeForNetworkUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldOptimizeForNetworkUse"
        }
      ],
      "role": "symbol",
      "title": "shouldOptimizeForNetworkUse",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/shouldoptimizefornetworkuse"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/supportedFileTypes": {
      "abstract": [
        {
          "text": "An array containing the types of files the session can write.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedFileTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/supportedFileTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedFileTypes"
        }
      ],
      "role": "symbol",
      "title": "supportedFileTypes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/supportedfiletypes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/timeRange": {
      "abstract": [
        {
          "text": "The time range of the source asset to export.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/timeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeRange"
        }
      ],
      "role": "symbol",
      "title": "timeRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/timerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType": {
      "abstract": [
        {
          "text": "The uniform type identifiers for various file formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileType"
        }
      ],
      "role": "symbol",
      "title": "AVFileType",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Output",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/outputURL",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/outputFileType",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/allowsParallelizedExport",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/shouldOptimizeForNetworkUse",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/canPerformMultiplePassesOverSourceMediaData",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/timeRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/fileLengthLimit",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/directoryForTemporaryFiles"
      ],
      "title": "Configuring Output"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "supportedFileTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Output",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/outputURL",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/outputFileType",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/allowsParallelizedExport",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/shouldOptimizeForNetworkUse",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/canPerformMultiplePassesOverSourceMediaData",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/timeRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/fileLengthLimit",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/directoryForTemporaryFiles"
              ],
              "title": "Configuring Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSString *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "supportedFileTypes"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType/title",
          "value": "AVFileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1directoryForTemporaryFiles/title",
          "value": "directoryForTemporaryFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1directoryForTemporaryFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "directoryForTemporaryFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1allowsParallelizedExport/title",
          "value": "allowsParallelizedExport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1allowsParallelizedExport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsParallelizedExport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1outputFileType/title",
          "value": "outputFileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1outputFileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1canPerformMultiplePassesOverSourceMediaData/title",
          "value": "canPerformMultiplePassesOverSourceMediaData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1canPerformMultiplePassesOverSourceMediaData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canPerformMultiplePassesOverSourceMediaData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1supportedFileTypes/title",
          "value": "supportedFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1supportedFileTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1timeRange/title",
          "value": "timeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1timeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1fileLengthLimit/title",
          "value": "fileLengthLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1fileLengthLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fileLengthLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/title",
          "value": "AVAssetExportSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1outputURL/title",
          "value": "outputURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1outputURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1shouldOptimizeForNetworkUse/title",
          "value": "shouldOptimizeForNetworkUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1shouldOptimizeForNetworkUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldOptimizeForNetworkUse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avassetexportsession/supportedfiletypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avassetexportsession/supportedfiletypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
