{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/init(rawValue:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So23TVContentItemImageTraitV8rawValueABSu_tcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "rawValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Su",
        "text": "UInt"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(rawValue:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "rawValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Su",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Su",
              "text": "UInt"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait": {
      "abstract": [
        {
          "text": "Traits describing the type of image you want.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVContentItemImageTrait"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageTrait"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageTrait",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimagetrait"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimagetrait/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:Su": {
      "abstract": [
        {
          "text": "An unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Su",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt",
      "type": "topic",
      "url": "/documentation/Swift/UInt"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait/title",
          "value": "TVContentItemImageTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageTrait"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/tvcontentitemimagetrait/init(rawvalue:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
