{
  "abstract": [
    {
      "text": "An image meant for a light user interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/userInterfaceStyleLight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TVContentItemImageTrait@TVContentItemImageTraitUserInterfaceStyleLight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "userInterfaceStyleLight"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@TVContentItemImageTrait",
        "text": "TVContentItemImageTrait"
      }
    ],
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVContentItemImageTraitUserInterfaceStyleLight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "userInterfaceStyleLight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "userInterfaceStyleLight"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@TVContentItemImageTrait",
              "text": "TVContentItemImageTrait"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Specify this constant, or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/userInterfaceStyleDark",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constant, but not both.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait": {
      "abstract": [
        {
          "text": "Traits describing the type of image you want.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVContentItemImageTrait"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageTrait"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageTrait",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimagetrait"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/screenScale1x": {
      "abstract": [
        {
          "text": "An image meant for a regular display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenScale1x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVContentItemImageTrait",
          "text": "TVContentItemImageTrait"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/screenScale1x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageTraitScreenScale1x"
        }
      ],
      "role": "symbol",
      "title": "screenScale1x",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimagetrait/screenscale1x"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/screenScale2x": {
      "abstract": [
        {
          "text": "An image meant for a Retina display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenScale2x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVContentItemImageTrait",
          "text": "TVContentItemImageTrait"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/screenScale2x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageTraitScreenScale2x"
        }
      ],
      "role": "symbol",
      "title": "screenScale2x",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimagetrait/screenscale2x"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/userInterfaceStyleDark": {
      "abstract": [
        {
          "text": "An image meant for a dark user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceStyleDark"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVContentItemImageTrait",
          "text": "TVContentItemImageTrait"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/userInterfaceStyleDark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageTraitUserInterfaceStyleDark"
        }
      ],
      "role": "symbol",
      "title": "userInterfaceStyleDark",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimagetrait/userinterfacestyledark"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/userInterfaceStyleLight": {
      "abstract": [
        {
          "text": "An image meant for a light user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceStyleLight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVContentItemImageTrait",
          "text": "TVContentItemImageTrait"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/userInterfaceStyleLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageTraitUserInterfaceStyleLight"
        }
      ],
      "role": "symbol",
      "title": "userInterfaceStyleLight",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimagetrait/userinterfacestylelight"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Traits",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/screenScale1x",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/screenScale2x",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/userInterfaceStyleDark"
      ],
      "title": "Traits"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVContentItemImageTraitUserInterfaceStyleLight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageTraitUserInterfaceStyleLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvservices/documentation/TVServices",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Traits",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/screenScale1x",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/screenScale2x",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageTrait/userInterfaceStyleDark"
              ],
              "title": "Traits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "TVContentItemImageTraitUserInterfaceStyleLight"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait~1userInterfaceStyleDark/title",
          "value": "TVContentItemImageTraitUserInterfaceStyleDark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait~1userInterfaceStyleDark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageTraitUserInterfaceStyleDark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait/title",
          "value": "TVContentItemImageTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait~1screenScale2x/title",
          "value": "TVContentItemImageTraitScreenScale2x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait~1screenScale2x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageTraitScreenScale2x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait~1screenScale1x/title",
          "value": "TVContentItemImageTraitScreenScale1x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait~1screenScale1x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageTraitScreenScale1x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait~1userInterfaceStyleLight/title",
          "value": "TVContentItemImageTraitUserInterfaceStyleLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageTrait~1userInterfaceStyleLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageTraitUserInterfaceStyleLight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/tvcontentitemimagetrait/userinterfacestylelight"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvservices/tvcontentitemimagetrait/userinterfacestylelight"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
