{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventChangeConnectionLinkKeyCompleteResults"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventChangeConnectionLinkKeyCompleteResults/init(connectionHandle:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So55BluetoothHCIEventChangeConnectionLinkKeyCompleteResultsV16connectionHandleABs6UInt16V_tcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "connectionHandle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
        "text": "BluetoothConnectionHandle"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(connectionHandle:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "connectionHandle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
              "text": "BluetoothConnectionHandle"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "role": "symbol",
      "title": "BluetoothConnectionHandle",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothconnectionhandle"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventChangeConnectionLinkKeyCompleteResults": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIEventChangeConnectionLinkKeyCompleteResults"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventChangeConnectionLinkKeyCompleteResults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIEventChangeConnectionLinkKeyCompleteResults"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIEventChangeConnectionLinkKeyCompleteResults",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcieventchangeconnectionlinkkeycompleteresults"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventChangeConnectionLinkKeyCompleteResults/init(connectionHandle:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "connectionHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
          "text": "BluetoothConnectionHandle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventChangeConnectionLinkKeyCompleteResults/init(connectionHandle:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(connectionHandle:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcieventchangeconnectionlinkkeycompleteresults/init(connectionhandle:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/title",
          "value": "BluetoothConnectionHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEventChangeConnectionLinkKeyCompleteResults/title",
          "value": "BluetoothHCIEventChangeConnectionLinkKeyCompleteResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEventChangeConnectionLinkKeyCompleteResults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEventChangeConnectionLinkKeyCompleteResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEventChangeConnectionLinkKeyCompleteResults/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEventChangeConnectionLinkKeyCompleteResults"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhcieventchangeconnectionlinkkeycompleteresults/init(connectionhandle:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
