{
  "abstract": [
    {
      "text": "Tells the delegate that document scanning failed while the camera view controller was active.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.VisionKit/documentation/VisionKit",
        "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewController(_:didFailWithError:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)VNDocumentCameraViewControllerDelegate(im)documentCameraViewController:didFailWithError:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "documentCameraViewController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VNDocumentCameraViewController",
        "text": "VNDocumentCameraViewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didFailWithError"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "VisionKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "documentCameraViewController:didFailWithError:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "documentCameraViewController(_:didFailWithError:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "documentCameraViewController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VNDocumentCameraViewController",
              "text": "VNDocumentCameraViewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didFailWithError"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The document camera view controller that failed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "controller"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The error containing the reason for failure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.VisionKit/documentation/VisionKit": {
      "abstract": [
        {
          "text": "Identify and extract information in the environment using the device’s camera, or in images that your app displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit",
      "kind": "symbol",
      "role": "collection",
      "title": "VisionKit",
      "type": "topic",
      "url": "/documentation/visionkit"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewController": {
      "abstract": [
        {
          "text": "An object that presents UI for a camera pass-through that helps people scan physical documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDocumentCameraViewController"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDocumentCameraViewController"
        }
      ],
      "role": "symbol",
      "title": "VNDocumentCameraViewController",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcameraviewcontroller"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol through which the document camera returns its scanned results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDocumentCameraViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDocumentCameraViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "VNDocumentCameraViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcameraviewcontrollerdelegate"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewController(_:didFailWithError:)": {
      "abstract": [
        {
          "text": "Tells the delegate that document scanning failed while the camera view controller was active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentCameraViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNDocumentCameraViewController",
          "text": "VNDocumentCameraViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewController(_:didFailWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentCameraViewController:didFailWithError:"
        }
      ],
      "role": "symbol",
      "title": "documentCameraViewController(_:didFailWithError:)",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcameraviewcontrollerdelegate/documentcameraviewcontroller(_:didfailwitherror:)"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewController(_:didFinishWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user successfully saved a scanned document from the document camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentCameraViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNDocumentCameraViewController",
          "text": "VNDocumentCameraViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNDocumentCameraScan",
          "text": "VNDocumentCameraScan"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewController(_:didFinishWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentCameraViewController:didFinishWithScan:"
        }
      ],
      "role": "symbol",
      "title": "documentCameraViewController(_:didFinishWith:)",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcameraviewcontrollerdelegate/documentcameraviewcontroller(_:didfinishwith:)"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewControllerDidCancel(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user canceled out of the document scanner camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentCameraViewControllerDidCancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNDocumentCameraViewController",
          "text": "VNDocumentCameraViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewControllerDidCancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentCameraViewControllerDidCancel:"
        }
      ],
      "role": "symbol",
      "title": "documentCameraViewControllerDidCancel(_:)",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcameraviewcontrollerdelegate/documentcameraviewcontrollerdidcancel(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-scan-results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewController(_:didFinishWith:)",
        "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewControllerDidCancel(_:)"
      ],
      "title": "Determining scan results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "documentCameraViewController:didFailWithError:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentCameraViewController:didFailWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.VisionKit/documentation/VisionKit",
                "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-scan-results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewController(_:didFinishWith:)",
                "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewControllerDidCancel(_:)"
              ],
              "title": "Determining scan results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "documentCameraViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNDocumentCameraViewController",
                    "text": "VNDocumentCameraViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "controller"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didFailWithError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The document camera view controller that failed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "controller"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The error containing the reason for failure.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate/title",
          "value": "VNDocumentCameraViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate~1documentCameraViewControllerDidCancel(_:)/title",
          "value": "documentCameraViewControllerDidCancel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate~1documentCameraViewControllerDidCancel(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentCameraViewControllerDidCancel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewController/title",
          "value": "VNDocumentCameraViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate~1documentCameraViewController(_:didFinishWith:)/title",
          "value": "documentCameraViewController:didFinishWithScan:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate~1documentCameraViewController(_:didFinishWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentCameraViewController:didFinishWithScan:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate~1documentCameraViewController(_:didFailWithError:)/title",
          "value": "documentCameraViewController:didFailWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate~1documentCameraViewController(_:didFailWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentCameraViewController:didFailWithError:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/visionkit/vndocumentcameraviewcontrollerdelegate/documentcameraviewcontroller(_:didfailwitherror:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/visionkit/vndocumentcameraviewcontrollerdelegate/documentcameraviewcontroller(_:didfailwitherror:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
