{
  "abstract": [
    {
      "text": "Indicates whether a preferred network is available.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/isPreferredNetworkAvailable(completion:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)THClient(im)isPreferredNetworkAvailableWithCompletion:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isPreferredNetworkAvailable"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "completion"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "ThreadNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "isPreferredNetworkAvailableWithCompletion:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "isPreferredNetworkAvailable(completion:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isPreferredNetworkAvailable"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isPreferredAvailable"
            },
            {
              "kind": "text",
              "text": "() "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The completion handler that returns the result of the preferred network status.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completion"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/configuring-a-border-router",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/managing-thread-network-credentials"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "You can call this method from synchronous code using a completion handler,",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "as shown on this page, or you can call it as an asynchronous method that has the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "following declaration:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "code": [
                "func isPreferredAvailable() async -> Bool"
              ],
              "syntax": "swift",
              "type": "codeListing"
            },
            {
              "inlineContent": [
                {
                  "text": "For information about concurrency and asynchronous code in Swift, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Concurrency note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Call the method as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func obtainPreferredAvailable() async -> (NSString?) {",
            "    let client = THClient()",
            "    var bIsPreferredAvailable:Bool?",
            "    bIsPreferredAvailable = await client.isPreferredAvailable()",
            "    let str = ((bIsPreferredAvailable == true) ? \"true\" : \"false\")",
            "    return str as NSString;",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork": {
      "abstract": [
        {
          "text": "Share credentials and choose a designated network for each home.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "ThreadNetwork",
      "type": "topic",
      "url": "/documentation/threadnetwork"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient": {
      "abstract": [
        {
          "text": "A class that supports safely sharing Thread credentials between multiple clients.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "THClient"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "THClient"
        }
      ],
      "role": "symbol",
      "title": "THClient",
      "type": "topic",
      "url": "/documentation/threadnetwork/thclient"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/checkPreferredNetwork(forActiveOperationalDataset:completion:)": {
      "abstract": [
        {
          "text": "Determines if the essential operating parameters match the preferred network’s parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkPreferredNetwork"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forActiveOperationalDataset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/checkPreferredNetwork(forActiveOperationalDataset:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "checkPreferredNetworkForActiveOperationalDataset:completion:"
        }
      ],
      "role": "symbol",
      "title": "checkPreferredNetwork(forActiveOperationalDataset:completion:)",
      "type": "topic",
      "url": "/documentation/threadnetwork/thclient/checkpreferrednetwork(foractiveoperationaldataset:completion:)"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/isPreferredNetworkAvailable(completion:)": {
      "abstract": [
        {
          "text": "Indicates whether a preferred network is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPreferredNetworkAvailable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/isPreferredNetworkAvailable(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isPreferredNetworkAvailableWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "isPreferredNetworkAvailable(completion:)",
      "type": "topic",
      "url": "/documentation/threadnetwork/thclient/ispreferrednetworkavailable(completion:)"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveAllActiveCredentials(_:)": {
      "abstract": [
        {
          "text": "Returns a set of the active credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retrieveAllActiveCredentials"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)THCredentials",
          "text": "THCredentials"
        },
        {
          "kind": "text",
          "text": ">?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveAllActiveCredentials(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retrieveAllActiveCredentials:"
        }
      ],
      "role": "symbol",
      "title": "retrieveAllActiveCredentials(_:)",
      "type": "topic",
      "url": "/documentation/threadnetwork/thclient/retrieveallactivecredentials(_:)"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveAllCredentials(_:)": {
      "abstract": [
        {
          "text": "Requests all Thread credentials from the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retrieveAllCredentials"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)THCredentials",
          "text": "THCredentials"
        },
        {
          "kind": "text",
          "text": ">?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveAllCredentials(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retrieveAllCredentials:"
        }
      ],
      "role": "symbol",
      "title": "retrieveAllCredentials(_:)",
      "type": "topic",
      "url": "/documentation/threadnetwork/thclient/retrieveallcredentials(_:)"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveCredentials(forBorderAgent:completion:)": {
      "abstract": [
        {
          "text": "Requests Thread credentials for a Border Agent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retrieveCredentials"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forBorderAgent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)THCredentials",
          "text": "THCredentials"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveCredentials(forBorderAgent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retrieveCredentialsForBorderAgent:completion:"
        }
      ],
      "role": "symbol",
      "title": "retrieveCredentials(forBorderAgent:completion:)",
      "type": "topic",
      "url": "/documentation/threadnetwork/thclient/retrievecredentials(forborderagent:completion:)"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveCredentials(forExtendedPANID:completion:)": {
      "abstract": [
        {
          "text": "Requests Thread credentials for an extended Personal Area Network (PAN) ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retrieveCredentials"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forExtendedPANID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)THCredentials",
          "text": "THCredentials"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveCredentials(forExtendedPANID:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retrieveCredentialsForExtendedPANID:completion:"
        }
      ],
      "role": "symbol",
      "title": "retrieveCredentials(forExtendedPANID:completion:)",
      "type": "topic",
      "url": "/documentation/threadnetwork/thclient/retrievecredentials(forextendedpanid:completion:)"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrievePreferredCredentials(_:)": {
      "abstract": [
        {
          "text": "Requests Thread credentials for the preferred network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retrievePreferredCredentials"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)THCredentials",
          "text": "THCredentials"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrievePreferredCredentials(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retrievePreferredCredentials:"
        }
      ],
      "role": "symbol",
      "title": "retrievePreferredCredentials(_:)",
      "type": "topic",
      "url": "/documentation/threadnetwork/thclient/retrievepreferredcredentials(_:)"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/configuring-a-border-router": {
      "abstract": [
        {
          "text": "Set up or add a Border Router on a Thread network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/configuring-a-border-router",
      "kind": "article",
      "role": "article",
      "title": "Configuring a Border Router",
      "type": "topic",
      "url": "/documentation/threadnetwork/configuring-a-border-router"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/managing-thread-network-credentials": {
      "abstract": [
        {
          "text": "Store, delete, retrieve, and update Thread network credentials on your Apple device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/managing-thread-network-credentials",
      "kind": "article",
      "role": "article",
      "title": "Managing Thread network credentials",
      "type": "topic",
      "url": "/documentation/threadnetwork/managing-thread-network-credentials"
    },
    "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously": {
      "abstract": [
        {
          "text": "Learn how functions and methods that take a completion handler are converted to Swift asynchronous functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
      "kind": "article",
      "role": "article",
      "title": "Calling Objective-C APIs Asynchronously",
      "type": "topic",
      "url": "/documentation/Swift/calling-objective-c-apis-asynchronously"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retrieving-Credentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/checkPreferredNetwork(forActiveOperationalDataset:completion:)",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveCredentials(forBorderAgent:completion:)",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveCredentials(forExtendedPANID:completion:)",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveAllCredentials(_:)",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrievePreferredCredentials(_:)",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveAllActiveCredentials(_:)"
      ],
      "title": "Retrieving Credentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "isPreferredNetworkAvailableWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isPreferredNetworkAvailableWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Retrieving-Credentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/checkPreferredNetwork(forActiveOperationalDataset:completion:)",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveCredentials(forBorderAgent:completion:)",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveCredentials(forExtendedPANID:completion:)",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveAllCredentials(_:)",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrievePreferredCredentials(_:)",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient/retrieveAllActiveCredentials(_:)"
              ],
              "title": "Retrieving Credentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "isPreferredNetworkAvailableWithCompletion:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "isPreferredAvailable"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The completion handler that returns the result of the preferred network status.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completion"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient/title",
          "value": "THClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "THClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "THClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1retrieveCredentials(forExtendedPANID:completion:)/title",
          "value": "retrieveCredentialsForExtendedPANID:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1retrieveCredentials(forExtendedPANID:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "retrieveCredentialsForExtendedPANID:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1retrievePreferredCredentials(_:)/title",
          "value": "retrievePreferredCredentials:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1retrievePreferredCredentials(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "retrievePreferredCredentials:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1isPreferredNetworkAvailable(completion:)/title",
          "value": "isPreferredNetworkAvailableWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1isPreferredNetworkAvailable(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isPreferredNetworkAvailableWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1checkPreferredNetwork(forActiveOperationalDataset:completion:)/title",
          "value": "checkPreferredNetworkForActiveOperationalDataset:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1checkPreferredNetwork(forActiveOperationalDataset:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "checkPreferredNetworkForActiveOperationalDataset:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1retrieveAllCredentials(_:)/title",
          "value": "retrieveAllCredentials:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1retrieveAllCredentials(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "retrieveAllCredentials:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1retrieveCredentials(forBorderAgent:completion:)/title",
          "value": "retrieveCredentialsForBorderAgent:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1retrieveCredentials(forBorderAgent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "retrieveCredentialsForBorderAgent:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1retrieveAllActiveCredentials(_:)/title",
          "value": "retrieveAllActiveCredentials:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient~1retrieveAllActiveCredentials(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "retrieveAllActiveCredentials:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/threadnetwork/thclient/ispreferrednetworkavailable(completion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/threadnetwork/thclient/ispreferrednetworkavailable(completion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
