{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontroller(_:skiptonextchannel:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontroller(_:skiptonextchannel:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToNextChannel:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate"]]},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","title":"playerViewController(_:skipToNextChannel:)","externalID":"c:objc(pl)AVPlayerViewControllerDelegate(im)playerViewController:skipToNextChannel:","platforms":[{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"name":"tvOS"}],"navigatorTitle":[{"text":"playerViewController:skipToNextChannel:","kind":"identifier"}],"modules":[{"name":"AVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVPlayerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"text":", ","kind":"text"},{"text":"skipToNextChannel","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol"},"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToPreviousChannel:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/nextChannelInterstitialViewController(for:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/previousChannelInterstitialViewController(for:)"],"title":"Responding to Channel Changes","generated":true,"anchor":"Responding-to-Channel-Changes"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","text":"AVPlayerViewController","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"text":", ","kind":"text"},{"text":"skipToNextChannel","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","identifier":"doc://com.externally.resolved.symbol/s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["tvOS"]},{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewControllerSkipToNextChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerViewController"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","text":"AVPlayerViewController","preciseIdentifier":"c:objc(cs)AVPlayerViewController","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["tvOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The player view controller.","type":"text"}],"type":"paragraph"}],"name":"playerViewController"},{"content":[{"inlineContent":[{"text":"A completion callback to invoke to dismiss the channel’s interstitial view.","type":"text"}],"type":"paragraph"}],"name":"completion"}]},{"content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"aside","style":"important","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"You can call this method from synchronous code using a completion handler, as shown on this page, or you can call it as an asynchronous method that has the following declaration:"}],"type":"paragraph"},{"syntax":"swift","code":["optional func playerViewControllerSkipToNextChannel(_ playerViewController: AVPlayerViewController) async -> Bool"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"For information about concurrency and asynchronous code in Swift, see "},{"identifier":"doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"Important"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To enable channel skipping, adopt this method and replace the current player item with one that reflects the next channel’s content, and call the completion handler to dismiss the channel’s interstitial view. Each call to this method should advance one channel, relative to the previous request, even if the prior request hasn’t yet completed."}]},{"type":"aside","style":"important","content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Only live video streams support channel skipping. This feature isn’t supported for VOD streams or local media.","type":"text"}],"type":"paragraph"}],"name":"Important"}],"kind":"content"}],"abstract":[{"text":"Tells the delegate when the user wants to skip to the next channel.","type":"text"}],"kind":"symbol","references":{"doc://com.externally.resolved.symbol/s:s4Voida":{"title":"Void","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Void"},{"kind":"text","text":" = ()"}],"kind":"symbol","type":"topic","url":"/documentation/Swift/Void"},"doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously":{"title":"Calling Objective-C APIs Asynchronously","role":"article","identifier":"doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously","abstract":[{"text":"Learn how functions and methods that take a completion handler are converted to Swift asynchronous functions.","type":"text"}],"kind":"article","type":"topic","url":"/documentation/Swift/calling-objective-c-apis-asynchronously"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/previousChannelInterstitialViewController(for:)":{"type":"topic","role":"symbol","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/previousChannelInterstitialViewController(for:)","navigatorTitle":[{"text":"previousChannelInterstitialViewControllerForPlayerViewController:","kind":"identifier"}],"title":"previousChannelInterstitialViewController(for:)","url":"/documentation/avkit/avplayerviewcontrollerdelegate/previouschannelinterstitialviewcontroller(for:)","abstract":[{"text":"Asks the delegate for a view controller that describes the layout of the previous channel’s interstitial view.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousChannelInterstitialViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVPlayerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"text":") -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"kind":"symbol"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToNextChannel:)":{"title":"playerViewController(_:skipToNextChannel:)","kind":"symbol","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontroller(_:skiptonextchannel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVPlayerViewController","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"kind":"text","text":", "},{"text":"skipToNextChannel","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToNextChannel:)","role":"symbol","abstract":[{"type":"text","text":"Tells the delegate when the user wants to skip to the next channel."}],"navigatorTitle":[{"text":"playerViewController:skipToNextChannel:","kind":"identifier"}]},"doc://com.apple.avkit/documentation/AVKit":{"identifier":"doc://com.apple.avkit/documentation/AVKit","type":"topic","url":"/documentation/avkit","abstract":[{"type":"text","text":"Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions."}],"kind":"symbol","title":"AVKit","role":"collection"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"url":"/documentation/Swift/Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"symbol","role":"symbol"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToPreviousChannel:)":{"kind":"symbol","abstract":[{"text":"Tells the delegate when the user wants to skip to the previous channel.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"skipToPreviousChannel"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontroller(_:skiptopreviouschannel:)","navigatorTitle":[{"text":"playerViewController:skipToPreviousChannel:","kind":"identifier"}],"role":"symbol","title":"playerViewController(_:skipToPreviousChannel:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToPreviousChannel:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","role":"overview"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/nextChannelInterstitialViewController(for:)":{"kind":"symbol","abstract":[{"text":"Asks the delegate for a view controller that describes the layout of the next channel’s interstitial view.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextChannelInterstitialViewController"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/avkit/avplayerviewcontrollerdelegate/nextchannelinterstitialviewcontroller(for:)","navigatorTitle":[{"text":"nextChannelInterstitialViewControllerForPlayerViewController:","kind":"identifier"}],"role":"symbol","title":"nextChannelInterstitialViewController(for:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/nextChannelInterstitialViewController(for:)"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController":{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","type":"topic","url":"/documentation/avkit/avplayerviewcontroller","abstract":[{"type":"text","text":"A view controller that displays content from a player and presents a native user interface to control playback."}],"kind":"symbol","title":"AVPlayerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVPlayerViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerViewController"}]},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate":{"url":"/documentation/avkit/avplayerviewcontrollerdelegate","abstract":[{"text":"A protocol that defines the methods to implement to respond to player view controller events.","type":"text"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"AVPlayerViewControllerDelegate"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"13.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"playerViewController:skipToNextChannel:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerViewController:skipToNextChannel:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Responding to Channel Changes","generated":true,"identifiers":["doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToPreviousChannel:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/nextChannelInterstitialViewController(for:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/previousChannelInterstitialViewController(for:)"],"anchor":"Responding-to-Channel-Changes"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"playerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVPlayerViewController","kind":"typeIdentifier","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"text":" *) ","kind":"text"},{"text":"playerViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"skipToNextChannel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"playerViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The player view controller."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A completion callback to invoke to dismiss the channel’s interstitial view."}]}]}]},"path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1previousChannelInterstitialViewController(for:)/title","value":"previousChannelInterstitialViewControllerForPlayerViewController:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1previousChannelInterstitialViewController(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"previousChannelInterstitialViewControllerForPlayerViewController:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:skipToNextChannel:)/title","value":"playerViewController:skipToNextChannel:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:skipToNextChannel:)/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playerViewController:skipToNextChannel:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:skipToPreviousChannel:)/title","value":"playerViewController:skipToPreviousChannel:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:skipToPreviousChannel:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewController:skipToPreviousChannel:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1nextChannelInterstitialViewController(for:)/title","value":"nextChannelInterstitialViewControllerForPlayerViewController:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1nextChannelInterstitialViewController(for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nextChannelInterstitialViewControllerForPlayerViewController:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/title","value":"AVPlayerViewController","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/fragments","value":[{"text":"AVPlayerViewController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/navigatorTitle","value":[{"text":"AVPlayerViewController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/title","value":"AVPlayerViewControllerDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/fragments","value":[{"kind":"identifier","text":"AVPlayerViewControllerDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/navigatorTitle","value":[{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}