{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontrollerwillstartpictureinpicture(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontrollerwillstartpictureinpicture(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerWillStartPictureInPicture(_:)"},"seeAlsoSections":[{"anchor":"Responding-to-Picture-in-Picture-Life-Cycle-Events","title":"Responding to Picture in Picture Life Cycle Events","identifiers":["doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart(_:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerDidStartPictureInPicture(_:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:failedToStartPictureInPictureWithError:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerWillStopPictureInPicture(_:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerDidStopPictureInPicture(_:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewControllerWillStartPictureInPicture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AVPlayerViewController","preciseIdentifier":"c:objc(cs)AVPlayerViewController","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The player view controller.","type":"text"}],"type":"paragraph"}],"name":"playerViewController"}],"kind":"parameters"},{"mentions":["doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player"],"kind":"mentions"},{"content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Implement this method to update your player user interface, such as hiding or disabling playback controls, prior to PiP starting.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"abstract":[{"text":"Tells the delegate when Picture in Picture is about to start.","type":"text"}],"metadata":{"platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"9.0","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"9.0","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"tvOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false}],"externalID":"c:objc(pl)AVPlayerViewControllerDelegate(im)playerViewControllerWillStartPictureInPicture:","symbolKind":"method","role":"symbol","modules":[{"name":"AVKit"}],"navigatorTitle":[{"text":"playerViewControllerWillStartPictureInPicture:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewControllerWillStartPictureInPicture","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"playerViewControllerWillStartPictureInPicture(_:)"},"references":{"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:failedToStartPictureInPictureWithError:)":{"title":"playerViewController(_:failedToStartPictureInPictureWithError:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:failedToStartPictureInPictureWithError:)","navigatorTitle":[{"text":"playerViewController:failedToStartPictureInPictureWithError:","kind":"identifier"}],"type":"topic","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontroller(_:failedtostartpictureinpicturewitherror:)","kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate when Picture in Picture fails to start."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVPlayerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"text":", ","kind":"text"},{"text":"failedToStartPictureInPictureWithError","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerWillStartPictureInPicture(_:)":{"title":"playerViewControllerWillStartPictureInPicture(_:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerWillStartPictureInPicture(_:)","navigatorTitle":[{"text":"playerViewControllerWillStartPictureInPicture:","kind":"identifier"}],"type":"topic","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontrollerwillstartpictureinpicture(_:)","kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate when Picture in Picture is about to start."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playerViewControllerWillStartPictureInPicture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVPlayerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"text":")","kind":"text"}]},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerDidStopPictureInPicture(_:)":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Tells the delegate when Picture in Picture stops."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewControllerDidStopPictureInPicture","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"playerViewControllerDidStopPictureInPicture:","kind":"identifier"}],"title":"playerViewControllerDidStopPictureInPicture(_:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerDidStopPictureInPicture(_:)","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontrollerdidstoppictureinpicture(_:)"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerWillStopPictureInPicture(_:)":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Tells the delegate when Picture in Picture is about to stop."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewControllerWillStopPictureInPicture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVPlayerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"playerViewControllerWillStopPictureInPicture:","kind":"identifier"}],"title":"playerViewControllerWillStopPictureInPicture(_:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerWillStopPictureInPicture(_:)","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontrollerwillstoppictureinpicture(_:)"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerDidStartPictureInPicture(_:)":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Tells the delegate when Picture in Picture starts.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewControllerDidStartPictureInPicture"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"playerViewControllerDidStartPictureInPicture:","kind":"identifier"}],"title":"playerViewControllerDidStartPictureInPicture(_:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerDidStartPictureInPicture(_:)","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontrollerdidstartpictureinpicture(_:)"},"doc://com.apple.avkit/documentation/AVKit":{"identifier":"doc://com.apple.avkit/documentation/AVKit","type":"topic","url":"/documentation/avkit","abstract":[{"type":"text","text":"Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions."}],"kind":"symbol","title":"AVKit","role":"collection"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate":{"url":"/documentation/avkit/avplayerviewcontrollerdelegate","abstract":[{"text":"A protocol that defines the methods to implement to respond to player view controller events.","type":"text"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"AVPlayerViewControllerDelegate"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart(_:)":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Asks the delegate whether the player view controller automatically dismisses itself when Picture in Picture starts."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart:","kind":"identifier"}],"title":"playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart(_:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart(_:)","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontrollershouldautomaticallydismissatpictureinpicturestart(_:)"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController":{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","type":"topic","url":"/documentation/avkit/avplayerviewcontroller","abstract":[{"type":"text","text":"A view controller that displays content from a player and presents a native user interface to control playback."}],"kind":"symbol","title":"AVPlayerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVPlayerViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerViewController"}]},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Tells the delegate when Picture in Picture is about to stop so you can restore your app’s user interface.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController"},{"text":", ","kind":"text"},{"text":"restoreUserInterfaceForPictureInPictureStopWithCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"playerViewController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","kind":"identifier"}],"title":"playerViewController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontroller(_:restoreuserinterfaceforpictureinpicturestopwithcompletionhandler:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","role":"overview"},"doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player":{"type":"topic","kind":"article","role":"article","abstract":[{"text":"Add Picture in Picture (PiP) playback to your app using a player view controller.","type":"text"}],"title":"Adopting Picture in Picture in a Standard Player","identifier":"doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player","url":"/documentation/avkit/adopting-picture-in-picture-in-a-standard-player"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","value":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"9.0","unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"9.0","unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1","unavailable":false},{"beta":false,"introducedAt":"14.0","unavailable":false,"deprecated":false,"name":"tvOS"},{"beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"playerViewControllerWillStartPictureInPicture:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewControllerWillStartPictureInPicture:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Responding to Picture in Picture Life Cycle Events","generated":true,"identifiers":["doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart(_:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerDidStartPictureInPicture(_:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:failedToStartPictureInPictureWithError:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerWillStopPictureInPicture(_:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewControllerDidStopPictureInPicture(_:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)"],"anchor":"Responding-to-Picture-in-Picture-Life-Cycle-Events"}],"op":"replace"},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"playerViewControllerWillStartPictureInPicture:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","preciseIdentifier":"c:objc(cs)AVPlayerViewController","kind":"typeIdentifier","text":"AVPlayerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerViewController"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]}},{"path":"/primaryContentSections/1","value":{"parameters":[{"name":"playerViewController","content":[{"inlineContent":[{"text":"The player view controller.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:failedToStartPictureInPictureWithError:)/title","op":"replace","value":"playerViewController:failedToStartPictureInPictureWithError:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:failedToStartPictureInPictureWithError:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playerViewController:failedToStartPictureInPictureWithError:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewControllerWillStartPictureInPicture(_:)/title","op":"replace","value":"playerViewControllerWillStartPictureInPicture:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewControllerWillStartPictureInPicture(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playerViewControllerWillStartPictureInPicture:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewControllerDidStopPictureInPicture(_:)/title","op":"replace","value":"playerViewControllerDidStopPictureInPicture:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewControllerDidStopPictureInPicture(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playerViewControllerDidStopPictureInPicture:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewControllerWillStopPictureInPicture(_:)/title","op":"replace","value":"playerViewControllerWillStopPictureInPicture:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewControllerWillStopPictureInPicture(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewControllerWillStopPictureInPicture:"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewControllerDidStartPictureInPicture(_:)/title","op":"replace","value":"playerViewControllerDidStartPictureInPicture:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewControllerDidStartPictureInPicture(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playerViewControllerDidStartPictureInPicture:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/title","op":"replace","value":"AVPlayerViewControllerDelegate"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/fragments","op":"replace","value":[{"kind":"identifier","text":"AVPlayerViewControllerDelegate"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/navigatorTitle","op":"replace","value":[{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart(_:)/title","op":"replace","value":"playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewControllerShouldAutomaticallyDismissAtPictureInPictureStart:"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/title","op":"replace","value":"AVPlayerViewController"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/fragments","op":"replace","value":[{"kind":"identifier","text":"AVPlayerViewController"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AVPlayerViewController"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)/title","op":"replace","value":"playerViewController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playerViewController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}