{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousChannelInterstitialViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","kind":"typeIdentifier","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","text":"AVPlayerViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UIViewController","text":"UIViewController"}],"platforms":["tvOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The player view controller.","type":"text"}],"type":"paragraph"}],"name":"playerViewController"}]},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"The framework calls this method when the user initiates, but hasn’t yet committed, a change in channel. The framework may call this method while a previous channel’s interstitial view is visible (on screen, or transitioning).","type":"text"}],"type":"paragraph"},{"style":"important","type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Only live video streams support channel skipping. This feature isn’t supported for VOD streams or local media."}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate"]]},"seeAlsoSections":[{"generated":true,"anchor":"Responding-to-Channel-Changes","identifiers":["doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToNextChannel:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToPreviousChannel:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/nextChannelInterstitialViewController(for:)"],"title":"Responding to Channel Changes"}],"metadata":{"navigatorTitle":[{"text":"previousChannelInterstitialViewControllerForPlayerViewController:","kind":"identifier"}],"modules":[{"name":"AVKit"}],"externalID":"c:objc(pl)AVPlayerViewControllerDelegate(im)previousChannelInterstitialViewControllerForPlayerViewController:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previousChannelInterstitialViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","kind":"typeIdentifier","text":"AVPlayerViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"tvOS","introducedAt":"13.0"}],"role":"symbol","symbolKind":"method","title":"previousChannelInterstitialViewController(for:)","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/previousChannelInterstitialViewController(for:)"},"abstract":[{"text":"Asks the delegate for a view controller that describes the layout of the previous channel’s interstitial view.","type":"text"}],"variants":[{"paths":["/documentation/avkit/avplayerviewcontrollerdelegate/previouschannelinterstitialviewcontroller(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avkit/avplayerviewcontrollerdelegate/previouschannelinterstitialviewcontroller(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController":{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","type":"topic","url":"/documentation/avkit/avplayerviewcontroller","abstract":[{"type":"text","text":"A view controller that displays content from a player and presents a native user interface to control playback."}],"kind":"symbol","title":"AVPlayerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVPlayerViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerViewController"}]},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToNextChannel:)":{"title":"playerViewController(_:skipToNextChannel:)","kind":"symbol","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontroller(_:skiptonextchannel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVPlayerViewController","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"kind":"text","text":", "},{"text":"skipToNextChannel","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToNextChannel:)","role":"symbol","abstract":[{"type":"text","text":"Tells the delegate when the user wants to skip to the next channel."}],"navigatorTitle":[{"text":"playerViewController:skipToNextChannel:","kind":"identifier"}]},"doc://com.apple.avkit/documentation/AVKit":{"identifier":"doc://com.apple.avkit/documentation/AVKit","type":"topic","url":"/documentation/avkit","abstract":[{"type":"text","text":"Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions."}],"kind":"symbol","title":"AVKit","role":"collection"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate":{"url":"/documentation/avkit/avplayerviewcontrollerdelegate","abstract":[{"text":"A protocol that defines the methods to implement to respond to player view controller events.","type":"text"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"AVPlayerViewControllerDelegate"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","role":"overview"},"doc://com.externally.resolved.symbol/c:objc(cs)UIViewController":{"url":"/documentation/UIKit/UIViewController","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UIViewController","abstract":[{"text":"An object that manages a view hierarchy for your UIKit app.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UIViewController","kind":"identifier"}],"title":"UIViewController"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/nextChannelInterstitialViewController(for:)":{"kind":"symbol","abstract":[{"text":"Asks the delegate for a view controller that describes the layout of the next channel’s interstitial view.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextChannelInterstitialViewController"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/avkit/avplayerviewcontrollerdelegate/nextchannelinterstitialviewcontroller(for:)","navigatorTitle":[{"text":"nextChannelInterstitialViewControllerForPlayerViewController:","kind":"identifier"}],"role":"symbol","title":"nextChannelInterstitialViewController(for:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/nextChannelInterstitialViewController(for:)"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/previousChannelInterstitialViewController(for:)":{"type":"topic","role":"symbol","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/previousChannelInterstitialViewController(for:)","navigatorTitle":[{"text":"previousChannelInterstitialViewControllerForPlayerViewController:","kind":"identifier"}],"title":"previousChannelInterstitialViewController(for:)","url":"/documentation/avkit/avplayerviewcontrollerdelegate/previouschannelinterstitialviewcontroller(for:)","abstract":[{"text":"Asks the delegate for a view controller that describes the layout of the previous channel’s interstitial view.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousChannelInterstitialViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVPlayerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"text":") -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"kind":"symbol"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToPreviousChannel:)":{"kind":"symbol","abstract":[{"text":"Tells the delegate when the user wants to skip to the previous channel.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"skipToPreviousChannel"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontroller(_:skiptopreviouschannel:)","navigatorTitle":[{"text":"playerViewController:skipToPreviousChannel:","kind":"identifier"}],"role":"symbol","title":"playerViewController(_:skipToPreviousChannel:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToPreviousChannel:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"13.0","beta":false,"name":"tvOS","deprecated":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"previousChannelInterstitialViewControllerForPlayerViewController:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"previousChannelInterstitialViewControllerForPlayerViewController:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToNextChannel:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:skipToPreviousChannel:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/nextChannelInterstitialViewController(for:)"],"anchor":"Responding-to-Channel-Changes","title":"Responding to Channel Changes"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"previousChannelInterstitialViewControllerForPlayerViewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","kind":"typeIdentifier","text":"AVPlayerViewController","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerViewController"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The player view controller."}],"type":"paragraph"}],"name":"playerViewController"}],"kind":"parameters"}},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/title","op":"replace","value":"AVPlayerViewController"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/fragments","op":"replace","value":[{"text":"AVPlayerViewController","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/navigatorTitle","op":"replace","value":[{"text":"AVPlayerViewController","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:skipToNextChannel:)/title","op":"replace","value":"playerViewController:skipToNextChannel:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:skipToNextChannel:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewController:skipToNextChannel:"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/title","op":"replace","value":"AVPlayerViewControllerDelegate"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/fragments","op":"replace","value":[{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AVPlayerViewControllerDelegate"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIViewController/fragments","op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewController"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIResponder","kind":"typeIdentifier","text":"UIResponder"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1nextChannelInterstitialViewController(for:)/title","op":"replace","value":"nextChannelInterstitialViewControllerForPlayerViewController:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1nextChannelInterstitialViewController(for:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nextChannelInterstitialViewControllerForPlayerViewController:"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1previousChannelInterstitialViewController(for:)/title","op":"replace","value":"previousChannelInterstitialViewControllerForPlayerViewController:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1previousChannelInterstitialViewController(for:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"previousChannelInterstitialViewControllerForPlayerViewController:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:skipToPreviousChannel:)/title","op":"replace","value":"playerViewController:skipToPreviousChannel:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:skipToPreviousChannel:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewController:skipToPreviousChannel:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}