{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Tells the delegate when the user requests skipping to the next item in the timeline.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"skipToNextItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","text":"AVPlayerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The player view controller.","type":"text"}]}],"name":"playerViewController"}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The framework calls this method when you set the player view controller’s skipping behavior to "},{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerSkippingBehavior/skipItem","isActive":true,"type":"reference"},{"type":"text","text":" and a user performs a forward skip gesture (by pressing the right side of the Siri Remote’s Touch surface). Implement this method to update the player view controller’s "},{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/player","type":"reference","isActive":true},{"text":" to play the next player item.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/skipToNextItem(for:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"skipToNextItemForPlayerViewController:"}],"title":"skipToNextItem(for:)","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipToNextItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","kind":"typeIdentifier","text":"AVPlayerViewController"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)AVPlayerViewControllerDelegate(im)skipToNextItemForPlayerViewController:","modules":[{"name":"AVKit"}],"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"10.0","name":"tvOS","beta":false}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate"]]},"seeAlsoSections":[{"generated":true,"title":"Responding to Navigation Events","anchor":"Responding-to-Navigation-Events","identifiers":["doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:timeToSeekAfterUserNavigatedFrom:to:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:willResumePlaybackAfterUserNavigatedFrom:to:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/skipToPreviousItem(for:)"]}],"kind":"symbol","variants":[{"paths":["/documentation/avkit/avplayerviewcontrollerdelegate/skiptonextitem(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avkit/avplayerviewcontrollerdelegate/skiptonextitem(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate":{"url":"/documentation/avkit/avplayerviewcontrollerdelegate","abstract":[{"text":"A protocol that defines the methods to implement to respond to player view controller events.","type":"text"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AVPlayerViewControllerDelegate","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"AVPlayerViewControllerDelegate"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerSkippingBehavior/skipItem":{"type":"topic","title":"AVPlayerViewControllerSkippingBehavior.skipItem","url":"/documentation/avkit/avplayerviewcontrollerskippingbehavior/skipitem","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVPlayerViewControllerSkippingBehaviorSkipItem"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerSkippingBehavior/skipItem","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipItem"}],"abstract":[{"type":"text","text":"Skipping behavior that specifies skipping to the next or previous item in the player’s playlist."}]},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:timeToSeekAfterUserNavigatedFrom:to:)":{"abstract":[{"text":"Tells the delegate when the user skips, scrubs, or otherwise navigates to a new time and wants to resume playback at the target time.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:timeToSeekAfterUserNavigatedFrom:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVPlayerViewController","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeToSeekAfterUserNavigatedFrom"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime","text":"CMTime"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime","text":"CMTime"}],"title":"playerViewController(_:timeToSeekAfterUserNavigatedFrom:to:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"playerViewController:timeToSeekAfterUserNavigatedFromTime:toTime:"}],"url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontroller(_:timetoseekafterusernavigatedfrom:to:)"},"doc://com.apple.avkit/documentation/AVKit":{"identifier":"doc://com.apple.avkit/documentation/AVKit","type":"topic","url":"/documentation/avkit","abstract":[{"type":"text","text":"Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions."}],"kind":"symbol","title":"AVKit","role":"collection"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController":{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","type":"topic","url":"/documentation/avkit/avplayerviewcontroller","abstract":[{"type":"text","text":"A view controller that displays content from a player and presents a native user interface to control playback."}],"kind":"symbol","title":"AVPlayerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVPlayerViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerViewController"}]},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:willResumePlaybackAfterUserNavigatedFrom:to:)":{"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate when the user navigates to a new time and playback is about to begin."}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willResumePlaybackAfterUserNavigatedFrom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":")"}],"title":"playerViewController(_:willResumePlaybackAfterUserNavigatedFrom:to:)","url":"/documentation/avkit/avplayerviewcontrollerdelegate/playerviewcontroller(_:willresumeplaybackafterusernavigatedfrom:to:)","navigatorTitle":[{"kind":"identifier","text":"playerViewController:willResumePlaybackAfterUserNavigatedFromTime:toTime:"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:willResumePlaybackAfterUserNavigatedFrom:to:)"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/skipToNextItem(for:)":{"abstract":[{"text":"Tells the delegate when the user requests skipping to the next item in the timeline.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/skipToNextItem(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skipToNextItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVPlayerViewController","preciseIdentifier":"c:objc(cs)AVPlayerViewController"},{"kind":"text","text":")"}],"title":"skipToNextItem(for:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"skipToNextItemForPlayerViewController:"}],"url":"/documentation/avkit/avplayerviewcontrollerdelegate/skiptonextitem(for:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","role":"overview"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/player":{"abstract":[{"text":"The player object that provides the media content for the view controller to display.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVPlayer","preciseIdentifier":"c:objc(cs)AVPlayer","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"player"}],"type":"topic","title":"player","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/player","url":"/documentation/avkit/avplayerviewcontroller/player","kind":"symbol","role":"symbol"},"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/skipToPreviousItem(for:)":{"abstract":[{"text":"Tells the delegate when the user requests skipping to the previous item in the timeline.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/skipToPreviousItem(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skipToPreviousItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerViewController","text":"AVPlayerViewController"},{"kind":"text","text":")"}],"title":"skipToPreviousItem(for:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"skipToPreviousItemForPlayerViewController:"}],"url":"/documentation/avkit/avplayerviewcontrollerdelegate/skiptopreviousitem(for:)"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"beta":false,"introducedAt":"10.0","unavailable":false,"name":"tvOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","value":"skipToNextItemForPlayerViewController:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"skipToNextItemForPlayerViewController:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate"]]},"op":"replace"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Responding to Navigation Events","generated":true,"identifiers":["doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:timeToSeekAfterUserNavigatedFrom:to:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/playerViewController(_:willResumePlaybackAfterUserNavigatedFrom:to:)","doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate/skipToPreviousItem(for:)"],"anchor":"Responding-to-Navigation-Events"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"skipToNextItemForPlayerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","identifier":"doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController","text":"AVPlayerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"playerViewController","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The player view controller.","type":"text"}]}],"name":"playerViewController"}]}},{"value":"AVPlayerViewControllerDelegate","op":"replace","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/title"},{"value":[{"kind":"identifier","text":"AVPlayerViewControllerDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/fragments"},{"value":[{"kind":"identifier","text":"AVPlayerViewControllerDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/navigatorTitle"},{"value":"AVPlayerViewControllerSkippingBehaviorSkipItem","op":"replace","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerSkippingBehavior~1skipItem/title"},{"value":[{"kind":"identifier","text":"AVPlayerViewControllerSkippingBehaviorSkipItem"}],"op":"replace","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerSkippingBehavior~1skipItem/fragments"},{"value":"playerViewController:timeToSeekAfterUserNavigatedFromTime:toTime:","op":"replace","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:timeToSeekAfterUserNavigatedFrom:to:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerViewController:timeToSeekAfterUserNavigatedFromTime:toTime:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:timeToSeekAfterUserNavigatedFrom:to:)/fragments"},{"value":"AVPlayerViewController","op":"replace","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/title"},{"value":[{"text":"AVPlayerViewController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/fragments"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/navigatorTitle","value":[{"text":"AVPlayerViewController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:willResumePlaybackAfterUserNavigatedFrom:to:)/title","value":"playerViewController:willResumePlaybackAfterUserNavigatedFromTime:toTime:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1playerViewController(_:willResumePlaybackAfterUserNavigatedFrom:to:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerViewController:willResumePlaybackAfterUserNavigatedFromTime:toTime:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1skipToNextItem(for:)/title","value":"skipToNextItemForPlayerViewController:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1skipToNextItem(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"skipToNextItemForPlayerViewController:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1player/title","value":"player","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1player/fragments","value":[{"kind":"identifier","text":"player"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1skipToPreviousItem(for:)/title","value":"skipToPreviousItemForPlayerViewController:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate~1skipToPreviousItem(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"skipToPreviousItemForPlayerViewController:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}