{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/webkit/domnode/baseuri"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/webkit/domnode/baseuri"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/DOMNode"]]},"identifier":{"url":"doc://com.apple.webkit/documentation/WebKit/DOMNode/baseURI","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"WebKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"baseURI","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","externalID":"c:objc(cs)DOMNode(py)baseURI","roleHeading":"Instance Property","navigatorTitle":[{"text":"baseURI","kind":"identifier"}],"title":"baseURI","platforms":[{"unavailable":false,"beta":false,"deprecatedAt":"10.14","introducedAt":"10.5","deprecated":false,"name":"macOS"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseURI","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:SS","text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}]}],"references":{"doc://com.apple.webkit/documentation/WebKit/DOMNode":{"url":"/documentation/webkit/domnode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMNode","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"DOMNode","kind":"identifier"}],"deprecated":true,"title":"DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","abstract":[]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/baseURI":{"url":"/documentation/webkit/domnode/baseuri","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseURI","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"baseURI","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/baseURI","deprecated":true,"abstract":[],"navigatorTitle":[{"text":"baseURI","kind":"identifier"}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"role":"symbol","kind":"symbol","title":"NSString","url":"/documentation/foundation/nsstring"},"doc://com.externally.resolved.symbol/s:SS":{"type":"topic","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SS","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"role":"symbol","kind":"symbol","title":"String","url":"/documentation/Swift/String"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"10.5","beta":false,"deprecatedAt":"10.14","unavailable":false,"deprecated":false,"name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"baseURI","path":"/metadata/title"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"baseURI","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/DOMNode"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"baseURI"},{"kind":"text","text":";"}],"platforms":["macOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"DOMNode","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/fragments","value":[{"text":"DOMNode","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/navigatorTitle","value":[{"kind":"identifier","text":"DOMNode"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1baseURI/title","value":"baseURI","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1baseURI/fragments","value":[{"kind":"identifier","text":"baseURI"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}