{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/DOMNode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"isSupported::","kind":"identifier"}],"role":"symbol","platforms":[{"name":"macOS","deprecatedAt":"10.5","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"10.4"}],"title":"isSupported::","fragments":[{"text":"- ","kind":"text"},{"text":"isSupported::","kind":"identifier"}],"modules":[{"name":"WebKit"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)DOMNode(im)isSupported::"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isSupported:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"feature"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"version"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc://com.apple.webkit/documentation/WebKit/DOMNode/isSupported::","interfaceLanguage":"occ"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/webkit/domnode/issupported::"]}],"references":{"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.apple.webkit/documentation/WebKit/DOMNode":{"url":"/documentation/webkit/domnode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMNode","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"DOMNode","kind":"identifier"}],"deprecated":true,"title":"DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","abstract":[]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/isSupported::":{"url":"/documentation/webkit/domnode/issupported::","title":"isSupported::","fragments":[{"text":"- ","kind":"text"},{"text":"isSupported::","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"isSupported::","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/isSupported::","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"role":"symbol","kind":"symbol","title":"NSString","url":"/documentation/foundation/nsstring"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"url":"/documentation/objectivec/bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOMNode","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOMNode"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/fragments","op":"replace"},{"value":[{"text":"DOMNode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/navigatorTitle","op":"replace"},{"value":[{"type":"text","text":"A static, plain-text Unicode string object."}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}