{"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"nodeValue","kind":"identifier"}],"externalID":"c:objc(cs)DOMNode(py)nodeValue","title":"nodeValue","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"WebKit"}],"platforms":[{"introducedAt":"10.4","deprecated":false,"beta":false,"name":"macOS","unavailable":false,"deprecatedAt":"10.14"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"nodeValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/DOMNode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeValue"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/webkit/domnode/nodevalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/webkit/domnode/nodevalue"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nodeValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeValue":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeValue","type":"topic","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"nodeValue","kind":"identifier"}],"url":"/documentation/webkit/domnode/nodevalue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nodeValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"deprecated":true,"title":"nodeValue"},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.externally.resolved.symbol/s:SS":{"type":"topic","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SS","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"role":"symbol","kind":"symbol","title":"String","url":"/documentation/Swift/String"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"role":"symbol","kind":"symbol","title":"NSString","url":"/documentation/foundation/nsstring"},"doc://com.apple.webkit/documentation/WebKit/DOMNode":{"url":"/documentation/webkit/domnode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMNode","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"DOMNode","kind":"identifier"}],"deprecated":true,"title":"DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecatedAt":"10.14","unavailable":false,"beta":false,"introducedAt":"10.4","name":"macOS","deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"nodeValue","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"nodeValue","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/DOMNode"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"nodeValue","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1nodeValue/title","value":"nodeValue","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1nodeValue/fragments","value":[{"text":"nodeValue","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/title","value":"DOMNode","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/fragments","value":[{"text":"DOMNode","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/navigatorTitle","value":[{"kind":"identifier","text":"DOMNode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}