{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"replaceChild:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"newChild"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"oldChild"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/DOMNode"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/webkit/domnode/replacechild::"]}],"sections":[],"metadata":{"externalID":"c:objc(cs)DOMNode(im)replaceChild::","modules":[{"name":"WebKit"}],"symbolKind":"method","platforms":[{"beta":false,"name":"macOS","deprecatedAt":"10.5","introducedAt":"10.4","deprecated":false,"unavailable":false}],"roleHeading":"Instance Method","role":"symbol","title":"replaceChild::","fragments":[{"text":"- ","kind":"text"},{"text":"replaceChild::","kind":"identifier"}],"navigatorTitle":[{"text":"replaceChild::","kind":"identifier"}]},"identifier":{"url":"doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild::","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild::":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild::","abstract":[],"type":"topic","url":"/documentation/webkit/domnode/replacechild::","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"replaceChild::"}],"kind":"symbol","title":"replaceChild::","navigatorTitle":[{"kind":"identifier","text":"replaceChild::"}]},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.apple.webkit/documentation/WebKit/DOMNode":{"url":"/documentation/webkit/domnode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMNode","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"DOMNode","kind":"identifier"}],"deprecated":true,"title":"DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","abstract":[]},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/title","op":"replace","value":"DOMNode"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/fragments","op":"replace","value":[{"text":"DOMNode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOMNode"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}