{"sections":[],"identifier":{"url":"doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild(_:oldChild:)","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/webkit/domnode/replacechild(_:oldchild:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/webkit/domnode/replacechild(_:oldchild:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/DOMNode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replaceChild","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"newChild","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"oldChild","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"WebKit"}],"platforms":[{"unavailable":false,"beta":false,"introducedAt":"10.5","name":"macOS","deprecatedAt":"10.14","deprecated":false}],"symbolKind":"method","role":"symbol","externalID":"c:objc(cs)DOMNode(im)replaceChild:oldChild:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceChild"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"oldChild"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!"}],"roleHeading":"Instance Method","title":"replaceChild(_:oldChild:)","navigatorTitle":[{"kind":"identifier","text":"replaceChild:oldChild:"}]},"kind":"symbol","references":{"doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild(_:oldChild:)":{"role":"symbol","deprecated":true,"url":"/documentation/webkit/domnode/replacechild(_:oldchild:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceChild"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"oldChild"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode"},{"kind":"text","text":"!"}],"type":"topic","title":"replaceChild(_:oldChild:)","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild(_:oldChild:)","navigatorTitle":[{"kind":"identifier","text":"replaceChild:oldChild:"}],"abstract":[],"kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.apple.webkit/documentation/WebKit/DOMNode":{"url":"/documentation/webkit/domnode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMNode","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"DOMNode","kind":"identifier"}],"deprecated":true,"title":"DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"unavailable":false,"name":"macOS","deprecated":false,"deprecatedAt":"10.14","introducedAt":"10.5"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"replaceChild:oldChild:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"replaceChild:oldChild:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/DOMNode"]]},"path":"/hierarchy","op":"replace"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"replaceChild:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","kind":"typeIdentifier","text":"DOMNode"},{"kind":"text","text":" *) "},{"text":"newChild","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"oldChild:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode"},{"kind":"text","text":" *) "},{"text":"oldChild","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["macOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":"replaceChild:oldChild:","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1replaceChild(_:oldChild:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"replaceChild:oldChild:"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1replaceChild(_:oldChild:)/fragments"},{"op":"replace","value":"DOMNode","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/title"},{"op":"replace","value":[{"text":"DOMNode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/fragments"},{"op":"replace","value":[{"text":"DOMNode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}