{
  "abstract": [
    {
      "text": "An array of ordinal numbers that filters which recurrences to include in the recurrence rule’s frequency.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/setPositions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)EKRecurrenceRule(py)setPositions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setPositions"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setPositions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "setPositions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setPositions"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For example, a yearly recurrence rule that has a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheWeek",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value that specifies Monday through Friday, and a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/setPositions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array containing ",
              "type": "text"
            },
            {
              "code": "2",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "-1",
              "type": "codeVoice"
            },
            {
              "text": ", occurs only on the second weekday and last weekday of every year. Values can be from ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "366",
              "type": "codeVoice"
            },
            {
              "text": " and from ",
              "type": "text"
            },
            {
              "code": "-1",
              "type": "codeVoice"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "-366",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Negative values indicate counting backwards from the end of the recurrence rule’s frequency (week, month, or year).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceDayOfWeek": {
      "abstract": [
        {
          "text": "A class that represents the day of the week.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKRecurrenceDayOfWeek"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceDayOfWeek",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKRecurrenceDayOfWeek"
        }
      ],
      "role": "symbol",
      "title": "EKRecurrenceDayOfWeek",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencedayofweek"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceFrequency": {
      "abstract": [
        {
          "text": "The frequency for recurrence rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKRecurrenceFrequency"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKRecurrenceFrequency"
        }
      ],
      "role": "symbol",
      "title": "EKRecurrenceFrequency",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencefrequency"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule": {
      "abstract": [
        {
          "text": "A class that describes the pattern for a recurring event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKRecurrenceRule"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKRecurrenceRule"
        }
      ],
      "role": "symbol",
      "title": "EKRecurrenceRule",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/calendarIdentifier": {
      "abstract": [
        {
          "text": "The identifier for the recurrence rule’s calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/calendarIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "calendarIdentifier"
        }
      ],
      "role": "symbol",
      "title": "calendarIdentifier",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/calendaridentifier"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheMonth": {
      "abstract": [
        {
          "text": "The days of the month associated with the recurrence rule, as an array of ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daysOfTheMonth"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheMonth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "daysOfTheMonth"
        }
      ],
      "role": "symbol",
      "title": "daysOfTheMonth",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/daysofthemonth"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheWeek": {
      "abstract": [
        {
          "text": "The days of the week associated with the recurrence rule, as an array of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceDayOfWeek",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daysOfTheWeek"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKRecurrenceDayOfWeek",
          "text": "EKRecurrenceDayOfWeek"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheWeek",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "daysOfTheWeek"
        }
      ],
      "role": "symbol",
      "title": "daysOfTheWeek",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/daysoftheweek"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheYear": {
      "abstract": [
        {
          "text": "The days of the year associated with the recurrence rule, as an array of ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daysOfTheYear"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheYear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "daysOfTheYear"
        }
      ],
      "role": "symbol",
      "title": "daysOfTheYear",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/daysoftheyear"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/firstDayOfTheWeek": {
      "abstract": [
        {
          "text": "Indicates which day of the week the recurrence rule treats as the first day of the week.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstDayOfTheWeek"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/firstDayOfTheWeek",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "firstDayOfTheWeek"
        }
      ],
      "role": "symbol",
      "title": "firstDayOfTheWeek",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/firstdayoftheweek"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/frequency": {
      "abstract": [
        {
          "text": "The frequency of the recurrence rule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKRecurrenceFrequency",
          "text": "EKRecurrenceFrequency"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/frequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frequency"
        }
      ],
      "role": "symbol",
      "title": "frequency",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/frequency"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/interval": {
      "abstract": [
        {
          "text": "Specifies how often the recurrence rule repeats over the unit of time indicated by its frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/interval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interval"
        }
      ],
      "role": "symbol",
      "title": "interval",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/interval"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/monthsOfTheYear": {
      "abstract": [
        {
          "text": "The months of the year associated with the recurrence rule, as an array of ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthsOfTheYear"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/monthsOfTheYear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "monthsOfTheYear"
        }
      ],
      "role": "symbol",
      "title": "monthsOfTheYear",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/monthsoftheyear"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/recurrenceEnd": {
      "abstract": [
        {
          "text": "Indicates when the recurrence rule ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recurrenceEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKRecurrenceEnd",
          "text": "EKRecurrenceEnd"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/recurrenceEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recurrenceEnd"
        }
      ],
      "role": "symbol",
      "title": "recurrenceEnd",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/recurrenceend"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/setPositions": {
      "abstract": [
        {
          "text": "An array of ordinal numbers that filters which recurrences to include in the recurrence rule’s frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPositions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/setPositions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPositions"
        }
      ],
      "role": "symbol",
      "title": "setPositions",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/setpositions"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/weeksOfTheYear": {
      "abstract": [
        {
          "text": "The weeks of the year associated with the recurrence rule, as an array of ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weeksOfTheYear"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/weeksOfTheYear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "weeksOfTheYear"
        }
      ],
      "role": "symbol",
      "title": "weeksOfTheYear",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule/weeksoftheyear"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE()": {
      "abstract": [
        {
          "text": "A deprecated function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE"
        }
      ],
      "role": "symbol",
      "title": "EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE()",
      "type": "topic",
      "url": "/documentation/eventkit/ek_lose_fractional_seconds_do_not_use()"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Recurrence-Rule-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceFrequency",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/calendarIdentifier",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/recurrenceEnd",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/frequency",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/interval",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/firstDayOfTheWeek",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheWeek",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheMonth",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheYear",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/weeksOfTheYear",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/monthsOfTheYear",
        "doc://com.apple.eventkit/documentation/EventKit/EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE()"
      ],
      "title": "Accessing Recurrence Rule Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setPositions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "setPositions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Recurrence-Rule-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceFrequency",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/calendarIdentifier",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/recurrenceEnd",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/frequency",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/interval",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/firstDayOfTheWeek",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheWeek",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheMonth",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/daysOfTheYear",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/weeksOfTheYear",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule/monthsOfTheYear",
                "doc://com.apple.eventkit/documentation/EventKit/EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE()"
              ],
              "title": "Accessing Recurrence Rule Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSNumber *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "setPositions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1daysOfTheYear/title",
          "value": "daysOfTheYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1daysOfTheYear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "daysOfTheYear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1firstDayOfTheWeek/title",
          "value": "firstDayOfTheWeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1firstDayOfTheWeek/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "firstDayOfTheWeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1monthsOfTheYear/title",
          "value": "monthsOfTheYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1monthsOfTheYear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "monthsOfTheYear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceFrequency/title",
          "value": "EKRecurrenceFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceFrequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceFrequency/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1daysOfTheWeek/title",
          "value": "daysOfTheWeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1daysOfTheWeek/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "daysOfTheWeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1frequency/title",
          "value": "frequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1frequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1setPositions/title",
          "value": "setPositions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1setPositions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "setPositions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE()/title",
          "value": "EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EK_LOSE_FRACTIONAL_SECONDS_DO_NOT_USE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1interval/title",
          "value": "interval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1interval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1daysOfTheMonth/title",
          "value": "daysOfTheMonth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1daysOfTheMonth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "daysOfTheMonth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1weeksOfTheYear/title",
          "value": "weeksOfTheYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1weeksOfTheYear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "weeksOfTheYear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceDayOfWeek/title",
          "value": "EKRecurrenceDayOfWeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceDayOfWeek/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceDayOfWeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceDayOfWeek/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceDayOfWeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1recurrenceEnd/title",
          "value": "recurrenceEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1recurrenceEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recurrenceEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule/title",
          "value": "EKRecurrenceRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1calendarIdentifier/title",
          "value": "calendarIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule~1calendarIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "calendarIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekrecurrencerule/setpositions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekrecurrencerule/setpositions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
