{"abstract":[{"text":"Returns the index of the tick mark closest to the location of the slider represented by the given point.","type":"text"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)","interfaceLanguage":"swift"},"metadata":{"platforms":[{"name":"macOS","unavailable":false,"beta":false,"deprecated":false}],"roleHeading":"Instance Method","externalID":"c:objc(cs)NSSlider(im)indexOfTickMarkAtPoint:","navigatorTitle":[{"kind":"identifier","text":"indexOfTickMarkAtPoint:"}],"modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexOfTickMark"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"indexOfTickMark(at:)","symbolKind":"method","role":"symbol","extendedModule":"AppKit"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsslider/indexoftickmark(at:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsslider/indexoftickmark(at:)"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly","doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks","doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property","doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)"],"generated":true,"title":"Managing Tick Marks","anchor":"Managing-Tick-Marks"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfTickMark","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"point","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"point","content":[{"inlineContent":[{"text":"The point representing the location for which to retrieve the tick mark.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The index of the tick mark closest to the location specified by ","type":"text"},{"type":"codeVoice","code":"point"},{"text":". If ","type":"text"},{"type":"codeVoice","code":"point"},{"text":" is not within the bounding rectangle (plus an extra pixel of space) of any tick mark, the method returns ","type":"text"},{"type":"codeVoice","code":"NSNotFound"},{"text":".","type":"text"}]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"In its implementation of this method, the receiving ","type":"text"},{"type":"codeVoice","code":"NSSlider"},{"text":" instance invokes the method of the same name of its ","type":"text"},{"type":"codeVoice","code":"NSSliderCell"},{"text":" instance. This method invokes ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)","isActive":true},{"text":" for each tick mark on the slider until it finds a tick mark containing the point.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.externally.resolved.symbol/c:@T@NSPoint":{"abstract":[{"text":"A point in a Cartesian coordinate system.","type":"text"}],"url":"/documentation/foundation/nspoint","kind":"symbol","role":"symbol","title":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","type":"topic","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSPoint","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider","url":"/documentation/appkit/nsslider","navigatorTitle":[{"kind":"identifier","text":"NSSlider"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSSlider","kind":"identifier"}],"type":"topic","title":"NSSlider","role":"symbol","abstract":[{"text":"A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)":{"title":"rectOfTickMark(at:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rectOfTickMark"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"}],"abstract":[{"text":"Returns the bounding rectangle of the tick mark at the given index.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rectOfTickMarkAtIndex:"}],"role":"symbol","url":"/documentation/appkit/nsslider/rectoftickmark(at:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property":{"title":"tickMarkPosition","navigatorTitle":[{"text":"tickMarkPosition","kind":"identifier"}],"role":"symbol","url":"/documentation/appkit/nsslider/tickmarkposition-swift.property","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property","kind":"symbol","abstract":[{"type":"text","text":"Determines where the slider’s tick marks are displayed."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tickMarkPosition"},{"text":": ","kind":"text"},{"text":"NSSlider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSlider"},{"text":".","kind":"text"},{"text":"TickMarkPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTickMarkPosition"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)":{"title":"closestTickMarkValue(toValue:)","navigatorTitle":[{"kind":"identifier","text":"closestTickMarkValueToValue:"}],"role":"symbol","url":"/documentation/appkit/nsslider/closesttickmarkvalue(tovalue:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)","kind":"symbol","abstract":[{"type":"text","text":"Returns the value of the tick mark closest to the specified value."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"closestTickMarkValue"},{"text":"(","kind":"text"},{"text":"toValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks":{"title":"numberOfTickMarks","navigatorTitle":[{"kind":"identifier","text":"numberOfTickMarks"}],"role":"symbol","url":"/documentation/appkit/nsslider/numberoftickmarks","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks","kind":"symbol","abstract":[{"text":"The number of tick marks associated with the slider.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numberOfTickMarks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)":{"title":"indexOfTickMark(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfTickMark","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"text":"Returns the index of the tick mark closest to the location of the slider represented by the given point.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"indexOfTickMarkAtPoint:"}],"role":"symbol","url":"/documentation/appkit/nsslider/indexoftickmark(at:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum":{"url":"/documentation/appkit/nsslider/tickmarkposition-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TickMarkPosition","kind":"identifier"}],"title":"NSSlider.TickMarkPosition","kind":"symbol","abstract":[{"text":"The position where a linear slider’s tick marks appear (above, below, leading, or trailing).","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum","role":"symbol","type":"topic","navigatorTitle":[{"text":"TickMarkPosition","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)":{"title":"tickMarkValue(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tickMarkValue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Returns the slider’s value represented by the tick mark at the specified index.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tickMarkValueAtIndex:"}],"role":"symbol","url":"/documentation/appkit/nsslider/tickmarkvalue(at:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly":{"title":"allowsTickMarkValuesOnly","navigatorTitle":[{"kind":"identifier","text":"allowsTickMarkValuesOnly"}],"role":"symbol","url":"/documentation/appkit/nsslider/allowstickmarkvaluesonly","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the slider fixes its values to those values represented by its tick marks."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsTickMarkValuesOnly","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"indexOfTickMarkAtPoint:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"indexOfTickMarkAtPoint:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"anchor":"Managing-Tick-Marks","title":"Managing Tick Marks","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly","doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks","doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property","doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"indexOfTickMarkAtPoint:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"point"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The point representing the location for which to retrieve the tick mark.","type":"text"}]}],"name":"point"}],"kind":"parameters"}},{"op":"replace","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The index of the tick mark closest to the location specified by "},{"type":"codeVoice","code":"point"},{"type":"text","text":". If "},{"type":"codeVoice","code":"point"},{"type":"text","text":" is not within the bounding rectangle (plus an extra pixel of space) of any tick mark, the method returns "},{"type":"codeVoice","code":"NSNotFound"},{"type":"text","text":"."}]}]},"path":"/primaryContentSections/2"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title","op":"replace","value":"NSSlider"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments","op":"replace","value":[{"text":"NSSlider","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle","op":"replace","value":[{"text":"NSSlider","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1rectOfTickMark(at:)/title","op":"replace","value":"rectOfTickMarkAtIndex:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1rectOfTickMark(at:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rectOfTickMarkAtIndex:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkPosition-swift.property/title","op":"replace","value":"tickMarkPosition"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkPosition-swift.property/fragments","op":"replace","value":[{"text":"tickMarkPosition","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1closestTickMarkValue(toValue:)/title","op":"replace","value":"closestTickMarkValueToValue:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closestTickMarkValueToValue:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1closestTickMarkValue(toValue:)/fragments"},{"value":"numberOfTickMarks","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1numberOfTickMarks/title"},{"value":[{"text":"numberOfTickMarks","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1numberOfTickMarks/fragments"},{"value":"indexOfTickMarkAtPoint:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1indexOfTickMark(at:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfTickMarkAtPoint:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1indexOfTickMark(at:)/fragments"},{"value":"NSTickMarkPosition","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/title"},{"value":[{"text":"NSTickMarkPosition","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/fragments"},{"value":[{"kind":"identifier","text":"NSTickMarkPosition"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/navigatorTitle"},{"value":"tickMarkValueAtIndex:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkValue(at:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tickMarkValueAtIndex:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkValue(at:)/fragments"},{"value":"allowsTickMarkValuesOnly","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1allowsTickMarkValuesOnly/title"},{"value":[{"kind":"identifier","text":"allowsTickMarkValuesOnly"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1allowsTickMarkValuesOnly/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}