{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Slider/Slider.html#//apple_ref/doc/uid/10000025i"],"anchor":"Related-Documentation"},{"title":"Creating Sliders","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/init(value:minValue:maxValue:target:action:)"],"generated":true,"anchor":"Creating-Sliders"}],"metadata":{"platforms":[{"introducedAt":"10.12","unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"title":"init(target:action:)","extendedModule":"AppKit","navigatorTitle":[{"text":"sliderWithTarget:action:","kind":"identifier"}],"role":"symbol","symbolKind":"init","modules":[{"name":"AppKit"}],"roleHeading":"Initializer","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"c:objc(cs)NSSlider(cm)sliderWithTarget:action:"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSSlider/init(target:action:)"},"abstract":[{"type":"text","text":"Creates a continuous horizontal slider whose values range from "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":" to "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","kind":"typeIdentifier","text":"Selector"},{"kind":"text","text":"?)"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"target","content":[{"type":"paragraph","inlineContent":[{"text":"The target object that receives action messages from the control.","type":"text"}]}]},{"name":"action","content":[{"inlineContent":[{"type":"text","text":"The action message sent by the control."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An initialized slider control.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["/documentation/appkit/nsslider/init(target:action:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsslider/init(target:action:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:@T@SEL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","type":"topic","abstract":[{"type":"text","text":"Defines an opaque type that represents a method selector."}],"url":"/documentation/objectivec/sel","title":"SEL","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV":{"type":"topic","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Selector"}],"url":"/documentation/objectivec/selector","title":"Selector","abstract":[{"type":"text","text":""}],"identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/init(target:action:)":{"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","url":"/documentation/appkit/nsslider/init(target:action:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/init(target:action:)","abstract":[{"text":"Creates a continuous horizontal slider whose values range from ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":" to ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","title":"init(target:action:)","navigatorTitle":[{"kind":"identifier","text":"sliderWithTarget:action:"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider","url":"/documentation/appkit/nsslider","navigatorTitle":[{"kind":"identifier","text":"NSSlider"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSSlider","kind":"identifier"}],"type":"topic","title":"NSSlider","role":"symbol","abstract":[{"text":"A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/init(value:minValue:maxValue:target:action:)":{"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":"?)"}],"role":"symbol","url":"/documentation/appkit/nsslider/init(value:minvalue:maxvalue:target:action:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/init(value:minValue:maxValue:target:action:)","abstract":[{"text":"Creates a continuous horizontal slider that represents values over the specified range.","type":"text"}],"kind":"symbol","title":"init(value:minValue:maxValue:target:action:)","navigatorTitle":[{"kind":"identifier","text":"sliderWithValue:minValue:maxValue:target:action:"}]},"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Slider/Slider.html#//apple_ref/doc/uid/10000025i":{"titleInlineContent":[{"text":"Slider Programming Topics","type":"text"}],"url":"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Slider/Slider.html#//apple_ref/doc/uid/10000025i","type":"link","identifier":"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Slider/Slider.html#//apple_ref/doc/uid/10000025i","title":"Slider Programming Topics"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"value":[{"deprecated":false,"introducedAt":"10.12","name":"macOS","beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Type Method","op":"replace","path":"/metadata/roleHeading"},{"value":"sliderWithTarget:action:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sliderWithTarget:action:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Slider/Slider.html#//apple_ref/doc/uid/10000025i"]},{"anchor":"Creating-Sliders","generated":true,"title":"Creating Sliders","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/init(value:minValue:maxValue:target:action:)"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"sliderWithTarget:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"target","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"action:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","text":"SEL","kind":"typeIdentifier","preciseIdentifier":"c:@T@SEL"},{"text":") ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"target","content":[{"inlineContent":[{"type":"text","text":"The target object that receives action messages from the control."}],"type":"paragraph"}]},{"name":"action","content":[{"inlineContent":[{"text":"The action message sent by the control.","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"value":{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An initialized slider control."}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"/primaryContentSections/2"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1init(target:action:)/title","value":"sliderWithTarget:action:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1init(target:action:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sliderWithTarget:action:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title","value":"NSSlider","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments","value":[{"kind":"identifier","text":"NSSlider"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle","value":[{"kind":"identifier","text":"NSSlider"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1init(value:minValue:maxValue:target:action:)/title","value":"sliderWithValue:minValue:maxValue:target:action:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1init(value:minValue:maxValue:target:action:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sliderWithValue:minValue:maxValue:target:action:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}