{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsslider/numberoftickmarks"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsslider/numberoftickmarks"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTickMarks"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]},{"content":[{"anchor":"Discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This property includes tick marks assigned to the minimum and maximum values. In its implementation of this property, the receiving "},{"type":"codeVoice","code":"NSSlider"},{"type":"text","text":" instance invokes the method of the same name of its "},{"type":"codeVoice","code":"NSSliderCell"},{"type":"text","text":" instance. By default, this value is 0, and no tick marks appear. The number of tick marks assigned to a slider, along with the slider’s minimum and maximum values, determines the values associated with the tick marks."}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"title":"Managing Tick Marks","generated":true,"anchor":"Managing-Tick-Marks","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly","doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property","doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)"]}],"abstract":[{"type":"text","text":"The number of tick marks associated with the slider."}],"metadata":{"externalID":"c:objc(cs)NSSlider(py)numberOfTickMarks","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfTickMarks","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"roleHeading":"Instance Property","extendedModule":"AppKit","navigatorTitle":[{"kind":"identifier","text":"numberOfTickMarks"}],"modules":[{"name":"AppKit"}],"title":"numberOfTickMarks","symbolKind":"property","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSSlider":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider","url":"/documentation/appkit/nsslider","navigatorTitle":[{"kind":"identifier","text":"NSSlider"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSSlider","kind":"identifier"}],"type":"topic","title":"NSSlider","role":"symbol","abstract":[{"text":"A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)":{"title":"rectOfTickMark(at:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rectOfTickMark"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"}],"abstract":[{"text":"Returns the bounding rectangle of the tick mark at the given index.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rectOfTickMarkAtIndex:"}],"role":"symbol","url":"/documentation/appkit/nsslider/rectoftickmark(at:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)":{"title":"indexOfTickMark(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfTickMark","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"text":"Returns the index of the tick mark closest to the location of the slider represented by the given point.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"indexOfTickMarkAtPoint:"}],"role":"symbol","url":"/documentation/appkit/nsslider/indexoftickmark(at:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum":{"url":"/documentation/appkit/nsslider/tickmarkposition-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TickMarkPosition","kind":"identifier"}],"title":"NSSlider.TickMarkPosition","kind":"symbol","abstract":[{"text":"The position where a linear slider’s tick marks appear (above, below, leading, or trailing).","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum","role":"symbol","type":"topic","navigatorTitle":[{"text":"TickMarkPosition","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks":{"title":"numberOfTickMarks","navigatorTitle":[{"kind":"identifier","text":"numberOfTickMarks"}],"role":"symbol","url":"/documentation/appkit/nsslider/numberoftickmarks","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks","kind":"symbol","abstract":[{"text":"The number of tick marks associated with the slider.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numberOfTickMarks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property":{"title":"tickMarkPosition","navigatorTitle":[{"text":"tickMarkPosition","kind":"identifier"}],"role":"symbol","url":"/documentation/appkit/nsslider/tickmarkposition-swift.property","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property","kind":"symbol","abstract":[{"type":"text","text":"Determines where the slider’s tick marks are displayed."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tickMarkPosition"},{"text":": ","kind":"text"},{"text":"NSSlider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSlider"},{"text":".","kind":"text"},{"text":"TickMarkPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTickMarkPosition"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly":{"title":"allowsTickMarkValuesOnly","navigatorTitle":[{"kind":"identifier","text":"allowsTickMarkValuesOnly"}],"role":"symbol","url":"/documentation/appkit/nsslider/allowstickmarkvaluesonly","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the slider fixes its values to those values represented by its tick marks."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsTickMarkValuesOnly","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)":{"title":"tickMarkValue(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tickMarkValue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Returns the slider’s value represented by the tick mark at the specified index.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tickMarkValueAtIndex:"}],"role":"symbol","url":"/documentation/appkit/nsslider/tickmarkvalue(at:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)":{"title":"closestTickMarkValue(toValue:)","navigatorTitle":[{"kind":"identifier","text":"closestTickMarkValueToValue:"}],"role":"symbol","url":"/documentation/appkit/nsslider/closesttickmarkvalue(tovalue:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)","kind":"symbol","abstract":[{"type":"text","text":"Returns the value of the tick mark closest to the specified value."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"closestTickMarkValue"},{"text":"(","kind":"text"},{"text":"toValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"numberOfTickMarks"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"numberOfTickMarks"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Managing-Tick-Marks","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly","doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property","doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)"],"title":"Managing Tick Marks","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"numberOfTickMarks","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title","value":"NSSlider"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments","value":[{"text":"NSSlider","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle","value":[{"kind":"identifier","text":"NSSlider"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1rectOfTickMark(at:)/title","value":"rectOfTickMarkAtIndex:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1rectOfTickMark(at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rectOfTickMarkAtIndex:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1indexOfTickMark(at:)/title","value":"indexOfTickMarkAtPoint:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1indexOfTickMark(at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfTickMarkAtPoint:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/title","value":"NSTickMarkPosition"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/fragments","value":[{"kind":"identifier","text":"NSTickMarkPosition"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/navigatorTitle","value":[{"text":"NSTickMarkPosition","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1numberOfTickMarks/title","value":"numberOfTickMarks"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1numberOfTickMarks/fragments","value":[{"kind":"identifier","text":"numberOfTickMarks"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkPosition-swift.property/title","value":"tickMarkPosition"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkPosition-swift.property/fragments","value":[{"text":"tickMarkPosition","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1allowsTickMarkValuesOnly/title","value":"allowsTickMarkValuesOnly"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1allowsTickMarkValuesOnly/fragments","value":[{"kind":"identifier","text":"allowsTickMarkValuesOnly"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkValue(at:)/title","value":"tickMarkValueAtIndex:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkValue(at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tickMarkValueAtIndex:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1closestTickMarkValue(toValue:)/title","value":"closestTickMarkValueToValue:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1closestTickMarkValue(toValue:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"closestTickMarkValueToValue:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}