{"metadata":{"navigatorTitle":[{"text":"rectOfTickMarkAtIndex:","kind":"identifier"}],"externalID":"c:objc(cs)NSSlider(im)rectOfTickMarkAtIndex:","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"roleHeading":"Instance Method","symbolKind":"method","extendedModule":"AppKit","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rectOfTickMark","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"modules":[{"name":"AppKit"}],"title":"rectOfTickMark(at:)","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)"},"kind":"symbol","abstract":[{"text":"Returns the bounding rectangle of the tick mark at the given index.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"variants":[{"paths":["/documentation/appkit/nsslider/rectoftickmark(at:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsslider/rectoftickmark(at:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"seeAlsoSections":[{"generated":true,"anchor":"Managing-Tick-Marks","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly","doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property","doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)"],"title":"Managing Tick Marks"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rectOfTickMark","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"index","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","preciseIdentifier":"c:@T@NSRect"}],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index of the tick mark for which to retrieve the bounds.  The minimum-value tick mark is at index "},{"code":"0","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"index"}]},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"The bounding rectangle of the specified tick mark.","type":"text"}]}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"If no tick mark is associated with "},{"code":"index","type":"codeVoice"},{"type":"text","text":", the method raises "},{"code":"NSRangeException","type":"codeVoice"},{"type":"text","text":". In its implementation of this method, the receiving "},{"code":"NSSlider","type":"codeVoice"},{"type":"text","text":" instance invokes the method of the same name of its "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSliderCell","type":"reference","isActive":true},{"type":"text","text":" instance."}]}],"kind":"content"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)":{"title":"rectOfTickMark(at:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rectOfTickMark"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"}],"abstract":[{"text":"Returns the bounding rectangle of the tick mark at the given index.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rectOfTickMarkAtIndex:"}],"role":"symbol","url":"/documentation/appkit/nsslider/rectoftickmark(at:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum":{"url":"/documentation/appkit/nsslider/tickmarkposition-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TickMarkPosition","kind":"identifier"}],"title":"NSSlider.TickMarkPosition","kind":"symbol","abstract":[{"text":"The position where a linear slider’s tick marks appear (above, below, leading, or trailing).","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum","role":"symbol","type":"topic","navigatorTitle":[{"text":"TickMarkPosition","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks":{"title":"numberOfTickMarks","navigatorTitle":[{"kind":"identifier","text":"numberOfTickMarks"}],"role":"symbol","url":"/documentation/appkit/nsslider/numberoftickmarks","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks","kind":"symbol","abstract":[{"text":"The number of tick marks associated with the slider.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numberOfTickMarks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly":{"title":"allowsTickMarkValuesOnly","navigatorTitle":[{"kind":"identifier","text":"allowsTickMarkValuesOnly"}],"role":"symbol","url":"/documentation/appkit/nsslider/allowstickmarkvaluesonly","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the slider fixes its values to those values represented by its tick marks."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsTickMarkValuesOnly","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.apple.appkit/documentation/AppKit/NSSliderCell":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The appearance and behavior of an "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider","type":"reference"},{"type":"text","text":" object."}],"kind":"symbol","url":"/documentation/appkit/nsslidercell","title":"NSSliderCell","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSliderCell","navigatorTitle":[{"kind":"identifier","text":"NSSliderCell"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSSliderCell"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property":{"title":"tickMarkPosition","navigatorTitle":[{"text":"tickMarkPosition","kind":"identifier"}],"role":"symbol","url":"/documentation/appkit/nsslider/tickmarkposition-swift.property","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property","kind":"symbol","abstract":[{"type":"text","text":"Determines where the slider’s tick marks are displayed."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tickMarkPosition"},{"text":": ","kind":"text"},{"text":"NSSlider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSlider"},{"text":".","kind":"text"},{"text":"TickMarkPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTickMarkPosition"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)":{"title":"indexOfTickMark(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfTickMark","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"text":"Returns the index of the tick mark closest to the location of the slider represented by the given point.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"indexOfTickMarkAtPoint:"}],"role":"symbol","url":"/documentation/appkit/nsslider/indexoftickmark(at:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)":{"title":"tickMarkValue(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tickMarkValue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Returns the slider’s value represented by the tick mark at the specified index.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tickMarkValueAtIndex:"}],"role":"symbol","url":"/documentation/appkit/nsslider/tickmarkvalue(at:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)":{"title":"closestTickMarkValue(toValue:)","navigatorTitle":[{"kind":"identifier","text":"closestTickMarkValueToValue:"}],"role":"symbol","url":"/documentation/appkit/nsslider/closesttickmarkvalue(tovalue:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)","kind":"symbol","abstract":[{"type":"text","text":"Returns the value of the tick mark closest to the specified value."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"closestTickMarkValue"},{"text":"(","kind":"text"},{"text":"toValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider","url":"/documentation/appkit/nsslider","navigatorTitle":[{"kind":"identifier","text":"NSSlider"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSSlider","kind":"identifier"}],"type":"topic","title":"NSSlider","role":"symbol","abstract":[{"text":"A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"rectOfTickMarkAtIndex:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"rectOfTickMarkAtIndex:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly","doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)","doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property","doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)"],"anchor":"Managing-Tick-Marks","title":"Managing Tick Marks","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"text":") ","kind":"text"},{"text":"rectOfTickMarkAtIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"index","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index of the tick mark for which to retrieve the bounds.  The minimum-value tick mark is at index "},{"type":"codeVoice","code":"0"},{"type":"text","text":"."}]}],"name":"index"}]},"path":"/primaryContentSections/1","op":"replace"},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The bounding rectangle of the specified tick mark."}],"type":"paragraph"}]}},{"value":"rectOfTickMarkAtIndex:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1rectOfTickMark(at:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"rectOfTickMarkAtIndex:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1rectOfTickMark(at:)/fragments","op":"replace"},{"value":"NSTickMarkPosition","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/title","op":"replace"},{"value":[{"text":"NSTickMarkPosition","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/fragments","op":"replace"},{"value":[{"text":"NSTickMarkPosition","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/navigatorTitle","op":"replace"},{"value":"numberOfTickMarks","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1numberOfTickMarks/title","op":"replace"},{"value":[{"text":"numberOfTickMarks","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1numberOfTickMarks/fragments","op":"replace"},{"value":"allowsTickMarkValuesOnly","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1allowsTickMarkValuesOnly/title","op":"replace"},{"value":[{"kind":"identifier","text":"allowsTickMarkValuesOnly"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1allowsTickMarkValuesOnly/fragments","op":"replace"},{"value":"NSSliderCell","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell/title","op":"replace"},{"value":[{"text":"NSSliderCell","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSSliderCell"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell/navigatorTitle","op":"replace"},{"value":"tickMarkPosition","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkPosition-swift.property/title","op":"replace"},{"value":[{"kind":"identifier","text":"tickMarkPosition"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkPosition-swift.property/fragments","op":"replace"},{"value":"indexOfTickMarkAtPoint:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1indexOfTickMark(at:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfTickMarkAtPoint:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1indexOfTickMark(at:)/fragments","op":"replace"},{"value":"tickMarkValueAtIndex:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkValue(at:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"tickMarkValueAtIndex:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkValue(at:)/fragments","op":"replace"},{"value":"closestTickMarkValueToValue:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1closestTickMarkValue(toValue:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"closestTickMarkValueToValue:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1closestTickMarkValue(toValue:)/fragments","op":"replace"},{"value":"NSSlider","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title","op":"replace"},{"value":[{"text":"NSSlider","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSSlider"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}