{
  "abstract": [
    {
      "text": "Sets the cell used to draw the slider’s title.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No replacement needed.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSSlider(im)setTitleCell:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "setTitleCell:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setTitleCell:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.9",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setTitleCell:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setTitleCell:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCell",
              "text": "NSCell"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "cell"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The cell used to draw the title.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cell"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You only need to invoke this method if the default title cell, ",
              "type": "text"
            },
            {
              "code": "NSTextFieldCell",
              "type": "codeVoice"
            },
            {
              "text": ", doesn’t suit your needs—that is, you want to display the title in a manner that ",
              "type": "text"
            },
            {
              "code": "NSTextFieldCell",
              "type": "codeVoice"
            },
            {
              "text": " doesn’t permit. When you do choose to override the default, ",
              "type": "text"
            },
            {
              "code": "titleCell",
              "type": "codeVoice"
            },
            {
              "text": " should be an instance of a subclass of ",
              "type": "text"
            },
            {
              "code": "NSTextFieldCell",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell": {
      "abstract": [
        {
          "text": "A mechanism for displaying text or images in a view object without the overhead of a full ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCell"
        }
      ],
      "role": "symbol",
      "title": "NSCell",
      "type": "topic",
      "url": "/documentation/appkit/nscell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider": {
      "abstract": [
        {
          "text": "A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSlider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSlider"
        }
      ],
      "role": "symbol",
      "title": "NSSlider",
      "type": "topic",
      "url": "/documentation/appkit/nsslider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:": {
      "abstract": [
        {
          "text": "Sets the title the slider displays in the bar behind its knob.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitle:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitle:"
        }
      ],
      "role": "symbol",
      "title": "setTitle:",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/settitle:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:": {
      "abstract": [
        {
          "text": "Sets the cell used to draw the slider’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitleCell:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleCell:"
        }
      ],
      "role": "symbol",
      "title": "setTitleCell:",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/settitlecell:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:": {
      "abstract": [
        {
          "text": "Sets the color used to draw the slider’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitleColor:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleColor:"
        }
      ],
      "role": "symbol",
      "title": "setTitleColor:",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/settitlecolor:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:": {
      "abstract": [
        {
          "text": "Sets the font used to draw the slider’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitleFont:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleFont:"
        }
      ],
      "role": "symbol",
      "title": "setTitleFont:",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/settitlefont:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/title": {
      "abstract": [
        {
          "text": "Returns the slider’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/title"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell": {
      "abstract": [
        {
          "text": "This method has been deprecated. Returns ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "titleCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleCell"
        }
      ],
      "role": "symbol",
      "title": "titleCell",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/titlecell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor": {
      "abstract": [
        {
          "text": "This method has been deprecated. Returns ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "titleColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleColor"
        }
      ],
      "role": "symbol",
      "title": "titleColor",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/titlecolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont": {
      "abstract": [
        {
          "text": "This method has been deprecated. Returns ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "titleFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleFont"
        }
      ],
      "role": "symbol",
      "title": "titleFont",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/titlefont"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Sliders-Title",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/title",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:"
      ],
      "title": "Managing the Slider’s Title"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title",
          "value": "NSSlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title",
          "value": "NSCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsslider/settitlecell:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
