{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"seeAlsoSections":[{"title":"Managing the Slider’s Appearance","generated":true,"anchor":"Managing-the-Sliders-Appearance","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSSlider/altIncrementValue","doc://com.apple.appkit/documentation/AppKit/NSSlider/knobThickness","doc://com.apple.appkit/documentation/AppKit/NSSlider/isVertical","doc://com.apple.appkit/documentation/AppKit/NSSlider/trackFillColor"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSlider/sliderType-swift.property","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","platforms":[{"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"10.10","beta":false}],"roleHeading":"Instance Property","modules":[{"name":"AppKit"}],"role":"symbol","externalID":"c:objc(cs)NSSlider(py)sliderType","title":"sliderType","navigatorTitle":[{"text":"sliderType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sliderType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSSlider","preciseIdentifier":"c:objc(cs)NSSlider","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SliderType","preciseIdentifier":"c:@E@NSSliderType","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sliderType","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider","text":"NSSlider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSlider"},{"text":".","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum","text":"SliderType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSSliderType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"See ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum","isActive":true,"type":"reference"},{"text":" for possible values.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsslider/slidertype-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsslider/slidertype-swift.property"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The type of the slider, such as vertical or circular.","type":"text"}],"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SliderType"}],"title":"NSSlider.SliderType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum","url":"/documentation/appkit/nsslider/slidertype-swift.enum","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SliderType"}],"abstract":[{"text":"The types of sliders, used by ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType"},{"text":".","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/trackFillColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackFillColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSColor","preciseIdentifier":"c:objc(cs)NSColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/appkit/nsslider/trackfillcolor","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/trackFillColor","role":"symbol","title":"trackFillColor","navigatorTitle":[{"text":"trackFillColor","kind":"identifier"}],"abstract":[{"type":"text","text":"The color of the filled portion of the slider track, in appearances that support it."}],"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/altIncrementValue":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"altIncrementValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsslider/altincrementvalue","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/altIncrementValue","role":"symbol","title":"altIncrementValue","navigatorTitle":[{"text":"altIncrementValue","kind":"identifier"}],"abstract":[{"type":"text","text":"The amount by which the slider changes its value when the user Option-drags the slider knob."}],"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType":{"abstract":[{"text":"The slider type, either linear or circular.","type":"text"}],"title":"sliderType","url":"/documentation/appkit/nsslidercell/slidertype","kind":"symbol","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sliderType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSSlider","preciseIdentifier":"c:objc(cs)NSSlider","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SliderType","preciseIdentifier":"c:@E@NSSliderType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sliderType","kind":"identifier"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/isVertical":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVertical","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsslider/isvertical","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/isVertical","role":"symbol","title":"isVertical","navigatorTitle":[{"text":"vertical","kind":"identifier"}],"abstract":[{"type":"text","text":"An integer indicating the orientation (horizontal or vertical) of the slider."}],"type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/sliderType-swift.property":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sliderType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSSlider","text":"NSSlider","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SliderType","preciseIdentifier":"c:@E@NSSliderType","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsslider/slidertype-swift.property","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/sliderType-swift.property","role":"symbol","title":"sliderType","navigatorTitle":[{"text":"sliderType","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of the slider, such as vertical or circular."}],"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setKnobThickness:":{"fragments":[{"text":"- ","kind":"text"},{"text":"setKnobThickness:","kind":"identifier"}],"url":"/documentation/appkit/nsslider/setknobthickness:","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setKnobThickness:","role":"symbol","title":"setKnobThickness:","navigatorTitle":[{"text":"setKnobThickness:","kind":"identifier"}],"abstract":[],"deprecated":true,"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider","url":"/documentation/appkit/nsslider","navigatorTitle":[{"kind":"identifier","text":"NSSlider"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSSlider","kind":"identifier"}],"type":"topic","title":"NSSlider","role":"symbol","abstract":[{"text":"A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/knobThickness":{"type":"topic","role":"symbol","url":"/documentation/appkit/nsslider/knobthickness","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/knobThickness","abstract":[{"text":"The knob’s thickness, in pixels.","type":"text"}],"title":"knobThickness","navigatorTitle":[{"text":"knobThickness","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"knobThickness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"introducedAt":"10.10","deprecated":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"value":"sliderType","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"sliderType"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSSlider/altIncrementValue","doc://com.apple.appkit/documentation/AppKit/NSSlider/knobThickness","doc://com.apple.appkit/documentation/AppKit/NSSlider/setKnobThickness:","doc://com.apple.appkit/documentation/AppKit/NSSlider/isVertical","doc://com.apple.appkit/documentation/AppKit/NSSlider/trackFillColor"],"generated":true,"title":"Managing the Slider’s Appearance","anchor":"Managing-the-Sliders-Appearance"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSliderType","preciseIdentifier":"c:@E@NSSliderType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"sliderType","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"NSSliderType","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum/title"},{"value":[{"kind":"identifier","text":"NSSliderType"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum/fragments"},{"value":[{"kind":"identifier","text":"NSSliderType"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum/navigatorTitle"},{"value":"trackFillColor","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1trackFillColor/title"},{"value":[{"text":"trackFillColor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1trackFillColor/fragments"},{"value":"altIncrementValue","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1altIncrementValue/title"},{"value":[{"text":"altIncrementValue","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1altIncrementValue/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1sliderType/title","value":"sliderType"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1sliderType/fragments","value":[{"text":"sliderType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1isVertical/title","value":"vertical"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1isVertical/fragments","value":[{"text":"vertical","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1sliderType-swift.property/title","value":"sliderType"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1sliderType-swift.property/fragments","value":[{"text":"sliderType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title","value":"NSSlider"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments","value":[{"kind":"identifier","text":"NSSlider"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle","value":[{"kind":"identifier","text":"NSSlider"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1knobThickness/title","value":"knobThickness"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1knobThickness/fragments","value":[{"kind":"identifier","text":"knobThickness"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}