{
  "abstract": [
    {
      "text": "Determines where the slider’s tick marks are displayed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSSlider(py)tickMarkPosition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tickMarkPosition"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSSlider",
        "text": "NSSlider"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSTickMarkPosition",
        "text": "TickMarkPosition"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tickMarkPosition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "tickMarkPosition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tickMarkPosition"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSlider",
              "text": "NSSlider"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTickMarkPosition",
              "text": "TickMarkPosition"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For horizontal sliders, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/below",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/above",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For vertical sliders, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/leading",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/trailing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The default positions are ",
              "type": "text"
            },
            {
              "code": "below",
              "type": "codeVoice"
            },
            {
              "text": " for horizontal and ",
              "type": "text"
            },
            {
              "code": "leading",
              "type": "codeVoice"
            },
            {
              "text": " for vertical. This property has no effect if ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ", or if the slider is circular. In its implementation of this property, the receiving ",
              "type": "text"
            },
            {
              "code": "NSSlider",
              "type": "codeVoice"
            },
            {
              "text": " instance invokes the method of the same name of its ",
              "type": "text"
            },
            {
              "code": "NSSliderCell",
              "type": "codeVoice"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider": {
      "abstract": [
        {
          "text": "A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSlider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSlider"
        }
      ],
      "role": "symbol",
      "title": "NSSlider",
      "type": "topic",
      "url": "/documentation/appkit/nsslider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum": {
      "abstract": [
        {
          "text": "The position where a linear slider’s tick marks appear (above, below, leading, or trailing).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TickMarkPosition"
        }
      ],
      "role": "symbol",
      "title": "NSSlider.TickMarkPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/above": {
      "abstract": [
        {
          "text": "A constant indicating that tick marks are displayed above the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "above"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/above",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTickMarkPositionAbove"
        }
      ],
      "role": "symbol",
      "title": "NSSlider.TickMarkPosition.above",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum/above"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/below": {
      "abstract": [
        {
          "text": "A constant indicating that tick marks are displayed below the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "below"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/below",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTickMarkPositionBelow"
        }
      ],
      "role": "symbol",
      "title": "NSSlider.TickMarkPosition.below",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum/below"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/leading": {
      "abstract": [
        {
          "text": "A constant indicating that tick marks are displayed on the leading side of the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSlider",
          "text": "NSSlider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTickMarkPosition",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTickMarkPositionLeading"
        }
      ],
      "role": "symbol",
      "title": "leading",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum/leading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/trailing": {
      "abstract": [
        {
          "text": "A constant indicating that tick marks are displayed on the trailing side of the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSlider",
          "text": "NSSlider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTickMarkPosition",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTickMarkPositionTrailing"
        }
      ],
      "role": "symbol",
      "title": "trailing",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum/trailing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the slider fixes its values to those values represented by its tick marks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsTickMarkValuesOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsTickMarkValuesOnly"
        }
      ],
      "role": "symbol",
      "title": "allowsTickMarkValuesOnly",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/allowstickmarkvaluesonly"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)": {
      "abstract": [
        {
          "text": "Returns the value of the tick mark closest to the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closestTickMarkValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "closestTickMarkValueToValue:"
        }
      ],
      "role": "symbol",
      "title": "closestTickMarkValue(toValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/closesttickmarkvalue(tovalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)": {
      "abstract": [
        {
          "text": "Returns the index of the tick mark closest to the location of the slider represented by the given point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexOfTickMark"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfTickMarkAtPoint:"
        }
      ],
      "role": "symbol",
      "title": "indexOfTickMark(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/indexoftickmark(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks": {
      "abstract": [
        {
          "text": "The number of tick marks associated with the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfTickMarks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfTickMarks"
        }
      ],
      "role": "symbol",
      "title": "numberOfTickMarks",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/numberoftickmarks"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)": {
      "abstract": [
        {
          "text": "Returns the bounding rectangle of the tick mark at the given index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectOfTickMark"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectOfTickMarkAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "rectOfTickMark(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/rectoftickmark(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property": {
      "abstract": [
        {
          "text": "Determines where the slider’s tick marks are displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tickMarkPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSlider",
          "text": "NSSlider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTickMarkPosition",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkPosition-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tickMarkPosition"
        }
      ],
      "role": "symbol",
      "title": "tickMarkPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)": {
      "abstract": [
        {
          "text": "Returns the slider’s value represented by the tick mark at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tickMarkValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tickMarkValueAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "tickMarkValue(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkvalue(at:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Tick-Marks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)"
      ],
      "title": "Managing Tick Marks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "tickMarkPosition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSlider"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Tick-Marks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/allowsTickMarkValuesOnly",
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/closestTickMarkValue(toValue:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/indexOfTickMark(at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/numberOfTickMarks",
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/rectOfTickMark(at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/tickMarkValue(at:)"
              ],
              "title": "Managing Tick Marks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSTickMarkPosition",
                    "text": "NSTickMarkPosition"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "tickMarkPosition"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title",
          "value": "NSSlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1below/title",
          "value": "NSTickMarkPositionBelow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1below/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPositionBelow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/title",
          "value": "NSTickMarkPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkValue(at:)/title",
          "value": "tickMarkValueAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkValue(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tickMarkValueAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1numberOfTickMarks/title",
          "value": "numberOfTickMarks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1numberOfTickMarks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfTickMarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1above/title",
          "value": "NSTickMarkPositionAbove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1above/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPositionAbove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1leading/title",
          "value": "NSTickMarkPositionLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPositionLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1allowsTickMarkValuesOnly/title",
          "value": "allowsTickMarkValuesOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1allowsTickMarkValuesOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsTickMarkValuesOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1closestTickMarkValue(toValue:)/title",
          "value": "closestTickMarkValueToValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1closestTickMarkValue(toValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "closestTickMarkValueToValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1rectOfTickMark(at:)/title",
          "value": "rectOfTickMarkAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1rectOfTickMark(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rectOfTickMarkAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkPosition-swift.property/title",
          "value": "tickMarkPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1tickMarkPosition-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1indexOfTickMark(at:)/title",
          "value": "indexOfTickMarkAtPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1indexOfTickMark(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexOfTickMarkAtPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1trailing/title",
          "value": "NSTickMarkPositionTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPositionTrailing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsslider/tickmarkposition-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsslider/tickmarkposition-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
