{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSlider/title","interfaceLanguage":"occ"},"seeAlsoSections":[{"anchor":"Managing-the-Sliders-Title","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell","doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor","doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:"],"generated":true,"title":"Managing the Slider’s Title"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsslider/title"]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"No replacement needed."}]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"AppKit"}],"title":"title","navigatorTitle":[{"text":"title","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","platforms":[{"introducedAt":"10.0","deprecatedAt":"10.9","name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"externalID":"c:objc(cs)NSSlider(im)title","fragments":[{"text":"- ","kind":"text"},{"text":"title","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Returns the slider’s title.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"title","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"text":"The title. The default title is the empty string (","type":"text"},{"type":"codeVoice","code":"@\"\""},{"text":").","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"title":"NSString","kind":"symbol","url":"/documentation/foundation/nsstring","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont":{"kind":"symbol","url":"/documentation/appkit/nsslider/titlefont","title":"titleFont","navigatorTitle":[{"kind":"identifier","text":"titleFont"}],"abstract":[{"type":"text","text":"This method has been deprecated. Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleFont"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/title":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/title","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"title"}],"deprecated":true,"role":"symbol","url":"/documentation/appkit/nsslider/title","title":"title","navigatorTitle":[{"kind":"identifier","text":"title"}],"type":"topic","abstract":[{"type":"text","text":"Returns the slider’s title."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleCell"}],"role":"symbol","url":"/documentation/appkit/nsslider/titlecell","title":"titleCell","navigatorTitle":[{"kind":"identifier","text":"titleCell"}],"type":"topic","abstract":[{"type":"text","text":"This method has been deprecated. Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitle:"}],"deprecated":true,"role":"symbol","url":"/documentation/appkit/nsslider/settitle:","title":"setTitle:","navigatorTitle":[{"kind":"identifier","text":"setTitle:"}],"type":"topic","abstract":[{"type":"text","text":"Sets the title the slider displays in the bar behind its knob."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleColor"}],"role":"symbol","url":"/documentation/appkit/nsslider/titlecolor","title":"titleColor","navigatorTitle":[{"kind":"identifier","text":"titleColor"}],"type":"topic","abstract":[{"type":"text","text":"This method has been deprecated. Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:":{"kind":"symbol","url":"/documentation/appkit/nsslider/settitlefont:","title":"setTitleFont:","navigatorTitle":[{"kind":"identifier","text":"setTitleFont:"}],"abstract":[{"type":"text","text":"Sets the font used to draw the slider’s title."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:","deprecated":true,"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleFont:"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleColor:"}],"deprecated":true,"role":"symbol","url":"/documentation/appkit/nsslider/settitlecolor:","title":"setTitleColor:","navigatorTitle":[{"kind":"identifier","text":"setTitleColor:"}],"type":"topic","abstract":[{"type":"text","text":"Sets the color used to draw the slider’s title."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider","url":"/documentation/appkit/nsslider","navigatorTitle":[{"kind":"identifier","text":"NSSlider"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSSlider","kind":"identifier"}],"type":"topic","title":"NSSlider","role":"symbol","abstract":[{"text":"A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:":{"kind":"symbol","url":"/documentation/appkit/nsslider/settitlecell:","title":"setTitleCell:","navigatorTitle":[{"kind":"identifier","text":"setTitleCell:"}],"abstract":[{"type":"text","text":"Sets the cell used to draw the slider’s title."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:","deprecated":true,"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleCell:"}]}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace","value":[{"type":"text","text":"A static, plain-text Unicode string object."}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title","op":"replace","value":"NSSlider"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments","op":"replace","value":[{"text":"NSSlider","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle","op":"replace","value":[{"text":"NSSlider","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}