{"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"titleCell"}],"symbolKind":"method","externalID":"c:objc(cs)NSSlider(im)titleCell","title":"titleCell","platforms":[{"name":"macOS","unavailable":false,"introducedAt":"10.0","deprecatedAt":"10.9","deprecated":false,"beta":false}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleCell"}]},"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Managing the Slider’s Title","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/title","doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor","doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:"],"anchor":"Managing-the-Sliders-Title","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"titleCell"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"This method has been deprecated. Returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsslider/titlecell"]}],"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSSlider":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider","url":"/documentation/appkit/nsslider","navigatorTitle":[{"kind":"identifier","text":"NSSlider"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSSlider","kind":"identifier"}],"type":"topic","title":"NSSlider","role":"symbol","abstract":[{"text":"A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:":{"kind":"symbol","url":"/documentation/appkit/nsslider/settitlefont:","title":"setTitleFont:","navigatorTitle":[{"kind":"identifier","text":"setTitleFont:"}],"abstract":[{"type":"text","text":"Sets the font used to draw the slider’s title."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:","deprecated":true,"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleFont:"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont":{"kind":"symbol","url":"/documentation/appkit/nsslider/titlefont","title":"titleFont","navigatorTitle":[{"kind":"identifier","text":"titleFont"}],"abstract":[{"type":"text","text":"This method has been deprecated. Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleFont"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:":{"kind":"symbol","url":"/documentation/appkit/nsslider/settitlecell:","title":"setTitleCell:","navigatorTitle":[{"kind":"identifier","text":"setTitleCell:"}],"abstract":[{"type":"text","text":"Sets the cell used to draw the slider’s title."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:","deprecated":true,"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleCell:"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleColor:"}],"deprecated":true,"role":"symbol","url":"/documentation/appkit/nsslider/settitlecolor:","title":"setTitleColor:","navigatorTitle":[{"kind":"identifier","text":"setTitleColor:"}],"type":"topic","abstract":[{"type":"text","text":"Sets the color used to draw the slider’s title."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitle:"}],"deprecated":true,"role":"symbol","url":"/documentation/appkit/nsslider/settitle:","title":"setTitle:","navigatorTitle":[{"kind":"identifier","text":"setTitle:"}],"type":"topic","abstract":[{"type":"text","text":"Sets the title the slider displays in the bar behind its knob."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/title":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/title","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"title"}],"deprecated":true,"role":"symbol","url":"/documentation/appkit/nsslider/title","title":"title","navigatorTitle":[{"kind":"identifier","text":"title"}],"type":"topic","abstract":[{"type":"text","text":"Returns the slider’s title."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleCell"}],"role":"symbol","url":"/documentation/appkit/nsslider/titlecell","title":"titleCell","navigatorTitle":[{"kind":"identifier","text":"titleCell"}],"type":"topic","abstract":[{"type":"text","text":"This method has been deprecated. Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleColor"}],"role":"symbol","url":"/documentation/appkit/nsslider/titlecolor","title":"titleColor","navigatorTitle":[{"kind":"identifier","text":"titleColor"}],"type":"topic","abstract":[{"type":"text","text":"This method has been deprecated. Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title","value":"NSSlider"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments","value":[{"kind":"identifier","text":"NSSlider"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle","value":[{"kind":"identifier","text":"NSSlider"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}