{"abstract":[{"type":"text","text":"This method has been deprecated. Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsslider/titlefont"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSlider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSFont","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont","preciseIdentifier":"c:objc(cs)NSFont","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"titleFont"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"metadata":{"externalID":"c:objc(cs)NSSlider(im)titleFont","navigatorTitle":[{"text":"titleFont","kind":"identifier"}],"platforms":[{"name":"macOS","introducedAt":"10.0","deprecatedAt":"10.9","beta":false,"unavailable":false,"deprecated":false}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"titleFont","kind":"identifier"}],"role":"symbol","title":"titleFont","modules":[{"name":"AppKit"}]},"seeAlsoSections":[{"anchor":"Managing-the-Sliders-Title","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSlider/title","doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell","doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:","doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:"],"generated":true,"title":"Managing the Slider’s Title"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont","interfaceLanguage":"occ"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleColor","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleColor"}],"role":"symbol","url":"/documentation/appkit/nsslider/titlecolor","title":"titleColor","navigatorTitle":[{"kind":"identifier","text":"titleColor"}],"type":"topic","abstract":[{"type":"text","text":"This method has been deprecated. Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSFont":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSFont"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSFont"}],"url":"/documentation/appkit/nsfont","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont","title":"NSFont","abstract":[{"text":"The representation of a font in an app.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSSlider":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider","url":"/documentation/appkit/nsslider","navigatorTitle":[{"kind":"identifier","text":"NSSlider"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSSlider","kind":"identifier"}],"type":"topic","title":"NSSlider","role":"symbol","abstract":[{"text":"A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont":{"kind":"symbol","url":"/documentation/appkit/nsslider/titlefont","title":"titleFont","navigatorTitle":[{"kind":"identifier","text":"titleFont"}],"abstract":[{"type":"text","text":"This method has been deprecated. Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleFont","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleFont"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/title":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/title","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"title"}],"deprecated":true,"role":"symbol","url":"/documentation/appkit/nsslider/title","title":"title","navigatorTitle":[{"kind":"identifier","text":"title"}],"type":"topic","abstract":[{"type":"text","text":"Returns the slider’s title."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleColor:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleColor:"}],"deprecated":true,"role":"symbol","url":"/documentation/appkit/nsslider/settitlecolor:","title":"setTitleColor:","navigatorTitle":[{"kind":"identifier","text":"setTitleColor:"}],"type":"topic","abstract":[{"type":"text","text":"Sets the color used to draw the slider’s title."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/titleCell","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleCell"}],"role":"symbol","url":"/documentation/appkit/nsslider/titlecell","title":"titleCell","navigatorTitle":[{"kind":"identifier","text":"titleCell"}],"type":"topic","abstract":[{"type":"text","text":"This method has been deprecated. Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:":{"kind":"symbol","url":"/documentation/appkit/nsslider/settitlefont:","title":"setTitleFont:","navigatorTitle":[{"kind":"identifier","text":"setTitleFont:"}],"abstract":[{"type":"text","text":"Sets the font used to draw the slider’s title."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleFont:","deprecated":true,"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleFont:"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:":{"kind":"symbol","url":"/documentation/appkit/nsslider/settitlecell:","title":"setTitleCell:","navigatorTitle":[{"kind":"identifier","text":"setTitleCell:"}],"abstract":[{"type":"text","text":"Sets the cell used to draw the slider’s title."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitleCell:","deprecated":true,"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleCell:"}]},"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSlider/setTitle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitle:"}],"deprecated":true,"role":"symbol","url":"/documentation/appkit/nsslider/settitle:","title":"setTitle:","navigatorTitle":[{"kind":"identifier","text":"setTitle:"}],"type":"topic","abstract":[{"type":"text","text":"Sets the title the slider displays in the bar behind its knob."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"NSFont","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title"},{"op":"replace","value":[{"text":"NSFont","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments"},{"value":[{"kind":"identifier","text":"NSFont"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle","op":"replace"},{"value":"NSSlider","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments","value":[{"text":"NSSlider","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle","value":[{"text":"NSSlider","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}