{
  "abstract": [
    {
      "text": "A value that specifies the second moment constant in the range 0 to 1.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use BNNSGraph* APIs",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@BNNSOptimizerAdamWithClippingFields@FI@beta2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "beta2"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "beta2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use BNNSGraph* APIs",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use BNNSGraph* APIs",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use BNNSGraph* APIs",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "Use BNNSGraph* APIs",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use BNNSGraph* APIs",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use BNNSGraph* APIs",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "7.0",
        "message": "Use BNNSGraph* APIs",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "beta2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "beta2"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of an Adam or AdamW optimizer that optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerAdamWithClippingFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerAdamWithClippingFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerAdamWithClippingFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta1": {
      "abstract": [
        {
          "text": "A value that specifies the first moment constant in the range 0 to 1.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beta1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beta1"
        }
      ],
      "role": "symbol",
      "title": "beta1",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/beta1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta2": {
      "abstract": [
        {
          "text": "A value that specifies the second moment constant in the range 0 to 1.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beta2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beta2"
        }
      ],
      "role": "symbol",
      "title": "beta2",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/beta2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max": {
      "abstract": [
        {
          "text": "The maximum clipping value for clipping by value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clip_gradients_max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clip_gradients_max"
        }
      ],
      "role": "symbol",
      "title": "clip_gradients_max",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/clip_gradients_max"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max_norm": {
      "abstract": [
        {
          "text": "The maximum Euclidean norm for clipping by norm and clipping by global norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clip_gradients_max_norm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max_norm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clip_gradients_max_norm"
        }
      ],
      "role": "symbol",
      "title": "clip_gradients_max_norm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/clip_gradients_max_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_min": {
      "abstract": [
        {
          "text": "The minimum clipping value for clipping by value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clip_gradients_min"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clip_gradients_min"
        }
      ],
      "role": "symbol",
      "title": "clip_gradients_min",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/clip_gradients_min"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_use_norm": {
      "abstract": [
        {
          "text": "An optional value for a known Euclidean norm for clipping by global norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clip_gradients_use_norm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_use_norm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clip_gradients_use_norm"
        }
      ],
      "role": "symbol",
      "title": "clip_gradients_use_norm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/clip_gradients_use_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clipping_func": {
      "abstract": [
        {
          "text": "The clipping function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clipping_func"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerClippingFunction",
          "text": "BNNSOptimizerClippingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clipping_func",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clipping_func"
        }
      ],
      "role": "symbol",
      "title": "clipping_func",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/clipping_func"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/epsilon": {
      "abstract": [
        {
          "text": "An addition for the division in the parameter update stage.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "epsilon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/epsilon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "epsilon"
        }
      ],
      "role": "symbol",
      "title": "epsilon",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/epsilon"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/gradient_scale": {
      "abstract": [
        {
          "text": "A value that specifies the gradient scaling factor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradient_scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/gradient_scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradient_scale"
        }
      ],
      "role": "symbol",
      "title": "gradient_scale",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/gradient_scale"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/learning_rate": {
      "abstract": [
        {
          "text": "A value that specifies the learning rate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "learning_rate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/learning_rate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "learning_rate"
        }
      ],
      "role": "symbol",
      "title": "learning_rate",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/learning_rate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_func": {
      "abstract": [
        {
          "text": "The variable that specifies the regularization function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularization_func"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerRegularizationFunction",
          "text": "BNNSOptimizerRegularizationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_func",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularization_func"
        }
      ],
      "role": "symbol",
      "title": "regularization_func",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/regularization_func"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_scale": {
      "abstract": [
        {
          "text": "A value that specifies the regularization scaling factor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularization_scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularization_scale"
        }
      ],
      "role": "symbol",
      "title": "regularization_scale",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/regularization_scale"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/time_step": {
      "abstract": [
        {
          "text": "A value that’s at least 1 and represents the optimizer’s current time.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "time_step"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/time_step",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "time_step"
        }
      ],
      "role": "symbol",
      "title": "time_step",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/time_step"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction": {
      "abstract": [
        {
          "text": "Constants that describe clipping functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerClippingFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerclippingfunction"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/learning_rate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta1",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/time_step",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/epsilon",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/gradient_scale",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_scale",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_func",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clipping_func",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_min",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max_norm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_use_norm"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "beta2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beta2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/learning_rate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta1",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/time_step",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/epsilon",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/gradient_scale",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_scale",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_func",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clipping_func",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_min",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max_norm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_use_norm"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "beta2"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingFunction/title",
          "value": "BNNSOptimizerClippingFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_max_norm/title",
          "value": "clip_gradients_max_norm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_max_norm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clip_gradients_max_norm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1beta1/title",
          "value": "beta1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1beta1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beta1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1regularization_func/title",
          "value": "regularization_func"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1regularization_func/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularization_func"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clipping_func/title",
          "value": "clipping_func"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clipping_func/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clipping_func"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1gradient_scale/title",
          "value": "gradient_scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1gradient_scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradient_scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1epsilon/title",
          "value": "epsilon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1epsilon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "epsilon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields/title",
          "value": "BNNSOptimizerAdamWithClippingFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerAdamWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerAdamWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1regularization_scale/title",
          "value": "regularization_scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1regularization_scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularization_scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_min/title",
          "value": "clip_gradients_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clip_gradients_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1learning_rate/title",
          "value": "learning_rate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1learning_rate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "learning_rate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_max/title",
          "value": "clip_gradients_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clip_gradients_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1time_step/title",
          "value": "time_step"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1time_step/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "time_step"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_use_norm/title",
          "value": "clip_gradients_use_norm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_use_norm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clip_gradients_use_norm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1beta2/title",
          "value": "beta2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1beta2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beta2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/beta2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/beta2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
