{
  "abstract": [
    {
      "text": "The device that measures the data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/originDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMOdometerData(py)originDevice",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "originDevice"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CMOdometerOriginDevice",
        "text": "CMOdometerOriginDevice"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "originDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "originDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "originDevice"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerOriginDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CMOdometerOriginDevice",
              "text": "CMOdometerOriginDevice"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData": {
      "abstract": [
        {
          "text": "A class that represents odometer data for workouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMOdometerData"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMOdometerData"
        }
      ],
      "role": "symbol",
      "title": "CMOdometerData",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/originDevice": {
      "abstract": [
        {
          "text": "The device that measures the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "originDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMOdometerOriginDevice",
          "text": "CMOdometerOriginDevice"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/originDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "originDevice"
        }
      ],
      "role": "symbol",
      "title": "originDevice",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/origindevice"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerOriginDevice": {
      "abstract": [
        {
          "text": "The device that the odometer sample originates from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMOdometerOriginDevice"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerOriginDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMOdometerOriginDevice"
        }
      ],
      "role": "symbol",
      "title": "CMOdometerOriginDevice",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerorigindevice"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-device",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerOriginDevice"
      ],
      "title": "Getting the device"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "originDevice"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "originDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-device",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerOriginDevice"
              ],
              "title": "Getting the device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerOriginDevice",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CMOdometerOriginDevice",
                    "text": "CMOdometerOriginDevice"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "originDevice"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1originDevice/title",
          "value": "originDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1originDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "originDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData/title",
          "value": "CMOdometerData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMOdometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMOdometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerOriginDevice/title",
          "value": "CMOdometerOriginDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerOriginDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMOdometerOriginDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerOriginDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMOdometerOriginDevice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmodometerdata/origindevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmodometerdata/origindevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
