{
  "abstract": [
    {
      "text": "Browse debugging utilities and constants to use with the XPC APIs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/utilities"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Utilities"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED": {
      "abstract": [
        {
          "text": "The minimum required Simulator host version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED"
        }
      ],
      "role": "symbol",
      "title": "IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED",
      "type": "topic",
      "url": "/documentation/xpc/iphone_simulator_host_min_version_required"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_API_VERSION": {
      "abstract": [
        {
          "text": "The version of the XPC API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_API_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_API_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_API_VERSION"
        }
      ],
      "role": "symbol",
      "title": "XPC_API_VERSION",
      "type": "topic",
      "url": "/documentation/xpc/xpc_api_version"
    },
    "doc://com.apple.xpc/documentation/XPC/launchd": {
      "abstract": [
        {
          "text": "Browse APIs for interacting with ",
          "type": "text"
        },
        {
          "code": "launchd",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/launchd",
      "kind": "article",
      "role": "collectionGroup",
      "title": "launchd",
      "type": "topic",
      "url": "/documentation/xpc/launchd"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc-connections": {
      "abstract": [
        {
          "text": "Create and manage connections to services using connection-based APIs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc-connections",
      "kind": "article",
      "role": "collectionGroup",
      "title": "XPC connections",
      "type": "topic",
      "url": "/documentation/xpc/xpc-connections"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc-objects": {
      "abstract": [
        {
          "text": "Encapsulate data in objects that represent primitive types, collections, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc-objects",
      "kind": "article",
      "role": "collectionGroup",
      "title": "XPC objects",
      "type": "topic",
      "url": "/documentation/xpc/xpc-objects"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_debugger_api_misuse_info()": {
      "abstract": [
        {
          "text": "Returns a pointer to a string that describes the reason XPC aborts the calling process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_debugger_api_misuse_info"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_debugger_api_misuse_info()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_debugger_api_misuse_info"
        }
      ],
      "role": "symbol",
      "title": "xpc_debugger_api_misuse_info()",
      "type": "topic",
      "url": "/documentation/xpc/xpc_debugger_api_misuse_info()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Additional-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc-objects",
        "doc://com.apple.xpc/documentation/XPC/xpc-connections"
      ],
      "title": "Additional Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Debug-Functions",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_debugger_api_misuse_info()"
      ],
      "title": "Debug Functions"
    },
    {
      "anchor": "Version-Details",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPC_API_VERSION",
        "doc://com.apple.xpc/documentation/XPC/IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED"
      ],
      "title": "Version Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Debug-Functions",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_debugger_api_misuse_info()"
              ],
              "title": "Debug Functions"
            },
            {
              "anchor": "Version-Details",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/XPC_API_VERSION",
                "doc://com.apple.xpc/documentation/XPC/IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED"
              ],
              "title": "Version Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Additional-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc-objects",
                "doc://com.apple.xpc/documentation/XPC/launchd",
                "doc://com.apple.xpc/documentation/XPC/xpc-connections"
              ],
              "title": "Additional types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_debugger_api_misuse_info()/title",
          "value": "xpc_debugger_api_misuse_info"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_debugger_api_misuse_info()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_debugger_api_misuse_info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_API_VERSION/title",
          "value": "XPC_API_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_API_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_API_VERSION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED/title",
          "value": "IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IPHONE_SIMULATOR_HOST_MIN_VERSION_REQUIRED"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/utilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/utilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
