{
  "abstract": [
    {
      "text": "Respond on demand to IOKit events and notifications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc-events"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "XPC events"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_EVENT_KEY_NAME-c.macro": {
      "abstract": [
        {
          "text": "A key for querying an XPC event dictionary to retrieve a string that identifies the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XPC_EVENT_KEY_NAME"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_EVENT_KEY_NAME-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_EVENT_KEY_NAME",
      "type": "topic",
      "url": "/documentation/xpc/xpc_event_key_name-c.macro"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_EVENT_KEY_NAME-swift.var": {
      "abstract": [
        {
          "text": "A key for querying an XPC event dictionary to retrieve a string that identifies the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_EVENT_KEY_NAME"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_EVENT_KEY_NAME-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_EVENT_KEY_NAME",
      "type": "topic",
      "url": "/documentation/xpc/xpc_event_key_name-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_set_event_stream_handler(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the event handler to invoke when receiving streamed events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_set_event_stream_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_handler_t",
          "text": "xpc_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_set_event_stream_handler(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_set_event_stream_handler"
        }
      ],
      "role": "symbol",
      "title": "xpc_set_event_stream_handler(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_set_event_stream_handler(_:_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Event-handling",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_set_event_stream_handler(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/XPC_EVENT_KEY_NAME-swift.var"
      ],
      "title": "Event handling"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Event-handling",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_set_event_stream_handler(_:_:_:)",
                "doc://com.apple.xpc/documentation/XPC/XPC_EVENT_KEY_NAME-c.macro"
              ],
              "title": "Event handling"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_set_event_stream_handler(_:_:_:)/title",
          "value": "xpc_set_event_stream_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_set_event_stream_handler(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_set_event_stream_handler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
