{
  "abstract": [
    {
      "text": "Schedule background activities for the system to execute.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc-activities"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "XPC activities"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_ALLOW_BATTERY": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to allow the activity to run while the computer is on battery power.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_ALLOW_BATTERY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_ALLOW_BATTERY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_ALLOW_BATTERY"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_ALLOW_BATTERY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_allow_battery"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_CHECK_IN": {
      "abstract": [
        {
          "text": "A constant to check in with the system for a previously registered activity using the same identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_CHECK_IN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_CHECK_IN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_CHECK_IN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_CHECK_IN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_check_in"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY": {
      "abstract": [
        {
          "text": "An integer property that indicates the number of seconds to delay before beginning the activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_DELAY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_DELAY"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_DELAY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_delay"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD": {
      "abstract": [
        {
          "text": "An integer property that indicates the number of seconds to allow as a grace period before the scheduling of the activity becomes more aggressive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_GRACE_PERIOD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_GRACE_PERIOD"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_GRACE_PERIOD",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_grace_period"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL": {
      "abstract": [
        {
          "text": "An integer property that indicates the desired time interval of the activity in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 15-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_15_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_15_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_15_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_15_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY": {
      "abstract": [
        {
          "text": "A constant that represents a one-day time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_DAY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_DAY"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_1_DAY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_1_day"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR": {
      "abstract": [
        {
          "text": "A constant that represents a 1-hour time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_HOUR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_HOUR"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_1_HOUR",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_1_hour"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 1-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_1_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_1_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 30-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_30_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_30_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_30_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_30_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS": {
      "abstract": [
        {
          "text": "A constant that represents a 4-hour time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_4_HOURS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_4_HOURS"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_4_HOURS",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_4_hours"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 5-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_5_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_5_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_5_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_5_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS": {
      "abstract": [
        {
          "text": "A constant that represents a seven-day time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_7_DAYS",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_7_days"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS": {
      "abstract": [
        {
          "text": "A constant that represents an 8-hour time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_8_HOURS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_8_HOURS"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_8_HOURS",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_8_hours"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PREVENT_DEVICE_SLEEP": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the activity prevents the system from sleeping while on battery power.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PREVENT_DEVICE_SLEEP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PREVENT_DEVICE_SLEEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PREVENT_DEVICE_SLEEP"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_PREVENT_DEVICE_SLEEP",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_prevent_device_sleep"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY": {
      "abstract": [
        {
          "text": "A string property that indicates the priority of the activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_PRIORITY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_priority"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_MAINTENANCE": {
      "abstract": [
        {
          "text": "A string that indicates an activity is maintenance priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_MAINTENANCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_PRIORITY_MAINTENANCE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_priority_maintenance"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_UTILITY": {
      "abstract": [
        {
          "text": "A string that indicates an activity is utility priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY_UTILITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_UTILITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY_UTILITY"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_PRIORITY_UTILITY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_priority_utility"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REPEATING": {
      "abstract": [
        {
          "text": "A Boolean property that indicates whether this is a repeating activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_REPEATING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REPEATING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_REPEATING"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_REPEATING",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_repeating"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_BATTERY_LEVEL": {
      "abstract": [
        {
          "text": "An integer percentage of minimum battery charge required to allow the activity to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_REQUIRE_BATTERY_LEVEL"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_BATTERY_LEVEL",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_ACTIVITY_REQUIRE_BATTERY_LEVEL",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_require_battery_level"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_HDD_SPINNING": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the activity should only be performed while the hard disk drive (HDD) is spinning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_REQUIRE_HDD_SPINNING"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_HDD_SPINNING",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_ACTIVITY_REQUIRE_HDD_SPINNING",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_require_hdd_spinning"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the activity performs only while the primary screen is in sleep mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_require_screen_sleep"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN": {
      "abstract": [
        {
          "text": "The activity has completed a check-in with the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_CHECK_IN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_CHECK_IN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_CHECK_IN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_check_in"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE": {
      "abstract": [
        {
          "text": "The activity continues its operation beyond the return of its handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_CONTINUE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_CONTINUE"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_CONTINUE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_continue"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER": {
      "abstract": [
        {
          "text": "The activity needs to wait until it satisfies its criteria again.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_DEFER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_DEFER"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_DEFER",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_defer"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE": {
      "abstract": [
        {
          "text": "The activity is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_DONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_DONE"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_DONE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_done"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN": {
      "abstract": [
        {
          "text": "The activity is eligible to run according to its criteria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_RUN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_RUN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_RUN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_run"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT": {
      "abstract": [
        {
          "text": "The activity is waiting for an opportunity to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_WAIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_WAIT"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_WAIT",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_wait"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts": {
      "abstract": [
        {
          "text": "A type that represents the state of an activity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "xpc_activity_state_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc-activity-state-t-swift-consts"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_copy_criteria(_:)": {
      "abstract": [
        {
          "text": "Returns an XPC dictionary that describes the execution criteria of an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_copy_criteria"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_t",
          "text": "xpc_activity_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_copy_criteria(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_copy_criteria"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_copy_criteria(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_copy_criteria(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)": {
      "abstract": [
        {
          "text": "Returns the current state of an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_get_state"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_t",
          "text": "xpc_activity_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_state_t",
          "text": "xpc_activity_state_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_get_state"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_get_state(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_get_state(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_handler_t": {
      "abstract": [
        {
          "text": "A block to call when an XPC activity becomes eligible to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_handler_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)": {
      "abstract": [
        {
          "text": "Registers an activity with the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_register"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_handler_t",
          "text": "xpc_activity_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_register"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_register(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_register(_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_criteria(_:_:)": {
      "abstract": [
        {
          "text": "Modifies the execution criteria of an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_set_criteria"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_t",
          "text": "xpc_activity_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_criteria(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_set_criteria"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_set_criteria(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_set_criteria(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)": {
      "abstract": [
        {
          "text": "Updates the current state of an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_set_state"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_t",
          "text": "xpc_activity_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_state_t",
          "text": "xpc_activity_state_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_set_state"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_set_state(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_set_state(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)": {
      "abstract": [
        {
          "text": "Tests whether to defer an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_should_defer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_t",
          "text": "xpc_activity_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_should_defer"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_should_defer(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_should_defer(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t": {
      "abstract": [
        {
          "text": "A type that represents the state of an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_state_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_state_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_state_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_t": {
      "abstract": [
        {
          "text": "An XPC activity object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_unregister(_:)": {
      "abstract": [
        {
          "text": "Unregisters an activity with the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_unregister"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_unregister(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_unregister"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_unregister(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_unregister(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Registration",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_unregister(_:)",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_CHECK_IN",
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_t",
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_handler_t"
      ],
      "title": "Registration"
    },
    {
      "anchor": "State",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts",
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE"
      ],
      "title": "State"
    },
    {
      "anchor": "Execution-criteria",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_copy_criteria(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_criteria(_:_:)"
      ],
      "title": "Execution criteria"
    },
    {
      "anchor": "Scheduling",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REPEATING",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD"
      ],
      "title": "Scheduling"
    },
    {
      "anchor": "Time-Intervals",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS"
      ],
      "title": "Time Intervals"
    },
    {
      "anchor": "Priority",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_MAINTENANCE",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_UTILITY"
      ],
      "title": "Priority"
    },
    {
      "anchor": "Power-consumption",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_ALLOW_BATTERY",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PREVENT_DEVICE_SLEEP"
      ],
      "title": "Power consumption"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Registration",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_unregister(_:)",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_CHECK_IN",
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_t",
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_handler_t"
              ],
              "title": "Registration"
            },
            {
              "anchor": "State",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts",
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE"
              ],
              "title": "State"
            },
            {
              "anchor": "Execution-criteria",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_copy_criteria(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_criteria(_:_:)"
              ],
              "title": "Execution criteria"
            },
            {
              "anchor": "Scheduling",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REPEATING",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD"
              ],
              "title": "Scheduling"
            },
            {
              "anchor": "Time-Intervals",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS"
              ],
              "title": "Time Intervals"
            },
            {
              "anchor": "Priority",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_MAINTENANCE",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_UTILITY"
              ],
              "title": "Priority"
            },
            {
              "anchor": "Power-consumption",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_ALLOW_BATTERY",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PREVENT_DEVICE_SLEEP"
              ],
              "title": "Power consumption"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_BATTERY_LEVEL",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_HDD_SPINNING"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_ALLOW_BATTERY/title",
          "value": "XPC_ACTIVITY_ALLOW_BATTERY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_ALLOW_BATTERY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_ALLOW_BATTERY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_HOUR/title",
          "value": "XPC_ACTIVITY_INTERVAL_1_HOUR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_HOUR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_1_HOUR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_7_DAYS/title",
          "value": "XPC_ACTIVITY_INTERVAL_7_DAYS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_7_DAYS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_4_HOURS/title",
          "value": "XPC_ACTIVITY_INTERVAL_4_HOURS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_4_HOURS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_4_HOURS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY_UTILITY/title",
          "value": "XPC_ACTIVITY_PRIORITY_UTILITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY_UTILITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_PRIORITY_UTILITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_CHECK_IN/title",
          "value": "XPC_ACTIVITY_CHECK_IN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_CHECK_IN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_CHECK_IN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY/title",
          "value": "XPC_ACTIVITY_PRIORITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_PRIORITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_REPEATING/title",
          "value": "XPC_ACTIVITY_REPEATING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_REPEATING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_REPEATING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_DAY/title",
          "value": "XPC_ACTIVITY_INTERVAL_1_DAY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_DAY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_1_DAY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_30_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_30_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_30_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_30_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_WAIT/title",
          "value": "XPC_ACTIVITY_STATE_WAIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_WAIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_WAIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_DELAY/title",
          "value": "XPC_ACTIVITY_DELAY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_DELAY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_DELAY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY_MAINTENANCE/title",
          "value": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY_MAINTENANCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP/title",
          "value": "XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PREVENT_DEVICE_SLEEP/title",
          "value": "XPC_ACTIVITY_PREVENT_DEVICE_SLEEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PREVENT_DEVICE_SLEEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_PREVENT_DEVICE_SLEEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_register(_:_:_:)/title",
          "value": "xpc_activity_register"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_register(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_register"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_state_t/title",
          "value": "xpc_activity_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_unregister(_:)/title",
          "value": "xpc_activity_unregister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_unregister(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_unregister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_15_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_15_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_15_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_15_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_handler_t/title",
          "value": "xpc_activity_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL/title",
          "value": "XPC_ACTIVITY_INTERVAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DONE/title",
          "value": "XPC_ACTIVITY_STATE_DONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_DONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_1_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_1_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DEFER/title",
          "value": "XPC_ACTIVITY_STATE_DEFER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DEFER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_DEFER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_set_state(_:_:)/title",
          "value": "xpc_activity_set_state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_set_state(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_set_state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CHECK_IN/title",
          "value": "XPC_ACTIVITY_STATE_CHECK_IN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CHECK_IN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_CHECK_IN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_copy_criteria(_:)/title",
          "value": "xpc_activity_copy_criteria"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_copy_criteria(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_copy_criteria"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_8_HOURS/title",
          "value": "XPC_ACTIVITY_INTERVAL_8_HOURS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_8_HOURS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_8_HOURS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_RUN/title",
          "value": "XPC_ACTIVITY_STATE_RUN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_RUN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_RUN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_set_criteria(_:_:)/title",
          "value": "xpc_activity_set_criteria"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_set_criteria(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_set_criteria"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_should_defer(_:)/title",
          "value": "xpc_activity_should_defer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_should_defer(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_should_defer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CONTINUE/title",
          "value": "XPC_ACTIVITY_STATE_CONTINUE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CONTINUE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_CONTINUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_5_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_5_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_5_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_5_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_t/title",
          "value": "xpc_activity_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_GRACE_PERIOD/title",
          "value": "XPC_ACTIVITY_GRACE_PERIOD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_GRACE_PERIOD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_GRACE_PERIOD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_get_state(_:)/title",
          "value": "xpc_activity_get_state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_get_state(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_get_state"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc-activities"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc-activities"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
