{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"xpc_activity_handler_t"}],"roleHeading":"Type Alias","title":"xpc_activity_handler_t","modules":[{"name":"XPC"}],"symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_handler_t"}],"externalID":"c:@T@xpc_activity_handler_t","platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"role":"symbol"},"abstract":[{"type":"text","text":"A block to call when an XPC activity becomes eligible to run."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_activity_handler_t","kind":"identifier"},{"text":" = (","kind":"text"},{"preciseIdentifier":"c:@T@xpc_activity_t","text":"xpc_activity_t","kind":"typeIdentifier","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_t"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s4Voida"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)","doc://com.apple.xpc/documentation/XPC/xpc_activity_unregister(_:)","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_CHECK_IN","doc://com.apple.xpc/documentation/XPC/xpc_activity_t"],"anchor":"Registration","generated":true,"title":"Registration"}],"variants":[{"paths":["/documentation/xpc/xpc_activity_handler_t"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/xpc/xpc_activity_handler_t"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.xpc/documentation/XPC/xpc_activity_handler_t","interfaceLanguage":"swift"},"references":{"doc://com.apple.xpc/documentation/XPC/xpc_activity_t":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_t"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"xpc_activity_t"}],"kind":"symbol","title":"xpc_activity_t","role":"symbol","abstract":[{"type":"text","text":"An XPC activity object."}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_t","url":"/documentation/xpc/xpc_activity_t"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_CHECK_IN":{"kind":"symbol","abstract":[{"text":"A constant to check in with the system for a previously registered activity using the same identifier.","type":"text"}],"type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_CHECK_IN","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_CHECK_IN"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_CHECK_IN"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@xpc_object_t","kind":"typeIdentifier","text":"xpc_object_t"}],"url":"/documentation/xpc/xpc_activity_check_in","title":"XPC_ACTIVITY_CHECK_IN","role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_activity_handler_t":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_handler_t","type":"topic","abstract":[{"text":"A block to call when an XPC activity becomes eligible to run.","type":"text"}],"kind":"symbol","role":"symbol","url":"/documentation/xpc/xpc_activity_handler_t","navigatorTitle":[{"text":"xpc_activity_handler_t","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_activity_handler_t","kind":"identifier"}],"title":"xpc_activity_handler_t"},"doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)":{"url":"/documentation/xpc/xpc_activity_register(_:_:_:)","type":"topic","abstract":[{"type":"text","text":"Registers an activity with the system."}],"navigatorTitle":[{"kind":"identifier","text":"xpc_activity_register"}],"role":"symbol","title":"xpc_activity_register(_:_:_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_register"},{"kind":"text","text":"("},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"xpc_object_t","preciseIdentifier":"c:@T@xpc_object_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"xpc_activity_handler_t","preciseIdentifier":"c:@T@xpc_activity_handler_t"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)"},"doc://com.apple.xpc/documentation/XPC/xpc_activity_unregister(_:)":{"url":"/documentation/xpc/xpc_activity_unregister(_:)","navigatorTitle":[{"kind":"identifier","text":"xpc_activity_unregister"}],"abstract":[{"type":"text","text":"Unregisters an activity with the specified identifier."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_unregister(_:)","title":"xpc_activity_unregister(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_unregister"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">)"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.externally.resolved.symbol/s:s4Voida":{"role":"symbol","type":"topic","url":"/documentation/Swift/Void","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Void","kind":"identifier"},{"text":" = ()","kind":"text"}],"title":"Void","abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Alias","path":"/metadata/roleHeading","op":"replace"},{"value":"xpc_activity_handler_t","path":"/metadata/title","op":"replace"},{"path":"/metadata/symbolKind","op":"replace","value":"typealias"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"xpc_activity_handler_t"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"xpc_activity_handler_t"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Registration","identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)","doc://com.apple.xpc/documentation/XPC/xpc_activity_unregister(_:)","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_CHECK_IN","doc://com.apple.xpc/documentation/XPC/xpc_activity_t"],"anchor":"Registration","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(NSObject<OS_xpc_object> *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSObjectobjc(pl)OS_xpc_object)"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_handler_t"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_t/title","op":"replace","value":"xpc_activity_t"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_t/fragments","op":"replace","value":[{"text":"xpc_activity_t","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_t/navigatorTitle","op":"replace","value":[{"text":"xpc_activity_t","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_CHECK_IN/title","op":"replace","value":"XPC_ACTIVITY_CHECK_IN"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_CHECK_IN/fragments","op":"replace","value":[{"kind":"identifier","text":"XPC_ACTIVITY_CHECK_IN"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_handler_t/title","op":"replace","value":"xpc_activity_handler_t"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_handler_t/fragments","op":"replace","value":[{"text":"xpc_activity_handler_t","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_handler_t/navigatorTitle","op":"replace","value":[{"text":"xpc_activity_handler_t","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_register(_:_:_:)/title","op":"replace","value":"xpc_activity_register"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_register(_:_:_:)/fragments","op":"replace","value":[{"text":"xpc_activity_register","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_unregister(_:)/title","op":"replace","value":"xpc_activity_unregister"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_unregister(_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"xpc_activity_unregister"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}