{
  "abstract": [
    {
      "text": "Returns a pointer to the internal storage of a data object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_data_get_bytes_ptr(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@xpc_data_get_bytes_ptr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "xpc_data_get_bytes_ptr"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@xpc_object_t",
        "text": "xpc_object_t"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SV",
        "text": "UnsafeRawPointer"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xpc_data_get_bytes_ptr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "xpc_data_get_bytes_ptr(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_data_get_bytes_ptr"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "xdata"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_object_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_object_t",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SV",
              "text": "UnsafeRawPointer"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The data object which is to be examined.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "xdata"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A pointer to the underlying boxed data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_data_create(_:_:)": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents a buffer of bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_data_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_data_create(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_data_create"
        }
      ],
      "role": "symbol",
      "title": "xpc_data_create(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_data_create(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_data_create_with_dispatch_data(_:)": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents a buffer of bytes that the specified GCD data object describes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_data_create_with_dispatch_data"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "dispatch_data_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_data_create_with_dispatch_data(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_data_create_with_dispatch_data"
        }
      ],
      "role": "symbol",
      "title": "xpc_data_create_with_dispatch_data(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_data_create_with_dispatch_data(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_data_get_bytes(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Copies the bytes in a data object into the specified buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_data_get_bytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_data_get_bytes(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_data_get_bytes"
        }
      ],
      "role": "symbol",
      "title": "xpc_data_get_bytes(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_data_get_bytes(_:_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_data_get_bytes_ptr(_:)": {
      "abstract": [
        {
          "text": "Returns a pointer to the internal storage of a data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_data_get_bytes_ptr"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_data_get_bytes_ptr(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_data_get_bytes_ptr"
        }
      ],
      "role": "symbol",
      "title": "xpc_data_get_bytes_ptr(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_data_get_bytes_ptr(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_data_get_length(_:)": {
      "abstract": [
        {
          "text": "Returns the length of the data that an XPC data object encapsulates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_data_get_length"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_data_get_length(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_data_get_length"
        }
      ],
      "role": "symbol",
      "title": "xpc_data_get_length(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_data_get_length(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_object_t": {
      "abstract": [
        {
          "text": "A type that can describe all XPC objects, including dictionaries, arrays, strings, and numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_object_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_object_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_object_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_object_t"
    },
    "doc://com.externally.resolved.symbol/s:SV": {
      "abstract": [
        {
          "text": "A raw pointer for accessing untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_data_create(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_data_create_with_dispatch_data(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_data_get_bytes(_:_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_data_get_length(_:)"
      ],
      "title": "Data objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "xpc_data_get_bytes_ptr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_data_get_bytes_ptr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_data_create(_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_data_create_with_dispatch_data(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_data_get_bytes(_:_:_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_data_get_length(_:)"
              ],
              "title": "Data objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "xpc_data_get_bytes_ptr"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_object_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@xpc_object_t",
                    "text": "xpc_object_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "xdata"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The data object which is to be examined.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "xdata"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A pointer to the underlying boxed data.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_data_get_bytes(_:_:_:_:)/title",
          "value": "xpc_data_get_bytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_data_get_bytes(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_data_get_bytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_data_create_with_dispatch_data(_:)/title",
          "value": "xpc_data_create_with_dispatch_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_data_create_with_dispatch_data(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_data_create_with_dispatch_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_data_get_bytes_ptr(_:)/title",
          "value": "xpc_data_get_bytes_ptr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_data_get_bytes_ptr(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_data_get_bytes_ptr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/title",
          "value": "xpc_object_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_data_create(_:_:)/title",
          "value": "xpc_data_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_data_create(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_data_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_data_get_length(_:)/title",
          "value": "xpc_data_get_length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_data_get_length(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_data_get_length"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_data_get_bytes_ptr(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_data_get_bytes_ptr(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
