{"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_activate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc://com.apple.xpc/documentation/XPC/OS_xpc_object","text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error_out","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:SA","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t","text":"xpc_rich_error_t","preciseIdentifier":"c:@T@xpc_rich_error_t","kind":"typeIdentifier"},{"text":"?>?) -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"paths":["/documentation/xpc/xpc_session_activate(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"XPC"}],"externalID":"s:3XPC20xpc_session_activateySbSo03OS_B7_object_p_SAySoAC_pSgGSgtF","title":"xpc_session_activate(_:_:)","platforms":[{"beta":false,"deprecated":false,"renamed":"activate()","deprecatedAt":"17.0","unavailable":false,"name":"Mac Catalyst","introducedAt":"16.0"},{"beta":false,"deprecated":false,"renamed":"activate()","deprecatedAt":"14.0","unavailable":false,"name":"macOS","introducedAt":"13.0"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_session_activate","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"xpc_rich_error_t","preciseIdentifier":"c:@T@xpc_rich_error_t","kind":"typeIdentifier"},{"text":"?>?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Function","symbolKind":"func"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Managing life cycle","generated":true,"identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj","doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f"],"anchor":"Managing-life-cycle"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)"},"references":{"doc://com.apple.xpc/documentation/XPC/OS_xpc_object":{"url":"/documentation/xpc/os_xpc_object","type":"topic","abstract":[{"type":"text","text":"The interface for an XPC object."}],"navigatorTitle":[{"kind":"identifier","text":"OS_xpc_object"}],"role":"symbol","title":"OS_xpc_object","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OS_xpc_object"}],"identifier":"doc://com.apple.xpc/documentation/XPC/OS_xpc_object"},"doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)","title":"xpc_session_activate(_:_:)","url":"/documentation/xpc/xpc_session_activate(_:_:)","abstract":[],"kind":"symbol","deprecated":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_activate"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"xpc_rich_error_t","preciseIdentifier":"c:@T@xpc_rich_error_t"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xpc_session_cancel_handler_t"}],"abstract":[],"title":"xpc_session_cancel_handler_t","navigatorTitle":[{"kind":"identifier","text":"xpc_session_cancel_handler_t"}],"type":"topic","url":"/documentation/xpc/xpc_session_cancel_handler_t-65b6f","deprecated":true},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_cancel"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object"},{"kind":"text","text":")"}],"url":"/documentation/xpc/xpc_session_cancel(_:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)","title":"xpc_session_cancel(_:)","deprecated":true,"abstract":[],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_session_set_incoming_message_handler","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"xpc_session_incoming_message_handler_t","preciseIdentifier":"s:3XPC38xpc_session_incoming_message_handler_ta","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"xpc_session_set_incoming_message_handler(_:_:)","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Sets a handler to receive incoming messages for a session."}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)","url":"/documentation/xpc/xpc_session_set_incoming_message_handler(_:_:)"},"doc://com.externally.resolved.symbol/s:SA":{"type":"topic","title":"AutoreleasingUnsafeMutablePointer","identifier":"doc://com.externally.resolved.symbol/s:SA","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Pointee"},{"kind":"text","text":">"}],"url":"/documentation/Swift/AutoreleasingUnsafeMutablePointer","kind":"symbol","abstract":[{"type":"text","text":"A mutable pointer addressing an Objective-C reference that doesn’t own its target."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj","type":"topic","abstract":[],"kind":"symbol","role":"symbol","url":"/documentation/xpc/xpc_session_incoming_message_handler_t-elj","navigatorTitle":[{"kind":"identifier","text":"xpc_session_incoming_message_handler_t"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_incoming_message_handler_t"}],"deprecated":true,"title":"xpc_session_incoming_message_handler_t"},"doc://com.externally.resolved.symbol/s:Sb":{"identifier":"doc://com.externally.resolved.symbol/s:Sb","title":"Bool","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Bool","kind":"identifier"}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)","title":"xpc_session_set_cancel_handler(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_set_cancel_handler"},{"kind":"text","text":"(any "},{"text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"xpc_session_cancel_handler_t","preciseIdentifier":"s:3XPC28xpc_session_cancel_handler_ta"},{"kind":"text","text":")"}],"type":"topic","url":"/documentation/xpc/xpc_session_set_cancel_handler(_:_:)","kind":"symbol","abstract":[],"role":"symbol","deprecated":true},"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t":{"url":"/documentation/xpc/xpc_rich_error_t","type":"topic","abstract":[{"text":"A type that describes an error, and whether you can retry the operation that experienced the error.","type":"text"}],"navigatorTitle":[{"text":"xpc_rich_error_t","kind":"identifier"}],"role":"symbol","title":"xpc_rich_error_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_rich_error_t","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"}},"variantOverrides":[{"patch":[{"value":"OS_xpc_object","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/title","op":"replace"},{"value":[{"text":"OS_xpc_object","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/fragments","op":"replace"},{"value":[{"text":"OS_xpc_object","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/navigatorTitle","op":"replace"},{"value":"xpc_rich_error_t","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/title","op":"replace"},{"value":[{"text":"xpc_rich_error_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/fragments","op":"replace"},{"value":[{"text":"xpc_rich_error_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}