{"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Managing life cycle","identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_session_activate","doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler","doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-3eb2a","doc://com.apple.xpc/documentation/XPC/xpc_session_cancel","doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-7y2lv"],"generated":true,"anchor":"Managing-life-cycle"}],"metadata":{"title":"xpc_session_set_cancel_handler","platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"16.0"},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"16.0"},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"16.0"},{"name":"macOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.0"}],"symbolKind":"func","roleHeading":"Function","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"xpc_session_set_cancel_handler"}],"fragments":[{"kind":"identifier","text":"xpc_session_set_cancel_handler"}],"modules":[{"name":"XPC"}],"externalID":"c:@F@xpc_session_set_cancel_handler"},"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/xpc/xpc_session_set_cancel_handler"]}],"abstract":[{"type":"text","text":"Sets a handler the session calls when it’s canceled."}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"xpc_session_set_cancel_handler","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@xpc_session_t","text":"xpc_session_t","kind":"typeIdentifier","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@xpc_session_cancel_handler_t","text":"xpc_session_cancel_handler_t","kind":"typeIdentifier","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-7y2lv"},{"text":"cancel_handler","kind":"internalParam"},{"text":");","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The session to set the handler on."}],"type":"paragraph"}],"name":"session"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The block the session calls when it’s canceled.","type":"text"}]}],"name":"cancel_handler"}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"The ","type":"text"},{"code":"session","type":"codeVoice"},{"text":" you pass to this method must be inactive. To create an inactive session, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-c.enum/XPC_SESSION_CREATE_INACTIVE"},{"text":" flag when you call ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service"},{"text":" or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service"},{"text":". If the session already has a cancellation handler, this method replaces it.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0":{"url":"/documentation/xpc/xpc_session_t-10if0","navigatorTitle":[{"kind":"identifier","text":"xpc_session_t"}],"abstract":[{"text":"A C type that sends messages to a server process.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0","title":"xpc_session_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"xpc_session_t","kind":"identifier"}]},"doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service","title":"xpc_session_create_mach_service","fragments":[{"kind":"identifier","text":"xpc_session_create_mach_service"}],"type":"topic","url":"/documentation/xpc/xpc_session_create_mach_service","kind":"symbol","abstract":[{"type":"text","text":"Establishes a connection to a launch agent or launch daemon with the name you specify."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service":{"url":"/documentation/xpc/xpc_session_create_xpc_service","type":"topic","abstract":[{"type":"text","text":"Establishes a connection to an XPC service with the name you specify."}],"role":"symbol","title":"xpc_session_create_xpc_service","kind":"symbol","fragments":[{"kind":"identifier","text":"xpc_session_create_xpc_service"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service"},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler":{"type":"topic","fragments":[{"kind":"identifier","text":"xpc_session_set_cancel_handler"}],"kind":"symbol","url":"/documentation/xpc/xpc_session_set_cancel_handler","title":"xpc_session_set_cancel_handler","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler","abstract":[{"type":"text","text":"Sets a handler the session calls when it’s canceled."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-c.enum/XPC_SESSION_CREATE_INACTIVE":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-c.enum/XPC_SESSION_CREATE_INACTIVE","title":"XPC_SESSION_CREATE_INACTIVE","fragments":[{"kind":"identifier","text":"XPC_SESSION_CREATE_INACTIVE"}],"type":"topic","url":"/documentation/xpc/xpc_session_create_flags_t-c.enum/xpc_session_create_inactive","kind":"symbol","abstract":[{"type":"text","text":"Configures a new session in an inactive state."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_activate":{"url":"/documentation/xpc/xpc_session_activate","type":"topic","abstract":[{"type":"text","text":"Activates a session so you can send messages."}],"role":"symbol","title":"xpc_session_activate","kind":"symbol","fragments":[{"text":"xpc_session_activate","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_activate"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel":{"type":"topic","fragments":[{"kind":"identifier","text":"xpc_session_cancel"}],"kind":"symbol","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel","title":"xpc_session_cancel","role":"symbol","abstract":[{"type":"text","text":"Cancels a session, discarding any unsent messages."}],"url":"/documentation/xpc/xpc_session_cancel"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-7y2lv":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-7y2lv","type":"topic","abstract":[{"type":"text","text":"A block the session calls when it’s canceled."}],"kind":"symbol","role":"symbol","url":"/documentation/xpc/xpc_session_cancel_handler_t-7y2lv","fragments":[{"kind":"identifier","text":"xpc_session_cancel_handler_t"}],"title":"xpc_session_cancel_handler_t"},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler":{"type":"topic","fragments":[{"kind":"identifier","text":"xpc_session_set_incoming_message_handler"}],"kind":"symbol","url":"/documentation/xpc/xpc_session_set_incoming_message_handler","title":"xpc_session_set_incoming_message_handler","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler","abstract":[{"type":"text","text":"Sets a handler to receive incoming messages for a session."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-3eb2a":{"role":"symbol","type":"topic","url":"/documentation/xpc/xpc_session_incoming_message_handler_t-3eb2a","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-3eb2a","kind":"symbol","fragments":[{"kind":"identifier","text":"xpc_session_incoming_message_handler_t"}],"title":"xpc_session_incoming_message_handler_t","abstract":[{"type":"text","text":"A closure that receives an incoming message for a session."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/title","value":"xpc_session_t"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/fragments","value":[{"kind":"identifier","text":"xpc_session_t"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/navigatorTitle","value":[{"kind":"identifier","text":"xpc_session_t"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}