{"variants":[{"paths":["/documentation/xpc/xpc_session_cancel"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"title":"Managing life cycle","identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_session_activate","doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler","doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-3eb2a","doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler","doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-7y2lv"],"anchor":"Managing-life-cycle"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"abstract":[{"text":"Cancels a session, discarding any unsent messages.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_cancel"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0","preciseIdentifier":"c:@T@xpc_session_t","kind":"typeIdentifier","text":"xpc_session_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":");"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The session to cancel."}]}],"name":"session"}]},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"When you cancel a session, it discards any unsent messages and invalidates its connection. If there are messages awaiting replies, the session calls the reply handlers with an appropriate "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t"},{"type":"text","text":"."}],"type":"paragraph"}]}],"sections":[],"identifier":{"url":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel","interfaceLanguage":"occ"},"metadata":{"symbolKind":"func","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"xpc_session_cancel"}],"roleHeading":"Function","modules":[{"name":"XPC"}],"platforms":[{"introducedAt":"16.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"16.0","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"16.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"13.0","beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"fragments":[{"kind":"identifier","text":"xpc_session_cancel"}],"title":"xpc_session_cancel","externalID":"c:@F@xpc_session_cancel"},"references":{"doc://com.apple.xpc/documentation/XPC/xpc_session_activate":{"url":"/documentation/xpc/xpc_session_activate","type":"topic","abstract":[{"type":"text","text":"Activates a session so you can send messages."}],"role":"symbol","title":"xpc_session_activate","kind":"symbol","fragments":[{"text":"xpc_session_activate","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_activate"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-7y2lv":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-7y2lv","type":"topic","abstract":[{"type":"text","text":"A block the session calls when it’s canceled."}],"kind":"symbol","role":"symbol","url":"/documentation/xpc/xpc_session_cancel_handler_t-7y2lv","fragments":[{"kind":"identifier","text":"xpc_session_cancel_handler_t"}],"title":"xpc_session_cancel_handler_t"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel":{"type":"topic","fragments":[{"kind":"identifier","text":"xpc_session_cancel"}],"kind":"symbol","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel","title":"xpc_session_cancel","role":"symbol","abstract":[{"type":"text","text":"Cancels a session, discarding any unsent messages."}],"url":"/documentation/xpc/xpc_session_cancel"},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler":{"type":"topic","fragments":[{"kind":"identifier","text":"xpc_session_set_incoming_message_handler"}],"kind":"symbol","url":"/documentation/xpc/xpc_session_set_incoming_message_handler","title":"xpc_session_set_incoming_message_handler","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler","abstract":[{"type":"text","text":"Sets a handler to receive incoming messages for a session."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0":{"url":"/documentation/xpc/xpc_session_t-10if0","navigatorTitle":[{"kind":"identifier","text":"xpc_session_t"}],"abstract":[{"text":"A C type that sends messages to a server process.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0","title":"xpc_session_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"xpc_session_t","kind":"identifier"}]},"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t":{"url":"/documentation/xpc/xpc_rich_error_t","type":"topic","abstract":[{"text":"A type that describes an error, and whether you can retry the operation that experienced the error.","type":"text"}],"navigatorTitle":[{"text":"xpc_rich_error_t","kind":"identifier"}],"role":"symbol","title":"xpc_rich_error_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_rich_error_t","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t"},"doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-3eb2a":{"role":"symbol","type":"topic","url":"/documentation/xpc/xpc_session_incoming_message_handler_t-3eb2a","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-3eb2a","kind":"symbol","fragments":[{"kind":"identifier","text":"xpc_session_incoming_message_handler_t"}],"title":"xpc_session_incoming_message_handler_t","abstract":[{"type":"text","text":"A closure that receives an incoming message for a session."}]},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler":{"type":"topic","fragments":[{"kind":"identifier","text":"xpc_session_set_cancel_handler"}],"kind":"symbol","url":"/documentation/xpc/xpc_session_set_cancel_handler","title":"xpc_session_set_cancel_handler","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler","abstract":[{"type":"text","text":"Sets a handler the session calls when it’s canceled."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/title","value":"xpc_session_t","op":"replace"},{"value":[{"kind":"identifier","text":"xpc_session_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/fragments"},{"value":[{"kind":"identifier","text":"xpc_session_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/navigatorTitle"},{"value":"xpc_rich_error_t","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_rich_error_t"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_rich_error_t"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}