{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)"},"metadata":{"platforms":[{"unavailable":false,"name":"Mac Catalyst","renamed":"setCancellationHandler()","introducedAt":"16.0","beta":false,"deprecatedAt":"17.0","deprecated":false},{"unavailable":false,"name":"macOS","renamed":"setCancellationHandler()","introducedAt":"13.0","beta":false,"deprecatedAt":"14.0","deprecated":false}],"symbolKind":"func","role":"symbol","modules":[{"name":"XPC"}],"title":"xpc_session_set_cancel_handler(_:_:)","externalID":"s:3XPC30xpc_session_set_cancel_handleryySo03OS_B7_object_p_ySoAC_pctF","roleHeading":"Function","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_session_set_cancel_handler","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)OS_xpc_object","text":"OS_xpc_object","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:3XPC28xpc_session_cancel_handler_ta","text":"xpc_session_cancel_handler_t","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_session_set_cancel_handler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)OS_xpc_object","text":"OS_xpc_object","kind":"typeIdentifier","identifier":"doc://com.apple.xpc/documentation/XPC/OS_xpc_object"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cancel_handler","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:3XPC28xpc_session_cancel_handler_ta","text":"xpc_session_cancel_handler_t","kind":"typeIdentifier","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["/documentation/xpc/xpc_session_set_cancel_handler(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Managing life cycle","generated":true,"anchor":"Managing-life-cycle","identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj","doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f"]}],"references":{"doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)","title":"xpc_session_activate(_:_:)","url":"/documentation/xpc/xpc_session_activate(_:_:)","abstract":[],"kind":"symbol","deprecated":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_activate"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"xpc_rich_error_t","preciseIdentifier":"c:@T@xpc_rich_error_t"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xpc_session_cancel_handler_t"}],"abstract":[],"title":"xpc_session_cancel_handler_t","navigatorTitle":[{"kind":"identifier","text":"xpc_session_cancel_handler_t"}],"type":"topic","url":"/documentation/xpc/xpc_session_cancel_handler_t-65b6f","deprecated":true},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)","title":"xpc_session_set_cancel_handler(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_set_cancel_handler"},{"kind":"text","text":"(any "},{"text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"xpc_session_cancel_handler_t","preciseIdentifier":"s:3XPC28xpc_session_cancel_handler_ta"},{"kind":"text","text":")"}],"type":"topic","url":"/documentation/xpc/xpc_session_set_cancel_handler(_:_:)","kind":"symbol","abstract":[],"role":"symbol","deprecated":true},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_session_set_incoming_message_handler","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"xpc_session_incoming_message_handler_t","preciseIdentifier":"s:3XPC38xpc_session_incoming_message_handler_ta","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"xpc_session_set_incoming_message_handler(_:_:)","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Sets a handler to receive incoming messages for a session."}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)","url":"/documentation/xpc/xpc_session_set_incoming_message_handler(_:_:)"},"doc://com.apple.xpc/documentation/XPC/OS_xpc_object":{"url":"/documentation/xpc/os_xpc_object","type":"topic","abstract":[{"type":"text","text":"The interface for an XPC object."}],"navigatorTitle":[{"kind":"identifier","text":"OS_xpc_object"}],"role":"symbol","title":"OS_xpc_object","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OS_xpc_object"}],"identifier":"doc://com.apple.xpc/documentation/XPC/OS_xpc_object"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_cancel"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object"},{"kind":"text","text":")"}],"url":"/documentation/xpc/xpc_session_cancel(_:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)","title":"xpc_session_cancel(_:)","deprecated":true,"abstract":[],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj","type":"topic","abstract":[],"kind":"symbol","role":"symbol","url":"/documentation/xpc/xpc_session_incoming_message_handler_t-elj","navigatorTitle":[{"kind":"identifier","text":"xpc_session_incoming_message_handler_t"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_incoming_message_handler_t"}],"deprecated":true,"title":"xpc_session_incoming_message_handler_t"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/title","op":"replace","value":"OS_xpc_object"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/fragments","op":"replace","value":[{"text":"OS_xpc_object","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OS_xpc_object"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}