{
  "abstract": [
    {
      "text": "The type of the function to invoke for a bundled XPC service when there’s a new connection on the service.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_connection_handler_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@xpc_connection_handler_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "xpc_connection_handler_t"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xpc_connection_handler_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "xpc_connection_handler_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_handler_t"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A new connection that is equivalent to one received by a listener connection. See the documentation for ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_event_handler(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for the semantics associated with the received connection.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "connection"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_handler_t": {
      "abstract": [
        {
          "text": "The type of the function to invoke for a bundled XPC service when there’s a new connection on the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_handler_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_event_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets the event handler block for the connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_event_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_handler_t",
          "text": "xpc_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_event_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_set_event_handler"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_set_event_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_set_event_handler(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_t": {
      "abstract": [
        {
          "text": "A type that represents a connection to a named service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_handler_t": {
      "abstract": [
        {
          "text": "The type of block that the XPC connection APIs accept.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_handler_t"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Event-handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_event_handler(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_handler_t"
      ],
      "title": "Event handling"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "xpc_connection_handler_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Event-handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_event_handler(_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_handler_t"
              ],
              "title": "Event handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fv(#*Q$objc(cs)NSObjectobjc(pl)OS_xpc_object)",
                    "text": "void (*)(NSObject<OS_xpc_object> *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "xpc_connection_handler_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_event_handler(_:_:)/title",
          "value": "xpc_connection_set_event_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_event_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_set_event_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_handler_t/title",
          "value": "xpc_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_t/title",
          "value": "xpc_connection_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_handler_t/title",
          "value": "xpc_connection_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_handler_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_connection_handler_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_connection_handler_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
