{
  "abstract": [
    {
      "text": "A type that represents an unsigned, 64-bit integer value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_UINT64-swift.var"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:3XPC0A12_TYPE_UINT64s13OpaquePointerVvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XPC_TYPE_UINT64"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@xpc_type_t",
        "text": "xpc_type_t"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "XPC_TYPE_UINT64"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPC_TYPE_UINT64"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_type_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_type_t",
              "text": "xpc_type_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ACTIVITY-swift.var": {
      "abstract": [
        {
          "text": "A type that represents the XPC activity object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_ACTIVITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ACTIVITY-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_ACTIVITY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_activity-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ARRAY-swift.var": {
      "abstract": [
        {
          "text": "A type that represents an array of XPC objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_ARRAY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ARRAY-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_ARRAY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_array-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_BOOL-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_BOOL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_BOOL-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_BOOL",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_bool-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_CONNECTION-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a connection to a named service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_CONNECTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_CONNECTION-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_CONNECTION",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_connection-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DATA-swift.var": {
      "abstract": [
        {
          "text": "A type that represents an arbitrary buffer of bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_DATA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DATA-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_DATA",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_data-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DATE-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a date interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_DATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DATE-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_DATE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_date-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DICTIONARY-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a dictionary of XPC objects keyed off of C-strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_DICTIONARY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DICTIONARY-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_DICTIONARY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_dictionary-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DOUBLE-swift.var": {
      "abstract": [
        {
          "text": "A type that represents an IEEE-compliant, double-precision floating point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_DOUBLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DOUBLE-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_DOUBLE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_double-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ENDPOINT-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a connection in serialized form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_ENDPOINT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ENDPOINT-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_ENDPOINT",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_endpoint-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_FD-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a POSIX file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_FD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_FD-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_FD",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_fd-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_INT64-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a signed, 64-bit integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_INT64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_INT64-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_INT64",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_int64-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_NULL-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a null object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_NULL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_NULL-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_NULL",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_null-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_SHMEM-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a region of shared memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_SHMEM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_SHMEM-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_SHMEM",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_shmem-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_STRING-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a null-terminated C-string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_STRING-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_STRING",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_string-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_UINT64-swift.var": {
      "abstract": [
        {
          "text": "A type that represents an unsigned, 64-bit integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_UINT64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_UINT64-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_UINT64",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_uint64-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_UUID-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a universally unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_UUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_UUID-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_UUID",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_uuid-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_type_t": {
      "abstract": [
        {
          "text": "A type that describes XPC object types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_type_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_type_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types-of-objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ACTIVITY-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ARRAY-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_BOOL-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_CONNECTION-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DATA-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DATE-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DICTIONARY-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_DOUBLE-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ENDPOINT-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_FD-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_INT64-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_NULL-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_SHMEM-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_STRING-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_UUID-swift.var"
      ],
      "title": "Types of objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_type_t/title",
          "value": "xpc_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_type_uint64-swift.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
