{"abstract":[{"type":"text","text":"A Boolean property that indicates whether this is a repeating activity."}],"sections":[],"seeAlsoSections":[{"title":"Scheduling","generated":true,"anchor":"Scheduling","identifiers":["doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XPC_ACTIVITY_REPEATING","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","identifier":"doc://com.externally.resolved.symbol/s:s5CChara","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REPEATING"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/xpc/xpc_activity_repeating"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/xpc/xpc_activity_repeating"]}],"metadata":{"externalID":"c:@XPC_ACTIVITY_REPEATING","title":"XPC_ACTIVITY_REPEATING","role":"symbol","modules":[{"name":"XPC"}],"platforms":[{"name":"macOS","unavailable":false,"introducedAt":"10.9","deprecated":false,"beta":false}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XPC_ACTIVITY_REPEATING","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"XPC_ACTIVITY_REPEATING","kind":"identifier"}],"roleHeading":"Global Variable","symbolKind":"var"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:s5CChara":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CChar"},{"kind":"text","text":" = "},{"preciseIdentifier":"s:s4Int8V","kind":"typeIdentifier","text":"Int8"}],"type":"topic","kind":"symbol","title":"CChar","role":"symbol","abstract":[{"type":"text","text":"The C ‘char’ type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5CChara","url":"/documentation/Swift/CChar"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REPEATING":{"abstract":[{"text":"A Boolean property that indicates whether this is a repeating activity.","type":"text"}],"url":"/documentation/xpc/xpc_activity_repeating","role":"symbol","title":"XPC_ACTIVITY_REPEATING","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_REPEATING"},{"kind":"text","text":": "},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">","kind":"text"}],"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REPEATING","navigatorTitle":[{"text":"XPC_ACTIVITY_REPEATING","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY":{"abstract":[{"text":"An integer property that indicates the number of seconds to delay before beginning the activity.","type":"text"}],"url":"/documentation/xpc/xpc_activity_delay","role":"symbol","title":"XPC_ACTIVITY_DELAY","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_DELAY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"text":">","kind":"text"}],"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY","navigatorTitle":[{"text":"XPC_ACTIVITY_DELAY","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:SP":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Pointee"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Pointee"},{"kind":"text","text":" : ~Copyable"}],"type":"topic","kind":"symbol","title":"UnsafePointer","role":"symbol","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"identifier":"doc://com.externally.resolved.symbol/s:SP","url":"/documentation/Swift/UnsafePointer"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD":{"navigatorTitle":[{"text":"XPC_ACTIVITY_GRACE_PERIOD","kind":"identifier"}],"abstract":[{"text":"An integer property that indicates the number of seconds to allow as a grace period before the scheduling of the activity becomes more aggressive.","type":"text"}],"title":"XPC_ACTIVITY_GRACE_PERIOD","url":"/documentation/xpc/xpc_activity_grace_period","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_GRACE_PERIOD"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">","kind":"text"}],"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"macOS","unavailable":false,"introducedAt":"10.9","deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","value":"XPC_ACTIVITY_REPEATING","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"XPC_ACTIVITY_REPEATING","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Scheduling","generated":true,"title":"Scheduling","identifiers":["doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"char","preciseIdentifier":"c:C"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_REPEATING"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_REPEATING/title","op":"replace","value":"XPC_ACTIVITY_REPEATING"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_REPEATING/fragments","op":"replace","value":[{"kind":"identifier","text":"XPC_ACTIVITY_REPEATING"}]},{"op":"replace","value":"XPC_ACTIVITY_DELAY","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_DELAY/title"},{"op":"replace","value":[{"text":"XPC_ACTIVITY_DELAY","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_DELAY/fragments"},{"op":"replace","value":"XPC_ACTIVITY_GRACE_PERIOD","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_GRACE_PERIOD/title"},{"op":"replace","value":[{"text":"XPC_ACTIVITY_GRACE_PERIOD","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_GRACE_PERIOD/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}