{
  "abstract": [
    {
      "text": "A type that describes an error, and whether you can retry the operation that experienced the error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@xpc_rich_error_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "xpc_rich_error_t"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xpc_rich_error_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "xpc_rich_error_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_rich_error_t"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_object_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_object_t",
              "text": "xpc_object_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_object_t": {
      "abstract": [
        {
          "text": "A type that can describe all XPC objects, including dictionaries, arrays, strings, and numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_object_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_object_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_object_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_object_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean that indicates whether you can retry the operation that experienced an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_rich_error_can_retry"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_rich_error_can_retry"
        }
      ],
      "role": "symbol",
      "title": "xpc_rich_error_can_retry(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_rich_error_can_retry(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)": {
      "abstract": [
        {
          "text": "Copies the string description of an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_rich_error_copy_description"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_rich_error_copy_description"
        }
      ],
      "role": "symbol",
      "title": "xpc_rich_error_copy_description(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_rich_error_copy_description(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t": {
      "abstract": [
        {
          "text": "A type that describes an error, and whether you can retry the operation that experienced the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_rich_error_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_rich_error_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_rich_error_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_rich_error_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-2hf7c": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_reply_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-2hf7c",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_reply_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_reply_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_reply_handler_t-2hf7c"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-7kfe4": {
      "abstract": [
        {
          "text": "A block that receives the reply to a message a session sends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_reply_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-7kfe4",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_reply_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_reply_handler_t-7kfe4"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message": {
      "abstract": [
        {
          "text": "Sends a message over the session to the destination service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_send_message"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message(_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_send_message"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async": {
      "abstract": [
        {
          "text": "Sends a message asynchronously over the session to the destination service, calling a handler after receiving a reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_send_message_with_reply_async"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message_with_reply_async",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message_with_reply_async"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async(_:_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_send_message_with_reply_async"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC27xpc_session_reply_handler_ta",
          "text": "xpc_session_reply_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async(_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message_with_reply_async(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message_with_reply_async(_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync": {
      "abstract": [
        {
          "text": "Sends a message over the session to the destination service, blocking the caller until receiving a reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_send_message_with_reply_sync"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message_with_reply_sync",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message_with_reply_sync"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync(_:_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_send_message_with_reply_sync"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync(_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message_with_reply_sync(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message_with_reply_sync(_:_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sending-messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-2hf7c",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync(_:_:_:)"
      ],
      "title": "Sending messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "xpc_rich_error_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_rich_error_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_rich_error_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sending-messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-7kfe4",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync",
                "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)"
              ],
              "title": "Sending messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_object_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@xpc_object_t",
                    "text": "xpc_object_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "xpc_rich_error_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/title",
          "value": "xpc_object_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/title",
          "value": "xpc_rich_error_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_rich_error_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_rich_error_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_copy_description(_:)/title",
          "value": "xpc_rich_error_copy_description"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_copy_description(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_rich_error_copy_description"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_can_retry(_:)/title",
          "value": "xpc_rich_error_can_retry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_can_retry(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_rich_error_can_retry"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_rich_error_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_rich_error_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
