{"sections":[],"seeAlsoSections":[{"anchor":"Managing-life-cycle","identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj"],"title":"Managing life cycle","generated":true}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"See XPCSession initializer","type":"text"}]}],"variants":[{"paths":["/documentation/xpc/xpc_session_cancel_handler_t-65b6f"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_session_cancel_handler_t","kind":"identifier"},{"text":" = (","kind":"text"},{"text":"xpc_rich_error_t","preciseIdentifier":"c:@T@xpc_rich_error_t","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","kind":"typeIdentifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"metadata":{"title":"xpc_session_cancel_handler_t","externalID":"s:3XPC28xpc_session_cancel_handler_ta","modules":[{"name":"XPC"}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_cancel_handler_t"}],"platforms":[{"deprecatedAt":"17.0","deprecated":false,"beta":false,"introducedAt":"16.0","message":"See XPCSession initializer","name":"Mac Catalyst","unavailable":false},{"deprecatedAt":"14.0","deprecated":false,"beta":false,"introducedAt":"13.0","message":"See XPCSession initializer","name":"macOS","unavailable":false}],"roleHeading":"Type Alias","symbolKind":"typealias","navigatorTitle":[{"kind":"identifier","text":"xpc_session_cancel_handler_t"}]},"references":{"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t":{"url":"/documentation/xpc/xpc_rich_error_t","type":"topic","abstract":[{"text":"A type that describes an error, and whether you can retry the operation that experienced the error.","type":"text"}],"navigatorTitle":[{"text":"xpc_rich_error_t","kind":"identifier"}],"role":"symbol","title":"xpc_rich_error_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_rich_error_t","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t"},"doc://com.externally.resolved.symbol/s:s4Voida":{"role":"symbol","type":"topic","url":"/documentation/Swift/Void","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Void","kind":"identifier"},{"text":" = ()","kind":"text"}],"title":"Void","abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}]},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)","title":"xpc_session_set_cancel_handler(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_set_cancel_handler"},{"kind":"text","text":"(any "},{"text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"xpc_session_cancel_handler_t","preciseIdentifier":"s:3XPC28xpc_session_cancel_handler_ta"},{"kind":"text","text":")"}],"type":"topic","url":"/documentation/xpc/xpc_session_set_cancel_handler(_:_:)","kind":"symbol","abstract":[],"role":"symbol","deprecated":true},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_cancel"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object"},{"kind":"text","text":")"}],"url":"/documentation/xpc/xpc_session_cancel(_:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)","title":"xpc_session_cancel(_:)","deprecated":true,"abstract":[],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xpc_session_cancel_handler_t"}],"abstract":[],"title":"xpc_session_cancel_handler_t","navigatorTitle":[{"kind":"identifier","text":"xpc_session_cancel_handler_t"}],"type":"topic","url":"/documentation/xpc/xpc_session_cancel_handler_t-65b6f","deprecated":true},"doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj","type":"topic","abstract":[],"kind":"symbol","role":"symbol","url":"/documentation/xpc/xpc_session_incoming_message_handler_t-elj","navigatorTitle":[{"kind":"identifier","text":"xpc_session_incoming_message_handler_t"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_incoming_message_handler_t"}],"deprecated":true,"title":"xpc_session_incoming_message_handler_t"},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_session_set_incoming_message_handler","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"xpc_session_incoming_message_handler_t","preciseIdentifier":"s:3XPC38xpc_session_incoming_message_handler_ta","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"xpc_session_set_incoming_message_handler(_:_:)","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Sets a handler to receive incoming messages for a session."}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)","url":"/documentation/xpc/xpc_session_set_incoming_message_handler(_:_:)"},"doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)","title":"xpc_session_activate(_:_:)","url":"/documentation/xpc/xpc_session_activate(_:_:)","abstract":[],"kind":"symbol","deprecated":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_activate"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"OS_xpc_object","preciseIdentifier":"c:objc(pl)OS_xpc_object"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"xpc_rich_error_t","preciseIdentifier":"c:@T@xpc_rich_error_t"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"xpc_rich_error_t","op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/title"},{"value":[{"kind":"identifier","text":"xpc_rich_error_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/fragments"},{"value":[{"kind":"identifier","text":"xpc_rich_error_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}