{"abstract":[{"type":"text","text":"A Boolean value that indicates whether the activity performs only while the primary screen is in sleep mode."}],"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"introducedAt":"10.9","beta":false,"name":"macOS"}],"roleHeading":"Global Variable","title":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","externalID":"c:@XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","modules":[{"name":"XPC"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP"}],"symbolKind":"var","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","identifier":"doc://com.externally.resolved.symbol/s:s5CChara","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/xpc/xpc_activity_require_screen_sleep"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/xpc/xpc_activity_require_screen_sleep"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"seeAlsoSections":[{"generated":true,"title":"Power consumption","identifiers":["doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_ALLOW_BATTERY","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PREVENT_DEVICE_SLEEP"],"anchor":"Power-consumption"}],"kind":"symbol","identifier":{"url":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","interfaceLanguage":"swift"},"references":{"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PREVENT_DEVICE_SLEEP":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XPC_ACTIVITY_PREVENT_DEVICE_SLEEP","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"/documentation/xpc/xpc_activity_prevent_device_sleep","abstract":[{"type":"text","text":"A Boolean that indicates whether the activity prevents the system from sleeping while on battery power."}],"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PREVENT_DEVICE_SLEEP","navigatorTitle":[{"text":"XPC_ACTIVITY_PREVENT_DEVICE_SLEEP","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"XPC_ACTIVITY_PREVENT_DEVICE_SLEEP"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_ALLOW_BATTERY":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XPC_ACTIVITY_ALLOW_BATTERY","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"/documentation/xpc/xpc_activity_allow_battery","abstract":[{"type":"text","text":"A Boolean value that indicates whether to allow the activity to run while the computer is on battery power."}],"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_ALLOW_BATTERY","navigatorTitle":[{"text":"XPC_ACTIVITY_ALLOW_BATTERY","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"XPC_ACTIVITY_ALLOW_BATTERY"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.externally.resolved.symbol/s:s5CChara":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CChar"},{"kind":"text","text":" = "},{"preciseIdentifier":"s:s4Int8V","kind":"typeIdentifier","text":"Int8"}],"type":"topic","kind":"symbol","title":"CChar","role":"symbol","abstract":[{"type":"text","text":"The C ‘char’ type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5CChara","url":"/documentation/Swift/CChar"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"/documentation/xpc/xpc_activity_require_screen_sleep","abstract":[{"type":"text","text":"A Boolean value that indicates whether the activity performs only while the primary screen is in sleep mode."}],"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","navigatorTitle":[{"text":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP"},"doc://com.externally.resolved.symbol/s:SP":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Pointee"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Pointee"},{"kind":"text","text":" : ~Copyable"}],"type":"topic","kind":"symbol","title":"UnsafePointer","role":"symbol","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"identifier":"doc://com.externally.resolved.symbol/s:SP","url":"/documentation/Swift/UnsafePointer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"macOS","deprecated":false,"beta":false,"introducedAt":"10.9","unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Global Variable","path":"/metadata/roleHeading"},{"op":"replace","value":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"path":"/hierarchy"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"identifiers":["doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_ALLOW_BATTERY","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PREVENT_DEVICE_SLEEP"],"title":"Power consumption","anchor":"Power-consumption"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"preciseIdentifier":"c:C","kind":"typeIdentifier","text":"char"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"XPC_ACTIVITY_PREVENT_DEVICE_SLEEP","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PREVENT_DEVICE_SLEEP/title"},{"op":"replace","value":[{"text":"XPC_ACTIVITY_PREVENT_DEVICE_SLEEP","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PREVENT_DEVICE_SLEEP/fragments"},{"op":"replace","value":"XPC_ACTIVITY_ALLOW_BATTERY","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_ALLOW_BATTERY/title"},{"op":"replace","value":[{"text":"XPC_ACTIVITY_ALLOW_BATTERY","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_ALLOW_BATTERY/fragments"},{"op":"replace","value":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP/title"},{"value":[{"text":"XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}