{
  "abstract": [
    {
      "text": "A constant to pass as the destination index to the class of primitive XPC array setters indicating that the specified primitive needs to append to the array.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.xpc/documentation/XPC/XPC_ARRAY_APPEND-c.macro"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@XPC_ARRAY_APPEND",
    "fragments": [
      {
        "kind": "identifier",
        "text": "XPC_ARRAY_APPEND"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XPC_ARRAY_APPEND"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "XPC_ARRAY_APPEND"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPC_ARRAY_APPEND"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ARRAY_APPEND-c.macro": {
      "abstract": [
        {
          "text": "A constant to pass as the destination index to the class of primitive XPC array setters indicating that the specified primitive needs to append to the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XPC_ARRAY_APPEND"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ARRAY_APPEND-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_ARRAY_APPEND",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_append-c.macro"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_append_value(_:_:)": {
      "abstract": [
        {
          "text": "Appends an object to an XPC array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_append_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_append_value(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_append_value"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_append_value(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_append_value(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_apply(_:_:)": {
      "abstract": [
        {
          "text": "Invokes the specified block for every value in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_apply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_apply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_apply"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_apply(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_apply(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_create(_:_:)": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents an array of XPC objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_create(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_create"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_create(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_create(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_create_connection(_:_:)": {
      "abstract": [
        {
          "text": "Creates a connection object from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_create_connection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_create_connection(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_create_connection"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_create_connection(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_create_connection(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_create_empty()": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents an array of XPC objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_create_empty"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_create_empty()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_create_empty"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_create_empty()",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_create_empty()"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_dup_fd(_:_:)": {
      "abstract": [
        {
          "text": "Gets a file descriptor from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_dup_fd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_dup_fd(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_dup_fd"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_dup_fd(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_dup_fd(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_array(_:_:)": {
      "abstract": [
        {
          "text": "Returns the array at the specified index in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_array"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_array(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_array"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_array(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_array(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_bool(_:_:)": {
      "abstract": [
        {
          "text": "Gets a Boolean primitive value from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_bool"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_bool(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_bool"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_bool(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_bool(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_count(_:)": {
      "abstract": [
        {
          "text": "Returns the count of values in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_count(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_count"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_count(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_count(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_data(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets a pointer to the raw bytes of a data object from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_data"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_data(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_data"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_data(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_data(_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_date(_:_:)": {
      "abstract": [
        {
          "text": "Gets a date interval from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_date"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_date(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_date"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_date(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_date(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_dictionary(_:_:)": {
      "abstract": [
        {
          "text": "Returns the dictionary at the specified index in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_dictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_dictionary(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_dictionary"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_dictionary(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_dictionary(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_double(_:_:)": {
      "abstract": [
        {
          "text": "Gets a double-precision floating point primitive value from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_double(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_double"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_double(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_double(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_value(_:_:)": {
      "abstract": [
        {
          "text": "Returns the value at the specified index in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_value(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_value"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_value(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_value(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_set_value(_:_:_:)": {
      "abstract": [
        {
          "text": "Inserts the specified object into the array at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_set_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_set_value(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_set_value"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_set_value(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_set_value(_:_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Array-objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_array_create(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_create_empty()",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_create_connection(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_set_value(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_value(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_append_value(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_count(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_apply(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_dup_fd(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_array(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_bool(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_data(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_date(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_dictionary(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_double(_:_:)"
      ],
      "title": "Array objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_bool(_:_:)/title",
          "value": "xpc_array_get_bool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_bool(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_bool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_date(_:_:)/title",
          "value": "xpc_array_get_date"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_date(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_date"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create_empty()/title",
          "value": "xpc_array_create_empty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create_empty()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_create_empty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_dictionary(_:_:)/title",
          "value": "xpc_array_get_dictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_dictionary(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_dictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_data(_:_:_:)/title",
          "value": "xpc_array_get_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_data(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_set_value(_:_:_:)/title",
          "value": "xpc_array_set_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_set_value(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_set_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_count(_:)/title",
          "value": "xpc_array_get_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_count(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_value(_:_:)/title",
          "value": "xpc_array_get_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_value(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_dup_fd(_:_:)/title",
          "value": "xpc_array_dup_fd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_dup_fd(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_dup_fd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_apply(_:_:)/title",
          "value": "xpc_array_apply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_apply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_apply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_array(_:_:)/title",
          "value": "xpc_array_get_array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_array(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_append_value(_:_:)/title",
          "value": "xpc_array_append_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_append_value(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_append_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create_connection(_:_:)/title",
          "value": "xpc_array_create_connection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create_connection(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_create_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create(_:_:)/title",
          "value": "xpc_array_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_double(_:_:)/title",
          "value": "xpc_array_get_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_double(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_double"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_array_append-c.macro"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
