{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"char","preciseIdentifier":"c:C"},{"kind":"text","text":" * "},{"kind":"identifier","text":"xpc_session_copy_description"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0","text":"xpc_session_t","preciseIdentifier":"c:@T@xpc_session_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":");"}]}]},{"kind":"parameters","parameters":[{"name":"session","content":[{"inlineContent":[{"text":"The session to get the description from.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A string that describes the session.","type":"text"}]}],"kind":"content"},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"To dispose of the string when it’s no longer needed, call ","type":"text"},{"code":"free()","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"modules":[{"name":"XPC"}],"fragments":[{"text":"xpc_session_copy_description","kind":"identifier"}],"roleHeading":"Function","navigatorTitle":[{"text":"xpc_session_copy_description","kind":"identifier"}],"role":"symbol","platforms":[{"name":"iOS","introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false},{"name":"macOS","introducedAt":"13.0","unavailable":false,"beta":false,"deprecated":false}],"externalID":"c:@F@xpc_session_copy_description","symbolKind":"func","title":"xpc_session_copy_description"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/xpc/xpc_session_copy_description"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service","doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service","doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-c.enum","doc://com.apple.xpc/documentation/XPC/xpc_session_set_target_queue"],"anchor":"Creating-a-session","generated":true,"title":"Creating a session"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.xpc/documentation/XPC/xpc_session_copy_description","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Copies the description string of a session."}],"references":{"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC/xpc_session_copy_description":{"role":"symbol","type":"topic","url":"/documentation/xpc/xpc_session_copy_description","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_copy_description","kind":"symbol","fragments":[{"text":"xpc_session_copy_description","kind":"identifier"}],"title":"xpc_session_copy_description","abstract":[{"text":"Copies the description string of a session.","type":"text"}]},"doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service","title":"xpc_session_create_mach_service","fragments":[{"kind":"identifier","text":"xpc_session_create_mach_service"}],"type":"topic","url":"/documentation/xpc/xpc_session_create_mach_service","kind":"symbol","abstract":[{"type":"text","text":"Establishes a connection to a launch agent or launch daemon with the name you specify."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_target_queue":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_target_queue","title":"xpc_session_set_target_queue","fragments":[{"kind":"identifier","text":"xpc_session_set_target_queue"}],"type":"topic","url":"/documentation/xpc/xpc_session_set_target_queue","kind":"symbol","abstract":[{"type":"text","text":"Sets the target dispatch queue on an inactive session for processing messages."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0":{"url":"/documentation/xpc/xpc_session_t-10if0","navigatorTitle":[{"kind":"identifier","text":"xpc_session_t"}],"abstract":[{"text":"A C type that sends messages to a server process.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0","title":"xpc_session_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"xpc_session_t","kind":"identifier"}]},"doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-c.enum":{"role":"symbol","type":"topic","url":"/documentation/xpc/xpc_session_create_flags_t-c.enum","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-c.enum","kind":"symbol","fragments":[{"text":"xpc_session_create_flags_t","kind":"identifier"}],"title":"xpc_session_create_flags_t","abstract":[{"text":"Options that specify how to create inactive or privileged sessions.","type":"text"}]},"doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service":{"url":"/documentation/xpc/xpc_session_create_xpc_service","type":"topic","abstract":[{"type":"text","text":"Establishes a connection to an XPC service with the name you specify."}],"role":"symbol","title":"xpc_session_create_xpc_service","kind":"symbol","fragments":[{"kind":"identifier","text":"xpc_session_create_xpc_service"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service"}},"variantOverrides":[{"patch":[{"value":"xpc_session_t","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/title","op":"replace"},{"value":[{"text":"xpc_session_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/fragments","op":"replace"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/navigatorTitle","value":[{"kind":"identifier","text":"xpc_session_t"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}