{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A block that receives the reply to a message a session sends."}],"identifier":{"url":"doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-7kfe4","interfaceLanguage":"occ"},"metadata":{"platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}],"modules":[{"name":"XPC"}],"symbolKind":"typealias","role":"symbol","title":"xpc_session_reply_handler_t","fragments":[{"kind":"identifier","text":"xpc_session_reply_handler_t"}],"externalID":"c:@T@xpc_session_reply_handler_t","roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"xpc_session_reply_handler_t"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(NSObject<OS_xpc_object> *, NSObject<OS_xpc_object> *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSObjectobjc(pl)OS_xpc_object#S2_)"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_reply_handler_t"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"languages":["occ"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object the destination service sends back."}]}],"name":"reply"},{"content":[{"inlineContent":[{"type":"text","text":"An error, if one occurs while sending a message."}],"type":"paragraph"}],"name":"error"}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/xpc/xpc_session_reply_handler_t-7kfe4"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_session_send_message","doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async","doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync","doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t","doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)","doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)"],"generated":true,"title":"Sending messages","anchor":"Sending-messages"}],"references":{"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t":{"url":"/documentation/xpc/xpc_rich_error_t","type":"topic","abstract":[{"text":"A type that describes an error, and whether you can retry the operation that experienced the error.","type":"text"}],"navigatorTitle":[{"text":"xpc_rich_error_t","kind":"identifier"}],"role":"symbol","title":"xpc_rich_error_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_rich_error_t","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t"},"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async":{"title":"xpc_session_send_message_with_reply_async","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async","type":"topic","abstract":[{"type":"text","text":"Sends a message asynchronously over the session to the destination service, calling a handler after receiving a reply."}],"role":"symbol","url":"/documentation/xpc/xpc_session_send_message_with_reply_async","kind":"symbol","fragments":[{"kind":"identifier","text":"xpc_session_send_message_with_reply_async"}]},"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message","role":"symbol","kind":"symbol","fragments":[{"text":"xpc_session_send_message","kind":"identifier"}],"abstract":[{"text":"Sends a message over the session to the destination service.","type":"text"}],"title":"xpc_session_send_message","type":"topic","url":"/documentation/xpc/xpc_session_send_message"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)":{"role":"symbol","type":"topic","url":"/documentation/xpc/xpc_rich_error_can_retry(_:)","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_rich_error_can_retry","kind":"identifier"},{"text":"(","kind":"text"},{"text":"xpc_rich_error_t","preciseIdentifier":"c:@T@xpc_rich_error_t","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"xpc_rich_error_can_retry","kind":"identifier"}],"title":"xpc_rich_error_can_retry(_:)","abstract":[{"type":"text","text":"Returns a Boolean that indicates whether you can retry the operation that experienced an error."}]},"doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-7kfe4":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-7kfe4","title":"xpc_session_reply_handler_t","fragments":[{"kind":"identifier","text":"xpc_session_reply_handler_t"}],"type":"topic","url":"/documentation/xpc/xpc_session_reply_handler_t-7kfe4","kind":"symbol","abstract":[{"type":"text","text":"A block that receives the reply to a message a session sends."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)":{"url":"/documentation/xpc/xpc_rich_error_copy_description(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"xpc_rich_error_copy_description"}],"abstract":[{"type":"text","text":"Copies the string description of an error."}],"role":"symbol","title":"xpc_rich_error_copy_description(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xpc_rich_error_copy_description"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@xpc_rich_error_t","kind":"typeIdentifier","text":"xpc_rich_error_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)"},"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync":{"url":"/documentation/xpc/xpc_session_send_message_with_reply_sync","kind":"symbol","abstract":[{"type":"text","text":"Sends a message over the session to the destination service, blocking the caller until receiving a reply."}],"role":"symbol","title":"xpc_session_send_message_with_reply_sync","type":"topic","fragments":[{"kind":"identifier","text":"xpc_session_send_message_with_reply_sync"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"xpc_rich_error_t","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/title"},{"op":"replace","value":[{"text":"xpc_rich_error_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_rich_error_t"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/navigatorTitle"},{"op":"replace","value":"xpc_rich_error_can_retry","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_can_retry(_:)/title"},{"op":"replace","value":[{"text":"xpc_rich_error_can_retry","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_can_retry(_:)/fragments"},{"op":"replace","value":"xpc_rich_error_copy_description","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_copy_description(_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_rich_error_copy_description"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_copy_description(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}