{
  "abstract": [
    {
      "text": "A type that represents the state of an activity.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@xpc_activity_state_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "xpc_activity_state_t"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xpc_activity_state_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "xpc_activity_state_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_activity_state_t"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An activity is in one of the states that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " defines. Apps may check the current state of the activity using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the handler block that you provide to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The app can modify the state of the activity by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with one of the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN": {
      "abstract": [
        {
          "text": "The activity has completed a check-in with the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_CHECK_IN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_CHECK_IN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_CHECK_IN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_check_in"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE": {
      "abstract": [
        {
          "text": "The activity continues its operation beyond the return of its handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_CONTINUE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_CONTINUE"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_CONTINUE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_continue"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER": {
      "abstract": [
        {
          "text": "The activity needs to wait until it satisfies its criteria again.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_DEFER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_DEFER"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_DEFER",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_defer"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE": {
      "abstract": [
        {
          "text": "The activity is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_DONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_DONE"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_DONE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_done"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN": {
      "abstract": [
        {
          "text": "The activity is eligible to run according to its criteria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_RUN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_RUN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_RUN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_run"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT": {
      "abstract": [
        {
          "text": "The activity is waiting for an opportunity to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_WAIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_STATE_WAIT"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_STATE_WAIT",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_wait"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts": {
      "abstract": [
        {
          "text": "A type that represents the state of an activity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "xpc_activity_state_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc-activity-state-t-swift-consts"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)": {
      "abstract": [
        {
          "text": "Returns the current state of an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_get_state"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_t",
          "text": "xpc_activity_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_state_t",
          "text": "xpc_activity_state_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_get_state"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_get_state(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_get_state(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)": {
      "abstract": [
        {
          "text": "Registers an activity with the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_register"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_handler_t",
          "text": "xpc_activity_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_register(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_register"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_register(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_register(_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)": {
      "abstract": [
        {
          "text": "Updates the current state of an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_set_state"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_t",
          "text": "xpc_activity_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_state_t",
          "text": "xpc_activity_state_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_set_state"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_set_state(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_set_state(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)": {
      "abstract": [
        {
          "text": "Tests whether to defer an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_should_defer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_activity_t",
          "text": "xpc_activity_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_should_defer"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_should_defer(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_should_defer(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t": {
      "abstract": [
        {
          "text": "A type that represents the state of an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_activity_state_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_activity_state_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_activity_state_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_state_t"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE"
      ],
      "title": "State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "xpc_activity_state_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE"
              ],
              "title": "State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:L",
                    "text": "long"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "xpc_activity_state_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CHECK_IN/title",
          "value": "XPC_ACTIVITY_STATE_CHECK_IN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CHECK_IN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_CHECK_IN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DONE/title",
          "value": "XPC_ACTIVITY_STATE_DONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_DONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_register(_:_:_:)/title",
          "value": "xpc_activity_register"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_register(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_register"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_should_defer(_:)/title",
          "value": "xpc_activity_should_defer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_should_defer(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_should_defer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CONTINUE/title",
          "value": "XPC_ACTIVITY_STATE_CONTINUE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CONTINUE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_CONTINUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_RUN/title",
          "value": "XPC_ACTIVITY_STATE_RUN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_RUN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_RUN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_set_state(_:_:)/title",
          "value": "xpc_activity_set_state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_set_state(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_set_state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_WAIT/title",
          "value": "XPC_ACTIVITY_STATE_WAIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_WAIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_WAIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_state_t/title",
          "value": "xpc_activity_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DEFER/title",
          "value": "XPC_ACTIVITY_STATE_DEFER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DEFER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_STATE_DEFER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_get_state(_:)/title",
          "value": "xpc_activity_get_state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_get_state(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_activity_get_state"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_activity_state_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_activity_state_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
