{
  "abstract": [
    {
      "text": "A constant that represents a seven-day time interval.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@XPC_ACTIVITY_INTERVAL_7_DAYS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int64V",
        "text": "Int64"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "XPC_ACTIVITY_INTERVAL_7_DAYS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int64V",
              "text": "Int64"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL": {
      "abstract": [
        {
          "text": "An integer property that indicates the desired time interval of the activity in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 15-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_15_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_15_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_15_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_15_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY": {
      "abstract": [
        {
          "text": "A constant that represents a one-day time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_DAY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_DAY"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_1_DAY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_1_day"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR": {
      "abstract": [
        {
          "text": "A constant that represents a 1-hour time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_HOUR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_HOUR"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_1_HOUR",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_1_hour"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 1-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_1_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_1_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 30-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_30_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_30_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_30_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_30_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS": {
      "abstract": [
        {
          "text": "A constant that represents a 4-hour time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_4_HOURS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_4_HOURS"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_4_HOURS",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_4_hours"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 5-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_5_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_5_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_5_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_5_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS": {
      "abstract": [
        {
          "text": "A constant that represents a seven-day time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_7_DAYS",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_7_days"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS": {
      "abstract": [
        {
          "text": "A constant that represents an 8-hour time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_8_HOURS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_8_HOURS"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_8_HOURS",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_8_hours"
    },
    "doc://com.externally.resolved.symbol/s:s5Int64V": {
      "abstract": [
        {
          "text": "A 64-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int64V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int64",
      "type": "topic",
      "url": "/documentation/Swift/Int64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Time-Intervals",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY"
      ],
      "title": "Time Intervals"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XPC_ACTIVITY_INTERVAL_7_DAYS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Time-Intervals",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY"
              ],
              "title": "Time Intervals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int64_t",
                    "text": "int64_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_15_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_15_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_15_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_15_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL/title",
          "value": "XPC_ACTIVITY_INTERVAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_4_HOURS/title",
          "value": "XPC_ACTIVITY_INTERVAL_4_HOURS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_4_HOURS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_4_HOURS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_30_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_30_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_30_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_30_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_DAY/title",
          "value": "XPC_ACTIVITY_INTERVAL_1_DAY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_DAY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_1_DAY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_5_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_5_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_5_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_5_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_HOUR/title",
          "value": "XPC_ACTIVITY_INTERVAL_1_HOUR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_HOUR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_1_HOUR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_1_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_1_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_7_DAYS/title",
          "value": "XPC_ACTIVITY_INTERVAL_7_DAYS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_7_DAYS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_8_HOURS/title",
          "value": "XPC_ACTIVITY_INTERVAL_8_HOURS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_8_HOURS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_8_HOURS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_activity_interval_7_days"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_activity_interval_7_days"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
