{
  "abstract": [
    {
      "text": "Sets a handler to receive incoming messages for a session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:3XPC40xpc_session_set_incoming_message_handleryySo03OS_B7_object_p_ySoAC_pctF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "xpc_session_set_incoming_message_handler"
      },
      {
        "kind": "text",
        "text": "(any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)OS_xpc_object",
        "text": "OS_xpc_object"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:3XPC38xpc_session_incoming_message_handler_ta",
        "text": "xpc_session_incoming_message_handler_t"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "renamed": "setIncomingMessageHandler()",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.0",
        "name": "macOS",
        "renamed": "setIncomingMessageHandler()",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "xpc_session_set_incoming_message_handler(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_session_set_incoming_message_handler"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/OS_xpc_object",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_xpc_object",
              "text": "OS_xpc_object"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:3XPC38xpc_session_incoming_message_handler_ta",
              "text": "xpc_session_incoming_message_handler_t"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The session that receives messages.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block that the session invokes when it receives messages.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "handler"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/OS_xpc_object": {
      "abstract": [
        {
          "text": "The interface for an XPC object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_xpc_object"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/OS_xpc_object",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_xpc_object"
        }
      ],
      "role": "symbol",
      "title": "OS_xpc_object",
      "type": "topic",
      "url": "/documentation/xpc/os_xpc_object"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_activate"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_activate(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_activate(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_cancel"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_cancel(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_cancel(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_cancel_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_cancel_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_cancel_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_cancel_handler_t-65b6f"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_incoming_message_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_incoming_message_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_incoming_message_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_incoming_message_handler_t-elj"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_set_cancel_handler"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC28xpc_session_cancel_handler_ta",
          "text": "xpc_session_cancel_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_set_cancel_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_set_cancel_handler(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to receive incoming messages for a session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_set_incoming_message_handler"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC38xpc_session_incoming_message_handler_ta",
          "text": "xpc_session_incoming_message_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_set_incoming_message_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_set_incoming_message_handler(_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-life-cycle",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f"
      ],
      "title": "Managing life cycle"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/title",
          "value": "OS_xpc_object"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_xpc_object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_xpc_object"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_session_set_incoming_message_handler(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
