{
  "abstract": [
    {
      "text": "A type that represents an error object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ERROR-swift.var"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:3XPC0A11_TYPE_ERRORs13OpaquePointerVvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XPC_TYPE_ERROR"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@xpc_type_t",
        "text": "xpc_type_t"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "XPC_TYPE_ERROR"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPC_TYPE_ERROR"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_type_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_type_t",
              "text": "xpc_type_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Errors in XPC are dictionaries, but ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_get_type(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " will return this type when given an error object. You cannot create an error object directly; XPC will only give them to handlers. These error objects have pointer values that are constant across the lifetime of your process and can be safely compared.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "These constants are enumerated in the header for the connection object. Error dictionaries may reserve keys so that they can be queried to obtain more detailed information about the error. Currently, the only reserved key is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ERROR_KEY_DESCRIPTION-swift.var",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCRichError": {
      "abstract": [
        {
          "text": "An error that contains a description and indicates if you can retry the operation that caused the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCRichError"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCRichError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCRichError"
        }
      ],
      "role": "symbol",
      "title": "XPCRichError",
      "type": "topic",
      "url": "/documentation/xpc/xpcricherror"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ERROR_KEY_DESCRIPTION-swift.var": {
      "abstract": [
        {
          "text": "A key for querying an error dictionary to retrieve a string with a human-readable description of the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ERROR_KEY_DESCRIPTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ERROR_KEY_DESCRIPTION-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_ERROR_KEY_DESCRIPTION",
      "type": "topic",
      "url": "/documentation/xpc/xpc_error_key_description-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT",
      "type": "topic",
      "url": "/documentation/xpc/xpc_error_peer_code_signing_requirement-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ERROR-swift.var": {
      "abstract": [
        {
          "text": "A type that represents an error object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_ERROR-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_ERROR",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_error-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_RICH_ERROR-swift.var": {
      "abstract": [
        {
          "text": "A type that represents a rich error object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_TYPE_RICH_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_RICH_ERROR-swift.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_TYPE_RICH_ERROR",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_rich_error-swift.var"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_get_type(_:)": {
      "abstract": [
        {
          "text": "Returns the type of an object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_get_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_get_type(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_get_type"
        }
      ],
      "role": "symbol",
      "title": "xpc_get_type(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_get_type(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_type_t": {
      "abstract": [
        {
          "text": "A type that describes XPC object types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_type_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_type_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_type_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_type_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCRichError",
        "doc://com.apple.xpc/documentation/XPC/XPC_TYPE_RICH_ERROR-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_ERROR_KEY_DESCRIPTION-swift.var",
        "doc://com.apple.xpc/documentation/XPC/XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT-swift.var"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_get_type(_:)/title",
          "value": "xpc_get_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_get_type(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_get_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_type_t/title",
          "value": "xpc_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_type_error-swift.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
