{"sections":[],"identifier":{"url":"doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t","interfaceLanguage":"swift"},"abstract":[{"text":"A block that receives an incoming peer session request from a client.","type":"text"}],"variants":[{"paths":["/documentation/xpc/xpc_listener_incoming_session_handler_t"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/xpc/xpc_listener_incoming_session_handler_t"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"xpc_listener_incoming_session_handler_t","kind":"identifier"}],"externalID":"c:@T@xpc_listener_incoming_session_handler_t","symbolKind":"typealias","modules":[{"name":"XPC"}],"role":"symbol","title":"xpc_listener_incoming_session_handler_t","platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"roleHeading":"Type Alias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"}]},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0","text":"xpc_session_t","preciseIdentifier":"c:@T@xpc_session_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When a client connects to your service, the system invokes this block with a session that represents the server’s connection to the client. Before returning from this block, you must do one of the following:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call "},{"type":"reference","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler","isActive":true},{"type":"text","text":" to set a handler for incoming messages."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Call "},{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel","isActive":true,"type":"reference"},{"type":"text","text":" to cancel the session."}],"type":"paragraph"}]}]},{"type":"aside","style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Failure to take one of these actions results in an API misuse crash."}]}]},{"type":"paragraph","inlineContent":[{"text":"When the ","type":"text"},{"code":"incoming_session_handler","type":"codeVoice"},{"text":" returns, the system automatically activates the peer session unless you explicitly cancel it.","type":"text"}]}]}],"references":{"doc://com.externally.resolved.symbol/s:s4Voida":{"role":"symbol","type":"topic","url":"/documentation/Swift/Void","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Void","kind":"identifier"},{"text":" = ()","kind":"text"}],"title":"Void","abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}]},"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler":{"type":"topic","fragments":[{"kind":"identifier","text":"xpc_session_set_incoming_message_handler"}],"kind":"symbol","url":"/documentation/xpc/xpc_session_set_incoming_message_handler","title":"xpc_session_set_incoming_message_handler","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler","abstract":[{"type":"text","text":"Sets a handler to receive incoming messages for a session."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t":{"kind":"symbol","abstract":[{"type":"text","text":"A block that receives an incoming peer session request from a client."}],"type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t","navigatorTitle":[{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"}],"url":"/documentation/xpc/xpc_listener_incoming_session_handler_t","title":"xpc_listener_incoming_session_handler_t","role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel":{"type":"topic","fragments":[{"kind":"identifier","text":"xpc_session_cancel"}],"kind":"symbol","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel","title":"xpc_session_cancel","role":"symbol","abstract":[{"type":"text","text":"Cancels a session, discarding any unsent messages."}],"url":"/documentation/xpc/xpc_session_cancel"},"doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t":{"role":"symbol","type":"topic","url":"/documentation/xpc/xpc_listener_create_flags_t","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t","kind":"symbol","fragments":[{"text":"xpc_listener_create_flags_t","kind":"identifier"}],"title":"xpc_listener_create_flags_t","abstract":[{"text":"Options that control the listener’s configuration.","type":"text"}]},"doc://com.apple.xpc/documentation/XPC/xpc_listener_create":{"fragments":[{"kind":"identifier","text":"xpc_listener_create"}],"url":"/documentation/xpc/xpc_listener_create","kind":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_listener_create","title":"xpc_listener_create","abstract":[{"type":"text","text":"Creates the server side of an XPC service using the specified service name."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0":{"url":"/documentation/xpc/xpc_session_t-10if0","navigatorTitle":[{"kind":"identifier","text":"xpc_session_t"}],"abstract":[{"text":"A C type that sends messages to a server process.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0","title":"xpc_session_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"xpc_session_t","kind":"identifier"}]},"doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description","type":"topic","abstract":[{"text":"Copies the description string of a listener.","type":"text"}],"kind":"symbol","role":"symbol","url":"/documentation/xpc/xpc_listener_copy_description","fragments":[{"text":"xpc_listener_copy_description","kind":"identifier"}],"title":"xpc_listener_copy_description"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Alias","path":"/metadata/roleHeading","op":"replace"},{"value":"xpc_listener_incoming_session_handler_t","path":"/metadata/title","op":"replace"},{"op":"replace","value":"typealias","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"}],"path":"/metadata/fragments"},{"op":"replace","value":[{"text":"xpc_listener_incoming_session_handler_t","kind":"identifier"}],"path":"/metadata/navigatorTitle"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":[{"title":"Creating a listener","anchor":"Creating-a-listener","identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_listener_create","doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t","doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*Q$objc(cs)NSObjectobjc(pl)OS_xpc_session)","text":"void (^)(NSObject<OS_xpc_session> *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/title","value":"xpc_listener_incoming_session_handler_t"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/fragments","value":[{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/navigatorTitle","value":[{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/title","value":"xpc_session_t"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/fragments","value":[{"text":"xpc_session_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/navigatorTitle","value":[{"text":"xpc_session_t","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}