{
  "abstract": [
    {
      "text": "A string that indicates an activity is maintenance priority.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_MAINTENANCE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@XPC_ACTIVITY_PRIORITY_MAINTENANCE",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5CChara",
        "text": "CChar"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Maintenance priority is intended for user-invisible maintenance tasks such as garbage collection or optimization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY": {
      "abstract": [
        {
          "text": "A string property that indicates the priority of the activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_PRIORITY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_priority"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_MAINTENANCE": {
      "abstract": [
        {
          "text": "A string that indicates an activity is maintenance priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_MAINTENANCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_PRIORITY_MAINTENANCE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_priority_maintenance"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_UTILITY": {
      "abstract": [
        {
          "text": "A string that indicates an activity is utility priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY_UTILITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_UTILITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_PRIORITY_UTILITY"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_PRIORITY_UTILITY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_priority_utility"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C ‘char’ type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Priority",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_UTILITY"
      ],
      "title": "Priority"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Priority",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_PRIORITY_UTILITY"
              ],
              "title": "Priority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:C",
                    "text": "char"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY/title",
          "value": "XPC_ACTIVITY_PRIORITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_PRIORITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY_UTILITY/title",
          "value": "XPC_ACTIVITY_PRIORITY_UTILITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY_UTILITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_PRIORITY_UTILITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY_MAINTENANCE/title",
          "value": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_PRIORITY_MAINTENANCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_PRIORITY_MAINTENANCE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_activity_priority_maintenance"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_activity_priority_maintenance"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
