{
  "abstract": [
    {
      "text": "A C type that performs tasks for clients across process boundaries.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_listener_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@xpc_listener_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "xpc_listener_t"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xpc_listener_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "xpc_listener_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/OS_xpc_listener-swift.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)OS_xpc_listener",
              "text": "OS_xpc_listener"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To implement an XPC service, create a listener and respond to incoming session requests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/OS_xpc_listener-swift.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_xpc_listener"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/OS_xpc_listener-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_xpc_listener"
        }
      ],
      "role": "symbol",
      "title": "OS_xpc_listener",
      "type": "topic",
      "url": "/documentation/xpc/os_xpc_listener-swift.class"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCListener": {
      "abstract": [
        {
          "text": "A type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "role": "symbol",
      "title": "XPCListener",
      "type": "topic",
      "url": "/documentation/xpc/xpclistener"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage": {
      "abstract": [
        {
          "text": "A type that represents a message sent between a session and a listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCReceivedMessage"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCReceivedMessage"
        }
      ],
      "role": "symbol",
      "title": "XPCReceivedMessage",
      "type": "topic",
      "url": "/documentation/xpc/xpcreceivedmessage"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession": {
      "abstract": [
        {
          "text": "A type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "role": "symbol",
      "title": "XPCSession",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession"
    },
    "doc://com.apple.xpc/documentation/XPC/creating-xpc-services": {
      "abstract": [
        {
          "text": "Configure a listener, establish a client session, and exchange messages between processes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
      "kind": "article",
      "role": "article",
      "title": "Creating XPC services",
      "type": "topic",
      "url": "/documentation/xpc/creating-xpc-services"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_activate": {
      "abstract": [
        {
          "text": "Activates an inactive listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_activate"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_activate",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_activate",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_activate"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_cancel": {
      "abstract": [
        {
          "text": "Cancels a listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_cancel"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_cancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_cancel",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_cancel"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description": {
      "abstract": [
        {
          "text": "Copies the description string of a listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_copy_description"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_copy_description",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_copy_description"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_create": {
      "abstract": [
        {
          "text": "Creates the server side of an XPC service using the specified service name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_create"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_create",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_create"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t": {
      "abstract": [
        {
          "text": "Options that control the listener’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_create_flags_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_create_flags_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_create_flags_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t": {
      "abstract": [
        {
          "text": "A block that receives an incoming peer session request from a client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_incoming_session_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_listener_incoming_session_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_listener_incoming_session_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_incoming_session_handler_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_reject_peer": {
      "abstract": [
        {
          "text": "Rejects an incoming peer session request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_reject_peer"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_reject_peer",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_reject_peer",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_reject_peer"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_set_peer_code_signing_requirement(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_set_peer_code_signing_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_listener_t",
          "text": "xpc_listener_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_set_peer_code_signing_requirement(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_listener_set_peer_code_signing_requirement"
        }
      ],
      "role": "symbol",
      "title": "xpc_listener_set_peer_code_signing_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_set_peer_code_signing_requirement(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_t": {
      "abstract": [
        {
          "text": "A C type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_listener_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0": {
      "abstract": [
        {
          "text": "A C type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_t-10if0"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interprocess-communication",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
        "doc://com.apple.xpc/documentation/XPC/XPCListener",
        "doc://com.apple.xpc/documentation/XPC/XPCSession",
        "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0"
      ],
      "title": "Interprocess communication"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-listener",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t"
      ],
      "title": "Creating a listener"
    },
    {
      "anchor": "Working-with-code-signing",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_set_peer_code_signing_requirement(_:_:)"
      ],
      "title": "Working with code signing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "xpc_listener_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-listener",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_listener_create",
                "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t",
                "doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t",
                "doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description"
              ],
              "title": "Creating a listener"
            },
            {
              "anchor": "Managing-the-life-cycle",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_listener_activate",
                "doc://com.apple.xpc/documentation/XPC/xpc_listener_cancel",
                "doc://com.apple.xpc/documentation/XPC/xpc_listener_reject_peer"
              ],
              "title": "Managing the life cycle"
            },
            {
              "anchor": "Working-with-code-signing",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_listener_set_peer_code_signing_requirement(_:_:)"
              ],
              "title": "Working with code signing"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interprocess-communication",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0"
              ],
              "title": "Interprocess communication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_xpc_listener",
                    "text": "NSObject<OS_xpc_listener>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "xpc_listener_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_set_peer_code_signing_requirement(_:_:)/title",
          "value": "xpc_listener_set_peer_code_signing_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_set_peer_code_signing_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_set_peer_code_signing_requirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/title",
          "value": "xpc_listener_incoming_session_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_incoming_session_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_incoming_session_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/title",
          "value": "xpc_session_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/title",
          "value": "xpc_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_listener_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_listener_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
