{
  "abstract": [
    {
      "text": "Options that control the listener’s configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@xpc_listener_create_flags_t",
    "fragments": [
      {
        "kind": "identifier",
        "text": "xpc_listener_create_flags_t"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xpc_listener_create_flags_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "xpc_listener_create_flags_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "xpc_listener_create_flags_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description": {
      "abstract": [
        {
          "text": "Copies the description string of a listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_copy_description"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_copy_description",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_copy_description"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_create": {
      "abstract": [
        {
          "text": "Creates the server side of an XPC service using the specified service name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_create"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_create",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_create"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t": {
      "abstract": [
        {
          "text": "Options that control the listener’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_create_flags_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_create_flags_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_create_flags_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_FORCE_MACH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XPC_LISTENER_CREATE_FORCE_MACH"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_FORCE_MACH",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_LISTENER_CREATE_FORCE_MACH",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_create_flags_t/xpc_listener_create_force_mach"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_FORCE_XPCSERVICE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XPC_LISTENER_CREATE_FORCE_XPCSERVICE"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_FORCE_XPCSERVICE",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_LISTENER_CREATE_FORCE_XPCSERVICE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_create_flags_t/xpc_listener_create_force_xpcservice"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_INACTIVE": {
      "abstract": [
        {
          "text": "Prevents the system from automatically activating the listener after creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XPC_LISTENER_CREATE_INACTIVE"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_INACTIVE",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_LISTENER_CREATE_INACTIVE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_create_flags_t/xpc_listener_create_inactive"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_NONE": {
      "abstract": [
        {
          "text": "Configures the listener in a default state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XPC_LISTENER_CREATE_NONE"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_NONE",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_LISTENER_CREATE_NONE",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_create_flags_t/xpc_listener_create_none"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t": {
      "abstract": [
        {
          "text": "A block that receives an incoming peer session request from a client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_incoming_session_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_listener_incoming_session_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_listener_incoming_session_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_incoming_session_handler_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-listener",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_create",
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t",
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description"
      ],
      "title": "Creating a listener"
    }
  ],
  "topicSections": [
    {
      "anchor": "Listener-state",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_INACTIVE",
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_NONE"
      ],
      "title": "Listener state"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_FORCE_MACH",
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t/XPC_LISTENER_CREATE_FORCE_XPCSERVICE"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/title",
          "value": "xpc_listener_incoming_session_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_incoming_session_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_incoming_session_handler_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_listener_create_flags_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
