{
  "abstract": [
    {
      "text": "Copies the description string of a listener.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@xpc_listener_copy_description",
    "fragments": [
      {
        "kind": "identifier",
        "text": "xpc_listener_copy_description"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xpc_listener_copy_description"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "xpc_listener_copy_description"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "xpc_listener_copy_description"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_listener_t",
              "text": "xpc_listener_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "listener"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The listener to get the description from.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "listener"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A string that describes the listener.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To dispose of the string when it’s no longer needed, call ",
              "type": "text"
            },
            {
              "code": "free()",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description": {
      "abstract": [
        {
          "text": "Copies the description string of a listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_copy_description"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_copy_description",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_copy_description",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_copy_description"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_create": {
      "abstract": [
        {
          "text": "Creates the server side of an XPC service using the specified service name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_create"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_create",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_create"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t": {
      "abstract": [
        {
          "text": "Options that control the listener’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_listener_create_flags_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_create_flags_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_create_flags_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t": {
      "abstract": [
        {
          "text": "A block that receives an incoming peer session request from a client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_incoming_session_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_listener_incoming_session_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_listener_incoming_session_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_incoming_session_handler_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_t": {
      "abstract": [
        {
          "text": "A C type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_listener_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-listener",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_create",
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_create_flags_t",
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t"
      ],
      "title": "Creating a listener"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/title",
          "value": "xpc_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/title",
          "value": "xpc_listener_incoming_session_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_incoming_session_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_incoming_session_handler_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_listener_copy_description"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
