{"metadata":{"platforms":[{"unavailable":false,"deprecatedAt":"17.0","introducedAt":"16.0","deprecated":false,"beta":false,"renamed":"send(message:replyHandler:)","name":"Mac Catalyst"},{"unavailable":false,"deprecatedAt":"14.0","introducedAt":"13.0","deprecated":false,"beta":false,"renamed":"send(message:replyHandler:)","name":"macOS"}],"modules":[{"name":"XPC"}],"symbolKind":"func","externalID":"s:3XPC41xpc_session_send_message_with_reply_asyncyySo03OS_B7_object_p_SoAC_pySoAC_pSg_ADtctF","title":"xpc_session_send_message_with_reply_async(_:_:_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_session_send_message_with_reply_async","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)OS_xpc_object","text":"OS_xpc_object"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_object_t","text":"xpc_object_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:3XPC27xpc_session_reply_handler_ta","text":"xpc_session_reply_handler_t"},{"text":")","kind":"text"}],"roleHeading":"Function"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/xpc/xpc_session_send_message_with_reply_async(_:_:_:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"seeAlsoSections":[{"title":"Sending messages","generated":true,"anchor":"Sending-messages","identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t","doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)","doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_send_message(_:_:)","doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-2hf7c","doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync(_:_:_:)"]}],"identifier":{"url":"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async(_:_:_:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_session_send_message_with_reply_async","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc://com.apple.xpc/documentation/XPC/OS_xpc_object","text":"OS_xpc_object","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)OS_xpc_object"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_object_t","text":"xpc_object_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_object_t"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"reply_handler","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_session_reply_handler_t","kind":"typeIdentifier","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-2hf7c","preciseIdentifier":"s:3XPC27xpc_session_reply_handler_ta"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.apple.xpc/documentation/XPC/xpc_object_t":{"role":"symbol","abstract":[{"type":"text","text":"A type that can describe all XPC objects, including dictionaries, arrays, strings, and numbers."}],"kind":"symbol","url":"/documentation/xpc/xpc_object_t","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_object_t","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"xpc_object_t","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_object_t","title":"xpc_object_t"},"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync(_:_:_:)":{"deprecated":true,"title":"xpc_session_send_message_with_reply_sync(_:_:_:)","url":"/documentation/xpc/xpc_session_send_message_with_reply_sync(_:_:_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"xpc_session_send_message_with_reply_sync","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"OS_xpc_object","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)OS_xpc_object"},{"text":", ","kind":"text"},{"text":"xpc_object_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_object_t"},{"text":", ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"text":"xpc_rich_error_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_rich_error_t"},{"text":"?>?) -> ","kind":"text"},{"text":"xpc_object_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_object_t"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync(_:_:_:)"},"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t":{"url":"/documentation/xpc/xpc_rich_error_t","type":"topic","abstract":[{"text":"A type that describes an error, and whether you can retry the operation that experienced the error.","type":"text"}],"navigatorTitle":[{"text":"xpc_rich_error_t","kind":"identifier"}],"role":"symbol","title":"xpc_rich_error_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_rich_error_t","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t"},"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)":{"role":"symbol","type":"topic","url":"/documentation/xpc/xpc_rich_error_can_retry(_:)","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_rich_error_can_retry","kind":"identifier"},{"text":"(","kind":"text"},{"text":"xpc_rich_error_t","preciseIdentifier":"c:@T@xpc_rich_error_t","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"xpc_rich_error_can_retry","kind":"identifier"}],"title":"xpc_rich_error_can_retry(_:)","abstract":[{"type":"text","text":"Returns a Boolean that indicates whether you can retry the operation that experienced an error."}]},"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message(_:_:)":{"type":"topic","abstract":[],"title":"xpc_session_send_message(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_send_message"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)OS_xpc_object","text":"OS_xpc_object"},{"kind":"text","text":", "},{"text":"xpc_object_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_object_t"},{"text":") -> ","kind":"text"},{"text":"xpc_rich_error_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_rich_error_t"},{"text":"?","kind":"text"}],"deprecated":true,"role":"symbol","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message(_:_:)","url":"/documentation/xpc/xpc_session_send_message(_:_:)","kind":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async(_:_:_:)":{"type":"topic","abstract":[],"title":"xpc_session_send_message_with_reply_async(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_send_message_with_reply_async"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)OS_xpc_object","kind":"typeIdentifier","text":"OS_xpc_object"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@xpc_object_t","kind":"typeIdentifier","text":"xpc_object_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:3XPC27xpc_session_reply_handler_ta","kind":"typeIdentifier","text":"xpc_session_reply_handler_t"},{"text":")","kind":"text"}],"deprecated":true,"role":"symbol","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async(_:_:_:)","url":"/documentation/xpc/xpc_session_send_message_with_reply_async(_:_:_:)","kind":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)":{"url":"/documentation/xpc/xpc_rich_error_copy_description(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"xpc_rich_error_copy_description"}],"abstract":[{"type":"text","text":"Copies the string description of an error."}],"role":"symbol","title":"xpc_rich_error_copy_description(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xpc_rich_error_copy_description"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@xpc_rich_error_t","kind":"typeIdentifier","text":"xpc_rich_error_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)"},"doc://com.apple.xpc/documentation/XPC/OS_xpc_object":{"url":"/documentation/xpc/os_xpc_object","type":"topic","abstract":[{"type":"text","text":"The interface for an XPC object."}],"navigatorTitle":[{"kind":"identifier","text":"OS_xpc_object"}],"role":"symbol","title":"OS_xpc_object","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OS_xpc_object"}],"identifier":"doc://com.apple.xpc/documentation/XPC/OS_xpc_object"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-2hf7c":{"type":"topic","abstract":[],"title":"xpc_session_reply_handler_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_session_reply_handler_t"}],"navigatorTitle":[{"kind":"identifier","text":"xpc_session_reply_handler_t"}],"deprecated":true,"role":"symbol","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-2hf7c","url":"/documentation/xpc/xpc_session_reply_handler_t-2hf7c","kind":"symbol"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/title","op":"replace","value":"xpc_object_t"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/fragments","op":"replace","value":[{"kind":"identifier","text":"xpc_object_t"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"xpc_object_t"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/title","op":"replace","value":"xpc_rich_error_t"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/fragments","op":"replace","value":[{"kind":"identifier","text":"xpc_rich_error_t"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"xpc_rich_error_t"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_can_retry(_:)/title","op":"replace","value":"xpc_rich_error_can_retry"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_can_retry(_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"xpc_rich_error_can_retry"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_copy_description(_:)/title","op":"replace","value":"xpc_rich_error_copy_description"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_copy_description(_:)/fragments","op":"replace","value":[{"text":"xpc_rich_error_copy_description","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/title","op":"replace","value":"OS_xpc_object"},{"op":"replace","value":[{"kind":"identifier","text":"OS_xpc_object"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OS_xpc_object"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1OS_xpc_object/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}