{
  "abstract": [
    {
      "text": "Sets a requirement that the executable for the peer process has a valid code signature that identifies it as an Apple-signed binary with the given signing identifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@xpc_connection_set_peer_platform_identity_requirement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "xpc_connection_set_peer_platform_identity_requirement"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@xpc_connection_t",
        "text": "xpc_connection_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5CChara",
        "text": "CChar"
      },
      {
        "kind": "text",
        "text": ">?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xpc_connection_set_peer_platform_identity_requirement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "xpc_connection_set_peer_platform_identity_requirement(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_platform_identity_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "signing_identifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The XPC connection.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "connection"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The code-signing identifier for the peer process’s executable. This value is typically a Bundle ID for apps and extensions. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to indicate that any Apple-signed binary is acceptable.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "signing_identifier"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On success, ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ". Otherwise, a value from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc-connections#Errors",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you set this requirement on a connection, the operating system checks that peer process satisfies the requirement every time it sends a message to your process. If the peer process initiated the connection and its executable doesn’t satisfy the lightweight code requirement, then you don’t receive a message and the operating system doesn’t call your event handler. If your process sent a message to its peer expecting a reply, and its executable doesn’t have the requested entitlement, then you don’t receive a reply and the operating system delivers ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT-c.macro",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "It’s an error to call this function multiple times for the same connection, or to call multiple functions that set code-signing requirements on the same connection. If you do, then the operating system terminates your process.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT",
      "type": "topic",
      "url": "/documentation/xpc/xpc_error_peer_code_signing_requirement-c.macro"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc-connections#Errors": {
      "abstract": [],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc-connections#Errors",
      "kind": "section",
      "title": "Errors",
      "type": "topic",
      "url": "/documentation/xpc/xpc-connections#Errors"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_asid(_:)": {
      "abstract": [
        {
          "text": "Returns the audit session identifier of the remote peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_get_asid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@au_asid_t",
          "text": "au_asid_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_asid(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_get_asid"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_get_asid(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_get_asid(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_egid(_:)": {
      "abstract": [
        {
          "text": "Returns the EGID of the remote peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_get_egid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gid_t",
          "text": "gid_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_egid(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_get_egid"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_get_egid(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_get_egid(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_euid(_:)": {
      "abstract": [
        {
          "text": "Returns the EUID of the remote peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_get_euid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uid_t",
          "text": "uid_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_euid(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_get_euid"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_get_euid(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_get_euid(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_name(_:)": {
      "abstract": [
        {
          "text": "Returns the name of the remote service that creates the connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_get_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_name(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_get_name"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_get_name(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_get_name(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_pid(_:)": {
      "abstract": [
        {
          "text": "Returns the PID of the remote peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_get_pid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_pid(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_get_pid"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_get_pid(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_get_pid(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_code_signing_requirement(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_code_signing_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_code_signing_requirement(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_code_signing_requirement"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_set_peer_code_signing_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_set_peer_code_signing_requirement(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that contains an entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_entitlement_exists_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_entitlement_exists_requirement"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_set_peer_entitlement_exists_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that contains an entitlement with a specific value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_entitlement_matches_value_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_entitlement_matches_value_requirement"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_lightweight_code_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that matches the lightweight code requirement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_lightweight_code_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_lightweight_code_requirement(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_lightweight_code_requirement"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_set_peer_lightweight_code_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_set_peer_lightweight_code_requirement(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that identifies it as an Apple-signed binary with the given signing identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_platform_identity_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_platform_identity_requirement"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_set_peer_platform_identity_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_set_peer_platform_identity_requirement(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature and is signed by the same team identifier as the calling process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_team_identity_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_team_identity_requirement"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_set_peer_team_identity_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_set_peer_team_identity_requirement(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_connection_t": {
      "abstract": [
        {
          "text": "A type that represents a connection to a named service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_connection_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_connection_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_connection_t"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C ‘char’ type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Remote-peer-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_name(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_euid(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_egid(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_pid(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_asid(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_lightweight_code_requirement(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_code_signing_requirement(_:_:)"
      ],
      "title": "Remote peer information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "xpc_connection_set_peer_platform_identity_requirement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_platform_identity_requirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Remote-peer-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_name(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_euid(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_egid(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_pid(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_get_asid(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_lightweight_code_requirement(_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_connection_set_peer_code_signing_requirement(_:_:)"
              ],
              "title": "Remote peer information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "xpc_connection_set_peer_platform_identity_requirement"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_connection_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@xpc_connection_t",
                    "text": "xpc_connection_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "connection"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:C",
                    "text": "char"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "signing_identifier"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The XPC connection.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "connection"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The code-signing identifier for the peer process’s executable. This value is typically a Bundle ID for apps and extensions. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to indicate that any Apple-signed binary is acceptable.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "signing_identifier"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "On success, ",
                    "type": "text"
                  },
                  {
                    "code": "0",
                    "type": "codeVoice"
                  },
                  {
                    "text": ". Otherwise, a value from ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.xpc/documentation/XPC/xpc-connections#Errors",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_get_asid(_:)/title",
          "value": "xpc_connection_get_asid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_get_asid(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_get_asid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_get_pid(_:)/title",
          "value": "xpc_connection_get_pid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_get_pid(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_get_pid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_t/title",
          "value": "xpc_connection_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)/title",
          "value": "xpc_connection_set_peer_entitlement_matches_value_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_entitlement_matches_value_requirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_get_name(_:)/title",
          "value": "xpc_connection_get_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_get_name(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_get_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_lightweight_code_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_lightweight_code_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_lightweight_code_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_lightweight_code_requirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_platform_identity_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_platform_identity_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_platform_identity_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_platform_identity_requirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_entitlement_exists_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_entitlement_exists_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_entitlement_exists_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_entitlement_exists_requirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_code_signing_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_code_signing_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_code_signing_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_code_signing_requirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_get_egid(_:)/title",
          "value": "xpc_connection_get_egid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_get_egid(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_get_egid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_team_identity_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_team_identity_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_set_peer_team_identity_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_team_identity_requirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_get_euid(_:)/title",
          "value": "xpc_connection_get_euid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_connection_get_euid(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_connection_get_euid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_connection_set_peer_platform_identity_requirement(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_connection_set_peer_platform_identity_requirement(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
