{
  "abstract": [
    {
      "text": "A C type that sends messages to a server process.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@xpc_session_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "xpc_session_t"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xpc_session_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "xpc_session_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/OS_xpc_session-swift.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)OS_xpc_session",
              "text": "OS_xpc_session"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "XPC sessions are stateful connections you use to send structured messages to a separate process. Once established, a session remains active until one side of the connection cancels it, at which point the system invalidates the connection. Unlike lower-level ",
              "type": "text"
            },
            {
              "code": "xpc_connection",
              "type": "codeVoice"
            },
            {
              "text": " functions, the system makes no attempt to reestablish a connection or relaunch the service.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/OS_xpc_session-swift.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_xpc_session"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/OS_xpc_session-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_xpc_session"
        }
      ],
      "role": "symbol",
      "title": "OS_xpc_session",
      "type": "topic",
      "url": "/documentation/xpc/os_xpc_session-swift.class"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCListener": {
      "abstract": [
        {
          "text": "A type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "role": "symbol",
      "title": "XPCListener",
      "type": "topic",
      "url": "/documentation/xpc/xpclistener"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage": {
      "abstract": [
        {
          "text": "A type that represents a message sent between a session and a listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCReceivedMessage"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCReceivedMessage"
        }
      ],
      "role": "symbol",
      "title": "XPCReceivedMessage",
      "type": "topic",
      "url": "/documentation/xpc/xpcreceivedmessage"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession": {
      "abstract": [
        {
          "text": "A type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "role": "symbol",
      "title": "XPCSession",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession"
    },
    "doc://com.apple.xpc/documentation/XPC/creating-xpc-services": {
      "abstract": [
        {
          "text": "Configure a listener, establish a client session, and exchange messages between processes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
      "kind": "article",
      "role": "article",
      "title": "Creating XPC services",
      "type": "topic",
      "url": "/documentation/xpc/creating-xpc-services"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_t": {
      "abstract": [
        {
          "text": "A C type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_listener_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean that indicates whether you can retry the operation that experienced an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_rich_error_can_retry"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_rich_error_can_retry"
        }
      ],
      "role": "symbol",
      "title": "xpc_rich_error_can_retry(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_rich_error_can_retry(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)": {
      "abstract": [
        {
          "text": "Copies the string description of an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_rich_error_copy_description"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_rich_error_copy_description"
        }
      ],
      "role": "symbol",
      "title": "xpc_rich_error_copy_description(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_rich_error_copy_description(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t": {
      "abstract": [
        {
          "text": "A type that describes an error, and whether you can retry the operation that experienced the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_rich_error_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_rich_error_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_rich_error_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_rich_error_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_activate": {
      "abstract": [
        {
          "text": "Activates a session so you can send messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_activate"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_activate",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_activate",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_activate"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_activate"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_activate(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_activate(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel": {
      "abstract": [
        {
          "text": "Cancels a session, discarding any unsent messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_cancel"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_cancel",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_cancel"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_cancel"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_cancel(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_cancel(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_cancel_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_cancel_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_cancel_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_cancel_handler_t-65b6f"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-7y2lv": {
      "abstract": [
        {
          "text": "A block the session calls when it’s canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_cancel_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-7y2lv",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_cancel_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_cancel_handler_t-7y2lv"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_copy_description": {
      "abstract": [
        {
          "text": "Copies the description string of a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_copy_description"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_copy_description",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_copy_description",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_copy_description"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_copy_description(_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_copy_description"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_copy_description(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_copy_description(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_copy_description(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-c.enum": {
      "abstract": [
        {
          "text": "Options that specify how to create inactive or privileged sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_create_flags_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-c.enum",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_create_flags_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_create_flags_t-c.enum"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_create_flags_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_create_flags_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_create_flags_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_create_flags_t-swift.struct"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service": {
      "abstract": [
        {
          "text": "Establishes a connection to a launch agent or launch daemon with the name you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_create_mach_service"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_create_mach_service",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_create_mach_service"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service(_:_:_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_create_mach_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC26xpc_session_create_flags_tV",
          "text": "xpc_session_create_flags_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": "?>?) -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service(_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_create_mach_service(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_create_mach_service(_:_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service": {
      "abstract": [
        {
          "text": "Establishes a connection to an XPC service with the name you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_create_xpc_service"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_create_xpc_service",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_create_xpc_service"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service(_:_:_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_create_xpc_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC26xpc_session_create_flags_tV",
          "text": "xpc_session_create_flags_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": "?>?) -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service(_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_create_xpc_service(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_create_xpc_service(_:_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-3eb2a": {
      "abstract": [
        {
          "text": "A closure that receives an incoming message for a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_incoming_message_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-3eb2a",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_incoming_message_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_incoming_message_handler_t-3eb2a"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_incoming_message_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_incoming_message_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_incoming_message_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_incoming_message_handler_t-elj"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-2hf7c": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_reply_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-2hf7c",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_reply_handler_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_reply_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_reply_handler_t-2hf7c"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-7kfe4": {
      "abstract": [
        {
          "text": "A block that receives the reply to a message a session sends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_reply_handler_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-7kfe4",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_reply_handler_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_reply_handler_t-7kfe4"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message": {
      "abstract": [
        {
          "text": "Sends a message over the session to the destination service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_send_message"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message(_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_send_message"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async": {
      "abstract": [
        {
          "text": "Sends a message asynchronously over the session to the destination service, calling a handler after receiving a reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_send_message_with_reply_async"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message_with_reply_async",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message_with_reply_async"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async(_:_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_send_message_with_reply_async"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC27xpc_session_reply_handler_ta",
          "text": "xpc_session_reply_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async(_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message_with_reply_async(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message_with_reply_async(_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync": {
      "abstract": [
        {
          "text": "Sends a message over the session to the destination service, blocking the caller until receiving a reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_send_message_with_reply_sync"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message_with_reply_sync",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message_with_reply_sync"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync(_:_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_send_message_with_reply_sync"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_rich_error_t",
          "text": "xpc_rich_error_t"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync(_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_send_message_with_reply_sync(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_send_message_with_reply_sync(_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler": {
      "abstract": [
        {
          "text": "Sets a handler the session calls when it’s canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_set_cancel_handler"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_set_cancel_handler",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_set_cancel_handler"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_set_cancel_handler"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC28xpc_session_cancel_handler_ta",
          "text": "xpc_session_cancel_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_set_cancel_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_set_cancel_handler(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler": {
      "abstract": [
        {
          "text": "Sets a handler to receive incoming messages for a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_set_incoming_message_handler"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_set_incoming_message_handler",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_set_incoming_message_handler"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to receive incoming messages for a session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_set_incoming_message_handler"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC38xpc_session_incoming_message_handler_ta",
          "text": "xpc_session_incoming_message_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_set_incoming_message_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_set_incoming_message_handler(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_set_peer_code_signing_requirement(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_set_peer_code_signing_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_session_t",
          "text": "xpc_session_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_set_peer_code_signing_requirement(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_set_peer_code_signing_requirement"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_set_peer_code_signing_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_set_peer_code_signing_requirement(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_set_target_queue": {
      "abstract": [
        {
          "text": "Sets the target dispatch queue on an inactive session for processing messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_session_set_target_queue"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_set_target_queue",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_set_target_queue",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_set_target_queue"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_set_target_queue(_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_set_target_queue"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_set_target_queue(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_set_target_queue(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_set_target_queue(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0": {
      "abstract": [
        {
          "text": "A C type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_t-10if0"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_t-49tiv": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_t-49tiv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_t-49tiv"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interprocess-communication",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
        "doc://com.apple.xpc/documentation/XPC/XPCListener",
        "doc://com.apple.xpc/documentation/XPC/XPCSession",
        "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage",
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_t"
      ],
      "title": "Interprocess communication"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-session",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_session_t-49tiv",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service(_:_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service(_:_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-swift.struct",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_copy_description(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_set_target_queue(_:_:)"
      ],
      "title": "Creating a session"
    },
    {
      "anchor": "Managing-life-cycle",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_session_activate(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-elj",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-65b6f"
      ],
      "title": "Managing life cycle"
    },
    {
      "anchor": "Sending-messages",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t",
        "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-2hf7c",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync(_:_:_:)"
      ],
      "title": "Sending messages"
    },
    {
      "anchor": "Working-with-code-signing",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_session_set_peer_code_signing_requirement(_:_:)"
      ],
      "title": "Working with code signing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "xpc_session_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-session",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_session_create_xpc_service",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_create_mach_service",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_create_flags_t-c.enum",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_set_target_queue",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_copy_description"
              ],
              "title": "Creating a session"
            },
            {
              "anchor": "Managing-life-cycle",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_session_activate",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_set_incoming_message_handler",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_incoming_message_handler_t-3eb2a",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_set_cancel_handler",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_cancel_handler_t-7y2lv"
              ],
              "title": "Managing life cycle"
            },
            {
              "anchor": "Sending-messages",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_async",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_reply_handler_t-7kfe4",
                "doc://com.apple.xpc/documentation/XPC/xpc_session_send_message_with_reply_sync",
                "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_t",
                "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_can_retry(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_rich_error_copy_description(_:)"
              ],
              "title": "Sending messages"
            },
            {
              "anchor": "Working-with-code-signing",
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_session_set_peer_code_signing_requirement(_:_:)"
              ],
              "title": "Working with code signing"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interprocess-communication",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
                "doc://com.apple.xpc/documentation/XPC/xpc_listener_t"
              ],
              "title": "Interprocess communication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_xpc_session",
                    "text": "NSObject<OS_xpc_session>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "xpc_session_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/title",
          "value": "xpc_rich_error_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_rich_error_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_rich_error_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_set_peer_code_signing_requirement(_:_:)/title",
          "value": "xpc_session_set_peer_code_signing_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_set_peer_code_signing_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_set_peer_code_signing_requirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/title",
          "value": "xpc_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/title",
          "value": "xpc_session_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_copy_description(_:)/title",
          "value": "xpc_rich_error_copy_description"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_copy_description(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_rich_error_copy_description"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_can_retry(_:)/title",
          "value": "xpc_rich_error_can_retry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_rich_error_can_retry(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_rich_error_can_retry"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_session_t-10if0"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_session_t-10if0"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
