{
  "abstract": [
    {
      "text": "An integer property that indicates the desired time interval of the activity in seconds.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@XPC_ACTIVITY_INTERVAL",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XPC_ACTIVITY_INTERVAL"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5CChara",
        "text": "CChar"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XPC_ACTIVITY_INTERVAL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "XPC_ACTIVITY_INTERVAL"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The activity doesn’t run more than once per time interval. Due to the nature of XPC Activity finding an opportune time to run the activity, any two occurrences may be more or less than ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " seconds apart, but on average are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " seconds apart. The presence of this key implies the following, unless you override these values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REPEATING",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with a value of ",
                      "type": "text"
                    },
                    {
                      "code": "true",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with a value of half the interval. The delay enforces a minimum distance between any two occurrences.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with a value of half the interval. The grace period is the amount of time that passes after the end of the interval before more aggressive scheduling occurs. The grace period doesn’t increase the size of the interval.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY": {
      "abstract": [
        {
          "text": "An integer property that indicates the number of seconds to delay before beginning the activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_DELAY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_DELAY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_DELAY"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_DELAY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_delay"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD": {
      "abstract": [
        {
          "text": "An integer property that indicates the number of seconds to allow as a grace period before the scheduling of the activity becomes more aggressive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_GRACE_PERIOD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_GRACE_PERIOD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_GRACE_PERIOD"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_GRACE_PERIOD",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_grace_period"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL": {
      "abstract": [
        {
          "text": "An integer property that indicates the desired time interval of the activity in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 15-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_15_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_15_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_15_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_15_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY": {
      "abstract": [
        {
          "text": "A constant that represents a one-day time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_DAY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_DAY"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_1_DAY",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_1_day"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR": {
      "abstract": [
        {
          "text": "A constant that represents a 1-hour time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_HOUR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_HOUR"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_1_HOUR",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_1_hour"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 1-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_1_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_1_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_1_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 30-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_30_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_30_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_30_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_30_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS": {
      "abstract": [
        {
          "text": "A constant that represents a 4-hour time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_4_HOURS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_4_HOURS"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_4_HOURS",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_4_hours"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN": {
      "abstract": [
        {
          "text": "A constant that represents a 5-minute time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_5_MIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_5_MIN"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_5_MIN",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_5_min"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS": {
      "abstract": [
        {
          "text": "A constant that represents a seven-day time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_7_DAYS",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_7_days"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS": {
      "abstract": [
        {
          "text": "A constant that represents an 8-hour time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_8_HOURS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_INTERVAL_8_HOURS"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_INTERVAL_8_HOURS",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_interval_8_hours"
    },
    "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REPEATING": {
      "abstract": [
        {
          "text": "A Boolean property that indicates whether this is a repeating activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_REPEATING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_REPEATING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPC_ACTIVITY_REPEATING"
        }
      ],
      "role": "symbol",
      "title": "XPC_ACTIVITY_REPEATING",
      "type": "topic",
      "url": "/documentation/xpc/xpc_activity_repeating"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C ‘char’ type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Time-Intervals",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY",
        "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS"
      ],
      "title": "Time Intervals"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XPC_ACTIVITY_INTERVAL"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Time-Intervals",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY",
                "doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS"
              ],
              "title": "Time Intervals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:C",
                    "text": "char"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XPC_ACTIVITY_INTERVAL"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_1_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_1_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_DAY/title",
          "value": "XPC_ACTIVITY_INTERVAL_1_DAY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_DAY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_1_DAY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_5_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_5_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_5_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_5_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_REPEATING/title",
          "value": "XPC_ACTIVITY_REPEATING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_REPEATING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_REPEATING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_DELAY/title",
          "value": "XPC_ACTIVITY_DELAY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_DELAY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_DELAY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_15_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_15_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_15_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_15_MIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL/title",
          "value": "XPC_ACTIVITY_INTERVAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_8_HOURS/title",
          "value": "XPC_ACTIVITY_INTERVAL_8_HOURS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_8_HOURS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_8_HOURS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_HOUR/title",
          "value": "XPC_ACTIVITY_INTERVAL_1_HOUR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_HOUR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_1_HOUR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_7_DAYS/title",
          "value": "XPC_ACTIVITY_INTERVAL_7_DAYS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_7_DAYS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_7_DAYS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_4_HOURS/title",
          "value": "XPC_ACTIVITY_INTERVAL_4_HOURS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_4_HOURS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_4_HOURS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_GRACE_PERIOD/title",
          "value": "XPC_ACTIVITY_GRACE_PERIOD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_GRACE_PERIOD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_GRACE_PERIOD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_30_MIN/title",
          "value": "XPC_ACTIVITY_INTERVAL_30_MIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_30_MIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XPC_ACTIVITY_INTERVAL_30_MIN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_activity_interval"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_activity_interval"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
