{
  "abstract": [
    {
      "text": "Returns the length of the underlying string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/xpc_string_get_length(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@xpc_string_get_length",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "xpc_string_get_length"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@xpc_object_t",
        "text": "xpc_object_t"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xpc_string_get_length"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "xpc_string_get_length(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_string_get_length"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "xstring"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_object_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_object_t",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The string object which is to be examined.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "xstring"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The length of the underlying string, not including the ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": "-terminator.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_object_t": {
      "abstract": [
        {
          "text": "A type that can describe all XPC objects, including dictionaries, arrays, strings, and numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_object_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_object_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_object_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_object_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_string_create(_:)": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents a null-terminated C-string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_string_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_string_create(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_string_create"
        }
      ],
      "role": "symbol",
      "title": "xpc_string_create(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_string_create(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_string_create_with_format": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents a C-string that the specified format string and arguments generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xpc_string_create_with_format"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_string_create_with_format",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_string_create_with_format",
      "type": "topic",
      "url": "/documentation/xpc/xpc_string_create_with_format"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_string_create_with_format_and_arguments(_:_:)": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents a C-string that the specified format string and argument list pointer generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_string_create_with_format_and_arguments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14CVaListPointerV",
          "text": "CVaListPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_string_create_with_format_and_arguments(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_string_create_with_format_and_arguments"
        }
      ],
      "role": "symbol",
      "title": "xpc_string_create_with_format_and_arguments(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_string_create_with_format_and_arguments(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_string_get_length(_:)": {
      "abstract": [
        {
          "text": "Returns the length of the underlying string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_string_get_length"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_string_get_length(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_string_get_length"
        }
      ],
      "role": "symbol",
      "title": "xpc_string_get_length(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_string_get_length(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_string_get_string_ptr(_:)": {
      "abstract": [
        {
          "text": "Returns a pointer to the internal storage of a string object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_string_get_string_ptr"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_string_get_string_ptr(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_string_get_string_ptr"
        }
      ],
      "role": "symbol",
      "title": "xpc_string_get_string_ptr(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_string_get_string_ptr(_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@size_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "size_t",
      "type": "topic",
      "url": "/documentation/kernel/size_t"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "String-objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_string_create(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_string_create_with_format_and_arguments(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_string_get_string_ptr(_:)"
      ],
      "title": "String objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "xpc_string_get_length"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_string_get_length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xpc/documentation/XPC"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "String-objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xpc/documentation/XPC/xpc_string_create(_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_string_create_with_format",
                "doc://com.apple.xpc/documentation/XPC/xpc_string_create_with_format_and_arguments(_:_:)",
                "doc://com.apple.xpc/documentation/XPC/xpc_string_get_string_ptr(_:)"
              ],
              "title": "String objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@size_t",
                    "text": "size_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "xpc_string_get_length"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_object_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@xpc_object_t",
                    "text": "xpc_object_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "xstring"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The string object which is to be examined.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "xstring"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The length of the underlying string, not including the ",
                    "type": "text"
                  },
                  {
                    "code": "NULL",
                    "type": "codeVoice"
                  },
                  {
                    "text": "-terminator.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/title",
          "value": "xpc_object_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_object_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_string_get_length(_:)/title",
          "value": "xpc_string_get_length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_string_get_length(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_string_get_length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_string_create(_:)/title",
          "value": "xpc_string_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_string_create(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_string_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_string_get_string_ptr(_:)/title",
          "value": "xpc_string_get_string_ptr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_string_get_string_ptr(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_string_get_string_ptr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_string_create_with_format_and_arguments(_:_:)/title",
          "value": "xpc_string_create_with_format_and_arguments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_string_create_with_format_and_arguments(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_string_create_with_format_and_arguments"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpc_string_get_length(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xpc/xpc_string_get_length(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
