{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS"},"kind":"symbol","sections":[],"metadata":{"platforms":[{"deprecated":false,"name":"macOS","beta":false,"introducedAt":"10.9","unavailable":false}],"roleHeading":"Global Variable","title":"XPC_ACTIVITY_INTERVAL_8_HOURS","externalID":"c:@XPC_ACTIVITY_INTERVAL_8_HOURS","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_8_HOURS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"role":"symbol","modules":[{"name":"XPC"}],"navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_8_HOURS"}],"symbolKind":"var"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"abstract":[{"type":"text","text":"A constant that represents an 8-hour time interval."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_8_HOURS"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","identifier":"doc://com.externally.resolved.symbol/s:s5Int64V","kind":"typeIdentifier","text":"Int64"}],"platforms":["macOS"]}]}],"seeAlsoSections":[{"generated":true,"anchor":"Time-Intervals","identifiers":["doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS"],"title":"Time Intervals"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/xpc/xpc_activity_interval_8_hours"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/xpc/xpc_activity_interval_8_hours"]}],"references":{"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN":{"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN","type":"topic","abstract":[{"type":"text","text":"A constant that represents a 30-minute time interval."}],"kind":"symbol","role":"symbol","url":"/documentation/xpc/xpc_activity_interval_30_min","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_30_MIN"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_30_MIN"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"title":"XPC_ACTIVITY_INTERVAL_30_MIN"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_4_HOURS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"url":"/documentation/xpc/xpc_activity_interval_4_hours","kind":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS","title":"XPC_ACTIVITY_INTERVAL_4_HOURS","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_4_HOURS"}],"abstract":[{"type":"text","text":"A constant that represents a 4-hour time interval."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_8_HOURS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_8_HOURS"}],"kind":"symbol","title":"XPC_ACTIVITY_INTERVAL_8_HOURS","role":"symbol","abstract":[{"type":"text","text":"A constant that represents an 8-hour time interval."}],"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_8_HOURS","url":"/documentation/xpc/xpc_activity_interval_8_hours"},"doc://com.externally.resolved.symbol/s:s5Int64V":{"url":"/documentation/Swift/Int64","type":"topic","abstract":[{"type":"text","text":"A 64-bit signed integer value type."}],"role":"symbol","title":"Int64","kind":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int64","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int64V"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL":{"role":"symbol","type":"topic","url":"/documentation/xpc/xpc_activity_interval","identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL"}],"title":"XPC_ACTIVITY_INTERVAL","abstract":[{"type":"text","text":"An integer property that indicates the desired time interval of the activity in seconds."}]},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN":{"url":"/documentation/xpc/xpc_activity_interval_5_min","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_5_MIN"}],"abstract":[{"type":"text","text":"A constant that represents a 5-minute time interval."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN","title":"XPC_ACTIVITY_INTERVAL_5_MIN","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_5_MIN"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"}]},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_1_DAY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_1_DAY"}],"kind":"symbol","identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY","title":"XPC_ACTIVITY_INTERVAL_1_DAY","role":"symbol","abstract":[{"type":"text","text":"A constant that represents a one-day time interval."}],"url":"/documentation/xpc/xpc_activity_interval_1_day"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN":{"url":"/documentation/xpc/xpc_activity_interval_15_min","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_15_MIN"}],"abstract":[{"type":"text","text":"A constant that represents a 15-minute time interval."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN","title":"XPC_ACTIVITY_INTERVAL_15_MIN","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_15_MIN"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}]},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS":{"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS","type":"topic","abstract":[{"type":"text","text":"A constant that represents a seven-day time interval."}],"kind":"symbol","role":"symbol","url":"/documentation/xpc/xpc_activity_interval_7_days","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_7_DAYS"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_7_DAYS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"}],"title":"XPC_ACTIVITY_INTERVAL_7_DAYS"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_1_HOUR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_1_HOUR"}],"kind":"symbol","identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR","title":"XPC_ACTIVITY_INTERVAL_1_HOUR","role":"symbol","abstract":[{"type":"text","text":"A constant that represents a 1-hour time interval."}],"url":"/documentation/xpc/xpc_activity_interval_1_hour"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN":{"role":"symbol","type":"topic","url":"/documentation/xpc/xpc_activity_interval_1_min","identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XPC_ACTIVITY_INTERVAL_1_MIN","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"}],"navigatorTitle":[{"text":"XPC_ACTIVITY_INTERVAL_1_MIN","kind":"identifier"}],"title":"XPC_ACTIVITY_INTERVAL_1_MIN","abstract":[{"text":"A constant that represents a 1-minute time interval.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"macOS","beta":false,"introducedAt":"10.9","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Global Variable","path":"/metadata/roleHeading","op":"replace"},{"value":"XPC_ACTIVITY_INTERVAL_8_HOURS","path":"/metadata/title","op":"replace"},{"value":"var","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_8_HOURS"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"title":"Time Intervals","anchor":"Time-Intervals","identifiers":["doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_MIN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_5_MIN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_15_MIN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_30_MIN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_HOUR","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_4_HOURS","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_1_DAY","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_INTERVAL_7_DAYS"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@T@int64_t","kind":"typeIdentifier","text":"int64_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_8_HOURS"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_30_MIN/title","value":"XPC_ACTIVITY_INTERVAL_30_MIN"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_30_MIN/fragments","value":[{"text":"XPC_ACTIVITY_INTERVAL_30_MIN","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_4_HOURS/title","value":"XPC_ACTIVITY_INTERVAL_4_HOURS"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_4_HOURS/fragments","value":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_4_HOURS"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_8_HOURS/title","value":"XPC_ACTIVITY_INTERVAL_8_HOURS"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_8_HOURS/fragments","value":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_8_HOURS"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL/title","value":"XPC_ACTIVITY_INTERVAL"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL/fragments","value":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_5_MIN/title","value":"XPC_ACTIVITY_INTERVAL_5_MIN"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_5_MIN/fragments","value":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_5_MIN"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_DAY/title","value":"XPC_ACTIVITY_INTERVAL_1_DAY"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_DAY/fragments","value":[{"text":"XPC_ACTIVITY_INTERVAL_1_DAY","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_15_MIN/title","value":"XPC_ACTIVITY_INTERVAL_15_MIN"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_15_MIN/fragments","value":[{"text":"XPC_ACTIVITY_INTERVAL_15_MIN","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_7_DAYS/title","value":"XPC_ACTIVITY_INTERVAL_7_DAYS"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_7_DAYS/fragments","value":[{"text":"XPC_ACTIVITY_INTERVAL_7_DAYS","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_HOUR/title","value":"XPC_ACTIVITY_INTERVAL_1_HOUR"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_HOUR/fragments","value":[{"text":"XPC_ACTIVITY_INTERVAL_1_HOUR","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_MIN/title","value":"XPC_ACTIVITY_INTERVAL_1_MIN"},{"op":"replace","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_INTERVAL_1_MIN/fragments","value":[{"kind":"identifier","text":"XPC_ACTIVITY_INTERVAL_1_MIN"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}