{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_listener_reject_peer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0","text":"xpc_session_t","preciseIdentifier":"c:@T@xpc_session_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"peer"},{"kind":"text","text":", "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"char","preciseIdentifier":"c:C"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"reason"},{"kind":"text","text":");"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"]}]},{"parameters":[{"name":"peer","content":[{"inlineContent":[{"type":"text","text":"The peer session request attempting to connect to the listener. This must be a session received in "},{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"reason","content":[{"inlineContent":[{"text":"A description of why the listener rejected the peer session request.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This function calls ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel","type":"reference"},{"text":" with the peer session, and you can’t use the session after rejecting it.","type":"text"}]}],"kind":"content"}],"sections":[],"abstract":[{"text":"Rejects an incoming peer session request.","type":"text"}],"identifier":{"url":"doc://com.apple.xpc/documentation/XPC/xpc_listener_reject_peer","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"seeAlsoSections":[{"anchor":"Managing-the-life-cycle","generated":true,"identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_listener_activate","doc://com.apple.xpc/documentation/XPC/xpc_listener_cancel"],"title":"Managing the life cycle"}],"variants":[{"paths":["/documentation/xpc/xpc_listener_reject_peer"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"XPC"}],"symbolKind":"func","platforms":[{"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"17.0","deprecated":false},{"name":"macOS","beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false}],"fragments":[{"kind":"identifier","text":"xpc_listener_reject_peer"}],"role":"symbol","roleHeading":"Function","title":"xpc_listener_reject_peer","externalID":"c:@F@xpc_listener_reject_peer","navigatorTitle":[{"kind":"identifier","text":"xpc_listener_reject_peer"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t":{"kind":"symbol","abstract":[{"type":"text","text":"A block that receives an incoming peer session request from a client."}],"type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_listener_incoming_session_handler_t","navigatorTitle":[{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"}],"url":"/documentation/xpc/xpc_listener_incoming_session_handler_t","title":"xpc_listener_incoming_session_handler_t","role":"symbol"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.xpc/documentation/XPC/xpc_listener_activate":{"url":"/documentation/xpc/xpc_listener_activate","type":"topic","abstract":[{"text":"Activates an inactive listener.","type":"text"}],"role":"symbol","title":"xpc_listener_activate","kind":"symbol","fragments":[{"text":"xpc_listener_activate","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_listener_activate"},"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel":{"type":"topic","fragments":[{"kind":"identifier","text":"xpc_session_cancel"}],"kind":"symbol","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_cancel","title":"xpc_session_cancel","role":"symbol","abstract":[{"type":"text","text":"Cancels a session, discarding any unsent messages."}],"url":"/documentation/xpc/xpc_session_cancel"},"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0":{"url":"/documentation/xpc/xpc_session_t-10if0","navigatorTitle":[{"kind":"identifier","text":"xpc_session_t"}],"abstract":[{"text":"A C type that sends messages to a server process.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0","title":"xpc_session_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"xpc_session_t","kind":"identifier"}]},"doc://com.apple.xpc/documentation/XPC/xpc_listener_reject_peer":{"url":"/documentation/xpc/xpc_listener_reject_peer","type":"topic","abstract":[{"text":"Rejects an incoming peer session request.","type":"text"}],"role":"symbol","title":"xpc_listener_reject_peer","kind":"symbol","fragments":[{"text":"xpc_listener_reject_peer","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_listener_reject_peer"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC/xpc_listener_cancel":{"url":"/documentation/xpc/xpc_listener_cancel","type":"topic","abstract":[{"text":"Cancels a listener.","type":"text"}],"role":"symbol","title":"xpc_listener_cancel","kind":"symbol","fragments":[{"text":"xpc_listener_cancel","kind":"identifier"}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_listener_cancel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/title","op":"replace","value":"xpc_listener_incoming_session_handler_t"},{"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/fragments","op":"replace","value":[{"kind":"identifier","text":"xpc_listener_incoming_session_handler_t"}]},{"op":"replace","value":[{"text":"xpc_listener_incoming_session_handler_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_incoming_session_handler_t/navigatorTitle"},{"op":"replace","value":"xpc_session_t","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/title"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_session_t"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_session_t"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}