{"seeAlsoSections":[{"anchor":"State","identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)","doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)","doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts","doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE"],"generated":true,"title":"State"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/xpc/xpc_activity_set_state(_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/xpc/xpc_activity_set_state(_:_:)"]}],"metadata":{"title":"xpc_activity_set_state(_:_:)","roleHeading":"Function","symbolKind":"func","externalID":"c:@F@xpc_activity_set_state","role":"symbol","navigatorTitle":[{"text":"xpc_activity_set_state","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xpc_activity_set_state","kind":"identifier"},{"text":"(","kind":"text"},{"text":"xpc_activity_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_activity_t"},{"text":", ","kind":"text"},{"text":"xpc_activity_state_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_activity_state_t"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"XPC"}],"platforms":[{"deprecated":false,"introducedAt":"10.9","unavailable":false,"name":"macOS","beta":false}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xpc_activity_set_state"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"activity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_activity_t","text":"xpc_activity_t","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_activity_state_t","text":"xpc_activity_state_t","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the state was successfully updated; otherwise, returns "},{"code":"false","type":"codeVoice"},{"type":"text","text":" if the requested state transition is not valid."}]}]}],"abstract":[{"text":"Updates the current state of an activity.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"sections":[],"references":{"doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts":{"identifier":"doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts","role":"collectionGroup","url":"/documentation/xpc/xpc-activity-state-t-swift-consts","abstract":[{"type":"text","text":"A type that represents the state of an activity."}],"kind":"article","title":"xpc_activity_state_t","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER":{"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER","type":"topic","abstract":[{"type":"text","text":"The activity needs to wait until it satisfies its criteria again."}],"kind":"symbol","role":"symbol","url":"/documentation/xpc/xpc_activity_state_defer","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_STATE_DEFER"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_STATE_DEFER"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"XPC_ACTIVITY_STATE_DEFER"},"doc://com.externally.resolved.symbol/s:Sb":{"identifier":"doc://com.externally.resolved.symbol/s:Sb","title":"Bool","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Bool","kind":"identifier"}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_STATE_CHECK_IN"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"/documentation/xpc/xpc_activity_state_check_in","kind":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN","title":"XPC_ACTIVITY_STATE_CHECK_IN","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_STATE_CHECK_IN"}],"abstract":[{"type":"text","text":"The activity has completed a check-in with the system."}],"role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Returns the current state of an activity."}],"type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)","navigatorTitle":[{"kind":"identifier","text":"xpc_activity_get_state"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_get_state"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_activity_t","text":"xpc_activity_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@xpc_activity_state_t","text":"xpc_activity_state_t"}],"url":"/documentation/xpc/xpc_activity_get_state(_:)","title":"xpc_activity_get_state(_:)","role":"symbol"},"doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t":{"kind":"symbol","abstract":[{"type":"text","text":"A type that represents the state of an activity."}],"type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t","navigatorTitle":[{"kind":"identifier","text":"xpc_activity_state_t"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_state_t"}],"url":"/documentation/xpc/xpc_activity_state_t","title":"xpc_activity_state_t","role":"symbol"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT":{"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT","role":"symbol","url":"/documentation/xpc/xpc_activity_state_wait","abstract":[{"text":"The activity is waiting for an opportunity to run.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_STATE_WAIT"}],"title":"XPC_ACTIVITY_STATE_WAIT","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_STATE_WAIT"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_STATE_RUN"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_STATE_RUN"}],"kind":"symbol","title":"XPC_ACTIVITY_STATE_RUN","role":"symbol","abstract":[{"type":"text","text":"The activity is eligible to run according to its criteria."}],"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN","url":"/documentation/xpc/xpc_activity_state_run"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE":{"identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE","role":"symbol","url":"/documentation/xpc/xpc_activity_state_continue","abstract":[{"text":"The activity continues its operation beyond the return of its handler block.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"XPC_ACTIVITY_STATE_CONTINUE"}],"title":"XPC_ACTIVITY_STATE_CONTINUE","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"XPC_ACTIVITY_STATE_CONTINUE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.xpc/documentation/XPC/xpc_activity_t":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_t"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"xpc_activity_t"}],"kind":"symbol","title":"xpc_activity_t","role":"symbol","abstract":[{"type":"text","text":"An XPC activity object."}],"identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_t","url":"/documentation/xpc/xpc_activity_t"},"doc://com.apple.xpc/documentation/XPC":{"role":"collection","abstract":[{"text":"Access a low-level interprocess communication mechanism.","type":"text"}],"kind":"symbol","url":"/documentation/xpc","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC","title":"XPC"},"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE":{"role":"symbol","type":"topic","url":"/documentation/xpc/xpc_activity_state_done","identifier":"doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"XPC_ACTIVITY_STATE_DONE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"XPC_ACTIVITY_STATE_DONE","kind":"identifier"}],"title":"XPC_ACTIVITY_STATE_DONE","abstract":[{"text":"The activity is complete.","type":"text"}]},"doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)":{"url":"/documentation/xpc/xpc_activity_set_state(_:_:)","navigatorTitle":[{"kind":"identifier","text":"xpc_activity_set_state"}],"abstract":[{"text":"Updates the current state of an activity.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_set_state(_:_:)","title":"xpc_activity_set_state(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_set_state"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@xpc_activity_t","kind":"typeIdentifier","text":"xpc_activity_t"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@xpc_activity_state_t","kind":"typeIdentifier","text":"xpc_activity_state_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)":{"title":"xpc_activity_should_defer(_:)","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)","type":"topic","abstract":[{"type":"text","text":"Tests whether to defer an activity."}],"role":"symbol","url":"/documentation/xpc/xpc_activity_should_defer(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_should_defer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"xpc_activity_t","preciseIdentifier":"c:@T@xpc_activity_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"xpc_activity_should_defer"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"introducedAt":"10.9","unavailable":false,"name":"macOS","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Function","path":"/metadata/roleHeading"},{"op":"replace","value":"xpc_activity_set_state","path":"/metadata/title"},{"op":"replace","value":"func","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"xpc_activity_set_state","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.xpc/documentation/XPC"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"State","anchor":"State","generated":true,"identifiers":["doc://com.apple.xpc/documentation/XPC/xpc_activity_get_state(_:)","doc://com.apple.xpc/documentation/XPC/xpc_activity_should_defer(_:)","doc://com.apple.xpc/documentation/XPC/xpc-activity-state-t-swift-consts","doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CHECK_IN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_WAIT","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_RUN","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DEFER","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_CONTINUE","doc://com.apple.xpc/documentation/XPC/XPC_ACTIVITY_STATE_DONE"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"bool"},{"kind":"text","text":" "},{"kind":"identifier","text":"xpc_activity_set_state"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@xpc_activity_t","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_t","kind":"typeIdentifier","text":"xpc_activity_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"activity"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@xpc_activity_state_t","identifier":"doc://com.apple.xpc/documentation/XPC/xpc_activity_state_t","kind":"typeIdentifier","text":"xpc_activity_state_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":");"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the state was successfully updated; otherwise, returns ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" if the requested state transition is not valid.","type":"text"}]}],"kind":"content"},"op":"replace"},{"op":"replace","value":"XPC_ACTIVITY_STATE_DEFER","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DEFER/title"},{"op":"replace","value":[{"kind":"identifier","text":"XPC_ACTIVITY_STATE_DEFER"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DEFER/fragments"},{"op":"replace","value":"XPC_ACTIVITY_STATE_CHECK_IN","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CHECK_IN/title"},{"op":"replace","value":[{"kind":"identifier","text":"XPC_ACTIVITY_STATE_CHECK_IN"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CHECK_IN/fragments"},{"op":"replace","value":"xpc_activity_get_state","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_get_state(_:)/title"},{"op":"replace","value":[{"text":"xpc_activity_get_state","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_get_state(_:)/fragments"},{"op":"replace","value":"xpc_activity_state_t","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_state_t/title"},{"op":"replace","value":[{"text":"xpc_activity_state_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_state_t/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_activity_state_t"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_state_t/navigatorTitle"},{"op":"replace","value":"XPC_ACTIVITY_STATE_WAIT","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_WAIT/title"},{"op":"replace","value":[{"kind":"identifier","text":"XPC_ACTIVITY_STATE_WAIT"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_WAIT/fragments"},{"op":"replace","value":"XPC_ACTIVITY_STATE_RUN","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_RUN/title"},{"op":"replace","value":[{"text":"XPC_ACTIVITY_STATE_RUN","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_RUN/fragments"},{"op":"replace","value":"XPC_ACTIVITY_STATE_CONTINUE","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CONTINUE/title"},{"op":"replace","value":[{"text":"XPC_ACTIVITY_STATE_CONTINUE","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_CONTINUE/fragments"},{"op":"replace","value":"xpc_activity_t","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_t/title"},{"op":"replace","value":[{"text":"xpc_activity_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_t/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_activity_t"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_t/navigatorTitle"},{"op":"replace","value":"XPC_ACTIVITY_STATE_DONE","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DONE/title"},{"op":"replace","value":[{"text":"XPC_ACTIVITY_STATE_DONE","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1XPC_ACTIVITY_STATE_DONE/fragments"},{"op":"replace","value":"xpc_activity_set_state","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_set_state(_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_activity_set_state"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_set_state(_:_:)/fragments"},{"op":"replace","value":"xpc_activity_should_defer","path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_should_defer(_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"xpc_activity_should_defer"}],"path":"/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_activity_should_defer(_:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}