{
  "abstract": [
    {
      "text": "An ordered random-access collection of XPC objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/XPCArray"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:3XPC8XPCArrayV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XPCArray"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XPCArray"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "XPCArray"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPCArray"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray": {
      "abstract": [
        {
          "text": "An ordered random-access collection of XPC objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCArray"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCArray"
        }
      ],
      "role": "symbol",
      "title": "XPCArray",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/IndexValuePair": {
      "abstract": [
        {
          "text": "A type that contains an index and the object at that index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IndexValuePair"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/IndexValuePair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IndexValuePair"
        }
      ],
      "role": "symbol",
      "title": "XPCArray.IndexValuePair",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/indexvaluepair"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/copy(into:)": {
      "abstract": [
        {
          "text": "Copies the elements of the array to a different array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "into"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC8XPCArrayV",
          "text": "XPCArray"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/copy(into:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "copy(into:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/copy(into:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/count": {
      "abstract": [
        {
          "text": "The number of elements in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/count",
      "kind": "symbol",
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/count"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/forEach(_:)-2ib8a": {
      "abstract": [
        {
          "text": "Calls the given closure with an index and element of the array in the same order as a for-in loop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forEach"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/forEach(_:)-2ib8a",
      "kind": "symbol",
      "role": "symbol",
      "title": "forEach(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/foreach(_:)-2ib8a"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/forEach(_:)-6obs3": {
      "abstract": [
        {
          "text": "Calls the given closure with each element in the array in the same order as a for-in loop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forEach"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC8XPCArrayV",
          "text": "XPCArray"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC8XPCArrayV14IndexValuePaira",
          "text": "IndexValuePair"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/forEach(_:)-6obs3",
      "kind": "symbol",
      "role": "symbol",
      "title": "forEach(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/foreach(_:)-6obs3"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/init()": {
      "abstract": [
        {
          "text": "Creates a new, empty array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/init()"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new array that contains the given XPC object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/init(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/isEmpty": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the array is empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/isEmpty",
      "kind": "symbol",
      "role": "symbol",
      "title": "isEmpty",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/isempty"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/map(_:)": {
      "abstract": [
        {
          "text": "Returns an array containing the results of mapping the given closure over the sequence’s elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "map"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "ReturnType"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC8XPCArrayV",
          "text": "XPCArray"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC8XPCArrayV14IndexValuePaira",
          "text": "IndexValuePair"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "ReturnType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "text": "ReturnType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/map(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "map(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/map(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-1s7qq": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as an XPC dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-1s7qq",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:)-1s7qq"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-2f94n": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as a signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-2f94n",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:)-2f94n"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-56wjj": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as an XPC object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-56wjj",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:)-56wjj"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-6c9gh": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-6c9gh",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:)-6c9gh"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-8wubg": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as a floating point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-8wubg",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:)-8wubg"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-9x9ho": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as an unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-9x9ho",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:)-9x9ho"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-i6v5": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as a Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-i6v5",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:)-i6v5"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-1bilh": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as a Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-1bilh",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:as:)-1bilh"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-2hql9": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as a floating point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-2hql9",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:as:)-2hql9"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-3ae6x": {
      "abstract": [
        {
          "text": "Reads the value associated with the given key as an XPC dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-3ae6x",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:as:)-3ae6x"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-3tgp4": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as an XPC object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-3tgp4",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:as:)-3tgp4"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-6grs4": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as an integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-6grs4",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:as:)-6grs4"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-931lh": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as an XPC object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-931lh",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:as:)-931lh"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-9ukjj": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-9ukjj",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:as:)-9ukjj"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:default:)-2bn95": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as a Boolean value, falling back to the given default value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ".Type, "
        },
        {
          "kind": "externalParam",
          "text": "default"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:default:)-2bn95",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:default:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:as:default:)-2bn95"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:default:)-3k2qm": {
      "abstract": [
        {
          "text": "Reads and writes the value at the given index as a floating point value, falling back to the given default value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ".Type, "
        },
        {
          "kind": "externalParam",
          "text": "default"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:default:)-3k2qm",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:default:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/subscript(_:as:default:)-3k2qm"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCArray/withUnsafeUnderlyingArray(_:)": {
      "abstract": [
        {
          "text": "Calls a closure with an unsafe reference to the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withUnsafeUnderlyingArray"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "ReturnType"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "ReturnType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "ReturnType"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCArray/withUnsafeUnderlyingArray(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "withUnsafeUnderlyingArray(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcarray/withunsafeunderlyingarray(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_append_value(_:_:)": {
      "abstract": [
        {
          "text": "Appends an object to an XPC array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_append_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_append_value(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_append_value"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_append_value(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_append_value(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_apply(_:_:)": {
      "abstract": [
        {
          "text": "Invokes the specified block for every value in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_apply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_apply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_apply"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_apply(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_apply(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_create(_:_:)": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents an array of XPC objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_create(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_create"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_create(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_create(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_create_connection(_:_:)": {
      "abstract": [
        {
          "text": "Creates a connection object from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_create_connection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_create_connection(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_create_connection"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_create_connection(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_create_connection(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_create_empty()": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents an array of XPC objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_create_empty"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_create_empty()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_create_empty"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_create_empty()",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_create_empty()"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_dup_fd(_:_:)": {
      "abstract": [
        {
          "text": "Gets a file descriptor from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_dup_fd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_dup_fd(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_dup_fd"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_dup_fd(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_dup_fd(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_array(_:_:)": {
      "abstract": [
        {
          "text": "Returns the array at the specified index in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_array"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_array(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_array"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_array(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_array(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_bool(_:_:)": {
      "abstract": [
        {
          "text": "Gets a Boolean primitive value from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_bool"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_bool(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_bool"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_bool(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_bool(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_count(_:)": {
      "abstract": [
        {
          "text": "Returns the count of values in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_count(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_count"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_count(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_count(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_data(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets a pointer to the raw bytes of a data object from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_data"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_data(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_data"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_data(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_data(_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_date(_:_:)": {
      "abstract": [
        {
          "text": "Gets a date interval from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_date"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_date(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_date"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_date(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_date(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_dictionary(_:_:)": {
      "abstract": [
        {
          "text": "Returns the dictionary at the specified index in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_dictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_dictionary(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_dictionary"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_dictionary(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_dictionary(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_double(_:_:)": {
      "abstract": [
        {
          "text": "Gets a double-precision floating point primitive value from an array directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_double(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_double"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_double(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_double(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_get_value(_:_:)": {
      "abstract": [
        {
          "text": "Returns the value at the specified index in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_get_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_get_value(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_get_value"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_get_value(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_get_value(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_array_set_value(_:_:_:)": {
      "abstract": [
        {
          "text": "Inserts the specified object into the array at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_array_set_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_array_set_value(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_array_set_value"
        }
      ],
      "role": "symbol",
      "title": "xpc_array_set_value(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_array_set_value(_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Array-objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_array_create(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_create_empty()",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_create_connection(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_set_value(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_value(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_append_value(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_count(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_apply(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_dup_fd(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_array(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_bool(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_data(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_date(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_dictionary(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_array_get_double(_:_:)"
      ],
      "title": "Array objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-array",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCArray/init()",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/init(_:)",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/copy(into:)"
      ],
      "title": "Creating an array"
    },
    {
      "anchor": "Inspecting-an-array",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCArray/isEmpty",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/count"
      ],
      "title": "Inspecting an array"
    },
    {
      "anchor": "Accessing-elements",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-1s7qq",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-6c9gh",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-i6v5",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-56wjj",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-8wubg",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-9x9ho",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:)-2f94n",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-3ae6x",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-9ukjj",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-1bilh",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-931lh",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-3tgp4",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-2hql9",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:)-6grs4",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:default:)-2bn95",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/subscript(_:as:default:)-3k2qm",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/withUnsafeUnderlyingArray(_:)"
      ],
      "title": "Accessing elements"
    },
    {
      "anchor": "Iterating-over-an-arrays-elements",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCArray/forEach(_:)-6obs3",
        "doc://com.apple.xpc/documentation/XPC/XPCArray/forEach(_:)-2ib8a"
      ],
      "title": "Iterating over an array’s elements"
    },
    {
      "anchor": "Transforming-an-array",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCArray/map(_:)"
      ],
      "title": "Transforming an array"
    },
    {
      "anchor": "Supporting-types",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCArray/IndexValuePair"
      ],
      "title": "Supporting types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create_empty()/title",
          "value": "xpc_array_create_empty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create_empty()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_create_empty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_dictionary(_:_:)/title",
          "value": "xpc_array_get_dictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_dictionary(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_dictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_dup_fd(_:_:)/title",
          "value": "xpc_array_dup_fd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_dup_fd(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_dup_fd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_value(_:_:)/title",
          "value": "xpc_array_get_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_value(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create_connection(_:_:)/title",
          "value": "xpc_array_create_connection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create_connection(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_create_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create(_:_:)/title",
          "value": "xpc_array_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_create(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_date(_:_:)/title",
          "value": "xpc_array_get_date"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_date(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_date"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_count(_:)/title",
          "value": "xpc_array_get_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_count(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_bool(_:_:)/title",
          "value": "xpc_array_get_bool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_bool(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_bool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_append_value(_:_:)/title",
          "value": "xpc_array_append_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_append_value(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_append_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_array(_:_:)/title",
          "value": "xpc_array_get_array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_array(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_data(_:_:_:)/title",
          "value": "xpc_array_get_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_data(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_double(_:_:)/title",
          "value": "xpc_array_get_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_get_double(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_get_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_apply(_:_:)/title",
          "value": "xpc_array_apply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_apply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_apply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_set_value(_:_:_:)/title",
          "value": "xpc_array_set_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_array_set_value(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_array_set_value"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpcarray"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
