{
  "abstract": [
    {
      "text": "A type that contains key-value pairs, notably used as the container of messages between a client and listener.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/XPCDictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:3XPC13XPCDictionaryV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XPCDictionary"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XPCDictionary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "XPCDictionary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPCDictionary"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary": {
      "abstract": [
        {
          "text": "A type that contains key-value pairs, notably used as the container of messages between a client and listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCDictionary"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCDictionary"
        }
      ],
      "role": "symbol",
      "title": "XPCDictionary",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/KeyValuePair": {
      "abstract": [
        {
          "text": "A type that contains a dictionary’s key-value pair.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KeyValuePair"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/KeyValuePair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KeyValuePair"
        }
      ],
      "role": "symbol",
      "title": "XPCDictionary.KeyValuePair",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/keyvaluepair"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/copy(into:)": {
      "abstract": [
        {
          "text": "Copies the keys and values of the dictionary to a different dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "into"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/copy(into:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "copy(into:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/copy(into:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/count": {
      "abstract": [
        {
          "text": "The number of key-value pairs in the dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/count",
      "kind": "symbol",
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/count"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/forEach(_:)-6riqn": {
      "abstract": [
        {
          "text": "Calls the given closure with each key and value in the dictionary in the same order as a for-in loop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forEach"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/forEach(_:)-6riqn",
      "kind": "symbol",
      "role": "symbol",
      "title": "forEach(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/foreach(_:)-6riqn"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/forEach(_:)-9hufx": {
      "abstract": [
        {
          "text": "Calls the given closure with each element in the dictionary in the same order as a for-in loop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forEach"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV12KeyValuePaira",
          "text": "KeyValuePair"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/forEach(_:)-9hufx",
      "kind": "symbol",
      "role": "symbol",
      "title": "forEach(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/foreach(_:)-9hufx"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/init()": {
      "abstract": [
        {
          "text": "Creates an empty dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/init()"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/init(_:)": {
      "abstract": [
        {
          "text": "Creates a dictionary using the keys and values in the specified object parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/init(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/isEmpty": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the dictionary is empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/isEmpty",
      "kind": "symbol",
      "role": "symbol",
      "title": "isEmpty",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/isempty"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/keys": {
      "abstract": [
        {
          "text": "A collection containing just the keys of the dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keys"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/keys",
      "kind": "symbol",
      "role": "symbol",
      "title": "keys",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/keys"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/map(_:)": {
      "abstract": [
        {
          "text": "Returns an array containing the results of mapping the given closure over the sequence’s elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "map"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "ReturnType"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV12KeyValuePaira",
          "text": "KeyValuePair"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "ReturnType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "text": "ReturnType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/map(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "map(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/map(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/removeValue(forKey:)": {
      "abstract": [
        {
          "text": "Removes the given key and its associated value from the dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/removeValue(forKey:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeValue(forKey:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/removevalue(forkey:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/reply(_:)": {
      "abstract": [
        {
          "text": "Sends a reply to the originator of the dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/reply(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "reply(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/reply(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-3i01t": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as a signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-3i01t",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:)-3i01t"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-4hbmg": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as an XPC dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-4hbmg",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:)-4hbmg"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-4j21u": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as an XPC object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-4j21u",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:)-4j21u"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-4vrsa": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as an unsigned integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-4vrsa",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:)-4vrsa"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-80fs2": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-80fs2",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:)-80fs2"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-8gyze": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as a floating point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-8gyze",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:)-8gyze"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-gas6": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as a Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-gas6",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:)-gas6"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-119cl": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as an integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-119cl",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:as:)-119cl"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-18db5": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as a Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-18db5",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:as:)-18db5"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-1mm7n": {
      "abstract": [
        {
          "text": "Reads the value associated with the given key as an XPC dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-1mm7n",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:as:)-1mm7n"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-3mzgc": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as a floating point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-3mzgc",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:as:)-3mzgc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-4zxc8": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-4zxc8",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:as:)-4zxc8"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-5y39v": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as an XPC object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-5y39v",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:as:)-5y39v"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-qjxa": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as an XPC object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_type_t",
          "text": "xpc_type_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-qjxa",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:as:)-qjxa"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:default:)-4ssx3": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key converted to the specified type, falling back to the given default value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ".Type, "
        },
        {
          "kind": "externalParam",
          "text": "default"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:default:)-4ssx3",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:default:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:as:default:)-4ssx3"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:default:)-5ufgs": {
      "abstract": [
        {
          "text": "Reads and writes the value associated with the given key as a Boolean value, falling back to the given default value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ".Type, "
        },
        {
          "kind": "externalParam",
          "text": "default"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:default:)-5ufgs",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:as:default:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/subscript(_:as:default:)-5ufgs"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/values": {
      "abstract": [
        {
          "text": "A collection containing just the values of the dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "values"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/values",
      "kind": "symbol",
      "role": "symbol",
      "title": "values",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/values"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCDictionary/withUnsafeUnderlyingDictionary(_:)": {
      "abstract": [
        {
          "text": "Calls a closure with an unsafe reference to the dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withUnsafeUnderlyingDictionary"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "ReturnType"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "ReturnType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "ReturnType"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCDictionary/withUnsafeUnderlyingDictionary(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "withUnsafeUnderlyingDictionary(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcdictionary/withunsafeunderlyingdictionary(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_apply(_:_:)": {
      "abstract": [
        {
          "text": "Invokes the specified block for every key-value pair in the dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_apply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_apply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_apply"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_apply(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_apply(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents a dictionary of XPC objects keyed to C-strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_create"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_create(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_create(_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create_connection(_:_:)": {
      "abstract": [
        {
          "text": "Creates a connection from a dictionary directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_create_connection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create_connection(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_create_connection"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_create_connection(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_create_connection(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create_empty()": {
      "abstract": [
        {
          "text": "Creates an XPC object that represents a dictionary of XPC objects keyed to C-strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_create_empty"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create_empty()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_create_empty"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_create_empty()",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_create_empty()"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create_reply(_:)": {
      "abstract": [
        {
          "text": "Creates a dictionary that is in reply to the specified dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_create_reply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create_reply(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_create_reply"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_create_reply(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_create_reply(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_dup_fd(_:_:)": {
      "abstract": [
        {
          "text": "Creates a file descriptor from a dictionary directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_dup_fd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_dup_fd(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_dup_fd"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_dup_fd(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_dup_fd(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_array(_:_:)": {
      "abstract": [
        {
          "text": "Returns the array value for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_array"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_array(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_array"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_get_array(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_get_array(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_bool(_:_:)": {
      "abstract": [
        {
          "text": "Gets a Boolean primitive value from a dictionary directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_bool"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_bool(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_bool"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_get_bool(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_get_bool(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_count(_:)": {
      "abstract": [
        {
          "text": "Returns the number of values in the dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_count(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_count"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_get_count(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_get_count(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_data(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets a raw data value from a dictionary directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_data"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_data(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_data"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_get_data(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_get_data(_:_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_date(_:_:)": {
      "abstract": [
        {
          "text": "Gets a date value from a dictionary directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_date"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_date(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_date"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_get_date(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_get_date(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_dictionary(_:_:)": {
      "abstract": [
        {
          "text": "Returns the dictionary value for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_dictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_dictionary(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_dictionary"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_get_dictionary(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_get_dictionary(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_double(_:_:)": {
      "abstract": [
        {
          "text": "Gets a double-precision floating point primitive value from a dictionary directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_double(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_double"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_get_double(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_get_double(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_value(_:_:)": {
      "abstract": [
        {
          "text": "Returns the value for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_value(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_get_value"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_get_value(_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_get_value(_:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_set_value(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the value for the specified key to the specified object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_dictionary_set_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_set_value(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_dictionary_set_value"
        }
      ],
      "role": "symbol",
      "title": "xpc_dictionary_set_value(_:_:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpc_dictionary_set_value(_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Dictionary-objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create_empty()",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create_connection(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_create_reply(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_set_value(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_count(_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_value(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_apply(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_dup_fd(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_array(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_bool(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_data(_:_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_date(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_dictionary(_:_:)",
        "doc://com.apple.xpc/documentation/XPC/xpc_dictionary_get_double(_:_:)"
      ],
      "title": "Dictionary objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-dictionary",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/init()",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/init(_:)",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/copy(into:)"
      ],
      "title": "Creating a dictionary"
    },
    {
      "anchor": "Replying-to-client-messages",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/reply(_:)"
      ],
      "title": "Replying to client messages"
    },
    {
      "anchor": "Inspecting-a-dictionary",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/isEmpty",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/count"
      ],
      "title": "Inspecting a dictionary"
    },
    {
      "anchor": "Accessing-keys-and-values",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/keys",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/values",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-4hbmg",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-80fs2",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-gas6",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-4j21u",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-8gyze",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-4vrsa",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:)-3i01t",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-1mm7n",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-4zxc8",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-18db5",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-5y39v",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-qjxa",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-3mzgc",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:)-119cl",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:default:)-5ufgs",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/subscript(_:as:default:)-4ssx3",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/withUnsafeUnderlyingDictionary(_:)"
      ],
      "title": "Accessing keys and values"
    },
    {
      "anchor": "Removing-keys-and-values",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/removeValue(forKey:)"
      ],
      "title": "Removing keys and values"
    },
    {
      "anchor": "Supporting-types",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/KeyValuePair"
      ],
      "title": "Supporting types"
    },
    {
      "anchor": "Iterating-over-keys-and-values",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/forEach(_:)-9hufx",
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/forEach(_:)-6riqn"
      ],
      "title": "Iterating over keys and values"
    },
    {
      "anchor": "Transforming-a-dictionary",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCDictionary/map(_:)"
      ],
      "title": "Transforming a dictionary"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_create_reply(_:)/title",
          "value": "xpc_dictionary_create_reply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_create_reply(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_create_reply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_create_empty()/title",
          "value": "xpc_dictionary_create_empty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_create_empty()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_create_empty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_double(_:_:)/title",
          "value": "xpc_dictionary_get_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_double(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_get_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_bool(_:_:)/title",
          "value": "xpc_dictionary_get_bool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_bool(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_get_bool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_set_value(_:_:_:)/title",
          "value": "xpc_dictionary_set_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_set_value(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_set_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_date(_:_:)/title",
          "value": "xpc_dictionary_get_date"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_date(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_get_date"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_dup_fd(_:_:)/title",
          "value": "xpc_dictionary_dup_fd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_dup_fd(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_dup_fd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_apply(_:_:)/title",
          "value": "xpc_dictionary_apply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_apply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_apply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_count(_:)/title",
          "value": "xpc_dictionary_get_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_count(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_get_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_array(_:_:)/title",
          "value": "xpc_dictionary_get_array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_array(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_get_array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_create_connection(_:_:)/title",
          "value": "xpc_dictionary_create_connection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_create_connection(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_create_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_value(_:_:)/title",
          "value": "xpc_dictionary_get_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_value(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_get_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_create(_:_:_:)/title",
          "value": "xpc_dictionary_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_create(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_data(_:_:_:)/title",
          "value": "xpc_dictionary_get_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_data(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_get_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_dictionary(_:_:)/title",
          "value": "xpc_dictionary_get_dictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_dictionary_get_dictionary(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_dictionary_get_dictionary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpcdictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
