{
  "abstract": [
    {
      "text": "A type that performs tasks for clients across process boundaries.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/XPCListener"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:3XPC11XPCListenerC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XPCListener"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XPCListener"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XPCListener"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPCListener"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.xpc/documentation/XPC/creating-xpc-services"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To implement an XPC service, create a listener and respond to incoming session requests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCListener": {
      "abstract": [
        {
          "text": "A type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "role": "symbol",
      "title": "XPCListener",
      "type": "topic",
      "url": "/documentation/xpc/xpclistener"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCListener/IncomingSessionRequest": {
      "abstract": [
        {
          "text": "A session request from a client that you accept or reject.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IncomingSessionRequest"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCListener/IncomingSessionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IncomingSessionRequest"
        }
      ],
      "role": "symbol",
      "title": "XPCListener.IncomingSessionRequest",
      "type": "topic",
      "url": "/documentation/xpc/xpclistener/incomingsessionrequest"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCListener/InitializationOptions": {
      "abstract": [
        {
          "text": "Options that control the listener’s configuration, such as if it’s inactive at creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InitializationOptions"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCListener/InitializationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InitializationOptions"
        }
      ],
      "role": "symbol",
      "title": "XPCListener.InitializationOptions",
      "type": "topic",
      "url": "/documentation/xpc/xpclistener/initializationoptions"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCListener/activate()": {
      "abstract": [
        {
          "text": "Activates an inactive listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCListener/activate()",
      "kind": "symbol",
      "role": "symbol",
      "title": "activate()",
      "type": "topic",
      "url": "/documentation/xpc/xpclistener/activate()"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCListener/cancel()": {
      "abstract": [
        {
          "text": "Cancels a listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCListener/cancel()",
      "kind": "symbol",
      "role": "symbol",
      "title": "cancel()",
      "type": "topic",
      "url": "/documentation/xpc/xpclistener/cancel()"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCListener/init(service:targetQueue:options:incomingSessionHandler:)": {
      "abstract": [
        {
          "text": "Creates the server side of an XPC service using the specified service name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "service"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC11XPCListenerC",
          "text": "XPCListener"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC11XPCListenerC21InitializationOptionsV",
          "text": "InitializationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "incomingSessionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC11XPCListenerC",
          "text": "XPCListener"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC11XPCListenerC22IncomingSessionRequestC",
          "text": "IncomingSessionRequest"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC11XPCListenerC",
          "text": "XPCListener"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC11XPCListenerC22IncomingSessionRequestC",
          "text": "IncomingSessionRequest"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC11XPCListenerC22IncomingSessionRequestC8DecisionV",
          "text": "Decision"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCListener/init(service:targetQueue:options:incomingSessionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(service:targetQueue:options:incomingSessionHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpclistener/init(service:targetqueue:options:incomingsessionhandler:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCPeerHandler": {
      "abstract": [
        {
          "text": "A type that handles incoming messages from a client and session cancellation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCPeerHandler"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCPeerHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCPeerHandler"
        }
      ],
      "role": "symbol",
      "title": "XPCPeerHandler",
      "type": "topic",
      "url": "/documentation/xpc/xpcpeerhandler"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage": {
      "abstract": [
        {
          "text": "A type that represents a message sent between a session and a listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCReceivedMessage"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCReceivedMessage"
        }
      ],
      "role": "symbol",
      "title": "XPCReceivedMessage",
      "type": "topic",
      "url": "/documentation/xpc/xpcreceivedmessage"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession": {
      "abstract": [
        {
          "text": "A type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "role": "symbol",
      "title": "XPCSession",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession"
    },
    "doc://com.apple.xpc/documentation/XPC/creating-xpc-services": {
      "abstract": [
        {
          "text": "Configure a listener, establish a client session, and exchange messages between processes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
      "kind": "article",
      "role": "article",
      "title": "Creating XPC services",
      "type": "topic",
      "url": "/documentation/xpc/creating-xpc-services"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_t": {
      "abstract": [
        {
          "text": "A C type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_listener_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0": {
      "abstract": [
        {
          "text": "A C type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_t-10if0"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interprocess-communication",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
        "doc://com.apple.xpc/documentation/XPC/XPCSession",
        "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage",
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_t",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0"
      ],
      "title": "Interprocess communication"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-listener",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCListener/init(service:targetQueue:options:incomingSessionHandler:)",
        "doc://com.apple.xpc/documentation/XPC/XPCListener/InitializationOptions",
        "doc://com.apple.xpc/documentation/XPC/XPCListener/IncomingSessionRequest"
      ],
      "title": "Creating a listener"
    },
    {
      "anchor": "Managing-the-life-cycle",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCListener/activate()",
        "doc://com.apple.xpc/documentation/XPC/XPCListener/cancel()"
      ],
      "title": "Managing the life cycle"
    },
    {
      "anchor": "Handling-incoming-messages",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCPeerHandler"
      ],
      "title": "Handling incoming messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/title",
          "value": "xpc_session_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/title",
          "value": "xpc_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpclistener"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
