{
  "abstract": [
    {
      "text": "A type that represents a message sent between a session and a listener.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:3XPC18XPCReceivedMessageV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XPCReceivedMessage"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XPCReceivedMessage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "XPCReceivedMessage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPCReceivedMessage"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.xpc/documentation/XPC/creating-xpc-services"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCListener": {
      "abstract": [
        {
          "text": "A type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "role": "symbol",
      "title": "XPCListener",
      "type": "topic",
      "url": "/documentation/xpc/xpclistener"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage": {
      "abstract": [
        {
          "text": "A type that represents a message sent between a session and a listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCReceivedMessage"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCReceivedMessage"
        }
      ],
      "role": "symbol",
      "title": "XPCReceivedMessage",
      "type": "topic",
      "url": "/documentation/xpc/xpcreceivedmessage"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/decode(as:)": {
      "abstract": [
        {
          "text": "Decodes a message as the given type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decode"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ".Type) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/decode(as:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "decode(as:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcreceivedmessage/decode(as:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/expectsReply": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the client that sent the message expects a reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expectsReply"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/expectsReply",
      "kind": "symbol",
      "role": "symbol",
      "title": "expectsReply",
      "type": "topic",
      "url": "/documentation/xpc/xpcreceivedmessage/expectsreply"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/handoffReply(to:_:)": {
      "abstract": [
        {
          "text": "Informs the system when message processing and response continues in a separate dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handoffReply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": ", () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SE",
          "text": "Encodable"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/handoffReply(to:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "handoffReply(to:_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcreceivedmessage/handoffreply(to:_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/isSync": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if this message is from a synchronous request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/isSync",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSync",
      "type": "topic",
      "url": "/documentation/xpc/xpcreceivedmessage/issync"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/reply(_:)": {
      "abstract": [
        {
          "text": "Sends a reply to the originator of the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reply"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/reply(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "reply(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcreceivedmessage/reply(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession": {
      "abstract": [
        {
          "text": "A type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "role": "symbol",
      "title": "XPCSession",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession"
    },
    "doc://com.apple.xpc/documentation/XPC/creating-xpc-services": {
      "abstract": [
        {
          "text": "Configure a listener, establish a client session, and exchange messages between processes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
      "kind": "article",
      "role": "article",
      "title": "Creating XPC services",
      "type": "topic",
      "url": "/documentation/xpc/creating-xpc-services"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_t": {
      "abstract": [
        {
          "text": "A C type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_listener_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0": {
      "abstract": [
        {
          "text": "A C type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_t-10if0"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interprocess-communication",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
        "doc://com.apple.xpc/documentation/XPC/XPCListener",
        "doc://com.apple.xpc/documentation/XPC/XPCSession",
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_t",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0"
      ],
      "title": "Interprocess communication"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-message-content",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/decode(as:)",
        "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/isSync"
      ],
      "title": "Accessing message content"
    },
    {
      "anchor": "Replying-to-messages",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/expectsReply",
        "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/reply(_:)",
        "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage/handoffReply(to:_:)"
      ],
      "title": "Replying to messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/title",
          "value": "xpc_session_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/title",
          "value": "xpc_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpcreceivedmessage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
