{
  "abstract": [
    {
      "text": "A type that sends messages to a server process.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xpc/documentation/XPC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xpc/documentation/XPC/XPCSession"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:3XPC10XPCSessionC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XPCSession"
      }
    ],
    "modules": [
      {
        "name": "XPC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XPCSession"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XPCSession"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XPCSession"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "XPC sessions are stateful connections you use to send structured messages to a separate process. Once established, a session remains active until one side of the connection cancels it, at which point the system invalidates the connection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xpc/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/xpc"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCListener": {
      "abstract": [
        {
          "text": "A type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "role": "symbol",
      "title": "XPCListener",
      "type": "topic",
      "url": "/documentation/xpc/xpclistener"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage": {
      "abstract": [
        {
          "text": "A type that represents a message sent between a session and a listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCReceivedMessage"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCReceivedMessage"
        }
      ],
      "role": "symbol",
      "title": "XPCReceivedMessage",
      "type": "topic",
      "url": "/documentation/xpc/xpcreceivedmessage"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession": {
      "abstract": [
        {
          "text": "A type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "role": "symbol",
      "title": "XPCSession",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/InitializationOptions": {
      "abstract": [
        {
          "text": "Options that control the session’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InitializationOptions"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/InitializationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InitializationOptions"
        }
      ],
      "role": "symbol",
      "title": "XPCSession.InitializationOptions",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/initializationoptions"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/activate()": {
      "abstract": [
        {
          "text": "Activates a session so you can send messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/activate()",
      "kind": "symbol",
      "role": "symbol",
      "title": "activate()",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/activate()"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/cancel(reason:)": {
      "abstract": [
        {
          "text": "Cancels a session, discarding any unsent messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/cancel(reason:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "cancel(reason:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/cancel(reason:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:cancellationHandler:)": {
      "abstract": [
        {
          "text": "Establishes a connection to a launch agent or launch daemon with the name you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "machService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC",
          "text": "XPCSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC21InitializationOptionsV",
          "text": "InitializationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cancellationHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:cancellationHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(machService:targetQueue:options:cancellationHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/init(machservice:targetqueue:options:cancellationhandler:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-2xuyi": {
      "abstract": [
        {
          "text": "Establishes a connection to a launch agent or launch daemon with the name and received message handler you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "machService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC",
          "text": "XPCSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC21InitializationOptionsV",
          "text": "InitializationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "incomingMessageHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC18XPCReceivedMessageV",
          "text": "XPCReceivedMessage"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SE",
          "text": "Encodable"
        },
        {
          "kind": "text",
          "text": ")?)?, "
        },
        {
          "kind": "externalParam",
          "text": "cancellationHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-2xuyi",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/init(machservice:targetqueue:options:incomingmessagehandler:cancellationhandler:)-2xuyi"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-6jz7y": {
      "abstract": [
        {
          "text": "Establishes a connection to a launch agent or launch daemon with the name and dictionary message handler you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "machService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC",
          "text": "XPCSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC21InitializationOptionsV",
          "text": "InitializationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "incomingMessageHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": "?)?, "
        },
        {
          "kind": "externalParam",
          "text": "cancellationHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-6jz7y",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/init(machservice:targetqueue:options:incomingmessagehandler:cancellationhandler:)-6jz7y"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-l3rz": {
      "abstract": [
        {
          "text": "Establishes a connection to a launch agent or launch daemon with the name and decodable message handler you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "machService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC",
          "text": "XPCSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC21InitializationOptionsV",
          "text": "InitializationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "incomingMessageHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SE",
          "text": "Encodable"
        },
        {
          "kind": "text",
          "text": ")?)?, "
        },
        {
          "kind": "externalParam",
          "text": "cancellationHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-l3rz",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/init(machservice:targetqueue:options:incomingmessagehandler:cancellationhandler:)-l3rz"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:cancellationHandler:)": {
      "abstract": [
        {
          "text": "Establishes a connection to an XPC service with the name you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "xpcService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC",
          "text": "XPCSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC21InitializationOptionsV",
          "text": "InitializationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cancellationHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:cancellationHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(xpcService:targetQueue:options:cancellationHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/init(xpcservice:targetqueue:options:cancellationhandler:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-407h2": {
      "abstract": [
        {
          "text": "Establishes a connection to an XPC service with the name and decodable message handler you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "xpcService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC",
          "text": "XPCSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC21InitializationOptionsV",
          "text": "InitializationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "incomingMessageHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SE",
          "text": "Encodable"
        },
        {
          "kind": "text",
          "text": ")?)?, "
        },
        {
          "kind": "externalParam",
          "text": "cancellationHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-407h2",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/init(xpcservice:targetqueue:options:incomingmessagehandler:cancellationhandler:)-407h2"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-9f4u0": {
      "abstract": [
        {
          "text": "Establishes a connection to an XPC service with the name and received message handler you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "xpcService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC",
          "text": "XPCSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC21InitializationOptionsV",
          "text": "InitializationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "incomingMessageHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC18XPCReceivedMessageV",
          "text": "XPCReceivedMessage"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SE",
          "text": "Encodable"
        },
        {
          "kind": "text",
          "text": ")?)?, "
        },
        {
          "kind": "externalParam",
          "text": "cancellationHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-9f4u0",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/init(xpcservice:targetqueue:options:incomingmessagehandler:cancellationhandler:)-9f4u0"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-bel3": {
      "abstract": [
        {
          "text": "Establishes a connection to an XPC service with the name and dictionary message handler you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "xpcService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC",
          "text": "XPCSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC10XPCSessionC21InitializationOptionsV",
          "text": "InitializationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "incomingMessageHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": "?)?, "
        },
        {
          "kind": "externalParam",
          "text": "cancellationHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-bel3",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/init(xpcservice:targetqueue:options:incomingmessagehandler:cancellationhandler:)-bel3"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/send(_:)": {
      "abstract": [
        {
          "text": "Sends an encodable message over the session to the destination service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/send(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "send(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/send(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/send(_:replyHandler:)-3wjln": {
      "abstract": [
        {
          "text": "Sends an encodable message over the session to the destination service, using the closure you specify to handle a reply and rich error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC18XPCReceivedMessageV",
          "text": "XPCReceivedMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/send(_:replyHandler:)-3wjln",
      "kind": "symbol",
      "role": "symbol",
      "title": "send(_:replyHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/send(_:replyhandler:)-3wjln"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/send(_:replyHandler:)-9an0u": {
      "abstract": [
        {
          "text": "Sends an encodable message over the session to the destination service, using the closure you specify to handle a reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Reply"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Reply"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/send(_:replyHandler:)-9an0u",
      "kind": "symbol",
      "role": "symbol",
      "title": "send(_:replyHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/send(_:replyhandler:)-9an0u"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/send(message:)": {
      "abstract": [
        {
          "text": "Sends a dictionary message over the session to the destination service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "message"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/send(message:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "send(message:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/send(message:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/send(message:replyHandler:)": {
      "abstract": [
        {
          "text": "Sends a message asynchronously over the session to the destination service, calling a closure after receiving a reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "message"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/send(message:replyHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "send(message:replyHandler:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/send(message:replyhandler:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/sendSync(_:)-88u0s": {
      "abstract": [
        {
          "text": "Sends an encodable message over the session to the destination service, blocking the caller until receiving an encodable reply message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendSync"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Reply"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Reply"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/sendSync(_:)-88u0s",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendSync(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/sendsync(_:)-88u0s"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/sendSync(_:)-8a284": {
      "abstract": [
        {
          "text": "Sends an encodable message over the session to the destination service, blocking the caller until receiving a reply message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendSync"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC18XPCReceivedMessageV",
          "text": "XPCReceivedMessage"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/sendSync(_:)-8a284",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendSync(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/sendsync(_:)-8a284"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/sendSync(message:)": {
      "abstract": [
        {
          "text": "Sends a dictionary message over the session to the destination service, blocking the caller until receiving a reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendSync"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "message"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/sendSync(message:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendSync(message:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/sendsync(message:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/setCancellationHandler(_:)": {
      "abstract": [
        {
          "text": "Sets a closure the session calls when it’s canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCancellationHandler"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC12XPCRichErrorV",
          "text": "XPCRichError"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/setCancellationHandler(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setCancellationHandler(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/setcancellationhandler(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/setIncomingMessageHandler(_:)-2ukdh": {
      "abstract": [
        {
          "text": "Sets a closure to receive incoming decodable messages for a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIncomingMessageHandler"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SE",
          "text": "Encodable"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/setIncomingMessageHandler(_:)-2ukdh",
      "kind": "symbol",
      "role": "symbol",
      "title": "setIncomingMessageHandler(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/setincomingmessagehandler(_:)-2ukdh"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/setIncomingMessageHandler(_:)-5lu26": {
      "abstract": [
        {
          "text": "Sets a closure to receive incoming received messages for a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIncomingMessageHandler"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC18XPCReceivedMessageV",
          "text": "XPCReceivedMessage"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SE",
          "text": "Encodable"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/setIncomingMessageHandler(_:)-5lu26",
      "kind": "symbol",
      "role": "symbol",
      "title": "setIncomingMessageHandler(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/setincomingmessagehandler(_:)-5lu26"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/setIncomingMessageHandler(_:)-75ou9": {
      "abstract": [
        {
          "text": "Sets a closure to receive incoming dictionary messages for a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIncomingMessageHandler"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:3XPC13XPCDictionaryV",
          "text": "XPCDictionary"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/setIncomingMessageHandler(_:)-75ou9",
      "kind": "symbol",
      "role": "symbol",
      "title": "setIncomingMessageHandler(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/setincomingmessagehandler(_:)-75ou9"
    },
    "doc://com.apple.xpc/documentation/XPC/XPCSession/setTargetQueue(_:)": {
      "abstract": [
        {
          "text": "Sets the target dispatch queue on an inactive session for processing messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTargetQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/XPCSession/setTargetQueue(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTargetQueue(_:)",
      "type": "topic",
      "url": "/documentation/xpc/xpcsession/settargetqueue(_:)"
    },
    "doc://com.apple.xpc/documentation/XPC/creating-xpc-services": {
      "abstract": [
        {
          "text": "Configure a listener, establish a client session, and exchange messages between processes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
      "kind": "article",
      "role": "article",
      "title": "Creating XPC services",
      "type": "topic",
      "url": "/documentation/xpc/creating-xpc-services"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_listener_t": {
      "abstract": [
        {
          "text": "A C type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_listener_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_listener_t"
    },
    "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0": {
      "abstract": [
        {
          "text": "A C type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "identifier": "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        }
      ],
      "role": "symbol",
      "title": "xpc_session_t",
      "type": "topic",
      "url": "/documentation/xpc/xpc_session_t-10if0"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interprocess-communication",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/creating-xpc-services",
        "doc://com.apple.xpc/documentation/XPC/XPCListener",
        "doc://com.apple.xpc/documentation/XPC/XPCReceivedMessage",
        "doc://com.apple.xpc/documentation/XPC/xpc_listener_t",
        "doc://com.apple.xpc/documentation/XPC/xpc_session_t-10if0"
      ],
      "title": "Interprocess communication"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-session",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-407h2",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-9f4u0",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-bel3",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/init(xpcService:targetQueue:options:cancellationHandler:)",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-l3rz",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-2xuyi",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:incomingMessageHandler:cancellationHandler:)-6jz7y",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/init(machService:targetQueue:options:cancellationHandler:)",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/InitializationOptions",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/setTargetQueue(_:)"
      ],
      "title": "Creating a session"
    },
    {
      "anchor": "Managing-the-life-cycle",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCSession/activate()",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/setIncomingMessageHandler(_:)-2ukdh",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/setIncomingMessageHandler(_:)-5lu26",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/setIncomingMessageHandler(_:)-75ou9",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/cancel(reason:)",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/setCancellationHandler(_:)"
      ],
      "title": "Managing the life cycle"
    },
    {
      "anchor": "Sending-messages",
      "identifiers": [
        "doc://com.apple.xpc/documentation/XPC/XPCSession/send(_:)",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/send(_:replyHandler:)-3wjln",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/send(_:replyHandler:)-9an0u",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/send(message:)",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/send(message:replyHandler:)",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/sendSync(_:)-8a284",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/sendSync(_:)-88u0s",
        "doc://com.apple.xpc/documentation/XPC/XPCSession/sendSync(message:)"
      ],
      "title": "Sending messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/title",
          "value": "xpc_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/title",
          "value": "xpc_session_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xpc~1documentation~1XPC~1xpc_session_t-10if0/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xpc/xpcsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
