{
  "abstract": [
    {
      "text": "Creates an object that describes the camera in use for tracking.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.DockKit/documentation/DockKit",
        "doc://com.apple.DockKit/documentation/DockKit/DockAccessory",
        "doc://com.apple.DockKit/documentation/DockKit/DockAccessory/CameraInformation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.DockKit/documentation/DockKit/DockAccessory/CameraInformation/init(captureDevice:cameraPosition:orientation:cameraIntrinsics:referenceDimensions:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:7DockKit0A9AccessoryC17CameraInformationV13captureDevice14cameraPosition11orientation0H10Intrinsics19referenceDimensionsAESo09AVCaptureG4Typea_So0ngI0VAC0D11OrientationOSo13simd_float3x3aSgSo6CGSizeVSgtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "captureDevice"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
        "text": "AVCaptureDevice"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVCaptureDeviceType",
        "text": "DeviceType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "cameraPosition"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
        "text": "AVCaptureDevice"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVCaptureDevicePosition",
        "text": "Position"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "orientation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7DockKit0A9AccessoryC",
        "text": "DockAccessory"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7DockKit0A9AccessoryC17CameraOrientationO",
        "text": "CameraOrientation"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "cameraIntrinsics"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@matrix_float3x3",
        "text": "matrix_float3x3"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "referenceDimensions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGSize",
        "text": "CGSize"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "DockKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.1",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(captureDevice:cameraPosition:orientation:cameraIntrinsics:referenceDimensions:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "captureDevice"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AVCaptureDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
              "text": "AVCaptureDevice"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@AVCaptureDeviceType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVCaptureDeviceType",
              "text": "DeviceType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "cameraPosition"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AVCaptureDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
              "text": "AVCaptureDevice"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@AVCaptureDevicePosition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVCaptureDevicePosition",
              "text": "Position"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "orientation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.DockKit/documentation/DockKit/DockAccessory",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7DockKit0A9AccessoryC",
              "text": "DockAccessory"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.DockKit/documentation/DockKit/DockAccessory/CameraOrientation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7DockKit0A9AccessoryC17CameraOrientationO",
              "text": "CameraOrientation"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "cameraIntrinsics"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@matrix_float3x3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@matrix_float3x3",
              "text": "matrix_float3x3"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "referenceDimensions"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGSize",
              "text": "CGSize"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The capture device generating the video.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "captureDevice"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The physical position of the capture device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cameraPosition"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The orientation of the capture device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "orientation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A matrix that represents the characteristics of the lens.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cameraIntrinsics"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The size of the video frame.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "referenceDimensions"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.DockKit/documentation/DockKit": {
      "abstract": [
        {
          "text": "Interact with accessories that track subjects on camera as they move around.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DockKit/documentation/DockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "DockKit",
      "type": "topic",
      "url": "/documentation/dockkit"
    },
    "doc://com.apple.DockKit/documentation/DockKit/DockAccessory": {
      "abstract": [
        {
          "text": "Obtain accessory information and control tracking behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DockAccessory"
        }
      ],
      "identifier": "doc://com.apple.DockKit/documentation/DockKit/DockAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DockAccessory"
        }
      ],
      "role": "symbol",
      "title": "DockAccessory",
      "type": "topic",
      "url": "/documentation/dockkit/dockaccessory"
    },
    "doc://com.apple.DockKit/documentation/DockKit/DockAccessory/CameraInformation": {
      "abstract": [
        {
          "text": "A collection of tracking information about the camera currently in use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CameraInformation"
        }
      ],
      "identifier": "doc://com.apple.DockKit/documentation/DockKit/DockAccessory/CameraInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CameraInformation"
        }
      ],
      "role": "symbol",
      "title": "DockAccessory.CameraInformation",
      "type": "topic",
      "url": "/documentation/dockkit/dockaccessory/camerainformation"
    },
    "doc://com.apple.DockKit/documentation/DockKit/DockAccessory/CameraInformation/init(captureDevice:cameraPosition:orientation:cameraIntrinsics:referenceDimensions:)": {
      "abstract": [
        {
          "text": "Creates an object that describes the camera in use for tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "captureDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureDeviceType",
          "text": "DeviceType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cameraPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureDevicePosition",
          "text": "Position"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7DockKit0A9AccessoryC",
          "text": "DockAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7DockKit0A9AccessoryC17CameraOrientationO",
          "text": "CameraOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cameraIntrinsics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@matrix_float3x3",
          "text": "matrix_float3x3"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "referenceDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.DockKit/documentation/DockKit/DockAccessory/CameraInformation/init(captureDevice:cameraPosition:orientation:cameraIntrinsics:referenceDimensions:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(captureDevice:cameraPosition:orientation:cameraIntrinsics:referenceDimensions:)",
      "type": "topic",
      "url": "/documentation/dockkit/dockaccessory/camerainformation/init(capturedevice:cameraposition:orientation:cameraintrinsics:referencedimensions:)"
    },
    "doc://com.apple.DockKit/documentation/DockKit/DockAccessory/CameraOrientation": {
      "abstract": [
        {
          "text": "The set of camera orientations used to extract coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CameraOrientation"
        }
      ],
      "identifier": "doc://com.apple.DockKit/documentation/DockKit/DockAccessory/CameraOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CameraOrientation"
        }
      ],
      "role": "symbol",
      "title": "DockAccessory.CameraOrientation",
      "type": "topic",
      "url": "/documentation/dockkit/dockaccessory/cameraorientation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@AVCaptureDevicePosition": {
      "abstract": [
        {
          "text": "Constants that indicate the physical position of a capture device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@AVCaptureDevicePosition",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureDevice.Position",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice/Position-swift.enum"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGSize": {
      "abstract": [
        {
          "text": "A structure that contains width and height values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGSize",
      "type": "topic",
      "url": "/documentation/corefoundation/cgsize"
    },
    "doc://com.externally.resolved.symbol/c:@T@AVCaptureDeviceType": {
      "abstract": [
        {
          "text": "A structure that defines the device types the framework supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DeviceType"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@AVCaptureDeviceType",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureDevice.DeviceType",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct"
    },
    "doc://com.externally.resolved.symbol/c:@T@matrix_float3x3": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_float3x3"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@matrix_float3x3",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_float3x3",
      "type": "topic",
      "url": "/documentation/simd/matrix_float3x3"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AVCaptureDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AVCaptureDevicePosition/title",
          "value": "AVCaptureDevicePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AVCaptureDevicePosition/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureDevicePosition"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@matrix_float3x3/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_float3x3",
              "text": "simd_float3x3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "matrix_float3x3"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@AVCaptureDeviceType/title",
          "value": "AVCaptureDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@AVCaptureDeviceType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dockkit/dockaccessory/camerainformation/init(capturedevice:cameraposition:orientation:cameraintrinsics:referencedimensions:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
