{
  "abstract": [
    {
      "text": "The collection list is a smart folder containing one or more Events synced from iPhoto.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/smartFolderEvents"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHCollectionListSubtype@PHCollectionListSubtypeSmartFolderEvents",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "smartFolderEvents"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHCollectionListSubtypeSmartFolderEvents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHCollectionListSubtype.smartFolderEvents"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "smartFolderEvents"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This subtype applies only to collection lists whose type is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListType/smartFolder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionList/collectionListSubtype": {
      "abstract": [
        {
          "text": "The type of asset collection grouping the collection list represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionListSubtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHCollectionListSubtype",
          "text": "PHCollectionListSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList/collectionListSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionListSubtype"
        }
      ],
      "role": "symbol",
      "title": "collectionListSubtype",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlist/collectionlistsubtype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionList/fetchCollectionLists(with:subtype:options:)": {
      "abstract": [
        {
          "text": "Retrieves collection lists of the specified type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchCollectionLists"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHCollectionListType",
          "text": "PHCollectionListType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHCollectionListSubtype",
          "text": "PHCollectionListSubtype"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchOptions",
          "text": "PHFetchOptions"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCollectionList",
          "text": "PHCollectionList"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList/fetchCollectionLists(with:subtype:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchCollectionListsWithType:subtype:options:"
        }
      ],
      "role": "symbol",
      "title": "fetchCollectionLists(with:subtype:options:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlist/fetchcollectionlists(with:subtype:options:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionList/fetchMomentLists(with:containingMoment:options:)": {
      "abstract": [
        {
          "text": "Retrieves collection lists of the specified moment list type containing the specified moment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchMomentLists"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHCollectionListSubtype",
          "text": "PHCollectionListSubtype"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "containingMoment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetCollection",
          "text": "PHAssetCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchOptions",
          "text": "PHFetchOptions"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCollectionList",
          "text": "PHCollectionList"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList/fetchMomentLists(with:containingMoment:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchMomentListsWithSubtype:containingMoment:options:"
        }
      ],
      "role": "symbol",
      "title": "fetchMomentLists(with:containingMoment:options:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlist/fetchmomentlists(with:containingmoment:options:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionList/fetchMomentLists(with:options:)": {
      "abstract": [
        {
          "text": "Retrieves collection lists of the specified moment list type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchMomentLists"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHCollectionListSubtype",
          "text": "PHCollectionListSubtype"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchOptions",
          "text": "PHFetchOptions"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCollectionList",
          "text": "PHCollectionList"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList/fetchMomentLists(with:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchMomentListsWithSubtype:options:"
        }
      ],
      "role": "symbol",
      "title": "fetchMomentLists(with:options:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlist/fetchmomentlists(with:options:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype": {
      "abstract": [
        {
          "text": "Major distinctions between kinds of collection list, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList/collectionListSubtype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList/fetchCollectionLists(with:subtype:options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList/fetchMomentLists(with:containingMoment:options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList/fetchMomentLists(with:options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCollectionListSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListSubtype"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListSubtype",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistsubtype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/any": {
      "abstract": [
        {
          "text": "Use this value to fetch collection lists of all possible subtypes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListSubtypeAny"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListSubtype.any",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistsubtype/any"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/momentListCluster": {
      "abstract": [
        {
          "text": "The collection list is a moment cluster, grouping several related moments.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentListCluster"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/momentListCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListSubtypeMomentListCluster"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListSubtype.momentListCluster",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistsubtype/momentlistcluster"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/momentListYear": {
      "abstract": [
        {
          "text": "The collection list is a moment year, grouping all moments from one or more calendar years.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentListYear"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/momentListYear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListSubtypeMomentListYear"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListSubtype.momentListYear",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistsubtype/momentlistyear"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/regularFolder": {
      "abstract": [
        {
          "text": "The collection list is a folder containing albums or other folders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularFolder"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/regularFolder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListSubtypeRegularFolder"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListSubtype.regularFolder",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistsubtype/regularfolder"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/smartFolderEvents": {
      "abstract": [
        {
          "text": "The collection list is a smart folder containing one or more Events synced from iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartFolderEvents"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/smartFolderEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListSubtypeSmartFolderEvents"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListSubtype.smartFolderEvents",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistsubtype/smartfolderevents"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/smartFolderFaces": {
      "abstract": [
        {
          "text": "The collection list is a smart folder containing one or more Faces synced from iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartFolderFaces"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/smartFolderFaces",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListSubtypeSmartFolderFaces"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListSubtype.smartFolderFaces",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistsubtype/smartfolderfaces"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListType/smartFolder": {
      "abstract": [
        {
          "text": "A smart folder synced to the device from .",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartFolder"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListType/smartFolder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListTypeSmartFolder"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListType.smartFolder",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlisttype/smartfolder"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/momentListCluster",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/momentListYear",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/regularFolder",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/smartFolderFaces",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/any"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHCollectionListSubtypeSmartFolderEvents"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListSubtypeSmartFolderEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/momentListCluster",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/momentListYear",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/regularFolder",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/smartFolderFaces",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListSubtype/any"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHCollectionListSubtypeSmartFolderEvents"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList~1collectionListSubtype/title",
          "value": "collectionListSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList~1collectionListSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collectionListSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList~1fetchMomentLists(with:options:)/title",
          "value": "fetchMomentListsWithSubtype:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList~1fetchMomentLists(with:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchMomentListsWithSubtype:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1momentListYear/title",
          "value": "PHCollectionListSubtypeMomentListYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1momentListYear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListSubtypeMomentListYear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1momentListCluster/title",
          "value": "PHCollectionListSubtypeMomentListCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1momentListCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListSubtypeMomentListCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1regularFolder/title",
          "value": "PHCollectionListSubtypeRegularFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1regularFolder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListSubtypeRegularFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListType~1smartFolder/title",
          "value": "PHCollectionListTypeSmartFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListType~1smartFolder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListTypeSmartFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1smartFolderEvents/title",
          "value": "PHCollectionListSubtypeSmartFolderEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1smartFolderEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListSubtypeSmartFolderEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList~1fetchMomentLists(with:containingMoment:options:)/title",
          "value": "fetchMomentListsWithSubtype:containingMoment:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList~1fetchMomentLists(with:containingMoment:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchMomentListsWithSubtype:containingMoment:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1any/title",
          "value": "PHCollectionListSubtypeAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListSubtypeAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList~1fetchCollectionLists(with:subtype:options:)/title",
          "value": "fetchCollectionListsWithType:subtype:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList~1fetchCollectionLists(with:subtype:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchCollectionListsWithType:subtype:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1smartFolderFaces/title",
          "value": "PHCollectionListSubtypeSmartFolderFaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype~1smartFolderFaces/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListSubtypeSmartFolderFaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype/title",
          "value": "PHCollectionListSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListSubtype"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phcollectionlistsubtype/smartfolderevents"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phcollectionlistsubtype/smartfolderevents"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
