{
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/agl-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AGL Constants"
  },
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL-collection": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl/agl-collection"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ALLOW_OFFLINE_RENDERERS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ALLOW_OFFLINE_RENDERERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ALLOW_OFFLINE_RENDERERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ALLOW_OFFLINE_RENDERERS"
        }
      ],
      "role": "symbol",
      "title": "AGL_ALLOW_OFFLINE_RENDERERS",
      "type": "topic",
      "url": "/documentation/agl/agl_allow_offline_renderers"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_DISPLAY_MASK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_DISPLAY_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_DISPLAY_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_DISPLAY_MASK"
        }
      ],
      "role": "symbol",
      "title": "AGL_DISPLAY_MASK",
      "type": "topic",
      "url": "/documentation/agl/agl_display_mask"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_INVALID_FUNCTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_INVALID_FUNCTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_INVALID_FUNCTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_INVALID_FUNCTION"
        }
      ],
      "role": "symbol",
      "title": "AGL_INVALID_FUNCTION",
      "type": "topic",
      "url": "/documentation/agl/agl_invalid_function"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_VERSION_3_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_VERSION_3_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_VERSION_3_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_VERSION_3_0"
        }
      ],
      "role": "symbol",
      "title": "AGL_VERSION_3_0",
      "type": "topic",
      "url": "/documentation/agl/agl_version_3_0"
    },
    "doc://com.apple.agl/documentation/AGL/agl-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.agl/documentation/AGL/agl-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL Data Types",
      "type": "topic",
      "url": "/documentation/agl/agl-data-types"
    },
    "doc://com.apple.agl/documentation/AGL/agl-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.agl/documentation/AGL/agl-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL Functions",
      "type": "topic",
      "url": "/documentation/agl/agl-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL-collection"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_ALLOW_OFFLINE_RENDERERS",
        "doc://com.apple.agl/documentation/AGL/AGL_DISPLAY_MASK",
        "doc://com.apple.agl/documentation/AGL/AGL_INVALID_FUNCTION",
        "doc://com.apple.agl/documentation/AGL/AGL_VERSION_3_0",
        "doc://com.apple.agl/documentation/AGL/AGL_ALLOW_OFFLINE_RENDERERS",
        "doc://com.apple.agl/documentation/AGL/AGL_DISPLAY_MASK",
        "doc://com.apple.agl/documentation/AGL/AGL_INVALID_FUNCTION",
        "doc://com.apple.agl/documentation/AGL/AGL_VERSION_3_0"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_ALLOW_OFFLINE_RENDERERS",
                "doc://com.apple.agl/documentation/AGL/AGL_DISPLAY_MASK",
                "doc://com.apple.agl/documentation/AGL/AGL_INVALID_FUNCTION",
                "doc://com.apple.agl/documentation/AGL/AGL_VERSION_3_0",
                "doc://com.apple.agl/documentation/AGL/AGL_ALLOW_OFFLINE_RENDERERS",
                "doc://com.apple.agl/documentation/AGL/AGL_DISPLAY_MASK",
                "doc://com.apple.agl/documentation/AGL/AGL_INVALID_FUNCTION",
                "doc://com.apple.agl/documentation/AGL/AGL_VERSION_3_0"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL-collection",
                "doc://com.apple.agl/documentation/AGL/agl-functions",
                "doc://com.apple.agl/documentation/AGL/agl-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ALLOW_OFFLINE_RENDERERS/title",
          "value": "AGL_ALLOW_OFFLINE_RENDERERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ALLOW_OFFLINE_RENDERERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ALLOW_OFFLINE_RENDERERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DISPLAY_MASK/title",
          "value": "AGL_DISPLAY_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DISPLAY_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_DISPLAY_MASK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_INVALID_FUNCTION/title",
          "value": "AGL_INVALID_FUNCTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_INVALID_FUNCTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_INVALID_FUNCTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_VERSION_3_0/title",
          "value": "AGL_VERSION_3_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_VERSION_3_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_VERSION_3_0"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/agl-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/agl-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
