{
  "abstract": [
    {
      "text": "The associated value specifies the opacity of the OpenGL surface. A value of ",
      "type": "text"
    },
    {
      "code": "1",
      "type": "codeVoice"
    },
    {
      "text": " means the surface is opaque (the default); ",
      "type": "text"
    },
    {
      "code": "0",
      "type": "codeVoice"
    },
    {
      "text": " means completely transparent.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/AGL_SURFACE_OPACITY"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@AGL_SURFACE_OPACITY",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AGL_SURFACE_OPACITY"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AGL_SURFACE_OPACITY"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AGL_SURFACE_OPACITY"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AGL_SURFACE_OPACITY"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_NAME": {
      "abstract": [
        {
          "text": "The associated value is a buffer name. You can use this option to allow multiple OpenGL contexts to share a buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_NAME"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_NAME",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_NAME"
        }
      ],
      "role": "symbol",
      "title": "AGL_BUFFER_NAME",
      "type": "topic",
      "url": "/documentation/agl/agl_buffer_name"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_RECT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_RECT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_RECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_RECT"
        }
      ],
      "role": "symbol",
      "title": "AGL_BUFFER_RECT",
      "type": "topic",
      "url": "/documentation/agl/agl_buffer_rect"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_CLIP_REGION": {
      "abstract": [
        {
          "text": "Enables or sets the drawable clipping region. The associated value is a ",
          "type": "text"
        },
        {
          "code": "rgnHandle",
          "type": "codeVoice"
        },
        {
          "text": " data type that defines the clipping region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_CLIP_REGION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_CLIP_REGION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_CLIP_REGION"
        }
      ],
      "role": "symbol",
      "title": "AGL_CLIP_REGION",
      "type": "topic",
      "url": "/documentation/agl/agl_clip_region"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_COLORMAP_ENTRY": {
      "abstract": [
        {
          "text": "The associated value is a color map entry specifies as {",
          "type": "text"
        },
        {
          "code": "index, r, g, b}",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_COLORMAP_ENTRY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_COLORMAP_ENTRY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_COLORMAP_ENTRY"
        }
      ],
      "role": "symbol",
      "title": "AGL_COLORMAP_ENTRY",
      "type": "topic",
      "url": "/documentation/agl/agl_colormap_entry"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_COLORMAP_TRACKING": {
      "abstract": [
        {
          "text": "Enable or disable color map tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_COLORMAP_TRACKING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_COLORMAP_TRACKING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_COLORMAP_TRACKING"
        }
      ],
      "role": "symbol",
      "title": "AGL_COLORMAP_TRACKING",
      "type": "topic",
      "url": "/documentation/agl/agl_colormap_tracking"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_CONTEXT_DISPLAY_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_CONTEXT_DISPLAY_ID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_CONTEXT_DISPLAY_ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_CONTEXT_DISPLAY_ID"
        }
      ],
      "role": "symbol",
      "title": "AGL_CONTEXT_DISPLAY_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_context_display_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_CONTEXT_SURFACE_ID": {
      "abstract": [
        {
          "text": "The associated value is the ID of the drawable surface for the rendering context. You can’t set this value because the system sets it. However, you can retrieve the value using the function ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/library/archive/#id(F15035)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_CONTEXT_SURFACE_ID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_CONTEXT_SURFACE_ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_CONTEXT_SURFACE_ID"
        }
      ],
      "role": "symbol",
      "title": "AGL_CONTEXT_SURFACE_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_context_surface_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_FS_CAPTURE_SINGLE": {
      "abstract": [
        {
          "text": "Enables the capture of a single display for full-screen rendering. This option is disabled by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_FS_CAPTURE_SINGLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_FS_CAPTURE_SINGLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_FS_CAPTURE_SINGLE"
        }
      ],
      "role": "symbol",
      "title": "AGL_FS_CAPTURE_SINGLE",
      "type": "topic",
      "url": "/documentation/agl/agl_fs_capture_single"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ORDER_CONTEXT_TO_FRONT": {
      "abstract": [
        {
          "text": "Specifies to order the current rendering context in front of all the other contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ORDER_CONTEXT_TO_FRONT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ORDER_CONTEXT_TO_FRONT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ORDER_CONTEXT_TO_FRONT"
        }
      ],
      "role": "symbol",
      "title": "AGL_ORDER_CONTEXT_TO_FRONT",
      "type": "topic",
      "url": "/documentation/agl/agl_order_context_to_front"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RASTERIZATION": {
      "abstract": [
        {
          "text": "Enable or disable all rasterization of 2D and 3D primitives. You can use this option to debug and characterize the performance of an OpenGL driver without actually rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RASTERIZATION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RASTERIZATION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RASTERIZATION"
        }
      ],
      "role": "symbol",
      "title": "AGL_RASTERIZATION",
      "type": "topic",
      "url": "/documentation/agl/agl_rasterization"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_STATE_VALIDATION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_STATE_VALIDATION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_STATE_VALIDATION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_STATE_VALIDATION"
        }
      ],
      "role": "symbol",
      "title": "AGL_STATE_VALIDATION",
      "type": "topic",
      "url": "/documentation/agl/agl_state_validation"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SURFACE_OPACITY": {
      "abstract": [
        {
          "text": "The associated value specifies the opacity of the OpenGL surface. A value of ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": " means the surface is opaque (the default); ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " means completely transparent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SURFACE_OPACITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SURFACE_OPACITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SURFACE_OPACITY"
        }
      ],
      "role": "symbol",
      "title": "AGL_SURFACE_OPACITY",
      "type": "topic",
      "url": "/documentation/agl/agl_surface_opacity"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SURFACE_ORDER": {
      "abstract": [
        {
          "text": "The associated value is the position of the OpenGL surface relative to the window. A value of ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": " means that the position is above the window; a value of ",
          "type": "text"
        },
        {
          "code": "–1",
          "type": "codeVoice"
        },
        {
          "text": " specifies a position that is below the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SURFACE_ORDER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SURFACE_ORDER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SURFACE_ORDER"
        }
      ],
      "role": "symbol",
      "title": "AGL_SURFACE_ORDER",
      "type": "topic",
      "url": "/documentation/agl/agl_surface_order"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SWAP_INTERVAL": {
      "abstract": [
        {
          "text": "The associated parameter contains one value: the current swap interval setting. A value of ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": "   specifies not to synchronize to the vertical retrace. All other values indicate to synchronize to the vertical retrace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SWAP_INTERVAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SWAP_INTERVAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SWAP_INTERVAL"
        }
      ],
      "role": "symbol",
      "title": "AGL_SWAP_INTERVAL",
      "type": "topic",
      "url": "/documentation/agl/agl_swap_interval"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SWAP_LIMIT": {
      "abstract": [
        {
          "text": "Enable or disable the swap asynchronous limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SWAP_LIMIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SWAP_LIMIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SWAP_LIMIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_SWAP_LIMIT",
      "type": "topic",
      "url": "/documentation/agl/agl_swap_limit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SWAP_RECT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SWAP_RECT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SWAP_RECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SWAP_RECT"
        }
      ],
      "role": "symbol",
      "title": "AGL_SWAP_RECT",
      "type": "topic",
      "url": "/documentation/agl/agl_swap_rect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    },
    "https://developer.apple.com/library/archive/#id(F15035)": {
      "identifier": "https://developer.apple.com/library/archive/#id(F15035)",
      "title": "aglGetInteger",
      "titleInlineContent": [
        {
          "text": "aglGetInteger",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/#id(F15035)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_SWAP_RECT",
        "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_RECT",
        "doc://com.apple.agl/documentation/AGL/AGL_SWAP_LIMIT",
        "doc://com.apple.agl/documentation/AGL/AGL_COLORMAP_TRACKING",
        "doc://com.apple.agl/documentation/AGL/AGL_COLORMAP_ENTRY",
        "doc://com.apple.agl/documentation/AGL/AGL_RASTERIZATION",
        "doc://com.apple.agl/documentation/AGL/AGL_SWAP_INTERVAL",
        "doc://com.apple.agl/documentation/AGL/AGL_STATE_VALIDATION",
        "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_NAME",
        "doc://com.apple.agl/documentation/AGL/AGL_ORDER_CONTEXT_TO_FRONT",
        "doc://com.apple.agl/documentation/AGL/AGL_CONTEXT_SURFACE_ID",
        "doc://com.apple.agl/documentation/AGL/AGL_CONTEXT_DISPLAY_ID",
        "doc://com.apple.agl/documentation/AGL/AGL_SURFACE_ORDER",
        "doc://com.apple.agl/documentation/AGL/AGL_CLIP_REGION",
        "doc://com.apple.agl/documentation/AGL/AGL_FS_CAPTURE_SINGLE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AGL_SURFACE_OPACITY"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SURFACE_OPACITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.agl/documentation/AGL"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_SWAP_RECT",
                "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_RECT",
                "doc://com.apple.agl/documentation/AGL/AGL_SWAP_LIMIT",
                "doc://com.apple.agl/documentation/AGL/AGL_COLORMAP_TRACKING",
                "doc://com.apple.agl/documentation/AGL/AGL_COLORMAP_ENTRY",
                "doc://com.apple.agl/documentation/AGL/AGL_RASTERIZATION",
                "doc://com.apple.agl/documentation/AGL/AGL_SWAP_INTERVAL",
                "doc://com.apple.agl/documentation/AGL/AGL_STATE_VALIDATION",
                "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_NAME",
                "doc://com.apple.agl/documentation/AGL/AGL_ORDER_CONTEXT_TO_FRONT",
                "doc://com.apple.agl/documentation/AGL/AGL_CONTEXT_SURFACE_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_CONTEXT_DISPLAY_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_SURFACE_ORDER",
                "doc://com.apple.agl/documentation/AGL/AGL_CLIP_REGION",
                "doc://com.apple.agl/documentation/AGL/AGL_FS_CAPTURE_SINGLE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AGL_SURFACE_OPACITY"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ORDER_CONTEXT_TO_FRONT/title",
          "value": "AGL_ORDER_CONTEXT_TO_FRONT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ORDER_CONTEXT_TO_FRONT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ORDER_CONTEXT_TO_FRONT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_RECT/title",
          "value": "AGL_BUFFER_RECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_RECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BUFFER_RECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SURFACE_ORDER/title",
          "value": "AGL_SURFACE_ORDER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SURFACE_ORDER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SURFACE_ORDER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SWAP_RECT/title",
          "value": "AGL_SWAP_RECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SWAP_RECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SWAP_RECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STATE_VALIDATION/title",
          "value": "AGL_STATE_VALIDATION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STATE_VALIDATION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_STATE_VALIDATION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COLORMAP_TRACKING/title",
          "value": "AGL_COLORMAP_TRACKING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COLORMAP_TRACKING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_COLORMAP_TRACKING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SURFACE_OPACITY/title",
          "value": "AGL_SURFACE_OPACITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SURFACE_OPACITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SURFACE_OPACITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_NAME/title",
          "value": "AGL_BUFFER_NAME"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_NAME/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BUFFER_NAME"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_CONTEXT_DISPLAY_ID/title",
          "value": "AGL_CONTEXT_DISPLAY_ID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_CONTEXT_DISPLAY_ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_CONTEXT_DISPLAY_ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_CONTEXT_SURFACE_ID/title",
          "value": "AGL_CONTEXT_SURFACE_ID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_CONTEXT_SURFACE_ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_CONTEXT_SURFACE_ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SWAP_LIMIT/title",
          "value": "AGL_SWAP_LIMIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SWAP_LIMIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SWAP_LIMIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_CLIP_REGION/title",
          "value": "AGL_CLIP_REGION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_CLIP_REGION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_CLIP_REGION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_FS_CAPTURE_SINGLE/title",
          "value": "AGL_FS_CAPTURE_SINGLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_FS_CAPTURE_SINGLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_FS_CAPTURE_SINGLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SWAP_INTERVAL/title",
          "value": "AGL_SWAP_INTERVAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SWAP_INTERVAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SWAP_INTERVAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COLORMAP_ENTRY/title",
          "value": "AGL_COLORMAP_ENTRY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COLORMAP_ENTRY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_COLORMAP_ENTRY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RASTERIZATION/title",
          "value": "AGL_RASTERIZATION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RASTERIZATION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RASTERIZATION"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/agl_surface_opacity"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/agl_surface_opacity"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
