{
  "abstract": [
    {
      "text": "Specifies a format that has 8-16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=7:0, R=15:11, G=10:5, B=4:0",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/AGL_RGB565_A8_BIT"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@AGL_RGB565_A8_BIT",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AGL_RGB565_A8_BIT"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AGL_RGB565_A8_BIT"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AGL_RGB565_A8_BIT"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AGL_RGB565_A8_BIT"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ARGB1555_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=15, R=14:10, G=9:5, B=4:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ARGB1555_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ARGB1555_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ARGB1555_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_ARGB1555_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_argb1555_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ARGB4444_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=15:12, R=11:8, G=7:4, B=3:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ARGB4444_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ARGB4444_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ARGB4444_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_ARGB4444_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_argb4444_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ARGB8888_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 32 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=31:24, R=23:16, G=15:8, B=7:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ARGB8888_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ARGB8888_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ARGB8888_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_ARGB8888_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_argb8888_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BGR233_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies an 8-8 ARGB bits per pixel format and the channels located in the following bits: A=7:0, B=7:6, G=5:3, R=2:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BGR233_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BGR233_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BGR233_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_BGR233_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_bgr233_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BGR233_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8 bits per pixel with an RGB channel layout, and the channels located in the following bits:  B=7:6, G=5:3, R=2:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BGR233_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BGR233_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BGR233_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_BGR233_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_bgr233_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB332_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies an 8-8 ARGB bits per pixel format and the channels located in the following bits: A=7:0, R=7:5, G=4:2, B=1:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB332_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB332_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB332_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB332_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb332_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB332_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=7:5, G=4:2, B=1:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB332_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB332_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB332_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB332_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb332_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB444_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8-16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=7:0, R=11:8, G=7:4, B=3:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB444_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB444_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB444_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB444_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb444_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB444_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 16 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=11:8, G=7:4, B=3:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB444_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB444_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB444_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB444_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb444_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB555_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8-16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=7:0, R=14:10, G=9:5, B=4:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB555_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB555_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB555_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB555_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb555_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB555_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 16 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=14:10, G=9:5, B=4:0. The top bit is not used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB555_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB555_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB555_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB555_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb555_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB565_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8-16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=7:0, R=15:11, G=10:5, B=4:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB565_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB565_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB565_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB565_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb565_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB565_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 16 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=15:11, G=10:5, B=4:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB565_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB565_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB565_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB565_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb565_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB888_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 32 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=23:16, G=15:8, B=7:0; R, G, and B take 1 byte each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB888_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB888_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB888_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB888_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb888_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB8_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies an 8-8 ARGB bits per pixel format and the channels located in the following bits: A=7:0, RGB=7:0, inverse color map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB8_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB8_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB8_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB8_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb8_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB8_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8 bits per pixel with an RGB channel layout:  RGB=7:0, inverse color map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb8_bit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_RGB8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB8_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_BGR233_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_BGR233_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB332_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB332_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB444_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB4444_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB444_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB555_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB1555_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB555_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB565_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB888_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB8888_BIT"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AGL_RGB565_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB565_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.agl/documentation/AGL"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_RGB8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB8_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_BGR233_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_BGR233_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB332_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB332_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB444_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB4444_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB444_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB555_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB1555_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB555_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB565_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB888_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB8888_BIT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AGL_RGB565_A8_BIT"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BGR233_BIT/title",
          "value": "AGL_BGR233_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BGR233_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BGR233_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB8_BIT/title",
          "value": "AGL_RGB8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB1555_BIT/title",
          "value": "AGL_ARGB1555_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB1555_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ARGB1555_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB8_A8_BIT/title",
          "value": "AGL_RGB8_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB8_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB8_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB4444_BIT/title",
          "value": "AGL_ARGB4444_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB4444_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ARGB4444_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB555_A8_BIT/title",
          "value": "AGL_RGB555_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB555_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB555_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BGR233_A8_BIT/title",
          "value": "AGL_BGR233_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BGR233_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BGR233_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB444_A8_BIT/title",
          "value": "AGL_RGB444_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB444_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB444_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB332_BIT/title",
          "value": "AGL_RGB332_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB332_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB332_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB565_BIT/title",
          "value": "AGL_RGB565_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB565_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB565_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB888_BIT/title",
          "value": "AGL_RGB888_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB888_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB888_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB555_BIT/title",
          "value": "AGL_RGB555_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB555_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB555_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB444_BIT/title",
          "value": "AGL_RGB444_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB444_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB444_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB8888_BIT/title",
          "value": "AGL_ARGB8888_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB8888_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ARGB8888_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB565_A8_BIT/title",
          "value": "AGL_RGB565_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB565_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB565_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB332_A8_BIT/title",
          "value": "AGL_RGB332_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB332_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB332_A8_BIT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/agl_rgb565_a8_bit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/agl_rgb565_a8_bit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
