{
  "abstract": [
    {
      "text": "This constant is a Boolean attribute. If it is present in the attributes array, the pixel format choosing policy is altered for the color, depth, and accumulation buffers such that only buffers of size greater than or equal to the desired size are considered. Do not supply a value with this constant because its presence in the array implies ",
      "type": "text"
    },
    {
      "code": "true",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/AGL_MINIMUM_POLICY"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@AGL_MINIMUM_POLICY",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AGL_MINIMUM_POLICY"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AGL_MINIMUM_POLICY"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AGL_MINIMUM_POLICY"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AGL_MINIMUM_POLICY"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_RED_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of bits of red stored in the accumulation buffer. A red accumulation buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_RED_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_RED_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_RED_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_ACCUM_RED_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_accum_red_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ALL_RENDERERS": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, pixel format selection is open to all available renderers, including debug and special-purpose renderers that are not OpenGL compliant. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ALL_RENDERERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ALL_RENDERERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ALL_RENDERERS"
        }
      ],
      "role": "symbol",
      "title": "AGL_ALL_RENDERERS",
      "type": "topic",
      "url": "/documentation/agl/agl_all_renderers"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ALPHA_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of alpha component bits. The value is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " if the ",
          "type": "text"
        },
        {
          "code": "AGL_RGBA",
          "type": "codeVoice"
        },
        {
          "text": " attribute is ",
          "type": "text"
        },
        {
          "code": "GL_FALSE",
          "type": "codeVoice"
        },
        {
          "text": ". An alpha buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ALPHA_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ALPHA_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ALPHA_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_ALPHA_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_alpha_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_AUX_BUFFERS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_AUX_BUFFERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_AUX_BUFFERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_AUX_BUFFERS"
        }
      ],
      "role": "symbol",
      "title": "AGL_AUX_BUFFERS",
      "type": "topic",
      "url": "/documentation/agl/agl_aux_buffers"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BLUE_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of blue component bits. The value is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " if the ",
          "type": "text"
        },
        {
          "code": "AGL_RGBA",
          "type": "codeVoice"
        },
        {
          "text": " attribute is ",
          "type": "text"
        },
        {
          "code": "GL_FALSE",
          "type": "codeVoice"
        },
        {
          "text": ". A blue buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BLUE_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BLUE_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BLUE_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BLUE_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_blue_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_SIZE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BUFFER_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_buffer_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of bits in the depth buffer. A depth buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_DEPTH_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_DEPTH_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_DEPTH_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_depth_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, only double-buffered pixel formats are considered. Otherwise, only single-buffered pixel formats are considered. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_DOUBLEBUFFER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_DOUBLEBUFFER"
        }
      ],
      "role": "symbol",
      "title": "AGL_DOUBLEBUFFER",
      "type": "topic",
      "url": "/documentation/agl/agl_doublebuffer"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_GREEN_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of green component bits. The value is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " if the ",
          "type": "text"
        },
        {
          "code": "AGL_RGBA",
          "type": "codeVoice"
        },
        {
          "text": " attribute is ",
          "type": "text"
        },
        {
          "code": "GL_FALSE",
          "type": "codeVoice"
        },
        {
          "text": ". A green buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_GREEN_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_GREEN_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_GREEN_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_GREEN_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_green_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_LEVEL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_LEVEL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_LEVEL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_LEVEL"
        }
      ],
      "role": "symbol",
      "title": "AGL_LEVEL",
      "type": "topic",
      "url": "/documentation/agl/agl_level"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MINIMUM_POLICY": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, the pixel format choosing policy is altered for the color, depth, and accumulation buffers such that only buffers of size greater than or equal to the desired size are considered. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MINIMUM_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MINIMUM_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MINIMUM_POLICY"
        }
      ],
      "role": "symbol",
      "title": "AGL_MINIMUM_POLICY",
      "type": "topic",
      "url": "/documentation/agl/agl_minimum_policy"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_NONE": {
      "abstract": [
        {
          "text": "Used to terminate a pixel format attribute list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_NONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_NONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_NONE"
        }
      ],
      "role": "symbol",
      "title": "AGL_NONE",
      "type": "topic",
      "url": "/documentation/agl/agl_none"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RED_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of red component bits. The value is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " if the ",
          "type": "text"
        },
        {
          "code": "AGL_RGBA",
          "type": "codeVoice"
        },
        {
          "text": " attribute is ",
          "type": "text"
        },
        {
          "code": "GL_FALSE",
          "type": "codeVoice"
        },
        {
          "text": ". A red buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RED_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RED_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RED_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_RED_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_red_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGBA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGBA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGBA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGBA"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGBA",
      "type": "topic",
      "url": "/documentation/agl/agl_rgba"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of bits in the stencil buffer. The smallest stencil buffer of at least the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_STENCIL_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_STENCIL_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_STENCIL_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_stencil_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_STEREO": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, only stereo pixel formats are considered. Otherwise, only monoscopic pixel formats are considered. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_STEREO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_STEREO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_STEREO"
        }
      ],
      "role": "symbol",
      "title": "AGL_STEREO",
      "type": "topic",
      "url": "/documentation/agl/agl_stereo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_NONE",
        "doc://com.apple.agl/documentation/AGL/AGL_ALL_RENDERERS",
        "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBA",
        "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER",
        "doc://com.apple.agl/documentation/AGL/AGL_STEREO",
        "doc://com.apple.agl/documentation/AGL/AGL_AUX_BUFFERS",
        "doc://com.apple.agl/documentation/AGL/AGL_RED_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_GREEN_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_BLUE_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ALPHA_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_RED_SIZE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AGL_MINIMUM_POLICY"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MINIMUM_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.agl/documentation/AGL"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_NONE",
                "doc://com.apple.agl/documentation/AGL/AGL_ALL_RENDERERS",
                "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBA",
                "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER",
                "doc://com.apple.agl/documentation/AGL/AGL_STEREO",
                "doc://com.apple.agl/documentation/AGL/AGL_AUX_BUFFERS",
                "doc://com.apple.agl/documentation/AGL/AGL_RED_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_GREEN_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_BLUE_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ALPHA_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_RED_SIZE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AGL_MINIMUM_POLICY"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BLUE_SIZE/title",
          "value": "AGL_BLUE_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BLUE_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BLUE_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBA/title",
          "value": "AGL_RGBA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGBA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_GREEN_SIZE/title",
          "value": "AGL_GREEN_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_GREEN_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_GREEN_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STENCIL_SIZE/title",
          "value": "AGL_STENCIL_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STENCIL_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_STENCIL_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ALL_RENDERERS/title",
          "value": "AGL_ALL_RENDERERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ALL_RENDERERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ALL_RENDERERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_RED_SIZE/title",
          "value": "AGL_ACCUM_RED_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_RED_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ACCUM_RED_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DEPTH_SIZE/title",
          "value": "AGL_DEPTH_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DEPTH_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_DEPTH_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_NONE/title",
          "value": "AGL_NONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_NONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_NONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_SIZE/title",
          "value": "AGL_BUFFER_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BUFFER_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MINIMUM_POLICY/title",
          "value": "AGL_MINIMUM_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MINIMUM_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MINIMUM_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RED_SIZE/title",
          "value": "AGL_RED_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RED_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RED_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_AUX_BUFFERS/title",
          "value": "AGL_AUX_BUFFERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_AUX_BUFFERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_AUX_BUFFERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ALPHA_SIZE/title",
          "value": "AGL_ALPHA_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ALPHA_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ALPHA_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DOUBLEBUFFER/title",
          "value": "AGL_DOUBLEBUFFER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DOUBLEBUFFER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_DOUBLEBUFFER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STEREO/title",
          "value": "AGL_STEREO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STEREO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_STEREO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_LEVEL/title",
          "value": "AGL_LEVEL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_LEVEL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_LEVEL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/agl_minimum_policy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/agl_minimum_policy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
