{
  "abstract": [
    {
      "text": "Invalid numerical value.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/AGL_BAD_VALUE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@AGL_BAD_VALUE",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AGL_BAD_VALUE"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AGL_BAD_VALUE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AGL_BAD_VALUE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AGL_BAD_VALUE"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_ATTRIBUTE": {
      "abstract": [
        {
          "text": "Invalid pixel format attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_ATTRIBUTE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_ATTRIBUTE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_ATTRIBUTE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_ATTRIBUTE",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_attribute"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONTEXT": {
      "abstract": [
        {
          "text": "Invalid rendering context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_CONTEXT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONTEXT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_CONTEXT"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_CONTEXT",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_context"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_DRAWABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_DRAWABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_DRAWABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_DRAWABLE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_DRAWABLE",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_drawable"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_ENUM": {
      "abstract": [
        {
          "text": "Invalid enumerant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_ENUM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_ENUM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_ENUM"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_ENUM",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_enum"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_FULLSCREEN": {
      "abstract": [
        {
          "text": "Invalid full-screen drawable object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_FULLSCREEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_FULLSCREEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_FULLSCREEN"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_FULLSCREEN",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_fullscreen"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_GDEV": {
      "abstract": [
        {
          "text": "Invalid graphics device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_GDEV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_GDEV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_GDEV"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_GDEV",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_gdev"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_MATCH": {
      "abstract": [
        {
          "text": "Invalid share rendering context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_MATCH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_MATCH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_MATCH"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_MATCH",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_match"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_OFFSCREEN": {
      "abstract": [
        {
          "text": "Invalid offscreen drawable object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_OFFSCREEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_OFFSCREEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_OFFSCREEN"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_OFFSCREEN",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_offscreen"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_PIXELFMT": {
      "abstract": [
        {
          "text": "Invalid pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_PIXELFMT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_PIXELFMT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_PIXELFMT"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_PIXELFMT",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_pixelfmt"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_POINTER": {
      "abstract": [
        {
          "text": "Invalid pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_POINTER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_POINTER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_POINTER"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_POINTER",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_pointer"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_PROPERTY": {
      "abstract": [
        {
          "text": "Invalid renderer property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_PROPERTY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_PROPERTY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_PROPERTY"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_PROPERTY",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_property"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_RENDINFO": {
      "abstract": [
        {
          "text": "Invalid renderer info.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_RENDINFO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_RENDINFO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_RENDINFO"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_RENDINFO",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_rendinfo"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_STATE": {
      "abstract": [
        {
          "text": "Invalid rendering context state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_STATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_STATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_STATE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_STATE",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_state"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_VALUE": {
      "abstract": [
        {
          "text": "Invalid numerical value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_VALUE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_VALUE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_VALUE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_VALUE",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_value"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_WINDOW": {
      "abstract": [
        {
          "text": "Invalid window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_WINDOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_WINDOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_WINDOW"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_WINDOW",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_window"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_NO_ERROR": {
      "abstract": [
        {
          "text": "No error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_NO_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_NO_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_NO_ERROR"
        }
      ],
      "role": "symbol",
      "title": "AGL_NO_ERROR",
      "type": "topic",
      "url": "/documentation/agl/agl_no_error"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_NO_ERROR",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_ATTRIBUTE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_PROPERTY",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_PIXELFMT",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_RENDINFO",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONTEXT",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_DRAWABLE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_GDEV",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_STATE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_MATCH",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_ENUM",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_OFFSCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_FULLSCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_WINDOW",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_POINTER"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AGL_BAD_VALUE"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_VALUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.agl/documentation/AGL"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_NO_ERROR",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_ATTRIBUTE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_PROPERTY",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_PIXELFMT",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_RENDINFO",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONTEXT",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_DRAWABLE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_GDEV",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_STATE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_MATCH",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_ENUM",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_OFFSCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_FULLSCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_WINDOW",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_POINTER"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AGL_BAD_VALUE"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_PIXELFMT/title",
          "value": "AGL_BAD_PIXELFMT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_PIXELFMT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_PIXELFMT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_CONTEXT/title",
          "value": "AGL_BAD_CONTEXT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_CONTEXT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_CONTEXT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_NO_ERROR/title",
          "value": "AGL_NO_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_NO_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_NO_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_MATCH/title",
          "value": "AGL_BAD_MATCH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_MATCH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_MATCH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_DRAWABLE/title",
          "value": "AGL_BAD_DRAWABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_DRAWABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_DRAWABLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_POINTER/title",
          "value": "AGL_BAD_POINTER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_POINTER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_POINTER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_PROPERTY/title",
          "value": "AGL_BAD_PROPERTY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_PROPERTY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_PROPERTY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_WINDOW/title",
          "value": "AGL_BAD_WINDOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_WINDOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_WINDOW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_ENUM/title",
          "value": "AGL_BAD_ENUM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_ENUM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_ENUM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_STATE/title",
          "value": "AGL_BAD_STATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_STATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_STATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_VALUE/title",
          "value": "AGL_BAD_VALUE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_VALUE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_VALUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_OFFSCREEN/title",
          "value": "AGL_BAD_OFFSCREEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_OFFSCREEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_OFFSCREEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_RENDINFO/title",
          "value": "AGL_BAD_RENDINFO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_RENDINFO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_RENDINFO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_ATTRIBUTE/title",
          "value": "AGL_BAD_ATTRIBUTE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_ATTRIBUTE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_ATTRIBUTE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_GDEV/title",
          "value": "AGL_BAD_GDEV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_GDEV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_GDEV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_FULLSCREEN/title",
          "value": "AGL_BAD_FULLSCREEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_FULLSCREEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_FULLSCREEN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/agl_bad_value"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/agl_bad_value"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
