{
  "abstract": [
    {
      "text": "A bit depth of 6 bits.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/AGL_6_BIT"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@AGL_6_BIT",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AGL_6_BIT"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AGL_6_BIT"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AGL_6_BIT"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AGL_6_BIT"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_0_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_0_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_0_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_0_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_0_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_0_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_10_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 10 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_10_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_10_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_10_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_10_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_10_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_12_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 12 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_12_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_12_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_12_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_12_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_12_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_16_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 16 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_16_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_16_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_16_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_16_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_16_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_1_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 1 bit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_1_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_1_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_1_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_1_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_1_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_24_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 24 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_24_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_24_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_24_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_24_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_24_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_2_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 2 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_2_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_2_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_2_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_2_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_2_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_32_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 32 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_32_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_32_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_32_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_32_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_32_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_3_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 3 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_3_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_3_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_3_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_3_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_3_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_48_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 48 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_48_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_48_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_48_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_48_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_48_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_4_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 4 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_4_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_4_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_4_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_4_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_4_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_5_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 5 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_5_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_5_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_5_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_5_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_5_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_64_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 64 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_64_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_64_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_64_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_64_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_64_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_6_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 6 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_6_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_6_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_6_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_6_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_6_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_8_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 7 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_96_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 96 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_96_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_96_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_96_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_96_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_96_bit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_0_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_1_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_2_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_3_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_4_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_5_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_10_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_12_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_16_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_24_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_32_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_48_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_64_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_96_BIT"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AGL_6_BIT"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_6_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.agl/documentation/AGL"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_0_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_1_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_2_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_3_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_4_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_5_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_10_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_12_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_16_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_24_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_32_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_48_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_64_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_96_BIT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AGL_6_BIT"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_10_BIT/title",
          "value": "AGL_10_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_10_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_10_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_2_BIT/title",
          "value": "AGL_2_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_2_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_2_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_16_BIT/title",
          "value": "AGL_16_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_16_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_16_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_4_BIT/title",
          "value": "AGL_4_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_4_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_4_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_12_BIT/title",
          "value": "AGL_12_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_12_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_12_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_48_BIT/title",
          "value": "AGL_48_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_48_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_48_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_3_BIT/title",
          "value": "AGL_3_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_3_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_3_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_1_BIT/title",
          "value": "AGL_1_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_1_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_1_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_24_BIT/title",
          "value": "AGL_24_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_24_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_24_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_8_BIT/title",
          "value": "AGL_8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_32_BIT/title",
          "value": "AGL_32_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_32_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_32_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_5_BIT/title",
          "value": "AGL_5_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_5_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_5_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_0_BIT/title",
          "value": "AGL_0_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_0_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_0_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_96_BIT/title",
          "value": "AGL_96_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_96_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_96_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_64_BIT/title",
          "value": "AGL_64_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_64_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_64_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_6_BIT/title",
          "value": "AGL_6_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_6_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_6_BIT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/agl_6_bit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/agl_6_bit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
