{
  "abstract": [
    {
      "text": "The associated value can be a bitwise ",
      "type": "text"
    },
    {
      "code": "OR",
      "type": "codeVoice"
    },
    {
      "text": " of any of the constants specified in ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_MODES"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@AGL_ACCUM_MODES",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AGL_ACCUM_MODES"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AGL_ACCUM_MODES"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AGL_ACCUM_MODES"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AGL_ACCUM_MODES"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_MODES": {
      "abstract": [
        {
          "text": "The associated value can be a bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of any of the constants specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_MODES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_MODES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_MODES"
        }
      ],
      "role": "symbol",
      "title": "AGL_ACCUM_MODES",
      "type": "topic",
      "url": "/documentation/agl/agl_accum_modes"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES": {
      "abstract": [
        {
          "text": "The associated value can be a bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of the any of the constants specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_MODES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_MODES"
        }
      ],
      "role": "symbol",
      "title": "AGL_BUFFER_MODES",
      "type": "topic",
      "url": "/documentation/agl/agl_buffer_modes"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES": {
      "abstract": [
        {
          "text": "The associated value can be a bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of any of the constants specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_COLOR_MODES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_COLOR_MODES"
        }
      ],
      "role": "symbol",
      "title": "AGL_COLOR_MODES",
      "type": "topic",
      "url": "/documentation/agl/agl_color_modes"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES": {
      "abstract": [
        {
          "text": "The associated value can be the bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of any of the constants specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_DEPTH_MODES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_DEPTH_MODES"
        }
      ],
      "role": "symbol",
      "title": "AGL_DEPTH_MODES",
      "type": "topic",
      "url": "/documentation/agl/agl_depth_modes"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MAX_AUX_BUFFERS": {
      "abstract": [
        {
          "text": "The associated value is the maximum number of auxiliary buffers that can be supported by the renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MAX_AUX_BUFFERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MAX_AUX_BUFFERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MAX_AUX_BUFFERS"
        }
      ],
      "role": "symbol",
      "title": "AGL_MAX_AUX_BUFFERS",
      "type": "topic",
      "url": "/documentation/agl/agl_max_aux_buffers"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL": {
      "abstract": [
        {
          "text": "The associated value specifies the maximum overlay buffer level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MAX_LEVEL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MAX_LEVEL"
        }
      ],
      "role": "symbol",
      "title": "AGL_MAX_LEVEL",
      "type": "topic",
      "url": "/documentation/agl/agl_max_level"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL": {
      "abstract": [
        {
          "text": "The associated value specifies the minimum overlay buffer level. Negative values indicate an underlay buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MIN_LEVEL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MIN_LEVEL"
        }
      ],
      "role": "symbol",
      "title": "AGL_MIN_LEVEL",
      "type": "topic",
      "url": "/documentation/agl/agl_min_level"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_COUNT": {
      "abstract": [
        {
          "text": "The associated value is the number of renderers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_COUNT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_COUNT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_COUNT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RENDERER_COUNT",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_count"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_MODES": {
      "abstract": [
        {
          "text": "The associated value can be the bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of any of the constants specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_STENCIL_MODES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_MODES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_STENCIL_MODES"
        }
      ],
      "role": "symbol",
      "title": "AGL_STENCIL_MODES",
      "type": "topic",
      "url": "/documentation/agl/agl_stencil_modes"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_TEXTURE_MEMORY": {
      "abstract": [
        {
          "text": "The associated value is the amount of texture memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_TEXTURE_MEMORY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_TEXTURE_MEMORY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_TEXTURE_MEMORY"
        }
      ],
      "role": "symbol",
      "title": "AGL_TEXTURE_MEMORY",
      "type": "topic",
      "url": "/documentation/agl/agl_texture_memory"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_VIDEO_MEMORY": {
      "abstract": [
        {
          "text": "The associated value is the amount of video memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_VIDEO_MEMORY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_VIDEO_MEMORY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_VIDEO_MEMORY"
        }
      ],
      "role": "symbol",
      "title": "AGL_VIDEO_MEMORY",
      "type": "topic",
      "url": "/documentation/agl/agl_video_memory"
    },
    "doc://com.apple.agl/documentation/AGL/bit-depths": {
      "abstract": [
        {
          "text": "Define resolutions for the depth and stencil buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bit Depths",
      "type": "topic",
      "url": "/documentation/agl/bit-depths"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-mode-flags": {
      "abstract": [
        {
          "text": "Define constants used to set buffer modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Mode Flags",
      "type": "topic",
      "url": "/documentation/agl/buffer-mode-flags"
    },
    "doc://com.apple.agl/documentation/AGL/color-modes": {
      "abstract": [
        {
          "text": "Specify formats and color channel layout information for the color  buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Modes",
      "type": "topic",
      "url": "/documentation/agl/color-modes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_MAX_AUX_BUFFERS",
        "doc://com.apple.agl/documentation/AGL/AGL_VIDEO_MEMORY",
        "doc://com.apple.agl/documentation/AGL/AGL_TEXTURE_MEMORY",
        "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_COUNT",
        "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AGL_ACCUM_MODES"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ACCUM_MODES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.agl/documentation/AGL"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_MAX_AUX_BUFFERS",
                "doc://com.apple.agl/documentation/AGL/AGL_VIDEO_MEMORY",
                "doc://com.apple.agl/documentation/AGL/AGL_TEXTURE_MEMORY",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_COUNT",
                "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AGL_ACCUM_MODES"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STENCIL_MODES/title",
          "value": "AGL_STENCIL_MODES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STENCIL_MODES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_STENCIL_MODES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MIN_LEVEL/title",
          "value": "AGL_MIN_LEVEL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MIN_LEVEL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MIN_LEVEL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RENDERER_COUNT/title",
          "value": "AGL_RENDERER_COUNT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RENDERER_COUNT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RENDERER_COUNT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MAX_AUX_BUFFERS/title",
          "value": "AGL_MAX_AUX_BUFFERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MAX_AUX_BUFFERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MAX_AUX_BUFFERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_VIDEO_MEMORY/title",
          "value": "AGL_VIDEO_MEMORY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_VIDEO_MEMORY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_VIDEO_MEMORY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MAX_LEVEL/title",
          "value": "AGL_MAX_LEVEL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MAX_LEVEL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MAX_LEVEL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_MODES/title",
          "value": "AGL_BUFFER_MODES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_MODES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BUFFER_MODES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DEPTH_MODES/title",
          "value": "AGL_DEPTH_MODES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DEPTH_MODES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_DEPTH_MODES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_TEXTURE_MEMORY/title",
          "value": "AGL_TEXTURE_MEMORY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_TEXTURE_MEMORY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_TEXTURE_MEMORY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COLOR_MODES/title",
          "value": "AGL_COLOR_MODES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COLOR_MODES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_COLOR_MODES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_MODES/title",
          "value": "AGL_ACCUM_MODES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_MODES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ACCUM_MODES"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/agl_accum_modes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/agl_accum_modes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
