{
  "abstract": [
    {
      "text": "Sets the value of a global option.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.agl/documentation/AGL/aglConfigure"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@aglConfigure",
    "fragments": [
      {
        "kind": "identifier",
        "text": "aglConfigure"
      }
    ],
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "aglConfigure"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.9",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "aglConfigure"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLboolean",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLboolean",
              "text": "GLboolean"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "aglConfigure"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLenum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLenum",
              "text": "GLenum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pname"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLuint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLuint",
              "text": "GLuint"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "param"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the option whose value you want to set. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.agl/documentation/AGL/globally-configured-options",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for a list of constants you can pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pname"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The value to set the option to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "param"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "code": "GL_FALSE",
              "type": "codeVoice"
            },
            {
              "text": " if it fails for any reason, ",
              "type": "text"
            },
            {
              "code": "GL_TRUE",
              "type": "codeVoice"
            },
            {
              "text": " otherwise. If an error occurs, call the function ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/aglGetError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to determine what the error is.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function changes the values of options that affect the operation of OpenGL in all rendering contexts in the application, not just the current rendering context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/aglConfigure": {
      "abstract": [
        {
          "text": "Sets the value of a global option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglConfigure"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglConfigure",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglConfigure",
      "type": "topic",
      "url": "/documentation/agl/aglconfigure"
    },
    "doc://com.apple.agl/documentation/AGL/aglGetError": {
      "abstract": [
        {
          "text": "Returns an AGL error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglGetError"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglGetError",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglGetError",
      "type": "topic",
      "url": "/documentation/agl/aglgeterror"
    },
    "doc://com.apple.agl/documentation/AGL/aglGetVersion": {
      "abstract": [
        {
          "text": "Gets the major and minor version numbers of the AGL library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglGetVersion"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglGetVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglGetVersion",
      "type": "topic",
      "url": "/documentation/agl/aglgetversion"
    },
    "doc://com.apple.agl/documentation/AGL/aglResetLibrary": {
      "abstract": [
        {
          "text": "Resets the AGL library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglResetLibrary"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglResetLibrary",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglResetLibrary",
      "type": "topic",
      "url": "/documentation/agl/aglresetlibrary"
    },
    "doc://com.apple.agl/documentation/AGL/globally-configured-options": {
      "abstract": [
        {
          "text": "Specify options that apply globally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/globally-configured-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Globally Configured Options",
      "type": "topic",
      "url": "/documentation/agl/globally-configured-options"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLboolean": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLboolean"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLboolean",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLboolean",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLboolean"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLenum": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLenum"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLenum",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLenum",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLenum"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLuint": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLuint"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLuint",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLuint",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLuint"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-and-Setting-Global-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/aglGetVersion",
        "doc://com.apple.agl/documentation/AGL/aglResetLibrary"
      ],
      "title": "Getting and Setting Global Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLboolean/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint8_t",
              "text": "uint8_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLboolean"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLuint/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLuint"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLenum/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLenum"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/aglconfigure"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
