{
  "abstract": [
    {
      "text": "Retrieves the integer setting of an AGL context option.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.agl/documentation/AGL/aglGetInteger"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@aglGetInteger",
    "fragments": [
      {
        "kind": "identifier",
        "text": "aglGetInteger"
      }
    ],
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "aglGetInteger"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.9",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "aglGetInteger"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLboolean",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLboolean",
              "text": "GLboolean"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "aglGetInteger"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/AGLContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AGLContext",
              "text": "AGLContext"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ctx"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLenum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLenum",
              "text": "GLenum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pname"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLint",
              "text": "GLint"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "params"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An  rendering context.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ctx"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The option whose value you want to retrieve. You can pass any of the constants listed in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that have an associated value.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pname"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to the value of the option.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "params"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "code": "GL_FALSE",
              "type": "codeVoice"
            },
            {
              "text": " if it fails for any reason, ",
              "type": "text"
            },
            {
              "code": "GL_TRUE",
              "type": "codeVoice"
            },
            {
              "text": " otherwise. If an error occurs, call the function ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/aglGetError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to determine what the error is. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/error-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/aglEnable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to enable the option.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGLContext": {
      "abstract": [
        {
          "text": "Represents a pointer to an opaque AGL context object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGLContext"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGLContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGLContext",
      "type": "topic",
      "url": "/documentation/agl/aglcontext"
    },
    "doc://com.apple.agl/documentation/AGL/aglDisable": {
      "abstract": [
        {
          "text": "Disables an option for a rendering context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglDisable"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglDisable",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglDisable",
      "type": "topic",
      "url": "/documentation/agl/agldisable"
    },
    "doc://com.apple.agl/documentation/AGL/aglEnable": {
      "abstract": [
        {
          "text": "Enables an option for a rendering context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglEnable"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglEnable",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglEnable",
      "type": "topic",
      "url": "/documentation/agl/aglenable"
    },
    "doc://com.apple.agl/documentation/AGL/aglGetError": {
      "abstract": [
        {
          "text": "Returns an AGL error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglGetError"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglGetError",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglGetError",
      "type": "topic",
      "url": "/documentation/agl/aglgeterror"
    },
    "doc://com.apple.agl/documentation/AGL/aglGetInteger": {
      "abstract": [
        {
          "text": "Retrieves the integer setting of an AGL context option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglGetInteger"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglGetInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglGetInteger",
      "type": "topic",
      "url": "/documentation/agl/aglgetinteger"
    },
    "doc://com.apple.agl/documentation/AGL/aglIsEnabled": {
      "abstract": [
        {
          "text": "Reports whether an option is enabled for a rendering context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglIsEnabled"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglIsEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglIsEnabled",
      "type": "topic",
      "url": "/documentation/agl/aglisenabled"
    },
    "doc://com.apple.agl/documentation/AGL/aglSetInteger": {
      "abstract": [
        {
          "text": "Sets the value of an option for a rendering context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglSetInteger"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglSetInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglSetInteger",
      "type": "topic",
      "url": "/documentation/agl/aglsetinteger"
    },
    "doc://com.apple.agl/documentation/AGL/context-options-and-parameters": {
      "abstract": [
        {
          "text": "Define options and parameters that apply to a specific rendering context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Options and Parameters",
      "type": "topic",
      "url": "/documentation/agl/context-options-and-parameters"
    },
    "doc://com.apple.agl/documentation/AGL/error-codes": {
      "abstract": [
        {
          "text": "Defines the error codes that can be returned by the ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/agl/error-codes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLboolean": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLboolean"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLboolean",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLboolean",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLboolean"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLenum": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLenum"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLenum",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLenum",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLenum"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLint": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLint",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLint",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLint"
    },
    "https://developer.apple.com/library/archive/#id(F15037)": {
      "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
      "title": "aglGetError",
      "titleInlineContent": [
        {
          "text": "aglGetError",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/#id(F15037)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-and-Setting-Context-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/aglEnable",
        "doc://com.apple.agl/documentation/AGL/aglDisable",
        "doc://com.apple.agl/documentation/AGL/aglIsEnabled",
        "doc://com.apple.agl/documentation/AGL/aglSetInteger"
      ],
      "title": "Getting and Setting Context Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLint/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@int32_t",
              "text": "int32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLint"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLboolean/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint8_t",
              "text": "uint8_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLboolean"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLenum/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLenum"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/aglgetinteger"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
