{
  "abstract": [
    {
      "text": "Attaches a rendering context to a full screen graphics device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.agl/documentation/AGL/aglSetFullScreen"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@aglSetFullScreen",
    "fragments": [
      {
        "kind": "identifier",
        "text": "aglSetFullScreen"
      }
    ],
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "aglSetFullScreen"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.6",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "aglSetFullScreen"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLboolean",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLboolean",
              "text": "GLboolean"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "aglSetFullScreen"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/AGLContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AGLContext",
              "text": "AGLContext"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ctx"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLsizei",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLsizei",
              "text": "GLsizei"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "width"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLsizei",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLsizei",
              "text": "GLsizei"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "height"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLsizei",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLsizei",
              "text": "GLsizei"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "freq"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLint",
              "text": "GLint"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "device"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A rendering context.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ctx"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The width, in pixels, of the graphics device. This value must be an exact match to the graphics device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "width"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The height, in pixels, of the graphics device.  This value must be an exact match to the graphics device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "height"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The refresh frequency of the graphics device, in Hertz. If you specify a ",
                  "type": "text"
                },
                {
                  "code": "frequency",
                  "type": "codeVoice"
                },
                {
                  "text": " of ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ", AGL uses the highest refresh frequency available for the specified ",
                  "type": "text"
                },
                {
                  "code": "width",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "height",
                  "type": "codeVoice"
                },
                {
                  "text": ". If you specify a nonzero frequency, AGL chooses the closest frequency available for the given geometry. If a display provides only a ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": " refresh frequency, AGL   matches it with ",
                  "type": "text"
                },
                {
                  "code": "width",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "height",
                  "type": "codeVoice"
                },
                {
                  "text": " regardless of the value of ",
                  "type": "text"
                },
                {
                  "code": "frequency",
                  "type": "codeVoice"
                },
                {
                  "text": " passed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "freq"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This parameter is ignored in macOS, where all devices that are compatible with the pixel format of the rendering context are considered when selecting a full screen graphics device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "device"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "code": "GL_FALSE",
              "type": "codeVoice"
            },
            {
              "text": " if it fails for any reason, ",
              "type": "text"
            },
            {
              "code": "GL_TRUE",
              "type": "codeVoice"
            },
            {
              "text": " otherwise. If an error occurs, call the function ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/aglGetError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to determine what the error is.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Passing  ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " for the width, ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " for the height, and ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " for the frequency sets up a full screen context at the current height, width, and refresh rate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After calling this function, subsequent OpenGL rendering calls directed to the full-screen graphics device. The rendering context must be created with respect to a pixel format that supports a full-screen device, which you can request by passing ",
              "type": "text"
            },
            {
              "code": "AGL_FULLSCREEN",
              "type": "codeVoice"
            },
            {
              "text": " to the function ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/aglChoosePixelFormat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The ",
              "type": "text"
            },
            {
              "code": "aglSetFullScreen",
              "type": "codeVoice"
            },
            {
              "text": " function also performs all of the actions performed by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/aglUpdateContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The ",
              "type": "text"
            },
            {
              "code": "aglSetFullScreen",
              "type": "codeVoice"
            },
            {
              "text": " function uses information obtained from the pixel format object use to create the rendering context to choose the color depth for full-screen display mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When a rendering context is initially attached to a full screen graphics device, its viewport is set to the full size of the device. If the rendering context is subsequently attached to the same device, its viewport is unaltered. To disable a rendering context, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/aglSetDrawable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with the ",
              "type": "text"
            },
            {
              "code": "draw",
              "type": "codeVoice"
            },
            {
              "text": " parameter set to ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGLContext": {
      "abstract": [
        {
          "text": "Represents a pointer to an opaque AGL context object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGLContext"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGLContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGLContext",
      "type": "topic",
      "url": "/documentation/agl/aglcontext"
    },
    "doc://com.apple.agl/documentation/AGL/aglChoosePixelFormat": {
      "abstract": [
        {
          "text": "Creates a pixel format object that satisfies the constraints of the specified buffer and renderer attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglChoosePixelFormat"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglChoosePixelFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglChoosePixelFormat",
      "type": "topic",
      "url": "/documentation/agl/aglchoosepixelformat"
    },
    "doc://com.apple.agl/documentation/AGL/aglGetDrawable": {
      "abstract": [
        {
          "text": "Returns the drawable object attached to a rendering context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglGetDrawable"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglGetDrawable",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglGetDrawable",
      "type": "topic",
      "url": "/documentation/agl/aglgetdrawable"
    },
    "doc://com.apple.agl/documentation/AGL/aglGetError": {
      "abstract": [
        {
          "text": "Returns an AGL error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglGetError"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglGetError",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglGetError",
      "type": "topic",
      "url": "/documentation/agl/aglgeterror"
    },
    "doc://com.apple.agl/documentation/AGL/aglSetDrawable": {
      "abstract": [
        {
          "text": "Attaches a  rendering context to a Carbon window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglSetDrawable"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglSetDrawable",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglSetDrawable",
      "type": "topic",
      "url": "/documentation/agl/aglsetdrawable"
    },
    "doc://com.apple.agl/documentation/AGL/aglSetFullScreen": {
      "abstract": [
        {
          "text": "Attaches a rendering context to a full screen graphics device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglSetFullScreen"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglSetFullScreen",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglSetFullScreen",
      "type": "topic",
      "url": "/documentation/agl/aglsetfullscreen"
    },
    "doc://com.apple.agl/documentation/AGL/aglSetOffScreen": {
      "abstract": [
        {
          "text": "Attaches a rendering context to an offscreen memory area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglSetOffScreen"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglSetOffScreen",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglSetOffScreen",
      "type": "topic",
      "url": "/documentation/agl/aglsetoffscreen"
    },
    "doc://com.apple.agl/documentation/AGL/aglUpdateContext": {
      "abstract": [
        {
          "text": "Notifies the rendering context that the window geometry has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "aglUpdateContext"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/aglUpdateContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "aglUpdateContext",
      "type": "topic",
      "url": "/documentation/agl/aglupdatecontext"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLboolean": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLboolean"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLboolean",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLboolean",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLboolean"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLint": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLint",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLint",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLint"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLsizei": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLsizei"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLsizei",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLsizei",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLsizei"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Drawable-Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/aglGetDrawable",
        "doc://com.apple.agl/documentation/AGL/aglSetDrawable",
        "doc://com.apple.agl/documentation/AGL/aglSetOffScreen"
      ],
      "title": "Managing Drawable Objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLsizei/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@int32_t",
              "text": "int32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLsizei"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLboolean/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint8_t",
              "text": "uint8_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLboolean"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLint/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@int32_t",
              "text": "int32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLint"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/aglsetfullscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
