{
  "abstract": [
    {
      "text": "Define resolutions for the depth and stencil buffers.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL",
        "doc://com.apple.agl/documentation/AGL/AGL-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/bit-depths"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Bit Depths"
  },
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL-collection": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl/agl-collection"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_0_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_0_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_0_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_0_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_0_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_0_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_10_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 10 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_10_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_10_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_10_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_10_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_10_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_128_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 128 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_128_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_128_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_128_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_128_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_128_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_12_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 12 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_12_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_12_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_12_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_12_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_12_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_16_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 16 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_16_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_16_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_16_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_16_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_16_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_1_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 1 bit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_1_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_1_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_1_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_1_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_1_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_24_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 24 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_24_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_24_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_24_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_24_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_24_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_2_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 2 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_2_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_2_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_2_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_2_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_2_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_32_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 32 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_32_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_32_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_32_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_32_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_32_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_3_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 3 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_3_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_3_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_3_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_3_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_3_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_48_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 48 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_48_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_48_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_48_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_48_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_48_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_4_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 4 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_4_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_4_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_4_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_4_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_4_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_5_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 5 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_5_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_5_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_5_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_5_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_5_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_64_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 64 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_64_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_64_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_64_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_64_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_64_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_6_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 6 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_6_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_6_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_6_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_6_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_6_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_8_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 7 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_96_BIT": {
      "abstract": [
        {
          "text": "A bit depth of 96 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_96_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_96_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_96_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_96_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_96_bit"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes": {
      "abstract": [
        {
          "text": "Specify attributes used to create a pixel format object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer and Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/buffer-and-renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-mode-flags": {
      "abstract": [
        {
          "text": "Define constants used to set buffer modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Mode Flags",
      "type": "topic",
      "url": "/documentation/agl/buffer-mode-flags"
    },
    "doc://com.apple.agl/documentation/AGL/color-modes": {
      "abstract": [
        {
          "text": "Specify formats and color channel layout information for the color  buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Modes",
      "type": "topic",
      "url": "/documentation/agl/color-modes"
    },
    "doc://com.apple.agl/documentation/AGL/context-options-and-parameters": {
      "abstract": [
        {
          "text": "Define options and parameters that apply to a specific rendering context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Options and Parameters",
      "type": "topic",
      "url": "/documentation/agl/context-options-and-parameters"
    },
    "doc://com.apple.agl/documentation/AGL/error-codes": {
      "abstract": [
        {
          "text": "Defines the error codes that can be returned by the ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/agl/error-codes"
    },
    "doc://com.apple.agl/documentation/AGL/globally-configured-options": {
      "abstract": [
        {
          "text": "Specify options that apply globally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/globally-configured-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Globally Configured Options",
      "type": "topic",
      "url": "/documentation/agl/globally-configured-options"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-attributes": {
      "abstract": [
        {
          "text": "Define options for managing renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-ids": {
      "abstract": [
        {
          "text": "Define constants that specify hardware and software renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer IDs",
      "type": "topic",
      "url": "/documentation/agl/renderer-ids"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-properties": {
      "abstract": [
        {
          "text": "Specify constants that you can use to query renderer properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Properties",
      "type": "topic",
      "url": "/documentation/agl/renderer-properties"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/#id(F15037)": {
      "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
      "title": "aglGetError",
      "titleInlineContent": [
        {
          "text": "aglGetError",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/#id(F15037)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
        "doc://com.apple.agl/documentation/AGL/color-modes",
        "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
        "doc://com.apple.agl/documentation/AGL/error-codes",
        "doc://com.apple.agl/documentation/AGL/globally-configured-options",
        "doc://com.apple.agl/documentation/AGL/renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/renderer-ids",
        "doc://com.apple.agl/documentation/AGL/renderer-properties"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_0_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_1_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_2_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_3_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_4_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_5_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_6_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_10_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_12_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_16_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_24_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_32_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_48_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_64_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_96_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_128_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_0_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_1_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_2_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_3_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_4_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_5_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_6_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_10_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_12_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_16_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_24_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_32_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_48_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_64_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_96_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_128_BIT"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_0_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_1_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_2_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_3_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_4_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_5_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_6_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_10_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_12_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_16_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_24_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_32_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_48_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_64_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_96_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_128_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_0_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_1_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_2_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_3_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_4_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_5_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_6_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_10_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_12_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_16_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_24_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_32_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_48_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_64_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_96_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_128_BIT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
                "doc://com.apple.agl/documentation/AGL/color-modes",
                "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
                "doc://com.apple.agl/documentation/AGL/error-codes",
                "doc://com.apple.agl/documentation/AGL/globally-configured-options",
                "doc://com.apple.agl/documentation/AGL/renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/renderer-ids",
                "doc://com.apple.agl/documentation/AGL/renderer-properties"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_10_BIT/title",
          "value": "AGL_10_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_10_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_10_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_96_BIT/title",
          "value": "AGL_96_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_96_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_96_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_2_BIT/title",
          "value": "AGL_2_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_2_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_2_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_0_BIT/title",
          "value": "AGL_0_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_0_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_0_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_128_BIT/title",
          "value": "AGL_128_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_128_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_128_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_48_BIT/title",
          "value": "AGL_48_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_48_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_48_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_3_BIT/title",
          "value": "AGL_3_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_3_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_3_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_6_BIT/title",
          "value": "AGL_6_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_6_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_6_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_12_BIT/title",
          "value": "AGL_12_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_12_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_12_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_24_BIT/title",
          "value": "AGL_24_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_24_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_24_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_8_BIT/title",
          "value": "AGL_8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_4_BIT/title",
          "value": "AGL_4_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_4_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_4_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_16_BIT/title",
          "value": "AGL_16_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_16_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_16_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_64_BIT/title",
          "value": "AGL_64_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_64_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_64_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_1_BIT/title",
          "value": "AGL_1_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_1_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_1_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_32_BIT/title",
          "value": "AGL_32_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_32_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_32_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_5_BIT/title",
          "value": "AGL_5_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_5_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_5_BIT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/bit-depths"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/bit-depths"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
