{
  "abstract": [
    {
      "text": "Specify attributes used to create a pixel format object.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL",
        "doc://com.apple.agl/documentation/AGL/AGL-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Buffer and Renderer Attributes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each of these constants can be assigned to the the attribute array passed to the function ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". They can also be passed to the function ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL-collection": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl/agl-collection"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_ALPHA_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of bits of alpha stored in the accumulation buffer. An alpha accumulation buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_ALPHA_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_ALPHA_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_ALPHA_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_ACCUM_ALPHA_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_accum_alpha_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_BLUE_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of bits of blue stored in the accumulation buffer. A blue accumulation buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_BLUE_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_BLUE_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_BLUE_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_ACCUM_BLUE_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_accum_blue_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_GREEN_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of bits of green stored in the accumulation buffer. A green accumulation buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_GREEN_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_GREEN_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_GREEN_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_ACCUM_GREEN_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_accum_green_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_RED_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of bits of red stored in the accumulation buffer. A red accumulation buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_RED_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_RED_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_RED_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_ACCUM_RED_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_accum_red_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ALL_RENDERERS": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, pixel format selection is open to all available renderers, including debug and special-purpose renderers that are not OpenGL compliant. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ALL_RENDERERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ALL_RENDERERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ALL_RENDERERS"
        }
      ],
      "role": "symbol",
      "title": "AGL_ALL_RENDERERS",
      "type": "topic",
      "url": "/documentation/agl/agl_all_renderers"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ALPHA_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of alpha component bits. The value is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " if the ",
          "type": "text"
        },
        {
          "code": "AGL_RGBA",
          "type": "codeVoice"
        },
        {
          "text": " attribute is ",
          "type": "text"
        },
        {
          "code": "GL_FALSE",
          "type": "codeVoice"
        },
        {
          "text": ". An alpha buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ALPHA_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ALPHA_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ALPHA_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_ALPHA_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_alpha_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_AUX_BUFFERS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_AUX_BUFFERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_AUX_BUFFERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_AUX_BUFFERS"
        }
      ],
      "role": "symbol",
      "title": "AGL_AUX_BUFFERS",
      "type": "topic",
      "url": "/documentation/agl/agl_aux_buffers"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_AUX_DEPTH_STENCIL": {
      "abstract": [
        {
          "text": "The associated value is the independent depth and/or the stencil buffers for the auxiliary buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_AUX_DEPTH_STENCIL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_AUX_DEPTH_STENCIL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_AUX_DEPTH_STENCIL"
        }
      ],
      "role": "symbol",
      "title": "AGL_AUX_DEPTH_STENCIL",
      "type": "topic",
      "url": "/documentation/agl/agl_aux_depth_stencil"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BLUE_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of blue component bits. The value is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " if the ",
          "type": "text"
        },
        {
          "code": "AGL_RGBA",
          "type": "codeVoice"
        },
        {
          "text": " attribute is ",
          "type": "text"
        },
        {
          "code": "GL_FALSE",
          "type": "codeVoice"
        },
        {
          "text": ". A blue buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BLUE_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BLUE_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BLUE_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BLUE_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_blue_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_SIZE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BUFFER_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_buffer_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_COLOR_FLOAT": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, color buffers store floating-point pixels. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_COLOR_FLOAT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_COLOR_FLOAT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_COLOR_FLOAT"
        }
      ],
      "role": "symbol",
      "title": "AGL_COLOR_FLOAT",
      "type": "topic",
      "url": "/documentation/agl/agl_color_float"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of bits in the depth buffer. A depth buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_DEPTH_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_DEPTH_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_DEPTH_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_depth_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, only double-buffered pixel formats are considered. Otherwise, only single-buffered pixel formats are considered. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_DOUBLEBUFFER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_DOUBLEBUFFER"
        }
      ],
      "role": "symbol",
      "title": "AGL_DOUBLEBUFFER",
      "type": "topic",
      "url": "/documentation/agl/agl_doublebuffer"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_FULLSCREEN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_FULLSCREEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_FULLSCREEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_FULLSCREEN"
        }
      ],
      "role": "symbol",
      "title": "AGL_FULLSCREEN",
      "type": "topic",
      "url": "/documentation/agl/agl_fullscreen"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_GREEN_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of green component bits. The value is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " if the ",
          "type": "text"
        },
        {
          "code": "AGL_RGBA",
          "type": "codeVoice"
        },
        {
          "text": " attribute is ",
          "type": "text"
        },
        {
          "code": "GL_FALSE",
          "type": "codeVoice"
        },
        {
          "text": ". A green buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_GREEN_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_GREEN_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_GREEN_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_GREEN_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_green_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_LEVEL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_LEVEL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_LEVEL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_LEVEL"
        }
      ],
      "role": "symbol",
      "title": "AGL_LEVEL",
      "type": "topic",
      "url": "/documentation/agl/agl_level"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MAXIMUM_POLICY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MAXIMUM_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MAXIMUM_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MAXIMUM_POLICY"
        }
      ],
      "role": "symbol",
      "title": "AGL_MAXIMUM_POLICY",
      "type": "topic",
      "url": "/documentation/agl/agl_maximum_policy"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MINIMUM_POLICY": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, the pixel format choosing policy is altered for the color, depth, and accumulation buffers such that only buffers of size greater than or equal to the desired size are considered. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MINIMUM_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MINIMUM_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MINIMUM_POLICY"
        }
      ],
      "role": "symbol",
      "title": "AGL_MINIMUM_POLICY",
      "type": "topic",
      "url": "/documentation/agl/agl_minimum_policy"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MULTISAMPLE": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array,  specifies a hint to the driver to prefer multisampling. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MULTISAMPLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MULTISAMPLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MULTISAMPLE"
        }
      ],
      "role": "symbol",
      "title": "AGL_MULTISAMPLE",
      "type": "topic",
      "url": "/documentation/agl/agl_multisample"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_NONE": {
      "abstract": [
        {
          "text": "Used to terminate a pixel format attribute list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_NONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_NONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_NONE"
        }
      ],
      "role": "symbol",
      "title": "AGL_NONE",
      "type": "topic",
      "url": "/documentation/agl/agl_none"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_OFFSCREEN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_OFFSCREEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_OFFSCREEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_OFFSCREEN"
        }
      ],
      "role": "symbol",
      "title": "AGL_OFFSCREEN",
      "type": "topic",
      "url": "/documentation/agl/agl_offscreen"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_PIXEL_SIZE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_PIXEL_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_PIXEL_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_PIXEL_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_PIXEL_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_pixel_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RED_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of red component bits. The value is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " if the ",
          "type": "text"
        },
        {
          "code": "AGL_RGBA",
          "type": "codeVoice"
        },
        {
          "text": " attribute is ",
          "type": "text"
        },
        {
          "code": "GL_FALSE",
          "type": "codeVoice"
        },
        {
          "text": ". A red buffer that most closely matches the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RED_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RED_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RED_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_RED_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_red_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGBA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGBA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGBA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGBA"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGBA",
      "type": "topic",
      "url": "/documentation/agl/agl_rgba"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SAMPLES_ARB": {
      "abstract": [
        {
          "text": "The associated value is the number of samples per multisample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SAMPLES_ARB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SAMPLES_ARB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SAMPLES_ARB"
        }
      ],
      "role": "symbol",
      "title": "AGL_SAMPLES_ARB",
      "type": "topic",
      "url": "/documentation/agl/agl_samples_arb"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_ALPHA": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, request alpha filtering when multisampling. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SAMPLE_ALPHA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_ALPHA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SAMPLE_ALPHA"
        }
      ],
      "role": "symbol",
      "title": "AGL_SAMPLE_ALPHA",
      "type": "topic",
      "url": "/documentation/agl/agl_sample_alpha"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_BUFFERS_ARB": {
      "abstract": [
        {
          "text": "The associated value is the number of multisample buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SAMPLE_BUFFERS_ARB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_BUFFERS_ARB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SAMPLE_BUFFERS_ARB"
        }
      ],
      "role": "symbol",
      "title": "AGL_SAMPLE_BUFFERS_ARB",
      "type": "topic",
      "url": "/documentation/agl/agl_sample_buffers_arb"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_SIZE": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies the number of bits in the stencil buffer. The smallest stencil buffer of at least the specified size is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_STENCIL_SIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_SIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_STENCIL_SIZE"
        }
      ],
      "role": "symbol",
      "title": "AGL_STENCIL_SIZE",
      "type": "topic",
      "url": "/documentation/agl/agl_stencil_size"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_STEREO": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, only stereo pixel formats are considered. Otherwise, only monoscopic pixel formats are considered. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_STEREO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_STEREO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_STEREO"
        }
      ],
      "role": "symbol",
      "title": "AGL_STEREO",
      "type": "topic",
      "url": "/documentation/agl/agl_stereo"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SUPERSAMPLE": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, specifies a hint to the driver to prefer supersampling. Do not supply a value with this constant because its presence in the array implies ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SUPERSAMPLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SUPERSAMPLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SUPERSAMPLE"
        }
      ],
      "role": "symbol",
      "title": "AGL_SUPERSAMPLE",
      "type": "topic",
      "url": "/documentation/agl/agl_supersample"
    },
    "doc://com.apple.agl/documentation/AGL/bit-depths": {
      "abstract": [
        {
          "text": "Define resolutions for the depth and stencil buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bit Depths",
      "type": "topic",
      "url": "/documentation/agl/bit-depths"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-mode-flags": {
      "abstract": [
        {
          "text": "Define constants used to set buffer modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Mode Flags",
      "type": "topic",
      "url": "/documentation/agl/buffer-mode-flags"
    },
    "doc://com.apple.agl/documentation/AGL/color-modes": {
      "abstract": [
        {
          "text": "Specify formats and color channel layout information for the color  buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Modes",
      "type": "topic",
      "url": "/documentation/agl/color-modes"
    },
    "doc://com.apple.agl/documentation/AGL/context-options-and-parameters": {
      "abstract": [
        {
          "text": "Define options and parameters that apply to a specific rendering context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Options and Parameters",
      "type": "topic",
      "url": "/documentation/agl/context-options-and-parameters"
    },
    "doc://com.apple.agl/documentation/AGL/error-codes": {
      "abstract": [
        {
          "text": "Defines the error codes that can be returned by the ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/agl/error-codes"
    },
    "doc://com.apple.agl/documentation/AGL/globally-configured-options": {
      "abstract": [
        {
          "text": "Specify options that apply globally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/globally-configured-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Globally Configured Options",
      "type": "topic",
      "url": "/documentation/agl/globally-configured-options"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-attributes": {
      "abstract": [
        {
          "text": "Define options for managing renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-ids": {
      "abstract": [
        {
          "text": "Define constants that specify hardware and software renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer IDs",
      "type": "topic",
      "url": "/documentation/agl/renderer-ids"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-properties": {
      "abstract": [
        {
          "text": "Specify constants that you can use to query renderer properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Properties",
      "type": "topic",
      "url": "/documentation/agl/renderer-properties"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/#id(F15037)": {
      "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
      "title": "aglGetError",
      "titleInlineContent": [
        {
          "text": "aglGetError",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/#id(F15037)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/bit-depths",
        "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
        "doc://com.apple.agl/documentation/AGL/color-modes",
        "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
        "doc://com.apple.agl/documentation/AGL/error-codes",
        "doc://com.apple.agl/documentation/AGL/globally-configured-options",
        "doc://com.apple.agl/documentation/AGL/renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/renderer-ids",
        "doc://com.apple.agl/documentation/AGL/renderer-properties"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_NONE",
        "doc://com.apple.agl/documentation/AGL/AGL_ALL_RENDERERS",
        "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBA",
        "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER",
        "doc://com.apple.agl/documentation/AGL/AGL_STEREO",
        "doc://com.apple.agl/documentation/AGL/AGL_AUX_BUFFERS",
        "doc://com.apple.agl/documentation/AGL/AGL_RED_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_GREEN_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_BLUE_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ALPHA_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_RED_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_GREEN_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_BLUE_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_ALPHA_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_PIXEL_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_MINIMUM_POLICY",
        "doc://com.apple.agl/documentation/AGL/AGL_MAXIMUM_POLICY",
        "doc://com.apple.agl/documentation/AGL/AGL_OFFSCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_FULLSCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_BUFFERS_ARB",
        "doc://com.apple.agl/documentation/AGL/AGL_SAMPLES_ARB",
        "doc://com.apple.agl/documentation/AGL/AGL_AUX_DEPTH_STENCIL",
        "doc://com.apple.agl/documentation/AGL/AGL_COLOR_FLOAT",
        "doc://com.apple.agl/documentation/AGL/AGL_MULTISAMPLE",
        "doc://com.apple.agl/documentation/AGL/AGL_SUPERSAMPLE",
        "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_ALPHA",
        "doc://com.apple.agl/documentation/AGL/AGL_NONE",
        "doc://com.apple.agl/documentation/AGL/AGL_ALL_RENDERERS",
        "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBA",
        "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER",
        "doc://com.apple.agl/documentation/AGL/AGL_STEREO",
        "doc://com.apple.agl/documentation/AGL/AGL_AUX_BUFFERS",
        "doc://com.apple.agl/documentation/AGL/AGL_RED_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_GREEN_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_BLUE_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ALPHA_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_RED_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_GREEN_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_BLUE_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_ALPHA_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_PIXEL_SIZE",
        "doc://com.apple.agl/documentation/AGL/AGL_MINIMUM_POLICY",
        "doc://com.apple.agl/documentation/AGL/AGL_MAXIMUM_POLICY",
        "doc://com.apple.agl/documentation/AGL/AGL_OFFSCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_FULLSCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_BUFFERS_ARB",
        "doc://com.apple.agl/documentation/AGL/AGL_SAMPLES_ARB",
        "doc://com.apple.agl/documentation/AGL/AGL_AUX_DEPTH_STENCIL",
        "doc://com.apple.agl/documentation/AGL/AGL_COLOR_FLOAT",
        "doc://com.apple.agl/documentation/AGL/AGL_MULTISAMPLE",
        "doc://com.apple.agl/documentation/AGL/AGL_SUPERSAMPLE",
        "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_ALPHA"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_NONE",
                "doc://com.apple.agl/documentation/AGL/AGL_ALL_RENDERERS",
                "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBA",
                "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER",
                "doc://com.apple.agl/documentation/AGL/AGL_STEREO",
                "doc://com.apple.agl/documentation/AGL/AGL_AUX_BUFFERS",
                "doc://com.apple.agl/documentation/AGL/AGL_RED_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_GREEN_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_BLUE_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ALPHA_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_RED_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_GREEN_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_BLUE_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_ALPHA_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_PIXEL_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_MINIMUM_POLICY",
                "doc://com.apple.agl/documentation/AGL/AGL_MAXIMUM_POLICY",
                "doc://com.apple.agl/documentation/AGL/AGL_OFFSCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_FULLSCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_BUFFERS_ARB",
                "doc://com.apple.agl/documentation/AGL/AGL_SAMPLES_ARB",
                "doc://com.apple.agl/documentation/AGL/AGL_AUX_DEPTH_STENCIL",
                "doc://com.apple.agl/documentation/AGL/AGL_COLOR_FLOAT",
                "doc://com.apple.agl/documentation/AGL/AGL_MULTISAMPLE",
                "doc://com.apple.agl/documentation/AGL/AGL_SUPERSAMPLE",
                "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_ALPHA",
                "doc://com.apple.agl/documentation/AGL/AGL_NONE",
                "doc://com.apple.agl/documentation/AGL/AGL_ALL_RENDERERS",
                "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBA",
                "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER",
                "doc://com.apple.agl/documentation/AGL/AGL_STEREO",
                "doc://com.apple.agl/documentation/AGL/AGL_AUX_BUFFERS",
                "doc://com.apple.agl/documentation/AGL/AGL_RED_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_GREEN_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_BLUE_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ALPHA_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_RED_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_GREEN_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_BLUE_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_ALPHA_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_PIXEL_SIZE",
                "doc://com.apple.agl/documentation/AGL/AGL_MINIMUM_POLICY",
                "doc://com.apple.agl/documentation/AGL/AGL_MAXIMUM_POLICY",
                "doc://com.apple.agl/documentation/AGL/AGL_OFFSCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_FULLSCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_BUFFERS_ARB",
                "doc://com.apple.agl/documentation/AGL/AGL_SAMPLES_ARB",
                "doc://com.apple.agl/documentation/AGL/AGL_AUX_DEPTH_STENCIL",
                "doc://com.apple.agl/documentation/AGL/AGL_COLOR_FLOAT",
                "doc://com.apple.agl/documentation/AGL/AGL_MULTISAMPLE",
                "doc://com.apple.agl/documentation/AGL/AGL_SUPERSAMPLE",
                "doc://com.apple.agl/documentation/AGL/AGL_SAMPLE_ALPHA"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/bit-depths",
                "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
                "doc://com.apple.agl/documentation/AGL/color-modes",
                "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
                "doc://com.apple.agl/documentation/AGL/error-codes",
                "doc://com.apple.agl/documentation/AGL/globally-configured-options",
                "doc://com.apple.agl/documentation/AGL/renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/renderer-ids",
                "doc://com.apple.agl/documentation/AGL/renderer-properties"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SAMPLE_BUFFERS_ARB/title",
          "value": "AGL_SAMPLE_BUFFERS_ARB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SAMPLE_BUFFERS_ARB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SAMPLE_BUFFERS_ARB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MINIMUM_POLICY/title",
          "value": "AGL_MINIMUM_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MINIMUM_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MINIMUM_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COLOR_FLOAT/title",
          "value": "AGL_COLOR_FLOAT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COLOR_FLOAT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_COLOR_FLOAT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DOUBLEBUFFER/title",
          "value": "AGL_DOUBLEBUFFER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DOUBLEBUFFER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_DOUBLEBUFFER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBA/title",
          "value": "AGL_RGBA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGBA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_NONE/title",
          "value": "AGL_NONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_NONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_NONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_ALPHA_SIZE/title",
          "value": "AGL_ACCUM_ALPHA_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_ALPHA_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ACCUM_ALPHA_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MULTISAMPLE/title",
          "value": "AGL_MULTISAMPLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MULTISAMPLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MULTISAMPLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_SIZE/title",
          "value": "AGL_BUFFER_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BUFFER_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RED_SIZE/title",
          "value": "AGL_RED_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RED_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RED_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_AUX_DEPTH_STENCIL/title",
          "value": "AGL_AUX_DEPTH_STENCIL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_AUX_DEPTH_STENCIL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_AUX_DEPTH_STENCIL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STENCIL_SIZE/title",
          "value": "AGL_STENCIL_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STENCIL_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_STENCIL_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MAXIMUM_POLICY/title",
          "value": "AGL_MAXIMUM_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MAXIMUM_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MAXIMUM_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_GREEN_SIZE/title",
          "value": "AGL_ACCUM_GREEN_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_GREEN_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ACCUM_GREEN_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_FULLSCREEN/title",
          "value": "AGL_FULLSCREEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_FULLSCREEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_FULLSCREEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ALL_RENDERERS/title",
          "value": "AGL_ALL_RENDERERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ALL_RENDERERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ALL_RENDERERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SUPERSAMPLE/title",
          "value": "AGL_SUPERSAMPLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SUPERSAMPLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SUPERSAMPLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STEREO/title",
          "value": "AGL_STEREO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STEREO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_STEREO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_LEVEL/title",
          "value": "AGL_LEVEL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_LEVEL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_LEVEL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SAMPLES_ARB/title",
          "value": "AGL_SAMPLES_ARB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SAMPLES_ARB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SAMPLES_ARB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_AUX_BUFFERS/title",
          "value": "AGL_AUX_BUFFERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_AUX_BUFFERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_AUX_BUFFERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_RED_SIZE/title",
          "value": "AGL_ACCUM_RED_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_RED_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ACCUM_RED_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SAMPLE_ALPHA/title",
          "value": "AGL_SAMPLE_ALPHA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SAMPLE_ALPHA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SAMPLE_ALPHA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_PIXEL_SIZE/title",
          "value": "AGL_PIXEL_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_PIXEL_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_PIXEL_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_GREEN_SIZE/title",
          "value": "AGL_GREEN_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_GREEN_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_GREEN_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_BLUE_SIZE/title",
          "value": "AGL_ACCUM_BLUE_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_BLUE_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ACCUM_BLUE_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ALPHA_SIZE/title",
          "value": "AGL_ALPHA_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ALPHA_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ALPHA_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BLUE_SIZE/title",
          "value": "AGL_BLUE_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BLUE_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BLUE_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DEPTH_SIZE/title",
          "value": "AGL_DEPTH_SIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DEPTH_SIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_DEPTH_SIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_OFFSCREEN/title",
          "value": "AGL_OFFSCREEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_OFFSCREEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_OFFSCREEN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/buffer-and-renderer-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/buffer-and-renderer-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
