{
  "abstract": [
    {
      "text": "Define constants used to set buffer modes.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL",
        "doc://com.apple.agl/documentation/AGL/AGL-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Buffer Mode Flags"
  },
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL-collection": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl/agl-collection"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER_BIT": {
      "abstract": [
        {
          "text": "A front and back buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_DOUBLEBUFFER_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_DOUBLEBUFFER_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_DOUBLEBUFFER_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_doublebuffer_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MONOSCOPIC_BIT": {
      "abstract": [
        {
          "text": "A left buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MONOSCOPIC_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MONOSCOPIC_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MONOSCOPIC_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_MONOSCOPIC_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_monoscopic_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SINGLEBUFFER_BIT": {
      "abstract": [
        {
          "text": "A front buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SINGLEBUFFER_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SINGLEBUFFER_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SINGLEBUFFER_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_SINGLEBUFFER_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_singlebuffer_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_STEREOSCOPIC_BIT": {
      "abstract": [
        {
          "text": "A left and right buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_STEREOSCOPIC_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_STEREOSCOPIC_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_STEREOSCOPIC_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_STEREOSCOPIC_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_stereoscopic_bit"
    },
    "doc://com.apple.agl/documentation/AGL/bit-depths": {
      "abstract": [
        {
          "text": "Define resolutions for the depth and stencil buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bit Depths",
      "type": "topic",
      "url": "/documentation/agl/bit-depths"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes": {
      "abstract": [
        {
          "text": "Specify attributes used to create a pixel format object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer and Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/buffer-and-renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/color-modes": {
      "abstract": [
        {
          "text": "Specify formats and color channel layout information for the color  buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Modes",
      "type": "topic",
      "url": "/documentation/agl/color-modes"
    },
    "doc://com.apple.agl/documentation/AGL/context-options-and-parameters": {
      "abstract": [
        {
          "text": "Define options and parameters that apply to a specific rendering context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Options and Parameters",
      "type": "topic",
      "url": "/documentation/agl/context-options-and-parameters"
    },
    "doc://com.apple.agl/documentation/AGL/error-codes": {
      "abstract": [
        {
          "text": "Defines the error codes that can be returned by the ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/agl/error-codes"
    },
    "doc://com.apple.agl/documentation/AGL/globally-configured-options": {
      "abstract": [
        {
          "text": "Specify options that apply globally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/globally-configured-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Globally Configured Options",
      "type": "topic",
      "url": "/documentation/agl/globally-configured-options"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-attributes": {
      "abstract": [
        {
          "text": "Define options for managing renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-ids": {
      "abstract": [
        {
          "text": "Define constants that specify hardware and software renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer IDs",
      "type": "topic",
      "url": "/documentation/agl/renderer-ids"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-properties": {
      "abstract": [
        {
          "text": "Specify constants that you can use to query renderer properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Properties",
      "type": "topic",
      "url": "/documentation/agl/renderer-properties"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/#id(F15037)": {
      "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
      "title": "aglGetError",
      "titleInlineContent": [
        {
          "text": "aglGetError",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/#id(F15037)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/bit-depths",
        "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/color-modes",
        "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
        "doc://com.apple.agl/documentation/AGL/error-codes",
        "doc://com.apple.agl/documentation/AGL/globally-configured-options",
        "doc://com.apple.agl/documentation/AGL/renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/renderer-ids",
        "doc://com.apple.agl/documentation/AGL/renderer-properties"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_MONOSCOPIC_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_STEREOSCOPIC_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_SINGLEBUFFER_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_MONOSCOPIC_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_STEREOSCOPIC_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_SINGLEBUFFER_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER_BIT"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_MONOSCOPIC_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_STEREOSCOPIC_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_SINGLEBUFFER_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_MONOSCOPIC_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_STEREOSCOPIC_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_SINGLEBUFFER_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_DOUBLEBUFFER_BIT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/bit-depths",
                "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/color-modes",
                "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
                "doc://com.apple.agl/documentation/AGL/error-codes",
                "doc://com.apple.agl/documentation/AGL/globally-configured-options",
                "doc://com.apple.agl/documentation/AGL/renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/renderer-ids",
                "doc://com.apple.agl/documentation/AGL/renderer-properties"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SINGLEBUFFER_BIT/title",
          "value": "AGL_SINGLEBUFFER_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SINGLEBUFFER_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SINGLEBUFFER_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DOUBLEBUFFER_BIT/title",
          "value": "AGL_DOUBLEBUFFER_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DOUBLEBUFFER_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_DOUBLEBUFFER_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MONOSCOPIC_BIT/title",
          "value": "AGL_MONOSCOPIC_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MONOSCOPIC_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MONOSCOPIC_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STEREOSCOPIC_BIT/title",
          "value": "AGL_STEREOSCOPIC_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STEREOSCOPIC_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_STEREOSCOPIC_BIT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/buffer-mode-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/buffer-mode-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
