{
  "abstract": [
    {
      "text": "Specify formats and color channel layout information for the color  buffer.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL",
        "doc://com.apple.agl/documentation/AGL/AGL-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/color-modes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Color Modes"
  },
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL-collection": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl/agl-collection"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ARGB12121212_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 48 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=47:36, R=35:24, G=23:12, B=11:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ARGB12121212_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ARGB12121212_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ARGB12121212_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_ARGB12121212_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_argb12121212_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ARGB1555_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=15, R=14:10, G=9:5, B=4:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ARGB1555_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ARGB1555_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ARGB1555_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_ARGB1555_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_argb1555_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ARGB16161616_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 64 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=63:48, R=47:32, G=31:16, B=15:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ARGB16161616_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ARGB16161616_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ARGB16161616_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_ARGB16161616_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_argb16161616_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ARGB2101010_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 32 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=31:30 R=29:20, G=19:10, B=9:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ARGB2101010_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ARGB2101010_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ARGB2101010_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_ARGB2101010_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_argb2101010_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ARGB4444_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=15:12, R=11:8, G=7:4, B=3:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ARGB4444_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ARGB4444_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ARGB4444_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_ARGB4444_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_argb4444_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ARGB8888_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 32 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=31:24, R=23:16, G=15:8, B=7:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ARGB8888_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ARGB8888_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ARGB8888_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_ARGB8888_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_argb8888_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BGR233_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies an 8-8 ARGB bits per pixel format and the channels located in the following bits: A=7:0, B=7:6, G=5:3, R=2:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BGR233_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BGR233_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BGR233_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_BGR233_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_bgr233_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BGR233_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8 bits per pixel with an RGB channel layout, and the channels located in the following bits:  B=7:6, G=5:3, R=2:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BGR233_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BGR233_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BGR233_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_BGR233_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_bgr233_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_INDEX16_BIT": {
      "abstract": [
        {
          "text": "Specifies an 16-bit color look up table. (Deprecated)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_INDEX16_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_INDEX16_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_INDEX16_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_INDEX16_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_index16_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_INDEX8_BIT": {
      "abstract": [
        {
          "text": "Specifies an 8-bit color look up table. (Deprecated)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_INDEX8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_INDEX8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_INDEX8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_INDEX8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_index8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8-32 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=7:0 R=29:20, G=19:10, B=9:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB101010_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB101010_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB101010_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb101010_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 32 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=29:20, G=19:10, B=9:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB101010_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB101010_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB101010_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb101010_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB121212_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 48 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=35:24, G=23:12, B=11:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB121212_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB121212_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB121212_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB121212_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb121212_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB161616_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 64 bits per pixel with an RGB channel layout, and the channels located in the following bits:  R=47:32, G=31:16, B=15:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB161616_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB161616_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB161616_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB161616_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb161616_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB332_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies an 8-8 ARGB bits per pixel format and the channels located in the following bits: A=7:0, R=7:5, G=4:2, B=1:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB332_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB332_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB332_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB332_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb332_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB332_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=7:5, G=4:2, B=1:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB332_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB332_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB332_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB332_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb332_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB444_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8-16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=7:0, R=11:8, G=7:4, B=3:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB444_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB444_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB444_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB444_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb444_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB444_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 16 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=11:8, G=7:4, B=3:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB444_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB444_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB444_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB444_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb444_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB555_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8-16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=7:0, R=14:10, G=9:5, B=4:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB555_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB555_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB555_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB555_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb555_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB555_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 16 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=14:10, G=9:5, B=4:0. The top bit is not used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB555_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB555_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB555_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB555_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb555_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB565_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8-16 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=7:0, R=15:11, G=10:5, B=4:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB565_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB565_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB565_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB565_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb565_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB565_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 16 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=15:11, G=10:5, B=4:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB565_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB565_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB565_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB565_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb565_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB888_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8-32 bits per pixel with an ARGB channel layout, and the channels located in the following bits: A=7:0, R=23:16, G=15:8, B=7:0",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB888_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB888_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB888_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB888_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb888_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB888_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 32 bits per pixel with an RGB channel layout, and the channels located in the following bits: R=23:16, G=15:8, B=7:0; R, G, and B take 1 byte each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB888_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB888_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB888_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB888_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb888_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB8_A8_BIT": {
      "abstract": [
        {
          "text": "Specifies an 8-8 ARGB bits per pixel format and the channels located in the following bits: A=7:0, RGB=7:0, inverse color map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB8_A8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB8_A8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB8_A8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB8_A8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb8_a8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGB8_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 8 bits per pixel with an RGB channel layout:  RGB=7:0, inverse color map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGB8_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGB8_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGB8_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGB8_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgb8_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT128_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 128 bits per pixel with an ARGB channel layout, IEEE floating point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGBAFLOAT128_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT128_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGBAFLOAT128_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGBAFLOAT128_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgbafloat128_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT256_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 256 bits per pixel with an ARGB channel layout, IEEE double values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGBAFLOAT256_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT256_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGBAFLOAT256_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGBAFLOAT256_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgbafloat256_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT64_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 64 bits per pixel with an ARGB channel layout, half-floating point values. (A half-float is a 16-bit floating-point value.)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGBAFLOAT64_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT64_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGBAFLOAT64_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGBAFLOAT64_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgbafloat64_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT128_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 128 bits per pixel with an RGB channel layout, IEEE floating point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGBFLOAT128_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT128_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGBFLOAT128_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGBFLOAT128_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgbfloat128_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT256_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 256 bits per pixel with an RGB channel layout, IEEE double values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGBFLOAT256_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT256_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGBFLOAT256_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGBFLOAT256_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgbfloat256_bit"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT64_BIT": {
      "abstract": [
        {
          "text": "Specifies a format that has 64 bits per pixel with an RGB channel layout, half-floating point values. (A half-float is a 16-bit floating-point value.)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RGBFLOAT64_BIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT64_BIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RGBFLOAT64_BIT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RGBFLOAT64_BIT",
      "type": "topic",
      "url": "/documentation/agl/agl_rgbfloat64_bit"
    },
    "doc://com.apple.agl/documentation/AGL/bit-depths": {
      "abstract": [
        {
          "text": "Define resolutions for the depth and stencil buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bit Depths",
      "type": "topic",
      "url": "/documentation/agl/bit-depths"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes": {
      "abstract": [
        {
          "text": "Specify attributes used to create a pixel format object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer and Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/buffer-and-renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-mode-flags": {
      "abstract": [
        {
          "text": "Define constants used to set buffer modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Mode Flags",
      "type": "topic",
      "url": "/documentation/agl/buffer-mode-flags"
    },
    "doc://com.apple.agl/documentation/AGL/context-options-and-parameters": {
      "abstract": [
        {
          "text": "Define options and parameters that apply to a specific rendering context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Options and Parameters",
      "type": "topic",
      "url": "/documentation/agl/context-options-and-parameters"
    },
    "doc://com.apple.agl/documentation/AGL/error-codes": {
      "abstract": [
        {
          "text": "Defines the error codes that can be returned by the ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/agl/error-codes"
    },
    "doc://com.apple.agl/documentation/AGL/globally-configured-options": {
      "abstract": [
        {
          "text": "Specify options that apply globally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/globally-configured-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Globally Configured Options",
      "type": "topic",
      "url": "/documentation/agl/globally-configured-options"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-attributes": {
      "abstract": [
        {
          "text": "Define options for managing renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-ids": {
      "abstract": [
        {
          "text": "Define constants that specify hardware and software renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer IDs",
      "type": "topic",
      "url": "/documentation/agl/renderer-ids"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-properties": {
      "abstract": [
        {
          "text": "Specify constants that you can use to query renderer properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Properties",
      "type": "topic",
      "url": "/documentation/agl/renderer-properties"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/#id(F15037)": {
      "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
      "title": "aglGetError",
      "titleInlineContent": [
        {
          "text": "aglGetError",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/#id(F15037)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/bit-depths",
        "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
        "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
        "doc://com.apple.agl/documentation/AGL/error-codes",
        "doc://com.apple.agl/documentation/AGL/globally-configured-options",
        "doc://com.apple.agl/documentation/AGL/renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/renderer-ids",
        "doc://com.apple.agl/documentation/AGL/renderer-properties"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_RGB8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB8_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_BGR233_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_BGR233_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB332_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB332_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB444_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB4444_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB444_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB555_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB1555_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB555_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB565_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB565_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB888_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB8888_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB888_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB2101010_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB121212_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB12121212_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB161616_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB16161616_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_INDEX8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_INDEX16_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT64_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT64_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT128_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT128_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT256_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT256_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB8_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_BGR233_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_BGR233_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB332_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB332_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB444_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB4444_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB444_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB555_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB1555_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB555_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB565_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB565_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB888_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB8888_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB888_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB2101010_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_A8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB121212_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB12121212_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGB161616_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_ARGB16161616_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_INDEX8_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_INDEX16_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT64_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT64_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT128_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT128_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT256_BIT",
        "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT256_BIT"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_RGB8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB8_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_BGR233_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_BGR233_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB332_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB332_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB444_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB4444_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB444_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB555_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB1555_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB555_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB565_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB565_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB888_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB8888_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB888_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB2101010_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB121212_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB12121212_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB161616_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB16161616_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_INDEX8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_INDEX16_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT64_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT64_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT128_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT128_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT256_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT256_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB8_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_BGR233_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_BGR233_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB332_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB332_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB444_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB4444_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB444_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB555_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB1555_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB555_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB565_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB565_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB888_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB8888_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB888_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB2101010_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB101010_A8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB121212_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB12121212_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGB161616_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_ARGB16161616_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_INDEX8_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_INDEX16_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT64_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT64_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT128_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT128_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBFLOAT256_BIT",
                "doc://com.apple.agl/documentation/AGL/AGL_RGBAFLOAT256_BIT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/bit-depths",
                "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
                "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
                "doc://com.apple.agl/documentation/AGL/error-codes",
                "doc://com.apple.agl/documentation/AGL/globally-configured-options",
                "doc://com.apple.agl/documentation/AGL/renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/renderer-ids",
                "doc://com.apple.agl/documentation/AGL/renderer-properties"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB16161616_BIT/title",
          "value": "AGL_ARGB16161616_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB16161616_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ARGB16161616_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBAFLOAT256_BIT/title",
          "value": "AGL_RGBAFLOAT256_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBAFLOAT256_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGBAFLOAT256_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB332_A8_BIT/title",
          "value": "AGL_RGB332_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB332_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB332_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB1555_BIT/title",
          "value": "AGL_ARGB1555_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB1555_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ARGB1555_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBAFLOAT128_BIT/title",
          "value": "AGL_RGBAFLOAT128_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBAFLOAT128_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGBAFLOAT128_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB101010_BIT/title",
          "value": "AGL_RGB101010_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB101010_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB101010_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB161616_BIT/title",
          "value": "AGL_RGB161616_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB161616_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB161616_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB4444_BIT/title",
          "value": "AGL_ARGB4444_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB4444_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ARGB4444_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB565_A8_BIT/title",
          "value": "AGL_RGB565_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB565_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB565_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB12121212_BIT/title",
          "value": "AGL_ARGB12121212_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB12121212_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ARGB12121212_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB565_BIT/title",
          "value": "AGL_RGB565_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB565_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB565_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_INDEX16_BIT/title",
          "value": "AGL_INDEX16_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_INDEX16_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_INDEX16_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBFLOAT128_BIT/title",
          "value": "AGL_RGBFLOAT128_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBFLOAT128_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGBFLOAT128_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB888_A8_BIT/title",
          "value": "AGL_RGB888_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB888_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB888_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BGR233_A8_BIT/title",
          "value": "AGL_BGR233_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BGR233_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BGR233_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB8_BIT/title",
          "value": "AGL_RGB8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB121212_BIT/title",
          "value": "AGL_RGB121212_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB121212_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB121212_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB8888_BIT/title",
          "value": "AGL_ARGB8888_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB8888_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ARGB8888_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBFLOAT64_BIT/title",
          "value": "AGL_RGBFLOAT64_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBFLOAT64_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGBFLOAT64_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB888_BIT/title",
          "value": "AGL_RGB888_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB888_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB888_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB555_A8_BIT/title",
          "value": "AGL_RGB555_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB555_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB555_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB101010_A8_BIT/title",
          "value": "AGL_RGB101010_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB101010_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB101010_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB444_BIT/title",
          "value": "AGL_RGB444_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB444_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB444_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BGR233_BIT/title",
          "value": "AGL_BGR233_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BGR233_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BGR233_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB8_A8_BIT/title",
          "value": "AGL_RGB8_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB8_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB8_A8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBAFLOAT64_BIT/title",
          "value": "AGL_RGBAFLOAT64_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBAFLOAT64_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGBAFLOAT64_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBFLOAT256_BIT/title",
          "value": "AGL_RGBFLOAT256_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGBFLOAT256_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGBFLOAT256_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_INDEX8_BIT/title",
          "value": "AGL_INDEX8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_INDEX8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_INDEX8_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB332_BIT/title",
          "value": "AGL_RGB332_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB332_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB332_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB2101010_BIT/title",
          "value": "AGL_ARGB2101010_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ARGB2101010_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ARGB2101010_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB555_BIT/title",
          "value": "AGL_RGB555_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB555_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB555_BIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB444_A8_BIT/title",
          "value": "AGL_RGB444_A8_BIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RGB444_A8_BIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RGB444_A8_BIT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/color-modes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/color-modes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
