{
  "abstract": [
    {
      "text": "Defines the error codes that can be returned by the ",
      "type": "text"
    },
    {
      "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " function.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL",
        "doc://com.apple.agl/documentation/AGL/AGL-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/error-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error Codes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Unlike many Carbon APIs, AGL functions don’t return result codes for specific error conditions. Instead, AGL functions that fail either return ",
              "type": "text"
            },
            {
              "code": "GL_FALSE",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": ". You can find out the specific nature of the error by calling the function ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which returns the appropriate error code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL-collection": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl/agl-collection"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_ALLOC": {
      "abstract": [
        {
          "text": "Memory allocation failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_ALLOC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_ALLOC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_ALLOC"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_ALLOC",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_alloc"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_ATTRIBUTE": {
      "abstract": [
        {
          "text": "Invalid pixel format attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_ATTRIBUTE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_ATTRIBUTE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_ATTRIBUTE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_ATTRIBUTE",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_attribute"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONNECTION": {
      "abstract": [
        {
          "text": "Unable to connect to the window server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_CONNECTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONNECTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_CONNECTION"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_CONNECTION",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_connection"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONTEXT": {
      "abstract": [
        {
          "text": "Invalid rendering context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_CONTEXT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONTEXT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_CONTEXT"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_CONTEXT",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_context"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_DRAWABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_DRAWABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_DRAWABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_DRAWABLE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_DRAWABLE",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_drawable"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_ENUM": {
      "abstract": [
        {
          "text": "Invalid enumerant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_ENUM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_ENUM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_ENUM"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_ENUM",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_enum"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_FULLSCREEN": {
      "abstract": [
        {
          "text": "Invalid full-screen drawable object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_FULLSCREEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_FULLSCREEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_FULLSCREEN"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_FULLSCREEN",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_fullscreen"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_GDEV": {
      "abstract": [
        {
          "text": "Invalid graphics device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_GDEV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_GDEV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_GDEV"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_GDEV",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_gdev"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_MATCH": {
      "abstract": [
        {
          "text": "Invalid share rendering context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_MATCH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_MATCH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_MATCH"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_MATCH",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_match"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_MODULE": {
      "abstract": [
        {
          "text": "Invalid code module.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_MODULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_MODULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_MODULE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_MODULE",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_module"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_OFFSCREEN": {
      "abstract": [
        {
          "text": "Invalid offscreen drawable object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_OFFSCREEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_OFFSCREEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_OFFSCREEN"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_OFFSCREEN",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_offscreen"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_PIXELFMT": {
      "abstract": [
        {
          "text": "Invalid pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_PIXELFMT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_PIXELFMT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_PIXELFMT"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_PIXELFMT",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_pixelfmt"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_POINTER": {
      "abstract": [
        {
          "text": "Invalid pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_POINTER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_POINTER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_POINTER"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_POINTER",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_pointer"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_PROPERTY": {
      "abstract": [
        {
          "text": "Invalid renderer property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_PROPERTY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_PROPERTY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_PROPERTY"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_PROPERTY",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_property"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_RENDINFO": {
      "abstract": [
        {
          "text": "Invalid renderer info.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_RENDINFO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_RENDINFO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_RENDINFO"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_RENDINFO",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_rendinfo"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_STATE": {
      "abstract": [
        {
          "text": "Invalid rendering context state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_STATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_STATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_STATE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_STATE",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_state"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_VALUE": {
      "abstract": [
        {
          "text": "Invalid numerical value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_VALUE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_VALUE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_VALUE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_VALUE",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_value"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BAD_WINDOW": {
      "abstract": [
        {
          "text": "Invalid window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BAD_WINDOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BAD_WINDOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BAD_WINDOW"
        }
      ],
      "role": "symbol",
      "title": "AGL_BAD_WINDOW",
      "type": "topic",
      "url": "/documentation/agl/agl_bad_window"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_NO_ERROR": {
      "abstract": [
        {
          "text": "No error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_NO_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_NO_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_NO_ERROR"
        }
      ],
      "role": "symbol",
      "title": "AGL_NO_ERROR",
      "type": "topic",
      "url": "/documentation/agl/agl_no_error"
    },
    "doc://com.apple.agl/documentation/AGL/bit-depths": {
      "abstract": [
        {
          "text": "Define resolutions for the depth and stencil buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bit Depths",
      "type": "topic",
      "url": "/documentation/agl/bit-depths"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes": {
      "abstract": [
        {
          "text": "Specify attributes used to create a pixel format object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer and Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/buffer-and-renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-mode-flags": {
      "abstract": [
        {
          "text": "Define constants used to set buffer modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Mode Flags",
      "type": "topic",
      "url": "/documentation/agl/buffer-mode-flags"
    },
    "doc://com.apple.agl/documentation/AGL/color-modes": {
      "abstract": [
        {
          "text": "Specify formats and color channel layout information for the color  buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Modes",
      "type": "topic",
      "url": "/documentation/agl/color-modes"
    },
    "doc://com.apple.agl/documentation/AGL/context-options-and-parameters": {
      "abstract": [
        {
          "text": "Define options and parameters that apply to a specific rendering context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Options and Parameters",
      "type": "topic",
      "url": "/documentation/agl/context-options-and-parameters"
    },
    "doc://com.apple.agl/documentation/AGL/globally-configured-options": {
      "abstract": [
        {
          "text": "Specify options that apply globally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/globally-configured-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Globally Configured Options",
      "type": "topic",
      "url": "/documentation/agl/globally-configured-options"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-attributes": {
      "abstract": [
        {
          "text": "Define options for managing renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-ids": {
      "abstract": [
        {
          "text": "Define constants that specify hardware and software renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer IDs",
      "type": "topic",
      "url": "/documentation/agl/renderer-ids"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-properties": {
      "abstract": [
        {
          "text": "Specify constants that you can use to query renderer properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Properties",
      "type": "topic",
      "url": "/documentation/agl/renderer-properties"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/#id(F15037)": {
      "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
      "title": "aglGetError",
      "titleInlineContent": [
        {
          "text": "aglGetError",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/#id(F15037)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/bit-depths",
        "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
        "doc://com.apple.agl/documentation/AGL/color-modes",
        "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
        "doc://com.apple.agl/documentation/AGL/globally-configured-options",
        "doc://com.apple.agl/documentation/AGL/renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/renderer-ids",
        "doc://com.apple.agl/documentation/AGL/renderer-properties"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_NO_ERROR",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_ATTRIBUTE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_PROPERTY",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_PIXELFMT",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_RENDINFO",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONTEXT",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_DRAWABLE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_GDEV",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_STATE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_VALUE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_MATCH",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_ENUM",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_OFFSCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_FULLSCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_WINDOW",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_POINTER",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_MODULE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_ALLOC",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONNECTION",
        "doc://com.apple.agl/documentation/AGL/AGL_NO_ERROR",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_ATTRIBUTE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_PROPERTY",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_PIXELFMT",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_RENDINFO",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONTEXT",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_DRAWABLE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_GDEV",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_STATE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_VALUE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_MATCH",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_ENUM",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_OFFSCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_FULLSCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_WINDOW",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_POINTER",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_MODULE",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_ALLOC",
        "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONNECTION"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_NO_ERROR",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_ATTRIBUTE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_PROPERTY",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_PIXELFMT",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_RENDINFO",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONTEXT",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_DRAWABLE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_GDEV",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_STATE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_VALUE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_MATCH",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_ENUM",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_OFFSCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_FULLSCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_WINDOW",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_POINTER",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_MODULE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_ALLOC",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONNECTION",
                "doc://com.apple.agl/documentation/AGL/AGL_NO_ERROR",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_ATTRIBUTE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_PROPERTY",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_PIXELFMT",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_RENDINFO",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONTEXT",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_DRAWABLE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_GDEV",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_STATE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_VALUE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_MATCH",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_ENUM",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_OFFSCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_FULLSCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_WINDOW",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_POINTER",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_MODULE",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_ALLOC",
                "doc://com.apple.agl/documentation/AGL/AGL_BAD_CONNECTION"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/bit-depths",
                "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
                "doc://com.apple.agl/documentation/AGL/color-modes",
                "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
                "doc://com.apple.agl/documentation/AGL/globally-configured-options",
                "doc://com.apple.agl/documentation/AGL/renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/renderer-ids",
                "doc://com.apple.agl/documentation/AGL/renderer-properties"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_OFFSCREEN/title",
          "value": "AGL_BAD_OFFSCREEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_OFFSCREEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_OFFSCREEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_FULLSCREEN/title",
          "value": "AGL_BAD_FULLSCREEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_FULLSCREEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_FULLSCREEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_POINTER/title",
          "value": "AGL_BAD_POINTER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_POINTER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_POINTER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_RENDINFO/title",
          "value": "AGL_BAD_RENDINFO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_RENDINFO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_RENDINFO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_MODULE/title",
          "value": "AGL_BAD_MODULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_MODULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_MODULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_MATCH/title",
          "value": "AGL_BAD_MATCH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_MATCH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_MATCH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_ATTRIBUTE/title",
          "value": "AGL_BAD_ATTRIBUTE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_ATTRIBUTE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_ATTRIBUTE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_GDEV/title",
          "value": "AGL_BAD_GDEV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_GDEV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_GDEV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_CONNECTION/title",
          "value": "AGL_BAD_CONNECTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_CONNECTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_CONNECTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_ALLOC/title",
          "value": "AGL_BAD_ALLOC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_ALLOC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_ALLOC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_NO_ERROR/title",
          "value": "AGL_NO_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_NO_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_NO_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_VALUE/title",
          "value": "AGL_BAD_VALUE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_VALUE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_VALUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_PROPERTY/title",
          "value": "AGL_BAD_PROPERTY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_PROPERTY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_PROPERTY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_ENUM/title",
          "value": "AGL_BAD_ENUM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_ENUM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_ENUM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_DRAWABLE/title",
          "value": "AGL_BAD_DRAWABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_DRAWABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_DRAWABLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_WINDOW/title",
          "value": "AGL_BAD_WINDOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_WINDOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_WINDOW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_STATE/title",
          "value": "AGL_BAD_STATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_STATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_STATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_CONTEXT/title",
          "value": "AGL_BAD_CONTEXT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_CONTEXT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_CONTEXT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_PIXELFMT/title",
          "value": "AGL_BAD_PIXELFMT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BAD_PIXELFMT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BAD_PIXELFMT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/error-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/error-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
