{
  "abstract": [
    {
      "text": "Specify constants that you can use to query renderer properties.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL",
        "doc://com.apple.agl/documentation/AGL/AGL-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/renderer-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Renderer Properties"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can pass these constants to the function ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to find out the property value for a specific renderer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL-collection": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl/agl-collection"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_MODES": {
      "abstract": [
        {
          "text": "The associated value can be a bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of any of the constants specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_MODES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_MODES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ACCUM_MODES"
        }
      ],
      "role": "symbol",
      "title": "AGL_ACCUM_MODES",
      "type": "topic",
      "url": "/documentation/agl/agl_accum_modes"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES": {
      "abstract": [
        {
          "text": "The associated value can be a bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of the any of the constants specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_MODES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BUFFER_MODES"
        }
      ],
      "role": "symbol",
      "title": "AGL_BUFFER_MODES",
      "type": "topic",
      "url": "/documentation/agl/agl_buffer_modes"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES": {
      "abstract": [
        {
          "text": "The associated value can be a bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of any of the constants specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_COLOR_MODES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_COLOR_MODES"
        }
      ],
      "role": "symbol",
      "title": "AGL_COLOR_MODES",
      "type": "topic",
      "url": "/documentation/agl/agl_color_modes"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES": {
      "abstract": [
        {
          "text": "The associated value can be the bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of any of the constants specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_DEPTH_MODES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_DEPTH_MODES"
        }
      ],
      "role": "symbol",
      "title": "AGL_DEPTH_MODES",
      "type": "topic",
      "url": "/documentation/agl/agl_depth_modes"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MAX_AUX_BUFFERS": {
      "abstract": [
        {
          "text": "The associated value is the maximum number of auxiliary buffers that can be supported by the renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MAX_AUX_BUFFERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MAX_AUX_BUFFERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MAX_AUX_BUFFERS"
        }
      ],
      "role": "symbol",
      "title": "AGL_MAX_AUX_BUFFERS",
      "type": "topic",
      "url": "/documentation/agl/agl_max_aux_buffers"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL": {
      "abstract": [
        {
          "text": "The associated value specifies the maximum overlay buffer level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MAX_LEVEL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MAX_LEVEL"
        }
      ],
      "role": "symbol",
      "title": "AGL_MAX_LEVEL",
      "type": "topic",
      "url": "/documentation/agl/agl_max_level"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL": {
      "abstract": [
        {
          "text": "The associated value specifies the minimum overlay buffer level. Negative values indicate an underlay buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MIN_LEVEL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MIN_LEVEL"
        }
      ],
      "role": "symbol",
      "title": "AGL_MIN_LEVEL",
      "type": "topic",
      "url": "/documentation/agl/agl_min_level"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_COUNT": {
      "abstract": [
        {
          "text": "The associated value is the number of renderers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_COUNT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_COUNT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_COUNT"
        }
      ],
      "role": "symbol",
      "title": "AGL_RENDERER_COUNT",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_count"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_MODES": {
      "abstract": [
        {
          "text": "The associated value can be the bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of any of the constants specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_STENCIL_MODES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_MODES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_STENCIL_MODES"
        }
      ],
      "role": "symbol",
      "title": "AGL_STENCIL_MODES",
      "type": "topic",
      "url": "/documentation/agl/agl_stencil_modes"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_TEXTURE_MEMORY": {
      "abstract": [
        {
          "text": "The associated value is the amount of texture memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_TEXTURE_MEMORY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_TEXTURE_MEMORY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_TEXTURE_MEMORY"
        }
      ],
      "role": "symbol",
      "title": "AGL_TEXTURE_MEMORY",
      "type": "topic",
      "url": "/documentation/agl/agl_texture_memory"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_VIDEO_MEMORY": {
      "abstract": [
        {
          "text": "The associated value is the amount of video memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_VIDEO_MEMORY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_VIDEO_MEMORY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_VIDEO_MEMORY"
        }
      ],
      "role": "symbol",
      "title": "AGL_VIDEO_MEMORY",
      "type": "topic",
      "url": "/documentation/agl/agl_video_memory"
    },
    "doc://com.apple.agl/documentation/AGL/bit-depths": {
      "abstract": [
        {
          "text": "Define resolutions for the depth and stencil buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bit Depths",
      "type": "topic",
      "url": "/documentation/agl/bit-depths"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes": {
      "abstract": [
        {
          "text": "Specify attributes used to create a pixel format object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer and Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/buffer-and-renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-mode-flags": {
      "abstract": [
        {
          "text": "Define constants used to set buffer modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Mode Flags",
      "type": "topic",
      "url": "/documentation/agl/buffer-mode-flags"
    },
    "doc://com.apple.agl/documentation/AGL/color-modes": {
      "abstract": [
        {
          "text": "Specify formats and color channel layout information for the color  buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Modes",
      "type": "topic",
      "url": "/documentation/agl/color-modes"
    },
    "doc://com.apple.agl/documentation/AGL/context-options-and-parameters": {
      "abstract": [
        {
          "text": "Define options and parameters that apply to a specific rendering context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Options and Parameters",
      "type": "topic",
      "url": "/documentation/agl/context-options-and-parameters"
    },
    "doc://com.apple.agl/documentation/AGL/error-codes": {
      "abstract": [
        {
          "text": "Defines the error codes that can be returned by the ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/agl/error-codes"
    },
    "doc://com.apple.agl/documentation/AGL/globally-configured-options": {
      "abstract": [
        {
          "text": "Specify options that apply globally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/globally-configured-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Globally Configured Options",
      "type": "topic",
      "url": "/documentation/agl/globally-configured-options"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-attributes": {
      "abstract": [
        {
          "text": "Define options for managing renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-ids": {
      "abstract": [
        {
          "text": "Define constants that specify hardware and software renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer IDs",
      "type": "topic",
      "url": "/documentation/agl/renderer-ids"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/#id(F15037)": {
      "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
      "title": "aglGetError",
      "titleInlineContent": [
        {
          "text": "aglGetError",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/#id(F15037)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/bit-depths",
        "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
        "doc://com.apple.agl/documentation/AGL/color-modes",
        "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
        "doc://com.apple.agl/documentation/AGL/error-codes",
        "doc://com.apple.agl/documentation/AGL/globally-configured-options",
        "doc://com.apple.agl/documentation/AGL/renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/renderer-ids"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_MAX_AUX_BUFFERS",
        "doc://com.apple.agl/documentation/AGL/AGL_VIDEO_MEMORY",
        "doc://com.apple.agl/documentation/AGL/AGL_TEXTURE_MEMORY",
        "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_COUNT",
        "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL",
        "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_MODES",
        "doc://com.apple.agl/documentation/AGL/AGL_MAX_AUX_BUFFERS",
        "doc://com.apple.agl/documentation/AGL/AGL_VIDEO_MEMORY",
        "doc://com.apple.agl/documentation/AGL/AGL_TEXTURE_MEMORY",
        "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_COUNT"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_MAX_AUX_BUFFERS",
                "doc://com.apple.agl/documentation/AGL/AGL_VIDEO_MEMORY",
                "doc://com.apple.agl/documentation/AGL/AGL_TEXTURE_MEMORY",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_COUNT",
                "doc://com.apple.agl/documentation/AGL/AGL_BUFFER_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_MIN_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_MAX_LEVEL",
                "doc://com.apple.agl/documentation/AGL/AGL_COLOR_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCUM_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_DEPTH_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_STENCIL_MODES",
                "doc://com.apple.agl/documentation/AGL/AGL_MAX_AUX_BUFFERS",
                "doc://com.apple.agl/documentation/AGL/AGL_VIDEO_MEMORY",
                "doc://com.apple.agl/documentation/AGL/AGL_TEXTURE_MEMORY",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_COUNT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/bit-depths",
                "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
                "doc://com.apple.agl/documentation/AGL/color-modes",
                "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
                "doc://com.apple.agl/documentation/AGL/error-codes",
                "doc://com.apple.agl/documentation/AGL/globally-configured-options",
                "doc://com.apple.agl/documentation/AGL/renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/renderer-ids"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DEPTH_MODES/title",
          "value": "AGL_DEPTH_MODES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_DEPTH_MODES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_DEPTH_MODES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_MODES/title",
          "value": "AGL_BUFFER_MODES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BUFFER_MODES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BUFFER_MODES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COLOR_MODES/title",
          "value": "AGL_COLOR_MODES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COLOR_MODES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_COLOR_MODES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_MODES/title",
          "value": "AGL_ACCUM_MODES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCUM_MODES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ACCUM_MODES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RENDERER_COUNT/title",
          "value": "AGL_RENDERER_COUNT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RENDERER_COUNT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RENDERER_COUNT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_VIDEO_MEMORY/title",
          "value": "AGL_VIDEO_MEMORY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_VIDEO_MEMORY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_VIDEO_MEMORY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MAX_LEVEL/title",
          "value": "AGL_MAX_LEVEL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MAX_LEVEL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MAX_LEVEL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MIN_LEVEL/title",
          "value": "AGL_MIN_LEVEL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MIN_LEVEL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MIN_LEVEL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MAX_AUX_BUFFERS/title",
          "value": "AGL_MAX_AUX_BUFFERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MAX_AUX_BUFFERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MAX_AUX_BUFFERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_TEXTURE_MEMORY/title",
          "value": "AGL_TEXTURE_MEMORY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_TEXTURE_MEMORY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_TEXTURE_MEMORY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STENCIL_MODES/title",
          "value": "AGL_STENCIL_MODES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_STENCIL_MODES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_STENCIL_MODES"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/renderer-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/renderer-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
