{
  "abstract": [
    {
      "text": "Define constants that specify hardware and software renderers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL",
        "doc://com.apple.agl/documentation/AGL/AGL-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/renderer-ids"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Renderer IDs"
  },
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL-collection": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl/agl-collection"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_APPLE_SW_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_APPLE_SW_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_APPLE_SW_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_APPLE_SW_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_apple_sw_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_8500_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_ATI_RADEON_8500_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_8500_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_ATI_RADEON_8500_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_ati_radeon_8500_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_9700_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_ATI_RADEON_9700_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_9700_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_ATI_RADEON_9700_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_ati_radeon_9700_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_ATI_RADEON_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_ATI_RADEON_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_ati_radeon_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_X1000_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_ATI_RADEON_X1000_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_X1000_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_ATI_RADEON_X1000_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_ati_radeon_x1000_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_X2000_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_ATI_RADEON_X2000_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_X2000_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_ATI_RADEON_X2000_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_ati_radeon_x2000_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RAGE_128_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_ATI_RAGE_128_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RAGE_128_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_ATI_RAGE_128_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_ati_rage_128_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RAGE_PRO_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_ATI_RAGE_PRO_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RAGE_PRO_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_ATI_RAGE_PRO_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_ati_rage_pro_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_GENERIC_FLOAT_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_GENERIC_FLOAT_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_GENERIC_FLOAT_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_GENERIC_FLOAT_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_generic_float_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_GENERIC_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_GENERIC_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_GENERIC_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_GENERIC_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_generic_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_INTEL_900_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_INTEL_900_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_INTEL_900_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_INTEL_900_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_intel_900_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_INTEL_X3100_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_INTEL_X3100_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_INTEL_X3100_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_INTEL_X3100_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_intel_x3100_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_MESA_3DFX_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_MESA_3DFX_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_MESA_3DFX_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_MESA_3DFX_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_mesa_3dfx_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_2MX_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_NVIDIA_GEFORCE_2MX_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_2MX_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_NVIDIA_GEFORCE_2MX_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_nvidia_geforce_2mx_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_3_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_NVIDIA_GEFORCE_3_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_3_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_NVIDIA_GEFORCE_3_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_nvidia_geforce_3_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_8XXX_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_NVIDIA_GEFORCE_8XXX_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_8XXX_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_NVIDIA_GEFORCE_8XXX_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_nvidia_geforce_8xxx_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_FX_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_NVIDIA_GEFORCE_FX_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_FX_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_NVIDIA_GEFORCE_FX_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_nvidia_geforce_fx_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_VT_BLADE_XP2_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_VT_BLADE_XP2_ID"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_VT_BLADE_XP2_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AGL_RENDERER_VT_BLADE_XP2_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_vt_blade_xp2_id"
    },
    "doc://com.apple.agl/documentation/AGL/bit-depths": {
      "abstract": [
        {
          "text": "Define resolutions for the depth and stencil buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bit Depths",
      "type": "topic",
      "url": "/documentation/agl/bit-depths"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes": {
      "abstract": [
        {
          "text": "Specify attributes used to create a pixel format object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer and Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/buffer-and-renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-mode-flags": {
      "abstract": [
        {
          "text": "Define constants used to set buffer modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Mode Flags",
      "type": "topic",
      "url": "/documentation/agl/buffer-mode-flags"
    },
    "doc://com.apple.agl/documentation/AGL/color-modes": {
      "abstract": [
        {
          "text": "Specify formats and color channel layout information for the color  buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Modes",
      "type": "topic",
      "url": "/documentation/agl/color-modes"
    },
    "doc://com.apple.agl/documentation/AGL/context-options-and-parameters": {
      "abstract": [
        {
          "text": "Define options and parameters that apply to a specific rendering context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Options and Parameters",
      "type": "topic",
      "url": "/documentation/agl/context-options-and-parameters"
    },
    "doc://com.apple.agl/documentation/AGL/error-codes": {
      "abstract": [
        {
          "text": "Defines the error codes that can be returned by the ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/agl/error-codes"
    },
    "doc://com.apple.agl/documentation/AGL/globally-configured-options": {
      "abstract": [
        {
          "text": "Specify options that apply globally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/globally-configured-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Globally Configured Options",
      "type": "topic",
      "url": "/documentation/agl/globally-configured-options"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-attributes": {
      "abstract": [
        {
          "text": "Define options for managing renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-properties": {
      "abstract": [
        {
          "text": "Specify constants that you can use to query renderer properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Properties",
      "type": "topic",
      "url": "/documentation/agl/renderer-properties"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/#id(F15037)": {
      "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
      "title": "aglGetError",
      "titleInlineContent": [
        {
          "text": "aglGetError",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/#id(F15037)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/bit-depths",
        "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
        "doc://com.apple.agl/documentation/AGL/color-modes",
        "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
        "doc://com.apple.agl/documentation/AGL/error-codes",
        "doc://com.apple.agl/documentation/AGL/globally-configured-options",
        "doc://com.apple.agl/documentation/AGL/renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/renderer-properties"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_GENERIC_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_GENERIC_FLOAT_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_APPLE_SW_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RAGE_128_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_X2000_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RAGE_PRO_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_8500_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_9700_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ATI_RADEON_X1000_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_2MX_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_3_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_FX_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_NVIDIA_GEFORCE_8XXX_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_VT_BLADE_XP2_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_INTEL_900_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_INTEL_X3100_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_MESA_3DFX_ID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/bit-depths",
                "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
                "doc://com.apple.agl/documentation/AGL/color-modes",
                "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
                "doc://com.apple.agl/documentation/AGL/error-codes",
                "doc://com.apple.agl/documentation/AGL/globally-configured-options",
                "doc://com.apple.agl/documentation/AGL/renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/renderer-properties"
              ],
              "title": "Constants"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/renderer-ids"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/renderer-ids"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
