{
  "abstract": [
    {
      "text": "Define options for managing renderers.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.agl/documentation/AGL",
        "doc://com.apple.agl/documentation/AGL/AGL-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL/renderer-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Renderer Attributes"
  },
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL-collection": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl/agl-collection"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ACCELERATED": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array,  specifies renderers that are attached to a hardware accelerated graphics device. It is usually impossible to support more than one accelerated graphics device, because typically when a window spans more than one device, OpenGL uses the software renderer. You can pass this constant to the function ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to find out whether a particular renderer is hardware accelerated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ACCELERATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ACCELERATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ACCELERATED"
        }
      ],
      "role": "symbol",
      "title": "AGL_ACCELERATED",
      "type": "topic",
      "url": "/documentation/agl/agl_accelerated"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_BACKING_STORE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_BACKING_STORE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_BACKING_STORE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_BACKING_STORE"
        }
      ],
      "role": "symbol",
      "title": "AGL_BACKING_STORE",
      "type": "topic",
      "url": "/documentation/agl/agl_backing_store"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_CLOSEST_POLICY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_CLOSEST_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_CLOSEST_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_CLOSEST_POLICY"
        }
      ],
      "role": "symbol",
      "title": "AGL_CLOSEST_POLICY",
      "type": "topic",
      "url": "/documentation/agl/agl_closest_policy"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_COMPLIANT": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, specifies a pixel format that is fully compliant with OpenGL. All macOS renderers are OpenGL-compliant. You can pass this constant to the function ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_COMPLIANT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_COMPLIANT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_COMPLIANT"
        }
      ],
      "role": "symbol",
      "title": "AGL_COMPLIANT",
      "type": "topic",
      "url": "/documentation/agl/agl_compliant"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MP_SAFE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MP_SAFE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MP_SAFE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MP_SAFE"
        }
      ],
      "role": "symbol",
      "title": "AGL_MP_SAFE",
      "type": "topic",
      "url": "/documentation/agl/agl_mp_safe"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_MULTISCREEN": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, specifies that the renderer is capable of driving multiple screens with the same rendering context. (A single window can span multiple screens.) You can pass this constant to the function ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_MULTISCREEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_MULTISCREEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_MULTISCREEN"
        }
      ],
      "role": "symbol",
      "title": "AGL_MULTISCREEN",
      "type": "topic",
      "url": "/documentation/agl/agl_multiscreen"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_NO_RECOVERY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_NO_RECOVERY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_NO_RECOVERY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_NO_RECOVERY"
        }
      ],
      "role": "symbol",
      "title": "AGL_NO_RECOVERY",
      "type": "topic",
      "url": "/documentation/agl/agl_no_recovery"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_PBUFFER": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, specifies that the renderer can render to a pixel buffer. You can pass this constant to the function ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_PBUFFER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_PBUFFER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_PBUFFER"
        }
      ],
      "role": "symbol",
      "title": "AGL_PBUFFER",
      "type": "topic",
      "url": "/documentation/agl/agl_pbuffer"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_REMOTE_PBUFFER": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, specifies that the renderer can render offline to a pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_REMOTE_PBUFFER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_REMOTE_PBUFFER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_REMOTE_PBUFFER"
        }
      ],
      "role": "symbol",
      "title": "AGL_REMOTE_PBUFFER",
      "type": "topic",
      "url": "/documentation/agl/agl_remote_pbuffer"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ID": {
      "abstract": [
        {
          "text": "The associated value is a nonnegative integer that specifies a renderer. If present, OpenGL renderers that match the specified ID are preferred. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/renderer-ids",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for possible values. You can pass this constant to the function ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_ID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_RENDERER_ID"
        }
      ],
      "role": "symbol",
      "title": "AGL_RENDERER_ID",
      "type": "topic",
      "url": "/documentation/agl/agl_renderer_id"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_ROBUST": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array,  specifies that AGL should consider only those renderers that do not have any failure modes associated with a lack of video card resources. You can pass this constant to the function ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_ROBUST"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_ROBUST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_ROBUST"
        }
      ],
      "role": "symbol",
      "title": "AGL_ROBUST",
      "type": "topic",
      "url": "/documentation/agl/agl_robust"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_SINGLE_RENDERER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_SINGLE_RENDERER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_SINGLE_RENDERER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_SINGLE_RENDERER"
        }
      ],
      "role": "symbol",
      "title": "AGL_SINGLE_RENDERER",
      "type": "topic",
      "url": "/documentation/agl/agl_single_renderer"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_VIRTUAL_SCREEN": {
      "abstract": [
        {
          "text": "The associated value is an integer that specifies the virtual screen number of the pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_VIRTUAL_SCREEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_VIRTUAL_SCREEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_VIRTUAL_SCREEN"
        }
      ],
      "role": "symbol",
      "title": "AGL_VIRTUAL_SCREEN",
      "type": "topic",
      "url": "/documentation/agl/agl_virtual_screen"
    },
    "doc://com.apple.agl/documentation/AGL/AGL_WINDOW": {
      "abstract": [
        {
          "text": "This constant is a Boolean attribute. If it is present in the attributes array, specifies that the pixel format can be used to render to an onscreen window. You can pass this constant to the function ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AGL_WINDOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL_WINDOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AGL_WINDOW"
        }
      ],
      "role": "symbol",
      "title": "AGL_WINDOW",
      "type": "topic",
      "url": "/documentation/agl/agl_window"
    },
    "doc://com.apple.agl/documentation/AGL/bit-depths": {
      "abstract": [
        {
          "text": "Define resolutions for the depth and stencil buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/bit-depths",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bit Depths",
      "type": "topic",
      "url": "/documentation/agl/bit-depths"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes": {
      "abstract": [
        {
          "text": "Specify attributes used to create a pixel format object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer and Renderer Attributes",
      "type": "topic",
      "url": "/documentation/agl/buffer-and-renderer-attributes"
    },
    "doc://com.apple.agl/documentation/AGL/buffer-mode-flags": {
      "abstract": [
        {
          "text": "Define constants used to set buffer modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Mode Flags",
      "type": "topic",
      "url": "/documentation/agl/buffer-mode-flags"
    },
    "doc://com.apple.agl/documentation/AGL/color-modes": {
      "abstract": [
        {
          "text": "Specify formats and color channel layout information for the color  buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/color-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Modes",
      "type": "topic",
      "url": "/documentation/agl/color-modes"
    },
    "doc://com.apple.agl/documentation/AGL/context-options-and-parameters": {
      "abstract": [
        {
          "text": "Define options and parameters that apply to a specific rendering context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Options and Parameters",
      "type": "topic",
      "url": "/documentation/agl/context-options-and-parameters"
    },
    "doc://com.apple.agl/documentation/AGL/error-codes": {
      "abstract": [
        {
          "text": "Defines the error codes that can be returned by the ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/agl/error-codes"
    },
    "doc://com.apple.agl/documentation/AGL/globally-configured-options": {
      "abstract": [
        {
          "text": "Specify options that apply globally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/globally-configured-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Globally Configured Options",
      "type": "topic",
      "url": "/documentation/agl/globally-configured-options"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-ids": {
      "abstract": [
        {
          "text": "Define constants that specify hardware and software renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer IDs",
      "type": "topic",
      "url": "/documentation/agl/renderer-ids"
    },
    "doc://com.apple.agl/documentation/AGL/renderer-properties": {
      "abstract": [
        {
          "text": "Specify constants that you can use to query renderer properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/renderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Renderer Properties",
      "type": "topic",
      "url": "/documentation/agl/renderer-properties"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/#id(F15037)": {
      "identifier": "https://developer.apple.com/library/archive/#id(F15037)",
      "title": "aglGetError",
      "titleInlineContent": [
        {
          "text": "aglGetError",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/#id(F15037)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/bit-depths",
        "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
        "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
        "doc://com.apple.agl/documentation/AGL/color-modes",
        "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
        "doc://com.apple.agl/documentation/AGL/error-codes",
        "doc://com.apple.agl/documentation/AGL/globally-configured-options",
        "doc://com.apple.agl/documentation/AGL/renderer-ids",
        "doc://com.apple.agl/documentation/AGL/renderer-properties"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ID",
        "doc://com.apple.agl/documentation/AGL/AGL_SINGLE_RENDERER",
        "doc://com.apple.agl/documentation/AGL/AGL_NO_RECOVERY",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCELERATED",
        "doc://com.apple.agl/documentation/AGL/AGL_CLOSEST_POLICY",
        "doc://com.apple.agl/documentation/AGL/AGL_ROBUST",
        "doc://com.apple.agl/documentation/AGL/AGL_BACKING_STORE",
        "doc://com.apple.agl/documentation/AGL/AGL_MP_SAFE",
        "doc://com.apple.agl/documentation/AGL/AGL_WINDOW",
        "doc://com.apple.agl/documentation/AGL/AGL_MULTISCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_VIRTUAL_SCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_COMPLIANT",
        "doc://com.apple.agl/documentation/AGL/AGL_PBUFFER",
        "doc://com.apple.agl/documentation/AGL/AGL_REMOTE_PBUFFER",
        "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ID",
        "doc://com.apple.agl/documentation/AGL/AGL_SINGLE_RENDERER",
        "doc://com.apple.agl/documentation/AGL/AGL_NO_RECOVERY",
        "doc://com.apple.agl/documentation/AGL/AGL_ACCELERATED",
        "doc://com.apple.agl/documentation/AGL/AGL_CLOSEST_POLICY",
        "doc://com.apple.agl/documentation/AGL/AGL_ROBUST",
        "doc://com.apple.agl/documentation/AGL/AGL_BACKING_STORE",
        "doc://com.apple.agl/documentation/AGL/AGL_MP_SAFE",
        "doc://com.apple.agl/documentation/AGL/AGL_WINDOW",
        "doc://com.apple.agl/documentation/AGL/AGL_MULTISCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_VIRTUAL_SCREEN",
        "doc://com.apple.agl/documentation/AGL/AGL_COMPLIANT",
        "doc://com.apple.agl/documentation/AGL/AGL_PBUFFER",
        "doc://com.apple.agl/documentation/AGL/AGL_REMOTE_PBUFFER"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_SINGLE_RENDERER",
                "doc://com.apple.agl/documentation/AGL/AGL_NO_RECOVERY",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCELERATED",
                "doc://com.apple.agl/documentation/AGL/AGL_CLOSEST_POLICY",
                "doc://com.apple.agl/documentation/AGL/AGL_ROBUST",
                "doc://com.apple.agl/documentation/AGL/AGL_BACKING_STORE",
                "doc://com.apple.agl/documentation/AGL/AGL_MP_SAFE",
                "doc://com.apple.agl/documentation/AGL/AGL_WINDOW",
                "doc://com.apple.agl/documentation/AGL/AGL_MULTISCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_VIRTUAL_SCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_COMPLIANT",
                "doc://com.apple.agl/documentation/AGL/AGL_PBUFFER",
                "doc://com.apple.agl/documentation/AGL/AGL_REMOTE_PBUFFER",
                "doc://com.apple.agl/documentation/AGL/AGL_RENDERER_ID",
                "doc://com.apple.agl/documentation/AGL/AGL_SINGLE_RENDERER",
                "doc://com.apple.agl/documentation/AGL/AGL_NO_RECOVERY",
                "doc://com.apple.agl/documentation/AGL/AGL_ACCELERATED",
                "doc://com.apple.agl/documentation/AGL/AGL_CLOSEST_POLICY",
                "doc://com.apple.agl/documentation/AGL/AGL_ROBUST",
                "doc://com.apple.agl/documentation/AGL/AGL_BACKING_STORE",
                "doc://com.apple.agl/documentation/AGL/AGL_MP_SAFE",
                "doc://com.apple.agl/documentation/AGL/AGL_WINDOW",
                "doc://com.apple.agl/documentation/AGL/AGL_MULTISCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_VIRTUAL_SCREEN",
                "doc://com.apple.agl/documentation/AGL/AGL_COMPLIANT",
                "doc://com.apple.agl/documentation/AGL/AGL_PBUFFER",
                "doc://com.apple.agl/documentation/AGL/AGL_REMOTE_PBUFFER"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/bit-depths",
                "doc://com.apple.agl/documentation/AGL/buffer-and-renderer-attributes",
                "doc://com.apple.agl/documentation/AGL/buffer-mode-flags",
                "doc://com.apple.agl/documentation/AGL/color-modes",
                "doc://com.apple.agl/documentation/AGL/context-options-and-parameters",
                "doc://com.apple.agl/documentation/AGL/error-codes",
                "doc://com.apple.agl/documentation/AGL/globally-configured-options",
                "doc://com.apple.agl/documentation/AGL/renderer-ids",
                "doc://com.apple.agl/documentation/AGL/renderer-properties"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BACKING_STORE/title",
          "value": "AGL_BACKING_STORE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_BACKING_STORE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_BACKING_STORE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_REMOTE_PBUFFER/title",
          "value": "AGL_REMOTE_PBUFFER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_REMOTE_PBUFFER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_REMOTE_PBUFFER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MP_SAFE/title",
          "value": "AGL_MP_SAFE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MP_SAFE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MP_SAFE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ROBUST/title",
          "value": "AGL_ROBUST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ROBUST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ROBUST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCELERATED/title",
          "value": "AGL_ACCELERATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_ACCELERATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_ACCELERATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_NO_RECOVERY/title",
          "value": "AGL_NO_RECOVERY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_NO_RECOVERY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_NO_RECOVERY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_VIRTUAL_SCREEN/title",
          "value": "AGL_VIRTUAL_SCREEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_VIRTUAL_SCREEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_VIRTUAL_SCREEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_PBUFFER/title",
          "value": "AGL_PBUFFER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_PBUFFER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_PBUFFER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_CLOSEST_POLICY/title",
          "value": "AGL_CLOSEST_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_CLOSEST_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_CLOSEST_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RENDERER_ID/title",
          "value": "AGL_RENDERER_ID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_RENDERER_ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_RENDERER_ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COMPLIANT/title",
          "value": "AGL_COMPLIANT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_COMPLIANT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_COMPLIANT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SINGLE_RENDERER/title",
          "value": "AGL_SINGLE_RENDERER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_SINGLE_RENDERER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_SINGLE_RENDERER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MULTISCREEN/title",
          "value": "AGL_MULTISCREEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_MULTISCREEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_MULTISCREEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_WINDOW/title",
          "value": "AGL_WINDOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.agl~1documentation~1AGL~1AGL_WINDOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AGL_WINDOW"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl/renderer-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl/renderer-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
