{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPListSection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPListSection/init(items:)-6ksy3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CarPlay",
    "externalID": "s:So13CPListSectionC7CarPlayE5itemsABSaySo0A12TemplateItem_pG_tcfc",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "items"
      },
      {
        "kind": "text",
        "text": ": [any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)CPListTemplateItem",
        "text": "CPListTemplateItem"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(items:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "items"
            },
            {
              "kind": "text",
              "text": ": [any "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListTemplateItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)CPListTemplateItem",
              "text": "CPListTemplateItem"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListSection": {
      "abstract": [
        {
          "text": "A container that groups your list items into sections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListSection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListSection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListSection"
        }
      ],
      "role": "symbol",
      "title": "CPListSection",
      "type": "topic",
      "url": "/documentation/carplay/cplistsection"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListSection/init(items:)-6ksy3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "items"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CPListTemplateItem",
          "text": "CPListTemplateItem"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListSection/init(items:)-6ksy3",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(items:)",
      "type": "topic",
      "url": "/documentation/carplay/cplistsection/init(items:)-6ksy3"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListTemplateItem": {
      "abstract": [
        {
          "text": "A description of the common properties of all list item types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListTemplateItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListTemplateItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListTemplateItem"
        }
      ],
      "role": "symbol",
      "title": "CPListTemplateItem",
      "type": "topic",
      "url": "/documentation/carplay/cplisttemplateitem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListTemplateItem/title",
          "value": "CPListTemplateItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListTemplateItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListTemplateItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListTemplateItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListTemplateItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListSection/title",
          "value": "CPListSection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListSection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListSection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListSection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListSection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cplistsection/init(items:)-6ksy3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
