{
  "abstract": [
    {
      "text": "Initializes a view controller for an existing contact.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNContactViewController(cm)viewControllerForContact:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CNContact",
        "text": "CNContact"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Contacts UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "viewControllerForContact:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "contact"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CNContact",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CNContact",
              "text": "CNContact"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The existing contact.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "contact"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A newly initialized ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This view controller initializes the customized behavior and appearance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for a contact.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Contacts-UI/documentation/ContactsUI": {
      "abstract": [
        {
          "text": "Provide an interface that allows people to display information about their",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts UI",
      "type": "topic",
      "url": "/documentation/contactsui"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController": {
      "abstract": [
        {
          "text": "A view controller that displays a new, unknown, or existing contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactViewController"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactViewController"
        }
      ],
      "role": "symbol",
      "title": "CNContactViewController",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactviewcontroller"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(for:)": {
      "abstract": [
        {
          "text": "Initializes a view controller for an existing contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContact",
          "text": "CNContact"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewControllerForContact:"
        }
      ],
      "role": "symbol",
      "title": "init(for:)",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactviewcontroller/init(for:)"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forContact:)": {
      "abstract": [
        {
          "text": "Initializes a view controller for an existing contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContact",
          "text": "CNContact"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forContact:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(forContact:)",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactviewcontroller/init(forcontact:)"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forNewContact:)": {
      "abstract": [
        {
          "text": "Initializes a view controller for a new contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forNewContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContact",
          "text": "CNContact"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forNewContact:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewControllerForNewContact:"
        }
      ],
      "role": "symbol",
      "title": "init(forNewContact:)",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactviewcontroller/init(fornewcontact:)"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forUnknownContact:)": {
      "abstract": [
        {
          "text": "Initializes a view controller for an unknown contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forUnknownContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContact",
          "text": "CNContact"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forUnknownContact:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewControllerForUnknownContact:"
        }
      ],
      "role": "symbol",
      "title": "init(forUnknownContact:)",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactviewcontroller/init(forunknowncontact:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)CNContact": {
      "abstract": [
        {
          "text": "An immutable object that stores information about a single contact, such as the contact’s first name, phone numbers, and addresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContact"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CNContact",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNContact",
      "type": "topic",
      "url": "/documentation/Contacts/CNContact"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-the-Contact-Viewer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forContact:)",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forUnknownContact:)",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forNewContact:)"
      ],
      "title": "Creating the Contact Viewer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "viewControllerForContact:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "viewControllerForContact:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Contacts-UI/documentation/ContactsUI",
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-the-Contact-Viewer",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forUnknownContact:)",
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/init(forNewContact:)"
              ],
              "title": "Creating the Contact Viewer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "viewControllerForContact:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CNContact",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CNContact",
                    "text": "CNContact"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "contact"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The existing contact.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "contact"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A newly initialized ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController~1init(forNewContact:)/title",
          "value": "viewControllerForNewContact:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController~1init(forNewContact:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "viewControllerForNewContact:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController~1init(for:)/title",
          "value": "viewControllerForContact:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController~1init(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "viewControllerForContact:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)CNContact/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNContact"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/title",
          "value": "CNContactViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController~1init(forUnknownContact:)/title",
          "value": "viewControllerForUnknownContact:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController~1init(forUnknownContact:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "viewControllerForUnknownContact:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contactsui/cncontactviewcontroller/init(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contactsui/cncontactviewcontroller/init(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
