{
  "abstract": [
    {
      "text": "The group in which to add a new contact.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/parentGroup"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNContactViewController(py)parentGroup",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "parentGroup"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CNGroup",
        "text": "CNGroup"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Contacts UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "parentGroup"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "parentGroup"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "parentGroup"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CNGroup",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CNGroup",
              "text": "CNGroup"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you do not set this property, the view controller adds a new contact to the default",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "group.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Contacts-UI/documentation/ContactsUI": {
      "abstract": [
        {
          "text": "Provide an interface that allows people to display information about their",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts UI",
      "type": "topic",
      "url": "/documentation/contactsui"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController": {
      "abstract": [
        {
          "text": "A view controller that displays a new, unknown, or existing contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactViewController"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactViewController"
        }
      ],
      "role": "symbol",
      "title": "CNContactViewController",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactviewcontroller"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/parentContainer": {
      "abstract": [
        {
          "text": "The container in which to add a new contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentContainer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContainer",
          "text": "CNContainer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/parentContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parentContainer"
        }
      ],
      "role": "symbol",
      "title": "parentContainer",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactviewcontroller/parentcontainer"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/parentGroup": {
      "abstract": [
        {
          "text": "The group in which to add a new contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNGroup",
          "text": "CNGroup"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/parentGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parentGroup"
        }
      ],
      "role": "symbol",
      "title": "parentGroup",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactviewcontroller/parentgroup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)CNGroup": {
      "abstract": [
        {
          "text": "An immutable object that represents a group of contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNGroup"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CNGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNGroup",
      "type": "topic",
      "url": "/documentation/Contacts/CNGroup"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Contacts-Relationships",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/parentContainer"
      ],
      "title": "Configuring the Contact’s Relationships"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "parentGroup"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parentGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Contacts-UI/documentation/ContactsUI",
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Contacts-Relationships",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController/parentContainer"
              ],
              "title": "Configuring the Contact’s Relationships"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CNGroup",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CNGroup",
                    "text": "CNGroup"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "parentGroup"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController~1parentContainer/title",
          "value": "parentContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController~1parentContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)CNGroup/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNGroup"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController~1parentGroup/title",
          "value": "parentGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController~1parentGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parentGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/title",
          "value": "CNContactViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contactsui/cncontactviewcontroller/parentgroup"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contactsui/cncontactviewcontroller/parentgroup"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
