{
  "abstract": [
    {
      "text": "A delegate method the view controller calls when a connection succeeds.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.extensionkit/documentation/ExtensionKit",
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerDidActivate(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)EXHostViewControllerDelegate(im)hostViewControllerDidActivate:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hostViewControllerDidActivate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)EXHostViewController",
        "text": "EXHostViewController"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "ExtensionKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "hostViewControllerDidActivate:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "hostViewControllerDidActivate(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hostViewControllerDidActivate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "viewController"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)EXHostViewController",
              "text": "EXHostViewController"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The user interface object from the remote process.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "viewController"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This delegate method gets called when the extension process has launched and the remote scene connects. After this delegate method gets called the host view controller can establish an XPC connection with the scene in the extension process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit": {
      "abstract": [
        {
          "text": "Create executable bundles to extend the functionality of other apps by presenting a user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ExtensionKit",
      "type": "topic",
      "url": "/documentation/extensionkit"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController": {
      "abstract": [
        {
          "text": "A view controller that hosts remote views provided by an extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EXHostViewController"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EXHostViewController"
        }
      ],
      "role": "symbol",
      "title": "EXHostViewController",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate": {
      "abstract": [
        {
          "text": "The delegate for a hosted view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EXHostViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EXHostViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "EXHostViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontrollerdelegate"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerDidActivate(_:)": {
      "abstract": [
        {
          "text": "A delegate method the view controller calls when a connection succeeds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostViewControllerDidActivate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EXHostViewController",
          "text": "EXHostViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerDidActivate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hostViewControllerDidActivate:"
        }
      ],
      "role": "symbol",
      "title": "hostViewControllerDidActivate(_:)",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontrollerdelegate/hostviewcontrollerdidactivate(_:)"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerWillDeactivate(_:error:)": {
      "abstract": [
        {
          "text": "A delegate method the host view controller calls when an extension disconnects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostViewControllerWillDeactivate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EXHostViewController",
          "text": "EXHostViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerWillDeactivate(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hostViewControllerWillDeactivate:error:"
        }
      ],
      "role": "symbol",
      "title": "hostViewControllerWillDeactivate(_:error:)",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontrollerdelegate/hostviewcontrollerwilldeactivate(_:error:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Delegate-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerWillDeactivate(_:error:)"
      ],
      "title": "Delegate Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "hostViewControllerDidActivate:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hostViewControllerDidActivate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.extensionkit/documentation/ExtensionKit",
                "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Delegate-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerWillDeactivate(_:error:)"
              ],
              "title": "Delegate Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "hostViewControllerDidActivate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)EXHostViewController",
                    "text": "EXHostViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "viewController"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The user interface object from the remote process.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "viewController"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate~1hostViewControllerWillDeactivate(_:error:)/title",
          "value": "hostViewControllerWillDeactivate:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate~1hostViewControllerWillDeactivate(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hostViewControllerWillDeactivate:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate~1hostViewControllerDidActivate(_:)/title",
          "value": "hostViewControllerDidActivate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate~1hostViewControllerDidActivate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hostViewControllerDidActivate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController/title",
          "value": "EXHostViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate/title",
          "value": "EXHostViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewControllerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/extensionkit/exhostviewcontrollerdelegate/hostviewcontrollerdidactivate(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/extensionkit/exhostviewcontrollerdelegate/hostviewcontrollerdidactivate(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
