{
  "abstract": [
    {
      "text": "Gets a list of all transactions in the test environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/allTransactions()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKTestSession(im)allTransactions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "allTransactions"
      },
      {
        "kind": "text",
        "text": "() -> ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SKTestTransaction",
        "text": "SKTestTransaction"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "allTransactions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "allTransactions()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "allTransactions"
            },
            {
              "kind": "text",
              "text": "() -> ["
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestTransaction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SKTestTransaction",
              "text": "SKTestTransaction"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array that contains all transactions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This array contains all transactions, including those that don’t appear in the receipt, such as:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Failed transactions",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Pending Ask to Buy transactions",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Purchases of consumable products",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Use this list to work with Ask to Buy, to refund a specific transaction, or delete a transaction from the history, so you can repeat the test.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession": {
      "abstract": [
        {
          "text": "The controls and environment configuration you use to test StoreKit transactions in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/allTransactions()": {
      "abstract": [
        {
          "text": "Gets a list of all transactions in the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allTransactions"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTestTransaction",
          "text": "SKTestTransaction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/allTransactions()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allTransactions"
        }
      ],
      "role": "symbol",
      "title": "allTransactions()",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/alltransactions()"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/clearTransactions()": {
      "abstract": [
        {
          "text": "Removes all transactions from the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearTransactions"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/clearTransactions()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearTransactions"
        }
      ],
      "role": "symbol",
      "title": "clearTransactions()",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/cleartransactions()"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/deleteTransaction(identifier:)": {
      "abstract": [
        {
          "text": "Deletes a specific transaction from the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteTransaction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/deleteTransaction(identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteTransactionWithIdentifier:error:"
        }
      ],
      "role": "symbol",
      "title": "deleteTransaction(identifier:)",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/deletetransaction(identifier:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestTransaction": {
      "abstract": [
        {
          "text": "A transaction that occurs in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestTransaction"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTransaction"
        }
      ],
      "role": "symbol",
      "title": "SKTestTransaction",
      "type": "topic",
      "url": "/documentation/storekittest/sktesttransaction"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-transactions-in-the-test-environment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/deleteTransaction(identifier:)",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/clearTransactions()"
      ],
      "title": "Managing transactions in the test environment"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "allTransactions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "allTransactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-transactions-in-the-test-environment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/deleteTransaction(identifier:)",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/clearTransactions()"
              ],
              "title": "Managing transactions in the test environment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<SKTestTransaction *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "allTransactions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An array that contains all transactions.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1allTransactions()/title",
          "value": "allTransactions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1allTransactions()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "allTransactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1deleteTransaction(identifier:)/title",
          "value": "deleteTransactionWithIdentifier:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1deleteTransaction(identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deleteTransactionWithIdentifier:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1clearTransactions()/title",
          "value": "clearTransactions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1clearTransactions()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clearTransactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestTransaction/title",
          "value": "SKTestTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestTransaction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/title",
          "value": "SKTestSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/sktestsession/alltransactions()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/sktestsession/alltransactions()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
