{
  "abstract": [
    {
      "text": "The error code that transactions return when you enable failing transactions.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported. Use simulatedError(forAPI:)",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/failureError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKTestSession(py)failureError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failureError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11SKErrorCodeLeV",
        "text": "SKError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SKErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "failureError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "No longer supported. Use simulatedError(forAPI:)",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "No longer supported. Use simulatedError(forAPI:)",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "No longer supported. Use simulatedError(forAPI:)",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "11.0",
        "message": "No longer supported. Use simulatedError(forAPI:)",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "No longer supported. Use simulatedError(forAPI:)",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "7.0",
        "message": "No longer supported. Use simulatedError(forAPI:)",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "failureError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failureError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SC11SKErrorCodeLeV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11SKErrorCodeLeV",
              "text": "SKError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@SKErrorCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SKErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can force an error by setting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/failTransactionsEnabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": " and setting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/failureError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value to one of these supported error codes: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/unknown",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/invalidOfferIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/invalidSignature",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/missingOfferParams",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/invalidOfferPrice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use these settings to test your how your app responds to failed transactions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/invalidOfferIdentifier": {
      "abstract": [
        {
          "text": "Error code indicating that the offer identifier is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOfferIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/invalidOfferIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKError.Code.invalidOfferIdentifier",
      "type": "topic",
      "url": "/documentation/StoreKit/SKError/Code/invalidOfferIdentifier"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/invalidOfferPrice": {
      "abstract": [
        {
          "text": "Error code indicating that the price you specified in App Store Connect is no longer valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOfferPrice"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/invalidOfferPrice",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKError.Code.invalidOfferPrice",
      "type": "topic",
      "url": "/documentation/StoreKit/SKError/Code/invalidOfferPrice"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/invalidSignature": {
      "abstract": [
        {
          "text": "Error code indicating that the signature in a payment discount isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSignature"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/invalidSignature",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKError.Code.invalidSignature",
      "type": "topic",
      "url": "/documentation/StoreKit/SKError/Code/invalidSignature"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/missingOfferParams": {
      "abstract": [
        {
          "text": "Error code indicating that parameters are missing in a payment discount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingOfferParams"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/missingOfferParams",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKError.Code.missingOfferParams",
      "type": "topic",
      "url": "/documentation/StoreKit/SKError/Code/missingOfferParams"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/unknown": {
      "abstract": [
        {
          "text": "Error code indicating that an unknown or unexpected error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKError/Code/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKError.Code.unknown",
      "type": "topic",
      "url": "/documentation/StoreKit/SKError/Code/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession": {
      "abstract": [
        {
          "text": "The controls and environment configuration you use to test StoreKit transactions in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/failTransactionsEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether transactions fail in the testing environment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failTransactionsEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/failTransactionsEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "failTransactionsEnabled"
        }
      ],
      "role": "symbol",
      "title": "failTransactionsEnabled",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/failtransactionsenabled"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/failureError": {
      "abstract": [
        {
          "text": "The error code that transactions return when you enable failing transactions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/failureError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "failureError"
        }
      ],
      "role": "symbol",
      "title": "failureError",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/failureerror"
    },
    "doc://com.externally.resolved.symbol/c:@E@SKErrorCode": {
      "abstract": [
        {
          "text": "Error codes for StoreKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@SKErrorCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKError.Code",
      "type": "topic",
      "url": "/documentation/StoreKit/SKError/Code"
    },
    "doc://com.externally.resolved.symbol/s:SC11SKErrorCodeLeV": {
      "abstract": [
        {
          "text": "StoreKit error descriptions, codes, and domains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SC11SKErrorCodeLeV",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKError",
      "type": "topic",
      "url": "/documentation/StoreKit/SKError"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Forcing-failed-transactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/failTransactionsEnabled"
      ],
      "title": "Forcing failed transactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "failureError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "failureError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Forcing-failed-transactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/failTransactionsEnabled"
              ],
              "title": "Forcing failed transactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@SKErrorCode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@SKErrorCode",
                    "text": "SKErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "failureError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported. Use simulatedError(forAPI:)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKError~1Code~1invalidOfferPrice/title",
          "value": "SKErrorInvalidOfferPrice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKError~1Code~1invalidOfferPrice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorInvalidOfferPrice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/title",
          "value": "SKTestSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1failureError/title",
          "value": "failureError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1failureError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "failureError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKError~1Code~1missingOfferParams/title",
          "value": "SKErrorMissingOfferParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKError~1Code~1missingOfferParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorMissingOfferParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKError~1Code~1unknown/title",
          "value": "SKErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1failTransactionsEnabled/title",
          "value": "failTransactionsEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1failTransactionsEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "failTransactionsEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKError~1Code~1invalidSignature/title",
          "value": "SKErrorInvalidSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKError~1Code~1invalidSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorInvalidSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKError~1Code~1invalidOfferIdentifier/title",
          "value": "SKErrorInvalidOfferIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKError~1Code~1invalidOfferIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorInvalidOfferIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@SKErrorCode/title",
          "value": "SKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@SKErrorCode/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKErrorCode"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/sktestsession/failureerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/sktestsession/failureerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
