{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/simulatedError(forAPI:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "StoreKitTest",
    "externalID": "s:So13SKTestSessionC12StoreKitTestE14simulatedError6forAPI7FailureQzSgx_tYaAC08FailablecdI0RzlF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simulatedError"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "genericParameter",
        "text": "API"
      },
      {
        "kind": "text",
        "text": ">("
      },
      {
        "kind": "externalParam",
        "text": "forAPI"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "API"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "async"
      },
      {
        "kind": "text",
        "text": " -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "API"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:12StoreKitTest08FailableaB3APIP7FailureQa",
        "text": "Failure"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "simulatedError(forAPI:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simulatedError"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "API"
            },
            {
              "kind": "text",
              "text": ">("
            },
            {
              "kind": "externalParam",
              "text": "forAPI"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "api"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "API"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "API"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/FailableStoreKitAPI/Failure",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:12StoreKitTest08FailableaB3APIP7FailureQa",
              "text": "Failure"
            },
            {
              "kind": "text",
              "text": "? "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "API"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/FailableStoreKitAPI",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:12StoreKitTest08FailableaB3APIP",
              "text": "FailableStoreKitAPI"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/FailableStoreKitAPI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FailableStoreKitAPI"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/FailableStoreKitAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FailableStoreKitAPI"
        }
      ],
      "role": "symbol",
      "title": "FailableStoreKitAPI",
      "type": "topic",
      "url": "/documentation/storekittest/failablestorekitapi"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/FailableStoreKitAPI/Failure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "associatedtype"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12StoreKitTest13SKTestFailureP",
          "text": "SKTestFailure"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/FailableStoreKitAPI/Failure",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "Failure",
      "type": "topic",
      "url": "/documentation/storekittest/failablestorekitapi/failure"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession": {
      "abstract": [
        {
          "text": "The controls and environment configuration you use to test StoreKit transactions in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/buyProduct(identifier:options:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buyProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV2IDa",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV14PurchaseOptionV",
          "text": "PurchaseOption"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/buyProduct(identifier:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "buyProduct(identifier:options:)",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/buyproduct(identifier:options:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/setSimulatedError(_:forAPI:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSimulatedError"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "API"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "API"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12StoreKitTest08FailableaB3APIP7FailureQa",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forAPI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "API"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/setSimulatedError(_:forAPI:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setSimulatedError(_:forAPI:)",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/setsimulatederror(_:forapi:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/simulatedError(forAPI:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simulatedError"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "API"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "forAPI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "API"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "API"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12StoreKitTest08FailableaB3APIP7FailureQa",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/simulatedError(forAPI:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "simulatedError(forAPI:)",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/simulatederror(forapi:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/buyProduct(identifier:options:)",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/setSimulatedError(_:forAPI:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/title",
          "value": "SKTestSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/sktestsession/simulatederror(forapi:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
