{
  "abstract": [
    {
      "text": "The values for rates of time passing in the test environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "StoreKitTest",
    "externalID": "c:@E@SKTestTimeRate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TimeRate"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TimeRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SKTestSession.TimeRate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TimeRate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The time rates that affect subscription renewals in the test environment match those in the sandbox environment with these exceptions:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Only the test environment supports the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtySeconds",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " time rate.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Only the test environment supports the fixed time rate options: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFifteenMinutes",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFiveMinutes",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryMinute",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryThirtySeconds",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTenSeconds",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTwoSeconds",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Only the sandbox environment supports a monthly renewal in 3 minutes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about time rates in the sandbox environment, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/app-store-connect/test-in-app-purchases-main/test-in-app-purchases",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The time rates also affect the lengths of the billing retry period and the billing grace period in the testing environment. See the individual enumeration cases for the actual time values of the subscription renewal rates, billing retry periods, and billing grace periods.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession": {
      "abstract": [
        {
          "text": "The controls and environment configuration you use to test StoreKit transactions in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum": {
      "abstract": [
        {
          "text": "The values for rates of time passing in the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TimeRate"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TimeRate"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/fiveMinutesIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 5 minutes in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fiveMinutesIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/fiveMinutesIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateFiveMinutesIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.fiveMinutesIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/fiveminutesisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFifteenMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every 15 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryFifteenMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFifteenMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryFifteenMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryFifteenMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleveryfifteenminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFiveMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every 5 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryFiveMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFiveMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryFiveMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryFiveMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleveryfiveminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryHour": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every hour.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryHour"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryHour",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryHour"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryHour",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleveryhour"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every 30 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryThirtyMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryThirtyMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryThirtyMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleverythirtyminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtySeconds": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every 30 seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryThirtySeconds"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtySeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryThirtySeconds"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryThirtySeconds",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleverythirtyseconds"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneHourIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 1 hour in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneHourIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneHourIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneHourIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneHourIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onehourisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneMinuteIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 1 minute in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinuteIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneMinuteIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneMinuteIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneMinuteIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/oneminuteisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFifteenMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every 15 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryFifteenMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFifteenMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryFifteenMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryFifteenMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleveryfifteenminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFiveMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every 5 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryFiveMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFiveMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryFiveMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryFiveMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleveryfiveminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryMinute": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every minute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryMinute"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryMinute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryMinute"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryMinute",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleveryminute"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTenSeconds": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every 10 seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryTenSeconds"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTenSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryTenSeconds"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryTenSeconds",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleverytenseconds"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryThirtySeconds": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every 30 seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryThirtySeconds"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryThirtySeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryThirtySeconds"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryThirtySeconds",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleverythirtyseconds"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTwoSeconds": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every 2 seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryTwoSeconds"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTwoSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryTwoSeconds"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryTwoSeconds",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleverytwoseconds"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneSecondIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 1 second in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneSecondIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneSecondIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneSecondIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneSecondIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onesecondisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/realTime": {
      "abstract": [
        {
          "text": "A rate of time in which the test environment runs in real time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "realTime"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/realTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateRealTime"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.realTime",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/realtime"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtyMinutesIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 30 minutes in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirtyMinutesIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtyMinutesIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateThirtyMinutesIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.thirtyMinutesIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/thirtyminutesisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtySecondsIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 30 seconds in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirtySecondsIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtySecondsIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateThirtySecondsIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.thirtySecondsIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/thirtysecondsisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/disableAutoRenewForTransaction(identifier:)": {
      "abstract": [
        {
          "text": "Disables auto-renewing for an auto-renewable subscription in the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableAutoRenewForTransaction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/disableAutoRenewForTransaction(identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableAutoRenewForTransactionWithIdentifier:error:"
        }
      ],
      "role": "symbol",
      "title": "disableAutoRenewForTransaction(identifier:)",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/disableautorenewfortransaction(identifier:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/enableAutoRenewForTransaction(identifier:)": {
      "abstract": [
        {
          "text": "Enables auto-renewing for an auto-renewable subscription in the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableAutoRenewForTransaction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/enableAutoRenewForTransaction(identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableAutoRenewForTransactionWithIdentifier:error:"
        }
      ],
      "role": "symbol",
      "title": "enableAutoRenewForTransaction(identifier:)",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/enableautorenewfortransaction(identifier:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/expireSubscription(productIdentifier:)": {
      "abstract": [
        {
          "text": "Causes the identified auto-renewable subscription to expire immediately in the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expireSubscription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "productIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/expireSubscription(productIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expireSubscriptionWithProductIdentifier:error:"
        }
      ],
      "role": "symbol",
      "title": "expireSubscription(productIdentifier:)",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/expiresubscription(productidentifier:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/forceRenewalOfSubscription(productIdentifier:)": {
      "abstract": [
        {
          "text": "Ends the previous subscription period and begins the next period in the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceRenewalOfSubscription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "productIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/forceRenewalOfSubscription(productIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "forceRenewalOfSubscriptionWithProductIdentifier:error:"
        }
      ],
      "role": "symbol",
      "title": "forceRenewalOfSubscription(productIdentifier:)",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/forcerenewalofsubscription(productidentifier:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/timeRate-swift.property": {
      "abstract": [
        {
          "text": "The rate at which time passes for subscriptions in the test environment as compared to real time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTestSession",
          "text": "SKTestSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTestTimeRate",
          "text": "TimeRate"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/timeRate-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeRate"
        }
      ],
      "role": "symbol",
      "title": "timeRate",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/help/app-store-connect/test-in-app-purchases-main/test-in-app-purchases": {
      "identifier": "https://developer.apple.com/help/app-store-connect/test-in-app-purchases-main/test-in-app-purchases",
      "title": "Test in-app purchases",
      "titleInlineContent": [
        {
          "text": "Test in-app purchases",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/app-store-connect/test-in-app-purchases-main/test-in-app-purchases"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Testing-subscription-renewals",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/timeRate-swift.property",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/enableAutoRenewForTransaction(identifier:)",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/disableAutoRenewForTransaction(identifier:)",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/forceRenewalOfSubscription(productIdentifier:)",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/expireSubscription(productIdentifier:)"
      ],
      "title": "Testing subscription renewals"
    }
  ],
  "topicSections": [
    {
      "anchor": "Fixed-time-rates-for-subscription-renewals",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFifteenMinutes",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFiveMinutes",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryMinute",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryThirtySeconds",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTenSeconds",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTwoSeconds"
      ],
      "title": "Fixed time rates for subscription renewals"
    },
    {
      "anchor": "Scaled-time-rates-for-subscription-renewals",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/realTime",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryHour",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFifteenMinutes",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFiveMinutes",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtySeconds"
      ],
      "title": "Scaled time rates for subscription renewals"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneHourIsOneDay",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtyMinutesIsOneDay",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/fiveMinutesIsOneDay",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneMinuteIsOneDay",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtySecondsIsOneDay",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneSecondIsOneDay"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKTestTimeRate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Fixed-time-rates-for-subscription-renewals",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFifteenMinutes",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFiveMinutes",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryMinute",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryThirtySeconds",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTenSeconds",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTwoSeconds"
              ],
              "title": "Fixed time rates for subscription renewals"
            },
            {
              "anchor": "Scaled-time-rates-for-subscription-renewals",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/realTime",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryHour",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFifteenMinutes",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFiveMinutes",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtySeconds"
              ],
              "title": "Scaled time rates for subscription renewals"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneHourIsOneDay",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtyMinutesIsOneDay",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/fiveMinutesIsOneDay",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneMinuteIsOneDay",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtySecondsIsOneDay",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneSecondIsOneDay"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Testing-subscription-renewals",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/timeRate-swift.property",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/enableAutoRenewForTransaction(identifier:)",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/disableAutoRenewForTransaction(identifier:)",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/forceRenewalOfSubscription(productIdentifier:)",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/expireSubscription(productIdentifier:)"
              ],
              "title": "Testing subscription renewals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKTestTimeRate"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1thirtySecondsIsOneDay/title",
          "value": "SKTestTimeRateThirtySecondsIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1thirtySecondsIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateThirtySecondsIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryFifteenMinutes/title",
          "value": "SKTestTimeRateOneRenewalEveryFifteenMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryFifteenMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryFifteenMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryThirtyMinutes/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryThirtyMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryThirtyMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryThirtyMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1realTime/title",
          "value": "SKTestTimeRateRealTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1realTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateRealTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryTenSeconds/title",
          "value": "SKTestTimeRateOneRenewalEveryTenSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryTenSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryTenSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryFiveMinutes/title",
          "value": "SKTestTimeRateOneRenewalEveryFiveMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryFiveMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryFiveMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryThirtySeconds/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryThirtySeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryThirtySeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryThirtySeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneSecondIsOneDay/title",
          "value": "SKTestTimeRateOneSecondIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneSecondIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneSecondIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryFifteenMinutes/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryFifteenMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryFifteenMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryFifteenMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1forceRenewalOfSubscription(productIdentifier:)/title",
          "value": "forceRenewalOfSubscriptionWithProductIdentifier:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1forceRenewalOfSubscription(productIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "forceRenewalOfSubscriptionWithProductIdentifier:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1thirtyMinutesIsOneDay/title",
          "value": "SKTestTimeRateThirtyMinutesIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1thirtyMinutesIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateThirtyMinutesIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryTwoSeconds/title",
          "value": "SKTestTimeRateOneRenewalEveryTwoSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryTwoSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryTwoSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1fiveMinutesIsOneDay/title",
          "value": "SKTestTimeRateFiveMinutesIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1fiveMinutesIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateFiveMinutesIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1expireSubscription(productIdentifier:)/title",
          "value": "expireSubscriptionWithProductIdentifier:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1expireSubscription(productIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "expireSubscriptionWithProductIdentifier:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1enableAutoRenewForTransaction(identifier:)/title",
          "value": "enableAutoRenewForTransactionWithIdentifier:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1enableAutoRenewForTransaction(identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enableAutoRenewForTransactionWithIdentifier:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/title",
          "value": "SKTestTimeRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneHourIsOneDay/title",
          "value": "SKTestTimeRateOneHourIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneHourIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneHourIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneMinuteIsOneDay/title",
          "value": "SKTestTimeRateOneMinuteIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneMinuteIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneMinuteIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryThirtySeconds/title",
          "value": "SKTestTimeRateOneRenewalEveryThirtySeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryThirtySeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryThirtySeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1timeRate-swift.property/title",
          "value": "timeRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1timeRate-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryHour/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryHour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryHour/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryHour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/title",
          "value": "SKTestSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1disableAutoRenewForTransaction(identifier:)/title",
          "value": "disableAutoRenewForTransactionWithIdentifier:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1disableAutoRenewForTransaction(identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "disableAutoRenewForTransactionWithIdentifier:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryMinute/title",
          "value": "SKTestTimeRateOneRenewalEveryMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryMinute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryFiveMinutes/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryFiveMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryFiveMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryFiveMinutes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/sktestsession/timerate-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/sktestsession/timerate-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
