{
  "abstract": [
    {
      "text": "The app attempted to schedule a session too far in the future.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/scheduledTooFarInAdvance"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKExtendedRuntimeSessionErrorCode@WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "scheduledTooFarInAdvance"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKExtendedRuntimeSessionErrorCode.scheduledTooFarInAdvance"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scheduledTooFarInAdvance"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can’t schedule alarm sessions more than 36 hours in advance. Other session types do not support scheduling.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode": {
      "abstract": [
        {
          "text": "The error codes reported by extended runtime sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorCode"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorCode"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/barDisabled": {
      "abstract": [
        {
          "text": "The user has disabled background app refresh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barDisabled"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/barDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorBARDisabled"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.barDisabled",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/bardisabled"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/exceededResourceLimits": {
      "abstract": [
        {
          "text": "The session exceeded its resource limits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exceededResourceLimits"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/exceededResourceLimits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorExceededResourceLimits"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.exceededResourceLimits",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/exceededresourcelimits"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToStartOrSchedule": {
      "abstract": [
        {
          "text": "The watchOS app attempted to start or schedule a session while not in an active state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mustBeActiveToStartOrSchedule"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToStartOrSchedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorMustBeActiveToStartOrSchedule"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.mustBeActiveToStartOrSchedule",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/mustbeactivetostartorschedule"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToSchedule": {
      "abstract": [
        {
          "text": "The app attempted to schedule a session, but the session type does not support scheduling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notApprovedToSchedule"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToSchedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorNotApprovedToSchedule"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.notApprovedToSchedule",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/notapprovedtoschedule"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToStartSession": {
      "abstract": [
        {
          "text": "The app attempted to start a session, but doesn’t have a valid session type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notApprovedToStartSession"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToStartSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorNotApprovedToStartSession"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.notApprovedToStartSession",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/notapprovedtostartsession"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notYetStarted": {
      "abstract": [
        {
          "text": "The app invalidated the session before it started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notYetStarted"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notYetStarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorNotYetStarted"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.notYetStarted",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/notyetstarted"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/scheduledTooFarInAdvance": {
      "abstract": [
        {
          "text": "The app attempted to schedule a session too far in the future.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduledTooFarInAdvance"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/scheduledTooFarInAdvance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.scheduledTooFarInAdvance",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/scheduledtoofarinadvance"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.unknown",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unknown",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToStartOrSchedule",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notYetStarted",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/exceededResourceLimits",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/barDisabled",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToStartSession",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToSchedule"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unknown",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToStartOrSchedule",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notYetStarted",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/exceededResourceLimits",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/barDisabled",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToStartSession",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToSchedule"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notApprovedToSchedule/title",
          "value": "WKExtendedRuntimeSessionErrorNotApprovedToSchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notApprovedToSchedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorNotApprovedToSchedule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1barDisabled/title",
          "value": "WKExtendedRuntimeSessionErrorBARDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1barDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorBARDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode/title",
          "value": "WKExtendedRuntimeSessionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1unknown/title",
          "value": "WKExtendedRuntimeSessionErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1exceededResourceLimits/title",
          "value": "WKExtendedRuntimeSessionErrorExceededResourceLimits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1exceededResourceLimits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorExceededResourceLimits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notYetStarted/title",
          "value": "WKExtendedRuntimeSessionErrorNotYetStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notYetStarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorNotYetStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notApprovedToStartSession/title",
          "value": "WKExtendedRuntimeSessionErrorNotApprovedToStartSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notApprovedToStartSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorNotApprovedToStartSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1scheduledTooFarInAdvance/title",
          "value": "WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1scheduledTooFarInAdvance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1mustBeActiveToStartOrSchedule/title",
          "value": "WKExtendedRuntimeSessionErrorMustBeActiveToStartOrSchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1mustBeActiveToStartOrSchedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorMustBeActiveToStartOrSchedule"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkextendedruntimesessionerrorcode/scheduledtoofarinadvance"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkextendedruntimesessionerrorcode/scheduledtoofarinadvance"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
