{"seeAlsoSections":[{"title":"Identifying Record Types","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/covid19","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/immunization","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/recovery"],"anchor":"Identifying-Record-Types","generated":true}],"abstract":[{"text":"A value that represents laboratory results.","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkverifiableclinicalrecordcredentialtype/laboratory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkverifiableclinicalrecordcredentialtype/laboratory"]}],"metadata":{"modules":[{"name":"HealthKit"}],"title":"laboratory","roleHeading":"Type Property","platforms":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"15.4"},{"deprecated":false,"beta":false,"introducedAt":"15.4","name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"15.4","name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"13.0","name":"macOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"8.5","name":"watchOS","unavailable":false}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"HKVerifiableClinicalRecordCredentialTypeLaboratory","kind":"identifier"}],"externalID":"c:@HKVerifiableClinicalRecordCredentialTypeLaboratory","extendedModule":"HealthKit","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"laboratory","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKVerifiableClinicalRecordCredentialType","preciseIdentifier":"c:@T@HKVerifiableClinicalRecordCredentialType","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"laboratory","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType","text":"HKVerifiableClinicalRecordCredentialType","preciseIdentifier":"c:@T@HKVerifiableClinicalRecordCredentialType","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/laboratory","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/covid19":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/covid19","title":"covid19","navigatorTitle":[{"text":"HKVerifiableClinicalRecordCredentialTypeCOVID19","kind":"identifier"}],"abstract":[{"text":"A value that represents records about COVID-19.","type":"text"}],"kind":"symbol","url":"/documentation/healthkit/hkverifiableclinicalrecordcredentialtype/covid19","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"covid19","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKVerifiableClinicalRecordCredentialType","kind":"typeIdentifier","preciseIdentifier":"c:@T@HKVerifiableClinicalRecordCredentialType"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/laboratory":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/laboratory","title":"laboratory","navigatorTitle":[{"text":"HKVerifiableClinicalRecordCredentialTypeLaboratory","kind":"identifier"}],"abstract":[{"text":"A value that represents laboratory results.","type":"text"}],"kind":"symbol","url":"/documentation/healthkit/hkverifiableclinicalrecordcredentialtype/laboratory","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"laboratory","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKVerifiableClinicalRecordCredentialType","kind":"typeIdentifier","preciseIdentifier":"c:@T@HKVerifiableClinicalRecordCredentialType"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/immunization":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/immunization","title":"immunization","navigatorTitle":[{"kind":"identifier","text":"HKVerifiableClinicalRecordCredentialTypeImmunization"}],"abstract":[{"type":"text","text":"A value that represents immunizations."}],"kind":"symbol","url":"/documentation/healthkit/hkverifiableclinicalrecordcredentialtype/immunization","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"immunization"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@HKVerifiableClinicalRecordCredentialType","kind":"typeIdentifier","text":"HKVerifiableClinicalRecordCredentialType"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKVerifiableClinicalRecordCredentialType"}],"type":"topic","url":"/documentation/healthkit/hkverifiableclinicalrecordcredentialtype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKVerifiableClinicalRecordCredentialType"}],"abstract":[{"text":"The type of record returned by a verifiable clinical record query.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType","title":"HKVerifiableClinicalRecordCredentialType"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/recovery":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/recovery","title":"recovery","navigatorTitle":[{"kind":"identifier","text":"HKVerifiableClinicalRecordCredentialTypeRecovery"}],"abstract":[{"type":"text","text":"A value that represents recovery information."}],"kind":"symbol","url":"/documentation/healthkit/hkverifiableclinicalrecordcredentialtype/recovery","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recovery"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@HKVerifiableClinicalRecordCredentialType","kind":"typeIdentifier","text":"HKVerifiableClinicalRecordCredentialType"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"15.4","name":"iOS"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"15.4","name":"iPadOS"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"15.4","name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.0","name":"macOS"},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false},{"name":"watchOS","unavailable":false,"introducedAt":"8.5","deprecated":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Global Variable","path":"/metadata/roleHeading"},{"op":"replace","value":"HKVerifiableClinicalRecordCredentialTypeLaboratory","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"HKVerifiableClinicalRecordCredentialTypeLaboratory"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Identifying-Record-Types","title":"Identifying Record Types","generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/covid19","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/immunization","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType/recovery"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType","text":"HKVerifiableClinicalRecordCredentialType","preciseIdentifier":"c:@T@HKVerifiableClinicalRecordCredentialType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKVerifiableClinicalRecordCredentialTypeLaboratory","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType~1covid19/title","value":"HKVerifiableClinicalRecordCredentialTypeCOVID19","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType~1covid19/fragments","value":[{"text":"HKVerifiableClinicalRecordCredentialTypeCOVID19","kind":"identifier"}],"op":"replace"},{"value":"HKVerifiableClinicalRecordCredentialTypeLaboratory","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType~1laboratory/title"},{"value":[{"text":"HKVerifiableClinicalRecordCredentialTypeLaboratory","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType~1laboratory/fragments"},{"value":"HKVerifiableClinicalRecordCredentialTypeImmunization","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType~1immunization/title"},{"value":[{"text":"HKVerifiableClinicalRecordCredentialTypeImmunization","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType~1immunization/fragments"},{"value":"HKVerifiableClinicalRecordCredentialType","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType/title"},{"value":[{"text":"HKVerifiableClinicalRecordCredentialType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType/fragments"},{"value":[{"text":"HKVerifiableClinicalRecordCredentialType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType/navigatorTitle"},{"value":"HKVerifiableClinicalRecordCredentialTypeRecovery","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType~1recovery/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType~1recovery/fragments","value":[{"text":"HKVerifiableClinicalRecordCredentialTypeRecovery","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}