{
  "abstract": [
    {
      "text": "A modifier that indicates to draw an underline using a pattern of dots.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDot"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTUnderlineStyleModifiers@kCTUnderlinePatternDot",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "patternDot"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTUnderlineStyleModifiers",
        "text": "CTUnderlineStyleModifiers"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTUnderlinePatternDot"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "patternDot"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "patternDot"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTUnderlineStyleModifiers",
              "text": "CTUnderlineStyleModifiers"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers": {
      "abstract": [
        {
          "text": "Underline style modifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "role": "symbol",
      "title": "CTUnderlineStyleModifiers",
      "type": "topic",
      "url": "/documentation/coretext/ctunderlinestylemodifiers"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDash": {
      "abstract": [
        {
          "text": "A modifier that indicates to draw an underline using a pattern of dashes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTUnderlineStyleModifiers",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTUnderlinePatternDash"
        }
      ],
      "role": "symbol",
      "title": "patternDash",
      "type": "topic",
      "url": "/documentation/coretext/ctunderlinestylemodifiers/patterndash"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDashDot": {
      "abstract": [
        {
          "text": "A modifier that indicates to draw an underline using a pattern of alternating dashes and dots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDashDot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTUnderlineStyleModifiers",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDashDot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTUnderlinePatternDashDot"
        }
      ],
      "role": "symbol",
      "title": "patternDashDot",
      "type": "topic",
      "url": "/documentation/coretext/ctunderlinestylemodifiers/patterndashdot"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDashDotDot": {
      "abstract": [
        {
          "text": "A modifier that indicates to draw an underline using a pattern of a dash followed by two dots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDashDotDot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTUnderlineStyleModifiers",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDashDotDot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTUnderlinePatternDashDotDot"
        }
      ],
      "role": "symbol",
      "title": "patternDashDotDot",
      "type": "topic",
      "url": "/documentation/coretext/ctunderlinestylemodifiers/patterndashdotdot"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDot": {
      "abstract": [
        {
          "text": "A modifier that indicates to draw an underline using a pattern of dots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTUnderlineStyleModifiers",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTUnderlinePatternDot"
        }
      ],
      "role": "symbol",
      "title": "patternDot",
      "type": "topic",
      "url": "/documentation/coretext/ctunderlinestylemodifiers/patterndot"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternSolid": {
      "abstract": [
        {
          "text": "A modifier that indicates to draw a solid underline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternSolid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTUnderlineStyleModifiers",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternSolid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTUnderlinePatternSolid"
        }
      ],
      "role": "symbol",
      "title": "patternSolid",
      "type": "topic",
      "url": "/documentation/coretext/ctunderlinestylemodifiers/patternsolid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternSolid",
        "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDash",
        "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDashDot",
        "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDashDotDot"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTUnderlinePatternDot"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTUnderlinePatternDot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternSolid",
                "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDash",
                "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDashDot",
                "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers/patternDashDotDot"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTUnderlinePatternDot"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers/title",
          "value": "CTUnderlineStyleModifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTUnderlineStyleModifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTUnderlineStyleModifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers~1patternDot/title",
          "value": "kCTUnderlinePatternDot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers~1patternDot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTUnderlinePatternDot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers~1patternSolid/title",
          "value": "kCTUnderlinePatternSolid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers~1patternSolid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTUnderlinePatternSolid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers~1patternDashDot/title",
          "value": "kCTUnderlinePatternDashDot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers~1patternDashDot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTUnderlinePatternDashDot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers~1patternDash/title",
          "value": "kCTUnderlinePatternDash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers~1patternDash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTUnderlinePatternDash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers~1patternDashDotDot/title",
          "value": "kCTUnderlinePatternDashDotDot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers~1patternDashDotDot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTUnderlinePatternDashDotDot"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctunderlinestylemodifiers/patterndot"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctunderlinestylemodifiers/patterndot"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
