{
  "abstract": [
    {
      "text": "The various types of thumbnails that you can request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "QuickLookThumbnailing",
    "externalID": "c:@E@QLThumbnailGenerationRequestRepresentationTypes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "RepresentationTypes"
      }
    ],
    "modules": [
      {
        "name": "Quick Look Thumbnailing"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RepresentationTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "QLThumbnailGenerator.Request.RepresentationTypes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "RepresentationTypes"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Thumbnails come in one of three different types:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A file icon representation.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/icon",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A faster to generate version of the thumbnail that may sacrifice quality for speed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/lowQualityThumbnail",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A high-quality thumbnail.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/thumbnail",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "To request all thumbnail representations, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/all",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing": {
      "abstract": [
        {
          "text": "Generate thumbnails for common file types and add a Thumbnail Extension to your app to enable others to create thumbnails of your custom files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look Thumbnailing",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator": {
      "abstract": [
        {
          "text": "An object that generates thumbnail images based on provided requirements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailGenerator"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailGenerator"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailGenerator",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request": {
      "abstract": [
        {
          "text": "A request to generate a thumbnail for a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Request"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Request"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailGenerator.Request",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct": {
      "abstract": [
        {
          "text": "The various types of thumbnails that you can request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RepresentationTypes"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RepresentationTypes"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailGenerator.Request.RepresentationTypes",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/representationtypes-swift.struct"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/all": {
      "abstract": [
        {
          "text": "The thumbnail type to generate all possible thumbnail representations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerator",
          "text": "QLThumbnailGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerationRequest",
          "text": "Request"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@QLThumbnailGenerationRequestRepresentationTypes",
          "text": "RepresentationTypes"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailGenerationRequestRepresentationTypeAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/representationtypes-swift.struct/all"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/icon": {
      "abstract": [
        {
          "text": "A file icon representation of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "icon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerator",
          "text": "QLThumbnailGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerationRequest",
          "text": "Request"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@QLThumbnailGenerationRequestRepresentationTypes",
          "text": "RepresentationTypes"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/icon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailGenerationRequestRepresentationTypeIcon"
        }
      ],
      "role": "symbol",
      "title": "icon",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/representationtypes-swift.struct/icon"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new thumbnail type object for a given value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/representationtypes-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/lowQualityThumbnail": {
      "abstract": [
        {
          "text": "A faster to generate version of the thumbnail that may sacrifice quality for speed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowQualityThumbnail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerator",
          "text": "QLThumbnailGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerationRequest",
          "text": "Request"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@QLThumbnailGenerationRequestRepresentationTypes",
          "text": "RepresentationTypes"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/lowQualityThumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailGenerationRequestRepresentationTypeLowQualityThumbnail"
        }
      ],
      "role": "symbol",
      "title": "lowQualityThumbnail",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/representationtypes-swift.struct/lowqualitythumbnail"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/thumbnail": {
      "abstract": [
        {
          "text": "A thumbnail representation of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbnail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerator",
          "text": "QLThumbnailGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerationRequest",
          "text": "Request"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@QLThumbnailGenerationRequestRepresentationTypes",
          "text": "RepresentationTypes"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/thumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailGenerationRequestRepresentationTypeThumbnail"
        }
      ],
      "role": "symbol",
      "title": "thumbnail",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/representationtypes-swift.struct/thumbnail"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/contentType": {
      "abstract": [
        {
          "text": "The content type of the source data for the thumbnail request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/contentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentType"
        }
      ],
      "role": "symbol",
      "title": "contentType",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/contenttype"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/iconMode": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the generated thumbnail request should include icon decorations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/iconMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconMode"
        }
      ],
      "role": "symbol",
      "title": "iconMode",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/iconmode"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/minimumDimension": {
      "abstract": [
        {
          "text": "The minimum height or width for a generated thumbnail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumDimension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/minimumDimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumDimension"
        }
      ],
      "role": "symbol",
      "title": "minimumDimension",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/minimumdimension"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/representationTypes-swift.property": {
      "abstract": [
        {
          "text": "The thumbnail sizes that you provide for a thumbnail request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "representationTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerator",
          "text": "QLThumbnailGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerationRequest",
          "text": "Request"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@QLThumbnailGenerationRequestRepresentationTypes",
          "text": "RepresentationTypes"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/representationTypes-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "representationTypes"
        }
      ],
      "role": "symbol",
      "title": "representationTypes",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/representationtypes-swift.property"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/scale": {
      "abstract": [
        {
          "text": "The pixel density of the display on the intended device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scale"
        }
      ],
      "role": "symbol",
      "title": "scale",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/scale"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/size": {
      "abstract": [
        {
          "text": "The size of the thumbnails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/size"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Describing-the-Requested-Thumbnail",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/size",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/scale",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/contentType",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/representationTypes-swift.property",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/minimumDimension",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/iconMode"
      ],
      "title": "Describing the Requested Thumbnail"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Thumbnail-Type",
      "identifiers": [
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/init(rawValue:)",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/all",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/icon",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/lowQualityThumbnail",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/thumbnail"
      ],
      "title": "Creating a Thumbnail Type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLThumbnailGenerationRequestRepresentationTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerationRequestRepresentationTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerationRequestRepresentationTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Thumbnail-Type",
              "identifiers": [
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/all",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/icon",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/lowQualityThumbnail",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/RepresentationTypes-swift.struct/thumbnail"
              ],
              "title": "Creating a Thumbnail Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Describing-the-Requested-Thumbnail",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/size",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/scale",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/contentType",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/representationTypes-swift.property",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/minimumDimension",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/Request/iconMode"
              ],
              "title": "Describing the Requested Thumbnail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QLThumbnailGenerationRequestRepresentationTypes"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator/title",
          "value": "QLThumbnailGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct/title",
          "value": "QLThumbnailGenerationRequestRepresentationTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerationRequestRepresentationTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerationRequestRepresentationTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request/title",
          "value": "QLThumbnailGenerationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct~1lowQualityThumbnail/title",
          "value": "QLThumbnailGenerationRequestRepresentationTypeLowQualityThumbnail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct~1lowQualityThumbnail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerationRequestRepresentationTypeLowQualityThumbnail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1iconMode/title",
          "value": "iconMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1iconMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iconMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct~1all/title",
          "value": "QLThumbnailGenerationRequestRepresentationTypeAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerationRequestRepresentationTypeAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct~1thumbnail/title",
          "value": "QLThumbnailGenerationRequestRepresentationTypeThumbnail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct~1thumbnail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerationRequestRepresentationTypeThumbnail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct~1icon/title",
          "value": "QLThumbnailGenerationRequestRepresentationTypeIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1RepresentationTypes-swift.struct~1icon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerationRequestRepresentationTypeIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1scale/title",
          "value": "scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1contentType/title",
          "value": "contentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1contentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1representationTypes-swift.property/title",
          "value": "representationTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1representationTypes-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "representationTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1minimumDimension/title",
          "value": "minimumDimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1Request~1minimumDimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumDimension"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/representationtypes-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklookthumbnailing/qlthumbnailgenerator/request/representationtypes-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
