{
  "abstract": [
    {
      "text": "A unique error domain for the framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorDomain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@DDErrorDomain",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DDErrorDomain"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "DeviceDiscoveryExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DDErrorDomain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "DDErrorDomain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DDErrorDomain"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cferror/error_domains",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension": {
      "abstract": [
        {
          "text": "Stream media to a third-party device that a user selects in a system menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "DeviceDiscoveryExtension",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError": {
      "abstract": [
        {
          "text": "An error that the framework reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDError"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDError"
        }
      ],
      "role": "symbol",
      "title": "DDError",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dderror"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code": {
      "abstract": [
        {
          "text": "Codes that identify errors that can occur during the framework’s use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "DDError.Code",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dderror/code"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorDomain": {
      "abstract": [
        {
          "text": "A unique error domain for the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "DDErrorDomain",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dderrordomain"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorHandler": {
      "abstract": [
        {
          "text": "A function that executes code you provide when an operation returns an error or completes successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDErrorHandler"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDErrorHandler"
        }
      ],
      "role": "symbol",
      "title": "DDErrorHandler",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dderrorhandler"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorOutType": {
      "abstract": [
        {
          "text": "A type for framework functions that return error references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDErrorOutType"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorOutType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDErrorOutType"
        }
      ],
      "role": "symbol",
      "title": "DDErrorOutType",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dderrorouttype"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cferror/error_domains": {
      "abstract": [
        {
          "text": "These constants define domains for CFError objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cferror/error_domains",
      "kind": "article",
      "role": "article",
      "title": "Error domains",
      "type": "topic",
      "url": "/documentation/corefoundation/cferror/error_domains"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorHandler",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorOutType"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DDErrorDomain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorHandler",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDErrorOutType"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DDErrorDomain"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDErrorHandler/title",
          "value": "DDErrorHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDErrorHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDErrorHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDErrorHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDErrorHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code/title",
          "value": "DDErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDErrorOutType/title",
          "value": "DDErrorOutType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDErrorOutType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDErrorOutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDErrorOutType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDErrorOutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDErrorDomain/title",
          "value": "DDErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/devicediscoveryextension/dderrordomain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/devicediscoveryextension/dderrordomain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
