{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/validate()"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSToolbarItem"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/isEnabled"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/autovalidates"],"generated":true,"anchor":"Validating-the-item","title":"Validating the item"}],"sections":[],"variants":[{"paths":["/documentation/appkit/nstoolbaritem/validate()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nstoolbaritem/validate()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"13.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"13.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"title":"validate()","externalID":"c:objc(cs)NSToolbarItem(im)validate","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"validate","kind":"identifier"}],"modules":[{"name":"AppKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"()","kind":"text"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"()"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Typically, you don’t call this method directly. When automatic validation is enabled, the toolbar calls this method to validate the item. For standard toolbar items — that is, items without a custom view — the validation process checks whether the item can perform its associated action successfully and enables or disables the item accordingly. The process also validates the associated menu item. When someone switches to another app or window, the automatic validation process disables the item automatically."}],"type":"paragraph"},{"inlineContent":[{"text":"If the toolbar item has a custom view, subclass ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem","isActive":true,"type":"reference"},{"text":" and override this method to perform the validation yourself. After you validate your custom toolbar item, update the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/isEnabled"},{"type":"text","text":" property. You don’t need to call "},{"type":"codeVoice","code":"super"},{"type":"text","text":" in your implementation."}],"type":"paragraph"},{"inlineContent":[{"text":"If you disable automatic validation, toolbar items remain enabled and clickable, including when someone switches to another app or window. However, you can still call this method manually to validate the toolbar item.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"Validates the toolbar item’s menu and its ability to perfrom its action.","type":"text"}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem":{"url":"/documentation/appkit/nstoolbaritem","kind":"symbol","navigatorTitle":[{"text":"NSToolbarItem","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSToolbarItem","abstract":[{"type":"text","text":"A single item that appears in a window’s toolbar."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSToolbarItem","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/isEnabled":{"kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the item is enabled."}],"role":"symbol","type":"topic","url":"/documentation/appkit/nstoolbaritem/isenabled","identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"enabled","kind":"identifier"}],"title":"isEnabled"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/autovalidates":{"abstract":[{"type":"text","text":"A Boolean value that indicates whether the toolbar automatically validates the item."}],"title":"autovalidates","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autovalidates","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"autovalidates","kind":"identifier"}],"url":"/documentation/appkit/nstoolbaritem/autovalidates","identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/autovalidates","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/validate()":{"abstract":[{"text":"Validates the toolbar item’s menu and its ability to perfrom its action.","type":"text"}],"title":"validate()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"validate","kind":"identifier"}],"url":"/documentation/appkit/nstoolbaritem/validate()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/validate()","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"beta":false,"deprecated":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"validate","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"validate","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSToolbarItem"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/isEnabled"],"title":"Related Documentation","anchor":"Related-Documentation"},{"generated":true,"anchor":"Validating-the-item","title":"Validating the item","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/autovalidates"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"validate"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem/title","value":"NSToolbarItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem/fragments","value":[{"kind":"identifier","text":"NSToolbarItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem/navigatorTitle","value":[{"text":"NSToolbarItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1isEnabled/title","value":"enabled"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1isEnabled/fragments","value":[{"kind":"identifier","text":"enabled"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1autovalidates/title","value":"autovalidates","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1autovalidates/fragments","value":[{"text":"autovalidates","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1validate()/title","value":"validate","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1validate()/fragments","value":[{"text":"- ","kind":"text"},{"text":"validate","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}