{
  "abstract": [
    {
      "text": "The authorization failed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/notAuthorized"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@LARightState@LARightStateNotAuthorized",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notAuthorized"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LARightStateNotAuthorized"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "LARight.State.notAuthorized"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notAuthorized"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight": {
      "abstract": [
        {
          "text": "A grouped set of requirements that gate access to a resource or operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LARight"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LARight"
        }
      ],
      "role": "symbol",
      "title": "LARight",
      "type": "topic",
      "url": "/documentation/localauthentication/laright"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum": {
      "abstract": [
        {
          "text": "The possible states for a right during authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "LARight.State",
      "type": "topic",
      "url": "/documentation/localauthentication/laright/state-swift.enum"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/authorized": {
      "abstract": [
        {
          "text": "The authorization completed successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LARightStateAuthorized"
        }
      ],
      "role": "symbol",
      "title": "LARight.State.authorized",
      "type": "topic",
      "url": "/documentation/localauthentication/laright/state-swift.enum/authorized"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/authorizing": {
      "abstract": [
        {
          "text": "The authorization is in progress but not completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizing"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/authorizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LARightStateAuthorizing"
        }
      ],
      "role": "symbol",
      "title": "LARight.State.authorizing",
      "type": "topic",
      "url": "/documentation/localauthentication/laright/state-swift.enum/authorizing"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/notAuthorized": {
      "abstract": [
        {
          "text": "The authorization failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthorized"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/notAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LARightStateNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "LARight.State.notAuthorized",
      "type": "topic",
      "url": "/documentation/localauthentication/laright/state-swift.enum/notauthorized"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/unknown": {
      "abstract": [
        {
          "text": "The authorization is in an unknown state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LARightStateUnknown"
        }
      ],
      "role": "symbol",
      "title": "LARight.State.unknown",
      "type": "topic",
      "url": "/documentation/localauthentication/laright/state-swift.enum/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Authorization-states",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/authorizing",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/authorized",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/unknown"
      ],
      "title": "Authorization states"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LARightStateNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LARightStateNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Authorization-states",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/authorizing",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/authorized",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum/unknown"
              ],
              "title": "Authorization states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "LARightStateNotAuthorized"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight/title",
          "value": "LARight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LARight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LARight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum~1authorized/title",
          "value": "LARightStateAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LARightStateAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum~1authorizing/title",
          "value": "LARightStateAuthorizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum~1authorizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LARightStateAuthorizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum~1notAuthorized/title",
          "value": "LARightStateNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum~1notAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LARightStateNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum/title",
          "value": "LARightState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LARightState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LARightState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum~1unknown/title",
          "value": "LARightStateUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LARightStateUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/laright/state-swift.enum/notauthorized"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/laright/state-swift.enum/notauthorized"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
