{
  "abstract": [
    {
      "text": "The watch being off the wrist impacts the accuracy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/offWrist"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SRWristTemperatureCondition@SRWristTemperatureConditionOffWrist",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "offWrist"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRWristTemperature",
        "text": "SRWristTemperature"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SRWristTemperatureCondition",
        "text": "Condition"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRWristTemperatureConditionOffWrist"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "offWrist"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "offWrist"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRWristTemperature",
              "text": "SRWristTemperature"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SRWristTemperatureCondition",
              "text": "Condition"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature": {
      "abstract": [
        {
          "text": "The temperature of the user’s wrist while the user sleeps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRWristTemperature"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristTemperature"
        }
      ],
      "role": "symbol",
      "title": "SRWristTemperature",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct": {
      "abstract": [
        {
          "text": "The user activities with the watch that can impact the temperature measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Condition"
        }
      ],
      "role": "symbol",
      "title": "SRWristTemperature.Condition",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature/condition-swift.struct"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/inMotion": {
      "abstract": [
        {
          "text": "The watch being in motion impacts the accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inMotion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRWristTemperature",
          "text": "SRWristTemperature"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRWristTemperatureCondition",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/inMotion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristTemperatureConditionInMotion"
        }
      ],
      "role": "symbol",
      "title": "inMotion",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature/condition-swift.struct/inmotion"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/offWrist": {
      "abstract": [
        {
          "text": "The watch being off the wrist impacts the accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offWrist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRWristTemperature",
          "text": "SRWristTemperature"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRWristTemperatureCondition",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/offWrist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristTemperatureConditionOffWrist"
        }
      ],
      "role": "symbol",
      "title": "offWrist",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature/condition-swift.struct/offwrist"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/onCharger": {
      "abstract": [
        {
          "text": "The watch being on the charger impacts the accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onCharger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRWristTemperature",
          "text": "SRWristTemperature"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRWristTemperatureCondition",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/onCharger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristTemperatureConditionOnCharger"
        }
      ],
      "role": "symbol",
      "title": "onCharger",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature/condition-swift.struct/oncharger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Conditions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/onCharger",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/inMotion"
      ],
      "title": "Conditions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRWristTemperatureConditionOffWrist"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureConditionOffWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Conditions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/onCharger",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/inMotion"
              ],
              "title": "Conditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SRWristTemperatureConditionOffWrist"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1onCharger/title",
          "value": "SRWristTemperatureConditionOnCharger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1onCharger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureConditionOnCharger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1inMotion/title",
          "value": "SRWristTemperatureConditionInMotion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1inMotion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureConditionInMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct/title",
          "value": "SRWristTemperatureCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1offWrist/title",
          "value": "SRWristTemperatureConditionOffWrist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1offWrist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureConditionOffWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/title",
          "value": "SRWristTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperature"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srwristtemperature/condition-swift.struct/offwrist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srwristtemperature/condition-swift.struct/offwrist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
