{
  "abstract": [
    {
      "text": "Creates a capsule shape, a rounded rectangle with a corner radius equal to half the length of the rectangle’s smallest edge.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/capsuleShape"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIShape(cpy)capsuleShape",
    "fragments": [
      {
        "kind": "identifier",
        "text": "capsuleShape"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "capsuleShape"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "capsuleShape"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIShape",
              "text": "UIShape"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "capsuleShape"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICornerCurve": {
      "abstract": [
        {
          "text": "The corner curve to apply to a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICornerCurve"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICornerCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICornerCurve"
        }
      ],
      "role": "symbol",
      "title": "UICornerCurve",
      "type": "topic",
      "url": "/documentation/uikit/uicornercurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class": {
      "abstract": [
        {
          "text": "An abstract representation of a shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/capsuleShape": {
      "abstract": [
        {
          "text": "Creates a capsule shape, a rounded rectangle with a corner radius equal to half the length of the rectangle’s smallest edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "capsuleShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/capsuleShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "capsuleShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/capsuleshape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/circleShape": {
      "abstract": [
        {
          "text": "Creates a circular shape, with a radius equal to half the length of the frame rectangle’s smallest edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "circleShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/circleShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "circleShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/circleshape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:": {
      "abstract": [
        {
          "text": "Creates a fixed rectangular shape that uses the provided rectangle as its shape, regardless of the frame that contains it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:"
        }
      ],
      "role": "symbol",
      "title": "fixedRectShapeWithRect:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/fixedrectshapewithrect:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:": {
      "abstract": [
        {
          "text": "Creates a fixed rectangular shape with the provided corner radius, using the provided rectangle as its shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:"
        }
      ],
      "role": "symbol",
      "title": "fixedRectShapeWithRect:cornerRadius:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/fixedrectshapewithrect:cornerradius:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:": {
      "abstract": [
        {
          "text": "Creates a fixed rectangular shape with the provided corner radius and corner curve, using the provided rectangle as its shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "role": "symbol",
      "title": "fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/fixedrectshapewithrect:cornerradius:cornercurve:maskedcorners:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShape": {
      "abstract": [
        {
          "text": "Creates a rectangular shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "rectShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "rectShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:": {
      "abstract": [
        {
          "text": "Creates a rectangular shape with rounded corners, using the provided corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:"
        }
      ],
      "role": "symbol",
      "title": "rectShapeWithCornerRadius:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshapewithcornerradius:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:": {
      "abstract": [
        {
          "text": "Creates a rectangular shape with rounded corners, using the provided corner radius and corner curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:"
        }
      ],
      "role": "symbol",
      "title": "rectShapeWithCornerRadius:cornerCurve:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshapewithcornerradius:cornercurve:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:maskedCorners:": {
      "abstract": [
        {
          "text": "Creates a rectangular shape with rounded corners, using the provided corner radius, corner curve, and rectangle corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:maskedCorners:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "role": "symbol",
      "title": "rectShapeWithCornerRadius:cornerCurve:maskedCorners:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshapewithcornerradius:cornercurve:maskedcorners:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-hover-shape",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShape",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/circleShape",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:maskedCorners:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:",
        "doc://com.apple.uikit/documentation/UIKit/UICornerCurve"
      ],
      "title": "Creating a hover shape"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/title",
          "value": "UICornerCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uishape-c.class/capsuleshape"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
