{
  "abstract": [
    {
      "text": "Creates a circular shape, with a radius equal to half the length of the frame rectangle’s smallest edge.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/circle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit7UIShapeV6circleACvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "circle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit7UIShapeV",
        "text": "UIShape"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "circle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "circle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit7UIShapeV",
              "text": "UIShape"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICornerCurve": {
      "abstract": [
        {
          "text": "The corner curve to apply to a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICornerCurve"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICornerCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICornerCurve"
        }
      ],
      "role": "symbol",
      "title": "UICornerCurve",
      "type": "topic",
      "url": "/documentation/uikit/uicornercurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct": {
      "abstract": [
        {
          "text": "An abstract representation of a shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIShape"
        }
      ],
      "role": "symbol",
      "title": "UIShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/capsule": {
      "abstract": [
        {
          "text": "Creates a capsule shape, a rounded rectangle with a corner radius equal to half the length of the rectangle’s smallest edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capsule"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UIShapeV",
          "text": "UIShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/capsule",
      "kind": "symbol",
      "role": "symbol",
      "title": "capsule",
      "type": "topic",
      "url": "/documentation/uikit/uishape-swift.struct/capsule"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/circle": {
      "abstract": [
        {
          "text": "Creates a circular shape, with a radius equal to half the length of the frame rectangle’s smallest edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "circle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UIShapeV",
          "text": "UIShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/circle",
      "kind": "symbol",
      "role": "symbol",
      "title": "circle",
      "type": "topic",
      "url": "/documentation/uikit/uishape-swift.struct/circle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/fixedRect(_:cornerRadius:cornerCurve:maskedCorners:)": {
      "abstract": [
        {
          "text": "Creates a fixed rectangular shape that uses the provided rectangle as its shape, regardless of the frame that contains it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixedRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cornerRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cornerCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UICornerCurve",
          "text": "UICornerCurve"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maskedCorners"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRectCorner",
          "text": "UIRectCorner"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UIShapeV",
          "text": "UIShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/fixedRect(_:cornerRadius:cornerCurve:maskedCorners:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "fixedRect(_:cornerRadius:cornerCurve:maskedCorners:)",
      "type": "topic",
      "url": "/documentation/uikit/uishape-swift.struct/fixedrect(_:cornerradius:cornercurve:maskedcorners:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/rect": {
      "abstract": [
        {
          "text": "Creates a rectangular shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UIShapeV",
          "text": "UIShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/rect",
      "kind": "symbol",
      "role": "symbol",
      "title": "rect",
      "type": "topic",
      "url": "/documentation/uikit/uishape-swift.struct/rect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/rect(cornerRadius:cornerCurve:maskedCorners:)": {
      "abstract": [
        {
          "text": "Creates a rectangular shape with rounded corners, using the provided corner radius, corner curve, and rectangle corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "cornerRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cornerCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UICornerCurve",
          "text": "UICornerCurve"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maskedCorners"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRectCorner",
          "text": "UIRectCorner"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UIShapeV",
          "text": "UIShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/rect(cornerRadius:cornerCurve:maskedCorners:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "rect(cornerRadius:cornerCurve:maskedCorners:)",
      "type": "topic",
      "url": "/documentation/uikit/uishape-swift.struct/rect(cornerradius:cornercurve:maskedcorners:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-hover-shape",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/rect",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/capsule",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/rect(cornerRadius:cornerCurve:maskedCorners:)",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct/fixedRect(_:cornerRadius:cornerCurve:maskedCorners:)",
        "doc://com.apple.uikit/documentation/UIKit/UICornerCurve"
      ],
      "title": "Creating a hover shape"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/title",
          "value": "UICornerCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uishape-swift.struct/circle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
