{
  "abstract": [
    {
      "text": "The coefficient describing downward movement of the outer portion of the left eyebrow.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browDownLeft"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ARKit",
    "externalID": "c:@ARBlendShapeLocationBrowDownLeft",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "browDownLeft"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
        "text": "ARFaceAnchor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ARBlendShapeLocation",
        "text": "BlendShapeLocation"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARBlendShapeLocationBrowDownLeft"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "browDownLeft"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "browDownLeft"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
              "text": "ARFaceAnchor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ARBlendShapeLocation",
              "text": "BlendShapeLocation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The figure below shows a face geometry (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSCNFaceGeometry",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") in two states, demonstrating values of ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": " for this coefficient. In both states, the values for all other ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " coefficients are set to ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2930090",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor": {
      "abstract": [
        {
          "text": "An anchor for a unique face that is visible in the front-facing camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARFaceAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARFaceAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARFaceAnchor",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation": {
      "abstract": [
        {
          "text": "Identifiers for specific facial features, for use with coefficients describing the relative movements of those features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BlendShapeLocation"
        }
      ],
      "role": "symbol",
      "title": "ARFaceAnchor.BlendShapeLocation",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browDownLeft": {
      "abstract": [
        {
          "text": "The coefficient describing downward movement of the outer portion of the left eyebrow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "browDownLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browDownLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationBrowDownLeft"
        }
      ],
      "role": "symbol",
      "title": "browDownLeft",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/browdownleft"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browDownRight": {
      "abstract": [
        {
          "text": "The coefficient describing downward movement of the outer portion of the right eyebrow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "browDownRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browDownRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationBrowDownRight"
        }
      ],
      "role": "symbol",
      "title": "browDownRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/browdownright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browInnerUp": {
      "abstract": [
        {
          "text": "The coefficient describing upward movement of the inner portion of both eyebrows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "browInnerUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browInnerUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationBrowInnerUp"
        }
      ],
      "role": "symbol",
      "title": "browInnerUp",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/browinnerup"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browOuterUpLeft": {
      "abstract": [
        {
          "text": "The coefficient describing upward movement of the outer portion of the left eyebrow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "browOuterUpLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browOuterUpLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationBrowOuterUpLeft"
        }
      ],
      "role": "symbol",
      "title": "browOuterUpLeft",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/browouterupleft"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browOuterUpRight": {
      "abstract": [
        {
          "text": "The coefficient describing upward movement of the outer portion of the right eyebrow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "browOuterUpRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browOuterUpRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationBrowOuterUpRight"
        }
      ],
      "role": "symbol",
      "title": "browOuterUpRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/browouterupright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekPuff": {
      "abstract": [
        {
          "text": "The coefficient describing outward movement of both cheeks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cheekPuff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekPuff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationCheekPuff"
        }
      ],
      "role": "symbol",
      "title": "cheekPuff",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/cheekpuff"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekSquintLeft": {
      "abstract": [
        {
          "text": "The coefficient describing upward movement of the cheek around and below the left eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cheekSquintLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekSquintLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationCheekSquintLeft"
        }
      ],
      "role": "symbol",
      "title": "cheekSquintLeft",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/cheeksquintleft"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekSquintRight": {
      "abstract": [
        {
          "text": "The coefficient describing upward movement of the cheek around and below the right eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cheekSquintRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekSquintRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationCheekSquintRight"
        }
      ],
      "role": "symbol",
      "title": "cheekSquintRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/cheeksquintright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/noseSneerLeft": {
      "abstract": [
        {
          "text": "The coefficient describing a raising of the left side of the nose around the nostril.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noseSneerLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/noseSneerLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationNoseSneerLeft"
        }
      ],
      "role": "symbol",
      "title": "noseSneerLeft",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/nosesneerleft"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/noseSneerRight": {
      "abstract": [
        {
          "text": "The coefficient describing a raising of the right side of the nose around the nostril.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noseSneerRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/noseSneerRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationNoseSneerRight"
        }
      ],
      "role": "symbol",
      "title": "noseSneerRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/nosesneerright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSCNFaceGeometry": {
      "abstract": [
        {
          "text": "A SceneKit representation of face topology for use with face information that an AR session provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSCNFaceGeometry"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSCNFaceGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSCNFaceGeometry"
        }
      ],
      "role": "symbol",
      "title": "ARSCNFaceGeometry",
      "type": "topic",
      "url": "/documentation/arkit/arscnfacegeometry"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-2930090": {
      "alt": null,
      "identifier": "media-2930090",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5feff2496ffef93dc8ffd9c52307d421/media-2930090@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/379a82400ae92bc0424d09adaf0bbf14/media-2930090~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Eyebrows-Cheeks-and-Nose",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browDownRight",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browInnerUp",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browOuterUpLeft",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browOuterUpRight",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekPuff",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekSquintLeft",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekSquintRight",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/noseSneerLeft",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/noseSneerRight"
      ],
      "title": "Eyebrows, Cheeks, and Nose"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARBlendShapeLocationBrowDownLeft"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationBrowDownLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Eyebrows-Cheeks-and-Nose",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browDownRight",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browInnerUp",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browOuterUpLeft",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/browOuterUpRight",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekPuff",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekSquintLeft",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/cheekSquintRight",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/noseSneerLeft",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/noseSneerRight"
              ],
              "title": "Eyebrows, Cheeks, and Nose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ARBlendShapeLocation",
                    "text": "ARBlendShapeLocation"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARBlendShapeLocationBrowDownLeft"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1browInnerUp/title",
          "value": "ARBlendShapeLocationBrowInnerUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1browInnerUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationBrowInnerUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNFaceGeometry/title",
          "value": "ARSCNFaceGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNFaceGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSCNFaceGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNFaceGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSCNFaceGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1cheekPuff/title",
          "value": "ARBlendShapeLocationCheekPuff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1cheekPuff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationCheekPuff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1browOuterUpRight/title",
          "value": "ARBlendShapeLocationBrowOuterUpRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1browOuterUpRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationBrowOuterUpRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1cheekSquintLeft/title",
          "value": "ARBlendShapeLocationCheekSquintLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1cheekSquintLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationCheekSquintLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1noseSneerRight/title",
          "value": "ARBlendShapeLocationNoseSneerRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1noseSneerRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationNoseSneerRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation/title",
          "value": "ARBlendShapeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1noseSneerLeft/title",
          "value": "ARBlendShapeLocationNoseSneerLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1noseSneerLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationNoseSneerLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1cheekSquintRight/title",
          "value": "ARBlendShapeLocationCheekSquintRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1cheekSquintRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationCheekSquintRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1browDownLeft/title",
          "value": "ARBlendShapeLocationBrowDownLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1browDownLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationBrowDownLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1browOuterUpLeft/title",
          "value": "ARBlendShapeLocationBrowOuterUpLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1browOuterUpLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationBrowOuterUpLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor/title",
          "value": "ARFaceAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARFaceAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARFaceAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1browDownRight/title",
          "value": "ARBlendShapeLocationBrowDownRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1browDownRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationBrowDownRight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arfaceanchor/blendshapelocation/browdownleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arfaceanchor/blendshapelocation/browdownleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
