{
  "abstract": [
    {
      "text": "The coefficient describing contraction of the face around the right eye.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeSquintRight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ARKit",
    "externalID": "c:@ARBlendShapeLocationEyeSquintRight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "eyeSquintRight"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
        "text": "ARFaceAnchor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ARBlendShapeLocation",
        "text": "BlendShapeLocation"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARBlendShapeLocationEyeSquintRight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "eyeSquintRight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "eyeSquintRight"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
              "text": "ARFaceAnchor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ARBlendShapeLocation",
              "text": "BlendShapeLocation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The figure below shows a face geometry (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSCNFaceGeometry",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") in two states, demonstrating values of ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": " for this coefficient. In both states, the values for all other ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " coefficients are set to ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2929209",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor": {
      "abstract": [
        {
          "text": "An anchor for a unique face that is visible in the front-facing camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARFaceAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARFaceAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARFaceAnchor",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation": {
      "abstract": [
        {
          "text": "Identifiers for specific facial features, for use with coefficients describing the relative movements of those features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BlendShapeLocation"
        }
      ],
      "role": "symbol",
      "title": "ARFaceAnchor.BlendShapeLocation",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeBlinkRight": {
      "abstract": [
        {
          "text": "The coefficient describing closure of the eyelids over the right eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eyeBlinkRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeBlinkRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationEyeBlinkRight"
        }
      ],
      "role": "symbol",
      "title": "eyeBlinkRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/eyeblinkright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookDownRight": {
      "abstract": [
        {
          "text": "The coefficient describing movement of the right eyelids consistent with a downward gaze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eyeLookDownRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookDownRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationEyeLookDownRight"
        }
      ],
      "role": "symbol",
      "title": "eyeLookDownRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/eyelookdownright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookInRight": {
      "abstract": [
        {
          "text": "The coefficient describing movement of the right eyelids consistent with a leftward gaze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eyeLookInRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookInRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationEyeLookInRight"
        }
      ],
      "role": "symbol",
      "title": "eyeLookInRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/eyelookinright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookOutRight": {
      "abstract": [
        {
          "text": "The coefficient describing movement of the right eyelids consistent with a rightward gaze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eyeLookOutRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookOutRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationEyeLookOutRight"
        }
      ],
      "role": "symbol",
      "title": "eyeLookOutRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/eyelookoutright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookUpRight": {
      "abstract": [
        {
          "text": "The coefficient describing movement of the right eyelids consistent with an upward gaze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eyeLookUpRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookUpRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationEyeLookUpRight"
        }
      ],
      "role": "symbol",
      "title": "eyeLookUpRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/eyelookupright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeSquintRight": {
      "abstract": [
        {
          "text": "The coefficient describing contraction of the face around the right eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eyeSquintRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeSquintRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationEyeSquintRight"
        }
      ],
      "role": "symbol",
      "title": "eyeSquintRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/eyesquintright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeWideRight": {
      "abstract": [
        {
          "text": "The coefficient describing a widening of the eyelids around the right eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eyeWideRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARBlendShapeLocation",
          "text": "BlendShapeLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeWideRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBlendShapeLocationEyeWideRight"
        }
      ],
      "role": "symbol",
      "title": "eyeWideRight",
      "type": "topic",
      "url": "/documentation/arkit/arfaceanchor/blendshapelocation/eyewideright"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSCNFaceGeometry": {
      "abstract": [
        {
          "text": "A SceneKit representation of face topology for use with face information that an AR session provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSCNFaceGeometry"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSCNFaceGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSCNFaceGeometry"
        }
      ],
      "role": "symbol",
      "title": "ARSCNFaceGeometry",
      "type": "topic",
      "url": "/documentation/arkit/arscnfacegeometry"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-2929209": {
      "alt": null,
      "identifier": "media-2929209",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/dbf9ef4b8ff3d33d8db963c447b38c35/media-2929209@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6243b1d28c235e788c5c6558a44e8712/media-2929209~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Right-Eye",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeBlinkRight",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookDownRight",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookInRight",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookOutRight",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookUpRight",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeWideRight"
      ],
      "title": "Right Eye"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARBlendShapeLocationEyeSquintRight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationEyeSquintRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Right-Eye",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeBlinkRight",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookDownRight",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookInRight",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookOutRight",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeLookUpRight",
                "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation/eyeWideRight"
              ],
              "title": "Right Eye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceAnchor/BlendShapeLocation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ARBlendShapeLocation",
                    "text": "ARBlendShapeLocation"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARBlendShapeLocationEyeSquintRight"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeLookDownRight/title",
          "value": "ARBlendShapeLocationEyeLookDownRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeLookDownRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationEyeLookDownRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor/title",
          "value": "ARFaceAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARFaceAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARFaceAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation/title",
          "value": "ARBlendShapeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeSquintRight/title",
          "value": "ARBlendShapeLocationEyeSquintRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeSquintRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationEyeSquintRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeBlinkRight/title",
          "value": "ARBlendShapeLocationEyeBlinkRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeBlinkRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationEyeBlinkRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeLookOutRight/title",
          "value": "ARBlendShapeLocationEyeLookOutRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeLookOutRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationEyeLookOutRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeWideRight/title",
          "value": "ARBlendShapeLocationEyeWideRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeWideRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationEyeWideRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeLookUpRight/title",
          "value": "ARBlendShapeLocationEyeLookUpRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeLookUpRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationEyeLookUpRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNFaceGeometry/title",
          "value": "ARSCNFaceGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNFaceGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSCNFaceGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNFaceGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSCNFaceGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeLookInRight/title",
          "value": "ARBlendShapeLocationEyeLookInRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceAnchor~1BlendShapeLocation~1eyeLookInRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBlendShapeLocationEyeLookInRight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arfaceanchor/blendshapelocation/eyesquintright"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arfaceanchor/blendshapelocation/eyesquintright"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
