{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyListenerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyListenerDelegate/propertiesChanged(properties:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9CoreAudio24PropertyListenerDelegateP17propertiesChanged0F0ySaySo0b6ObjectC7AddressVG_tF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "propertiesChanged"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "properties"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
        "text": "AudioObjectPropertyAddress"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "propertiesChanged(properties:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "propertiesChanged"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "properties"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
              "text": "AudioObjectPropertyAddress"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyAddress",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyaddress"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyListenerDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PropertyListenerDelegate"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyListenerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PropertyListenerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PropertyListenerDelegate",
      "type": "topic",
      "url": "/documentation/coreaudio/propertylistenerdelegate"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyListenerDelegate/propertiesChanged(properties:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertiesChanged"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "properties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyListenerDelegate/propertiesChanged(properties:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "propertiesChanged(properties:)",
      "type": "topic",
      "url": "/documentation/coreaudio/propertylistenerdelegate/propertieschanged(properties:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/title",
          "value": "AudioObjectPropertyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/propertylistenerdelegate/propertieschanged(properties:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
