{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter/includedApplications"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCContentFilter(py)includedApplications",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "includedApplications"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SCRunningApplication",
        "text": "SCRunningApplication"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "includedApplications"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "includedApplications"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "includedApplications"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRunningApplication",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCRunningApplication",
              "text": "SCRunningApplication"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter": {
      "abstract": [
        {
          "text": "An instance that filters the content a stream captures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCContentFilter"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentFilter"
        }
      ],
      "role": "symbol",
      "title": "SCContentFilter",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentfilter"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter/includedApplications": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includedApplications"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCRunningApplication",
          "text": "SCRunningApplication"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter/includedApplications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "includedApplications"
        }
      ],
      "role": "symbol",
      "title": "includedApplications",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentfilter/includedapplications"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRunningApplication": {
      "abstract": [
        {
          "text": "An instance that represents an app running on a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCRunningApplication"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRunningApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCRunningApplication"
        }
      ],
      "role": "symbol",
      "title": "SCRunningApplication",
      "type": "topic",
      "url": "/documentation/screencapturekit/scrunningapplication"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "includedApplications"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includedApplications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<SCRunningApplication *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "includedApplications"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter/title",
          "value": "SCContentFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRunningApplication/title",
          "value": "SCRunningApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRunningApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRunningApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRunningApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRunningApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter~1includedApplications/title",
          "value": "includedApplications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter~1includedApplications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includedApplications"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit/sccontentfilter/includedapplications"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screencapturekit/sccontentfilter/includedapplications"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
