{
  "abstract": [
    {
      "text": "The properties and methods that conform to the option set protocol.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.VisionKit/documentation/VisionKit",
        "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer",
        "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/Configuration",
        "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/AnalysisTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.VisionKit/documentation/VisionKit/analysistypes-set-properties-and-methods"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "VisionKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Set properties and methods"
  },
  "references": {
    "doc://com.apple.VisionKit/documentation/VisionKit": {
      "abstract": [
        {
          "text": "Identify and extract information in the environment using the device’s camera, or in images that your app displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit",
      "kind": "symbol",
      "role": "collection",
      "title": "VisionKit",
      "type": "topic",
      "url": "/documentation/visionkit"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer": {
      "abstract": [
        {
          "text": "An object that finds items in images that people can interact with, such",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "as subjects, text, and QR codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImageAnalyzer"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImageAnalyzer"
        }
      ],
      "role": "symbol",
      "title": "ImageAnalyzer",
      "type": "topic",
      "url": "/documentation/visionkit/imageanalyzer"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/AnalysisTypes": {
      "abstract": [
        {
          "text": "The types of items that an image analyzer looks for in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnalysisTypes"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/AnalysisTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnalysisTypes"
        }
      ],
      "role": "symbol",
      "title": "ImageAnalyzer.AnalysisTypes",
      "type": "topic",
      "url": "/documentation/visionkit/imageanalyzer/analysistypes"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/AnalysisTypes/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates an analysis type with the given value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/AnalysisTypes/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/visionkit/imageanalyzer/analysistypes/init(rawvalue:)"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/AnalysisTypes/rawValue": {
      "abstract": [
        {
          "text": "A unique, underlying value for the analysis type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/AnalysisTypes/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/visionkit/imageanalyzer/analysistypes/rawvalue"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/Configuration": {
      "abstract": [
        {
          "text": "A configuration that specifies the types of items and locales that the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "image analyzer recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/Configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "ImageAnalyzer.Configuration",
      "type": "topic",
      "url": "/documentation/visionkit/imageanalyzer/configuration"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-sets",
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/AnalysisTypes/init(rawValue:)",
        "doc://com.apple.VisionKit/documentation/VisionKit/ImageAnalyzer/AnalysisTypes/rawValue"
      ],
      "title": "Creating sets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/visionkit/analysistypes-set-properties-and-methods"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/visionkit/analysistypes-set-properties-and-methods"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
