{
  "abstract": [
    {
      "text": "An object that scans the camera live video for text, data in text, and",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "machine-readable codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.VisionKit/documentation/VisionKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@M@VisionKit@objc(cs)DataScannerViewController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DataScannerViewController"
      }
    ],
    "modules": [
      {
        "name": "VisionKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DataScannerViewController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "DataScannerViewController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@objc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DataScannerViewController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.VisionKit/documentation/VisionKit/scanning-data-with-the-camera"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "code": "DataScannerViewController",
              "type": "codeVoice"
            },
            {
              "text": " object to get input from physical objects",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that appear in the camera’s live video, such as printed text and QR codes on",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "packages.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create a data scanner by passing parameters that configure the interface to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/init(recognizedDataTypes:qualityLevel:recognizesMultipleItems:isHighFrameRateTrackingEnabled:isPinchToZoomEnabled:isGuidanceEnabled:isHighlightingEnabled:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "initializer. Then set its delegate to an object in your app that implements",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewControllerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before presenting the view controller, check whether the data scanner is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "available using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isSupported",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isAvailable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. Before you can use the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "data scanner, you must provide a reason for using the camera (add the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSCameraUsageDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "key to the information property list), and a person must agree when the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "system dialog first appears.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Then begin data scanning by invoking the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/startScanning()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method and implement the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewControllerDelegate/dataScanner(_:didTapOn:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "similar delegate methods to handle user actions. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/RecognizedItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "parameter passed to these methods to perform data-specific actions. For",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "example, if the item is a QR code, perform an action with its payload",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "string, such as opening a URL in a browser, or calling a phone number.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Alternatively, you can track items that appear in the live video using the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "asynchronous ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/recognizedItems",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.VisionKit/documentation/VisionKit": {
      "abstract": [
        {
          "text": "Identify and extract information in the environment using the device’s camera, or in images that your app displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit",
      "kind": "symbol",
      "role": "collection",
      "title": "VisionKit",
      "type": "topic",
      "url": "/documentation/visionkit"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController": {
      "abstract": [
        {
          "text": "An object that scans the camera live video for text, data in text, and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "machine-readable codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataScannerViewController"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataScannerViewController"
        }
      ],
      "role": "symbol",
      "title": "DataScannerViewController",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/QualityLevel-swift.enum": {
      "abstract": [
        {
          "text": "The possible quality levels that the scanner uses to find data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QualityLevel"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/QualityLevel-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QualityLevel"
        }
      ],
      "role": "symbol",
      "title": "DataScannerViewController.QualityLevel",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/qualitylevel-swift.enum"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/RecognizedDataType": {
      "abstract": [
        {
          "text": "A type of data that the scanner recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RecognizedDataType"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/RecognizedDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RecognizedDataType"
        }
      ],
      "role": "symbol",
      "title": "DataScannerViewController.RecognizedDataType",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/recognizeddatatype"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/ScanningUnavailable": {
      "abstract": [
        {
          "text": "The possible reasons the data scanner is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScanningUnavailable"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/ScanningUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScanningUnavailable"
        }
      ],
      "role": "symbol",
      "title": "DataScannerViewController.ScanningUnavailable",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/scanningunavailable"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/TextContentType": {
      "abstract": [
        {
          "text": "Types of text that a data scanner recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextContentType"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/TextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextContentType"
        }
      ],
      "role": "symbol",
      "title": "DataScannerViewController.TextContentType",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/textcontenttype"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/capturePhoto()": {
      "abstract": [
        {
          "text": "Captures a high-resolution photo of the camera’s live video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capturePhoto"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/capturePhoto()",
      "kind": "symbol",
      "role": "symbol",
      "title": "capturePhoto()",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/capturephoto()"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/delegate": {
      "abstract": [
        {
          "text": "The delegate that handles user interaction with items recognized by the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "data scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9VisionKit33DataScannerViewControllerDelegateP",
          "text": "DataScannerViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/delegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/delegate"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/init(recognizedDataTypes:qualityLevel:recognizesMultipleItems:isHighFrameRateTrackingEnabled:isPinchToZoomEnabled:isGuidanceEnabled:isHighlightingEnabled:)": {
      "abstract": [
        {
          "text": "Creates a scanner for finding data, such as text and machine-readable",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "codes, in the camera’s live video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "recognizedDataTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@VisionKit@objc(cs)DataScannerViewController",
          "text": "DataScannerViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9VisionKit25DataScannerViewControllerC010RecognizedC4TypeV",
          "text": "RecognizedDataType"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "qualityLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@VisionKit@objc(cs)DataScannerViewController",
          "text": "DataScannerViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9VisionKit25DataScannerViewControllerC12QualityLevelO",
          "text": "QualityLevel"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "recognizesMultipleItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isHighFrameRateTrackingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isPinchToZoomEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isGuidanceEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isHighlightingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/init(recognizedDataTypes:qualityLevel:recognizesMultipleItems:isHighFrameRateTrackingEnabled:isPinchToZoomEnabled:isGuidanceEnabled:isHighlightingEnabled:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(recognizedDataTypes:qualityLevel:recognizesMultipleItems:isHighFrameRateTrackingEnabled:isPinchToZoomEnabled:isGuidanceEnabled:isHighlightingEnabled:)",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/init(recognizeddatatypes:qualitylevel:recognizesmultipleitems:ishighframeratetrackingenabled:ispinchtozoomenabled:isguidanceenabled:ishighlightingenabled:)"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a person grants your app access",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to the camera and doesn’t have any restrictions to using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "isAvailable",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/isavailable"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isGuidanceEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the scanner provides help to a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "person when selecting items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isGuidanceEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isGuidanceEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isGuidanceEnabled",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/isguidanceenabled"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isHighFrameRateTrackingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines the frequency at which the scanner",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "updates the geometry of recognized items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHighFrameRateTrackingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isHighFrameRateTrackingEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isHighFrameRateTrackingEnabled",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/ishighframeratetrackingenabled"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isHighlightingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the scanner displays highlights",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "around recognized items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHighlightingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isHighlightingEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isHighlightingEnabled",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/ishighlightingenabled"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isPinchToZoomEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether people can use a two-finger",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "pinch-to-zoom gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPinchToZoomEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isPinchToZoomEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isPinchToZoomEnabled",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/ispinchtozoomenabled"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isScanning": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the data scanner is actively looking",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "for items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isScanning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isScanning",
      "kind": "symbol",
      "role": "symbol",
      "title": "isScanning",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/isscanning"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device supports data",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "scanning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSupported",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/issupported"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/loadView()": {
      "abstract": [
        {
          "text": "Creates the view that the controller manages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadView"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/loadView()",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadView()",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/loadview()"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/maxZoomFactor": {
      "abstract": [
        {
          "text": "The maximum zoom factor that the camera supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxZoomFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/maxZoomFactor",
      "kind": "symbol",
      "role": "symbol",
      "title": "maxZoomFactor",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/maxzoomfactor"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/minZoomFactor": {
      "abstract": [
        {
          "text": "The minimum zoom factor that the camera supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minZoomFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/minZoomFactor",
      "kind": "symbol",
      "role": "symbol",
      "title": "minZoomFactor",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/minzoomfactor"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/overlayContainerView": {
      "abstract": [
        {
          "text": "A view that the data scanner displays over its view without interfering",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "with the Live Text interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlayContainerView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/overlayContainerView",
      "kind": "symbol",
      "role": "symbol",
      "title": "overlayContainerView",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/overlaycontainerview"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/qualityLevel-swift.property": {
      "abstract": [
        {
          "text": "The resolution that the scanner uses to find data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "qualityLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@VisionKit@objc(cs)DataScannerViewController",
          "text": "DataScannerViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9VisionKit25DataScannerViewControllerC12QualityLevelO",
          "text": "QualityLevel"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/qualityLevel-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "qualityLevel",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/qualitylevel-swift.property"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/recognizedDataTypes": {
      "abstract": [
        {
          "text": "The types of data that the data scanner identifies in the live video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognizedDataTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@VisionKit@objc(cs)DataScannerViewController",
          "text": "DataScannerViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9VisionKit25DataScannerViewControllerC010RecognizedC4TypeV",
          "text": "RecognizedDataType"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/recognizedDataTypes",
      "kind": "symbol",
      "role": "symbol",
      "title": "recognizedDataTypes",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/recognizeddatatypes"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/recognizedItems": {
      "abstract": [
        {
          "text": "An asynchronous array of items that the data scanner currently",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "recognizes in the camera’s live video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognizedItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ScS",
          "text": "AsyncStream"
        },
        {
          "kind": "text",
          "text": "<["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9VisionKit14RecognizedItemO",
          "text": "RecognizedItem"
        },
        {
          "kind": "text",
          "text": "]>"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/recognizedItems",
      "kind": "symbol",
      "role": "symbol",
      "title": "recognizedItems",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/recognizeditems"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/recognizesMultipleItems": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the scanner should identify all",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "items in the live video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognizesMultipleItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/recognizesMultipleItems",
      "kind": "symbol",
      "role": "symbol",
      "title": "recognizesMultipleItems",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/recognizesmultipleitems"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/regionOfInterest": {
      "abstract": [
        {
          "text": "The area of the live video in view coordinates that the data scanner",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "searches for items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionOfInterest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/regionOfInterest",
      "kind": "symbol",
      "role": "symbol",
      "title": "regionOfInterest",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/regionofinterest"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/removeFromParent()": {
      "abstract": [
        {
          "text": "Removes the view controller from its parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeFromParent"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/removeFromParent()",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeFromParent()",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/removefromparent()"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/startScanning()": {
      "abstract": [
        {
          "text": "Starts scanning the camera’s live video for data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startScanning"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/startScanning()",
      "kind": "symbol",
      "role": "symbol",
      "title": "startScanning()",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/startscanning()"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/stopScanning()": {
      "abstract": [
        {
          "text": "Stops scanning the camera’s live video for data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopScanning"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/stopScanning()",
      "kind": "symbol",
      "role": "symbol",
      "title": "stopScanning()",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/stopscanning()"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/supportedTextRecognitionLanguages": {
      "abstract": [
        {
          "text": "The identifiers for the languages that the data scanner recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedTextRecognitionLanguages"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/supportedTextRecognitionLanguages",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedTextRecognitionLanguages",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/supportedtextrecognitionlanguages"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/viewDidDisappear(_:)": {
      "abstract": [
        {
          "text": "Performs some action after the view disappears.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidDisappear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/viewDidDisappear(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewDidDisappear(_:)",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/viewdiddisappear(_:)"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/viewDidLoad()": {
      "abstract": [
        {
          "text": "Performs some action after the system loads the view into memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidLoad"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/viewDidLoad()",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewDidLoad()",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/viewdidload()"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/viewWillAppear(_:)": {
      "abstract": [
        {
          "text": "Performs some action before the view appears.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillAppear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/viewWillAppear(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewWillAppear(_:)",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/viewwillappear(_:)"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/zoomFactor": {
      "abstract": [
        {
          "text": "The zoom factor for the live video in the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoomFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/zoomFactor",
      "kind": "symbol",
      "role": "symbol",
      "title": "zoomFactor",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontroller/zoomfactor"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewControllerDelegate": {
      "abstract": [
        {
          "text": "A delegate object that responds when people interact with items that the data",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "scanner recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataScannerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataScannerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "DataScannerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontrollerdelegate"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewControllerDelegate/dataScanner(_:didTapOn:)": {
      "abstract": [
        {
          "text": "Responds when a person taps an item that the data scanner recognizes.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataScanner"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@VisionKit@objc(cs)DataScannerViewController",
          "text": "DataScannerViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didTapOn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9VisionKit14RecognizedItemO",
          "text": "RecognizedItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewControllerDelegate/dataScanner(_:didTapOn:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "dataScanner(_:didTapOn:)",
      "type": "topic",
      "url": "/documentation/visionkit/datascannerviewcontrollerdelegate/datascanner(_:didtapon:)"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/RecognizedItem": {
      "abstract": [
        {
          "text": "An item that the data scanner recognizes in the camera’s live video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RecognizedItem"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/RecognizedItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RecognizedItem"
        }
      ],
      "role": "symbol",
      "title": "RecognizedItem",
      "type": "topic",
      "url": "/documentation/visionkit/recognizeditem"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/scanning-data-with-the-camera": {
      "abstract": [
        {
          "text": "Enable Live Text data scanning of text and codes that appear in the camera’s viewfinder.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/scanning-data-with-the-camera",
      "kind": "article",
      "role": "article",
      "title": "Scanning data with the camera",
      "type": "topic",
      "url": "/documentation/visionkit/scanning-data-with-the-camera"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSCameraUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the device’s camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSCameraUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCameraUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSCameraUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/UIKit/UIViewController"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling": {
      "abstract": [
        {
          "text": "The interface an app extension uses to respond to a request from a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionRequestHandling",
      "type": "topic",
      "url": "/documentation/foundation/nsextensionrequesthandling"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding": {
      "abstract": [
        {
          "text": "An interface that provides a source for shareable content to fulfill user requests to share current content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationProviding"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIActivityItemsConfigurationProviding",
      "type": "topic",
      "url": "/documentation/UIKit/UIActivityItemsConfigurationProviding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer": {
      "abstract": [
        {
          "text": "A protocol that a class must adopt to allow appearance customization using the [`UIAppearance`](doc://com.apple.uikit/documentation/UIKit/UIAppearance) API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAppearanceContainer",
      "type": "topic",
      "url": "/documentation/UIKit/UIAppearanceContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer": {
      "abstract": [
        {
          "text": "A set of methods for adapting the contents of your view controllers to size and trait changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentContainer",
      "type": "topic",
      "url": "/documentation/UIKit/UIContentContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that define the focus behavior for a branch of the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIFocusEnvironment",
      "type": "topic",
      "url": "/documentation/UIKit/UIFocusEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting": {
      "abstract": [
        {
          "text": "The interface that determines whether a responder object supports paste configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteConfigurationSupporting",
      "type": "topic",
      "url": "/documentation/UIKit/UIPasteConfigurationSupporting"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions": {
      "abstract": [
        {
          "text": "A set of standard methods that apps can adopt to support editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIResponderStandardEditActions"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIResponderStandardEditActions",
      "type": "topic",
      "url": "/documentation/UIKit/UIResponderStandardEditActions"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring": {
      "abstract": [
        {
          "text": "Methods for adding objects to your state restoration archives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStateRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIStateRestoring",
      "type": "topic",
      "url": "/documentation/UIKit/UIStateRestoring"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring": {
      "abstract": [
        {
          "text": "The protocol you adopt to restore an object’s state from a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/UIKit/UIUserActivityRestoring"
    },
    "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitChangeObservable-67e94"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring",
        "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP",
        "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Barcode-and-text-scanning-through-the-camera",
      "generated": true,
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/scanning-data-with-the-camera",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewControllerDelegate",
        "doc://com.apple.VisionKit/documentation/VisionKit/RecognizedItem"
      ],
      "title": "Barcode and text scanning through the camera"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-availability",
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isSupported",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isAvailable",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/supportedTextRecognitionLanguages",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/ScanningUnavailable"
      ],
      "title": "Handling availability"
    },
    {
      "anchor": "Creating-data-scanners",
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/init(recognizedDataTypes:qualityLevel:recognizesMultipleItems:isHighFrameRateTrackingEnabled:isPinchToZoomEnabled:isGuidanceEnabled:isHighlightingEnabled:)",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/recognizedDataTypes",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/RecognizedDataType"
      ],
      "title": "Creating data scanners"
    },
    {
      "anchor": "Configuring-data-scanners",
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/delegate",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/qualityLevel-swift.property",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/QualityLevel-swift.enum",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/recognizesMultipleItems",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isHighFrameRateTrackingEnabled",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isPinchToZoomEnabled",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isGuidanceEnabled",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isHighlightingEnabled"
      ],
      "title": "Configuring data scanners"
    },
    {
      "anchor": "Zooming",
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/zoomFactor",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/minZoomFactor",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/maxZoomFactor"
      ],
      "title": "Zooming"
    },
    {
      "anchor": "Scanning-and-recognizing-items",
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/startScanning()",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/stopScanning()",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/isScanning",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/recognizedItems"
      ],
      "title": "Scanning and recognizing items"
    },
    {
      "anchor": "Capturing-photos",
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/capturePhoto()"
      ],
      "title": "Capturing photos"
    },
    {
      "anchor": "Customizing-the-interface",
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/overlayContainerView",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/regionOfInterest"
      ],
      "title": "Customizing the interface"
    },
    {
      "anchor": "Responding-to-view-controller-events",
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/loadView()",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/viewDidLoad()",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/viewWillAppear(_:)",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/viewDidDisappear(_:)",
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/removeFromParent()"
      ],
      "title": "Responding to view controller events"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/DataScannerViewController/TextContentType"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIResponderStandardEditActions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIResponderStandardEditActions"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIActivityItemsConfigurationProviding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationProviding"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIContentContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIStateRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIStateRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIFocusEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIPasteConfigurationSupporting/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIAppearanceContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIResponder",
              "text": "UIResponder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/visionkit/datascannerviewcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
