{
  "abstract": [
    {
      "text": "A single document scanned in the document camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.VisionKit/documentation/VisionKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNDocumentCameraScan",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNDocumentCameraScan"
      }
    ],
    "modules": [
      {
        "name": "VisionKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNDocumentCameraScan"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNDocumentCameraScan"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNDocumentCameraScan"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the document camera scans a document, it returns the resulting information in",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "this format, through the delegate method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewController(_:didFinishWith:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.VisionKit/documentation/VisionKit": {
      "abstract": [
        {
          "text": "Identify and extract information in the environment using the device’s camera, or in images that your app displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit",
      "kind": "symbol",
      "role": "collection",
      "title": "VisionKit",
      "type": "topic",
      "url": "/documentation/visionkit"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan": {
      "abstract": [
        {
          "text": "A single document scanned in the document camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDocumentCameraScan"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDocumentCameraScan"
        }
      ],
      "role": "symbol",
      "title": "VNDocumentCameraScan",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcamerascan"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/imageOfPage(at:)": {
      "abstract": [
        {
          "text": "Requests the image of a page at a specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageOfPage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/imageOfPage(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageOfPageAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "imageOfPage(at:)",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcamerascan/imageofpage(at:)"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/pageCount": {
      "abstract": [
        {
          "text": "The number of pages in the scanned document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/pageCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageCount"
        }
      ],
      "role": "symbol",
      "title": "pageCount",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcamerascan/pagecount"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/title": {
      "abstract": [
        {
          "text": "The title of the scanned document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcamerascan/title"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewController": {
      "abstract": [
        {
          "text": "An object that presents UI for a camera pass-through that helps people scan physical documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDocumentCameraViewController"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDocumentCameraViewController"
        }
      ],
      "role": "symbol",
      "title": "VNDocumentCameraViewController",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcameraviewcontroller"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol through which the document camera returns its scanned results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDocumentCameraViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDocumentCameraViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "VNDocumentCameraViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcameraviewcontrollerdelegate"
    },
    "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewController(_:didFinishWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user successfully saved a scanned document from the document camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentCameraViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNDocumentCameraViewController",
          "text": "VNDocumentCameraViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNDocumentCameraScan",
          "text": "VNDocumentCameraScan"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate/documentCameraViewController(_:didFinishWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentCameraViewController:didFinishWithScan:"
        }
      ],
      "role": "symbol",
      "title": "documentCameraViewController(_:didFinishWith:)",
      "type": "topic",
      "url": "/documentation/visionkit/vndocumentcameraviewcontrollerdelegate/documentcameraviewcontroller(_:didfinishwith:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/visionkit/structuring_recognized_text_on_a_document": {
      "abstract": [
        {
          "text": "Detect, recognize, and structure text on a business card or receipt using Vision and VisionKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionkit/structuring_recognized_text_on_a_document",
      "kind": "article",
      "role": "sampleCode",
      "title": "Structuring Recognized Text on a Document",
      "type": "topic",
      "url": "/documentation/visionkit/structuring_recognized_text_on_a_document"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Document-scanning-through-the-camera",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/visionkit/structuring_recognized_text_on_a_document",
        "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewController",
        "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate"
      ],
      "title": "Document scanning through the camera"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reading-the-scanned-document",
      "identifiers": [
        "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/title",
        "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/pageCount",
        "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/imageOfPage(at:)"
      ],
      "title": "Reading the scanned document"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNDocumentCameraScan"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.VisionKit/documentation/VisionKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reading-the-scanned-document",
              "identifiers": [
                "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/title",
                "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/pageCount",
                "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraScan/imageOfPage(at:)"
              ],
              "title": "Reading the scanned document"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Document-scanning-through-the-camera",
              "generated": true,
              "identifiers": [
                "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewController",
                "doc://com.apple.VisionKit/documentation/VisionKit/VNDocumentCameraViewControllerDelegate"
              ],
              "title": "Document scanning through the camera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNDocumentCameraScan"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraScan/title",
          "value": "VNDocumentCameraScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraScan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraScan/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewController/title",
          "value": "VNDocumentCameraViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraScan~1imageOfPage(at:)/title",
          "value": "imageOfPageAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraScan~1imageOfPage(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageOfPageAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate/title",
          "value": "VNDocumentCameraViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDocumentCameraViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraScan~1pageCount/title",
          "value": "pageCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraScan~1pageCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraScan~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraScan~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate~1documentCameraViewController(_:didFinishWith:)/title",
          "value": "documentCameraViewController:didFinishWithScan:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.VisionKit~1documentation~1VisionKit~1VNDocumentCameraViewControllerDelegate~1documentCameraViewController(_:didFinishWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentCameraViewController:didFinishWithScan:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/visionkit/vndocumentcamerascan"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/visionkit/vndocumentcamerascan"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
