{
  "abstract": [
    {
      "text": "Index error codes and error domain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/csindex-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CSIndex Errors"
  },
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError": {
      "abstract": [
        {
          "text": "Index errors returned by Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSIndexError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexError"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code": {
      "abstract": [
        {
          "text": "Error codes that describe indexing-specific errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for the index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSIndexErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CSIndexErrorDomain",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerrordomain"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryError": {
      "abstract": [
        {
          "text": "Search query errors returned by Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQueryError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQueryError"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQueryError",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchqueryerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors": {
      "abstract": [
        {
          "text": "Search query error codes and error domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CSSearchQuery Errors",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery-errors"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Index-Errors",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexErrorDomain"
      ],
      "title": "Index Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Index-Errors",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexErrorDomain"
              ],
              "title": "Index Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexErrorDomain/title",
          "value": "CSIndexErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code/title",
          "value": "CSIndexErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/csindex-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corespotlight/csindex-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
