{
  "abstract": [
    {
      "text": "Index errors returned by Core Spotlight.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC16CSIndexErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CSIndexError"
      }
    ],
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSIndexError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CSIndexError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSIndexError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError": {
      "abstract": [
        {
          "text": "Index errors returned by Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSIndexError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexError"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code": {
      "abstract": [
        {
          "text": "Error codes that describe indexing-specific errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/errordomain"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/indexUnavailableError": {
      "abstract": [
        {
          "text": "The indexer is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexUnavailableError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC16CSIndexErrorCodeLeV",
          "text": "CSIndexError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CSIndexErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/indexUnavailableError",
      "kind": "symbol",
      "role": "symbol",
      "title": "indexUnavailableError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/indexunavailableerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/indexingUnsupported": {
      "abstract": [
        {
          "text": "Indexing isn’t supported on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexingUnsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC16CSIndexErrorCodeLeV",
          "text": "CSIndexError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CSIndexErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/indexingUnsupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "indexingUnsupported",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/indexingunsupported"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/invalidClientStateError": {
      "abstract": [
        {
          "text": "The provided client state data is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidClientStateError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC16CSIndexErrorCodeLeV",
          "text": "CSIndexError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CSIndexErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/invalidClientStateError",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidClientStateError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/invalidclientstateerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/invalidItemError": {
      "abstract": [
        {
          "text": "The searchable item object is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidItemError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC16CSIndexErrorCodeLeV",
          "text": "CSIndexError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CSIndexErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/invalidItemError",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidItemError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/invaliditemerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/mismatchedClientState": {
      "abstract": [
        {
          "text": "The provided client state did not match the information in the index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mismatchedClientState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC16CSIndexErrorCodeLeV",
          "text": "CSIndexError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CSIndexErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/mismatchedClientState",
      "kind": "symbol",
      "role": "symbol",
      "title": "mismatchedClientState",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/mismatchedclientstate"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/quotaExceeded": {
      "abstract": [
        {
          "text": "The quota for the bundle has been exceeded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quotaExceeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC16CSIndexErrorCodeLeV",
          "text": "CSIndexError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CSIndexErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/quotaExceeded",
      "kind": "symbol",
      "role": "symbol",
      "title": "quotaExceeded",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/quotaexceeded"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/remoteConnectionError": {
      "abstract": [
        {
          "text": "An error occurred while communicating with the remote process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteConnectionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC16CSIndexErrorCodeLeV",
          "text": "CSIndexError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CSIndexErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/remoteConnectionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "remoteConnectionError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/remoteconnectionerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/unknownError": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC16CSIndexErrorCodeLeV",
          "text": "CSIndexError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CSIndexErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/unknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/unknownerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryError": {
      "abstract": [
        {
          "text": "Search query errors returned by Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQueryError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQueryError"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQueryError",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchqueryerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/csindex-errors": {
      "abstract": [
        {
          "text": "Index error codes and error domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/csindex-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CSIndex Errors",
      "type": "topic",
      "url": "/documentation/corespotlight/csindex-errors"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors": {
      "abstract": [
        {
          "text": "Search query error codes and error domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CSSearchQuery Errors",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery-errors"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/csindex-errors",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-error-codes",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/indexUnavailableError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/indexingUnsupported",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/invalidClientStateError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/invalidItemError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/mismatchedClientState",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/quotaExceeded",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/remoteConnectionError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/unknownError"
      ],
      "title": "Getting the error codes"
    },
    {
      "anchor": "Getting-codes-for-indexing-errors",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code"
      ],
      "title": "Getting codes for indexing errors"
    },
    {
      "anchor": "Getting-the-error-description",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/errorDomain"
      ],
      "title": "Getting the error description"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code/title",
          "value": "CSIndexErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/csindexerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
