{
  "abstract": [
    {
      "text": "A type you use to initiate searches from your interface and",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "offer suggested text completions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CSUserQuery",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CSUserQuery"
      }
    ],
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSUserQuery"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CSUserQuery"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "CSUserQuery",
              "type": "codeVoice"
            },
            {
              "text": " object provides the back-end support for your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app’s search features. Combine this object with your app’s search",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interface to perform lexical and semantic searches of human-entered",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "search terms. You can configure a query object to return ranked",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or unranked results. You can also use it to get a list of suggestions",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to display from your search interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the text in your search control changes, create a query object",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to begin searching for results based on the current text. You use a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "query object only once to perform a search. If the text changes again",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "while you a previous query is in progress, cancel the old query and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "execute the new one. For this reason, it’s a good idea to delay the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "start of each query until there is a sufficient gap between changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Configure the query parameters using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "which you can reuse for multiple queries. The context lets you configure",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the behavior for ranking results, specify the maximum number of results",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and suggestions, and filter the results using a predicate string. When",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you’re ready to start the query, choose one of the following options:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Get the value of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/responses-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property and iterate over the results.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/foundItemsHandler",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property and call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/start()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to execute the query manually.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Each query runs until Spotlight returns the requested maximum number",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of results. If you don’t specify the maximum number of results, Spotlight",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "runs until it returns all results. To end a search before you receive all",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the results, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/cancel()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Cancelling a query is especially",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "important if you’re about to start a new query with an updated search string.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about configuring a ",
              "type": "text"
            },
            {
              "code": "CSUserQuery",
              "type": "codeVoice"
            },
            {
              "text": " object,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery": {
      "abstract": [
        {
          "text": "A type you use to programmatically search the indexed app content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQuery"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQuery"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQuery",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/foundItemsHandler": {
      "abstract": [
        {
          "text": "The block to execute when the query delivers a new batch of matching items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foundItemsHandler"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSSearchableItem",
          "text": "CSSearchableItem"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/foundItemsHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "foundItemsHandler"
        }
      ],
      "role": "symbol",
      "title": "foundItemsHandler",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery/founditemshandler"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext": {
      "abstract": [
        {
          "text": "The behavior configuration to use for a search query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQueryContext"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQueryContext"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQueryContext",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquerycontext"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion": {
      "abstract": [
        {
          "text": "The kind of suggestion to use in a query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSuggestion"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSuggestion"
        }
      ],
      "role": "symbol",
      "title": "CSSuggestion",
      "type": "topic",
      "url": "/documentation/corespotlight/cssuggestion"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery": {
      "abstract": [
        {
          "text": "A type you use to initiate searches from your interface and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "offer suggested text completions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSUserQuery"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSUserQuery"
        }
      ],
      "role": "symbol",
      "title": "CSUserQuery",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Item": {
      "abstract": [
        {
          "text": "A search result that the query returns in a response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Item"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Item",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Item"
        }
      ],
      "role": "symbol",
      "title": "CSUserQuery.Item",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/item"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Responses-swift.struct": {
      "abstract": [
        {
          "text": "An asynchronous sequence that contains the results and suggestions",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "for a query string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Responses"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Responses-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Responses"
        }
      ],
      "role": "symbol",
      "title": "CSUserQuery.Responses",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/responses-swift.struct"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Suggestion": {
      "abstract": [
        {
          "text": "A suggested text completion for a query’s search term.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Suggestion"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Suggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Suggestion"
        }
      ],
      "role": "symbol",
      "title": "CSUserQuery.Suggestion",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/suggestion"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Suggestions-swift.struct": {
      "abstract": [
        {
          "text": "An asynchronous sequence that contains the suggested completions",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "for a search string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Suggestions"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Suggestions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Suggestions"
        }
      ],
      "role": "symbol",
      "title": "CSUserQuery.Suggestions",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/suggestions-swift.struct"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/UserInteractionKind": {
      "abstract": [
        {
          "text": "Constants that indicate how someone engaged with search-related content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UserInteractionKind"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/UserInteractionKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UserInteractionKind"
        }
      ],
      "role": "symbol",
      "title": "CSUserQuery.UserInteractionKind",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/userinteractionkind"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/cancel()": {
      "abstract": [
        {
          "text": "Cancels the current query operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/cancel()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "role": "symbol",
      "title": "cancel()",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/cancel()"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/foundSuggestionCount": {
      "abstract": [
        {
          "text": "The number of suggested items the query found so far.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foundSuggestionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/foundSuggestionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "foundSuggestionCount"
        }
      ],
      "role": "symbol",
      "title": "foundSuggestionCount",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/foundsuggestioncount"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/foundSuggestionsHandler": {
      "abstract": [
        {
          "text": "The block to execute when the query delivers a new batch of suggested items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foundSuggestionsHandler"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSSuggestion",
          "text": "CSSuggestion"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/foundSuggestionsHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "foundSuggestionsHandler"
        }
      ],
      "role": "symbol",
      "title": "foundSuggestionsHandler",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/foundsuggestionshandler"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/init(userQueryString:userQueryContext:)": {
      "abstract": [
        {
          "text": "Creates a new user query that searches for the specified term.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "userQueryString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "userQueryContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSUserQueryContext",
          "text": "CSUserQueryContext"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/init(userQueryString:userQueryContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUserQueryString:userQueryContext:"
        }
      ],
      "role": "symbol",
      "title": "init(userQueryString:userQueryContext:)",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/init(userquerystring:userquerycontext:)"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/prepare()": {
      "abstract": [
        {
          "text": "Performs one-time tasks that prepare Spotlight to search for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "content in all search indexes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/prepare()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepare"
        }
      ],
      "role": "symbol",
      "title": "prepare()",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/prepare()"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/prepareProtectionClasses(_:)": {
      "abstract": [
        {
          "text": "Performs one-time tasks that prepare Spotlight to search for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "content in one or more protected search indexes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareProtectionClasses"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProtectionType",
          "text": "FileProtectionType"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/prepareProtectionClasses(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareProtectionClasses:"
        }
      ],
      "role": "symbol",
      "title": "prepareProtectionClasses(_:)",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/prepareprotectionclasses(_:)"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/responses-swift.property": {
      "abstract": [
        {
          "text": "The matching results and suggestions for the current query string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "responses"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSUserQuery",
          "text": "CSUserQuery"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So11CSUserQueryC13CoreSpotlightE9ResponsesV",
          "text": "Responses"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/responses-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "responses",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/responses-swift.property"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/start()": {
      "abstract": [
        {
          "text": "Starts searching the index for items that match the current query",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "string and parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/start()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "start"
        }
      ],
      "role": "symbol",
      "title": "start()",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/start()"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/suggestions-swift.property": {
      "abstract": [
        {
          "text": "An asynchronous sequence of suggested completions for the current query text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suggestions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSUserQuery",
          "text": "CSUserQuery"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So11CSUserQueryC13CoreSpotlightE11SuggestionsV",
          "text": "Suggestions"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/suggestions-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "suggestions",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/suggestions-swift.property"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngaged(_:visibleItems:interaction:)": {
      "abstract": [
        {
          "text": "Notifies the system that someone engaged with a specific search",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "result in your app’s interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userEngaged"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSUserQuery",
          "text": "CSUserQuery"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So11CSUserQueryC13CoreSpotlightE4ItemV",
          "text": "Item"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "visibleItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSUserQuery",
          "text": "CSUserQuery"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So11CSUserQueryC13CoreSpotlightE4ItemV",
          "text": "Item"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "interaction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSUserQuery",
          "text": "CSUserQuery"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CSUserInteraction",
          "text": "UserInteractionKind"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngaged(_:visibleItems:interaction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "userEngaged(_:visibleItems:interaction:)",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/userengaged(_:visibleitems:interaction:)"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngaged(_:visibleSuggestions:interaction:)": {
      "abstract": [
        {
          "text": "Notifies the system that someone engaged with a specific text",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "completion in your app’s interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userEngaged"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSUserQuery",
          "text": "CSUserQuery"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So11CSUserQueryC13CoreSpotlightE10SuggestionV",
          "text": "Suggestion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "visibleSuggestions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSUserQuery",
          "text": "CSUserQuery"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So11CSUserQueryC13CoreSpotlightE10SuggestionV",
          "text": "Suggestion"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "interaction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSUserQuery",
          "text": "CSUserQuery"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CSUserInteraction",
          "text": "UserInteractionKind"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngaged(_:visibleSuggestions:interaction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "userEngaged(_:visibleSuggestions:interaction:)",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/userengaged(_:visiblesuggestions:interaction:)"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngagedWithItem:visibleItems:userInteractionType:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "userEngagedWithItem:visibleItems:userInteractionType:"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngagedWithItem:visibleItems:userInteractionType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userEngagedWithItem:visibleItems:userInteractionType:"
        }
      ],
      "role": "symbol",
      "title": "userEngagedWithItem:visibleItems:userInteractionType:",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/userengagedwithitem:visibleitems:userinteractiontype:"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngagedWithSuggestion:visibleSuggestions:userInteractionType:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "userEngagedWithSuggestion:visibleSuggestions:userInteractionType:"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngagedWithSuggestion:visibleSuggestions:userInteractionType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userEngagedWithSuggestion:visibleSuggestions:userInteractionType:"
        }
      ],
      "role": "symbol",
      "title": "userEngagedWithSuggestion:visibleSuggestions:userInteractionType:",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery/userengagedwithsuggestion:visiblesuggestions:userinteractiontype:"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext": {
      "abstract": [
        {
          "text": "The configuration details to apply to a user query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSUserQueryContext"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSUserQueryContext"
        }
      ],
      "role": "symbol",
      "title": "CSUserQueryContext",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app": {
      "abstract": [
        {
          "text": "Add a search interface to your app to execute Spotlight queries",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and offer suggested text completions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Building a search interface for your app",
      "type": "topic",
      "url": "/documentation/corespotlight/building-a-search-interface-for-your-app"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app": {
      "abstract": [
        {
          "text": "Search for app-specific content and refine search results using",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "predicates and filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Searching for information in your app",
      "type": "topic",
      "url": "/documentation/corespotlight/searching-for-information-in-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Queries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion"
      ],
      "title": "Queries"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-user-query",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/init(userQueryString:userQueryContext:)"
      ],
      "title": "Creating a user query"
    },
    {
      "anchor": "Preparing-to-search",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/prepare()",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/prepareProtectionClasses(_:)"
      ],
      "title": "Preparing to search"
    },
    {
      "anchor": "Executing-the-query-automatically",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/responses-swift.property",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/suggestions-swift.property",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Responses-swift.struct",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Suggestions-swift.struct",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Item",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/Suggestion"
      ],
      "title": "Executing the query automatically"
    },
    {
      "anchor": "Executing-the-query-with-handler-blocks",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/start()",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/cancel()",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/foundSuggestionsHandler",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/foundSuggestionCount"
      ],
      "title": "Executing the query with handler blocks"
    },
    {
      "anchor": "Improving-the-quality-of-ranked-results",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngaged(_:visibleItems:interaction:)",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngaged(_:visibleSuggestions:interaction:)",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/UserInteractionKind"
      ],
      "title": "Improving the quality of ranked results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CSUserQuery"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-user-query",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/init(userQueryString:userQueryContext:)"
              ],
              "title": "Creating a user query"
            },
            {
              "anchor": "Preparing-to-search",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/prepare()",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/prepareProtectionClasses(_:)"
              ],
              "title": "Preparing to search"
            },
            {
              "anchor": "Executing-the-query-with-handler-blocks",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/start()",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/cancel()",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/foundSuggestionsHandler",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/foundSuggestionCount"
              ],
              "title": "Executing the query with handler blocks"
            },
            {
              "anchor": "Improving-the-quality-of-ranked-results",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/UserInteractionKind"
              ],
              "title": "Improving the quality of ranked results"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngagedWithItem:visibleItems:userInteractionType:",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery/userEngagedWithSuggestion:visibleSuggestions:userInteractionType:"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Queries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion"
              ],
              "title": "Queries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CSUserQuery"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CSSearchQuery",
                    "text": "CSSearchQuery"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1prepare()/title",
          "value": "prepare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1prepare()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "prepare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/title",
          "value": "CSUserQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery~1foundItemsHandler/title",
          "value": "foundItemsHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery~1foundItemsHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "foundItemsHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1init(userQueryString:userQueryContext:)/title",
          "value": "initWithUserQueryString:userQueryContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1init(userQueryString:userQueryContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithUserQueryString:userQueryContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1foundSuggestionCount/title",
          "value": "foundSuggestionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1foundSuggestionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "foundSuggestionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/title",
          "value": "CSSearchQueryContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1foundSuggestionsHandler/title",
          "value": "foundSuggestionsHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1foundSuggestionsHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "foundSuggestionsHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1prepareProtectionClasses(_:)/title",
          "value": "prepareProtectionClasses:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1prepareProtectionClasses(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "prepareProtectionClasses:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/title",
          "value": "CSSearchQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1cancel()/title",
          "value": "cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1cancel()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/title",
          "value": "CSUserQueryContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/title",
          "value": "CSSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1start()/title",
          "value": "start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1start()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1UserInteractionKind/title",
          "value": "CSUserInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1UserInteractionKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery~1UserInteractionKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserInteraction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/csuserquery"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corespotlight/csuserquery"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
