{
  "abstract": [
    {
      "text": "The configuration details to apply to a user query.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CSUserQueryContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CSUserQueryContext"
      }
    ],
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSUserQueryContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CSUserQueryContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an instance of ",
              "type": "text"
            },
            {
              "code": "CSUserQueryContext",
              "type": "codeVoice"
            },
            {
              "text": " to configure the search",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "parameters for a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. This object stores",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "configuration details that the query uses to modify the search",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "results it delivers. For example, use this object to specify the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "maximum number of results or suggestions you want the query to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "return. You can also use it to enable or disable the ranking of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "results by Spotlight.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about search filters and other configurable query",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "parameters, see the parent class ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery": {
      "abstract": [
        {
          "text": "A type you use to programmatically search the indexed app content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQuery"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQuery"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQuery",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext": {
      "abstract": [
        {
          "text": "The behavior configuration to use for a search query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQueryContext"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQueryContext"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQueryContext",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquerycontext"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion": {
      "abstract": [
        {
          "text": "The kind of suggestion to use in a query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSuggestion"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSuggestion"
        }
      ],
      "role": "symbol",
      "title": "CSSuggestion",
      "type": "topic",
      "url": "/documentation/corespotlight/cssuggestion"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery": {
      "abstract": [
        {
          "text": "A type you use to initiate searches from your interface and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "offer suggested text completions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSUserQuery"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSUserQuery"
        }
      ],
      "role": "symbol",
      "title": "CSUserQuery",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext": {
      "abstract": [
        {
          "text": "The configuration details to apply to a user query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSUserQueryContext"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSUserQueryContext"
        }
      ],
      "role": "symbol",
      "title": "CSUserQueryContext",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/disableSemanticSearch": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to exclude semantic-based",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "search results from the output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableSemanticSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/disableSemanticSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableSemanticSearch"
        }
      ],
      "role": "symbol",
      "title": "disableSemanticSearch",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext/disablesemanticsearch"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/enableRankedResults": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the query sorts results",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "by their relevance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableRankedResults"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/enableRankedResults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableRankedResults"
        }
      ],
      "role": "symbol",
      "title": "enableRankedResults",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext/enablerankedresults"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/init(currentSuggestion:)": {
      "abstract": [
        {
          "text": "Creates a new query context object with an optional suggested search string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "currentSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSSuggestion",
          "text": "CSSuggestion"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/init(currentSuggestion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userQueryContextWithCurrentSuggestion:"
        }
      ],
      "role": "symbol",
      "title": "init(currentSuggestion:)",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext/init(currentsuggestion:)"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxRankedResultCount": {
      "abstract": [
        {
          "text": "The maximum number of ranked results to return during the query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxRankedResultCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxRankedResultCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxRankedResultCount"
        }
      ],
      "role": "symbol",
      "title": "maxRankedResultCount",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext/maxrankedresultcount"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxResultCount": {
      "abstract": [
        {
          "text": "The maximum number of search results for the query to return.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxResultCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxResultCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxResultCount"
        }
      ],
      "role": "symbol",
      "title": "maxResultCount",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext/maxresultcount"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxSuggestionCount": {
      "abstract": [
        {
          "text": "The maximum number of suggested text completions for the query to return.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxSuggestionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxSuggestionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxSuggestionCount"
        }
      ],
      "role": "symbol",
      "title": "maxSuggestionCount",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext/maxsuggestioncount"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/userQueryContext": {
      "abstract": [
        {
          "text": "Returns the current behavior configuration for the user query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "userQueryContext"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/userQueryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userQueryContext"
        }
      ],
      "role": "symbol",
      "title": "userQueryContext",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext/userquerycontext"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app": {
      "abstract": [
        {
          "text": "Add a search interface to your app to execute Spotlight queries",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and offer suggested text completions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Building a search interface for your app",
      "type": "topic",
      "url": "/documentation/corespotlight/building-a-search-interface-for-your-app"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app": {
      "abstract": [
        {
          "text": "Search for app-specific content and refine search results using",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "predicates and filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Searching for information in your app",
      "type": "topic",
      "url": "/documentation/corespotlight/searching-for-information-in-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Queries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion"
      ],
      "title": "Queries"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-query-context",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/init(currentSuggestion:)"
      ],
      "title": "Creating a query context"
    },
    {
      "anchor": "Configuring-search-options",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxResultCount",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxSuggestionCount",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/disableSemanticSearch"
      ],
      "title": "Configuring search options"
    },
    {
      "anchor": "Configuring-the-ranked-results-behavior",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/enableRankedResults",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxRankedResultCount"
      ],
      "title": "Configuring the ranked results behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CSUserQueryContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-query-context",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/init(currentSuggestion:)"
              ],
              "title": "Creating a query context"
            },
            {
              "anchor": "Configuring-search-options",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxResultCount",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxSuggestionCount",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/disableSemanticSearch"
              ],
              "title": "Configuring search options"
            },
            {
              "anchor": "Configuring-the-ranked-results-behavior",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/enableRankedResults",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/maxRankedResultCount"
              ],
              "title": "Configuring the ranked results behavior"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext/userQueryContext"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Queries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion"
              ],
              "title": "Queries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CSUserQueryContext"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CSSearchQueryContext",
                    "text": "CSSearchQueryContext"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/title",
          "value": "CSUserQueryContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1disableSemanticSearch/title",
          "value": "disableSemanticSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1disableSemanticSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disableSemanticSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/title",
          "value": "CSSearchQueryContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/title",
          "value": "CSSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/title",
          "value": "CSUserQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1enableRankedResults/title",
          "value": "enableRankedResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1enableRankedResults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enableRankedResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1maxRankedResultCount/title",
          "value": "maxRankedResultCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1maxRankedResultCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxRankedResultCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1maxResultCount/title",
          "value": "maxResultCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1maxResultCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxResultCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1maxSuggestionCount/title",
          "value": "maxSuggestionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1maxSuggestionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxSuggestionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/title",
          "value": "CSSearchQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1init(currentSuggestion:)/title",
          "value": "userQueryContextWithCurrentSuggestion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext~1init(currentSuggestion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "userQueryContextWithCurrentSuggestion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/csuserquerycontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corespotlight/csuserquerycontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
