{
  "abstract": [
    {
      "text": "Search for app-specific content and refine search results using",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "predicates and filters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Searching for information in your app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Add search capabilities to your app to find relevant information quickly.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Instead of building your own custom search tools, index your content",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "using the Core Spotlight APIs and use the framework-provided queries",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to retrieve information. Indexing your content makes it available",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to both your app and to the system’s Spotlight search feature.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to execute a search of your app’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "indexed content. With this query object, you specify which attributes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of an item to match, and the values that constitute a match. For example,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you might tell the query to look for media clips with a duration in a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "specific range. Although you might incorporate input from your app’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "UI when building your query string, use this query type to match",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "specific attributes of your indexed content. For information about",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "how to search based solely on input from a person, see",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Select-the-attributes-you-want-the-query-to-retrieve",
          "level": 3,
          "text": "Select the attributes you want the query to retrieve",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you execute a query, the system doesn’t automatically retrieve",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "every property of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. Instead, it",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "retrieves only the properties you specifically request. This",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "behavior improves performance by not spending time to retrieve information",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app doesn’t need.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Identify the properties you want, and specify the property names as",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "strings when you initialize your query. For example, to fetch the title",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and display name of each item, include “title” and “displayName” strings",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext/fetchAttributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of your context object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-query-string-for-your-search",
          "level": 3,
          "text": "Create a query string for your search",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you execute a query, Core Spotlight evaluates each item in the index",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "against a query string you provide. Construct your query string from one",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or more predicates, and use each predicate to evaluate an attribute of the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "indexed item. If the predicates in the overall query string evaluate to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "true for an item, the query object returns the item in the search results.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For each predicate in your query string, use one of the following formats:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "attributeName operator value[modifiers]",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "InRange(attributeName, minValue, maxValue)",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "In both formats, ",
              "type": "text"
            },
            {
              "code": "attributeName",
              "type": "codeVoice"
            },
            {
              "text": " is a property name from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "class. For example, to evaluate the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/title",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property of the item, use “title” as the attribute name. The ",
              "type": "text"
            },
            {
              "code": "InRange",
              "type": "codeVoice"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "predicate determines whether a property with a numeric value is between",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the specified minimum and maxium values. Other predicates compare the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "attribute to the value you specify using one of the following operators:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Operator",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Definition",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "==",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Equal.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "!=",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Not equal.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "<",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Less than. Works only for numeric and date values.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": ">",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Greater than. Works only for numeric and date values.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "<=",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Less than or equal. Works only for numeric and date values.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": ">=",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Greater than or equal. Works only for numeric and date values.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "When comparing text values, use modifiers to change the matching behavior",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the query applies to the comparison. Queries support the following modifiers:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Modifier",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Behavior",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "c",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Performs a case-insensitive search.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "d",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Performs a search that ignores diacritical marks.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "w",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches on word boundaries. This modifier treats transitions from lowercase to uppercase as word boundaries.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "t",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Performs a search on a tokenized value. For example, a search field can contain tokenized values.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "*",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Performs a wildcard search. Match a substring at the beginning, end, or middle.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "\\",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Don’t interpret the character that follows. Use this to include special characters. Examples include ",
                      "type": "text"
                    },
                    {
                      "code": "\\’",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "\\”",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Combine two predicates using either an AND or OR operation, listed in the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "table below. Use parentheses to prioritize the evaluation of predicates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Combination operator",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Definition",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "&&",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "AND operator. If both predicates are true, the entire result is true. If one predicate is false, the result is false.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "||",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "OR operator. If either predicate is true, the entire result is true. Otherwise, the result is false.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "The following examples show how operators, modifiers, and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "parentheses work for query strings. When trying to match a specific word,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "notice that the ",
              "type": "text"
            },
            {
              "code": "w",
              "type": "codeVoice"
            },
            {
              "text": " modifier is more precise than a wildcard because of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "how it matches word boundaries.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Query string",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Example matches",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "title == “Paris”",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches “Paris” but not “paris” or “I love Paris”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "title == “Paris”c",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches “Paris” and “paris”, but not “I love Paris”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "title == “Paris”wc",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches “Paris”, “paris”, “I love Paris”, and “paris-france.jpg”, but not “Comparison”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "title == “Window”w",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches “MyWindowClass” and “Broken Window”, but not “NSWindow”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "authorNames == “Frédéric”",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches “Frédéric”, but not “Frederic”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "authorNames == “Frédéric”cd",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches “Frédéric” and “Frederic”, regardless of case.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "title == “paris*”",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches words that begin with “paris” like “paris” and “parisol” but not “comparison”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "title == “*paris”",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches words that end with “paris”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "title == “*paris*”",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches words that contain “paris” anywhere in the string, including “paris”, “parisol”, and “comparison”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "title == ‘paris’",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches a value that is exactly equal to “paris”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "authorNames == “Steve”wc && contentType == “audio”wc’",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches audio items that Steve authored.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "authorNames == \"Steve\"wc && (contentType == \"audio\"wc || contentType == \"video\"wc)",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches any audio or video items that Steve authored.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "anchor": "Match-dates-and-times-in-a-query-string",
          "level": 3,
          "text": "Match dates and times in a query string",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When an attribute contains a date or time value, there are two ways you can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "specify the value portion of your predicate:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify a floating-point value with the number of seconds relative to January 1, 2001. You can get this value from a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdate-rv5",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/date",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " type using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1542812-cfdategetabsolutetime",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify a property of the built-in ",
                      "type": "text"
                    },
                    {
                      "code": "$time",
                      "type": "codeVoice"
                    },
                    {
                      "text": " variable.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides the ",
              "type": "text"
            },
            {
              "code": "$time",
              "type": "codeVoice"
            },
            {
              "text": " variable as a convenient way",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to specify date values in your query strings. When you start a query,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the system initializes this variable to the current date and time.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Include this variable in the value portion of your predicate to compare",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a date-based attribute to the date you specify. The following table",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "lists the properties of the variable you can use in your predicates and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "how the query matches them against attributes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.now",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches an attribute set to the current date and time.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.today",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches an attribute set to the current date.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.yesterday",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches an attribute set to yesterday’s date.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.last_week",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches an attribute set to a date from the week before the current week.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.this_week",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches an attribute set to a date from this week.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.this_month",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches an attribute set to a date in the current month.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.this_year",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches an attribute set to a date in the current year.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.now(NUMBER)",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Adds ",
                      "type": "text"
                    },
                    {
                      "code": "NUMBER",
                      "type": "codeVoice"
                    },
                    {
                      "text": " seconds to the current date and time and matches the attribute against that value. You can specify negative or positive numbers.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.today(NUMBER)",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Adds ",
                      "type": "text"
                    },
                    {
                      "code": "NUMBER",
                      "type": "codeVoice"
                    },
                    {
                      "text": " days to the current date and matches the attribute against that value. You can specify negative or positive numbers.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.this_week(NUMBER)",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Adds ",
                      "type": "text"
                    },
                    {
                      "code": "NUMBER",
                      "type": "codeVoice"
                    },
                    {
                      "text": " weeks to the current date and matches the attribute against that value. You can specify negative or positive numbers.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.this_month(NUMBER)",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Adds ",
                      "type": "text"
                    },
                    {
                      "code": "NUMBER",
                      "type": "codeVoice"
                    },
                    {
                      "text": " months to the current date and matches the attribute against that value. You can specify negative or positive numbers.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.this_year(NUMBER)",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Adds ",
                      "type": "text"
                    },
                    {
                      "code": "NUMBER",
                      "type": "codeVoice"
                    },
                    {
                      "text": " years to the current date and matches the attribute against that value. You can specify negative or positive numbers.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "$time.iso(ISO-8601-STR)",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Matches the date you specify using an ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://www.iso.org/iso-8601-date-and-time-format.html",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " compliant string.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "The following example shows a query string that includes different types",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of predicates and modifiers and uses the ",
              "type": "text"
            },
            {
              "code": "$time",
              "type": "codeVoice"
            },
            {
              "text": " variable. The predicate",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "matches an item if author is either Tim or Steve and the item’s completion",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "date occurred within the past 10 days. For the completion date check,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "adding a negative number to the ",
              "type": "text"
            },
            {
              "code": "$time.today",
              "type": "codeVoice"
            },
            {
              "text": " variable creates a date",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in the past.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "(authorNames == “Tim”wc || authorNames == “Steve”wc) &&",
            " InRange(completionDate,$time.today(-10),$time.today)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Start-the-query-and-process-the-results",
          "level": 3,
          "text": "Start the query and process the results",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Search queries are one-shot objects. While they run, they deliver matching",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "items asynchronously to the handlers you provide. When there are no more",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "items, the query stops. You can also stop a query early by calling its",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/cancel()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method before the system delivers all matching",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create a new query using a query string and a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "which contains the query configuration parameters. Start the query by",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "fetching the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/results-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the query object and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "iterating over the results. The property contains an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/AsyncSequence",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and fetching",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "it starts the query and begins the delivery of the results. The following",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "function searches for items with a specific title and processes the results",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in an asynchronous task:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import CoreSpotlight",
            "",
            "class QueryExample {",
            "    func executeQuery(withTitle title : String) {",
            "        var results = [CSSearchableItem]()",
            "        // Fetch the items with a title that starts with the",
            "        // specified string. Perform a case-insensitive comparison.",
            "        let queryString = \"title == '\\(title)*'c\"",
            "    ",
            "        let context = CSSearchQueryContext()",
            "        context.fetchAttributes = [\"title\", \"displayName\", \"keywords\", \"contentType\"]",
            "    ",
            "       // Create the query and specify a handler for the results.",
            "        let query = CSSearchQuery(queryString: queryString, queryContext: context)",
            "    ",
            "        // Process the results asynchronously.",
            "        Task {",
            "            do {",
            "                // Start the query and iterate over the results.",
            "                for try await result in query.results {",
            "                    let attributeSet = result.item.attributeSet",
            "                    let foundTitle = attributeSet.title",
            "                    let foundDisplayName = attributeSet.displayName",
            "                ",
            "                    // Use the results here.",
            "                }",
            "            } catch {",
            "                // Handle any errors.",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If you prefer not to process the results using an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/AsyncSequence",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", specify values",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/foundItemsHandler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/completionHandler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "properties. When using handler blocks, you’re responsible for calling",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/start()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to start the query. To deliver results,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the query calls your  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/foundItemsHandler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " block one or more",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "times, delivering new results with each call. The system executes your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "completion handler block only once after it finishes delivering all the results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Process results using either the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/results-swift.property",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "or handler blocks, but not both.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows a version of the previous method that uses handler",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "blocks to process the results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import CoreSpotlight",
            "",
            "class QueryExample {",
            "    private var query : CSSearchQuery? = nil",
            "    mutating func executeQueryWithHandlers(withTitle title : String) {",
            "        var results = [CSSearchableItem]()",
            "        // Fetch the items with a title that starts with the",
            "        // specified string. Perform a case-insensitive comparison.",
            "        let queryString = \"title == '\\(title)*'c\"",
            "        ",
            "        let context = CSSearchQueryContext()",
            "        context.fetchAttributes = [\"title\", \"displayName\", \"keywords\", \"contentType\"]",
            "        ",
            "        // Create the query and specify a handler for the results.",
            "        self.query = CSSearchQuery(queryString: queryString, queryContext: context)",
            "        self.query?.foundItemsHandler = { (items : [CSSearchableItem]) -> Void in",
            "            results.append(contentsOf: items)",
            "        }",
            "        ",
            "        // Display the results when the query finishes.",
            "        self.query?.completionHandler = { (error) -> Void in",
            "            if error == nil {",
            "                for item in results {",
            "                    let attributeSet = item.attributeSet",
            "                    let foundTitle = attributeSet.title",
            "                    let foundDisplayName = attributeSet.displayName",
            "                    ",
            "                    // Use the results here.",
            "                }",
            "            } else {",
            "                // Handle the error.",
            "            }",
            "        }",
            "                      ",
            "        // Start the query.",
            "        self.query?.start()",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery": {
      "abstract": [
        {
          "text": "A type you use to programmatically search the indexed app content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQuery"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQuery"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQuery",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/cancel()": {
      "abstract": [
        {
          "text": "Cancels the current query operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/cancel()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "role": "symbol",
      "title": "cancel()",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery/cancel()"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/completionHandler": {
      "abstract": [
        {
          "text": "The block to execute when the query finishes delivering all results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/completionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionHandler"
        }
      ],
      "role": "symbol",
      "title": "completionHandler",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery/completionhandler"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/foundItemsHandler": {
      "abstract": [
        {
          "text": "The block to execute when the query delivers a new batch of matching items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foundItemsHandler"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSSearchableItem",
          "text": "CSSearchableItem"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/foundItemsHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "foundItemsHandler"
        }
      ],
      "role": "symbol",
      "title": "foundItemsHandler",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery/founditemshandler"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/results-swift.property": {
      "abstract": [
        {
          "text": "The results that match the current query string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "results"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSSearchQuery",
          "text": "CSSearchQuery"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So13CSSearchQueryC13CoreSpotlightE7ResultsV",
          "text": "Results"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/results-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "results",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery/results-swift.property"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/start()": {
      "abstract": [
        {
          "text": "Starts searching the index for items that match the current query string and parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/start()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "start"
        }
      ],
      "role": "symbol",
      "title": "start()",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery/start()"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext": {
      "abstract": [
        {
          "text": "The behavior configuration to use for a search query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQueryContext"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQueryContext"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQueryContext",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquerycontext"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext/fetchAttributes": {
      "abstract": [
        {
          "text": "The attributes the system fetches for the searchable items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext/fetchAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchAttributes"
        }
      ],
      "role": "symbol",
      "title": "fetchAttributes",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquerycontext/fetchattributes"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem": {
      "abstract": [
        {
          "text": "The details of your app-specific content that someone might search",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "for on their devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableItem"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchableItem"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableItem",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitem"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet": {
      "abstract": [
        {
          "text": "The detailed metadata for a searchable item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableItemAttributeSet"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchableItemAttributeSet"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableItemAttributeSet",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/title": {
      "abstract": [
        {
          "text": "The title of the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/title"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion": {
      "abstract": [
        {
          "text": "The kind of suggestion to use in a query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSuggestion"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSuggestion"
        }
      ],
      "role": "symbol",
      "title": "CSSuggestion",
      "type": "topic",
      "url": "/documentation/corespotlight/cssuggestion"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery": {
      "abstract": [
        {
          "text": "A type you use to initiate searches from your interface and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "offer suggested text completions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSUserQuery"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSUserQuery"
        }
      ],
      "role": "symbol",
      "title": "CSUserQuery",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext": {
      "abstract": [
        {
          "text": "The configuration details to apply to a user query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSUserQueryContext"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSUserQueryContext"
        }
      ],
      "role": "symbol",
      "title": "CSUserQueryContext",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app": {
      "abstract": [
        {
          "text": "Add a search interface to your app to execute Spotlight queries",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and offer suggested text completions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Building a search interface for your app",
      "type": "topic",
      "url": "/documentation/corespotlight/building-a-search-interface-for-your-app"
    },
    "doc://com.apple.documentation/documentation/Swift/AsyncSequence": {
      "abstract": [
        {
          "text": "A type that provides asynchronous, sequential, iterated access to its elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AsyncSequence"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sci7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sci7FailureQa",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/AsyncSequence",
      "kind": "symbol",
      "role": "symbol",
      "title": "AsyncSequence",
      "type": "topic",
      "url": "/documentation/Swift/AsyncSequence"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1542812-cfdategetabsolutetime": {
      "abstract": [
        {
          "text": "Returns a `CFDate` object’s absolute time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFDateGetAbsoluteTime"
        },
        {
          "kind": "text",
          "text": "(CFDate!) -> CFAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1542812-cfdategetabsolutetime",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDateGetAbsoluteTime(_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1542812-cfdategetabsolutetime"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfdate-rv5": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdate-rv5",
      "kind": "article",
      "role": "article",
      "title": "CFDate",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdate-rv5"
    },
    "doc://com.apple.documentation/documentation/foundation/date": {
      "abstract": [
        {
          "text": "A specific point in time, independent of any calendar or time zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/date",
      "kind": "symbol",
      "role": "symbol",
      "title": "Date",
      "type": "topic",
      "url": "/documentation/foundation/date"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://www.iso.org/iso-8601-date-and-time-format.html": {
      "identifier": "https://www.iso.org/iso-8601-date-and-time-format.html",
      "title": "ISO-8601-STR",
      "titleInlineContent": [
        {
          "text": "ISO-8601-STR",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.iso.org/iso-8601-date-and-time-format.html"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Queries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion"
      ],
      "title": "Queries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Queries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion"
              ],
              "title": "Queries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11542812-cfdategetabsolutetime/title",
          "value": "CFDateGetAbsoluteTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext~1fetchAttributes/title",
          "value": "fetchAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext~1fetchAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fetchAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/title",
          "value": "CSUserQueryContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery~1completionHandler/title",
          "value": "completionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery~1completionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/title",
          "value": "CSSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery~1foundItemsHandler/title",
          "value": "foundItemsHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery~1foundItemsHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "foundItemsHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem/title",
          "value": "CSSearchableItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery~1start()/title",
          "value": "start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery~1start()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/title",
          "value": "CSSearchQueryContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/title",
          "value": "CSSearchableItemAttributeSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItemAttributeSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItemAttributeSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery~1cancel()/title",
          "value": "cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery~1cancel()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/title",
          "value": "CSSearchQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/title",
          "value": "CSUserQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/searching-for-information-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corespotlight/searching-for-information-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
