{"sections":[],"metadata":{"role":"symbol","title":"focusItemContainer","externalID":"c:objc(pl)UIFocusEnvironment(py)focusItemContainer","platforms":[{"introducedAt":"12.0","name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"12.0","name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"12.0","name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"1.0","name":"visionOS","deprecated":false,"beta":false,"unavailable":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focusItemContainer","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIFocusItemContainer","text":"UIFocusItemContainer","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"symbolKind":"property","required":true,"modules":[{"name":"UIKit"}],"navigatorTitle":[{"text":"focusItemContainer","kind":"identifier"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/focusItemContainer"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uifocusenvironment/focusitemcontainer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uifocusenvironment/focusitemcontainer"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusItemContainer"},{"kind":"text","text":": (any "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusItemContainer","kind":"typeIdentifier","text":"UIFocusItemContainer","preciseIdentifier":"c:objc(pl)UIFocusItemContainer"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"The value of this property is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" when no container exists.","type":"text"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"The container for the child focus items in this focus environment."}],"seeAlsoSections":[{"generated":true,"title":"Checking the ancestry of the environment","anchor":"Checking-the-ancestry-of-the-environment","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/contains(_:)","doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/parentFocusEnvironment"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/contains(_:)":{"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/contains(_:)","url":"/documentation/uikit/uifocusenvironment/contains(_:)","abstract":[{"text":"Returns a Boolean value that indicates whether the focus environment contains the specified environment.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contains","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIFocusEnvironment","text":"UIFocusEnvironment"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"contains(_:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIFocusItemContainer":{"navigatorTitle":[{"text":"UIFocusItemContainer","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusItemContainer","kind":"identifier"}],"url":"/documentation/uikit/uifocusitemcontainer","abstract":[{"text":"The container responsible for providing geometric context to focus items within a given focus environment.","type":"text"}],"title":"UIFocusItemContainer","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusItemContainer","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/focusItemContainer":{"role":"symbol","title":"focusItemContainer","required":true,"url":"/documentation/uikit/uifocusenvironment/focusitemcontainer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"focusItemContainer"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusItemContainer"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIFocusItemContainer","text":"UIFocusItemContainer"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The container for the child focus items in this focus environment."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/focusItemContainer"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment":{"role":"symbol","url":"/documentation/uikit/uifocusenvironment","abstract":[{"text":"A set of methods that define the focus behavior for a branch of the view hierarchy.","type":"text"}],"type":"topic","title":"UIFocusEnvironment","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusEnvironment","kind":"identifier"}],"navigatorTitle":[{"text":"UIFocusEnvironment","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/parentFocusEnvironment":{"url":"/documentation/uikit/uifocusenvironment/parentfocusenvironment","required":true,"kind":"symbol","navigatorTitle":[{"text":"parentFocusEnvironment","kind":"identifier"}],"title":"parentFocusEnvironment","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parentFocusEnvironment","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"UIFocusEnvironment","preciseIdentifier":"c:objc(pl)UIFocusEnvironment","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/parentFocusEnvironment","abstract":[{"text":"The parent focus environment for this environment.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"introducedAt":"12.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"12.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"introducedAt":"12.0","beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"focusItemContainer","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"focusItemContainer","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Checking-the-ancestry-of-the-environment","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/parentFocusEnvironment"],"title":"Checking the ancestry of the environment","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<UIFocusItemContainer>","preciseIdentifier":"c:Qoobjc(pl)UIFocusItemContainer","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"focusItemContainer","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"UIFocusItemContainer","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemContainer/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIFocusItemContainer"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemContainer/fragments","op":"replace"},{"value":[{"text":"UIFocusItemContainer","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemContainer/navigatorTitle","op":"replace"},{"value":"focusItemContainer","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment~1focusItemContainer/title","op":"replace"},{"value":[{"text":"focusItemContainer","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment~1focusItemContainer/fragments","op":"replace"},{"op":"replace","value":"UIFocusEnvironment","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIFocusEnvironment"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/fragments"},{"op":"replace","value":[{"text":"UIFocusEnvironment","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/navigatorTitle"},{"op":"replace","value":"parentFocusEnvironment","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment~1parentFocusEnvironment/title"},{"op":"replace","value":[{"kind":"identifier","text":"parentFocusEnvironment"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment~1parentFocusEnvironment/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}