{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/preferredFocusEnvironments"},"seeAlsoSections":[{"anchor":"Controlling-user-generated-focus-movements","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/preferredFocusedView"],"generated":true,"title":"Controlling user-generated focus movements"}],"abstract":[{"text":"An array of focus environments, ordered by priority, to which this environment prefers focus to be directed during a focus update.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredFocusEnvironments","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIFocusEnvironment","text":"UIFocusEnvironment","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The preferred focus environments listed in this property define where to search for the default focused item in an environment, such as when focus updates programmatically. Starting from the target environment, each preferred focus environment is recursively searched in the order it appears in the array until an eligible, focusable item is found. Preferred focus environments can include focusable and nonfocusable items, in addition to nonitem environments. Returning an empty array is equivalent to returning an array containing only ","type":"text"},{"code":"self","type":"codeVoice"},{"text":".","type":"text"}]}],"kind":"content"}],"sections":[],"variants":[{"paths":["/documentation/uikit/uifocusenvironment/preferredfocusenvironments"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uifocusenvironment/preferredfocusenvironments"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"UIKit"}],"externalID":"c:objc(pl)UIFocusEnvironment(py)preferredFocusEnvironments","navigatorTitle":[{"kind":"identifier","text":"preferredFocusEnvironments"}],"title":"preferredFocusEnvironments","required":true,"platforms":[{"introducedAt":"9.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"introducedAt":"9.0","deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"9.0","name":"tvOS"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredFocusEnvironments"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"UIFocusEnvironment","preciseIdentifier":"c:objc(pl)UIFocusEnvironment"},{"kind":"text","text":"]"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/preferredFocusedView":{"title":"preferredFocusedView","abstract":[{"text":"Specifies the view that should be focused if this environment is focused.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uifocusenvironment/preferredfocusedview","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/preferredFocusedView","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredFocusedView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"preferredFocusedView"}],"deprecated":true},"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/preferredFocusEnvironments":{"title":"preferredFocusEnvironments","required":true,"abstract":[{"text":"An array of focus environments, ordered by priority, to which this environment prefers focus to be directed during a focus update.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uifocusenvironment/preferredfocusenvironments","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/preferredFocusEnvironments","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredFocusEnvironments"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIFocusEnvironment","text":"UIFocusEnvironment"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"preferredFocusEnvironments"}]},"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment":{"role":"symbol","url":"/documentation/uikit/uifocusenvironment","abstract":[{"text":"A set of methods that define the focus behavior for a branch of the view hierarchy.","type":"text"}],"type":"topic","title":"UIFocusEnvironment","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusEnvironment","kind":"identifier"}],"navigatorTitle":[{"text":"UIFocusEnvironment","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"9.0","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"9.0","name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"9.0","name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"preferredFocusEnvironments","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"preferredFocusEnvironments","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Controlling user-generated focus movements","generated":true,"anchor":"Controlling-user-generated-focus-movements","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/preferredFocusedView"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<UIFocusEnvironment>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"preferredFocusEnvironments"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment~1preferredFocusedView/title","op":"replace","value":"preferredFocusedView"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment~1preferredFocusedView/fragments","op":"replace","value":[{"text":"preferredFocusedView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment~1preferredFocusEnvironments/title","op":"replace","value":"preferredFocusEnvironments"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment~1preferredFocusEnvironments/fragments","op":"replace","value":[{"text":"preferredFocusEnvironments","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/title","op":"replace","value":"UIFocusEnvironment"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/fragments","op":"replace","value":[{"kind":"identifier","text":"UIFocusEnvironment"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIFocusEnvironment"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}