{"seeAlsoSections":[{"anchor":"Getting-the-sound-to-play-during-updates","identifiers":["doc://com.apple.uikit/documentation/UIKit/using-custom-sounds-for-focus-movement","doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier"],"title":"Getting the sound to play during updates","generated":true}],"kind":"symbol","metadata":{"platforms":[{"introducedAt":"11.0","name":"tvOS","deprecated":false,"unavailable":false,"beta":false}],"roleHeading":"Instance Method","externalID":"c:objc(pl)UIFocusEnvironment(im)soundIdentifierForFocusUpdateInContext:","symbolKind":"method","title":"soundIdentifierForFocusUpdate(in:)","modules":[{"name":"UIKit"}],"role":"symbol","navigatorTitle":[{"text":"soundIdentifierForFocusUpdateInContext:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"soundIdentifierForFocusUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFocusUpdateContext","preciseIdentifier":"c:objc(cs)UIFocusUpdateContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIFocusSoundIdentifier","preciseIdentifier":"c:@T@UIFocusSoundIdentifier","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/soundIdentifierForFocusUpdate(in:)"},"sections":[],"abstract":[{"type":"text","text":"Asks the delegate for the identifier of the sound to play when the object gains focus."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uifocusenvironment/soundidentifierforfocusupdate(in:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uifocusenvironment/soundidentifierforfocusupdate(in:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"soundIdentifierForFocusUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext","text":"UIFocusUpdateContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFocusUpdateContext"},{"text":") -> ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier","text":"UIFocusSoundIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIFocusSoundIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"context","content":[{"inlineContent":[{"text":"The context object associated with the update.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the sound to be played. Return "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if you want to let the parent focus environment determine which sound to play."}]}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/using-custom-sounds-for-focus-movement"]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"text":"Use this method to return a custom sound when the focus environment object gains focus. Return ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/default"},{"text":" to play the default system sound, or return ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/none"},{"text":" to avoid playing a sound altogether. If you previously registered custom sounds using the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSystem/register(_:forSoundIdentifier:)"},{"text":" method of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSystem"},{"text":", you may also return an identifier for a sound that you registered.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"If you do not implement this method, the system assumes a ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" return value. If no ancestor environment defines a custom sound, the system plays the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/default","type":"reference","isActive":true},{"text":" sound.","type":"text"}],"type":"paragraph"},{"name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"You must register custom sounds before returning the associated identifiers from this method. Returning an identifier that is unknown to UIKit will result in an assertion failure and an immediate crash."}]}],"type":"aside","style":"important"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/UIFocusSystem":{"kind":"symbol","abstract":[{"type":"text","text":"Queries and reevaluates the currently focused item."}],"url":"/documentation/uikit/uifocussystem","navigatorTitle":[{"text":"UIFocusSystem","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusSystem","kind":"identifier"}],"title":"UIFocusSystem","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSystem","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusUpdateContext","kind":"identifier"}],"role":"symbol","title":"UIFocusUpdateContext","url":"/documentation/uikit/uifocusupdatecontext","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext","navigatorTitle":[{"text":"UIFocusUpdateContext","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"An object that provides information relevant to a specific focus update from one view to another.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/default":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/default","title":"default","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIFocusSoundIdentifierDefault"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UIFocusSoundIdentifier","kind":"typeIdentifier","text":"UIFocusSoundIdentifier"}],"url":"/documentation/uikit/uifocussoundidentifier/default","abstract":[{"type":"text","text":"The identifier for the default system sound to play during focus updates."}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier","type":"topic","url":"/documentation/uikit/uifocussoundidentifier","navigatorTitle":[{"text":"UIFocusSoundIdentifier","kind":"identifier"}],"role":"symbol","abstract":[{"text":"An identifier for a focus-related sound.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusSoundIdentifier","kind":"identifier"}],"title":"UIFocusSoundIdentifier","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/using-custom-sounds-for-focus-movement":{"abstract":[{"text":"Customize the sounds users hear when focus moves.","type":"text"}],"kind":"article","role":"article","title":"Using custom sounds for focus movement","url":"/documentation/uikit/using-custom-sounds-for-focus-movement","identifier":"doc://com.apple.uikit/documentation/UIKit/using-custom-sounds-for-focus-movement","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusSystem/register(_:forSoundIdentifier:)":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSystem/register(_:forSoundIdentifier:)","title":"register(_:forSoundIdentifier:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerURL:forSoundIdentifier:"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forSoundIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFocusSoundIdentifier","preciseIdentifier":"c:@T@UIFocusSoundIdentifier"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uifocussystem/register(_:forsoundidentifier:)","abstract":[{"text":"Registers the specified sound file with the focus engine.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment":{"role":"symbol","url":"/documentation/uikit/uifocusenvironment","abstract":[{"text":"A set of methods that define the focus behavior for a branch of the view hierarchy.","type":"text"}],"type":"topic","title":"UIFocusEnvironment","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusEnvironment","kind":"identifier"}],"navigatorTitle":[{"text":"UIFocusEnvironment","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/soundIdentifierForFocusUpdate(in:)":{"abstract":[{"text":"Asks the delegate for the identifier of the sound to play when the object gains focus.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"soundIdentifierForFocusUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFocusUpdateContext","preciseIdentifier":"c:objc(cs)UIFocusUpdateContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIFocusSoundIdentifier","preciseIdentifier":"c:@T@UIFocusSoundIdentifier","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"soundIdentifierForFocusUpdateInContext:","kind":"identifier"}],"role":"symbol","title":"soundIdentifierForFocusUpdate(in:)","url":"/documentation/uikit/uifocusenvironment/soundidentifierforfocusupdate(in:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment/soundIdentifierForFocusUpdate(in:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/none":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/none","title":"none","type":"topic","navigatorTitle":[{"text":"UIFocusSoundIdentifierNone","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UIFocusSoundIdentifier","text":"UIFocusSoundIdentifier","kind":"typeIdentifier"}],"url":"/documentation/uikit/uifocussoundidentifier/none","abstract":[{"text":"The identifier for disabling sound during a focus update.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"tvOS","beta":false,"unavailable":false,"introducedAt":"11.0","deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"soundIdentifierForFocusUpdateInContext:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"soundIdentifierForFocusUpdateInContext:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/using-custom-sounds-for-focus-movement","doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier"],"title":"Getting the sound to play during updates","anchor":"Getting-the-sound-to-play-during-updates"}]},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier","kind":"typeIdentifier","text":"UIFocusSoundIdentifier","preciseIdentifier":"c:@T@UIFocusSoundIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"soundIdentifierForFocusUpdateInContext:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext","kind":"typeIdentifier","text":"UIFocusUpdateContext","preciseIdentifier":"c:objc(cs)UIFocusUpdateContext"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"context"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"name":"context","content":[{"inlineContent":[{"text":"The context object associated with the update.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The identifier of the sound to be played. Return ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if you want to let the parent focus environment determine which sound to play.","type":"text"}]}]},"path":"/primaryContentSections/2","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSystem/title","op":"replace","value":"UIFocusSystem"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSystem/fragments","op":"replace","value":[{"kind":"identifier","text":"UIFocusSystem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSystem/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIFocusSystem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext/title","op":"replace","value":"UIFocusUpdateContext"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext/fragments","op":"replace","value":[{"text":"UIFocusUpdateContext","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIFocusUpdateContext"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier~1default/title","op":"replace","value":"UIFocusSoundIdentifierDefault"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier~1default/fragments","op":"replace","value":[{"text":"UIFocusSoundIdentifierDefault","kind":"identifier"}]},{"value":"UIFocusSoundIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier/title"},{"value":[{"kind":"identifier","text":"UIFocusSoundIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier/fragments"},{"value":[{"text":"UIFocusSoundIdentifier","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier/navigatorTitle"},{"value":"registerURL:forSoundIdentifier:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSystem~1register(_:forSoundIdentifier:)/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerURL:forSoundIdentifier:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSystem~1register(_:forSoundIdentifier:)/fragments"},{"value":"UIFocusEnvironment","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/title"},{"value":[{"kind":"identifier","text":"UIFocusEnvironment"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/fragments"},{"value":[{"kind":"identifier","text":"UIFocusEnvironment"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/navigatorTitle"},{"value":"soundIdentifierForFocusUpdateInContext:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment~1soundIdentifierForFocusUpdate(in:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"soundIdentifierForFocusUpdateInContext:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment~1soundIdentifierForFocusUpdate(in:)/fragments"},{"value":"UIFocusSoundIdentifierNone","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier~1none/title"},{"value":[{"kind":"identifier","text":"UIFocusSoundIdentifierNone"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier~1none/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}