{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileproviderui/documentation/FileProviderUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileproviderui/documentation/FileProviderUI/fileproviderui-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "File Provider UI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "FileProviderUI Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI": {
      "abstract": [
        {
          "text": "Add actions to the document browser’s context menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider UI",
      "type": "topic",
      "url": "/documentation/fileproviderui"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FPUIActionIdentifier"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FPUIActionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "FPUIActionIdentifier",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuiactionidentifier"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUI_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FPUI_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUI_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "FPUI_AVAILABLE",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpui_available"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUI_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FPUI_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUI_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "FPUI_EXPORT",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpui_export"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionIdentifier"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionIdentifier"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUI_AVAILABLE",
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUI_EXPORT"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionIdentifier/title",
          "value": "FPUIActionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIActionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIActionIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileproviderui/fileproviderui-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileproviderui/fileproviderui-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
