{
  "abstract": [
    {
      "text": "The request for user authorization to access app-related data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency",
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ATTrackingManager(cm)requestTrackingAuthorizationWithCompletionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "requestTrackingAuthorization"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ATTrackingManager",
        "text": "ATTrackingManager"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
        "text": "AuthorizationStatus"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "App Tracking Transparency"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "requestTrackingAuthorizationWithCompletionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "requestTrackingAuthorization(completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "requestTrackingAuthorization"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ATTrackingManager",
              "text": "ATTrackingManager"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
              "text": "AuthorizationStatus"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "requestTrackingAuthorization"
            },
            {
              "kind": "text",
              "text": "() "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ATTrackingManager",
              "text": "ATTrackingManager"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
              "text": "AuthorizationStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is a one-time request to authorize or deny access to app-related data that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "can be used for tracking the user or the device. The system remembers the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "user’s choice and doesn’t prompt again unless a user uninstalls and then",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "reinstalls the app on the device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Calls to the API only prompt when the application state",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is ",
              "type": "text"
            },
            {
              "code": "UIApplicationStateActive",
              "type": "codeVoice"
            },
            {
              "text": ". The authorization prompt doesn’t display if",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "another permission request is pending user confirmation. Concurrent requests",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "aren’t preserved by iOS, and calls to the API through an app extension don’t",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "prompt. Check the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/trackingAuthorizationStatus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "status of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/notDetermined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to determine if you need to make an additional call.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The completion handler will be called with the result of the user’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "decision for granting or denying permission to use application tracking.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The completion handler will be called immediately if access to request",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "authorization is restricted.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "To use",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ",",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "key must be in the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency": {
      "abstract": [
        {
          "text": "Request user authorization to access app-related data for tracking the user or the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency",
      "kind": "symbol",
      "role": "collection",
      "title": "App Tracking Transparency",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager": {
      "abstract": [
        {
          "text": "A class that provides a tracking authorization request and the tracking",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "authorization status of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ATTrackingManager"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATTrackingManager"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus": {
      "abstract": [
        {
          "text": "The status values for app tracking authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/notDetermined": {
      "abstract": [
        {
          "text": "The value that returns when the app can’t determine the user’s",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "authorization status for access to app-related data for tracking the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "user or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATTrackingManagerAuthorizationStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus.notDetermined",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus/notdetermined"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)": {
      "abstract": [
        {
          "text": "The request for user authorization to access app-related data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestTrackingAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ATTrackingManager",
          "text": "ATTrackingManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
          "text": "AuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestTrackingAuthorizationWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestTrackingAuthorization(completionHandler:)",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/requesttrackingauthorization(completionhandler:)"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/trackingAuthorizationStatus": {
      "abstract": [
        {
          "text": "The authorization status that is current for the calling application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ATTrackingManager",
          "text": "ATTrackingManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
          "text": "AuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/trackingAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackingAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "trackingAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/trackingauthorizationstatus"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "role": "symbol",
      "title": "Information Property List",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription": {
      "abstract": [
        {
          "text": "A message that informs the user why an app is requesting permission to use data for tracking the user or the device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserTrackingUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "requestTrackingAuthorizationWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestTrackingAuthorizationWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency",
                "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "requestTrackingAuthorizationWithCompletionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
                    "text": "ATTrackingManagerAuthorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "status"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/title",
          "value": "ATTrackingManagerAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1trackingAuthorizationStatus/title",
          "value": "trackingAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1trackingAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackingAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/title",
          "value": "ATTrackingManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1notDetermined/title",
          "value": "ATTrackingManagerAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1requestTrackingAuthorization(completionHandler:)/title",
          "value": "requestTrackingAuthorizationWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1requestTrackingAuthorization(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestTrackingAuthorizationWithCompletionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/apptrackingtransparency/attrackingmanager/requesttrackingauthorization(completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/apptrackingtransparency/attrackingmanager/requesttrackingauthorization(completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
