{
  "abstract": [
    {
      "text": "The body landmarks that Vision detects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/body-landmarks"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Body Landmarks"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The illustration below shows the nineteen body points that you can detect with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPoseRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3627959",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPoseRequest": {
      "abstract": [
        {
          "text": "A request that detects a human body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectHumanBodyPoseRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPoseRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectHumanBodyPoseRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectHumanBodyPoseRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodyposerequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/all": {
      "abstract": [
        {
          "text": "A group key identifying all landmarks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointGroupKeyAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/all"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyFace": {
      "abstract": [
        {
          "text": "A group key identifying the face, which includes the eyes, ears, and nose.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyFace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyFace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyFace"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyFace",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyface"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm": {
      "abstract": [
        {
          "text": "A group key identifying the landmarks of the left arm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyLeftArm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyLeftArm"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyLeftArm",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyleftarm"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftLeg": {
      "abstract": [
        {
          "text": "A group key identifying the landmarks of the left leg.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyLeftLeg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftLeg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyLeftLeg"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyLeftLeg",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyleftleg"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm": {
      "abstract": [
        {
          "text": "A group key identifying the landmarks of the right arm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyRightArm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyRightArm"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyRightArm",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyrightarm"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightLeg": {
      "abstract": [
        {
          "text": "A group key identifying the landmarks of the right leg.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyRightLeg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightLeg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyRightLeg"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyRightLeg",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyrightleg"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyTorso": {
      "abstract": [
        {
          "text": "A group key identifying the torso, which includes the neck, shoulders, hips, and root.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyTorso"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyTorso",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyTorso"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyTorso",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeytorso"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey": {
      "abstract": [
        {
          "text": "The data type for all recognized point keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPointKey",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftAnkle": {
      "abstract": [
        {
          "text": "The left ankle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyLeftAnkle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftAnkle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyLeftAnkle"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyLeftAnkle",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyleftankle"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftEar": {
      "abstract": [
        {
          "text": "The left ear.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyLeftEar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftEar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyLeftEar"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyLeftEar",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyleftear"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftElbow": {
      "abstract": [
        {
          "text": "The left elbow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyLeftElbow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftElbow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyLeftElbow"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyLeftElbow",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyleftelbow"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftEye": {
      "abstract": [
        {
          "text": "The left eye.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyLeftEye"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftEye",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyLeftEye"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyLeftEye",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeylefteye"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftHip": {
      "abstract": [
        {
          "text": "The left hip.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyLeftHip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftHip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyLeftHip"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyLeftHip",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeylefthip"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftKnee": {
      "abstract": [
        {
          "text": "The left knee.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyLeftKnee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftKnee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyLeftKnee"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyLeftKnee",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyleftknee"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftShoulder": {
      "abstract": [
        {
          "text": "The left shoulder.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyLeftShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftShoulder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyLeftShoulder"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyLeftShoulder",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyleftshoulder"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftWrist": {
      "abstract": [
        {
          "text": "The left wrist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyLeftWrist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftWrist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyLeftWrist"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyLeftWrist",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyleftwrist"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyNeck": {
      "abstract": [
        {
          "text": "The center point of the neck.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyNeck"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyNeck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyNeck"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyNeck",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyneck"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyNose": {
      "abstract": [
        {
          "text": "The nose.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyNose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyNose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyNose"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyNose",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeynose"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightAnkle": {
      "abstract": [
        {
          "text": "The right ankle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRightAnkle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightAnkle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRightAnkle"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRightAnkle",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyrightankle"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightEar": {
      "abstract": [
        {
          "text": "The right ear.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRightEar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightEar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRightEar"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRightEar",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyrightear"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightElbow": {
      "abstract": [
        {
          "text": "The right elbow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRightElbow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightElbow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRightElbow"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRightElbow",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyrightelbow"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightEye": {
      "abstract": [
        {
          "text": "The right eye.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRightEye"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightEye",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRightEye"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRightEye",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyrighteye"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightHip": {
      "abstract": [
        {
          "text": "The right hip.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRightHip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightHip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRightHip"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRightHip",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyrighthip"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightKnee": {
      "abstract": [
        {
          "text": "The right knee.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRightKnee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightKnee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRightKnee"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRightKnee",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyrightknee"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightShoulder": {
      "abstract": [
        {
          "text": "The right shoulder.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRightShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightShoulder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRightShoulder"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRightShoulder",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyrightshoulder"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightWrist": {
      "abstract": [
        {
          "text": "The right wrist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRightWrist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightWrist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRightWrist"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRightWrist",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyrightwrist"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRoot": {
      "abstract": [
        {
          "text": "The center point of the waist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRoot"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRoot",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyroot"
    },
    "doc://com.apple.vision/documentation/Vision/hand-landmarks": {
      "abstract": [
        {
          "text": "The hand landmarks that Vision detects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/hand-landmarks",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hand Landmarks",
      "type": "topic",
      "url": "/documentation/vision/hand-landmarks"
    },
    "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api": {
      "abstract": [],
      "identifier": "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original Objective-C and Swift API",
      "type": "topic",
      "url": "/documentation/vision/original-objective-c-and-swift-api"
    },
    "media-3627959": {
      "alt": "An illustration depicting a model of the human body. The body points that Vision detects are the right and left wrists, elbows, shoulders, ears, eyes, hips, knees, and ankles; and the nose, neck, and root, or center point.",
      "identifier": "media-3627959",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4e34d488e7a26e8c93e57970d5973369/media-3627959@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Landmarks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/hand-landmarks"
      ],
      "title": "Landmarks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Head",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftEye",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightEye",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftEar",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightEar",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyNose",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyFace"
      ],
      "title": "Head"
    },
    {
      "anchor": "Torso",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyNeck",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftShoulder",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightShoulder",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftHip",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightHip",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRoot",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyTorso"
      ],
      "title": "Torso"
    },
    {
      "anchor": "Arms",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightWrist",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightElbow",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftWrist",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftElbow",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm"
      ],
      "title": "Arms"
    },
    {
      "anchor": "Legs",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightKnee",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightAnkle",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightLeg",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftKnee",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftAnkle",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftLeg"
      ],
      "title": "Legs"
    },
    {
      "anchor": "All-Landmarks",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/all"
      ],
      "title": "All Landmarks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Head",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftEye",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightEye",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftEar",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightEar",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyNose",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyFace"
              ],
              "title": "Head"
            },
            {
              "anchor": "Torso",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyNeck",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftShoulder",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightShoulder",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftHip",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightHip",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRoot",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyTorso"
              ],
              "title": "Torso"
            },
            {
              "anchor": "Arms",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightWrist",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightElbow",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftWrist",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftElbow",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm"
              ],
              "title": "Arms"
            },
            {
              "anchor": "Legs",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightKnee",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightAnkle",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightLeg",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftKnee",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftAnkle",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftLeg"
              ],
              "title": "Legs"
            },
            {
              "anchor": "All-Landmarks",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/all"
              ],
              "title": "All Landmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Landmarks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/hand-landmarks"
              ],
              "title": "Landmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftKnee/title",
          "value": "VNBodyLandmarkKeyLeftKnee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftKnee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftKnee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyTorso/title",
          "value": "VNBodyLandmarkRegionKeyTorso"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyTorso/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyTorso"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftShoulder/title",
          "value": "VNBodyLandmarkKeyLeftShoulder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftShoulder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftShoulder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightWrist/title",
          "value": "VNBodyLandmarkKeyRightWrist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightWrist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRightWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyNeck/title",
          "value": "VNBodyLandmarkKeyNeck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyNeck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyNeck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftHip/title",
          "value": "VNBodyLandmarkKeyLeftHip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftHip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftHip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftEye/title",
          "value": "VNBodyLandmarkKeyLeftEye"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftEye/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftEye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyNose/title",
          "value": "VNBodyLandmarkKeyNose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyNose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyNose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRoot/title",
          "value": "VNBodyLandmarkKeyRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyLeftLeg/title",
          "value": "VNBodyLandmarkRegionKeyLeftLeg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyLeftLeg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyLeftLeg"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightKnee/title",
          "value": "VNBodyLandmarkKeyRightKnee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightKnee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRightKnee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/title",
          "value": "VNRecognizedPointKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightAnkle/title",
          "value": "VNBodyLandmarkKeyRightAnkle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightAnkle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRightAnkle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftElbow/title",
          "value": "VNBodyLandmarkKeyLeftElbow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftElbow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftElbow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyFace/title",
          "value": "VNBodyLandmarkRegionKeyFace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyFace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyFace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightHip/title",
          "value": "VNBodyLandmarkKeyRightHip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightHip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRightHip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftEar/title",
          "value": "VNBodyLandmarkKeyLeftEar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftEar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyRightArm/title",
          "value": "VNBodyLandmarkRegionKeyRightArm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyRightArm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyRightArm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightElbow/title",
          "value": "VNBodyLandmarkKeyRightElbow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightElbow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRightElbow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightEar/title",
          "value": "VNBodyLandmarkKeyRightEar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightEar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRightEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightEye/title",
          "value": "VNBodyLandmarkKeyRightEye"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightEye/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRightEye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftWrist/title",
          "value": "VNBodyLandmarkKeyLeftWrist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftWrist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1all/title",
          "value": "VNRecognizedPointGroupKeyAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointGroupKeyAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPoseRequest/title",
          "value": "VNDetectHumanBodyPoseRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPoseRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanBodyPoseRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPoseRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanBodyPoseRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightShoulder/title",
          "value": "VNBodyLandmarkKeyRightShoulder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightShoulder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRightShoulder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyRightLeg/title",
          "value": "VNBodyLandmarkRegionKeyRightLeg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyRightLeg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyRightLeg"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyLeftArm/title",
          "value": "VNBodyLandmarkRegionKeyLeftArm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyLeftArm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyLeftArm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftAnkle/title",
          "value": "VNBodyLandmarkKeyLeftAnkle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftAnkle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftAnkle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/body-landmarks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/body-landmarks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
