{
  "abstract": [
    {
      "text": "Draw the skeleton of an animal by using Vision’s capability to detect animal body poses.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/detecting-animal-body-poses-with-vision"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Detecting animal body poses with Vision"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC23 session 10045: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc23/10045",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample app doesn’t run in Simulator, so you need to run it on a physical device with iOS 17 or later, or iPadOS 17 or later. To run the app, start a live video feed from the back camera.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "22ccd8a7f68a/DetectingAnimalBodyPosesWithVision.zip": {
      "checksum": "22ccd8a7f68ac00b7f81231e5be39cedcfcc38793a4e655d6132f92c9cb536b4d7d1660ff9c27c3ee1f907832a4903436d984322ebd6ccea69ee520cd2f6d148",
      "identifier": "22ccd8a7f68a/DetectingAnimalBodyPosesWithVision.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/22ccd8a7f68a/DetectingAnimalBodyPosesWithVision.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation": {
      "abstract": [
        {
          "text": "An observation that provides the animal body points the analysis recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservation"
        }
      ],
      "role": "symbol",
      "title": "VNAnimalBodyPoseObservation",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectAnimalBodyPoseRequest": {
      "abstract": [
        {
          "text": "A request that detects an animal body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectAnimalBodyPoseRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectAnimalBodyPoseRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectAnimalBodyPoseRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectAnimalBodyPoseRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetectanimalbodyposerequest"
    },
    "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api": {
      "abstract": [],
      "identifier": "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original Objective-C and Swift API",
      "type": "topic",
      "url": "/documentation/vision/original-objective-c-and-swift-api"
    },
    "https://developer.apple.com/wwdc23/10045": {
      "identifier": "https://developer.apple.com/wwdc23/10045",
      "title": "Detect animal poses in Vision",
      "titleInlineContent": [
        {
          "text": "Detect animal poses in Vision",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc23/10045"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "22ccd8a7f68a/DetectingAnimalBodyPosesWithVision.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animal-body-pose-detection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectAnimalBodyPoseRequest",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation"
      ],
      "title": "Animal body pose detection"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation/title",
          "value": "VNAnimalBodyPoseObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectAnimalBodyPoseRequest/title",
          "value": "VNDetectAnimalBodyPoseRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectAnimalBodyPoseRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectAnimalBodyPoseRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectAnimalBodyPoseRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectAnimalBodyPoseRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/detecting-animal-body-poses-with-vision"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
