{
  "abstract": [
    {
      "text": "The hand landmarks that Vision detects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/hand-landmarks"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Hand Landmarks"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/all": {
      "abstract": [
        {
          "text": "A group key identifying all landmarks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointGroupKeyAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/all"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey": {
      "abstract": [
        {
          "text": "The data type for all recognized point keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPointKey",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey"
    },
    "doc://com.apple.vision/documentation/Vision/body-landmarks": {
      "abstract": [
        {
          "text": "The body landmarks that Vision detects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/body-landmarks",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Body Landmarks",
      "type": "topic",
      "url": "/documentation/vision/body-landmarks"
    },
    "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api": {
      "abstract": [],
      "identifier": "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original Objective-C and Swift API",
      "type": "topic",
      "url": "/documentation/vision/original-objective-c-and-swift-api"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Landmarks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/body-landmarks"
      ],
      "title": "Landmarks"
    }
  ],
  "topicSections": [
    {
      "anchor": "All-Landmarks",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/all"
      ],
      "title": "All Landmarks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "All-Landmarks",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/all"
              ],
              "title": "All Landmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Landmarks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/body-landmarks"
              ],
              "title": "Landmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/title",
          "value": "VNRecognizedPointKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1all/title",
          "value": "VNRecognizedPointGroupKeyAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointGroupKeyAll"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/hand-landmarks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/hand-landmarks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
