{
  "abstract": [
    {
      "text": "Apply Vision algorithms to track objects or rectangles throughout a video.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/tracking-multiple-objects-or-rectangles-in-video"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "11.3",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Tracking Multiple Objects or Rectangles in Video"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework, you can detect and track objects or rectangles through a sequence of frames coming from video, live capture, or other sources.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample app shows you how to pick an initial object to track, how to create Vision tracking requests to follow that object, and how to parse results from the object or rectangle tracker.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Preview-the-Sample-App",
          "level": 3,
          "text": "Preview the Sample App",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To see this sample app in action, build and run the project in Xcode, then choose a video from your photo library.  Once the video is loaded from your photo library, choose to track either objects or rectangles.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Nominate-Objects-or-Rectangles-to-Track",
          "level": 3,
          "text": "Nominate Objects or Rectangles to Track",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To track rectangles, select Rectangles.  The app runs the rectangle detector and shows rectangles it finds in a preview of the scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Otherwise, to track objects, select Objects.  Then nominate objects to track by touching them in the preview and dragging boxes around them.  You can select multiple objects; the app identifies them by their ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/foundation/uuid",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", using differently colored rectangles.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vntrackobjectrequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class requires a detected object observation to initialize.  The sample provides this observation by running ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vndetectrectanglesrequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or by creating one from the bounding box you drew in the preview.  It tracks multiple objects by iterating through each observation and creating a ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vndetectedobjectobservation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " from its bounding box.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var inputObservations = [UUID: VNDetectedObjectObservation]()",
            "var trackedObjects = [UUID: TrackedPolyRect]()",
            "switch type {",
            "case .object:",
            "    for rect in self.objectsToTrack {",
            "        let inputObservation = VNDetectedObjectObservation(boundingBox: rect.boundingBox)",
            "        inputObservations[inputObservation.uuid] = inputObservation",
            "        trackedObjects[inputObservation.uuid] = rect",
            "    }",
            "case .rectangle:",
            "    for rectangleObservation in initialRectObservations {",
            "        inputObservations[rectangleObservation.uuid] = rectangleObservation",
            "        let rectColor = TrackedObjectsPalette.color(atIndex: trackedObjects.count)",
            "        trackedObjects[rectangleObservation.uuid] = TrackedPolyRect(observation: rectangleObservation, color: rectColor)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In your own app, if you prefer to nominate objects programmatically, you can use observations returned from Vision’s own object detection algorithms.  For example, the Vision framework’s ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vnimagerequesthandler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " accepts face detection, text detection, and barcode detection requests, and those requests return their results in subclasses of ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vnobservation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".  You can pass these observations directly into ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vntrackobjectrequest",
              "isActive": true,
              "overridingTitle": "VNTrackObjectRequest",
              "overridingTitleInlineContent": [
                {
                  "code": "VNTrackObjectRequest",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Selecting a salient object heavily influences the performance of the tracking algorithm; provide the best initial bounding box segmentation of your object that you can.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Track-Objects-or-Rectangles-with-a-Request-Handler",
          "level": 3,
          "text": "Track Objects or Rectangles with a Request Handler",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Vision framework handles tracking requests through a ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vnsequencerequesthandler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".  Whereas the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vnimagerequesthandler",
              "isActive": true,
              "overridingTitle": "VNImageRequestHandler",
              "overridingTitleInlineContent": [
                {
                  "code": "VNImageRequestHandler",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " handles object detection requests on a still image, the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vnsequencerequesthandler",
              "isActive": true,
              "overridingTitle": "VNSequenceRequestHandler",
              "overridingTitleInlineContent": [
                {
                  "code": "VNSequenceRequestHandler",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " handles tracking requests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create a tracking request for each rectangle or object you’d like to track.  Seed each tracking request with the observation created during nomination.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let request: VNTrackingRequest!",
            "switch type {",
            "case .object:",
            "    request = VNTrackObjectRequest(detectedObjectObservation: inputObservation.value)",
            "case .rectangle:",
            "    guard let rectObservation = inputObservation.value as? VNRectangleObservation else {",
            "        continue",
            "    }",
            "    request = VNTrackRectangleRequest(rectangleObservation: rectObservation)",
            "}",
            "request.trackingLevel = trackingLevel",
            "",
            "trackingRequests.append(request)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For each such request, call the sequence request handler’s ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vnsequencerequesthandler/2880308-perform",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, making sure to pass in the video reader’s orientation to ensure upright tracking. This method runs synchronously; use a background queue, such as ",
              "type": "text"
            },
            {
              "code": "workQueue",
              "type": "codeVoice"
            },
            {
              "text": " in the sample code, so that the main queue isn’t blocked while your requests execute.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "try requestHandler.perform(trackingRequests, on: frame, orientation: videoReader.orientation)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "By iterating through each selected object or rectangle, creating a tracking request from it, and calling ",
              "type": "text"
            },
            {
              "code": "perform",
              "type": "codeVoice"
            },
            {
              "text": " on the request handler, Vision follows the object or rectangle over the image sequence and returns results through its ",
              "type": "text"
            },
            {
              "code": "results",
              "type": "codeVoice"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Interpret-Tracking-Results",
          "level": 3,
          "text": "Interpret Tracking Results",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Access tracking results through the request’s ",
              "type": "text"
            },
            {
              "code": "results",
              "type": "codeVoice"
            },
            {
              "text": " property or its completion handler.  A single tracking request represents a single tracked object in a one-to-one relationship.  If a tracking request succeeds, its ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vnrequest/2867238-results",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property contains ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vndetectedobjectobservation",
              "isActive": true,
              "overridingTitle": "VNDetectedObjectObservation",
              "overridingTitleInlineContent": [
                {
                  "code": "VNDetectedObjectObservation",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " objects describing the tracked object’s new location in the frame.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "guard let results = processedRequest.results else {",
            "    continue",
            "}",
            "guard let observation = results.first as? VNDetectedObjectObservation else {",
            "    continue",
            "}",
            "// Assume threshold = 0.5f",
            "let rectStyle: TrackedPolyRectStyle = observation.confidence > 0.5 ? .solid : .dashed",
            "let knownRect = trackedObjects[observation.uuid]!",
            "switch type {",
            "case .object:",
            "    rects.append(TrackedPolyRect(observation: observation, color: knownRect.color, style: rectStyle))",
            "case .rectangle:",
            "    guard let rectObservation = observation as? VNRectangleObservation else {",
            "        break",
            "    }",
            "    rects.append(TrackedPolyRect(observation: rectObservation, color: knownRect.color, style: rectStyle))",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Use the observation’s ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vndetectedobjectobservation/2867227-boundingbox",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to determine its location, so you can update your app or UI with the tracked object’s new location.  Also use it to seed the next round of tracking.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "inputObservations[observation.uuid] = observation"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In practice, you should periodically run a new tracking request with an updated set of input observations  to capture objects that weren’t present in your initial nomination frame. For instance, you could create a new ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/vision/vntrackobjectrequest",
              "isActive": true,
              "overridingTitle": "VNTrackObjectRequest",
              "overridingTitleInlineContent": [
                {
                  "code": "VNTrackObjectRequest",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " every ten frames.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "913130aaf0ea/TrackingMultipleObjectsOrRectanglesInVideo.zip": {
      "checksum": "913130aaf0ea013b2a5e3fbfa4c9dd12144a10313430da544298b29c4786adebd869f2fc99cee9508f9e7baef039e8ab879cc5f8a77e7c51937a4a7e2985faf2",
      "identifier": "913130aaf0ea/TrackingMultipleObjectsOrRectanglesInVideo.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/913130aaf0ea/TrackingMultipleObjectsOrRectanglesInVideo.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation": {
      "abstract": [
        {
          "text": "An observation that provides the position and extent of an image feature that an image- analysis request detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectedObjectObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectedObjectObservation"
        }
      ],
      "role": "symbol",
      "title": "VNDetectedObjectObservation",
      "type": "topic",
      "url": "/documentation/vision/vndetectedobjectobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackObjectRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that tracks the movement of a previously identified object across multiple images or video frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackObjectRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackObjectRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackObjectRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackObjectRequest",
      "type": "topic",
      "url": "/documentation/vision/vntrackobjectrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackRectangleRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that tracks movement of a previously identified rectangular object across multiple images or video frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackRectangleRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackRectangleRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackRectangleRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackRectangleRequest",
      "type": "topic",
      "url": "/documentation/vision/vntrackrectanglerequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackingRequest": {
      "abstract": [
        {
          "text": "The abstract superclass for image-analysis requests that track unique features across multiple images or video frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackingRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackingRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackingRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackingRequest",
      "type": "topic",
      "url": "/documentation/vision/vntrackingrequest"
    },
    "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api": {
      "abstract": [],
      "identifier": "doc://com.apple.vision/documentation/Vision/original-objective-c-and-swift-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original Objective-C and Swift API",
      "type": "topic",
      "url": "/documentation/vision/original-objective-c-and-swift-api"
    },
    "doc://com.apple.vision/documentation/Vision/tracking-the-user-s-face-in-real-time": {
      "abstract": [
        {
          "text": "Detect and track faces from the selfie cam feed in real time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/tracking-the-user-s-face-in-real-time",
      "kind": "article",
      "role": "sampleCode",
      "title": "Tracking the User’s Face in Real Time",
      "type": "topic",
      "url": "/documentation/vision/tracking-the-user-s-face-in-real-time"
    },
    "https://developer.apple.com/documentation/foundation/uuid": {
      "identifier": "https://developer.apple.com/documentation/foundation/uuid",
      "title": "UUID",
      "titleInlineContent": [
        {
          "code": "UUID",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/foundation/uuid"
    },
    "https://developer.apple.com/documentation/vision": {
      "identifier": "https://developer.apple.com/documentation/vision",
      "title": "Vision",
      "titleInlineContent": [
        {
          "text": "Vision",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/vision"
    },
    "https://developer.apple.com/documentation/vision/vndetectedobjectobservation": {
      "identifier": "https://developer.apple.com/documentation/vision/vndetectedobjectobservation",
      "title": "VNDetectedObjectObservation",
      "titleInlineContent": [
        {
          "code": "VNDetectedObjectObservation",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/vision/vndetectedobjectobservation"
    },
    "https://developer.apple.com/documentation/vision/vndetectedobjectobservation/2867227-boundingbox": {
      "identifier": "https://developer.apple.com/documentation/vision/vndetectedobjectobservation/2867227-boundingbox",
      "title": "boundingBox",
      "titleInlineContent": [
        {
          "code": "boundingBox",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/vision/vndetectedobjectobservation/2867227-boundingbox"
    },
    "https://developer.apple.com/documentation/vision/vndetectrectanglesrequest": {
      "identifier": "https://developer.apple.com/documentation/vision/vndetectrectanglesrequest",
      "title": "VNDetectRectanglesRequest",
      "titleInlineContent": [
        {
          "code": "VNDetectRectanglesRequest",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/vision/vndetectrectanglesrequest"
    },
    "https://developer.apple.com/documentation/vision/vnimagerequesthandler": {
      "identifier": "https://developer.apple.com/documentation/vision/vnimagerequesthandler",
      "title": "VNImageRequestHandler",
      "titleInlineContent": [
        {
          "code": "VNImageRequestHandler",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/vision/vnimagerequesthandler"
    },
    "https://developer.apple.com/documentation/vision/vnobservation": {
      "identifier": "https://developer.apple.com/documentation/vision/vnobservation",
      "title": "VNObservation",
      "titleInlineContent": [
        {
          "code": "VNObservation",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/vision/vnobservation"
    },
    "https://developer.apple.com/documentation/vision/vnrequest/2867238-results": {
      "identifier": "https://developer.apple.com/documentation/vision/vnrequest/2867238-results",
      "title": "results",
      "titleInlineContent": [
        {
          "code": "results",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/vision/vnrequest/2867238-results"
    },
    "https://developer.apple.com/documentation/vision/vnsequencerequesthandler": {
      "identifier": "https://developer.apple.com/documentation/vision/vnsequencerequesthandler",
      "title": "VNSequenceRequestHandler",
      "titleInlineContent": [
        {
          "code": "VNSequenceRequestHandler",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/vision/vnsequencerequesthandler"
    },
    "https://developer.apple.com/documentation/vision/vnsequencerequesthandler/2880308-perform": {
      "identifier": "https://developer.apple.com/documentation/vision/vnsequencerequesthandler/2880308-perform",
      "title": "perform(_:)",
      "titleInlineContent": [
        {
          "code": "perform(_:)",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/vision/vnsequencerequesthandler/2880308-perform"
    },
    "https://developer.apple.com/documentation/vision/vntrackobjectrequest": {
      "identifier": "https://developer.apple.com/documentation/vision/vntrackobjectrequest",
      "title": "VNTrackObjectRequest",
      "titleInlineContent": [
        {
          "code": "VNTrackObjectRequest",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/vision/vntrackobjectrequest"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "913130aaf0ea/TrackingMultipleObjectsOrRectanglesInVideo.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Object-tracking",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/tracking-the-user-s-face-in-real-time",
        "doc://com.apple.vision/documentation/Vision/VNTrackingRequest",
        "doc://com.apple.vision/documentation/Vision/VNTrackRectangleRequest",
        "doc://com.apple.vision/documentation/Vision/VNTrackObjectRequest",
        "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation"
      ],
      "title": "Object tracking"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Object-tracking",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/tracking-the-user-s-face-in-real-time",
                "doc://com.apple.vision/documentation/Vision/VNTrackingRequest",
                "doc://com.apple.vision/documentation/Vision/VNTrackRectangleRequest",
                "doc://com.apple.vision/documentation/Vision/VNTrackObjectRequest",
                "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation"
              ],
              "title": "Object tracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackObjectRequest/title",
          "value": "VNTrackObjectRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackObjectRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackObjectRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackObjectRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackObjectRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackRectangleRequest/title",
          "value": "VNTrackRectangleRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackRectangleRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackRectangleRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackRectangleRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackRectangleRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackingRequest/title",
          "value": "VNTrackingRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackingRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackingRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation/title",
          "value": "VNDetectedObjectObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectedObjectObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectedObjectObservation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/tracking-multiple-objects-or-rectangles-in-video"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/tracking-multiple-objects-or-rectangles-in-video"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
