{
  "abstract": [
    {
      "text": "The barcode symbologies that the framework detects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@VNBarcodeSymbology",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNBarcodeSymbology"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNBarcodeSymbology"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "VNBarcodeSymbology"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to get the specific symbologies the request supports.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology": {
      "abstract": [
        {
          "text": "The barcode symbologies that the framework detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbology"
        }
      ],
      "role": "symbol",
      "title": "VNBarcodeSymbology",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Aztec-6g0vi": {
      "abstract": [
        {
          "text": "A constant that indicates Aztec symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Aztec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Aztec-6g0vi",
      "kind": "symbol",
      "role": "symbol",
      "title": "Aztec",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/aztec-6g0vi"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code128-7spp7": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code128"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code128-7spp7",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code128",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code128-7spp7"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39-34358": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code39"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39-34358",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code39",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39-34358"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39Checksum-2jrn": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 symbology with a checksum.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code39Checksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39Checksum-2jrn",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code39Checksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39checksum-2jrn"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCII-m5wd": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 Full ASCII symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code39FullASCII"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCII-m5wd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code39FullASCII",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39fullascii-m5wd"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCIIChecksum-5xnfs": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 Full ASCII symbology with a checksum.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code39FullASCIIChecksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCIIChecksum-5xnfs",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code39FullASCIIChecksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39fullasciichecksum-5xnfs"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93-67nn0": {
      "abstract": [
        {
          "text": "A constant that indicates Code 93 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code93"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93-67nn0",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code93",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code93-67nn0"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93i-84cmv": {
      "abstract": [
        {
          "text": "A constant that indicates Code 93i symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code93i"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93i-84cmv",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code93i",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code93i-84cmv"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/DataMatrix-2fgc9": {
      "abstract": [
        {
          "text": "A constant that indicates Data Matrix symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/DataMatrix-2fgc9",
      "kind": "symbol",
      "role": "symbol",
      "title": "DataMatrix",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/datamatrix-2fgc9"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN13-8ir8e": {
      "abstract": [
        {
          "text": "A constant that indicates EAN-13 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAN13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN13-8ir8e",
      "kind": "symbol",
      "role": "symbol",
      "title": "EAN13",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/ean13-8ir8e"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN8-4rzbb": {
      "abstract": [
        {
          "text": "A constant that indicates EAN-8 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAN8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN8-4rzbb",
      "kind": "symbol",
      "role": "symbol",
      "title": "EAN8",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/ean8-4rzbb"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5-1r8e7": {
      "abstract": [
        {
          "text": "A constant that indicates Interleaved 2 of 5 (ITF) symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "I2of5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5-1r8e7",
      "kind": "symbol",
      "role": "symbol",
      "title": "I2of5",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/i2of5-1r8e7"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5Checksum-832s5": {
      "abstract": [
        {
          "text": "A constant that indicates Interleaved 2 of 5 (ITF) symbology with a checksum.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "I2of5Checksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5Checksum-832s5",
      "kind": "symbol",
      "role": "symbol",
      "title": "I2of5Checksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/i2of5checksum-832s5"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ITF14-1wp9s": {
      "abstract": [
        {
          "text": "A constant that indicates ITF-14 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITF14"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ITF14-1wp9s",
      "kind": "symbol",
      "role": "symbol",
      "title": "ITF14",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/itf14-1wp9s"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/PDF417-56ney": {
      "abstract": [
        {
          "text": "A constant that indicates PDF417 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDF417"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/PDF417-56ney",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDF417",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/pdf417-56ney"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/QR-2zqax": {
      "abstract": [
        {
          "text": "A constant that indicates Quick Response (QR) symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/QR-2zqax",
      "kind": "symbol",
      "role": "symbol",
      "title": "QR",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/qr-2zqax"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/UPCE-7qps5": {
      "abstract": [
        {
          "text": "A constant that indicates UPC-E symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UPCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/UPCE-7qps5",
      "kind": "symbol",
      "role": "symbol",
      "title": "UPCE",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/upce-7qps5"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/aztec-s3va": {
      "abstract": [
        {
          "text": "A constant that indicates Aztec symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aztec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/aztec-s3va",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyAztec"
        }
      ],
      "role": "symbol",
      "title": "aztec",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/aztec-s3va"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/codabar": {
      "abstract": [
        {
          "text": "A constant that indicates Codabar symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codabar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/codabar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCodabar"
        }
      ],
      "role": "symbol",
      "title": "codabar",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/codabar"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code128-1lkm2": {
      "abstract": [
        {
          "text": "A constant that indicates Code 128 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code128"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code128-1lkm2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode128"
        }
      ],
      "role": "symbol",
      "title": "code128",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code128-1lkm2"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39-2ggrb": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code39"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39-2ggrb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode39"
        }
      ],
      "role": "symbol",
      "title": "code39",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39-2ggrb"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39Checksum-3jdl6": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 symbology with a checksum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code39Checksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39Checksum-3jdl6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode39Checksum"
        }
      ],
      "role": "symbol",
      "title": "code39Checksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39checksum-3jdl6"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCII-942jj": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 Full ASCII symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code39FullASCII"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCII-942jj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode39FullASCII"
        }
      ],
      "role": "symbol",
      "title": "code39FullASCII",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39fullascii-942jj"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCIIChecksum-6700": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 Full ASCII symbology with a checksum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code39FullASCIIChecksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCIIChecksum-6700",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode39FullASCIIChecksum"
        }
      ],
      "role": "symbol",
      "title": "code39FullASCIIChecksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39fullasciichecksum-6700"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93-2geph": {
      "abstract": [
        {
          "text": "A constant that indicates Code 93 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code93"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93-2geph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode93"
        }
      ],
      "role": "symbol",
      "title": "code93",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code93-2geph"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93i-t5q5": {
      "abstract": [
        {
          "text": "A constant that indicates Code 93i symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code93i"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93i-t5q5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode93i"
        }
      ],
      "role": "symbol",
      "title": "code93i",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code93i-t5q5"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/dataMatrix-6tg7m": {
      "abstract": [
        {
          "text": "A constant that indicates Data Matrix symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/dataMatrix-6tg7m",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyDataMatrix"
        }
      ],
      "role": "symbol",
      "title": "dataMatrix",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/datamatrix-6tg7m"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean13-7gb2d": {
      "abstract": [
        {
          "text": "A constant that indicates EAN-13 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ean13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean13-7gb2d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyEAN13"
        }
      ],
      "role": "symbol",
      "title": "ean13",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/ean13-7gb2d"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean8-9qg0n": {
      "abstract": [
        {
          "text": "A constant that indicates EAN-8 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ean8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean8-9qg0n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyEAN8"
        }
      ],
      "role": "symbol",
      "title": "ean8",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/ean8-9qg0n"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBar": {
      "abstract": [
        {
          "text": "A constant that indicates GS1 DataBar symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gs1DataBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyGS1DataBar"
        }
      ],
      "role": "symbol",
      "title": "gs1DataBar",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/gs1databar"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarExpanded": {
      "abstract": [
        {
          "text": "A constant that indicates GS1 DataBar Expanded symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gs1DataBarExpanded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarExpanded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyGS1DataBarExpanded"
        }
      ],
      "role": "symbol",
      "title": "gs1DataBarExpanded",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/gs1databarexpanded"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarLimited": {
      "abstract": [
        {
          "text": "A constant that indicates GS1 DataBar Limited symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gs1DataBarLimited"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarLimited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyGS1DataBarLimited"
        }
      ],
      "role": "symbol",
      "title": "gs1DataBarLimited",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/gs1databarlimited"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/i2of5-cyk4": {
      "abstract": [
        {
          "text": "A constant that indicates Interleaved 2 of 5 (ITF) symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "i2of5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/i2of5-cyk4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyI2of5"
        }
      ],
      "role": "symbol",
      "title": "i2of5",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/i2of5-cyk4"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/i2of5Checksum-999jm": {
      "abstract": [
        {
          "text": "A constant that indicates Interleaved 2 of 5 (ITF) symbology with a checksum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "i2of5Checksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/i2of5Checksum-999jm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyI2of5Checksum"
        }
      ],
      "role": "symbol",
      "title": "i2of5Checksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/i2of5checksum-999jm"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a symbology with a string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/init(rawvalue:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/itf14-9mbkq": {
      "abstract": [
        {
          "text": "A constant that indicates ITF-14 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itf14"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/itf14-9mbkq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyITF14"
        }
      ],
      "role": "symbol",
      "title": "itf14",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/itf14-9mbkq"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/microPDF417": {
      "abstract": [
        {
          "text": "A constant that indicates MicroPDF417 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microPDF417"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/microPDF417",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyMicroPDF417"
        }
      ],
      "role": "symbol",
      "title": "microPDF417",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/micropdf417"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/microQR": {
      "abstract": [
        {
          "text": "A constant that indicates MicroQR symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microQR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/microQR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyMicroQR"
        }
      ],
      "role": "symbol",
      "title": "microQR",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/microqr"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/msiPlessey": {
      "abstract": [
        {
          "text": "A constant that indicates Modified Plessey symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msiPlessey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/msiPlessey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyMSIPlessey"
        }
      ],
      "role": "symbol",
      "title": "msiPlessey",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/msiplessey"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/pdf417-8n3oh": {
      "abstract": [
        {
          "text": "A constant that indicates PDF417 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pdf417"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/pdf417-8n3oh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyPDF417"
        }
      ],
      "role": "symbol",
      "title": "pdf417",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/pdf417-8n3oh"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/qr-2l1ve": {
      "abstract": [
        {
          "text": "A constant that indicates Quick Response (QR) symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "qr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/qr-2l1ve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyQR"
        }
      ],
      "role": "symbol",
      "title": "qr",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/qr-2l1ve"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/upce-1jtoc": {
      "abstract": [
        {
          "text": "A constant that indicates UPC-E symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/upce-1jtoc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyUPCE"
        }
      ],
      "role": "symbol",
      "title": "upce",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/upce-1jtoc"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/coalesceCompositeSymbologies": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to coalesce multiple codes based on the symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coalesceCompositeSymbologies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/coalesceCompositeSymbologies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coalesceCompositeSymbologies"
        }
      ],
      "role": "symbol",
      "title": "coalesceCompositeSymbologies",
      "type": "topic",
      "url": "/documentation/vision/vndetectbarcodesrequest/coalescecompositesymbologies"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies": {
      "abstract": [
        {
          "text": "The array of barcode symbologies that the request supports.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedSymbologies"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedSymbologies"
        }
      ],
      "role": "symbol",
      "title": "supportedSymbologies",
      "type": "topic",
      "url": "/documentation/vision/vndetectbarcodesrequest/supportedsymbologies"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies()": {
      "abstract": [
        {
          "text": "Returns the barcode symbologies that the request supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedSymbologies"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedSymbologiesAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "supportedSymbologies()",
      "type": "topic",
      "url": "/documentation/vision/vndetectbarcodesrequest/supportedsymbologies()"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/symbologies": {
      "abstract": [
        {
          "text": "The barcode symbologies that the request detects in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbologies"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/symbologies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbologies"
        }
      ],
      "role": "symbol",
      "title": "symbologies",
      "type": "topic",
      "url": "/documentation/vision/vndetectbarcodesrequest/symbologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Symbologies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies()",
        "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/symbologies",
        "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/coalesceCompositeSymbologies",
        "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies"
      ],
      "title": "Specifying Symbologies"
    }
  ],
  "topicSections": [
    {
      "anchor": "Supported-Symbologies",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/aztec-s3va",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/codabar",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39-2ggrb",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39Checksum-3jdl6",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCII-942jj",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCIIChecksum-6700",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93-2geph",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93i-t5q5",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code128-1lkm2",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/dataMatrix-6tg7m",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean8-9qg0n",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean13-7gb2d",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBar",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarExpanded",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarLimited",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/i2of5-cyk4",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/i2of5Checksum-999jm",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/itf14-9mbkq",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/microPDF417",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/microQR",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/msiPlessey",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/pdf417-8n3oh",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/qr-2l1ve",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/upce-1jtoc"
      ],
      "title": "Supported Symbologies"
    },
    {
      "anchor": "Deprecated-Symbols",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Aztec-6g0vi",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code128-7spp7",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39-34358",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39Checksum-2jrn",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCII-m5wd",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCIIChecksum-5xnfs",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93-67nn0",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93i-84cmv",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/DataMatrix-2fgc9",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN8-4rzbb",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN13-8ir8e",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5-1r8e7",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5Checksum-832s5",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ITF14-1wp9s",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/PDF417-56ney",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/QR-2zqax",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/UPCE-7qps5"
      ],
      "title": "Deprecated Symbols"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNBarcodeSymbology"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Supported-Symbologies",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/aztec-s3va",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/codabar",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39-2ggrb",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39Checksum-3jdl6",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCII-942jj",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCIIChecksum-6700",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93-2geph",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93i-t5q5",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code128-1lkm2",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/dataMatrix-6tg7m",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean8-9qg0n",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean13-7gb2d",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBar",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarExpanded",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarLimited",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/i2of5-cyk4",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/i2of5Checksum-999jm",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/itf14-9mbkq",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/microPDF417",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/microQR",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/msiPlessey",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/pdf417-8n3oh",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/qr-2l1ve",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/upce-1jtoc"
              ],
              "title": "Supported Symbologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Symbologies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies()",
                "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/symbologies",
                "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/coalesceCompositeSymbologies",
                "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies"
              ],
              "title": "Specifying Symbologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNBarcodeSymbology"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBarLimited/title",
          "value": "VNBarcodeSymbologyGS1DataBarLimited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBarLimited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyGS1DataBarLimited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1upce-1jtoc/title",
          "value": "VNBarcodeSymbologyUPCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1upce-1jtoc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyUPCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code93i-t5q5/title",
          "value": "VNBarcodeSymbologyCode93i"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code93i-t5q5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode93i"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code93-2geph/title",
          "value": "VNBarcodeSymbologyCode93"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code93-2geph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode93"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1i2of5Checksum-999jm/title",
          "value": "VNBarcodeSymbologyI2of5Checksum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1i2of5Checksum-999jm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyI2of5Checksum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1pdf417-8n3oh/title",
          "value": "VNBarcodeSymbologyPDF417"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1pdf417-8n3oh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyPDF417"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/title",
          "value": "VNBarcodeSymbology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1codabar/title",
          "value": "VNBarcodeSymbologyCodabar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1codabar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCodabar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39Checksum-3jdl6/title",
          "value": "VNBarcodeSymbologyCode39Checksum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39Checksum-3jdl6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode39Checksum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39-2ggrb/title",
          "value": "VNBarcodeSymbologyCode39"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39-2ggrb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode39"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1ean8-9qg0n/title",
          "value": "VNBarcodeSymbologyEAN8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1ean8-9qg0n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyEAN8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1itf14-9mbkq/title",
          "value": "VNBarcodeSymbologyITF14"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1itf14-9mbkq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyITF14"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1symbologies/title",
          "value": "symbologies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1symbologies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1i2of5-cyk4/title",
          "value": "VNBarcodeSymbologyI2of5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1i2of5-cyk4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyI2of5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1supportedSymbologies()/title",
          "value": "supportedSymbologiesAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1supportedSymbologies()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportedSymbologiesAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBar/title",
          "value": "VNBarcodeSymbologyGS1DataBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyGS1DataBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39FullASCIIChecksum-6700/title",
          "value": "VNBarcodeSymbologyCode39FullASCIIChecksum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39FullASCIIChecksum-6700/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode39FullASCIIChecksum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39FullASCII-942jj/title",
          "value": "VNBarcodeSymbologyCode39FullASCII"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39FullASCII-942jj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode39FullASCII"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1dataMatrix-6tg7m/title",
          "value": "VNBarcodeSymbologyDataMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1dataMatrix-6tg7m/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyDataMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1microPDF417/title",
          "value": "VNBarcodeSymbologyMicroPDF417"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1microPDF417/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyMicroPDF417"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1ean13-7gb2d/title",
          "value": "VNBarcodeSymbologyEAN13"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1ean13-7gb2d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyEAN13"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBarExpanded/title",
          "value": "VNBarcodeSymbologyGS1DataBarExpanded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBarExpanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyGS1DataBarExpanded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1supportedSymbologies/title",
          "value": "supportedSymbologies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1supportedSymbologies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedSymbologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1aztec-s3va/title",
          "value": "VNBarcodeSymbologyAztec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1aztec-s3va/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyAztec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1qr-2l1ve/title",
          "value": "VNBarcodeSymbologyQR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1qr-2l1ve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyQR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1coalesceCompositeSymbologies/title",
          "value": "coalesceCompositeSymbologies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1coalesceCompositeSymbologies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "coalesceCompositeSymbologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1microQR/title",
          "value": "VNBarcodeSymbologyMicroQR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1microQR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyMicroQR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1msiPlessey/title",
          "value": "VNBarcodeSymbologyMSIPlessey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1msiPlessey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyMSIPlessey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code128-1lkm2/title",
          "value": "VNBarcodeSymbologyCode128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code128-1lkm2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode128"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnbarcodesymbology"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnbarcodesymbology"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
