{
  "abstract": [
    {
      "text": "An object that represents a collection of key-value information that a Core ML image-analysis request produces.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNCoreMLFeatureValueObservation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNCoreMLFeatureValueObservation"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNCoreMLFeatureValueObservation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNCoreMLFeatureValueObservation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNCoreMLFeatureValueObservation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This type of observation results from performing a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNCoreMLRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " image analysis with a Core ML model whose role is prediction rather than classification or image-to-image processing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Vision infers that an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreML/MLModel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is a predictor model if that model predicts multiple features. You can tell that a model predicts multiple features when its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreML/MLModel/modelDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object has a ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " value for its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreML/MLModelDescription/predictedFeatureName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, or when it inserts its output in an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreML/MLModelDescription/outputDescriptionsByName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/CoreML/MLModel": {
      "abstract": [
        {
          "text": "An encapsulation of all the details of your machine learning model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModel"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreML/MLModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLModel",
      "type": "topic",
      "url": "/documentation/CoreML/MLModel"
    },
    "doc://com.apple.documentation/documentation/CoreML/MLModel/modelDescription": {
      "abstract": [
        {
          "text": "Model information you use at runtime during development, which Xcode also displays in its Core ML model editor view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelDescription",
          "text": "MLModelDescription"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreML/MLModel/modelDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "modelDescription",
      "type": "topic",
      "url": "/documentation/CoreML/MLModel/modelDescription"
    },
    "doc://com.apple.documentation/documentation/CoreML/MLModelDescription/outputDescriptionsByName": {
      "abstract": [
        {
          "text": "A dictionary of output feature descriptions, which the model keys by the output’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputDescriptionsByName"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLFeatureDescription",
          "text": "MLFeatureDescription"
        },
        {
          "kind": "text",
          "text": "] { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreML/MLModelDescription/outputDescriptionsByName",
      "kind": "symbol",
      "role": "symbol",
      "title": "outputDescriptionsByName",
      "type": "topic",
      "url": "/documentation/CoreML/MLModelDescription/outputDescriptionsByName"
    },
    "doc://com.apple.documentation/documentation/CoreML/MLModelDescription/predictedFeatureName": {
      "abstract": [
        {
          "text": "The name of the primary prediction feature output description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictedFeatureName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreML/MLModelDescription/predictedFeatureName",
      "kind": "symbol",
      "role": "symbol",
      "title": "predictedFeatureName",
      "type": "topic",
      "url": "/documentation/CoreML/MLModelDescription/predictedFeatureName"
    },
    "doc://com.apple.documentation/documentation/coreml/model_integration_samples/classifying_images_with_vision_and_core_ml": {
      "abstract": [
        {
          "text": "Crop and scale photos using the Vision framework and classify them with a Core ML model.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreml/model_integration_samples/classifying_images_with_vision_and_core_ml",
      "kind": "article",
      "role": "sampleCode",
      "title": "Classifying Images with Vision and Core ML",
      "type": "topic",
      "url": "/documentation/coreml/model_integration_samples/classifying_images_with_vision_and_core_ml"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNClassificationObservation": {
      "abstract": [
        {
          "text": "An object that represents classification information that an image-analysis request produces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNClassificationObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNClassificationObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNClassificationObservation"
        }
      ],
      "role": "symbol",
      "title": "VNClassificationObservation",
      "type": "topic",
      "url": "/documentation/vision/vnclassificationobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation": {
      "abstract": [
        {
          "text": "An object that represents a collection of key-value information that a Core ML image-analysis request produces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNCoreMLFeatureValueObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNCoreMLFeatureValueObservation"
        }
      ],
      "role": "symbol",
      "title": "VNCoreMLFeatureValueObservation",
      "type": "topic",
      "url": "/documentation/vision/vncoremlfeaturevalueobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation/featureName": {
      "abstract": [
        {
          "text": "The name used in the model description of the CoreML model that produced this observation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation/featureName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "featureName"
        }
      ],
      "role": "symbol",
      "title": "featureName",
      "type": "topic",
      "url": "/documentation/vision/vncoremlfeaturevalueobservation/featurename"
    },
    "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation/featureValue": {
      "abstract": [
        {
          "text": "The feature result of a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.vision/documentation/Vision/VNCoreMLRequest",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that outputs neither a classification nor an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLFeatureValue",
          "text": "MLFeatureValue"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation/featureValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "featureValue"
        }
      ],
      "role": "symbol",
      "title": "featureValue",
      "type": "topic",
      "url": "/documentation/vision/vncoremlfeaturevalueobservation/featurevalue"
    },
    "doc://com.apple.vision/documentation/Vision/VNCoreMLRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that uses a Core ML model to process images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNCoreMLRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNCoreMLRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNCoreMLRequest"
        }
      ],
      "role": "symbol",
      "title": "VNCoreMLRequest",
      "type": "topic",
      "url": "/documentation/vision/vncoremlrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNObservation": {
      "abstract": [
        {
          "text": "The abstract superclass for analysis results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNObservation"
        }
      ],
      "role": "symbol",
      "title": "VNObservation",
      "type": "topic",
      "url": "/documentation/vision/vnobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNPixelBufferObservation": {
      "abstract": [
        {
          "text": "An object that represents an image that an image-analysis request produces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNPixelBufferObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNPixelBufferObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNPixelBufferObservation"
        }
      ],
      "role": "symbol",
      "title": "VNPixelBufferObservation",
      "type": "topic",
      "url": "/documentation/vision/vnpixelbufferobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestRevisionProviding": {
      "abstract": [
        {
          "text": "A protocol for specifying the revision number of Vision algorithms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRequestRevisionProviding"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestRevisionProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestRevisionProviding"
        }
      ],
      "role": "symbol",
      "title": "VNRequestRevisionProviding",
      "type": "topic",
      "url": "/documentation/vision/vnrequestrevisionproviding"
    },
    "doc://com.apple.vision/documentation/Vision/training-a-create-ml-model-to-classify-flowers": {
      "abstract": [
        {
          "text": "Train a flower classifier using Create ML in Swift Playgrounds, and apply the resulting model to real-time image classification using Vision.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/training-a-create-ml-model-to-classify-flowers",
      "kind": "article",
      "role": "sampleCode",
      "title": "Training a Create ML Model to Classify Flowers",
      "type": "topic",
      "url": "/documentation/vision/training-a-create-ml-model-to-classify-flowers"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNObservation"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.apple.vision/documentation/Vision/VNRequestRevisionProviding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Machine-learning-image-analysis",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/coreml/model_integration_samples/classifying_images_with_vision_and_core_ml",
        "doc://com.apple.vision/documentation/Vision/training-a-create-ml-model-to-classify-flowers",
        "doc://com.apple.vision/documentation/Vision/VNCoreMLRequest",
        "doc://com.apple.vision/documentation/Vision/VNClassificationObservation",
        "doc://com.apple.vision/documentation/Vision/VNPixelBufferObservation"
      ],
      "title": "Machine learning image analysis"
    }
  ],
  "topicSections": [
    {
      "anchor": "Obtaining-Feature-Values",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation/featureValue",
        "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation/featureName"
      ],
      "title": "Obtaining Feature Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNCoreMLFeatureValueObservation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNCoreMLFeatureValueObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNCoreMLFeatureValueObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Obtaining-Feature-Values",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation/featureValue",
                "doc://com.apple.vision/documentation/Vision/VNCoreMLFeatureValueObservation/featureName"
              ],
              "title": "Obtaining Feature Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNObservation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Machine-learning-image-analysis",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/coreml/model_integration_samples/classifying_images_with_vision_and_core_ml",
                "doc://com.apple.vision/documentation/Vision/training-a-create-ml-model-to-classify-flowers",
                "doc://com.apple.vision/documentation/Vision/VNCoreMLRequest",
                "doc://com.apple.vision/documentation/Vision/VNClassificationObservation",
                "doc://com.apple.vision/documentation/Vision/VNPixelBufferObservation"
              ],
              "title": "Machine learning image analysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNCoreMLFeatureValueObservation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNObservation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNObservation",
                    "text": "VNObservation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLFeatureValueObservation~1featureName/title",
          "value": "featureName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLFeatureValueObservation~1featureName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "featureName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreML~1MLModelDescription~1outputDescriptionsByName/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,MLFeatureDescription *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "outputDescriptionsByName"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLFeatureValueObservation~1featureValue/title",
          "value": "featureValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLFeatureValueObservation~1featureValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "featureValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreML~1MLModel~1modelDescription/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLModelDescription",
              "text": "MLModelDescription"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "modelDescription"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionProviding/title",
          "value": "VNRequestRevisionProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestRevisionProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestRevisionProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLFeatureValueObservation/title",
          "value": "VNCoreMLFeatureValueObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLFeatureValueObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNCoreMLFeatureValueObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLFeatureValueObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNCoreMLFeatureValueObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLRequest/title",
          "value": "VNCoreMLRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNCoreMLRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNCoreMLRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreML~1MLModelDescription~1predictedFeatureName/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "predictedFeatureName"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreML~1MLModel/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLModel"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNPixelBufferObservation/title",
          "value": "VNPixelBufferObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNPixelBufferObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNPixelBufferObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNPixelBufferObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNPixelBufferObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNClassificationObservation/title",
          "value": "VNClassificationObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNClassificationObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNClassificationObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNClassificationObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNClassificationObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNObservation/title",
          "value": "VNObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNObservation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vncoremlfeaturevalueobservation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vncoremlfeaturevalueobservation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
