{
  "abstract": [
    {
      "text": "An observation that provides the position and extent of an image feature that an image- analysis request detects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNDetectedObjectObservation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNDetectedObjectObservation"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNDetectedObjectObservation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNDetectedObjectObservation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNDetectedObjectObservation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class is the observation type that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackObjectRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " generates. It represents an object that the Vision request detects and tracks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation": {
      "abstract": [
        {
          "text": "An observation that provides the position and extent of an image feature that an image- analysis request detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectedObjectObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectedObjectObservation"
        }
      ],
      "role": "symbol",
      "title": "VNDetectedObjectObservation",
      "type": "topic",
      "url": "/documentation/vision/vndetectedobjectobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/boundingBox": {
      "abstract": [
        {
          "text": "The bounding box of the object that the request detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundingBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/boundingBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundingBox"
        }
      ],
      "role": "symbol",
      "title": "boundingBox",
      "type": "topic",
      "url": "/documentation/vision/vndetectedobjectobservation/boundingbox"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/globalSegmentationMask": {
      "abstract": [
        {
          "text": "A resulting pixel buffer from a request to generate a segmentation mask for an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "globalSegmentationMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNPixelBufferObservation",
          "text": "VNPixelBufferObservation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/globalSegmentationMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "globalSegmentationMask"
        }
      ],
      "role": "symbol",
      "title": "globalSegmentationMask",
      "type": "topic",
      "url": "/documentation/vision/vndetectedobjectobservation/globalsegmentationmask"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/init(boundingBox:)": {
      "abstract": [
        {
          "text": "Creates an observation with a bounding box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "boundingBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/init(boundingBox:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observationWithBoundingBox:"
        }
      ],
      "role": "symbol",
      "title": "init(boundingBox:)",
      "type": "topic",
      "url": "/documentation/vision/vndetectedobjectobservation/init(boundingbox:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/init(requestRevision:boundingBox:)": {
      "abstract": [
        {
          "text": "Creates an observation with a revision number and bounding box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "requestRevision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "boundingBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/init(requestRevision:boundingBox:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observationWithRequestRevision:boundingBox:"
        }
      ],
      "role": "symbol",
      "title": "init(requestRevision:boundingBox:)",
      "type": "topic",
      "url": "/documentation/vision/vndetectedobjectobservation/init(requestrevision:boundingbox:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceObservation": {
      "abstract": [
        {
          "text": "Face or facial-feature information that an image analysis request detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNFaceObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNFaceObservation"
        }
      ],
      "role": "symbol",
      "title": "VNFaceObservation",
      "type": "topic",
      "url": "/documentation/vision/vnfaceobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanObservation": {
      "abstract": [
        {
          "text": "An object that represents a person that the request detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanObservation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanObservation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNObservation": {
      "abstract": [
        {
          "text": "The abstract superclass for analysis results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNObservation"
        }
      ],
      "role": "symbol",
      "title": "VNObservation",
      "type": "topic",
      "url": "/documentation/vision/vnobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedObjectObservation": {
      "abstract": [
        {
          "text": "A detected object observation with an array of classification labels that classify the recognized object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedObjectObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedObjectObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedObjectObservation"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedObjectObservation",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedobjectobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNRectangleObservation": {
      "abstract": [
        {
          "text": "An object that represents the four vertices of a detected rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRectangleObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRectangleObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRectangleObservation"
        }
      ],
      "role": "symbol",
      "title": "VNRectangleObservation",
      "type": "topic",
      "url": "/documentation/vision/vnrectangleobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestRevisionProviding": {
      "abstract": [
        {
          "text": "A protocol for specifying the revision number of Vision algorithms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRequestRevisionProviding"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestRevisionProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestRevisionProviding"
        }
      ],
      "role": "symbol",
      "title": "VNRequestRevisionProviding",
      "type": "topic",
      "url": "/documentation/vision/vnrequestrevisionproviding"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackObjectRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that tracks the movement of a previously identified object across multiple images or video frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackObjectRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackObjectRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackObjectRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackObjectRequest",
      "type": "topic",
      "url": "/documentation/vision/vntrackobjectrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackRectangleRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that tracks movement of a previously identified rectangular object across multiple images or video frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackRectangleRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackRectangleRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackRectangleRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackRectangleRequest",
      "type": "topic",
      "url": "/documentation/vision/vntrackrectanglerequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackingRequest": {
      "abstract": [
        {
          "text": "The abstract superclass for image-analysis requests that track unique features across multiple images or video frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackingRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackingRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackingRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackingRequest",
      "type": "topic",
      "url": "/documentation/vision/vntrackingrequest"
    },
    "doc://com.apple.vision/documentation/Vision/tracking-multiple-objects-or-rectangles-in-video": {
      "abstract": [
        {
          "text": "Apply Vision algorithms to track objects or rectangles throughout a video.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/tracking-multiple-objects-or-rectangles-in-video",
      "kind": "article",
      "role": "sampleCode",
      "title": "Tracking Multiple Objects or Rectangles in Video",
      "type": "topic",
      "url": "/documentation/vision/tracking-multiple-objects-or-rectangles-in-video"
    },
    "doc://com.apple.vision/documentation/Vision/tracking-the-user-s-face-in-real-time": {
      "abstract": [
        {
          "text": "Detect and track faces from the selfie cam feed in real time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/tracking-the-user-s-face-in-real-time",
      "kind": "article",
      "role": "sampleCode",
      "title": "Tracking the User’s Face in Real Time",
      "type": "topic",
      "url": "/documentation/vision/tracking-the-user-s-face-in-real-time"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNObservation"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNFaceObservation",
        "doc://com.apple.vision/documentation/Vision/VNHumanObservation",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedObjectObservation",
        "doc://com.apple.vision/documentation/Vision/VNRectangleObservation"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.apple.vision/documentation/Vision/VNRequestRevisionProviding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Object-tracking",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/tracking-the-user-s-face-in-real-time",
        "doc://com.apple.vision/documentation/Vision/tracking-multiple-objects-or-rectangles-in-video",
        "doc://com.apple.vision/documentation/Vision/VNTrackingRequest",
        "doc://com.apple.vision/documentation/Vision/VNTrackRectangleRequest",
        "doc://com.apple.vision/documentation/Vision/VNTrackObjectRequest"
      ],
      "title": "Object tracking"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Observation",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/init(boundingBox:)",
        "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/init(requestRevision:boundingBox:)"
      ],
      "title": "Creating an Observation"
    },
    {
      "anchor": "Locating-a-Detected-Object",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/boundingBox"
      ],
      "title": "Locating a Detected Object"
    },
    {
      "anchor": "Accessing-an-Image-Mask",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/globalSegmentationMask"
      ],
      "title": "Accessing an Image Mask"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNDetectedObjectObservation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectedObjectObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectedObjectObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-Observation",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/init(boundingBox:)",
                "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/init(requestRevision:boundingBox:)"
              ],
              "title": "Creating an Observation"
            },
            {
              "anchor": "Locating-a-Detected-Object",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/boundingBox"
              ],
              "title": "Locating a Detected Object"
            },
            {
              "anchor": "Accessing-an-Image-Mask",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectedObjectObservation/globalSegmentationMask"
              ],
              "title": "Accessing an Image Mask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNObservation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNFaceObservation",
                "doc://com.apple.vision/documentation/Vision/VNHumanObservation",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedObjectObservation",
                "doc://com.apple.vision/documentation/Vision/VNRectangleObservation"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Object-tracking",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/tracking-the-user-s-face-in-real-time",
                "doc://com.apple.vision/documentation/Vision/tracking-multiple-objects-or-rectangles-in-video",
                "doc://com.apple.vision/documentation/Vision/VNTrackingRequest",
                "doc://com.apple.vision/documentation/Vision/VNTrackRectangleRequest",
                "doc://com.apple.vision/documentation/Vision/VNTrackObjectRequest"
              ],
              "title": "Object tracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNDetectedObjectObservation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNObservation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNObservation",
                    "text": "VNObservation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedObjectObservation/title",
          "value": "VNRecognizedObjectObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedObjectObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedObjectObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedObjectObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedObjectObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation~1init(requestRevision:boundingBox:)/title",
          "value": "observationWithRequestRevision:boundingBox:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation~1init(requestRevision:boundingBox:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "observationWithRequestRevision:boundingBox:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackingRequest/title",
          "value": "VNTrackingRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackingRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackingRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation~1boundingBox/title",
          "value": "boundingBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation~1boundingBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "boundingBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanObservation/title",
          "value": "VNHumanObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackObjectRequest/title",
          "value": "VNTrackObjectRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackObjectRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackObjectRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackObjectRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackObjectRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNObservation/title",
          "value": "VNObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackRectangleRequest/title",
          "value": "VNTrackRectangleRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackRectangleRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackRectangleRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackRectangleRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackRectangleRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation/title",
          "value": "VNDetectedObjectObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectedObjectObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectedObjectObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceObservation/title",
          "value": "VNFaceObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRectangleObservation/title",
          "value": "VNRectangleObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRectangleObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRectangleObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRectangleObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRectangleObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionProviding/title",
          "value": "VNRequestRevisionProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestRevisionProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestRevisionProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation~1globalSegmentationMask/title",
          "value": "globalSegmentationMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation~1globalSegmentationMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "globalSegmentationMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation~1init(boundingBox:)/title",
          "value": "observationWithBoundingBox:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedObjectObservation~1init(boundingBox:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "observationWithBoundingBox:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vndetectedobjectobservation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vndetectedobjectobservation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
