{
  "abstract": [
    {
      "text": "A typealias for expressing tolerance angles in Vision.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNDegrees"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@VNDegrees",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNDegrees"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNDegrees"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "VNDegrees"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNDegrees"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNAspectRatio": {
      "abstract": [
        {
          "text": "A type alias for expressing rectangle aspect ratios in Vision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNAspectRatio"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAspectRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAspectRatio"
        }
      ],
      "role": "symbol",
      "title": "VNAspectRatio",
      "type": "topic",
      "url": "/documentation/vision/vnaspectratio"
    },
    "doc://com.apple.vision/documentation/Vision/VNConfidence": {
      "abstract": [
        {
          "text": "A type alias for the confidence value of an observation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNConfidence"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNConfidence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNConfidence"
        }
      ],
      "role": "symbol",
      "title": "VNConfidence",
      "type": "topic",
      "url": "/documentation/vision/vnconfidence"
    },
    "doc://com.apple.vision/documentation/Vision/VNDegrees": {
      "abstract": [
        {
          "text": "A typealias for expressing tolerance angles in Vision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDegrees"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDegrees",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDegrees"
        }
      ],
      "role": "symbol",
      "title": "VNDegrees",
      "type": "topic",
      "url": "/documentation/vision/vndegrees"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/maximumAspectRatio": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "float",
          "type": "codeVoice"
        },
        {
          "text": " specifying the maximum aspect ratio of the rectangle to detect, defined as the shorter dimension over the longer dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumAspectRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAspectRatio",
          "text": "VNAspectRatio"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/maximumAspectRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumAspectRatio"
        }
      ],
      "role": "symbol",
      "title": "maximumAspectRatio",
      "type": "topic",
      "url": "/documentation/vision/vndetectrectanglesrequest/maximumaspectratio"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/maximumObservations": {
      "abstract": [
        {
          "text": "An integer specifying the maximum number of rectangles Vision returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumObservations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/maximumObservations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumObservations"
        }
      ],
      "role": "symbol",
      "title": "maximumObservations",
      "type": "topic",
      "url": "/documentation/vision/vndetectrectanglesrequest/maximumobservations"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumAspectRatio": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "float",
          "type": "codeVoice"
        },
        {
          "text": " specifying the minimum aspect ratio of the rectangle to detect, defined as the shorter dimension over the longer dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumAspectRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAspectRatio",
          "text": "VNAspectRatio"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumAspectRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumAspectRatio"
        }
      ],
      "role": "symbol",
      "title": "minimumAspectRatio",
      "type": "topic",
      "url": "/documentation/vision/vndetectrectanglesrequest/minimumaspectratio"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumConfidence": {
      "abstract": [
        {
          "text": "A value specifying the minimum acceptable confidence level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumConfidence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNConfidence",
          "text": "VNConfidence"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumConfidence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumConfidence"
        }
      ],
      "role": "symbol",
      "title": "minimumConfidence",
      "type": "topic",
      "url": "/documentation/vision/vndetectrectanglesrequest/minimumconfidence"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumSize": {
      "abstract": [
        {
          "text": "The minimum size of a rectangle to detect, as a proportion of the smallest dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumSize"
        }
      ],
      "role": "symbol",
      "title": "minimumSize",
      "type": "topic",
      "url": "/documentation/vision/vndetectrectanglesrequest/minimumsize"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/quadratureTolerance": {
      "abstract": [
        {
          "text": "A float specifying the number of degrees a rectangle corner angle can deviate from 90°.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quadratureTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNDegrees",
          "text": "VNDegrees"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/quadratureTolerance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "quadratureTolerance"
        }
      ],
      "role": "symbol",
      "title": "quadratureTolerance",
      "type": "topic",
      "url": "/documentation/vision/vndetectrectanglesrequest/quadraturetolerance"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Detection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumAspectRatio",
        "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/maximumAspectRatio",
        "doc://com.apple.vision/documentation/Vision/VNAspectRatio",
        "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/quadratureTolerance",
        "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumSize",
        "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumConfidence",
        "doc://com.apple.vision/documentation/Vision/VNConfidence",
        "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/maximumObservations"
      ],
      "title": "Configuring Detection"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNDegrees"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDegrees"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDegrees"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Detection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumAspectRatio",
                "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/maximumAspectRatio",
                "doc://com.apple.vision/documentation/Vision/VNAspectRatio",
                "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/quadratureTolerance",
                "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumSize",
                "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/minimumConfidence",
                "doc://com.apple.vision/documentation/Vision/VNConfidence",
                "doc://com.apple.vision/documentation/Vision/VNDetectRectanglesRequest/maximumObservations"
              ],
              "title": "Configuring Detection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNDegrees"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAspectRatio/title",
          "value": "VNAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAspectRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAspectRatio/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1maximumObservations/title",
          "value": "maximumObservations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1maximumObservations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumObservations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1minimumConfidence/title",
          "value": "minimumConfidence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1minimumConfidence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1quadratureTolerance/title",
          "value": "quadratureTolerance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1quadratureTolerance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "quadratureTolerance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNConfidence/title",
          "value": "VNConfidence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNConfidence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNConfidence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1minimumSize/title",
          "value": "minimumSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1minimumSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1minimumAspectRatio/title",
          "value": "minimumAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1minimumAspectRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDegrees/title",
          "value": "VNDegrees"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDegrees/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDegrees"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDegrees/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDegrees"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1maximumAspectRatio/title",
          "value": "maximumAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectRectanglesRequest~1maximumAspectRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumAspectRatio"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vndegrees"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vndegrees"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
