{
  "abstract": [
    {
      "text": "A request that detects the trajectories of shapes moving along a parabolic path.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNDetectTrajectoriesRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNDetectTrajectoriesRequest"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNDetectTrajectoriesRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNDetectTrajectoriesRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNDetectTrajectoriesRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.vision/documentation/Vision/identifying-trajectories-in-video"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After the request detects a trajectory, it produces an observation that contains the shape’s detected points and an equation describing the parabola.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest": {
      "abstract": [
        {
          "text": "A request that detects the trajectories of shapes moving along a parabolic path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectTrajectoriesRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectTrajectoriesRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectTrajectoriesRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetecttrajectoriesrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/init(frameAnalysisSpacing:trajectoryLength:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request to detect trajectories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "frameAnalysisSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trajectoryLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/init(frameAnalysisSpacing:trajectoryLength:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrameAnalysisSpacing:trajectoryLength:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(frameAnalysisSpacing:trajectoryLength:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vndetecttrajectoriesrequest/init(frameanalysisspacing:trajectorylength:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/maximumObjectSize": {
      "abstract": [
        {
          "text": "The maximum radius of the tracked shape’s bounding circle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumObjectSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/maximumObjectSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumObjectSize"
        }
      ],
      "role": "symbol",
      "title": "maximumObjectSize",
      "type": "topic",
      "url": "/documentation/vision/vndetecttrajectoriesrequest/maximumobjectsize"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/minimumObjectSize": {
      "abstract": [
        {
          "text": "The minimum radius of the tracked shape’s bounding circle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumObjectSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/minimumObjectSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumObjectSize"
        }
      ],
      "role": "symbol",
      "title": "minimumObjectSize",
      "type": "topic",
      "url": "/documentation/vision/vndetecttrajectoriesrequest/minimumobjectsize"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/objectMaximumNormalizedRadius": {
      "abstract": [
        {
          "text": "The maximum radius of the bounding circle of the object to track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectMaximumNormalizedRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/objectMaximumNormalizedRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectMaximumNormalizedRadius"
        }
      ],
      "role": "symbol",
      "title": "objectMaximumNormalizedRadius",
      "type": "topic",
      "url": "/documentation/vision/vndetecttrajectoriesrequest/objectmaximumnormalizedradius"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/objectMinimumNormalizedRadius": {
      "abstract": [
        {
          "text": "The minimum radius of the bounding circle of the object to track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectMinimumNormalizedRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/objectMinimumNormalizedRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectMinimumNormalizedRadius"
        }
      ],
      "role": "symbol",
      "title": "objectMinimumNormalizedRadius",
      "type": "topic",
      "url": "/documentation/vision/vndetecttrajectoriesrequest/objectminimumnormalizedradius"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/results": {
      "abstract": [
        {
          "text": "The array of detected trajectory observations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "results"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNTrajectoryObservation",
          "text": "VNTrajectoryObservation"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/results",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "results"
        }
      ],
      "role": "symbol",
      "title": "results",
      "type": "topic",
      "url": "/documentation/vision/vndetecttrajectoriesrequest/results"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/targetFrameTime": {
      "abstract": [
        {
          "text": "The requested target frame time for processing trajectory detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetFrameTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/targetFrameTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetFrameTime"
        }
      ],
      "role": "symbol",
      "title": "targetFrameTime",
      "type": "topic",
      "url": "/documentation/vision/vndetecttrajectoriesrequest/targetframetime"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/trajectoryLength": {
      "abstract": [
        {
          "text": "The number of points to detect before calculating a trajectory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trajectoryLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/trajectoryLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trajectoryLength"
        }
      ],
      "role": "symbol",
      "title": "trajectoryLength",
      "type": "topic",
      "url": "/documentation/vision/vndetecttrajectoriesrequest/trajectorylength"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequestRevision1": {
      "abstract": [
        {
          "text": "A constant for specifying revision 1 of the trajectories detection request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectTrajectoriesRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectTrajectoriesRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNDetectTrajectoriesRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vndetecttrajectoriesrequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNStatefulRequest": {
      "abstract": [
        {
          "text": "An abstract request type that builds evidence of a condition over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNStatefulRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNStatefulRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNStatefulRequest"
        }
      ],
      "role": "symbol",
      "title": "VNStatefulRequest",
      "type": "topic",
      "url": "/documentation/vision/vnstatefulrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrajectoryObservation": {
      "abstract": [
        {
          "text": "An observation that describes a detected trajectory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrajectoryObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrajectoryObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrajectoryObservation"
        }
      ],
      "role": "symbol",
      "title": "VNTrajectoryObservation",
      "type": "topic",
      "url": "/documentation/vision/vntrajectoryobservation"
    },
    "doc://com.apple.vision/documentation/Vision/detecting-moving-objects-in-a-video": {
      "abstract": [
        {
          "text": "Identify the trajectory of a thrown object by using Vision.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/detecting-moving-objects-in-a-video",
      "kind": "article",
      "role": "sampleCode",
      "title": "Detecting moving objects in a video",
      "type": "topic",
      "url": "/documentation/vision/detecting-moving-objects-in-a-video"
    },
    "doc://com.apple.vision/documentation/Vision/identifying-trajectories-in-video": {
      "abstract": [
        {
          "text": "Gain new insights into your video data by using Vision to detect trajectories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/identifying-trajectories-in-video",
      "kind": "article",
      "role": "article",
      "title": "Identifying Trajectories in Video",
      "type": "topic",
      "url": "/documentation/vision/identifying-trajectories-in-video"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNStatefulRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Trajectory-detection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/identifying-trajectories-in-video",
        "doc://com.apple.vision/documentation/Vision/detecting-moving-objects-in-a-video"
      ],
      "title": "Trajectory detection"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Request",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/init(frameAnalysisSpacing:trajectoryLength:completionHandler:)"
      ],
      "title": "Creating a Request"
    },
    {
      "anchor": "Configuring-the-Request",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/targetFrameTime",
        "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/trajectoryLength",
        "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/objectMinimumNormalizedRadius",
        "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/objectMaximumNormalizedRadius",
        "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/minimumObjectSize",
        "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/maximumObjectSize"
      ],
      "title": "Configuring the Request"
    },
    {
      "anchor": "Inspecting-the-Results",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/results",
        "doc://com.apple.vision/documentation/Vision/VNTrajectoryObservation"
      ],
      "title": "Inspecting the Results"
    },
    {
      "anchor": "Identifying-Request-Revisions",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequestRevision1"
      ],
      "title": "Identifying Request Revisions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNDetectTrajectoriesRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectTrajectoriesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectTrajectoriesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Request",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/init(frameAnalysisSpacing:trajectoryLength:completionHandler:)"
              ],
              "title": "Creating a Request"
            },
            {
              "anchor": "Configuring-the-Request",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/targetFrameTime",
                "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/trajectoryLength",
                "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/objectMinimumNormalizedRadius",
                "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/objectMaximumNormalizedRadius",
                "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/minimumObjectSize",
                "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/maximumObjectSize"
              ],
              "title": "Configuring the Request"
            },
            {
              "anchor": "Inspecting-the-Results",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequest/results",
                "doc://com.apple.vision/documentation/Vision/VNTrajectoryObservation"
              ],
              "title": "Inspecting the Results"
            },
            {
              "anchor": "Identifying-Request-Revisions",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectTrajectoriesRequestRevision1"
              ],
              "title": "Identifying Request Revisions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNStatefulRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Trajectory-detection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/identifying-trajectories-in-video",
                "doc://com.apple.vision/documentation/Vision/detecting-moving-objects-in-a-video"
              ],
              "title": "Trajectory detection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNDetectTrajectoriesRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNStatefulRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNStatefulRequest",
                    "text": "VNStatefulRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest/title",
          "value": "VNDetectTrajectoriesRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectTrajectoriesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectTrajectoriesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1trajectoryLength/title",
          "value": "trajectoryLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1trajectoryLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trajectoryLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1targetFrameTime/title",
          "value": "targetFrameTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1targetFrameTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "targetFrameTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1maximumObjectSize/title",
          "value": "maximumObjectSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1maximumObjectSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumObjectSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/title",
          "value": "VNStatefulRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNStatefulRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNStatefulRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrajectoryObservation/title",
          "value": "VNTrajectoryObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrajectoryObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrajectoryObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrajectoryObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrajectoryObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1objectMaximumNormalizedRadius/title",
          "value": "objectMaximumNormalizedRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1objectMaximumNormalizedRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "objectMaximumNormalizedRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1objectMinimumNormalizedRadius/title",
          "value": "objectMinimumNormalizedRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1objectMinimumNormalizedRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "objectMinimumNormalizedRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1init(frameAnalysisSpacing:trajectoryLength:completionHandler:)/title",
          "value": "initWithFrameAnalysisSpacing:trajectoryLength:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1init(frameAnalysisSpacing:trajectoryLength:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrameAnalysisSpacing:trajectoryLength:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1minimumObjectSize/title",
          "value": "minimumObjectSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1minimumObjectSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumObjectSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1results/title",
          "value": "results"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequest~1results/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequestRevision1/title",
          "value": "VNDetectTrajectoriesRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectTrajectoriesRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectTrajectoriesRequestRevision1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vndetecttrajectoriesrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vndetecttrajectoriesrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
