{
  "abstract": [
    {
      "text": "An object that detects rectangular regions that contain text in the input image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNDetectDocumentSegmentationRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNDetectDocumentSegmentationRequest"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNDetectDocumentSegmentationRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNDetectDocumentSegmentationRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNDetectDocumentSegmentationRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Perform this request to detect a document in an image. The result that the request generates contains the four corner points of a document’s quadrilateral and saliency mask.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/createml/detecting_human_actions_in_a_live_video_feed": {
      "abstract": [
        {
          "text": "Identify body movements by sending a person’s pose data from a series of video frames to an action-classification model.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/createml/detecting_human_actions_in_a_live_video_feed",
      "kind": "article",
      "role": "sampleCode",
      "title": "Detecting Human Actions in a Live Video Feed",
      "type": "topic",
      "url": "/documentation/createml/detecting_human_actions_in_a_live_video_feed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequest": {
      "abstract": [
        {
          "text": "An object that detects rectangular regions that contain text in the input image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectDocumentSegmentationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectDocumentSegmentationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectDocumentSegmentationRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetectdocumentsegmentationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequest/results": {
      "abstract": [
        {
          "text": "The results of a document segmentation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "results"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNRectangleObservation",
          "text": "VNRectangleObservation"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequest/results",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "results"
        }
      ],
      "role": "symbol",
      "title": "results",
      "type": "topic",
      "url": "/documentation/vision/vndetectdocumentsegmentationrequest/results"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequestRevision1": {
      "abstract": [
        {
          "text": "A constant for specifying revision 1 of the document segmentation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectDocumentSegmentationRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectDocumentSegmentationRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNDetectDocumentSegmentationRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vndetectdocumentsegmentationrequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNGeneratePersonInstanceMaskRequest": {
      "abstract": [
        {
          "text": "An object that produces a mask of individual people it finds in the input image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGeneratePersonInstanceMaskRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonInstanceMaskRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGeneratePersonInstanceMaskRequest"
        }
      ],
      "role": "symbol",
      "title": "VNGeneratePersonInstanceMaskRequest",
      "type": "topic",
      "url": "/documentation/vision/vngeneratepersoninstancemaskrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest": {
      "abstract": [
        {
          "text": "An object that produces a matte image for a person it finds in the input image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGeneratePersonSegmentationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGeneratePersonSegmentationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNGeneratePersonSegmentationRequest",
      "type": "topic",
      "url": "/documentation/vision/vngeneratepersonsegmentationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest": {
      "abstract": [
        {
          "text": "The abstract superclass for image-analysis requests that focus on a specific part of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageBasedRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageBasedRequest"
        }
      ],
      "role": "symbol",
      "title": "VNImageBasedRequest",
      "type": "topic",
      "url": "/documentation/vision/vnimagebasedrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNRectangleObservation": {
      "abstract": [
        {
          "text": "An object that represents the four vertices of a detected rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRectangleObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRectangleObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRectangleObservation"
        }
      ],
      "role": "symbol",
      "title": "VNRectangleObservation",
      "type": "topic",
      "url": "/documentation/vision/vnrectangleobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNSequenceRequestHandler": {
      "abstract": [
        {
          "text": "An object that processes image-analysis requests for each frame in a sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNSequenceRequestHandler"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNSequenceRequestHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNSequenceRequestHandler"
        }
      ],
      "role": "symbol",
      "title": "VNSequenceRequestHandler",
      "type": "topic",
      "url": "/documentation/vision/vnsequencerequesthandler"
    },
    "doc://com.apple.vision/documentation/Vision/VNStatefulRequest": {
      "abstract": [
        {
          "text": "An abstract request type that builds evidence of a condition over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNStatefulRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNStatefulRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNStatefulRequest"
        }
      ],
      "role": "symbol",
      "title": "VNStatefulRequest",
      "type": "topic",
      "url": "/documentation/vision/vnstatefulrequest"
    },
    "doc://com.apple.vision/documentation/Vision/applying-matte-effects-to-people-in-images-and-video": {
      "abstract": [
        {
          "text": "Generate image masks for people automatically by using semantic person-segmentation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/applying-matte-effects-to-people-in-images-and-video",
      "kind": "article",
      "role": "sampleCode",
      "title": "Applying Matte Effects to People in Images and Video",
      "type": "topic",
      "url": "/documentation/vision/applying-matte-effects-to-people-in-images-and-video"
    },
    "doc://com.apple.vision/documentation/Vision/segmenting-and-colorizing-individuals-from-a-surrounding-scene": {
      "abstract": [
        {
          "text": "Use the Vision framework to isolate and apply colors to people in an image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/segmenting-and-colorizing-individuals-from-a-surrounding-scene",
      "kind": "article",
      "role": "sampleCode",
      "title": "Segmenting and colorizing individuals from a surrounding scene",
      "type": "topic",
      "url": "/documentation/vision/segmenting-and-colorizing-individuals-from-a-surrounding-scene"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-sequence-analysis",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/applying-matte-effects-to-people-in-images-and-video",
        "doc://com.apple.documentation/documentation/createml/detecting_human_actions_in_a_live_video_feed",
        "doc://com.apple.vision/documentation/Vision/segmenting-and-colorizing-individuals-from-a-surrounding-scene",
        "doc://com.apple.vision/documentation/Vision/VNStatefulRequest",
        "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest",
        "doc://com.apple.vision/documentation/Vision/VNGeneratePersonInstanceMaskRequest",
        "doc://com.apple.vision/documentation/Vision/VNSequenceRequestHandler"
      ],
      "title": "Image sequence analysis"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Results",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequest/results",
        "doc://com.apple.vision/documentation/Vision/VNRectangleObservation"
      ],
      "title": "Accessing the Results"
    },
    {
      "anchor": "Identifying-Request-Revisions",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequestRevision1"
      ],
      "title": "Identifying Request Revisions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNDetectDocumentSegmentationRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectDocumentSegmentationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectDocumentSegmentationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Results",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequest/results",
                "doc://com.apple.vision/documentation/Vision/VNRectangleObservation"
              ],
              "title": "Accessing the Results"
            },
            {
              "anchor": "Identifying-Request-Revisions",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectDocumentSegmentationRequestRevision1"
              ],
              "title": "Identifying Request Revisions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-sequence-analysis",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/applying-matte-effects-to-people-in-images-and-video",
                "doc://com.apple.vision/documentation/Vision/segmenting-and-colorizing-individuals-from-a-surrounding-scene",
                "doc://com.apple.vision/documentation/Vision/VNStatefulRequest",
                "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest",
                "doc://com.apple.vision/documentation/Vision/VNGeneratePersonInstanceMaskRequest",
                "doc://com.apple.vision/documentation/Vision/VNSequenceRequestHandler"
              ],
              "title": "Image sequence analysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNDetectDocumentSegmentationRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNImageBasedRequest",
                    "text": "VNImageBasedRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectDocumentSegmentationRequest/title",
          "value": "VNDetectDocumentSegmentationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectDocumentSegmentationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectDocumentSegmentationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectDocumentSegmentationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectDocumentSegmentationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNSequenceRequestHandler/title",
          "value": "VNSequenceRequestHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNSequenceRequestHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNSequenceRequestHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNSequenceRequestHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNSequenceRequestHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectDocumentSegmentationRequest~1results/title",
          "value": "results"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectDocumentSegmentationRequest~1results/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/title",
          "value": "VNStatefulRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNStatefulRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNStatefulRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest/title",
          "value": "VNGeneratePersonSegmentationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectDocumentSegmentationRequestRevision1/title",
          "value": "VNDetectDocumentSegmentationRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectDocumentSegmentationRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectDocumentSegmentationRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageBasedRequest/title",
          "value": "VNImageBasedRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageBasedRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageBasedRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageBasedRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageBasedRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRectangleObservation/title",
          "value": "VNRectangleObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRectangleObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRectangleObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRectangleObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRectangleObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonInstanceMaskRequest/title",
          "value": "VNGeneratePersonInstanceMaskRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonInstanceMaskRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonInstanceMaskRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonInstanceMaskRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonInstanceMaskRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vndetectdocumentsegmentationrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vndetectdocumentsegmentationrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
