{
  "abstract": [
    {
      "text": "A request that produces a floating-point number that represents the capture quality of a face in a photo.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNDetectFaceCaptureQualityRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNDetectFaceCaptureQualityRequest"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNDetectFaceCaptureQualityRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNDetectFaceCaptureQualityRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNDetectFaceCaptureQualityRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This request produces or updates a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceObservation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object’s property ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceObservation/faceCaptureQuality-bjg5",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with a floating-point value. The value ranges from ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ". Faces with quality closer to ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": " are better lit, sharper, and more centrally positioned than faces with quality closer to ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t execute the request, or the request fails, the property ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceObservation/faceCaptureQuality-bjg5",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nil-2gl",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/objectivec/nil-2gl": {
      "abstract": [
        {
          "text": "Defines the `id` of a null instance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nil-2gl",
      "kind": "symbol",
      "role": "symbol",
      "title": "nil",
      "type": "topic",
      "url": "/documentation/objectivec/nil-2gl"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequest": {
      "abstract": [
        {
          "text": "A request that produces a floating-point number that represents the capture quality of a face in a photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectFaceCaptureQualityRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectFaceCaptureQualityRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectFaceCaptureQualityRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacecapturequalityrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequest/results": {
      "abstract": [
        {
          "text": "The results of the face-capture quality request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "results"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceObservation",
          "text": "VNFaceObservation"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequest/results",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "results"
        }
      ],
      "role": "symbol",
      "title": "results",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacecapturequalityrequest/results"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision1": {
      "abstract": [
        {
          "text": "A constant for specifying revision 1 of the face capture detection request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectFaceCaptureQualityRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectFaceCaptureQualityRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNDetectFaceCaptureQualityRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacecapturequalityrequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision2": {
      "abstract": [
        {
          "text": "Revision 2 of the request algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectFaceCaptureQualityRequestRevision2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectFaceCaptureQualityRequestRevision2"
        }
      ],
      "role": "symbol",
      "title": "VNDetectFaceCaptureQualityRequestRevision2",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacecapturequalityrequestrevision2"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that finds facial features like eyes and mouth in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectFaceLandmarksRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectFaceLandmarksRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectFaceLandmarksRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacelandmarksrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceRectanglesRequest": {
      "abstract": [
        {
          "text": "A request that finds faces within an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectFaceRectanglesRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceRectanglesRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectFaceRectanglesRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectFaceRectanglesRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacerectanglesrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanRectanglesRequest": {
      "abstract": [
        {
          "text": "A request that finds rectangular regions that contain people in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectHumanRectanglesRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanRectanglesRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectHumanRectanglesRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectHumanRectanglesRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanrectanglesrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceObservation": {
      "abstract": [
        {
          "text": "Face or facial-feature information that an image analysis request detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNFaceObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNFaceObservation"
        }
      ],
      "role": "symbol",
      "title": "VNFaceObservation",
      "type": "topic",
      "url": "/documentation/vision/vnfaceobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceObservation/faceCaptureQuality-bjg5": {
      "abstract": [
        {
          "text": "A value that indicates the quality of the face capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceCaptureQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceObservation/faceCaptureQuality-bjg5",
      "kind": "symbol",
      "role": "symbol",
      "title": "faceCaptureQuality",
      "type": "topic",
      "url": "/documentation/vision/vnfaceobservation/facecapturequality-bjg5"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceObservationAccepting": {
      "abstract": [
        {
          "text": "An image analysis request that operates on face observations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNFaceObservationAccepting"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceObservationAccepting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNFaceObservationAccepting"
        }
      ],
      "role": "symbol",
      "title": "VNFaceObservationAccepting",
      "type": "topic",
      "url": "/documentation/vision/vnfaceobservationaccepting"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanObservation": {
      "abstract": [
        {
          "text": "An object that represents a person that the request detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanObservation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanObservation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest": {
      "abstract": [
        {
          "text": "The abstract superclass for image-analysis requests that focus on a specific part of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageBasedRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageBasedRequest"
        }
      ],
      "role": "symbol",
      "title": "VNImageBasedRequest",
      "type": "topic",
      "url": "/documentation/vision/vnimagebasedrequest"
    },
    "doc://com.apple.vision/documentation/Vision/selecting-a-selfie-based-on-capture-quality": {
      "abstract": [
        {
          "text": "Compare face-capture quality in a set of images by using Vision.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/selecting-a-selfie-based-on-capture-quality",
      "kind": "article",
      "role": "sampleCode",
      "title": "Selecting a selfie based on capture quality",
      "type": "topic",
      "url": "/documentation/vision/selecting-a-selfie-based-on-capture-quality"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.vision/documentation/Vision/VNFaceObservationAccepting"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Face-and-body-detection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/selecting-a-selfie-based-on-capture-quality",
        "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest",
        "doc://com.apple.vision/documentation/Vision/VNDetectFaceRectanglesRequest",
        "doc://com.apple.vision/documentation/Vision/VNDetectHumanRectanglesRequest",
        "doc://com.apple.vision/documentation/Vision/VNHumanObservation"
      ],
      "title": "Face and body detection"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Results",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequest/results",
        "doc://com.apple.vision/documentation/Vision/VNFaceObservation"
      ],
      "title": "Accessing the Results"
    },
    {
      "anchor": "Identifying-Request-Revisions",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision2",
        "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision1"
      ],
      "title": "Identifying Request Revisions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNDetectFaceCaptureQualityRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceCaptureQualityRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceCaptureQualityRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Results",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequest/results",
                "doc://com.apple.vision/documentation/Vision/VNFaceObservation"
              ],
              "title": "Accessing the Results"
            },
            {
              "anchor": "Identifying-Request-Revisions",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision2",
                "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision1"
              ],
              "title": "Identifying Request Revisions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNFaceObservationAccepting"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Face-and-body-detection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest",
                "doc://com.apple.vision/documentation/Vision/VNDetectFaceRectanglesRequest",
                "doc://com.apple.vision/documentation/Vision/VNDetectHumanRectanglesRequest",
                "doc://com.apple.vision/documentation/Vision/VNHumanObservation"
              ],
              "title": "Face and body detection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNDetectFaceCaptureQualityRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNImageBasedRequest",
                    "text": "VNImageBasedRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequestRevision2/title",
          "value": "VNDetectFaceCaptureQualityRequestRevision2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequestRevision2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceCaptureQualityRequestRevision2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequest/title",
          "value": "VNDetectFaceCaptureQualityRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceCaptureQualityRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceCaptureQualityRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceObservation/title",
          "value": "VNFaceObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequestRevision1/title",
          "value": "VNDetectFaceCaptureQualityRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceCaptureQualityRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceObservationAccepting/title",
          "value": "VNFaceObservationAccepting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceObservationAccepting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceObservationAccepting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceObservationAccepting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceObservationAccepting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageBasedRequest/title",
          "value": "VNImageBasedRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageBasedRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageBasedRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageBasedRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageBasedRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequest~1results/title",
          "value": "results"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequest~1results/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceRectanglesRequest/title",
          "value": "VNDetectFaceRectanglesRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceRectanglesRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceRectanglesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceRectanglesRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceRectanglesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest/title",
          "value": "VNDetectFaceLandmarksRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceLandmarksRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceLandmarksRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanRectanglesRequest/title",
          "value": "VNDetectHumanRectanglesRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanRectanglesRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanRectanglesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanRectanglesRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanRectanglesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanObservation/title",
          "value": "VNHumanObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanObservation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vndetectfacecapturequalityrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vndetectfacecapturequalityrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
