{
  "abstract": [
    {
      "text": "A request that detects points on human bodies in 3D space, relative to the camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNDetectHumanBodyPose3DRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNDetectHumanBodyPose3DRequest"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNDetectHumanBodyPose3DRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNDetectHumanBodyPose3DRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNDetectHumanBodyPose3DRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.vision/documentation/Vision/identifying-3d-human-body-poses-in-images"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This request generates a collection of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects that describe the position of each body the request detects. If the system allows it, the request uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVDepthData",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " information to improve the accuracy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AVFoundation/AVDepthData": {
      "abstract": [
        {
          "text": "A container for per-pixel distance or disparity information captured by compatible camera devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDepthData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVDepthData",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVDepthData",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVDepthData"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest": {
      "abstract": [
        {
          "text": "A request that detects points on human bodies in 3D space, relative to the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectHumanBodyPose3DRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectHumanBodyPose3DRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectHumanBodyPose3DRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodypose3drequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/init()": {
      "abstract": [
        {
          "text": "Creates a new request with no completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodypose3drequest/init()"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/init(completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new 3D body pose request with a completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/init(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodypose3drequest/init(completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/results": {
      "abstract": [
        {
          "text": "The 3D body pose the request observes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "results"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPose3DObservation",
          "text": "VNHumanBodyPose3DObservation"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/results",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "results"
        }
      ],
      "role": "symbol",
      "title": "results",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodypose3drequest/results"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointNames": {
      "abstract": [
        {
          "text": "Returns the joint group names the request supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedJointNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPose3DObservation",
          "text": "VNHumanBodyPose3DObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPose3DObservationJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointNames",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedJointNames",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodypose3drequest/supportedjointnames"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointNamesAndReturnError:": {
      "abstract": [
        {
          "text": "Returns the joint names the request supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "supportedJointNamesAndReturnError:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointNamesAndReturnError:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedJointNamesAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "supportedJointNamesAndReturnError:",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodypose3drequest/supportedjointnamesandreturnerror:"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointsGroupNames": {
      "abstract": [
        {
          "text": "Returns the joint names the request supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedJointsGroupNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPose3DObservation",
          "text": "VNHumanBodyPose3DObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPose3DObservationJointsGroupName",
          "text": "JointsGroupName"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointsGroupNames",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedJointsGroupNames",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodypose3drequest/supportedjointsgroupnames"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointsGroupNamesAndReturnError:": {
      "abstract": [
        {
          "text": "Returns the joint group names the request supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "supportedJointsGroupNamesAndReturnError:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointsGroupNamesAndReturnError:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedJointsGroupNamesAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "supportedJointsGroupNamesAndReturnError:",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodypose3drequest/supportedjointsgroupnamesandreturnerror:"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation": {
      "abstract": [
        {
          "text": "An observation that provides the 3D body points the request recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanBodyPose3DObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPose3DObservation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/JointName": {
      "abstract": [
        {
          "text": "The joint names for a 3D body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/JointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation.JointName",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/jointname"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/JointsGroupName": {
      "abstract": [
        {
          "text": "The joint group names for a 3D body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/JointsGroupName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointsGroupName"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation.JointsGroupName",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/jointsgroupname"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyRecognizedPoint3D": {
      "abstract": [
        {
          "text": "A recognized 3D point that includes a parent joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanBodyRecognizedPoint3D"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyRecognizedPoint3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyRecognizedPoint3D"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyRecognizedPoint3D",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyrecognizedpoint3d"
    },
    "doc://com.apple.vision/documentation/Vision/VNPoint3D": {
      "abstract": [
        {
          "text": "An object that represents a 3D point in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNPoint3D"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNPoint3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNPoint3D"
        }
      ],
      "role": "symbol",
      "title": "VNPoint3D",
      "type": "topic",
      "url": "/documentation/vision/vnpoint3d"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPoint3D": {
      "abstract": [
        {
          "text": "A 3D point that includes an identifier to the point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPoint3D"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPoint3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPoint3D"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPoint3D",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpoint3d"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPoints3DObservation": {
      "abstract": [
        {
          "text": "An observation that provides the 3D points for a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPoints3DObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPoints3DObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPoints3DObservation"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPoints3DObservation",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpoints3dobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNStatefulRequest": {
      "abstract": [
        {
          "text": "An abstract request type that builds evidence of a condition over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNStatefulRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNStatefulRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNStatefulRequest"
        }
      ],
      "role": "symbol",
      "title": "VNStatefulRequest",
      "type": "topic",
      "url": "/documentation/vision/vnstatefulrequest"
    },
    "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-3d-with-vision": {
      "abstract": [
        {
          "text": "Render skeletons of 3D body pose points in a scene overlaying the input image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-3d-with-vision",
      "kind": "article",
      "role": "sampleCode",
      "title": "Detecting human body poses in 3D with Vision",
      "type": "topic",
      "url": "/documentation/vision/detecting-human-body-poses-in-3d-with-vision"
    },
    "doc://com.apple.vision/documentation/Vision/identifying-3d-human-body-poses-in-images": {
      "abstract": [
        {
          "text": "Detect three-dimensional human body poses using the Vision framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/identifying-3d-human-body-poses-in-images",
      "kind": "article",
      "role": "article",
      "title": "Identifying 3D human body poses in images",
      "type": "topic",
      "url": "/documentation/vision/identifying-3d-human-body-poses-in-images"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNStatefulRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "3D-body-pose-detection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/identifying-3d-human-body-poses-in-images",
        "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-3d-with-vision",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPoints3DObservation",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyRecognizedPoint3D",
        "doc://com.apple.vision/documentation/Vision/VNPoint3D",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPoint3D",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/JointName",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/JointsGroupName"
      ],
      "title": "3D body pose detection"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-a-Request",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/init()",
        "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/init(completionHandler:)"
      ],
      "title": "Initializing a Request"
    },
    {
      "anchor": "Determining-Supported-Joints",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointsGroupNames",
        "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointNames"
      ],
      "title": "Determining Supported Joints"
    },
    {
      "anchor": "Accessing-the-Results",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/results"
      ],
      "title": "Accessing the Results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNDetectHumanBodyPose3DRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanBodyPose3DRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanBodyPose3DRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-a-Request",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/init()",
                "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/init(completionHandler:)"
              ],
              "title": "Initializing a Request"
            },
            {
              "anchor": "Determining-Supported-Joints",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointNamesAndReturnError:",
                "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/supportedJointsGroupNamesAndReturnError:"
              ],
              "title": "Determining Supported Joints"
            },
            {
              "anchor": "Accessing-the-Results",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequest/results"
              ],
              "title": "Accessing the Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNStatefulRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "3D-body-pose-detection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/identifying-3d-human-body-poses-in-images",
                "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-3d-with-vision",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPoints3DObservation",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyRecognizedPoint3D",
                "doc://com.apple.vision/documentation/Vision/VNPoint3D",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPoint3D",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/JointName",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/JointsGroupName"
              ],
              "title": "3D body pose detection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNDetectHumanBodyPose3DRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNStatefulRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNStatefulRequest",
                    "text": "VNStatefulRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1JointsGroupName/title",
          "value": "VNHumanBodyPose3DObservationJointsGroupName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1JointsGroupName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1JointsGroupName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequest~1init(completionHandler:)/title",
          "value": "initWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequest~1init(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequest/title",
          "value": "VNDetectHumanBodyPose3DRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanBodyPose3DRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanBodyPose3DRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/title",
          "value": "VNStatefulRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNStatefulRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNStatefulRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequest~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequest~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyRecognizedPoint3D/title",
          "value": "VNHumanBodyRecognizedPoint3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyRecognizedPoint3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyRecognizedPoint3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyRecognizedPoint3D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyRecognizedPoint3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVDepthData/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVDepthData"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPoints3DObservation/title",
          "value": "VNRecognizedPoints3DObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPoints3DObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPoints3DObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPoints3DObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPoints3DObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPoint3D/title",
          "value": "VNRecognizedPoint3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPoint3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPoint3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPoint3D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPoint3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequest~1results/title",
          "value": "results"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequest~1results/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNPoint3D/title",
          "value": "VNPoint3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNPoint3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNPoint3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNPoint3D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNPoint3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1JointName/title",
          "value": "VNHumanBodyPose3DObservationJointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1JointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1JointName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation/title",
          "value": "VNHumanBodyPose3DObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vndetecthumanbodypose3drequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vndetecthumanbodypose3drequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
