{
  "abstract": [
    {
      "text": "An object that generates directional change vectors for each pixel in the targeted image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNGenerateOpticalFlowRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNGenerateOpticalFlowRequest"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNGenerateOpticalFlowRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNGenerateOpticalFlowRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This request operates at a pixel level, so both images need to have the same dimensions to successfully perform the analysis. Setting a region of interest limits the region in which the analysis occurs. However, the system reports the resulting observation at full resolution.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Optical flow requests are resource-intensive, so create only one request at a time, and release it immediately after generating optical flows.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest": {
      "abstract": [
        {
          "text": "An object that generates directional change vectors for each pixel in the targeted image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequest"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequest",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum": {
      "abstract": [
        {
          "text": "The supported optical flow accuracy levels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComputationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComputationAccuracy"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequest.ComputationAccuracy",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest/computationaccuracy-swift.enum"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/computationAccuracy-swift.property": {
      "abstract": [
        {
          "text": "The accuracy level for computing optical flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "computationAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNGenerateOpticalFlowRequest",
          "text": "VNGenerateOpticalFlowRequest"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VNGenerateOpticalFlowRequestComputationAccuracy",
          "text": "ComputationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/computationAccuracy-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "computationAccuracy"
        }
      ],
      "role": "symbol",
      "title": "computationAccuracy",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest/computationaccuracy-swift.property"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/keepNetworkOutput": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to keep the raw pixel buffer coming from the machine learning network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keepNetworkOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/keepNetworkOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keepNetworkOutput"
        }
      ],
      "role": "symbol",
      "title": "keepNetworkOutput",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest/keepnetworkoutput"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/outputPixelFormat": {
      "abstract": [
        {
          "text": "The output buffer’s pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputPixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/outputPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "outputPixelFormat",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest/outputpixelformat"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/results": {
      "abstract": [
        {
          "text": "The results of the request to generate optical flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "results"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNPixelBufferObservation",
          "text": "VNPixelBufferObservation"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/results",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "results"
        }
      ],
      "role": "symbol",
      "title": "results",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest/results"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequestRevision1": {
      "abstract": [
        {
          "text": "A constant for specifying revision 1 of the optical flow generation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequestRevision2": {
      "abstract": [
        {
          "text": "A constant for specifying revision 2 of the optical flow generation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequestRevision2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequestRevision2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequestRevision2"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequestRevision2",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequestrevision2"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest": {
      "abstract": [
        {
          "text": "The abstract superclass for image analysis requests that operate on both the processed image and a secondary image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTargetedImageRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTargetedImageRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTargetedImageRequest",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest": {
      "abstract": [
        {
          "text": "An object that determines the direction change of vectors for each pixel from a previous to current image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackOpticalFlowRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackOpticalFlowRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackOpticalFlowRequest",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Optical-flow",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest"
      ],
      "title": "Optical flow"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-Request",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/computationAccuracy-swift.property",
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum",
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/outputPixelFormat",
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/keepNetworkOutput"
      ],
      "title": "Configuring the Request"
    },
    {
      "anchor": "Accessing-the-Results",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/results"
      ],
      "title": "Accessing the Results"
    },
    {
      "anchor": "Identifying-Request-Revisions",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequestRevision2",
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequestRevision1"
      ],
      "title": "Identifying Request Revisions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNGenerateOpticalFlowRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-Request",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/computationAccuracy-swift.property",
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum",
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/outputPixelFormat",
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/keepNetworkOutput"
              ],
              "title": "Configuring the Request"
            },
            {
              "anchor": "Accessing-the-Results",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/results"
              ],
              "title": "Accessing the Results"
            },
            {
              "anchor": "Identifying-Request-Revisions",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequestRevision2",
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequestRevision1"
              ],
              "title": "Identifying Request Revisions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Optical-flow",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest"
              ],
              "title": "Optical flow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNGenerateOpticalFlowRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNTargetedImageRequest",
                    "text": "VNTargetedImageRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest/title",
          "value": "VNTargetedImageRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTargetedImageRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTargetedImageRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1outputPixelFormat/title",
          "value": "outputPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1outputPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1computationAccuracy-swift.property/title",
          "value": "computationAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1computationAccuracy-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "computationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest/title",
          "value": "VNTrackOpticalFlowRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequestRevision1/title",
          "value": "VNGenerateOpticalFlowRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest/title",
          "value": "VNGenerateOpticalFlowRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1results/title",
          "value": "results"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1results/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum/title",
          "value": "VNGenerateOpticalFlowRequestComputationAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestComputationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestComputationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequestRevision2/title",
          "value": "VNGenerateOpticalFlowRequestRevision2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequestRevision2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestRevision2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1keepNetworkOutput/title",
          "value": "keepNetworkOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1keepNetworkOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keepNetworkOutput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vngenerateopticalflowrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vngenerateopticalflowrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
