{
  "abstract": [
    {
      "text": "An observation that provides the body points the analysis recognized.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNHumanBodyPoseObservation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNHumanBodyPoseObservation"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNHumanBodyPoseObservation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNHumanBodyPoseObservation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-images"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPoseRequest": {
      "abstract": [
        {
          "text": "A request that detects a human body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectHumanBodyPoseRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPoseRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectHumanBodyPoseRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectHumanBodyPoseRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodyposerequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanHandPoseRequest": {
      "abstract": [
        {
          "text": "A request that detects a human hand pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectHumanHandPoseRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanHandPoseRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectHumanHandPoseRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectHumanHandPoseRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanhandposerequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectedPoint": {
      "abstract": [
        {
          "text": "An object that represents a normalized point in an image, along with a confidence value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectedPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectedPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectedPoint"
        }
      ],
      "role": "symbol",
      "title": "VNDetectedPoint",
      "type": "topic",
      "url": "/documentation/vision/vndetectedpoint"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation": {
      "abstract": [
        {
          "text": "An observation that provides the body points the analysis recognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPoseObservation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointName": {
      "abstract": [
        {
          "text": "The supported joint names for the body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPoseObservation.JointName",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointname"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName": {
      "abstract": [
        {
          "text": "The supported joint group names for the body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointsGroupName"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPoseObservation.JointsGroupName",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointNames": {
      "abstract": [
        {
          "text": "The names of the available joints in the observation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableJointNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableJointNames"
        }
      ],
      "role": "symbol",
      "title": "availableJointNames",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/availablejointnames"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointsGroupNames": {
      "abstract": [
        {
          "text": "The available joint group names in the observation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableJointsGroupNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointsGroupNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableJointsGroupNames"
        }
      ],
      "role": "symbol",
      "title": "availableJointsGroupNames",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/availablejointsgroupnames"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoint(_:)": {
      "abstract": [
        {
          "text": "Retrieves the recognized point for a joint name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognizedPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNRecognizedPoint",
          "text": "VNRecognizedPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recognizedPointForJointName:error:"
        }
      ],
      "role": "symbol",
      "title": "recognizedPoint(_:)",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/recognizedpoint(_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoints(_:)": {
      "abstract": [
        {
          "text": "Retrieves the recognized points associated with the joint group name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognizedPoints"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNRecognizedPoint",
          "text": "VNRecognizedPoint"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoints(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recognizedPointsForJointsGroupName:error:"
        }
      ],
      "role": "symbol",
      "title": "recognizedPoints(_:)",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/recognizedpoints(_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation": {
      "abstract": [
        {
          "text": "An observation that provides the hand points the analysis recognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanHandPoseObservation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanHandPoseObservation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanhandposeobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNPoint": {
      "abstract": [
        {
          "text": "An immutable object that represents a single 2D point in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNPoint"
        }
      ],
      "role": "symbol",
      "title": "VNPoint",
      "type": "topic",
      "url": "/documentation/vision/vnpoint"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPoint": {
      "abstract": [
        {
          "text": "An object that represents a normalized point in an image, along with an identifier label and a confidence value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPoint"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPoint",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpoint"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey": {
      "abstract": [
        {
          "text": "The data type for all recognized-point group keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPointGroupKey",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey": {
      "abstract": [
        {
          "text": "The data type for all recognized point keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPointKey",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointsObservation": {
      "abstract": [
        {
          "text": "An observation that provides the points the analysis recognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointsObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointsObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointsObservation"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPointsObservation",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointsobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestRevisionProviding": {
      "abstract": [
        {
          "text": "A protocol for specifying the revision number of Vision algorithms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRequestRevisionProviding"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestRevisionProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestRevisionProviding"
        }
      ],
      "role": "symbol",
      "title": "VNRequestRevisionProviding",
      "type": "topic",
      "url": "/documentation/vision/vnrequestrevisionproviding"
    },
    "doc://com.apple.vision/documentation/Vision/detecting-hand-poses-with-vision": {
      "abstract": [
        {
          "text": "Create a virtual drawing app by using Vision’s capability to detect hand poses.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/detecting-hand-poses-with-vision",
      "kind": "article",
      "role": "sampleCode",
      "title": "Detecting Hand Poses with Vision",
      "type": "topic",
      "url": "/documentation/vision/detecting-hand-poses-with-vision"
    },
    "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-images": {
      "abstract": [
        {
          "text": "Add the capability to detect human body poses to your app using the Vision framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-images",
      "kind": "article",
      "role": "article",
      "title": "Detecting Human Body Poses in Images",
      "type": "topic",
      "url": "/documentation/vision/detecting-human-body-poses-in-images"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointsObservation"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.apple.vision/documentation/Vision/VNRequestRevisionProviding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Body-and-hand-pose-detection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-images",
        "doc://com.apple.vision/documentation/Vision/detecting-hand-poses-with-vision",
        "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPoseRequest",
        "doc://com.apple.vision/documentation/Vision/VNDetectHumanHandPoseRequest",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointsObservation",
        "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation",
        "doc://com.apple.vision/documentation/Vision/VNPoint",
        "doc://com.apple.vision/documentation/Vision/VNDetectedPoint",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPoint",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey"
      ],
      "title": "Body and hand pose detection"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Points",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointNames",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointName",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointsGroupNames",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoint(_:)",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoints(_:)"
      ],
      "title": "Accessing Points"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNHumanBodyPoseObservation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Points",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointNames",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointName",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointsGroupNames",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoint(_:)",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoints(_:)"
              ],
              "title": "Accessing Points"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointsObservation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Body-and-hand-pose-detection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-images",
                "doc://com.apple.vision/documentation/Vision/detecting-hand-poses-with-vision",
                "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPoseRequest",
                "doc://com.apple.vision/documentation/Vision/VNDetectHumanHandPoseRequest",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointsObservation",
                "doc://com.apple.vision/documentation/Vision/VNHumanHandPoseObservation",
                "doc://com.apple.vision/documentation/Vision/VNPoint",
                "doc://com.apple.vision/documentation/Vision/VNDetectedPoint",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPoint",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey"
              ],
              "title": "Body and hand pose detection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNHumanBodyPoseObservation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointsObservation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNRecognizedPointsObservation",
                    "text": "VNRecognizedPointsObservation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNPoint/title",
          "value": "VNPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1availableJointsGroupNames/title",
          "value": "availableJointsGroupNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1availableJointsGroupNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableJointsGroupNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPoint/title",
          "value": "VNRecognizedPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedPoint/title",
          "value": "VNDetectedPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectedPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectedPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectedPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation/title",
          "value": "VNHumanBodyPoseObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointName/title",
          "value": "VNHumanBodyPoseObservationJointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation/title",
          "value": "VNHumanHandPoseObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanHandPoseObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanHandPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/title",
          "value": "VNRecognizedPointKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1availableJointNames/title",
          "value": "availableJointNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1availableJointNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableJointNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPoseRequest/title",
          "value": "VNDetectHumanBodyPoseRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPoseRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanBodyPoseRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPoseRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanBodyPoseRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/title",
          "value": "VNRecognizedPointGroupKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointGroupKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointGroupKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanHandPoseRequest/title",
          "value": "VNDetectHumanHandPoseRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanHandPoseRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanHandPoseRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanHandPoseRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanHandPoseRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName/title",
          "value": "VNHumanBodyPoseObservationJointsGroupName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointsObservation/title",
          "value": "VNRecognizedPointsObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointsObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointsObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointsObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointsObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionProviding/title",
          "value": "VNRequestRevisionProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestRevisionProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestRevisionProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1recognizedPoint(_:)/title",
          "value": "recognizedPointForJointName:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1recognizedPoint(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recognizedPointForJointName:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1recognizedPoints(_:)/title",
          "value": "recognizedPointsForJointsGroupName:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1recognizedPoints(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recognizedPointsForJointsGroupName:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnhumanbodyposeobservation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnhumanbodyposeobservation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
