{
  "abstract": [
    {
      "text": "Options that define how Vision crops and scales an input-image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VNImageCropAndScaleOption",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNImageCropAndScaleOption"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNImageCropAndScaleOption"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VNImageCropAndScaleOption"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOption"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Scaling an image ensures that it fits within the algorithm’s input image dimensions, which may require a change in aspect ratio. The figure below shows how each crop-and-scale option transforms the input image:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3258357",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNCoreMLRequest/imageCropAndScaleOption": {
      "abstract": [
        {
          "text": "An optional setting that tells the Vision algorithm how to scale an input image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageCropAndScaleOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VNImageCropAndScaleOption",
          "text": "VNImageCropAndScaleOption"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNCoreMLRequest/imageCropAndScaleOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageCropAndScaleOption"
        }
      ],
      "role": "symbol",
      "title": "imageCropAndScaleOption",
      "type": "topic",
      "url": "/documentation/vision/vncoremlrequest/imagecropandscaleoption"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption": {
      "abstract": [
        {
          "text": "Options that define how Vision crops and scales an input-image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOption"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOption"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/centerCrop": {
      "abstract": [
        {
          "text": "An option that scales the image to fit its shorter side within the input dimensions, while preserving its aspect ratio, and center-crops the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerCrop"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/centerCrop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionCenterCrop"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.centerCrop",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/centercrop"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/init(rawvalue:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill": {
      "abstract": [
        {
          "text": "An option that scales the image to fill the input dimensions, resizing it if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFill"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionScaleFill"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.scaleFill",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/scalefill"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFillRotate90CCW": {
      "abstract": [
        {
          "text": "An option that rotates the image 90 degrees counterclockwise and then scales it to fill the input dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFillRotate90CCW"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFillRotate90CCW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionScaleFillRotate90CCW"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.scaleFillRotate90CCW",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/scalefillrotate90ccw"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFit": {
      "abstract": [
        {
          "text": "An option that scales the image to fit its longer side within the input dimensions, while preserving its aspect ratio, and center-crops the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFit"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionScaleFit"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.scaleFit",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/scalefit"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFitRotate90CCW": {
      "abstract": [
        {
          "text": "An option that rotates the image 90 degrees counterclockwise and then scales it, while preserving its aspect ratio, to fit on the long side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFitRotate90CCW"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFitRotate90CCW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionScaleFitRotate90CCW"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.scaleFitRotate90CCW",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/scalefitrotate90ccw"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "media-3258357": {
      "alt": "A series of six photos that show the effects of applying a center crop, scale fit, scale fill, scale fit rotate 90 degrees counterclockwise, and scale fill rotate 90 degrees counterclockwise option to the original input image.",
      "identifier": "media-3258357",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fec0f3784a37ea1c18aebea29f3df41f/media-3258357@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/864740cf6ced2aa53341c6e18f479fcf/media-3258357~dark@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Image-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNCoreMLRequest/imageCropAndScaleOption"
      ],
      "title": "Configuring Image Options"
    }
  ],
  "topicSections": [
    {
      "anchor": "Crop-and-Scale-Options",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/centerCrop",
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFit",
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill",
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFitRotate90CCW",
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFillRotate90CCW"
      ],
      "title": "Crop and Scale Options"
    },
    {
      "anchor": "Creating-a-Scale-Option",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/init(rawValue:)"
      ],
      "title": "Creating a Scale Option"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNImageCropAndScaleOption"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Crop-and-Scale-Options",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/centerCrop",
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFit",
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill",
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFitRotate90CCW",
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFillRotate90CCW"
              ],
              "title": "Crop and Scale Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Image-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNCoreMLRequest/imageCropAndScaleOption"
              ],
              "title": "Configuring Image Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNImageCropAndScaleOption"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1centerCrop/title",
          "value": "VNImageCropAndScaleOptionCenterCrop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1centerCrop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionCenterCrop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFill/title",
          "value": "VNImageCropAndScaleOptionScaleFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionScaleFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFillRotate90CCW/title",
          "value": "VNImageCropAndScaleOptionScaleFillRotate90CCW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFillRotate90CCW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionScaleFillRotate90CCW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption/title",
          "value": "VNImageCropAndScaleOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFit/title",
          "value": "VNImageCropAndScaleOptionScaleFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionScaleFit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFitRotate90CCW/title",
          "value": "VNImageCropAndScaleOptionScaleFitRotate90CCW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFitRotate90CCW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionScaleFitRotate90CCW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLRequest~1imageCropAndScaleOption/title",
          "value": "imageCropAndScaleOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCoreMLRequest~1imageCropAndScaleOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageCropAndScaleOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnimagecropandscaleoption"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnimagecropandscaleoption"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
