{
  "abstract": [
    {
      "text": "Projects a point from a region of interest within the normalized coordinates into image coordinates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNImagePointForNormalizedPointUsingRegionOfInterest(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@VNImagePointForNormalizedPointUsingRegionOfInterest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNImagePointForNormalizedPointUsingRegionOfInterest"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGPoint",
        "text": "CGPoint"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGRect",
        "text": "CGRect"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGPoint",
        "text": "CGPoint"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNImagePointForNormalizedPointUsingRegionOfInterest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "VNImagePointForNormalizedPointUsingRegionOfInterest(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNImagePointForNormalizedPointUsingRegionOfInterest"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "normalizedPoint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGPoint",
              "text": "CGPoint"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "imageWidth"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "imageHeight"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "roi"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGRect",
              "text": "CGRect"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGPoint",
              "text": "CGPoint"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The input point in normalized coordinates.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "normalizedPoint"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The width of the image.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "imageWidth"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The height of the image.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "imageHeight"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The region of interest within the normalized-coordinate space.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "roi"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A point in the image-coordinate space.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNImagePointForFaceLandmarkPoint(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the image coordinates of a specified face landmark point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImagePointForFaceLandmarkPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImagePointForFaceLandmarkPoint(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImagePointForFaceLandmarkPoint"
        }
      ],
      "role": "symbol",
      "title": "VNImagePointForFaceLandmarkPoint(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vision/vnimagepointforfacelandmarkpoint(_:_:_:_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNImagePointForNormalizedPoint(_:_:_:)": {
      "abstract": [
        {
          "text": "Projects a point in normalized coordinates into image coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImagePointForNormalizedPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImagePointForNormalizedPoint(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImagePointForNormalizedPoint"
        }
      ],
      "role": "symbol",
      "title": "VNImagePointForNormalizedPoint(_:_:_:)",
      "type": "topic",
      "url": "/documentation/vision/vnimagepointfornormalizedpoint(_:_:_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNImagePointForNormalizedPointUsingRegionOfInterest(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Projects a point from a region of interest within the normalized coordinates into image coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImagePointForNormalizedPointUsingRegionOfInterest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImagePointForNormalizedPointUsingRegionOfInterest(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImagePointForNormalizedPointUsingRegionOfInterest"
        }
      ],
      "role": "symbol",
      "title": "VNImagePointForNormalizedPointUsingRegionOfInterest(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vision/vnimagepointfornormalizedpointusingregionofinterest(_:_:_:_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageRectForNormalizedRect(_:_:_:)": {
      "abstract": [
        {
          "text": "Projects a rectangle from normalized coordinates into image coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageRectForNormalizedRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageRectForNormalizedRect(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageRectForNormalizedRect"
        }
      ],
      "role": "symbol",
      "title": "VNImageRectForNormalizedRect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/vision/vnimagerectfornormalizedrect(_:_:_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageRectForNormalizedRectUsingRegionOfInterest(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Projects a rectangle from a region of interest within the normalized coordinates into image coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageRectForNormalizedRectUsingRegionOfInterest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageRectForNormalizedRectUsingRegionOfInterest(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageRectForNormalizedRectUsingRegionOfInterest"
        }
      ],
      "role": "symbol",
      "title": "VNImageRectForNormalizedRectUsingRegionOfInterest(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vision/vnimagerectfornormalizedrectusingregionofinterest(_:_:_:_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNNormalizedFaceBoundingBoxPointForLandmarkPoint(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the coordinates of a specified face landmark point, in bounding box coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNNormalizedFaceBoundingBoxPointForLandmarkPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNNormalizedFaceBoundingBoxPointForLandmarkPoint(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNNormalizedFaceBoundingBoxPointForLandmarkPoint"
        }
      ],
      "role": "symbol",
      "title": "VNNormalizedFaceBoundingBoxPointForLandmarkPoint(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vision/vnnormalizedfaceboundingboxpointforlandmarkpoint(_:_:_:_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNNormalizedIdentityRect": {
      "abstract": [
        {
          "text": "A normalized identity rectangle with an origin of zero and unit length and width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNNormalizedIdentityRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNNormalizedIdentityRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNNormalizedIdentityRect"
        }
      ],
      "role": "symbol",
      "title": "VNNormalizedIdentityRect",
      "type": "topic",
      "url": "/documentation/vision/vnnormalizedidentityrect"
    },
    "doc://com.apple.vision/documentation/Vision/VNNormalizedPointForImagePoint(_:_:_:)": {
      "abstract": [
        {
          "text": "Projects a point from image coordinates into normalized coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNNormalizedPointForImagePoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNNormalizedPointForImagePoint(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNNormalizedPointForImagePoint"
        }
      ],
      "role": "symbol",
      "title": "VNNormalizedPointForImagePoint(_:_:_:)",
      "type": "topic",
      "url": "/documentation/vision/vnnormalizedpointforimagepoint(_:_:_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNNormalizedPointForImagePointUsingRegionOfInterest(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Projects a point from a region of interest within the image coordinates into normalized coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNNormalizedPointForImagePointUsingRegionOfInterest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNNormalizedPointForImagePointUsingRegionOfInterest(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNNormalizedPointForImagePointUsingRegionOfInterest"
        }
      ],
      "role": "symbol",
      "title": "VNNormalizedPointForImagePointUsingRegionOfInterest(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vision/vnnormalizedpointforimagepointusingregionofinterest(_:_:_:_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNNormalizedRectForImageRect(_:_:_:)": {
      "abstract": [
        {
          "text": "Projects a rectangle from image coordinates into normalized coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNNormalizedRectForImageRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNNormalizedRectForImageRect(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNNormalizedRectForImageRect"
        }
      ],
      "role": "symbol",
      "title": "VNNormalizedRectForImageRect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/vision/vnnormalizedrectforimagerect(_:_:_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNNormalizedRectForImageRectUsingRegionOfInterest(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Projects a rectangle from a region of interest within the image coordinates space into normalized coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNNormalizedRectForImageRectUsingRegionOfInterest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNNormalizedRectForImageRectUsingRegionOfInterest(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNNormalizedRectForImageRectUsingRegionOfInterest"
        }
      ],
      "role": "symbol",
      "title": "VNNormalizedRectForImageRectUsingRegionOfInterest(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vision/vnnormalizedrectforimagerectusingregionofinterest(_:_:_:_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNNormalizedRectIsIdentityRect(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the rectangle has an origin of zero and unit length and width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNNormalizedRectIsIdentityRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNNormalizedRectIsIdentityRect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNNormalizedRectIsIdentityRect"
        }
      ],
      "role": "symbol",
      "title": "VNNormalizedRectIsIdentityRect(_:)",
      "type": "topic",
      "url": "/documentation/vision/vnnormalizedrectisidentityrect(_:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGPoint": {
      "abstract": [
        {
          "text": "A structure that contains a point in a two-dimensional coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGPoint",
      "type": "topic",
      "url": "/documentation/corefoundation/cgpoint"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGRect": {
      "abstract": [
        {
          "text": "A structure that contains the location and dimensions of a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGRect",
      "type": "topic",
      "url": "/documentation/corefoundation/cgrect"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Coordinate-conversion",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNImagePointForNormalizedPoint(_:_:_:)",
        "doc://com.apple.vision/documentation/Vision/VNNormalizedPointForImagePoint(_:_:_:)",
        "doc://com.apple.vision/documentation/Vision/VNNormalizedPointForImagePointUsingRegionOfInterest(_:_:_:_:)",
        "doc://com.apple.vision/documentation/Vision/VNImageRectForNormalizedRect(_:_:_:)",
        "doc://com.apple.vision/documentation/Vision/VNNormalizedRectForImageRect(_:_:_:)",
        "doc://com.apple.vision/documentation/Vision/VNImageRectForNormalizedRectUsingRegionOfInterest(_:_:_:_:)",
        "doc://com.apple.vision/documentation/Vision/VNNormalizedRectForImageRectUsingRegionOfInterest(_:_:_:_:)",
        "doc://com.apple.vision/documentation/Vision/VNNormalizedIdentityRect",
        "doc://com.apple.vision/documentation/Vision/VNNormalizedRectIsIdentityRect(_:)",
        "doc://com.apple.vision/documentation/Vision/VNImagePointForFaceLandmarkPoint(_:_:_:_:)",
        "doc://com.apple.vision/documentation/Vision/VNNormalizedFaceBoundingBoxPointForLandmarkPoint(_:_:_:_:)"
      ],
      "title": "Coordinate conversion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNImagePointForNormalizedPointUsingRegionOfInterest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImagePointForNormalizedPointUsingRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Coordinate-conversion",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNImagePointForNormalizedPoint(_:_:_:)",
                "doc://com.apple.vision/documentation/Vision/VNNormalizedPointForImagePoint(_:_:_:)",
                "doc://com.apple.vision/documentation/Vision/VNNormalizedPointForImagePointUsingRegionOfInterest(_:_:_:_:)",
                "doc://com.apple.vision/documentation/Vision/VNImageRectForNormalizedRect(_:_:_:)",
                "doc://com.apple.vision/documentation/Vision/VNNormalizedRectForImageRect(_:_:_:)",
                "doc://com.apple.vision/documentation/Vision/VNImageRectForNormalizedRectUsingRegionOfInterest(_:_:_:_:)",
                "doc://com.apple.vision/documentation/Vision/VNNormalizedRectForImageRectUsingRegionOfInterest(_:_:_:_:)",
                "doc://com.apple.vision/documentation/Vision/VNNormalizedIdentityRect",
                "doc://com.apple.vision/documentation/Vision/VNNormalizedRectIsIdentityRect(_:)",
                "doc://com.apple.vision/documentation/Vision/VNImagePointForFaceLandmarkPoint(_:_:_:_:)",
                "doc://com.apple.vision/documentation/Vision/VNNormalizedFaceBoundingBoxPointForLandmarkPoint(_:_:_:_:)"
              ],
              "title": "Coordinate conversion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGPoint",
                    "text": "CGPoint"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNImagePointForNormalizedPointUsingRegionOfInterest"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGPoint",
                    "text": "CGPoint"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "normalizedPoint"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@size_t",
                    "text": "size_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "imageWidth"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@size_t",
                    "text": "size_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "imageHeight"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGRect",
                    "text": "CGRect"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "roi"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The input point in normalized coordinates.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "normalizedPoint"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The width of the image.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "imageWidth"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The height of the image.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "imageHeight"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The region of interest within the normalized-coordinate space.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "roi"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A point in the image-coordinate space.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImagePointForNormalizedPoint(_:_:_:)/title",
          "value": "VNImagePointForNormalizedPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImagePointForNormalizedPoint(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImagePointForNormalizedPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImagePointForNormalizedPointUsingRegionOfInterest(_:_:_:_:)/title",
          "value": "VNImagePointForNormalizedPointUsingRegionOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImagePointForNormalizedPointUsingRegionOfInterest(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImagePointForNormalizedPointUsingRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedPointForImagePointUsingRegionOfInterest(_:_:_:_:)/title",
          "value": "VNNormalizedPointForImagePointUsingRegionOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedPointForImagePointUsingRegionOfInterest(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNNormalizedPointForImagePointUsingRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedRectForImageRectUsingRegionOfInterest(_:_:_:_:)/title",
          "value": "VNNormalizedRectForImageRectUsingRegionOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedRectForImageRectUsingRegionOfInterest(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNNormalizedRectForImageRectUsingRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageRectForNormalizedRectUsingRegionOfInterest(_:_:_:_:)/title",
          "value": "VNImageRectForNormalizedRectUsingRegionOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageRectForNormalizedRectUsingRegionOfInterest(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageRectForNormalizedRectUsingRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedFaceBoundingBoxPointForLandmarkPoint(_:_:_:_:)/title",
          "value": "VNNormalizedFaceBoundingBoxPointForLandmarkPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedFaceBoundingBoxPointForLandmarkPoint(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNNormalizedFaceBoundingBoxPointForLandmarkPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedIdentityRect/title",
          "value": "VNNormalizedIdentityRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedIdentityRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNNormalizedIdentityRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedPointForImagePoint(_:_:_:)/title",
          "value": "VNNormalizedPointForImagePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedPointForImagePoint(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNNormalizedPointForImagePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageRectForNormalizedRect(_:_:_:)/title",
          "value": "VNImageRectForNormalizedRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageRectForNormalizedRect(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageRectForNormalizedRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedRectForImageRect(_:_:_:)/title",
          "value": "VNNormalizedRectForImageRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedRectForImageRect(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNNormalizedRectForImageRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedRectIsIdentityRect(_:)/title",
          "value": "VNNormalizedRectIsIdentityRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNNormalizedRectIsIdentityRect(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNNormalizedRectIsIdentityRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImagePointForFaceLandmarkPoint(_:_:_:_:)/title",
          "value": "VNImagePointForFaceLandmarkPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImagePointForFaceLandmarkPoint(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImagePointForFaceLandmarkPoint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnimagepointfornormalizedpointusingregionofinterest(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnimagepointfornormalizedpointusingregionofinterest(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
