{
  "abstract": [
    {
      "text": "A constant for specifying an unspecified request revision.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNRequestRevisionUnspecified"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@VNRequestRevisionUnspecified",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNRequestRevisionUnspecified"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNRequestRevisionUnspecified"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "VNRequestRevisionUnspecified"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNRequestRevisionUnspecified"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNCalculateImageAestheticsScoresRequestRevision1": {
      "abstract": [
        {
          "text": "A value that indicates the first revision for an aesthetics scores request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNCalculateImageAestheticsScoresRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNCalculateImageAestheticsScoresRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNCalculateImageAestheticsScoresRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNCalculateImageAestheticsScoresRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vncalculateimageaestheticsscoresrequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNClassifyImageRequestRevision1": {
      "abstract": [
        {
          "text": "A constant for specifying the first revision of the image-classification request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNClassifyImageRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNClassifyImageRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNClassifyImageRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNClassifyImageRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vnclassifyimagerequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNClassifyImageRequestRevision2": {
      "abstract": [
        {
          "text": "A value that indicates the second revision for an image-classification request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNClassifyImageRequestRevision2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNClassifyImageRequestRevision2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNClassifyImageRequestRevision2"
        }
      ],
      "role": "symbol",
      "title": "VNClassifyImageRequestRevision2",
      "type": "topic",
      "url": "/documentation/vision/vnclassifyimagerequestrevision2"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectAnimalBodyPoseRequestRevision1": {
      "abstract": [
        {
          "text": "A value that indicates the first revision for an animal body-pose request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectAnimalBodyPoseRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectAnimalBodyPoseRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectAnimalBodyPoseRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNDetectAnimalBodyPoseRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vndetectanimalbodyposerequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequestRevision4": {
      "abstract": [
        {
          "text": "A value that indicates the fourth revision for a barcode request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectBarcodesRequestRevision4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequestRevision4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectBarcodesRequestRevision4"
        }
      ],
      "role": "symbol",
      "title": "VNDetectBarcodesRequestRevision4",
      "type": "topic",
      "url": "/documentation/vision/vndetectbarcodesrequestrevision4"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision3": {
      "abstract": [
        {
          "text": "A value that indicates the third revision for a face capture-quality request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectFaceCaptureQualityRequestRevision3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectFaceCaptureQualityRequestRevision3"
        }
      ],
      "role": "symbol",
      "title": "VNDetectFaceCaptureQualityRequestRevision3",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacecapturequalityrequestrevision3"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequestRevision1": {
      "abstract": [
        {
          "text": "A value that indicates the first revision for a human 3D body pose request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectHumanBodyPose3DRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectHumanBodyPose3DRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNDetectHumanBodyPose3DRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vndetecthumanbodypose3drequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateAttentionBasedSaliencyImageRequestRevision2": {
      "abstract": [
        {
          "text": "A value that indicates the second revision for an attention-saliency image request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGenerateAttentionBasedSaliencyImageRequestRevision2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateAttentionBasedSaliencyImageRequestRevision2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateAttentionBasedSaliencyImageRequestRevision2"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateAttentionBasedSaliencyImageRequestRevision2",
      "type": "topic",
      "url": "/documentation/vision/vngenerateattentionbasedsaliencyimagerequestrevision2"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequestRevision1": {
      "abstract": [
        {
          "text": "A constant for specifying the first revision of the feature-print request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGenerateImageFeaturePrintRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateImageFeaturePrintRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateImageFeaturePrintRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vngenerateimagefeatureprintrequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequestRevision2": {
      "abstract": [
        {
          "text": "A value that indicates the second revision for a feature-print request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGenerateImageFeaturePrintRequestRevision2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequestRevision2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateImageFeaturePrintRequestRevision2"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateImageFeaturePrintRequestRevision2",
      "type": "topic",
      "url": "/documentation/vision/vngenerateimagefeatureprintrequestrevision2"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateObjectnessBasedSaliencyImageRequestRevision2": {
      "abstract": [
        {
          "text": "A value that indicates the second revision for an image-classification request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGenerateObjectnessBasedSaliencyImageRequestRevision2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateObjectnessBasedSaliencyImageRequestRevision2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateObjectnessBasedSaliencyImageRequestRevision2"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateObjectnessBasedSaliencyImageRequestRevision2",
      "type": "topic",
      "url": "/documentation/vision/vngenerateobjectnessbasedsaliencyimagerequestrevision2"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestRevisionUnspecified": {
      "abstract": [
        {
          "text": "A constant for specifying an unspecified request revision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRequestRevisionUnspecified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestRevisionUnspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestRevisionUnspecified"
        }
      ],
      "role": "symbol",
      "title": "VNRequestRevisionUnspecified",
      "type": "topic",
      "url": "/documentation/vision/vnrequestrevisionunspecified"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequestRevision1": {
      "abstract": [
        {
          "text": "A value that indicates the first revision for a homographic image-registration request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackHomographicImageRegistrationRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackHomographicImageRegistrationRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNTrackHomographicImageRegistrationRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vntrackhomographicimageregistrationrequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequestRevision1": {
      "abstract": [
        {
          "text": "A value that indicates the first revision for an optial-flow request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackOpticalFlowRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackOpticalFlowRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNTrackOpticalFlowRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequestRevision1": {
      "abstract": [
        {
          "text": "A value that indicates the first revision for a translational image-registration request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackTranslationalImageRegistrationRequestRevision1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequestRevision1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackTranslationalImageRegistrationRequestRevision1"
        }
      ],
      "role": "symbol",
      "title": "VNTrackTranslationalImageRegistrationRequestRevision1",
      "type": "topic",
      "url": "/documentation/vision/vntracktranslationalimageregistrationrequestrevision1"
    },
    "doc://com.apple.vision/documentation/Vision/VNVisionVersionNumber": {
      "abstract": [
        {
          "text": "The current version number of the Vision framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNVisionVersionNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNVisionVersionNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNVisionVersionNumber"
        }
      ],
      "role": "symbol",
      "title": "VNVisionVersionNumber",
      "type": "topic",
      "url": "/documentation/vision/vnvisionversionnumber"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Version-and-revision-numbers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNVisionVersionNumber",
        "doc://com.apple.vision/documentation/Vision/VNDetectAnimalBodyPoseRequestRevision1",
        "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequestRevision1",
        "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequestRevision1",
        "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequestRevision1",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequestRevision1",
        "doc://com.apple.vision/documentation/Vision/VNClassifyImageRequestRevision1",
        "doc://com.apple.vision/documentation/Vision/VNClassifyImageRequestRevision2",
        "doc://com.apple.vision/documentation/Vision/VNGenerateObjectnessBasedSaliencyImageRequestRevision2",
        "doc://com.apple.vision/documentation/Vision/VNGenerateAttentionBasedSaliencyImageRequestRevision2",
        "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequestRevision1",
        "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequestRevision2",
        "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision3",
        "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequestRevision4",
        "doc://com.apple.vision/documentation/Vision/VNCalculateImageAestheticsScoresRequestRevision1"
      ],
      "title": "Version and revision numbers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNRequestRevisionUnspecified"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestRevisionUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Version-and-revision-numbers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNVisionVersionNumber",
                "doc://com.apple.vision/documentation/Vision/VNDetectAnimalBodyPoseRequestRevision1",
                "doc://com.apple.vision/documentation/Vision/VNDetectHumanBodyPose3DRequestRevision1",
                "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequestRevision1",
                "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequestRevision1",
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequestRevision1",
                "doc://com.apple.vision/documentation/Vision/VNClassifyImageRequestRevision1",
                "doc://com.apple.vision/documentation/Vision/VNClassifyImageRequestRevision2",
                "doc://com.apple.vision/documentation/Vision/VNGenerateObjectnessBasedSaliencyImageRequestRevision2",
                "doc://com.apple.vision/documentation/Vision/VNGenerateAttentionBasedSaliencyImageRequestRevision2",
                "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequestRevision1",
                "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequestRevision2",
                "doc://com.apple.vision/documentation/Vision/VNDetectFaceCaptureQualityRequestRevision3",
                "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequestRevision4",
                "doc://com.apple.vision/documentation/Vision/VNCalculateImageAestheticsScoresRequestRevision1"
              ],
              "title": "Version and revision numbers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNRequestRevisionUnspecified"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackHomographicImageRegistrationRequestRevision1/title",
          "value": "VNTrackHomographicImageRegistrationRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackHomographicImageRegistrationRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackHomographicImageRegistrationRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateImageFeaturePrintRequestRevision1/title",
          "value": "VNGenerateImageFeaturePrintRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateImageFeaturePrintRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateImageFeaturePrintRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequestRevision1/title",
          "value": "VNTrackTranslationalImageRegistrationRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackTranslationalImageRegistrationRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNVisionVersionNumber/title",
          "value": "VNVisionVersionNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNVisionVersionNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNVisionVersionNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequestRevision4/title",
          "value": "VNDetectBarcodesRequestRevision4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequestRevision4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectBarcodesRequestRevision4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateAttentionBasedSaliencyImageRequestRevision2/title",
          "value": "VNGenerateAttentionBasedSaliencyImageRequestRevision2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateAttentionBasedSaliencyImageRequestRevision2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateAttentionBasedSaliencyImageRequestRevision2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequestRevision1/title",
          "value": "VNTrackOpticalFlowRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNClassifyImageRequestRevision1/title",
          "value": "VNClassifyImageRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNClassifyImageRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNClassifyImageRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCalculateImageAestheticsScoresRequestRevision1/title",
          "value": "VNCalculateImageAestheticsScoresRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNCalculateImageAestheticsScoresRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNCalculateImageAestheticsScoresRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectAnimalBodyPoseRequestRevision1/title",
          "value": "VNDetectAnimalBodyPoseRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectAnimalBodyPoseRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectAnimalBodyPoseRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequestRevision3/title",
          "value": "VNDetectFaceCaptureQualityRequestRevision3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceCaptureQualityRequestRevision3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceCaptureQualityRequestRevision3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNClassifyImageRequestRevision2/title",
          "value": "VNClassifyImageRequestRevision2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNClassifyImageRequestRevision2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNClassifyImageRequestRevision2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateObjectnessBasedSaliencyImageRequestRevision2/title",
          "value": "VNGenerateObjectnessBasedSaliencyImageRequestRevision2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateObjectnessBasedSaliencyImageRequestRevision2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateObjectnessBasedSaliencyImageRequestRevision2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateImageFeaturePrintRequestRevision2/title",
          "value": "VNGenerateImageFeaturePrintRequestRevision2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateImageFeaturePrintRequestRevision2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateImageFeaturePrintRequestRevision2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequestRevision1/title",
          "value": "VNDetectHumanBodyPose3DRequestRevision1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectHumanBodyPose3DRequestRevision1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectHumanBodyPose3DRequestRevision1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionUnspecified/title",
          "value": "VNRequestRevisionUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestRevisionUnspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestRevisionUnspecified"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnrequestrevisionunspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnrequestrevisionunspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
