{
  "abstract": [
    {
      "text": "An enumeration of face landmarks in a constellation object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VNRequestFaceLandmarksConstellation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNRequestFaceLandmarksConstellation"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNRequestFaceLandmarksConstellation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VNRequestFaceLandmarksConstellation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest/constellation": {
      "abstract": [
        {
          "text": "A variable that describes how a face landmarks request orders or enumerates the resulting features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constellation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VNRequestFaceLandmarksConstellation",
          "text": "VNRequestFaceLandmarksConstellation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest/constellation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constellation"
        }
      ],
      "role": "symbol",
      "title": "constellation",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacelandmarksrequest/constellation"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation": {
      "abstract": [
        {
          "text": "An enumeration of face landmarks in a constellation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation65Points": {
      "abstract": [
        {
          "text": "A constellation with 65 points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constellation65Points"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation65Points",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation65Points"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation.constellation65Points",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation/constellation65points"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points": {
      "abstract": [
        {
          "text": "A constellation with 76 points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constellation76Points"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation76Points"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation.constellation76Points",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation/constellation76points"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellationNotDefined": {
      "abstract": [
        {
          "text": "An undefined constellation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constellationNotDefined"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellationNotDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellationNotDefined"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation.constellationNotDefined",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation/constellationnotdefined"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Locating-Face-Landmarks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest/constellation"
      ],
      "title": "Locating Face Landmarks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Types-of-Constellations",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellationNotDefined",
        "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation65Points",
        "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points"
      ],
      "title": "Types of Constellations"
    },
    {
      "anchor": "Creating-a-Constellation",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/init(rawValue:)"
      ],
      "title": "Creating a Constellation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNRequestFaceLandmarksConstellation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Types-of-Constellations",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellationNotDefined",
                "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation65Points",
                "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points"
              ],
              "title": "Types of Constellations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Locating-Face-Landmarks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest/constellation"
              ],
              "title": "Locating Face Landmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNRequestFaceLandmarksConstellation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation/title",
          "value": "VNRequestFaceLandmarksConstellation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest~1constellation/title",
          "value": "constellation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest~1constellation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "constellation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellation65Points/title",
          "value": "VNRequestFaceLandmarksConstellation65Points"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellation65Points/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation65Points"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellationNotDefined/title",
          "value": "VNRequestFaceLandmarksConstellationNotDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellationNotDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellationNotDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellation76Points/title",
          "value": "VNRequestFaceLandmarksConstellation76Points"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellation76Points/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation76Points"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnrequestfacelandmarksconstellation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnrequestfacelandmarksconstellation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
