{
  "abstract": [
    {
      "text": "The abstract superclass for image analysis requests that operate on both the processed image and a secondary image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNTargetedImageRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNTargetedImageRequest"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNTargetedImageRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNTargetedImageRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNTargetedImageRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Other Vision request handlers that operate on both the processed image and a secondary image inherit from this abstract base class. Instantiate one of its subclasses to perform image analysis, and pass in auxiliary image data by filling in the ",
              "type": "text"
            },
            {
              "code": "options",
              "type": "codeVoice"
            },
            {
              "text": " dictionary at initialization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest": {
      "abstract": [
        {
          "text": "An object that generates directional change vectors for each pixel in the targeted image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequest"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequest",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNHomographicImageRegistrationRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that determines the perspective warp matrix necessary to align the content of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHomographicImageRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHomographicImageRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHomographicImageRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNHomographicImageRegistrationRequest",
      "type": "topic",
      "url": "/documentation/vision/vnhomographicimageregistrationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageAlignmentObservation": {
      "abstract": [
        {
          "text": "The abstract superclass for image-analysis results that describe the relative alignment of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageAlignmentObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageAlignmentObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageAlignmentObservation"
        }
      ],
      "role": "symbol",
      "title": "VNImageAlignmentObservation",
      "type": "topic",
      "url": "/documentation/vision/vnimagealignmentobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest": {
      "abstract": [
        {
          "text": "The abstract superclass for image-analysis requests that focus on a specific part of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageBasedRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageBasedRequest"
        }
      ],
      "role": "symbol",
      "title": "VNImageBasedRequest",
      "type": "topic",
      "url": "/documentation/vision/vnimagebasedrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageHomographicAlignmentObservation": {
      "abstract": [
        {
          "text": "An object that represents a perspective warp transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageHomographicAlignmentObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageHomographicAlignmentObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageHomographicAlignmentObservation"
        }
      ],
      "role": "symbol",
      "title": "VNImageHomographicAlignmentObservation",
      "type": "topic",
      "url": "/documentation/vision/vnimagehomographicalignmentobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageRegistrationRequest": {
      "abstract": [
        {
          "text": "The abstract superclass for image-analysis requests that align images according to their content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNImageRegistrationRequest",
      "type": "topic",
      "url": "/documentation/vision/vnimageregistrationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageTranslationAlignmentObservation": {
      "abstract": [
        {
          "text": "Affine transform information that an image-alignment request produces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageTranslationAlignmentObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageTranslationAlignmentObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageTranslationAlignmentObservation"
        }
      ],
      "role": "symbol",
      "title": "VNImageTranslationAlignmentObservation",
      "type": "topic",
      "url": "/documentation/vision/vnimagetranslationalignmentobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest": {
      "abstract": [
        {
          "text": "The abstract superclass for image analysis requests that operate on both the processed image and a secondary image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTargetedImageRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTargetedImageRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTargetedImageRequest",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCGImage:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request targeting a Core Graphics image, executing the completion handler when done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedCGImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCGImage:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCGImage:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedCGImage:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedcgimage:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCGImage:orientation:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request targeting a Core Graphics image of known orientation, executing the completion handler when done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedCGImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImagePropertyOrientation",
          "text": "CGImagePropertyOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCGImage:orientation:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCGImage:orientation:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedCGImage:orientation:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedcgimage:orientation:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCIImage:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request targeting a Core Image image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedCIImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIImage",
          "text": "CIImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCIImage:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCIImage:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedCIImage:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedciimage:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCIImage:orientation:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request targeting a Core Image image of known orientation, executing the completion handler when done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedCIImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIImage",
          "text": "CIImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImagePropertyOrientation",
          "text": "CGImagePropertyOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCIImage:orientation:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCIImage:orientation:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedCIImage:orientation:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedciimage:orientation:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCMSampleBuffer:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request with a completion handler that targets an image in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedCMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCMSampleBuffer:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCMSampleBuffer:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedCMSampleBuffer:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedcmsamplebuffer:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCMSampleBuffer:orientation:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request with a completion handler that targets an image of a known orientation in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedCMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImagePropertyOrientation",
          "text": "CGImagePropertyOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCMSampleBuffer:orientation:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCMSampleBuffer:orientation:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedCMSampleBuffer:orientation:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedcmsamplebuffer:orientation:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCVPixelBuffer:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request targeting an image in a pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedCVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCVPixelBuffer:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCVPixelBuffer:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedCVPixelBuffer:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedcvpixelbuffer:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCVPixelBuffer:orientation:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request targeting an image in a pixel buffer of known orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedCVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImagePropertyOrientation",
          "text": "CGImagePropertyOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCVPixelBuffer:orientation:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCVPixelBuffer:orientation:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedCVPixelBuffer:orientation:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedcvpixelbuffer:orientation:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageData:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request targeting an image as raw data, executing the completion handler when done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedImageData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageData:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedImageData:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedImageData:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedimagedata:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageData:orientation:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request targeting a raw data image of known orientation, executing the completion handler when done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedImageData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImagePropertyOrientation",
          "text": "CGImagePropertyOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageData:orientation:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedImageData:orientation:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedImageData:orientation:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedimagedata:orientation:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageURL:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request targeting an image at the specified URL, executing the completion handler when done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedImageURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageURL:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedImageURL:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedImageURL:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedimageurl:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageURL:orientation:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request targeting an image of known orientation, at the specified URL, executing the completion handler when done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetedImageURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImagePropertyOrientation",
          "text": "CGImagePropertyOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNImageOption",
          "text": "VNImageOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageURL:orientation:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedImageURL:orientation:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(targetedImageURL:orientation:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/init(targetedimageurl:orientation:options:completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCGImage:options:": {
      "abstract": [
        {
          "text": "Creates a new request targeting a Core Graphics image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedCGImage:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCGImage:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCGImage:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedCGImage:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedcgimage:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCGImage:orientation:options:": {
      "abstract": [
        {
          "text": "Creates a new request targeting a Core Graphics image of known orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedCGImage:orientation:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCGImage:orientation:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCGImage:orientation:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedCGImage:orientation:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedcgimage:orientation:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCIImage:options:": {
      "abstract": [
        {
          "text": "Creates a new request targeting a Core Image image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedCIImage:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCIImage:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCIImage:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedCIImage:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedciimage:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCIImage:orientation:options:": {
      "abstract": [
        {
          "text": "Creates a new request targeting a Core Image image of known orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedCIImage:orientation:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCIImage:orientation:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCIImage:orientation:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedCIImage:orientation:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedciimage:orientation:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCMSampleBuffer:options:": {
      "abstract": [
        {
          "text": "Creates a new request that targets an image in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedCMSampleBuffer:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCMSampleBuffer:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCMSampleBuffer:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedCMSampleBuffer:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedcmsamplebuffer:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCMSampleBuffer:orientation:options:": {
      "abstract": [
        {
          "text": "Creates a new request that targets an image of a known orientation in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedCMSampleBuffer:orientation:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCMSampleBuffer:orientation:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCMSampleBuffer:orientation:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedCMSampleBuffer:orientation:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedcmsamplebuffer:orientation:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCVPixelBuffer:options:": {
      "abstract": [
        {
          "text": "Creates a new request targeting an image in a pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedCVPixelBuffer:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCVPixelBuffer:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCVPixelBuffer:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedCVPixelBuffer:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedcvpixelbuffer:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCVPixelBuffer:orientation:options:": {
      "abstract": [
        {
          "text": "Creates a new request targeting an image in a pixel buffer of known orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedCVPixelBuffer:orientation:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCVPixelBuffer:orientation:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedCVPixelBuffer:orientation:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedCVPixelBuffer:orientation:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedcvpixelbuffer:orientation:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageData:options:": {
      "abstract": [
        {
          "text": "Creates a new request targeting an image as raw data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedImageData:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageData:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedImageData:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedImageData:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedimagedata:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageData:orientation:options:": {
      "abstract": [
        {
          "text": "Creates a new request targeting a raw data image of known orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedImageData:orientation:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageData:orientation:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedImageData:orientation:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedImageData:orientation:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedimagedata:orientation:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageURL:options:": {
      "abstract": [
        {
          "text": "Creates a new request targeting an image at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedImageURL:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageURL:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedImageURL:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedImageURL:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedimageurl:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageURL:orientation:options:": {
      "abstract": [
        {
          "text": "Creates a new request targeting an image of known orientation, at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTargetedImageURL:orientation:options:"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageURL:orientation:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetedImageURL:orientation:options:"
        }
      ],
      "role": "symbol",
      "title": "initWithTargetedImageURL:orientation:options:",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest/initwithtargetedimageurl:orientation:options:"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequest": {
      "abstract": [
        {
          "text": "An image-analysis request, as a stateful request you track over time, that determines the perspective warp matrix necessary to align the content of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackHomographicImageRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackHomographicImageRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackHomographicImageRegistrationRequest",
      "type": "topic",
      "url": "/documentation/vision/vntrackhomographicimageregistrationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest": {
      "abstract": [
        {
          "text": "An image-analysis request, as a stateful request you track over time, that determines the affine transform necessary to align the content of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackTranslationalImageRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackTranslationalImageRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackTranslationalImageRegistrationRequest",
      "type": "topic",
      "url": "/documentation/vision/vntracktranslationalimageregistrationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTranslationalImageRegistrationRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that determines the affine transform necessary to align the content of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTranslationalImageRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTranslationalImageRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTranslationalImageRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTranslationalImageRegistrationRequest",
      "type": "topic",
      "url": "/documentation/vision/vntranslationalimageregistrationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/aligning-similar-images": {
      "abstract": [
        {
          "text": "Construct a composite image from images that capture the same scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/aligning-similar-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Aligning Similar Images",
      "type": "topic",
      "url": "/documentation/vision/aligning-similar-images"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest",
        "doc://com.apple.vision/documentation/Vision/VNImageRegistrationRequest"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-alignment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/aligning-similar-images",
        "doc://com.apple.vision/documentation/Vision/VNImageRegistrationRequest",
        "doc://com.apple.vision/documentation/Vision/VNTranslationalImageRegistrationRequest",
        "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest",
        "doc://com.apple.vision/documentation/Vision/VNHomographicImageRegistrationRequest",
        "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequest",
        "doc://com.apple.vision/documentation/Vision/VNImageAlignmentObservation",
        "doc://com.apple.vision/documentation/Vision/VNImageTranslationAlignmentObservation",
        "doc://com.apple.vision/documentation/Vision/VNImageHomographicAlignmentObservation"
      ],
      "title": "Image alignment"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Request",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCGImage:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCGImage:orientation:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCIImage:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCIImage:orientation:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCVPixelBuffer:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCVPixelBuffer:orientation:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCMSampleBuffer:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCMSampleBuffer:orientation:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageData:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageData:orientation:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageURL:options:completionHandler:)",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageURL:orientation:options:completionHandler:)"
      ],
      "title": "Creating a Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNTargetedImageRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTargetedImageRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTargetedImageRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Request",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCGImage:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCGImage:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCGImage:orientation:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCGImage:orientation:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCIImage:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCIImage:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCIImage:orientation:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCIImage:orientation:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCVPixelBuffer:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCVPixelBuffer:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCVPixelBuffer:orientation:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCVPixelBuffer:orientation:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCMSampleBuffer:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCMSampleBuffer:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedCMSampleBuffer:orientation:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedCMSampleBuffer:orientation:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageData:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageData:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageData:orientation:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageData:orientation:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageURL:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageURL:options:completionHandler:)",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/initWithTargetedImageURL:orientation:options:",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest/init(targetedImageURL:orientation:options:completionHandler:)"
              ],
              "title": "Creating a Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest",
                "doc://com.apple.vision/documentation/Vision/VNImageRegistrationRequest"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-alignment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/aligning-similar-images",
                "doc://com.apple.vision/documentation/Vision/VNImageRegistrationRequest",
                "doc://com.apple.vision/documentation/Vision/VNTranslationalImageRegistrationRequest",
                "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest",
                "doc://com.apple.vision/documentation/Vision/VNHomographicImageRegistrationRequest",
                "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequest",
                "doc://com.apple.vision/documentation/Vision/VNImageAlignmentObservation",
                "doc://com.apple.vision/documentation/Vision/VNImageTranslationAlignmentObservation",
                "doc://com.apple.vision/documentation/Vision/VNImageHomographicAlignmentObservation"
              ],
              "title": "Image alignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNTargetedImageRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNImageBasedRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNImageBasedRequest",
                    "text": "VNImageBasedRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCVPixelBuffer:orientation:options:completionHandler:)/title",
          "value": "initWithTargetedCVPixelBuffer:orientation:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCVPixelBuffer:orientation:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedCVPixelBuffer:orientation:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedImageURL:options:completionHandler:)/title",
          "value": "initWithTargetedImageURL:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedImageURL:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedImageURL:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCMSampleBuffer:orientation:options:completionHandler:)/title",
          "value": "initWithTargetedCMSampleBuffer:orientation:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCMSampleBuffer:orientation:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedCMSampleBuffer:orientation:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest/title",
          "value": "VNTargetedImageRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTargetedImageRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTargetedImageRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCIImage:options:completionHandler:)/title",
          "value": "initWithTargetedCIImage:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCIImage:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedCIImage:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest/title",
          "value": "VNGenerateOpticalFlowRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackHomographicImageRegistrationRequest/title",
          "value": "VNTrackHomographicImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackHomographicImageRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackHomographicImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackHomographicImageRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackHomographicImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCVPixelBuffer:options:completionHandler:)/title",
          "value": "initWithTargetedCVPixelBuffer:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCVPixelBuffer:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedCVPixelBuffer:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageRegistrationRequest/title",
          "value": "VNImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageHomographicAlignmentObservation/title",
          "value": "VNImageHomographicAlignmentObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageHomographicAlignmentObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageHomographicAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageHomographicAlignmentObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageHomographicAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCGImage:options:completionHandler:)/title",
          "value": "initWithTargetedCGImage:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCGImage:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedCGImage:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedImageURL:orientation:options:completionHandler:)/title",
          "value": "initWithTargetedImageURL:orientation:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedImageURL:orientation:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedImageURL:orientation:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedImageData:orientation:options:completionHandler:)/title",
          "value": "initWithTargetedImageData:orientation:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedImageData:orientation:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedImageData:orientation:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTranslationalImageRegistrationRequest/title",
          "value": "VNTranslationalImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTranslationalImageRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTranslationalImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTranslationalImageRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTranslationalImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageAlignmentObservation/title",
          "value": "VNImageAlignmentObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageAlignmentObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageAlignmentObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCMSampleBuffer:options:completionHandler:)/title",
          "value": "initWithTargetedCMSampleBuffer:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCMSampleBuffer:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedCMSampleBuffer:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCIImage:orientation:options:completionHandler:)/title",
          "value": "initWithTargetedCIImage:orientation:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCIImage:orientation:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedCIImage:orientation:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCGImage:orientation:options:completionHandler:)/title",
          "value": "initWithTargetedCGImage:orientation:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedCGImage:orientation:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedCGImage:orientation:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageTranslationAlignmentObservation/title",
          "value": "VNImageTranslationAlignmentObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageTranslationAlignmentObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageTranslationAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageTranslationAlignmentObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageTranslationAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest/title",
          "value": "VNTrackTranslationalImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackTranslationalImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackTranslationalImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedImageData:options:completionHandler:)/title",
          "value": "initWithTargetedImageData:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest~1init(targetedImageData:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetedImageData:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageBasedRequest/title",
          "value": "VNImageBasedRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageBasedRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageBasedRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageBasedRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageBasedRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHomographicImageRegistrationRequest/title",
          "value": "VNHomographicImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHomographicImageRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHomographicImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHomographicImageRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHomographicImageRegistrationRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vntargetedimagerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vntargetedimagerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
