{
  "abstract": [
    {
      "text": "An image-analysis request, as a stateful request you track over time, that determines the affine transform necessary to align the content of two images.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNTrackTranslationalImageRegistrationRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VNTrackTranslationalImageRegistrationRequest"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNTrackTranslationalImageRegistrationRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VNTrackTranslationalImageRegistrationRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VNTrackTranslationalImageRegistrationRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This request is similar to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNTranslationalImageRegistrationRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". However, as a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNStatefulRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", it automatically computes the registration against the previous frame.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNHomographicImageRegistrationRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that determines the perspective warp matrix necessary to align the content of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHomographicImageRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHomographicImageRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHomographicImageRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNHomographicImageRegistrationRequest",
      "type": "topic",
      "url": "/documentation/vision/vnhomographicimageregistrationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageAlignmentObservation": {
      "abstract": [
        {
          "text": "The abstract superclass for image-analysis results that describe the relative alignment of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageAlignmentObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageAlignmentObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageAlignmentObservation"
        }
      ],
      "role": "symbol",
      "title": "VNImageAlignmentObservation",
      "type": "topic",
      "url": "/documentation/vision/vnimagealignmentobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageHomographicAlignmentObservation": {
      "abstract": [
        {
          "text": "An object that represents a perspective warp transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageHomographicAlignmentObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageHomographicAlignmentObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageHomographicAlignmentObservation"
        }
      ],
      "role": "symbol",
      "title": "VNImageHomographicAlignmentObservation",
      "type": "topic",
      "url": "/documentation/vision/vnimagehomographicalignmentobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageRegistrationRequest": {
      "abstract": [
        {
          "text": "The abstract superclass for image-analysis requests that align images according to their content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNImageRegistrationRequest",
      "type": "topic",
      "url": "/documentation/vision/vnimageregistrationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageTranslationAlignmentObservation": {
      "abstract": [
        {
          "text": "Affine transform information that an image-alignment request produces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageTranslationAlignmentObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageTranslationAlignmentObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageTranslationAlignmentObservation"
        }
      ],
      "role": "symbol",
      "title": "VNImageTranslationAlignmentObservation",
      "type": "topic",
      "url": "/documentation/vision/vnimagetranslationalignmentobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNStatefulRequest": {
      "abstract": [
        {
          "text": "An abstract request type that builds evidence of a condition over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNStatefulRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNStatefulRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNStatefulRequest"
        }
      ],
      "role": "symbol",
      "title": "VNStatefulRequest",
      "type": "topic",
      "url": "/documentation/vision/vnstatefulrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest": {
      "abstract": [
        {
          "text": "The abstract superclass for image analysis requests that operate on both the processed image and a secondary image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTargetedImageRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTargetedImageRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTargetedImageRequest",
      "type": "topic",
      "url": "/documentation/vision/vntargetedimagerequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequest": {
      "abstract": [
        {
          "text": "An image-analysis request, as a stateful request you track over time, that determines the perspective warp matrix necessary to align the content of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackHomographicImageRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackHomographicImageRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackHomographicImageRegistrationRequest",
      "type": "topic",
      "url": "/documentation/vision/vntrackhomographicimageregistrationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest": {
      "abstract": [
        {
          "text": "An image-analysis request, as a stateful request you track over time, that determines the affine transform necessary to align the content of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackTranslationalImageRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackTranslationalImageRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackTranslationalImageRegistrationRequest",
      "type": "topic",
      "url": "/documentation/vision/vntracktranslationalimageregistrationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/init()": {
      "abstract": [
        {
          "text": "Creates a new request that tracks the translational registration of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/vision/vntracktranslationalimageregistrationrequest/init()"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/init(completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new request that tracks the translational registration of two images, with a system callback on completion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRequestCompletionHandler",
          "text": "VNRequestCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/init(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(completionHandler:)",
      "type": "topic",
      "url": "/documentation/vision/vntracktranslationalimageregistrationrequest/init(completionhandler:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/results": {
      "abstract": [
        {
          "text": "The observed translational image alignment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "results"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNImageTranslationAlignmentObservation",
          "text": "VNImageTranslationAlignmentObservation"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/results",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "results"
        }
      ],
      "role": "symbol",
      "title": "results",
      "type": "topic",
      "url": "/documentation/vision/vntracktranslationalimageregistrationrequest/results"
    },
    "doc://com.apple.vision/documentation/Vision/VNTranslationalImageRegistrationRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that determines the affine transform necessary to align the content of two images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTranslationalImageRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTranslationalImageRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTranslationalImageRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTranslationalImageRegistrationRequest",
      "type": "topic",
      "url": "/documentation/vision/vntranslationalimageregistrationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/aligning-similar-images": {
      "abstract": [
        {
          "text": "Construct a composite image from images that capture the same scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/aligning-similar-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Aligning Similar Images",
      "type": "topic",
      "url": "/documentation/vision/aligning-similar-images"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNStatefulRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-alignment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/aligning-similar-images",
        "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest",
        "doc://com.apple.vision/documentation/Vision/VNImageRegistrationRequest",
        "doc://com.apple.vision/documentation/Vision/VNTranslationalImageRegistrationRequest",
        "doc://com.apple.vision/documentation/Vision/VNHomographicImageRegistrationRequest",
        "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequest",
        "doc://com.apple.vision/documentation/Vision/VNImageAlignmentObservation",
        "doc://com.apple.vision/documentation/Vision/VNImageTranslationAlignmentObservation",
        "doc://com.apple.vision/documentation/Vision/VNImageHomographicAlignmentObservation"
      ],
      "title": "Image alignment"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Translational-Image",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/init()",
        "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/init(completionHandler:)"
      ],
      "title": "Creating a Translational Image"
    },
    {
      "anchor": "Accessing-the-Results",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/results"
      ],
      "title": "Accessing the Results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNTrackTranslationalImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackTranslationalImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackTranslationalImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Translational-Image",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/init()",
                "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/init(completionHandler:)"
              ],
              "title": "Creating a Translational Image"
            },
            {
              "anchor": "Accessing-the-Results",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNTrackTranslationalImageRegistrationRequest/results"
              ],
              "title": "Accessing the Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNStatefulRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-alignment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/aligning-similar-images",
                "doc://com.apple.vision/documentation/Vision/VNTargetedImageRequest",
                "doc://com.apple.vision/documentation/Vision/VNImageRegistrationRequest",
                "doc://com.apple.vision/documentation/Vision/VNTranslationalImageRegistrationRequest",
                "doc://com.apple.vision/documentation/Vision/VNHomographicImageRegistrationRequest",
                "doc://com.apple.vision/documentation/Vision/VNTrackHomographicImageRegistrationRequest",
                "doc://com.apple.vision/documentation/Vision/VNImageAlignmentObservation",
                "doc://com.apple.vision/documentation/Vision/VNImageTranslationAlignmentObservation",
                "doc://com.apple.vision/documentation/Vision/VNImageHomographicAlignmentObservation"
              ],
              "title": "Image alignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNTrackTranslationalImageRegistrationRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNStatefulRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNStatefulRequest",
                    "text": "VNStatefulRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest/title",
          "value": "VNTargetedImageRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTargetedImageRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTargetedImageRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTargetedImageRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageRegistrationRequest/title",
          "value": "VNImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/title",
          "value": "VNStatefulRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNStatefulRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNStatefulRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNStatefulRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTranslationalImageRegistrationRequest/title",
          "value": "VNTranslationalImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTranslationalImageRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTranslationalImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTranslationalImageRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTranslationalImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest~1results/title",
          "value": "results"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest~1results/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageTranslationAlignmentObservation/title",
          "value": "VNImageTranslationAlignmentObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageTranslationAlignmentObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageTranslationAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageTranslationAlignmentObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageTranslationAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest~1init(completionHandler:)/title",
          "value": "initWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest~1init(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest/title",
          "value": "VNTrackTranslationalImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackTranslationalImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackTranslationalImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackTranslationalImageRegistrationRequest~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageAlignmentObservation/title",
          "value": "VNImageAlignmentObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageAlignmentObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageAlignmentObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackHomographicImageRegistrationRequest/title",
          "value": "VNTrackHomographicImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackHomographicImageRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackHomographicImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackHomographicImageRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackHomographicImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageHomographicAlignmentObservation/title",
          "value": "VNImageHomographicAlignmentObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageHomographicAlignmentObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageHomographicAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageHomographicAlignmentObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageHomographicAlignmentObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHomographicImageRegistrationRequest/title",
          "value": "VNHomographicImageRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHomographicImageRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHomographicImageRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHomographicImageRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHomographicImageRegistrationRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vntracktranslationalimageregistrationrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vntracktranslationalimageregistrationrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
