{
  "abstract": [
    {
      "text": "An accessory position at the bottom-left of the primary pointer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/bottomLeft"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So18UIPointerAccessoryC5UIKitE8PositionV10bottomLeftAEvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bottomLeft"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIPointerAccessory",
        "text": "UIPointerAccessory"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So18UIPointerAccessoryC5UIKitE8PositionV",
        "text": "Position"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "bottomLeft"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bottomLeft"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIPointerAccessory",
              "text": "UIPointerAccessory"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So18UIPointerAccessoryC5UIKitE8PositionV",
              "text": "Position"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory": {
      "abstract": [
        {
          "text": "Constants that describe accessories to display alongside the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerAccessory"
        }
      ],
      "role": "symbol",
      "title": "UIPointerAccessory",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct": {
      "abstract": [
        {
          "text": "A structure that specifies the position of the accessory relative to the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "role": "symbol",
      "title": "UIPointerAccessory.Position",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/position-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/bottom": {
      "abstract": [
        {
          "text": "An accessory position at the bottom of the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPointerAccessory",
          "text": "UIPointerAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18UIPointerAccessoryC5UIKitE8PositionV",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/bottom",
      "kind": "symbol",
      "role": "symbol",
      "title": "bottom",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/position-swift.struct/bottom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/bottomLeft": {
      "abstract": [
        {
          "text": "An accessory position at the bottom-left of the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPointerAccessory",
          "text": "UIPointerAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18UIPointerAccessoryC5UIKitE8PositionV",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/bottomLeft",
      "kind": "symbol",
      "role": "symbol",
      "title": "bottomLeft",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/position-swift.struct/bottomleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/bottomRight": {
      "abstract": [
        {
          "text": "An accessory position at the bottom-right of the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPointerAccessory",
          "text": "UIPointerAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18UIPointerAccessoryC5UIKitE8PositionV",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/bottomRight",
      "kind": "symbol",
      "role": "symbol",
      "title": "bottomRight",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/position-swift.struct/bottomright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/left": {
      "abstract": [
        {
          "text": "An accessory position at the left of the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPointerAccessory",
          "text": "UIPointerAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18UIPointerAccessoryC5UIKitE8PositionV",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/left",
      "kind": "symbol",
      "role": "symbol",
      "title": "left",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/position-swift.struct/left"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/right": {
      "abstract": [
        {
          "text": "An accessory position at the right of the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPointerAccessory",
          "text": "UIPointerAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18UIPointerAccessoryC5UIKitE8PositionV",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/right",
      "kind": "symbol",
      "role": "symbol",
      "title": "right",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/position-swift.struct/right"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/top": {
      "abstract": [
        {
          "text": "An accessory position at the top of the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPointerAccessory",
          "text": "UIPointerAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18UIPointerAccessoryC5UIKitE8PositionV",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/top",
      "kind": "symbol",
      "role": "symbol",
      "title": "top",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/position-swift.struct/top"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/topLeft": {
      "abstract": [
        {
          "text": "An accessory position at the top-left of the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPointerAccessory",
          "text": "UIPointerAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18UIPointerAccessoryC5UIKitE8PositionV",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/topLeft",
      "kind": "symbol",
      "role": "symbol",
      "title": "topLeft",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/position-swift.struct/topleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/topRight": {
      "abstract": [
        {
          "text": "An accessory position at the top-right of the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPointerAccessory",
          "text": "UIPointerAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18UIPointerAccessoryC5UIKitE8PositionV",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/topRight",
      "kind": "symbol",
      "role": "symbol",
      "title": "topRight",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/position-swift.struct/topright"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-an-accessory-position",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/top",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/topRight",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/right",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/bottomRight",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/bottom",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/left",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct/topLeft"
      ],
      "title": "Getting an accessory position"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/title",
          "value": "UIPointerAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerAccessory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipointeraccessory/position-swift.struct/bottomleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
