{
  "abstract": [
    {
      "text": "Adds the specified item to the end of the queue.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/appendItem(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKAudioFileQueuePlayer(im)appendItem:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "appendItem"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)WKAudioFilePlayerItem",
        "text": "WKAudioFilePlayerItem"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "appendItem:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "appendItem(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "appendItem"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "item"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKAudioFilePlayerItem",
              "text": "WKAudioFilePlayerItem"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The player item to add to the queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "item"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem": {
      "abstract": [
        {
          "text": "An object that manages the presentation state of an audio file while it is playing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayerItem"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayerItem"
        }
      ],
      "role": "symbol",
      "title": "WKAudioFilePlayerItem",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileplayeritem"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer": {
      "abstract": [
        {
          "text": "An object that controls playback of one or more audio items.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAudioFileQueuePlayer"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioFileQueuePlayer"
        }
      ],
      "role": "symbol",
      "title": "WKAudioFileQueuePlayer",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofilequeueplayer"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/advanceToNextItem()": {
      "abstract": [
        {
          "text": "Ends playback of the current item and begins playing the next item in the queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "advanceToNextItem"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/advanceToNextItem()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "advanceToNextItem"
        }
      ],
      "role": "symbol",
      "title": "advanceToNextItem()",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofilequeueplayer/advancetonextitem()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/appendItem(_:)": {
      "abstract": [
        {
          "text": "Adds the specified item to the end of the queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKAudioFilePlayerItem",
          "text": "WKAudioFilePlayerItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/appendItem(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appendItem:"
        }
      ],
      "role": "symbol",
      "title": "appendItem(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofilequeueplayer/appenditem(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/items": {
      "abstract": [
        {
          "text": "The array of queued items.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "items"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKAudioFilePlayerItem",
          "text": "WKAudioFilePlayerItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/items",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "items"
        }
      ],
      "role": "symbol",
      "title": "items",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofilequeueplayer/items"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/removeAllItems()": {
      "abstract": [
        {
          "text": "Removes all items from the queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllItems"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/removeAllItems()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllItems"
        }
      ],
      "role": "symbol",
      "title": "removeAllItems()",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofilequeueplayer/removeallitems()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/removeItem(_:)": {
      "abstract": [
        {
          "text": "Removes the specified item from the queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKAudioFilePlayerItem",
          "text": "WKAudioFilePlayerItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/removeItem(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeItem:"
        }
      ],
      "role": "symbol",
      "title": "removeItem(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofilequeueplayer/removeitem(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Items",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/items",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/advanceToNextItem()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/removeItem(_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/removeAllItems()"
      ],
      "title": "Managing Items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "appendItem:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "appendItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Items",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/items",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/advanceToNextItem()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/removeItem(_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer/removeAllItems()"
              ],
              "title": "Managing Items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "appendItem:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WKAudioFilePlayerItem",
                    "text": "WKAudioFilePlayerItem"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "item"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The player item to add to the queue.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "item"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer~1items/title",
          "value": "items"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer~1items/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer/title",
          "value": "WKAudioFileQueuePlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFileQueuePlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFileQueuePlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer~1appendItem(_:)/title",
          "value": "appendItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer~1appendItem(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "appendItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer~1advanceToNextItem()/title",
          "value": "advanceToNextItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer~1advanceToNextItem()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "advanceToNextItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerItem/title",
          "value": "WKAudioFilePlayerItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer~1removeAllItems()/title",
          "value": "removeAllItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer~1removeAllItems()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer~1removeItem(_:)/title",
          "value": "removeItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer~1removeItem(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeItem:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkaudiofilequeueplayer/appenditem(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkaudiofilequeueplayer/appenditem(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
