{
  "abstract": [
    {
      "text": "Don’t provide any reflection information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLPipelineOption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/MTLPipelineOptionNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLPipelineOption@MTLPipelineOptionNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MTLPipelineOptionNone"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLPipelineOptionNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "MTLPipelineOptionNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "MTLPipelineOptionNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPipelineOption": {
      "abstract": [
        {
          "text": "Options that determine how Metal prepares the pipeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPipelineOption"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPipelineOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPipelineOption"
        }
      ],
      "role": "symbol",
      "title": "MTLPipelineOption",
      "type": "topic",
      "url": "/documentation/metal/mtlpipelineoption"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/MTLPipelineOptionNone": {
      "abstract": [
        {
          "text": "Don’t provide any reflection information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLPipelineOptionNone"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/MTLPipelineOptionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLPipelineOptionNone",
      "type": "topic",
      "url": "/documentation/metal/mtlpipelineoption/mtlpipelineoptionnone"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/argumentInfo": {
      "abstract": [
        {
          "text": "An option instance that provides argument information for textures and threadgroup memory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argumentInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPipelineOption",
          "text": "MTLPipelineOption"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/argumentInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPipelineOptionArgumentInfo"
        }
      ],
      "role": "symbol",
      "title": "argumentInfo",
      "type": "topic",
      "url": "/documentation/metal/mtlpipelineoption/argumentinfo"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/bufferTypeInfo": {
      "abstract": [
        {
          "text": "An option instance that provides detailed buffer type information for buffer arguments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bufferTypeInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPipelineOption",
          "text": "MTLPipelineOption"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/bufferTypeInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPipelineOptionBufferTypeInfo"
        }
      ],
      "role": "symbol",
      "title": "bufferTypeInfo",
      "type": "topic",
      "url": "/documentation/metal/mtlpipelineoption/buffertypeinfo"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/failOnBinaryArchiveMiss": {
      "abstract": [
        {
          "text": "An option that specifies that Metal only creates the pipeline state object if the compiled shader is present inside a linked binary archive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failOnBinaryArchiveMiss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPipelineOption",
          "text": "MTLPipelineOption"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/failOnBinaryArchiveMiss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPipelineOptionFailOnBinaryArchiveMiss"
        }
      ],
      "role": "symbol",
      "title": "failOnBinaryArchiveMiss",
      "type": "topic",
      "url": "/documentation/metal/mtlpipelineoption/failonbinaryarchivemiss"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retrieving-Argument-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/bufferTypeInfo",
        "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/failOnBinaryArchiveMiss",
        "doc://com.apple.metal/documentation/Metal/MTLPipelineOption/argumentInfo"
      ],
      "title": "Retrieving Argument Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPipelineOption/title",
          "value": "MTLPipelineOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPipelineOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPipelineOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPipelineOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPipelineOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPipelineOption~1argumentInfo/title",
          "value": "MTLPipelineOptionArgumentInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPipelineOption~1argumentInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPipelineOptionArgumentInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPipelineOption~1failOnBinaryArchiveMiss/title",
          "value": "MTLPipelineOptionFailOnBinaryArchiveMiss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPipelineOption~1failOnBinaryArchiveMiss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPipelineOptionFailOnBinaryArchiveMiss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPipelineOption~1bufferTypeInfo/title",
          "value": "MTLPipelineOptionBufferTypeInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPipelineOption~1bufferTypeInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPipelineOptionBufferTypeInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlpipelineoption/mtlpipelineoptionnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
