{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSStoryboard"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSStoryboard/instantiateControllerWithIdentifier:creator:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSStoryboard(im)instantiateControllerWithIdentifier:creator:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "instantiateControllerWithIdentifier:creator:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "instantiateControllerWithIdentifier:creator:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "instantiateControllerWithIdentifier:creator:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "instantiateControllerWithIdentifier:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStoryboard/SceneIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSStoryboardSceneIdentifier",
              "text": "NSStoryboardSceneIdentifier"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "identifier"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "creator:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStoryboardControllerCreator",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSStoryboardControllerCreator",
              "text": "NSStoryboardControllerCreator"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStoryboard": {
      "abstract": [
        {
          "text": "An encapsulation of the design-time view controller and window controller graph represented in an Interface Builder storyboard resource file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStoryboard"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStoryboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStoryboard"
        }
      ],
      "role": "symbol",
      "title": "NSStoryboard",
      "type": "topic",
      "url": "/documentation/appkit/nsstoryboard"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStoryboard/SceneIdentifier": {
      "abstract": [
        {
          "text": "A string that uniquely identifies a view controller or window controller in your storyboard file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStoryboard/SceneIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSStoryboard.SceneIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nsstoryboard/sceneidentifier"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStoryboard/instantiateControllerWithIdentifier:creator:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "instantiateControllerWithIdentifier:creator:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStoryboard/instantiateControllerWithIdentifier:creator:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instantiateControllerWithIdentifier:creator:"
        }
      ],
      "role": "symbol",
      "title": "instantiateControllerWithIdentifier:creator:",
      "type": "topic",
      "url": "/documentation/appkit/nsstoryboard/instantiatecontrollerwithidentifier:creator:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStoryboard/instantiateInitialControllerWithCreator:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "instantiateInitialControllerWithCreator:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStoryboard/instantiateInitialControllerWithCreator:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instantiateInitialControllerWithCreator:"
        }
      ],
      "role": "symbol",
      "title": "instantiateInitialControllerWithCreator:",
      "type": "topic",
      "url": "/documentation/appkit/nsstoryboard/instantiateinitialcontrollerwithcreator:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStoryboardControllerCreator": {
      "abstract": [
        {
          "text": "A block that you use to handle the custom creation of controller objects from your storyboard file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStoryboardControllerCreator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStoryboardControllerCreator",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStoryboardControllerCreator",
      "type": "topic",
      "url": "/documentation/appkit/nsstoryboardcontrollercreator"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSStoryboard/instantiateInitialControllerWithCreator:"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStoryboard/title",
          "value": "NSStoryboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStoryboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStoryboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStoryboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStoryboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStoryboard~1SceneIdentifier/title",
          "value": "NSStoryboardSceneIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStoryboard~1SceneIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStoryboardSceneIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStoryboard~1SceneIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStoryboardSceneIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsstoryboard/instantiatecontrollerwithidentifier:creator:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
