{
  "abstract": [
    {
      "text": "The app shouldn’t display a badge.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/RemoteNotificationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSRemoteNotificationType/NSRemoteNotificationTypeNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSRemoteNotificationType@NSRemoteNotificationTypeNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSRemoteNotificationTypeNone"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSRemoteNotificationTypeNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NSRemoteNotificationTypeNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NSRemoteNotificationTypeNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/RemoteNotificationType": {
      "abstract": [
        {
          "text": "These constants determine whether apps launched by remote notifications display a badge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/RemoteNotificationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RemoteNotificationType"
        }
      ],
      "role": "symbol",
      "title": "NSApplication.RemoteNotificationType",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/remotenotificationtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRemoteNotificationType/NSRemoteNotificationTypeNone": {
      "abstract": [
        {
          "text": "The app shouldn’t display a badge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRemoteNotificationTypeNone"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRemoteNotificationType/NSRemoteNotificationTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRemoteNotificationTypeNone",
      "type": "topic",
      "url": "/documentation/appkit/nsremotenotificationtype/nsremotenotificationtypenone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1RemoteNotificationType/title",
          "value": "NSRemoteNotificationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1RemoteNotificationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRemoteNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1RemoteNotificationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRemoteNotificationType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsremotenotificationtype/nsremotenotificationtypenone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
