{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canInsert","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"type":"text","text":" if an object can be inserted into the receiver’s content collection, otherwise "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of this method can be used by a binding to enable user interface items."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property is observable using key-value observing."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSArrayController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/canInsert","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/appkit/nsarraycontroller/caninsert"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsarraycontroller/caninsert"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(_:)"],"anchor":"Inserting","title":"Inserting"}],"metadata":{"title":"canInsert","navigatorTitle":[{"kind":"identifier","text":"canInsert"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canInsert"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","symbolKind":"property","platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"externalID":"c:objc(cs)NSArrayController(py)canInsert","roleHeading":"Instance Property","modules":[{"name":"AppKit"}]},"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether an object can be inserted into the receiver’s content collection."}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController":{"role":"symbol","abstract":[{"type":"text","text":"A bindings-compatible controller that manages a collection of objects."}],"navigatorTitle":[{"kind":"identifier","text":"NSArrayController"}],"type":"topic","kind":"symbol","title":"NSArrayController","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController","url":"/documentation/appkit/nsarraycontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSArrayController"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(_:)":{"kind":"symbol","navigatorTitle":[{"text":"insert:","kind":"identifier"}],"url":"/documentation/appkit/nsarraycontroller/insert(_:)","title":"insert(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insert"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(_:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates a new object and inserts it into the receiver’s content array."}]},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/canInsert":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canInsert"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"/documentation/appkit/nsarraycontroller/caninsert","title":"canInsert","navigatorTitle":[{"kind":"identifier","text":"canInsert"}],"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether an object can be inserted into the receiver’s content collection."}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/canInsert","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"canInsert"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"canInsert","kind":"identifier"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSArrayController"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"anchor":"Inserting","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(_:)"],"title":"Inserting"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"canInsert","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"NSArrayController","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/title","op":"replace"},{"value":[{"text":"NSArrayController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSArrayController"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/navigatorTitle","op":"replace"},{"value":"insert:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1insert(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"insert:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1insert(_:)/fragments","op":"replace"},{"value":"canInsert","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1canInsert/title","op":"replace"},{"value":[{"kind":"identifier","text":"canInsert"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1canInsert/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}