{
  "abstract": [
    {
      "text": "Invoked when any criteria for arranging objects change.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSArrayController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSArrayController/didChangeArrangementCriteria()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSArrayController(im)didChangeArrangementCriteria",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "didChangeArrangementCriteria"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "didChangeArrangementCriteria"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "didChangeArrangementCriteria()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didChangeArrangementCriteria"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is invoked by the controller itself when any criteria for arranging objects change (sort descriptors or filter predicates) to reset the key paths for automatic rearranging.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you implement a subclass of ",
              "type": "text"
            },
            {
              "code": "NSArrayController",
              "type": "codeVoice"
            },
            {
              "text": " and override ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSArrayController/rearrangeObjects()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to use additional arrangement criteria, you should invoke this method if those criteria change.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSArrayController": {
      "abstract": [
        {
          "text": "A bindings-compatible controller that manages a collection of objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSArrayController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSArrayController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSArrayController"
        }
      ],
      "role": "symbol",
      "title": "NSArrayController",
      "type": "topic",
      "url": "/documentation/appkit/nsarraycontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSArrayController/automaticRearrangementKeyPaths": {
      "abstract": [
        {
          "text": "An array of key paths that trigger automatic content sorting or filtering",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticRearrangementKeyPaths"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSArrayController/automaticRearrangementKeyPaths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticRearrangementKeyPaths"
        }
      ],
      "role": "symbol",
      "title": "automaticRearrangementKeyPaths",
      "type": "topic",
      "url": "/documentation/appkit/nsarraycontroller/automaticrearrangementkeypaths"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSArrayController/automaticallyRearrangesObjects": {
      "abstract": [
        {
          "text": "A Boolean that indicates if the receiver automatically rearranges its content to correspond to the current sort descriptors and filter predicates",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallyRearrangesObjects"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSArrayController/automaticallyRearrangesObjects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallyRearrangesObjects"
        }
      ],
      "role": "symbol",
      "title": "automaticallyRearrangesObjects",
      "type": "topic",
      "url": "/documentation/appkit/nsarraycontroller/automaticallyrearrangesobjects"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSArrayController/didChangeArrangementCriteria()": {
      "abstract": [
        {
          "text": "Invoked when any criteria for arranging objects change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeArrangementCriteria"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSArrayController/didChangeArrangementCriteria()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didChangeArrangementCriteria"
        }
      ],
      "role": "symbol",
      "title": "didChangeArrangementCriteria()",
      "type": "topic",
      "url": "/documentation/appkit/nsarraycontroller/didchangearrangementcriteria()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSArrayController/rearrangeObjects()": {
      "abstract": [
        {
          "text": "Triggers filtering of the receiver’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rearrangeObjects"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSArrayController/rearrangeObjects()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rearrangeObjects"
        }
      ],
      "role": "symbol",
      "title": "rearrangeObjects()",
      "type": "topic",
      "url": "/documentation/appkit/nsarraycontroller/rearrangeobjects()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSArrayController/rearrangeObjects()"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Automatic-Content-Rearranging",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSArrayController/automaticallyRearrangesObjects",
        "doc://com.apple.appkit/documentation/AppKit/NSArrayController/automaticRearrangementKeyPaths"
      ],
      "title": "Automatic Content Rearranging"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "didChangeArrangementCriteria"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didChangeArrangementCriteria"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSArrayController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSArrayController/rearrangeObjects()"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Automatic-Content-Rearranging",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSArrayController/automaticallyRearrangesObjects",
                "doc://com.apple.appkit/documentation/AppKit/NSArrayController/automaticRearrangementKeyPaths"
              ],
              "title": "Automatic Content Rearranging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "didChangeArrangementCriteria"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1automaticallyRearrangesObjects/title",
          "value": "automaticallyRearrangesObjects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1automaticallyRearrangesObjects/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticallyRearrangesObjects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1automaticRearrangementKeyPaths/title",
          "value": "automaticRearrangementKeyPaths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1automaticRearrangementKeyPaths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticRearrangementKeyPaths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/title",
          "value": "NSArrayController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSArrayController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSArrayController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1rearrangeObjects()/title",
          "value": "rearrangeObjects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1rearrangeObjects()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rearrangeObjects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1didChangeArrangementCriteria()/title",
          "value": "didChangeArrangementCriteria"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1didChangeArrangementCriteria()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didChangeArrangementCriteria"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsarraycontroller/didchangearrangementcriteria()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsarraycontroller/didchangearrangementcriteria()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
