{"metadata":{"externalID":"c:objc(cs)NSArrayController(im)removeObject:","navigatorTitle":[{"kind":"identifier","text":"removeObject:"}],"roleHeading":"Instance Method","symbolKind":"method","title":"removeObject(_:)","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"role":"symbol","modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObject"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSArrayController"]]},"seeAlsoSections":[{"anchor":"Adding-and-Removing-Objects","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSArrayController/addObject(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/add(contentsOf:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(_:atArrangedObjectIndex:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(contentsOf:atArrangedObjectIndexes:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(atArrangedObjectIndex:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(atArrangedObjectIndexes:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(contentsOf:)"],"title":"Adding and Removing Objects","generated":true}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"If you are using Core Data, the exact semantics of this method differ depending on the settings for the array controller. If the receiver’s content is fetched automatically, removed objects are marked for deletion by the managed object context (and hence removal from the object graph). If, however, the receiver’s ","type":"text"},{"type":"codeVoice","code":"contentSet"},{"text":" is bound to a relationship, ","type":"text"},{"type":"codeVoice","code":"removeObject:"},{"text":" by default only removes the object from the relationship (not from the object graph). You can, though, set the “Deletes Object on Remove” option for the ","type":"text"},{"type":"codeVoice","code":"contentSet"},{"text":" binding, in which case objects are marked for deletion as well as being removed from the relationship.","type":"text"}]}],"kind":"content"}],"sections":[],"variants":[{"paths":["/documentation/appkit/nsarraycontroller/removeobject(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsarraycontroller/removeobject(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Removes ","type":"text"},{"code":"object","type":"codeVoice"},{"text":" from the receiver’s content collection.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeObject(_:)"},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"kind":"symbol","title":"remove(_:)","url":"/documentation/appkit/nsarraycontroller/remove(_:)","type":"topic","abstract":[{"type":"text","text":"Removes the receiver’s selected objects from the content collection."}],"navigatorTitle":[{"kind":"identifier","text":"remove:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(_:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(atArrangedObjectIndexes:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atArrangedObjectIndexes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier","text":"IndexSet"},{"kind":"text","text":")"}],"kind":"symbol","title":"remove(atArrangedObjectIndexes:)","url":"/documentation/appkit/nsarraycontroller/remove(atarrangedobjectindexes:)","type":"topic","abstract":[{"text":"Removes the objects at the specified ","type":"text"},{"type":"codeVoice","code":"indexes"},{"type":"text","text":" in the receiver’s arranged objects from the content array."}],"navigatorTitle":[{"kind":"identifier","text":"removeObjectsAtArrangedObjectIndexes:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(atArrangedObjectIndexes:)"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(contentsOf:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"contentsOf"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"kind":"symbol","title":"remove(contentsOf:)","url":"/documentation/appkit/nsarraycontroller/remove(contentsof:)","type":"topic","abstract":[{"text":"Removes ","type":"text"},{"code":"objects","type":"codeVoice"},{"text":" from the receiver’s content collection.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeObjects:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(contentsOf:)"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeObject(_:)":{"url":"/documentation/appkit/nsarraycontroller/removeobject(_:)","navigatorTitle":[{"kind":"identifier","text":"removeObject:"}],"title":"removeObject(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObject"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[{"text":"Removes ","type":"text"},{"code":"object","type":"codeVoice"},{"text":" from the receiver’s content collection.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeObject(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/addObject(_:)":{"navigatorTitle":[{"kind":"identifier","text":"addObject:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addObject"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/addObject(_:)","abstract":[{"type":"text","text":"Adds "},{"type":"codeVoice","code":"object"},{"type":"text","text":" to the receiver’s content collection and the arranged objects array."}],"title":"addObject(_:)","role":"symbol","type":"topic","url":"/documentation/appkit/nsarraycontroller/addobject(_:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(contentsOf:atArrangedObjectIndexes:)":{"type":"topic","title":"insert(contentsOf:atArrangedObjectIndexes:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insert"},{"kind":"text","text":"("},{"kind":"externalParam","text":"contentsOf"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"atArrangedObjectIndexes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier","text":"IndexSet"},{"kind":"text","text":")"}],"url":"/documentation/appkit/nsarraycontroller/insert(contentsof:atarrangedobjectindexes:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(contentsOf:atArrangedObjectIndexes:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"insertObjects:atArrangedObjectIndexes:"}],"abstract":[{"text":"Inserts ","type":"text"},{"code":"object","type":"codeVoice"},{"text":"s into the receiver’s arranged objects array at the locations specified in ","type":"text"},{"type":"codeVoice","code":"indexes"},{"type":"text","text":", and adds it to the receiver’s content collection."}]},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/add(contentsOf:)":{"type":"topic","url":"/documentation/appkit/nsarraycontroller/add(contentsof:)","navigatorTitle":[{"kind":"identifier","text":"addObjects:"}],"abstract":[{"text":"Adds ","type":"text"},{"code":"objects","type":"codeVoice"},{"type":"text","text":" to the receiver’s content collection."}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/add(contentsOf:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"contentsOf"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"title":"add(contentsOf:)"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(_:atArrangedObjectIndex:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insert"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"atArrangedObjectIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic","url":"/documentation/appkit/nsarraycontroller/insert(_:atarrangedobjectindex:)","navigatorTitle":[{"kind":"identifier","text":"insertObject:atArrangedObjectIndex:"}],"title":"insert(_:atArrangedObjectIndex:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(_:atArrangedObjectIndex:)","abstract":[{"text":"Inserts ","type":"text"},{"type":"codeVoice","code":"object"},{"type":"text","text":" into the receiver’s arranged objects array at the location specified by "},{"type":"codeVoice","code":"index"},{"type":"text","text":", and adds it to the receiver’s content collection."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(atArrangedObjectIndex:)":{"navigatorTitle":[{"kind":"identifier","text":"removeObjectAtArrangedObjectIndex:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atArrangedObjectIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(atArrangedObjectIndex:)","abstract":[{"type":"text","text":"Removes the object at the specified "},{"type":"codeVoice","code":"index"},{"type":"text","text":" in the receiver’s arranged objects from the receiver’s content array."}],"title":"remove(atArrangedObjectIndex:)","role":"symbol","type":"topic","url":"/documentation/appkit/nsarraycontroller/remove(atarrangedobjectindex:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController":{"role":"symbol","abstract":[{"type":"text","text":"A bindings-compatible controller that manages a collection of objects."}],"navigatorTitle":[{"kind":"identifier","text":"NSArrayController"}],"type":"topic","kind":"symbol","title":"NSArrayController","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController","url":"/documentation/appkit/nsarraycontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSArrayController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"removeObject:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeObject:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSArrayController"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"op":"replace","value":[{"anchor":"Adding-and-Removing-Objects","title":"Adding and Removing Objects","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSArrayController/addObject(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/add(contentsOf:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(_:atArrangedObjectIndex:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/insert(contentsOf:atArrangedObjectIndexes:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(atArrangedObjectIndex:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(atArrangedObjectIndexes:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/remove(contentsOf:)"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeObject:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"remove:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1remove(_:)/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1remove(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"remove:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1remove(atArrangedObjectIndexes:)/title","value":"removeObjectsAtArrangedObjectIndexes:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1remove(atArrangedObjectIndexes:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeObjectsAtArrangedObjectIndexes:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1remove(contentsOf:)/title","value":"removeObjects:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1remove(contentsOf:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeObjects:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1removeObject(_:)/title","value":"removeObject:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1removeObject(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeObject:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1addObject(_:)/title","value":"addObject:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1addObject(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addObject:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1insert(contentsOf:atArrangedObjectIndexes:)/title","value":"insertObjects:atArrangedObjectIndexes:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1insert(contentsOf:atArrangedObjectIndexes:)/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"insertObjects:atArrangedObjectIndexes:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1add(contentsOf:)/title","value":"addObjects:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1add(contentsOf:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addObjects:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1insert(_:atArrangedObjectIndex:)/title","value":"insertObject:atArrangedObjectIndex:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1insert(_:atArrangedObjectIndex:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertObject:atArrangedObjectIndex:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1remove(atArrangedObjectIndex:)/title","value":"removeObjectAtArrangedObjectIndex:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1remove(atArrangedObjectIndex:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeObjectAtArrangedObjectIndex:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/title","value":"NSArrayController"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/fragments","value":[{"kind":"identifier","text":"NSArrayController"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/navigatorTitle","value":[{"kind":"identifier","text":"NSArrayController"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}