{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionIndexes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"}],"roleHeading":"Instance Property","modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","beta":false,"deprecated":false,"unavailable":false}],"role":"symbol","externalID":"c:objc(cs)NSArrayController(py)selectionIndexes","symbolKind":"property","title":"selectionIndexes","navigatorTitle":[{"kind":"identifier","text":"selectionIndexes"}]},"seeAlsoSections":[{"title":"Managing selections","anchor":"Managing-selections","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectionIndex","doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectionIndex(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectsInsertedObjects","doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectionIndexes(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/addSelectionIndexes(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeSelectionIndexes(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectedObjects(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectedObjects","doc://com.apple.appkit/documentation/AppKit/NSArrayController/addSelectedObjects(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeSelectedObjects(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectNext(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/canSelectNext","doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectPrevious(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/canSelectPrevious"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"An index set containing the indexes of the receiver’s currently selected objects in the content array"}],"kind":"symbol","variants":[{"paths":["/documentation/appkit/nsarraycontroller/selectionindexes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsarraycontroller/selectionindexes"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectionIndexes","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSArrayController"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionIndexes","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property is observable using key-value observing."}]}],"kind":"content"}],"references":{"doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV":{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV","url":"/documentation/foundation/indexset","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"IndexSet"}],"kind":"symbol","type":"topic","title":"IndexSet","role":"symbol","abstract":[{"text":"A collection of unique integer values that represent the indexes of elements in another collection. ","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectedObjects(_:)":{"navigatorTitle":[{"text":"setSelectedObjects:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSelectedObjects","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Sets ","type":"text"},{"code":"objects","type":"codeVoice"},{"text":" as the receiver’s current selection, returning ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":" if the selection was changed.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectedObjects(_:)","kind":"symbol","url":"/documentation/appkit/nsarraycontroller/setselectedobjects(_:)","title":"setSelectedObjects(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectionIndexes":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectionIndexes","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionIndexes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"}],"title":"selectionIndexes","abstract":[{"type":"text","text":"An index set containing the indexes of the receiver’s currently selected objects in the content array"}],"navigatorTitle":[{"kind":"identifier","text":"selectionIndexes"}],"type":"topic","url":"/documentation/appkit/nsarraycontroller/selectionindexes"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectionIndex":{"type":"topic","title":"selectionIndex","role":"symbol","navigatorTitle":[{"text":"selectionIndex","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectionIndex","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","url":"/documentation/appkit/nsarraycontroller/selectionindex","abstract":[{"text":"The index of the first object in the receiver’s selection","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectedObjects":{"title":"selectedObjects","kind":"symbol","url":"/documentation/appkit/nsarraycontroller/selectedobjects","abstract":[{"text":"An array containing the receiver’s selected objects","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedObjects","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"navigatorTitle":[{"text":"selectedObjects","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectedObjects","type":"topic"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController":{"role":"symbol","abstract":[{"type":"text","text":"A bindings-compatible controller that manages a collection of objects."}],"navigatorTitle":[{"kind":"identifier","text":"NSArrayController"}],"type":"topic","kind":"symbol","title":"NSArrayController","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController","url":"/documentation/appkit/nsarraycontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSArrayController"}]},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/canSelectPrevious":{"type":"topic","title":"canSelectPrevious","role":"symbol","navigatorTitle":[{"text":"canSelectPrevious","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/canSelectPrevious","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSelectPrevious","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"/documentation/appkit/nsarraycontroller/canselectprevious","abstract":[{"text":"A Boolean value indicating whether the previous object, relative to the current selection, in the receiver’s content array can be selected","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectionIndex(_:)":{"kind":"symbol","title":"setSelectionIndex(_:)","url":"/documentation/appkit/nsarraycontroller/setselectionindex(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectionIndex(_:)","abstract":[{"type":"text","text":"Sets the receiver’s selection to the given index, and returns a Boolean value that indicates whether the selection was changed."}],"navigatorTitle":[{"kind":"identifier","text":"setSelectionIndex:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectionIndex"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectNext(_:)":{"url":"/documentation/appkit/nsarraycontroller/selectnext(_:)","title":"selectNext(_:)","type":"topic","navigatorTitle":[{"text":"selectNext:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectNext(_:)","abstract":[{"text":"Selects the next object, relative to the current selection, in the receiver’s arranged content.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectNext"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectionIndexes(_:)":{"title":"setSelectionIndexes(_:)","abstract":[{"text":"Sets the receiver’s selection indexes and returns a Boolean value that indicates whether the selection changed.","type":"text"}],"type":"topic","url":"/documentation/appkit/nsarraycontroller/setselectionindexes(_:)","navigatorTitle":[{"kind":"identifier","text":"setSelectionIndexes:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectionIndexes"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier","text":"IndexSet"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectionIndexes(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectPrevious(_:)":{"type":"topic","title":"selectPrevious(_:)","role":"symbol","navigatorTitle":[{"text":"selectPrevious:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectPrevious(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectPrevious","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"kind":"symbol","url":"/documentation/appkit/nsarraycontroller/selectprevious(_:)","abstract":[{"text":"Selects the previous object, relative to the current selection, in the receiver’s arranged content.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/addSelectionIndexes(_:)":{"type":"topic","title":"addSelectionIndexes(_:)","role":"symbol","navigatorTitle":[{"text":"addSelectionIndexes:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/addSelectionIndexes(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSelectionIndexes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","url":"/documentation/appkit/nsarraycontroller/addselectionindexes(_:)","abstract":[{"text":"Adds the objects at the specified indexes in the receiver’s content array to the current selection, returning ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"text":" if the selection was changed.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/canSelectNext":{"abstract":[{"text":"A Boolean value indicating whether the next object, relative to the current selection, in the receiver’s content array can be selected","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"canSelectNext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"canSelectNext","navigatorTitle":[{"text":"canSelectNext","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/canSelectNext","url":"/documentation/appkit/nsarraycontroller/canselectnext","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeSelectionIndexes(_:)":{"kind":"symbol","title":"removeSelectionIndexes(_:)","url":"/documentation/appkit/nsarraycontroller/removeselectionindexes(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeSelectionIndexes(_:)","abstract":[{"type":"text","text":"Removes the object as the specified "},{"type":"codeVoice","code":"indexes"},{"type":"text","text":" from the receiver’s current selection, returning "},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"type":"text","text":" if the selection was changed."}],"navigatorTitle":[{"text":"removeSelectionIndexes:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeSelectionIndexes"},{"kind":"text","text":"("},{"text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectsInsertedObjects":{"navigatorTitle":[{"text":"selectsInsertedObjects","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectsInsertedObjects","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"A Boolean value that indicates whether the receiver automatically selects inserted objects","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectsInsertedObjects","kind":"symbol","url":"/documentation/appkit/nsarraycontroller/selectsinsertedobjects","title":"selectsInsertedObjects","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/addSelectedObjects(_:)":{"type":"topic","title":"addSelectedObjects(_:)","role":"symbol","navigatorTitle":[{"text":"addSelectedObjects:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/addSelectedObjects(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSelectedObjects","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"/documentation/appkit/nsarraycontroller/addselectedobjects(_:)","abstract":[{"text":"Adds ","type":"text"},{"type":"codeVoice","code":"objects"},{"text":" from the receiver’s content array to the current selection, returning ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"text":" if the selection was changed.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeSelectedObjects(_:)":{"kind":"symbol","title":"removeSelectedObjects(_:)","url":"/documentation/appkit/nsarraycontroller/removeselectedobjects(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeSelectedObjects(_:)","abstract":[{"text":"Removes ","type":"text"},{"code":"objects","type":"codeVoice"},{"text":" from the receiver’s current selection, returning ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":" if the selection was changed.","type":"text"}],"navigatorTitle":[{"text":"removeSelectedObjects:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeSelectedObjects","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"unavailable":false,"name":"macOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"selectionIndexes","op":"replace","path":"/metadata/title"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"selectionIndexes"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSArrayController"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectionIndex","doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectionIndex(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectsInsertedObjects","doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectionIndexes(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/addSelectionIndexes(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeSelectionIndexes(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/setSelectedObjects(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectedObjects","doc://com.apple.appkit/documentation/AppKit/NSArrayController/addSelectedObjects(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/removeSelectedObjects(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectNext(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/canSelectNext","doc://com.apple.appkit/documentation/AppKit/NSArrayController/selectPrevious(_:)","doc://com.apple.appkit/documentation/AppKit/NSArrayController/canSelectPrevious"],"anchor":"Managing-selections","generated":true,"title":"Managing selections"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSIndexSet","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexSet"},{"text":" * ","kind":"text"},{"text":"selectionIndexes","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1setSelectedObjects(_:)/title","value":"setSelectedObjects:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1setSelectedObjects(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setSelectedObjects:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectionIndexes/title","value":"selectionIndexes","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectionIndexes/fragments","value":[{"text":"selectionIndexes","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectionIndex/title","value":"selectionIndex","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectionIndex/fragments","value":[{"text":"selectionIndex","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectedObjects/title","value":"selectedObjects","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectedObjects/fragments","value":[{"text":"selectedObjects","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/title","value":"NSArrayController","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/fragments","value":[{"text":"NSArrayController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/navigatorTitle","value":[{"kind":"identifier","text":"NSArrayController"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1canSelectPrevious/title","value":"canSelectPrevious","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1canSelectPrevious/fragments","value":[{"text":"canSelectPrevious","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1setSelectionIndex(_:)/title","value":"setSelectionIndex:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1setSelectionIndex(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSelectionIndex:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectNext(_:)/title","value":"selectNext:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectNext(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectNext:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1setSelectionIndexes(_:)/title","value":"setSelectionIndexes:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1setSelectionIndexes(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSelectionIndexes:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectPrevious(_:)/title","value":"selectPrevious:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectPrevious(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectPrevious:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1addSelectionIndexes(_:)/title","value":"addSelectionIndexes:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1addSelectionIndexes(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"addSelectionIndexes:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1canSelectNext/title","value":"canSelectNext","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1canSelectNext/fragments","value":[{"kind":"identifier","text":"canSelectNext"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1removeSelectionIndexes(_:)/title","value":"removeSelectionIndexes:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1removeSelectionIndexes(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeSelectionIndexes:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectsInsertedObjects/title","value":"selectsInsertedObjects","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1selectsInsertedObjects/fragments","value":[{"text":"selectsInsertedObjects","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1addSelectedObjects(_:)/title","value":"addSelectedObjects:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1addSelectedObjects(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addSelectedObjects:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1removeSelectedObjects(_:)/title","value":"removeSelectedObjects:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController~1removeSelectedObjects(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeSelectedObjects:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}