{
  "abstract": [
    {
      "text": "A ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIColor",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object used to color an element.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/color"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVColor(py)color",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "color"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIColor",
        "text": "UIColor"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "color"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "color"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "color"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIColor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIColor",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Only available when ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/colorType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColorType/plain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UIColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIColor",
      "type": "topic",
      "url": "/documentation/UIKit/UIColor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor": {
      "abstract": [
        {
          "text": "The color data used by styles.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVColor"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVColor"
        }
      ],
      "role": "symbol",
      "title": "TVColor",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvcolor"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/color": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/UIKit/UIColor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object used to color an element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvcolor/color"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/colorType": {
      "abstract": [
        {
          "text": "The color type for an element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVColorType",
          "text": "TVColorType"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/colorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorType"
        }
      ],
      "role": "symbol",
      "title": "colorType",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvcolor/colortype"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/gradientColors": {
      "abstract": [
        {
          "text": "An array of colors used to create a gradient for an element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientColors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/gradientColors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientColors"
        }
      ],
      "role": "symbol",
      "title": "gradientColors",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvcolor/gradientcolors"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/gradientPoints": {
      "abstract": [
        {
          "text": "An array of points used to determine gradient color changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientPoints"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/gradientPoints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientPoints"
        }
      ],
      "role": "symbol",
      "title": "gradientPoints",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvcolor/gradientpoints"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColorType": {
      "abstract": [
        {
          "text": "Designates how color for an element is to be displayed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVColorType"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVColorType"
        }
      ],
      "role": "symbol",
      "title": "TVColorType",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvcolortype"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColorType/plain": {
      "abstract": [
        {
          "text": "Indicates that a single color is to be used with an element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plain"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColorType/plain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVColorTypePlain"
        }
      ],
      "role": "symbol",
      "title": "TVColorType.plain",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvcolortype/plain"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIColor",
      "type": "topic",
      "url": "/documentation/UIKit/UIColor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Color-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/colorType",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColorType",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/gradientColors",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/gradientPoints"
      ],
      "title": "Getting Color Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "color"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Color-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/colorType",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColorType",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/gradientColors",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor/gradientPoints"
              ],
              "title": "Getting Color Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIColor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIColor",
                    "text": "UIColor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "color"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIColor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor~1colorType/title",
          "value": "colorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor~1colorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor~1gradientPoints/title",
          "value": "gradientPoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor~1gradientPoints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientPoints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIColor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColorType~1plain/title",
          "value": "TVColorTypePlain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColorType~1plain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVColorTypePlain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColorType/title",
          "value": "TVColorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVColorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVColorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor~1color/title",
          "value": "color"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor~1color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor~1gradientColors/title",
          "value": "gradientColors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor~1gradientColors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor/title",
          "value": "TVColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvcolor/color"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvcolor/color"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
