{"seeAlsoSections":[{"anchor":"Configuring-a-View","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNView/backgroundColor","doc://com.apple.scenekit/documentation/SceneKit/SCNView/rendersContinuously","doc://com.apple.scenekit/documentation/SceneKit/SCNView/antialiasingMode","doc://com.apple.scenekit/documentation/SceneKit/SCNAntialiasingMode"],"generated":true,"title":"Configuring a View"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredFramesPerSecond","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"SceneKit chooses an actual frame rate that is as close as possible to your preferred frame rate based on the capabilities of the screen the view is displayed on. The actual frame rate is usually a factor of the maximum refresh rate of the screen to provide a consistent frame rate. For example, if the maximum refresh rate of the screen is "},{"type":"codeVoice","code":"60"},{"type":"text","text":" frames per second, that is also the highest frame rate the view sets as the actual frame rate. However, if you ask for a lower frame rate, SceneKit might choose "},{"type":"codeVoice","code":"30"},{"type":"text","text":", "},{"type":"codeVoice","code":"20"},{"type":"text","text":", "},{"code":"15","type":"codeVoice"},{"text":" or some other factor to be the actual frame rate. For this reason, you want to choose a frame rate that your app can consistently maintain.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The default value is ","type":"text"},{"code":"60","type":"codeVoice"},{"text":" frames per second.","type":"text"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/scenekit/scnview/preferredframespersecond"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/scenekit/scnview/preferredframespersecond"]}],"abstract":[{"type":"text","text":"The animation frame rate that the view uses to render its scene."}],"identifier":{"url":"doc://com.apple.scenekit/documentation/SceneKit/SCNView/preferredFramesPerSecond","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"SceneKit"}],"title":"preferredFramesPerSecond","symbolKind":"property","navigatorTitle":[{"text":"preferredFramesPerSecond","kind":"identifier"}],"externalID":"c:objc(cs)SCNView(py)preferredFramesPerSecond","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"preferredFramesPerSecond","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"roleHeading":"Instance Property","platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false},{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.12","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNView"]]},"references":{"doc://com.apple.scenekit/documentation/SceneKit/SCNView/antialiasingMode":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNView/antialiasingMode","title":"antialiasingMode","abstract":[{"text":"The antialiasing mode used for rendering the view’s scene.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"antialiasingMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SCNAntialiasingMode","text":"SCNAntialiasingMode","kind":"typeIdentifier"}],"kind":"symbol","url":"/documentation/scenekit/scnview/antialiasingmode","type":"topic","navigatorTitle":[{"text":"antialiasingMode","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"url":"/documentation/Swift/MainActor","title":"MainActor","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","fragments":[{"kind":"attribute","text":"@globalActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"actor"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainActor"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNView":{"url":"/documentation/scenekit/scnview","role":"symbol","title":"SCNView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SCNView","kind":"identifier"}],"navigatorTitle":[{"text":"SCNView","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNView","abstract":[{"type":"text","text":"A view for displaying 3D SceneKit content."}],"kind":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNView/preferredFramesPerSecond":{"role":"symbol","kind":"symbol","title":"preferredFramesPerSecond","navigatorTitle":[{"kind":"identifier","text":"preferredFramesPerSecond"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredFramesPerSecond"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"/documentation/scenekit/scnview/preferredframespersecond","abstract":[{"text":"The animation frame rate that the view uses to render its scene.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNView/preferredFramesPerSecond"},"doc://com.externally.resolved.symbol/s:Si":{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"role":"symbol","title":"Int","type":"topic","abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","kind":"symbol","fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"role":"symbol","title":"NSInteger","type":"topic","abstract":[{"text":"Describes an integer.","type":"text"}],"url":"/documentation/objectivec/nsinteger"},"doc://com.apple.scenekit/documentation/SceneKit/SCNView/rendersContinuously":{"kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNView/rendersContinuously","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendersContinuously","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"rendersContinuously","navigatorTitle":[{"text":"rendersContinuously","kind":"identifier"}],"url":"/documentation/scenekit/scnview/renderscontinuously","abstract":[{"text":"A Boolean value that determines whether the view always renders at its preferred frame rate or only when its visible content changes.","type":"text"}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNAntialiasingMode":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNAntialiasingMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNAntialiasingMode","kind":"identifier"}],"url":"/documentation/scenekit/scnantialiasingmode","navigatorTitle":[{"text":"SCNAntialiasingMode","kind":"identifier"}],"abstract":[{"text":"Modes for antialiased rendering of the view’s scene, used by the ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNView","isActive":true,"type":"reference"},{"text":" property.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"SCNAntialiasingMode"},"doc://com.apple.scenekit/documentation/SceneKit/SCNView/backgroundColor":{"role":"symbol","navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}],"title":"backgroundColor","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNView/backgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSColor","preciseIdentifier":"c:objc(cs)NSColor","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/scenekit/scnview/backgroundcolor","abstract":[{"text":"The background color of the view.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"introducedAt":"10.12","beta":false,"name":"macOS","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"preferredFramesPerSecond","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"preferredFramesPerSecond"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNView"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Configuring-a-View","title":"Configuring a View","generated":true,"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNView/backgroundColor","doc://com.apple.scenekit/documentation/SceneKit/SCNView/rendersContinuously","doc://com.apple.scenekit/documentation/SceneKit/SCNView/antialiasingMode","doc://com.apple.scenekit/documentation/SceneKit/SCNAntialiasingMode"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"preferredFramesPerSecond","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"antialiasingMode","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1antialiasingMode/title"},{"op":"replace","value":[{"text":"antialiasingMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1antialiasingMode/fragments"},{"op":"replace","value":"SCNView","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/title"},{"op":"replace","value":[{"kind":"identifier","text":"SCNView"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/fragments"},{"op":"replace","value":[{"text":"SCNView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/navigatorTitle"},{"op":"replace","value":"preferredFramesPerSecond","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1preferredFramesPerSecond/title"},{"op":"replace","value":[{"kind":"identifier","text":"preferredFramesPerSecond"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1preferredFramesPerSecond/fragments"},{"value":"rendersContinuously","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1rendersContinuously/title","op":"replace"},{"value":[{"text":"rendersContinuously","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1rendersContinuously/fragments","op":"replace"},{"value":"SCNAntialiasingMode","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAntialiasingMode/title","op":"replace"},{"op":"replace","value":[{"text":"SCNAntialiasingMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAntialiasingMode/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SCNAntialiasingMode"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAntialiasingMode/navigatorTitle"},{"op":"replace","value":"backgroundColor","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1backgroundColor/title"},{"op":"replace","value":[{"kind":"identifier","text":"backgroundColor"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1backgroundColor/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}