{
  "abstract": [
    {
      "text": "The name of the symbol to show in the action sheet, and in Finder’s sidebar on macOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundlePrimaryIcon"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundlePrimaryIcon/CFBundleSymbolName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.CFBundleIcons.CFBundlePrimaryIcon.CFBundleSymbolName",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFBundleSymbolName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "CFBundleSymbolName"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "CFBundleSymbolName",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system associates the given symbol with your application. The system displays the symbol in the following locations:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The action sheet displayed by an Action extension",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The Finder sidebar icons for file provider domains (macOS only)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To use a symbol from SF Symbols as the icon, set the value of ",
              "type": "text"
            },
            {
              "code": "CFBundleSymbolName",
              "type": "codeVoice"
            },
            {
              "text": " to the symbol’s name. For example, to use the ",
              "type": "text"
            },
            {
              "code": "flame.fill",
              "type": "codeVoice"
            },
            {
              "text": " symbol, configure the ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " entry as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3922506",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The resulting item shown on the action sheet looks like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3922500",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the Finder sidebar, it looks like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3922503",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To create a custom symbol for your app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/creating-custom-symbol-images-for-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons": {
      "abstract": [
        {
          "text": "Information about all of the icons used by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon files (iOS 5)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
      "kind": "symbol",
      "name": "CFBundleIcons",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIcons"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIcons",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleicons"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundlePrimaryIcon": {
      "abstract": [
        {
          "text": "The app’s primary icon for display on the Home Screen, in the Settings app, and many other places throughout the system.",
          "type": "text"
        }
      ],
      "ideTitle": "Primary Icon",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundlePrimaryIcon",
      "kind": "symbol",
      "name": "CFBundlePrimaryIcon",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundlePrimaryIcon"
        }
      ],
      "role": "symbol",
      "title": "CFBundlePrimaryIcon",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleicons/cfbundleprimaryicon"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundlePrimaryIcon/CFBundleSymbolName": {
      "abstract": [
        {
          "text": "The name of the symbol to show in the action sheet, and in Finder’s sidebar on macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundlePrimaryIcon/CFBundleSymbolName",
      "kind": "symbol",
      "name": "CFBundleSymbolName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleSymbolName"
        }
      ],
      "role": "symbol",
      "title": "CFBundleSymbolName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleicons/cfbundleprimaryicon/cfbundlesymbolname"
    },
    "doc://com.apple.documentation/documentation/UIKit/creating-custom-symbol-images-for-your-app": {
      "abstract": [
        {
          "text": "Create, organize, and annotate symbol images using SF Symbols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/creating-custom-symbol-images-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Creating custom symbol images for your app",
      "type": "topic",
      "url": "/documentation/UIKit/creating-custom-symbol-images-for-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3922500": {
      "alt": "A screenshot of an action sheet entry showing an icon using the flame.fill SF symbol. ",
      "identifier": "media-3922500",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/f41a44e4f9c9c0a0c795419e053c51d5/media-3922500@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/637d6ff5161feb8c7f8e5e9281870eaf/media-3922500~dark@2x.png"
        }
      ]
    },
    "media-3922503": {
      "alt": "A screenshot of Finder, showing the flame.fill SF Symbol in the sidebar.",
      "identifier": "media-3922503",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8e0e0619fbcd52ede58c91e91651f10a/media-3922503@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a8d149e09c949f943cf7eda323f7f23e/media-3922503~dark@2x.png"
        }
      ]
    },
    "media-3922506": {
      "alt": "Screenshot showing the Icon files portion of an Info.plist file containing a primary icon entry with CFBundleSymbolName inside of that. The value of CFBundleSymbolName is a string containing the value “flame.fill”.",
      "identifier": "media-3922506",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e4d78c51f9e1de416e600af1a7f130c5/media-3922506@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/61d5b8dc3d3e346957469c503fec8089/media-3922506~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFBundleSymbolName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleSymbolName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundlePrimaryIcon"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundlePrimaryIcon/title",
          "value": "CFBundlePrimaryIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundlePrimaryIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundlePrimaryIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundlePrimaryIcon~1CFBundleSymbolName/title",
          "value": "CFBundleSymbolName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundlePrimaryIcon~1CFBundleSymbolName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleSymbolName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons/title",
          "value": "CFBundleIcons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIcons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/cfbundleicons/cfbundleprimaryicon/cfbundlesymbolname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/cfbundleicons/cfbundleprimaryicon/cfbundlesymbolname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
