{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticSpellingCorrectionEnabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSSpellChecker(cpy)automaticSpellingCorrectionEnabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isAutomaticSpellingCorrectionEnabled"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "automaticSpellingCorrectionEnabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "isAutomaticSpellingCorrectionEnabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isAutomaticSpellingCorrectionEnabled"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker": {
      "abstract": [
        {
          "text": "An interface to the Cocoa spell-checking service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSpellChecker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpellChecker"
        }
      ],
      "role": "symbol",
      "title": "NSSpellChecker",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticCapitalizationNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeAutomaticCapitalizationNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticCapitalizationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpellCheckerDidChangeAutomaticCapitalizationNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeAutomaticCapitalizationNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/didchangeautomaticcapitalizationnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticDashSubstitutionNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeAutomaticDashSubstitutionNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticDashSubstitutionNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpellCheckerDidChangeAutomaticDashSubstitutionNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeAutomaticDashSubstitutionNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/didchangeautomaticdashsubstitutionnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticPeriodSubstitutionNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeAutomaticPeriodSubstitutionNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticPeriodSubstitutionNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpellCheckerDidChangeAutomaticPeriodSubstitutionNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeAutomaticPeriodSubstitutionNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/didchangeautomaticperiodsubstitutionnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticQuoteSubstitutionNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeAutomaticQuoteSubstitutionNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticQuoteSubstitutionNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpellCheckerDidChangeAutomaticQuoteSubstitutionNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeAutomaticQuoteSubstitutionNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/didchangeautomaticquotesubstitutionnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticTextCompletionNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeAutomaticTextCompletionNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticTextCompletionNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpellCheckerDidChangeAutomaticTextCompletionNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeAutomaticTextCompletionNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/didchangeautomatictextcompletionnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticCapitalizationEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticCapitalizationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticCapitalizationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticCapitalizationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticCapitalizationEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/isautomaticcapitalizationenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticDashSubstitutionEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticDashSubstitutionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticDashSubstitutionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticDashSubstitutionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticDashSubstitutionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/isautomaticdashsubstitutionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticInlinePredictionEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticInlinePredictionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticInlinePredictionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticInlinePredictionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticInlinePredictionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/isautomaticinlinepredictionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticPeriodSubstitutionEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticPeriodSubstitutionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticPeriodSubstitutionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticPeriodSubstitutionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticPeriodSubstitutionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/isautomaticperiodsubstitutionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticQuoteSubstitutionEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticQuoteSubstitutionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticQuoteSubstitutionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticQuoteSubstitutionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticQuoteSubstitutionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/isautomaticquotesubstitutionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticSpellingCorrectionEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticSpellingCorrectionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticSpellingCorrectionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticSpellingCorrectionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticSpellingCorrectionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/isautomaticspellingcorrectionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticTextCompletionEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticTextCompletionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticTextCompletionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticTextCompletionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticTextCompletionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/isautomatictextcompletionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticTextReplacementEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticTextReplacementEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticTextReplacementEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticTextReplacementEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticTextReplacementEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/isautomatictextreplacementenabled"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticCapitalizationNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticDashSubstitutionNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticPeriodSubstitutionNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticQuoteSubstitutionNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticTextCompletionNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticCapitalizationEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticDashSubstitutionEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticInlinePredictionEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticPeriodSubstitutionEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticQuoteSubstitutionEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticTextCompletionEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticTextReplacementEnabled"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "automaticSpellingCorrectionEnabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticSpellingCorrectionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticCapitalizationNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticDashSubstitutionNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticPeriodSubstitutionNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticQuoteSubstitutionNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticTextCompletionNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticCapitalizationEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticDashSubstitutionEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticInlinePredictionEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticPeriodSubstitutionEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticQuoteSubstitutionEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticTextCompletionEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/isAutomaticTextReplacementEnabled"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "getter"
                  },
                  {
                    "kind": "text",
                    "text": "="
                  },
                  {
                    "kind": "identifier",
                    "text": "isAutomaticSpellingCorrectionEnabled"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "automaticSpellingCorrectionEnabled"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticInlinePredictionEnabled/title",
          "value": "automaticInlinePredictionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticInlinePredictionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticInlinePredictionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker/title",
          "value": "NSSpellChecker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpellChecker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpellChecker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticQuoteSubstitutionEnabled/title",
          "value": "automaticQuoteSubstitutionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticQuoteSubstitutionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticQuoteSubstitutionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticSpellingCorrectionEnabled/title",
          "value": "automaticSpellingCorrectionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticSpellingCorrectionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticSpellingCorrectionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticTextReplacementEnabled/title",
          "value": "automaticTextReplacementEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticTextReplacementEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticTextReplacementEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticCapitalizationNotification/title",
          "value": "NSSpellCheckerDidChangeAutomaticCapitalizationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticCapitalizationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpellCheckerDidChangeAutomaticCapitalizationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticDashSubstitutionNotification/title",
          "value": "NSSpellCheckerDidChangeAutomaticDashSubstitutionNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticDashSubstitutionNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpellCheckerDidChangeAutomaticDashSubstitutionNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticTextCompletionEnabled/title",
          "value": "automaticTextCompletionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticTextCompletionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticTextCompletionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticCapitalizationEnabled/title",
          "value": "automaticCapitalizationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticCapitalizationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticCapitalizationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticPeriodSubstitutionEnabled/title",
          "value": "automaticPeriodSubstitutionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticPeriodSubstitutionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticPeriodSubstitutionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticPeriodSubstitutionNotification/title",
          "value": "NSSpellCheckerDidChangeAutomaticPeriodSubstitutionNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticPeriodSubstitutionNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpellCheckerDidChangeAutomaticPeriodSubstitutionNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticTextCompletionNotification/title",
          "value": "NSSpellCheckerDidChangeAutomaticTextCompletionNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticTextCompletionNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpellCheckerDidChangeAutomaticTextCompletionNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticQuoteSubstitutionNotification/title",
          "value": "NSSpellCheckerDidChangeAutomaticQuoteSubstitutionNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticQuoteSubstitutionNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpellCheckerDidChangeAutomaticQuoteSubstitutionNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticDashSubstitutionEnabled/title",
          "value": "automaticDashSubstitutionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1isAutomaticDashSubstitutionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticDashSubstitutionEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsspellchecker/isautomaticspellingcorrectionenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsspellchecker/isautomaticspellingcorrectionenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
