{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency",
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager",
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/init(rawValue:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So36ATTrackingManagerAuthorizationStatusV8rawValueABSgSu_tcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "rawValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Su",
        "text": "UInt"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "App Tracking Transparency"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(rawValue:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "rawValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Su",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Su",
              "text": "UInt"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency": {
      "abstract": [
        {
          "text": "Request user authorization to access app-related data for tracking the user or the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency",
      "kind": "symbol",
      "role": "collection",
      "title": "App Tracking Transparency",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager": {
      "abstract": [
        {
          "text": "A class that provides a tracking authorization request and the tracking",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "authorization status of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ATTrackingManager"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATTrackingManager"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus": {
      "abstract": [
        {
          "text": "The status values for app tracking authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus/init(rawvalue:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Su": {
      "abstract": [
        {
          "text": "An unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Su",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt",
      "type": "topic",
      "url": "/documentation/Swift/UInt"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/title",
          "value": "ATTrackingManagerAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/title",
          "value": "ATTrackingManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus/init(rawvalue:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
