{
  "abstract": [
    {
      "text": "The value that returns if authorization to access app-related data for",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "tracking the user or the device has a restricted status.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency",
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager",
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/restricted"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ATTrackingManagerAuthorizationStatus@ATTrackingManagerAuthorizationStatusRestricted",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "restricted"
      }
    ],
    "modules": [
      {
        "name": "App Tracking Transparency"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ATTrackingManagerAuthorizationStatusRestricted"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ATTrackingManager.AuthorizationStatus.restricted"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "restricted"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A restricted condition means the device does not prompt for tracking",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "authorization when",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is called, nor is it displayed when the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is triggered. Also, on restricted devices, the Allow Apps To Request To",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Track setting is disabled and cannot be changed. This setting allows",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "users to opt in or out of allowing apps to request user consent to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "access app-related data that can be used for tracking the user or the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency": {
      "abstract": [
        {
          "text": "Request user authorization to access app-related data for tracking the user or the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency",
      "kind": "symbol",
      "role": "collection",
      "title": "App Tracking Transparency",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager": {
      "abstract": [
        {
          "text": "A class that provides a tracking authorization request and the tracking",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "authorization status of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ATTrackingManager"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATTrackingManager"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus": {
      "abstract": [
        {
          "text": "The status values for app tracking authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/authorized": {
      "abstract": [
        {
          "text": "The value that returns if the user authorizes access to app-related data for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "tracking the user or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATTrackingManagerAuthorizationStatusAuthorized"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus.authorized",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus/authorized"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/denied": {
      "abstract": [
        {
          "text": "The value that returns if the user denies authorization to access",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "app-related data for tracking the user or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATTrackingManagerAuthorizationStatusDenied"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus.denied",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus/denied"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/notDetermined": {
      "abstract": [
        {
          "text": "The value that returns when the app can’t determine the user’s",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "authorization status for access to app-related data for tracking the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "user or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATTrackingManagerAuthorizationStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus.notDetermined",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus/notdetermined"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/restricted": {
      "abstract": [
        {
          "text": "The value that returns if authorization to access app-related data for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "tracking the user or the device has a restricted status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATTrackingManagerAuthorizationStatusRestricted"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus.restricted",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus/restricted"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)": {
      "abstract": [
        {
          "text": "The request for user authorization to access app-related data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestTrackingAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ATTrackingManager",
          "text": "ATTrackingManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
          "text": "AuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestTrackingAuthorizationWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestTrackingAuthorization(completionHandler:)",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/requesttrackingauthorization(completionhandler:)"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription": {
      "abstract": [
        {
          "text": "A message that informs the user why an app is requesting permission to use data for tracking the user or the device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserTrackingUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/authorized",
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/denied",
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/notDetermined"
      ],
      "title": "Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ATTrackingManagerAuthorizationStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatusRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency",
                "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/authorized",
                "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/denied",
                "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/notDetermined"
              ],
              "title": "Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ATTrackingManagerAuthorizationStatusRestricted"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1restricted/title",
          "value": "ATTrackingManagerAuthorizationStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatusRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1requestTrackingAuthorization(completionHandler:)/title",
          "value": "requestTrackingAuthorizationWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1requestTrackingAuthorization(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestTrackingAuthorizationWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1denied/title",
          "value": "ATTrackingManagerAuthorizationStatusDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/title",
          "value": "ATTrackingManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1notDetermined/title",
          "value": "ATTrackingManagerAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1authorized/title",
          "value": "ATTrackingManagerAuthorizationStatusAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatusAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/title",
          "value": "ATTrackingManagerAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus/restricted"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus/restricted"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
