{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/SetAlgebra-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SetAlgebra Implementations"
  },
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSCompleteIOFlags"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSCompleteIOFlags"
        }
      ],
      "role": "symbol",
      "title": "FSCompleteIOFlags",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new set from a finite sequence of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags/init(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/init(arrayLiteral:)": {
      "abstract": [
        {
          "text": "Creates a set containing the elements of the given array literal.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "ArrayLiteralElement",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "arrayLiteral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "...)"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/init(arrayLiteral:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(arrayLiteral:)",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags/init(arrayliteral:)"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isDisjoint(with:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the set has no members in",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "common with the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDisjoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isDisjoint(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isDisjoint(with:)",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags/isdisjoint(with:)"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isEmpty": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the set has no elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isEmpty",
      "kind": "symbol",
      "role": "symbol",
      "title": "isEmpty",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags/isempty"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isStrictSubset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether this set is a strict",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "subset of the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isStrictSubset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isStrictSubset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isStrictSubset(of:)",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags/isstrictsubset(of:)"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isStrictSuperset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether this set is a strict",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "superset of the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isStrictSuperset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isStrictSuperset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isStrictSuperset(of:)",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags/isstrictsuperset(of:)"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isSubset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the set is a subset of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "another set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSubset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isSubset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSubset(of:)",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags/issubset(of:)"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isSuperset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the set is a superset of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSuperset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isSuperset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSuperset(of:)",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags/issuperset(of:)"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/subtract(_:)": {
      "abstract": [
        {
          "text": "Removes the elements of the given set from this set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/subtract(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtract(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags/subtract(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/subtracting(_:)": {
      "abstract": [
        {
          "text": "Returns a new set containing the elements of this set that do not occur",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "in the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtracting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/subtracting(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtracting(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags/subtracting(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/init(_:)",
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/init(arrayLiteral:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isEmpty"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isDisjoint(with:)",
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isStrictSubset(of:)",
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isStrictSuperset(of:)",
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isSubset(of:)",
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/isSuperset(of:)",
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/subtract(_:)",
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags/subtracting(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSCompleteIOFlags/title",
          "value": "FSCompleteIOFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSCompleteIOFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSCompleteIOFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSCompleteIOFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSCompleteIOFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fscompleteioflags/setalgebra-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
