{
  "abstract": [
    {
      "text": "Creates a new filter by using the playback style you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/playbackStyle(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8PhotosUI14PHPickerFilterV13playbackStyleyACSo015PHAssetPlaybackF0VFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "playbackStyle"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PHAsset",
        "text": "PHAsset"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PHAssetPlaybackStyle",
        "text": "PlaybackStyle"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
        "text": "PHPickerFilter"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "playbackStyle(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "playbackStyle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "playbackStyle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PHAsset",
              "text": "PHAsset"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/PlaybackStyle-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PHAssetPlaybackStyle",
              "text": "PlaybackStyle"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
              "text": "PHPickerFilter"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The asset playback style.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "playbackStyle"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new filter with the playback style you specify.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset": {
      "abstract": [
        {
          "text": "A representation of an image, video, or Live Photo in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "role": "symbol",
      "title": "PHAsset",
      "type": "topic",
      "url": "/documentation/photos/phasset"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/PlaybackStyle-swift.enum": {
      "abstract": [
        {
          "text": "An enumeration of asset playback styles that dictate how to present an asset to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PlaybackStyle"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/PlaybackStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PlaybackStyle"
        }
      ],
      "role": "symbol",
      "title": "PHAsset.PlaybackStyle",
      "type": "topic",
      "url": "/documentation/photos/phasset/playbackstyle-swift.enum"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct": {
      "abstract": [
        {
          "text": "A type that defines the filter to apply to the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "role": "symbol",
      "title": "PHPickerFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/all(of:)": {
      "abstract": [
        {
          "text": "Creates a new filter that includes only the filters you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/all(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "all(of:)",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/all(of:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/not(_:)": {
      "abstract": [
        {
          "text": "Creates a new filter that excludes the filter you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "not"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/not(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "not(_:)",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/not(_:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/playbackStyle(_:)": {
      "abstract": [
        {
          "text": "Creates a new filter by using the playback style you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackStyle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetPlaybackStyle",
          "text": "PlaybackStyle"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/playbackStyle(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "playbackStyle(_:)",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/playbackstyle(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Filters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/all(of:)",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/not(_:)"
      ],
      "title": "Creating Filters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1PlaybackStyle-swift.enum/title",
          "value": "PHAssetPlaybackStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1PlaybackStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetPlaybackStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1PlaybackStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetPlaybackStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title",
          "value": "PHAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phpickerfilter-swift.struct/playbackstyle(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
