{
  "abstract": [
    {
      "text": "The beacon interval (ms) for the network.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/beaconInterval"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CWNetwork(py)beaconInterval",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "beaconInterval"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "beaconInterval"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "beaconInterval"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "beaconInterval"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork": {
      "abstract": [
        {
          "text": "Encapsulates an IEEE 802.11 network, providing read-only accessors to various properties of the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWNetwork"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWNetwork"
        }
      ],
      "role": "symbol",
      "title": "CWNetwork",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/beaconInterval": {
      "abstract": [
        {
          "text": "The beacon interval (ms) for the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beaconInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/beaconInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beaconInterval"
        }
      ],
      "role": "symbol",
      "title": "beaconInterval",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork/beaconinterval"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/bssid": {
      "abstract": [
        {
          "text": "The basic service set identifier (BSSID) for the network, returned as UTF-8 string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bssid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/bssid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bssid"
        }
      ],
      "role": "symbol",
      "title": "bssid",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork/bssid"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/countryCode": {
      "abstract": [
        {
          "text": "The country code (ISO/IEC 3166-1:1997) for the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "countryCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/countryCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "countryCode"
        }
      ],
      "role": "symbol",
      "title": "countryCode",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork/countrycode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ibss": {
      "abstract": [
        {
          "text": "The network is an IBSS network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ibss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ibss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ibss"
        }
      ],
      "role": "symbol",
      "title": "ibss",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork/ibss"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/informationElementData": {
      "abstract": [
        {
          "text": "Information element data included in beacon or probe response frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "informationElementData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/informationElementData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "informationElementData"
        }
      ],
      "role": "symbol",
      "title": "informationElementData",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork/informationelementdata"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/noiseMeasurement": {
      "abstract": [
        {
          "text": "The aggregate noise measurement (dBm) for the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noiseMeasurement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/noiseMeasurement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "noiseMeasurement"
        }
      ],
      "role": "symbol",
      "title": "noiseMeasurement",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork/noisemeasurement"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/rssiValue": {
      "abstract": [
        {
          "text": "The aggregate received signal strength indication (RSSI) measurement (dBm) for the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rssiValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/rssiValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rssiValue"
        }
      ],
      "role": "symbol",
      "title": "rssiValue",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork/rssivalue"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ssid": {
      "abstract": [
        {
          "text": "The service set identifier (SSID) for the network, encoded as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ssid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ssid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ssid"
        }
      ],
      "role": "symbol",
      "title": "ssid",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork/ssid"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ssidData": {
      "abstract": [
        {
          "text": "The service set identifier (SSID) for the network, returned as data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ssidData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ssidData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ssidData"
        }
      ],
      "role": "symbol",
      "title": "ssidData",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork/ssiddata"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/wlanChannel": {
      "abstract": [
        {
          "text": "The channel for the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wlanChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CWChannel",
          "text": "CWChannel"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/wlanChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wlanChannel"
        }
      ],
      "role": "symbol",
      "title": "wlanChannel",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork/wlanchannel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/bssid",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/countryCode",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ibss",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/informationElementData",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/noiseMeasurement",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/rssiValue",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ssid",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ssidData",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/wlanChannel"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "beaconInterval"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beaconInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/bssid",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/countryCode",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ibss",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/informationElementData",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/noiseMeasurement",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/rssiValue",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ssid",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/ssidData",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork/wlanChannel"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "beaconInterval"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1beaconInterval/title",
          "value": "beaconInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1beaconInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beaconInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1wlanChannel/title",
          "value": "wlanChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1wlanChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wlanChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1bssid/title",
          "value": "bssid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1bssid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bssid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1informationElementData/title",
          "value": "informationElementData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1informationElementData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "informationElementData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1countryCode/title",
          "value": "countryCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1countryCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "countryCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1ssidData/title",
          "value": "ssidData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1ssidData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ssidData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1ssid/title",
          "value": "ssid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1ssid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ssid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1rssiValue/title",
          "value": "rssiValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1rssiValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rssiValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1ibss/title",
          "value": "ibss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1ibss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ibss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1noiseMeasurement/title",
          "value": "noiseMeasurement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork~1noiseMeasurement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "noiseMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork/title",
          "value": "CWNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWNetwork"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwnetwork/beaconinterval"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwnetwork/beaconinterval"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
