{
  "abstract": [
    {
      "text": "The size of the font used in the label.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontSize"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKLabelNode(py)fontSize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fontSize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "fontSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "fontSize"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fontSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fontSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.spritekit/documentation/SpriteKit/adding-text-to-a-scene"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default font size is 32 points.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode": {
      "abstract": [
        {
          "text": "A graphical element that draws text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKLabelNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelNode"
        }
      ],
      "role": "symbol",
      "title": "SKLabelNode",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontColor": {
      "abstract": [
        {
          "text": "The color of the label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontColor"
        }
      ],
      "role": "symbol",
      "title": "fontColor",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelnode/fontcolor"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontName": {
      "abstract": [
        {
          "text": "The font used for the text in the label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontName"
        }
      ],
      "role": "symbol",
      "title": "fontName",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelnode/fontname"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontSize": {
      "abstract": [
        {
          "text": "The size of the font used in the label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontSize"
        }
      ],
      "role": "symbol",
      "title": "fontSize",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelnode/fontsize"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/adding-text-to-a-scene": {
      "abstract": [
        {
          "text": "Draw text in your scene, such as a health indicator or a “Game Over” banner, by using a label node.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/adding-text-to-a-scene",
      "kind": "article",
      "role": "article",
      "title": "Adding Text to a Scene",
      "type": "topic",
      "url": "/documentation/spritekit/adding-text-to-a-scene"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-a-Labels-Font",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontColor",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontName"
      ],
      "title": "Specifying a Label’s Font"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "fontSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fontSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-a-Labels-Font",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontColor",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/fontName"
              ],
              "title": "Specifying a Label’s Font"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "fontSize"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode/title",
          "value": "SKLabelNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode~1fontName/title",
          "value": "fontName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode~1fontName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fontName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode~1fontSize/title",
          "value": "fontSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode~1fontSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fontSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode~1fontColor/title",
          "value": "fontColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode~1fontColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fontColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/sklabelnode/fontsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/sklabelnode/fontsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
