{
  "abstract": [
    {
      "text": "The vertical position of the text within the node.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/verticalAlignmentMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKLabelNode(py)verticalAlignmentMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "verticalAlignmentMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SKLabelVerticalAlignmentMode",
        "text": "SKLabelVerticalAlignmentMode"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "verticalAlignmentMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "verticalAlignmentMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "verticalAlignmentMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SKLabelVerticalAlignmentMode",
              "text": "SKLabelVerticalAlignmentMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "verticalAlignmentMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SKLabelVerticalAlignmentMode",
              "text": "SKLabelVerticalAlignmentMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.spritekit/documentation/SpriteKit/adding-text-to-a-scene"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The possible values for this property are listed in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The default value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/baseline",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelHorizontalAlignmentMode": {
      "abstract": [
        {
          "text": "Options for aligning text horizontally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKLabelHorizontalAlignmentMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelHorizontalAlignmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelHorizontalAlignmentMode"
        }
      ],
      "role": "symbol",
      "title": "SKLabelHorizontalAlignmentMode",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelhorizontalalignmentmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode": {
      "abstract": [
        {
          "text": "A graphical element that draws text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKLabelNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelNode"
        }
      ],
      "role": "symbol",
      "title": "SKLabelNode",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/horizontalAlignmentMode": {
      "abstract": [
        {
          "text": "The horizontal position of the text within the node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalAlignmentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKLabelHorizontalAlignmentMode",
          "text": "SKLabelHorizontalAlignmentMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/horizontalAlignmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "horizontalAlignmentMode"
        }
      ],
      "role": "symbol",
      "title": "horizontalAlignmentMode",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelnode/horizontalalignmentmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/verticalAlignmentMode": {
      "abstract": [
        {
          "text": "The vertical position of the text within the node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalAlignmentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKLabelVerticalAlignmentMode",
          "text": "SKLabelVerticalAlignmentMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/verticalAlignmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verticalAlignmentMode"
        }
      ],
      "role": "symbol",
      "title": "verticalAlignmentMode",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelnode/verticalalignmentmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode": {
      "abstract": [
        {
          "text": "Options for aligning text vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentMode"
        }
      ],
      "role": "symbol",
      "title": "SKLabelVerticalAlignmentMode",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelverticalalignmentmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/baseline": {
      "abstract": [
        {
          "text": "Positions the text so that the font’s baseline lies on the node’s origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseline"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/baseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentModeBaseline"
        }
      ],
      "role": "symbol",
      "title": "SKLabelVerticalAlignmentMode.baseline",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelverticalalignmentmode/baseline"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/adding-text-to-a-scene": {
      "abstract": [
        {
          "text": "Draw text in your scene, such as a health indicator or a “Game Over” banner, by using a label node.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/adding-text-to-a-scene",
      "kind": "article",
      "role": "article",
      "title": "Adding Text to a Scene",
      "type": "topic",
      "url": "/documentation/spritekit/adding-text-to-a-scene"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Controlling-a-Labels-Alignment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/horizontalAlignmentMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelHorizontalAlignmentMode"
      ],
      "title": "Controlling a Label’s Alignment"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "verticalAlignmentMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Controlling-a-Labels-Alignment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode/horizontalAlignmentMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelHorizontalAlignmentMode"
              ],
              "title": "Controlling a Label’s Alignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@SKLabelVerticalAlignmentMode",
                    "text": "SKLabelVerticalAlignmentMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "verticalAlignmentMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode~1verticalAlignmentMode/title",
          "value": "verticalAlignmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode~1verticalAlignmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode/title",
          "value": "SKLabelVerticalAlignmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode~1baseline/title",
          "value": "SKLabelVerticalAlignmentModeBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode~1baseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentModeBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode~1horizontalAlignmentMode/title",
          "value": "horizontalAlignmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode~1horizontalAlignmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "horizontalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelHorizontalAlignmentMode/title",
          "value": "SKLabelHorizontalAlignmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelHorizontalAlignmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelHorizontalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelHorizontalAlignmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelHorizontalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode/title",
          "value": "SKLabelNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelNode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/sklabelnode/verticalalignmentmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/sklabelnode/verticalalignmentmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
