{
  "abstract": [
    {
      "text": "A collection of properties that explains your app’s need to observe the user’s heart rate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSSensorKitUsageDetail.SRSensorUsageHeartRate",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRSensorUsageHeartRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "SRSensorUsageHeartRate"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "SRSensorUsageHeartRate",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key is a possible member of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail": {
      "abstract": [
        {
          "text": "A dictionary that includes keys for the specific information your app collects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail",
      "kind": "symbol",
      "name": "NSSensorKitUsageDetail",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSensorKitUsageDetail"
        }
      ],
      "role": "symbol",
      "title": "NSSensorKitUsageDetail",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageECG": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the person’s electrocardiogram sensor data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageECG",
      "kind": "symbol",
      "name": "SRSensorUsageECG",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageECG"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageECG",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageecg"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageElevation": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the device’s elevation data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageElevation",
      "kind": "symbol",
      "name": "SRSensorUsageElevation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageElevation"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageElevation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageelevation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageFacialMetrics": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the user’s facial expressions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageFacialMetrics",
      "kind": "symbol",
      "name": "SRSensorUsageFacialMetrics",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageFacialMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageFacialMetrics",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagefacialmetrics"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the user’s heart rate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate",
      "kind": "symbol",
      "name": "SRSensorUsageHeartRate",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageHeartRate"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageHeartRate",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageheartrate"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate/Description": {
      "abstract": [
        {
          "text": "An explanatory string that details the manner in which your study uses the sensor’s data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate/Description",
      "kind": "symbol",
      "name": "Description",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Description"
        }
      ],
      "role": "symbol",
      "title": "Description",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageheartrate/description"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate/Required": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app’s study relies on this sensor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate/Required",
      "kind": "symbol",
      "name": "Required",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Required"
        }
      ],
      "role": "symbol",
      "title": "Required",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageheartrate/required"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMediaEvents": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the user’s interactions with media, such as images and videos, in messaging apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMediaEvents",
      "kind": "symbol",
      "name": "SRSensorUsageMediaEvents",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageMediaEvents"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageMediaEvents",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagemediaevents"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMotion": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe motion data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMotion",
      "kind": "symbol",
      "name": "SRSensorUsageMotion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageMotion"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageMotion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagemotion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageOdometer": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the user’s odometer data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageOdometer",
      "kind": "symbol",
      "name": "SRSensorUsageOdometer",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageOdometer"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageOdometer",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageodometer"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePPG": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the person’s photoplethysmogram sensor data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePPG",
      "kind": "symbol",
      "name": "SRSensorUsagePPG",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsagePPG"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsagePPG",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageppg"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePedometer": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe steps information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePedometer",
      "kind": "symbol",
      "name": "SRSensorUsagePedometer",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsagePedometer"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsagePedometer",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagepedometer"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageSpeechMetrics": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to analyze the user’s speech.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageSpeechMetrics",
      "kind": "symbol",
      "name": "SRSensorUsageSpeechMetrics",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageSpeechMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageSpeechMetrics",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagespeechmetrics"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageVisits": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe the locations that the user frequents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageVisits",
      "kind": "symbol",
      "name": "SRSensorUsageVisits",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageVisits"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageVisits",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagevisits"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the user’s wrist temperature while the user sleeps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature",
      "kind": "symbol",
      "name": "SRSensorUsageWristTemperature",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageWristTemperature"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageWristTemperature",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagewristtemperature"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-Activity",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageECG",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageElevation",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageFacialMetrics",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMediaEvents",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMotion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageOdometer",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePedometer",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePPG",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageSpeechMetrics",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageVisits",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature"
      ],
      "title": "User Activity"
    }
  ],
  "topicSections": [
    {
      "anchor": "Sensor-usage-keys",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate/Description",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate/Required"
      ],
      "title": "Sensor usage keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRSensorUsageHeartRate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Sensor-usage-keys",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate/Description",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate/Required"
              ],
              "title": "Sensor usage keys"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-Activity",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageECG",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageElevation",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageFacialMetrics",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMediaEvents",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMotion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageOdometer",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePedometer",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePPG",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageSpeechMetrics",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageVisits",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature"
              ],
              "title": "User Activity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageElevation/title",
          "value": "SRSensorUsageElevation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageElevation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageElevation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail/title",
          "value": "NSSensorKitUsageDetail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSensorKitUsageDetail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageECG/title",
          "value": "SRSensorUsageECG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageECG/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageECG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsagePedometer/title",
          "value": "SRSensorUsagePedometer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsagePedometer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsagePedometer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageWristTemperature/title",
          "value": "SRSensorUsageWristTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageWristTemperature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageWristTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageFacialMetrics/title",
          "value": "SRSensorUsageFacialMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageFacialMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageFacialMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageHeartRate~1Required/title",
          "value": "Required"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageHeartRate~1Required/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Required"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageOdometer/title",
          "value": "SRSensorUsageOdometer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageOdometer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageOdometer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsagePPG/title",
          "value": "SRSensorUsagePPG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsagePPG/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsagePPG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageVisits/title",
          "value": "SRSensorUsageVisits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageVisits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageVisits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageHeartRate/title",
          "value": "SRSensorUsageHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageHeartRate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageHeartRate~1Description/title",
          "value": "Description"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageHeartRate~1Description/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Description"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageMotion/title",
          "value": "SRSensorUsageMotion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageMotion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageMediaEvents/title",
          "value": "SRSensorUsageMediaEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageMediaEvents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageMediaEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageSpeechMetrics/title",
          "value": "SRSensorUsageSpeechMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageSpeechMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageSpeechMetrics"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageheartrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageheartrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
