{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTuneRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDISystemStatus@kMIDIStatusTuneRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "statusTuneRequest"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDIStatusTuneRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MIDISystemStatus.statusTuneRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "statusTuneRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus": {
      "abstract": [
        {
          "text": "MIDI System status types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISystemStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISystemStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSending": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusActiveSending"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusActiveSending"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusActiveSending",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusactivesending"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusContinue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusContinue"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusContinue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusContinue"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusContinue",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statuscontinue"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusEndOfExclusive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusEndOfExclusive"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusEndOfExclusive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusEndOfExclusive"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusEndOfExclusive",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusendofexclusive"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusMTC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusMTC"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusMTC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusMTC"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusMTC",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusmtc"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongPosPointer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusSongPosPointer"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongPosPointer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusSongPosPointer"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusSongPosPointer",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statussongpospointer"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusSongSelect"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusSongSelect"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusSongSelect",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statussongselect"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusStart"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusStart"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusStart",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusstart"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStartOfExclusive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusStartOfExclusive"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStartOfExclusive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusStartOfExclusive"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusStartOfExclusive",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusstartofexclusive"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusStop"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusStop"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusStop",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusstop"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSystemReset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusSystemReset"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSystemReset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusSystemReset"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusSystemReset",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statussystemreset"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTimingClock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusTimingClock"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTimingClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusTimingClock"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusTimingClock",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statustimingclock"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTuneRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusTuneRequest"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTuneRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusTuneRequest"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusTuneRequest",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statustunerequest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Status-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSending",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusContinue",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusEndOfExclusive",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusMTC",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongPosPointer",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongSelect",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStart",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStartOfExclusive",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStop",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSystemReset",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTimingClock"
      ],
      "title": "Status Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMIDIStatusTuneRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusTuneRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Status-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSending",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusContinue",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusEndOfExclusive",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusMTC",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongPosPointer",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongSelect",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStart",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStartOfExclusive",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStop",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSystemReset",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTimingClock"
              ],
              "title": "Status Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMIDIStatusTuneRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStart/title",
          "value": "kMIDIStatusStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusContinue/title",
          "value": "kMIDIStatusContinue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusContinue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusContinue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusMTC/title",
          "value": "kMIDIStatusMTC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusMTC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusMTC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/title",
          "value": "MIDISystemStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusEndOfExclusive/title",
          "value": "kMIDIStatusEndOfExclusive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusEndOfExclusive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusEndOfExclusive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStop/title",
          "value": "kMIDIStatusStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSystemReset/title",
          "value": "kMIDIStatusSystemReset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSystemReset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusSystemReset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusActiveSending/title",
          "value": "kMIDIStatusActiveSending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusActiveSending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusActiveSending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSongPosPointer/title",
          "value": "kMIDIStatusSongPosPointer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSongPosPointer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusSongPosPointer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStartOfExclusive/title",
          "value": "kMIDIStatusStartOfExclusive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStartOfExclusive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusStartOfExclusive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSongSelect/title",
          "value": "kMIDIStatusSongSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSongSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusSongSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusTimingClock/title",
          "value": "kMIDIStatusTimingClock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusTimingClock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusTimingClock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusTuneRequest/title",
          "value": "kMIDIStatusTuneRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusTuneRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusTuneRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midisystemstatus/statustunerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midisystemstatus/statustunerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
