{
  "abstract": [
    {
      "text": "The amount of time – in calendar units such as day, month, or year – that represents a fraction of the total payment interval.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem/intervalUnit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKRecurringPaymentSummaryItem(py)intervalUnit",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "intervalUnit"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSCalendar",
        "text": "NSCalendar"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSCalendarUnit",
        "text": "Unit"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "intervalUnit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "intervalUnit"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "intervalUnit"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSCalendar",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCalendar",
              "text": "NSCalendar"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@NSCalendarUnit",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSCalendarUnit",
              "text": "Unit"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value for the interval unit is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nscalendar/unit/1418371-month",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The supported ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nscalendar/unit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " interval units are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533469-minute",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533526-hour",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533502-day",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533484-month",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533507-year",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To set an interval unit based on a week, set ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem/intervalUnit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533502-day",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and set ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem/intervalCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to a multiple of the number of days per week. To find the number of days for a week in the current calendar, call ",
              "type": "text"
            },
            {
              "code": "NSCalendar.current.maximumRange(of: .weekday)!.count)",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, the code below sets a payment that occurs every two weeks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let daysPerWeek = NSCalendar.current.maximumRange(of: .weekday)!.count)",
            "",
            "intervalUnit = .day",
            "intervalCount = daysPerWeek * 2"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533469-minute": {
      "abstract": [
        {
          "text": "Specifies the minute unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "minute"
        },
        {
          "kind": "text",
          "text": ": CFCalendarUnit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533469-minute",
      "kind": "symbol",
      "role": "symbol",
      "title": "minute",
      "type": "topic",
      "url": "/documentation/corefoundation/cfcalendarunit/1533469-minute"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533484-month": {
      "abstract": [
        {
          "text": "Specifies the month unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "month"
        },
        {
          "kind": "text",
          "text": ": CFCalendarUnit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533484-month",
      "kind": "symbol",
      "role": "symbol",
      "title": "month",
      "type": "topic",
      "url": "/documentation/corefoundation/cfcalendarunit/1533484-month"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533502-day": {
      "abstract": [
        {
          "text": "Specifies the day unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "day"
        },
        {
          "kind": "text",
          "text": ": CFCalendarUnit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533502-day",
      "kind": "symbol",
      "role": "symbol",
      "title": "day",
      "type": "topic",
      "url": "/documentation/corefoundation/cfcalendarunit/1533502-day"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533507-year": {
      "abstract": [
        {
          "text": "Specifies the year unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "year"
        },
        {
          "kind": "text",
          "text": ": CFCalendarUnit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533507-year",
      "kind": "symbol",
      "role": "symbol",
      "title": "year",
      "type": "topic",
      "url": "/documentation/corefoundation/cfcalendarunit/1533507-year"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533526-hour": {
      "abstract": [
        {
          "text": "Specifies the hour unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "hour"
        },
        {
          "kind": "text",
          "text": ": CFCalendarUnit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendarunit/1533526-hour",
      "kind": "symbol",
      "role": "symbol",
      "title": "hour",
      "type": "topic",
      "url": "/documentation/corefoundation/cfcalendarunit/1533526-hour"
    },
    "doc://com.apple.documentation/documentation/foundation/nscalendar/unit": {
      "abstract": [
        {
          "text": "Calendrical units such as year, month, day and hour. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSCalendar.Unit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscalendar/unit",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCalendar.Unit",
      "type": "topic",
      "url": "/documentation/foundation/nscalendar/unit"
    },
    "doc://com.apple.documentation/documentation/foundation/nscalendar/unit/1418371-month": {
      "abstract": [
        {
          "text": "Identifier for the month unit. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "month"
        },
        {
          "kind": "text",
          "text": ": NSCalendar.Unit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscalendar/unit/1418371-month",
      "kind": "symbol",
      "role": "symbol",
      "title": "month",
      "type": "topic",
      "url": "/documentation/foundation/nscalendar/unit/1418371-month"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem": {
      "abstract": [
        {
          "text": "An object that defines a summary item for a payment that occurs repeatedly at a specified interval, such as a subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKRecurringPaymentSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKRecurringPaymentSummaryItem"
        }
      ],
      "role": "symbol",
      "title": "PKRecurringPaymentSummaryItem",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentsummaryitem"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem/intervalCount": {
      "abstract": [
        {
          "text": "The number of interval units that make up the total payment interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intervalCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem/intervalCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intervalCount"
        }
      ],
      "role": "symbol",
      "title": "intervalCount",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentsummaryitem/intervalcount"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem/intervalUnit": {
      "abstract": [
        {
          "text": "The amount of time – in calendar units such as day, month, or year – that represents a fraction of the total payment interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intervalUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCalendar",
          "text": "NSCalendar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCalendarUnit",
          "text": "Unit"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem/intervalUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intervalUnit"
        }
      ],
      "role": "symbol",
      "title": "intervalUnit",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentsummaryitem/intervalunit"
    },
    "doc://com.externally.resolved.symbol/c:@E@NSCalendarUnit": {
      "abstract": [
        {
          "text": "Calendrical units such as year, month, day and hour. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSCalendar.Unit"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@NSCalendarUnit",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCalendar.Unit",
      "type": "topic",
      "url": "/documentation/foundation/nscalendar/unit"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSCalendar": {
      "abstract": [
        {
          "text": "An encapsulation of calendar information and calculations that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSCalendar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSCalendar",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCalendar",
      "type": "topic",
      "url": "/documentation/foundation/nscalendar"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-payment-interval",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem/intervalCount"
      ],
      "title": "Setting the payment interval"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "intervalUnit"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "intervalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-the-payment-interval",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem/intervalCount"
              ],
              "title": "Setting the payment interval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@NSCalendarUnit",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSCalendarUnit",
                    "text": "NSCalendarUnit"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "intervalUnit"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfcalendarunit~11533507-year/title",
          "value": "kCFCalendarUnitYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentSummaryItem~1intervalCount/title",
          "value": "intervalCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentSummaryItem~1intervalCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "intervalCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentSummaryItem~1intervalUnit/title",
          "value": "intervalUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentSummaryItem~1intervalUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "intervalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentSummaryItem/title",
          "value": "PKRecurringPaymentSummaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentSummaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentSummaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfcalendarunit~11533484-month/title",
          "value": "kCFCalendarUnitMonth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfcalendarunit~11533469-minute/title",
          "value": "kCFCalendarUnitMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nscalendar~1unit/title",
          "value": "NSCalendarUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSCalendar/abstract",
          "value": [
            {
              "text": "A definition of the relationships between calendar units and absolute points in time, providing features for calculation and comparison of dates.  ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nscalendar~1unit~11418371-month/title",
          "value": "NSCalendarUnitMonth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfcalendarunit~11533526-hour/title",
          "value": "kCFCalendarUnitHour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfcalendarunit~11533502-day/title",
          "value": "kCFCalendarUnitDay"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkrecurringpaymentsummaryitem/intervalunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkrecurringpaymentsummaryitem/intervalunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
