{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/TypeDisplayRepresentable-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "TypeDisplayRepresentable Implementations"
  },
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark": {
      "abstract": [
        {
          "text": "A user-friendly description of a geographic coordinate, often containing the name of the place, its address, and other relevant information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLPlacemark"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLPlacemark"
        }
      ],
      "role": "symbol",
      "title": "CLPlacemark",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/typeDisplayRepresentation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeDisplayRepresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents25TypeDisplayRepresentationV",
          "text": "TypeDisplayRepresentation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/typeDisplayRepresentation",
      "kind": "symbol",
      "role": "symbol",
      "title": "typeDisplayRepresentation",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/typedisplayrepresentation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/typeDisplayRepresentation"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark/title",
          "value": "CLPlacemark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLPlacemark"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/clplacemark/typedisplayrepresentable-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
