{
  "abstract": [
    {
      "text": "25 frames per second (standard PAL).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type25"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CVSMPTETimeType@kCVSMPTETimeType25",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "type25"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCVSMPTETimeType25"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CVSMPTETimeType.type25"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "type25"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVSMPTETimeType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVSMPTETimeType"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type24": {
      "abstract": [
        {
          "text": "24 frames per second (standard film).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type24"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVSMPTETimeType24"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType.type24",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype/type24"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type25": {
      "abstract": [
        {
          "text": "25 frames per second (standard PAL).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type25"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVSMPTETimeType25"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType.type25",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype/type25"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type2997": {
      "abstract": [
        {
          "text": "29.97 frames per second (standard NTSC).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2997"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type2997",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVSMPTETimeType2997"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType.type2997",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype/type2997"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type2997Drop": {
      "abstract": [
        {
          "text": "29.97 drop frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2997Drop"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type2997Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVSMPTETimeType2997Drop"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType.type2997Drop",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype/type2997drop"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type30": {
      "abstract": [
        {
          "text": "30 frames per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type30"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVSMPTETimeType30"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType.type30",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype/type30"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type30Drop": {
      "abstract": [
        {
          "text": "30 drop frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type30Drop"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type30Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVSMPTETimeType30Drop"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType.type30Drop",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype/type30drop"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type5994": {
      "abstract": [
        {
          "text": "59.94 frames per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type5994"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type5994",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVSMPTETimeType5994"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType.type5994",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype/type5994"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type60": {
      "abstract": [
        {
          "text": "60 frames per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type60"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVSMPTETimeType60"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType.type60",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype/type60"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type24",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type2997",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type2997Drop",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type30",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type30Drop",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type5994",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type60"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCVSMPTETimeType25"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVSMPTETimeType25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type24",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type2997",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type2997Drop",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type30",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type30Drop",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type5994",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType/type60"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCVSMPTETimeType25"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type24/title",
          "value": "kCVSMPTETimeType24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVSMPTETimeType24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type60/title",
          "value": "kCVSMPTETimeType60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVSMPTETimeType60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type30/title",
          "value": "kCVSMPTETimeType30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVSMPTETimeType30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type2997/title",
          "value": "kCVSMPTETimeType2997"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type2997/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVSMPTETimeType2997"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type30Drop/title",
          "value": "kCVSMPTETimeType30Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type30Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVSMPTETimeType30Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType/title",
          "value": "CVSMPTETimeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETimeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETimeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type25/title",
          "value": "kCVSMPTETimeType25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVSMPTETimeType25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type5994/title",
          "value": "kCVSMPTETimeType5994"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type5994/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVSMPTETimeType5994"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type2997Drop/title",
          "value": "kCVSMPTETimeType2997Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType~1type2997Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVSMPTETimeType2997Drop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvsmptetimetype/type25"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvsmptetimetype/type25"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
