{
  "abstract": [
    {
      "text": "Specifies a round line cap style for endpoints for an open path when stroked.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/round"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSLineCapStyle@NSLineCapStyleRound",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "round"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLineCapStyleRound"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSBezierPath.LineCapStyle.round"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "round"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Here is an example of the appearance of this style:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3670934",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath": {
      "abstract": [
        {
          "text": "An object that can create paths using PostScript-style commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the shape of endpoints for an open path when it is stroked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineCapStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineCapStyle"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineCapStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linecapstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/butt": {
      "abstract": [
        {
          "text": "Specifies a butt line cap style for endpoints for an open path when stroked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "butt"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/butt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineCapStyleButt"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineCapStyle.butt",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linecapstyle-swift.enum/butt"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/round": {
      "abstract": [
        {
          "text": "Specifies a round line cap style for endpoints for an open path when stroked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "round"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/round",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineCapStyleRound"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineCapStyle.round",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linecapstyle-swift.enum/round"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square": {
      "abstract": [
        {
          "text": "Specifies a square line cap style for endpoints for an open path when stroked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "square"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineCapStyleSquare"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineCapStyle.square",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linecapstyle-swift.enum/square"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3670934": {
      "alt": "Diagram that shows the round line cap style.",
      "identifier": "media-3670934",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a4375de4f678a4c65ee0780f7a1946ed/media-3670934@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/butt",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSLineCapStyleRound"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyleRound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/butt",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSLineCapStyleRound"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1round/title",
          "value": "NSLineCapStyleRound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1round/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyleRound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1butt/title",
          "value": "NSLineCapStyleButt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1butt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyleButt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1square/title",
          "value": "NSLineCapStyleSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1square/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyleSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/title",
          "value": "NSLineCapStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title",
          "value": "NSBezierPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbezierpath/linecapstyle-swift.enum/round"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbezierpath/linecapstyle-swift.enum/round"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
