{
  "abstract": [
    {
      "text": "Constants that describe actions for control characters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/textkit",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutManagerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/1619233-control-characters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Control Characters"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterContainerBreakAction": {
      "abstract": [
        {
          "text": "A character that causes a break in layout.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterContainerBreakAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterContainerBreakAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterContainerBreakAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterContainerBreakAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharactercontainerbreakaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterHorizontalTabAction": {
      "abstract": [
        {
          "text": "An action that inserts a horizontal tab.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterHorizontalTabAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterHorizontalTabAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterHorizontalTabAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterHorizontalTabAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharacterhorizontaltabaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterLineBreakAction": {
      "abstract": [
        {
          "text": "An action that causes a line break.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterLineBreakAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterLineBreakAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterLineBreakAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterLineBreakAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharacterlinebreakaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterParagraphBreakAction": {
      "abstract": [
        {
          "text": "An action that causes a paragraph break.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterParagraphBreakAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterParagraphBreakAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterParagraphBreakAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterParagraphBreakAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharacterparagraphbreakaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterWhitespaceAction": {
      "abstract": [
        {
          "text": "An action that programmatically changes the white space around the glyph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterWhitespaceAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterWhitespaceAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterWhitespaceAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterWhitespaceAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharacterwhitespaceaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterZeroAdvancementAction": {
      "abstract": [
        {
          "text": "An action that removes the glyph from layout.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterZeroAdvancementAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterZeroAdvancementAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterZeroAdvancementAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterZeroAdvancementAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharacterzeroadvancementaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager": {
      "abstract": [
        {
          "text": "An object that coordinates the layout and display of text characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutManagerDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods that delegates of layout manager objects implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutManagerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManagerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutManagerDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManagerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutmanagerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/textkit": {
      "abstract": [
        {
          "text": "Manage text storage and perform custom layout of text-based content in your app’s views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/textkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit",
      "type": "topic",
      "url": "/documentation/uikit/textkit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterContainerBreakAction",
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterHorizontalTabAction",
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterLineBreakAction",
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterParagraphBreakAction",
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterWhitespaceAction",
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterZeroAdvancementAction"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterContainerBreakAction",
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterHorizontalTabAction",
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterLineBreakAction",
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterParagraphBreakAction",
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterWhitespaceAction",
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterZeroAdvancementAction"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterParagraphBreakAction/title",
          "value": "NSControlCharacterParagraphBreakAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterParagraphBreakAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterParagraphBreakAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterZeroAdvancementAction/title",
          "value": "NSControlCharacterZeroAdvancementAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterZeroAdvancementAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterZeroAdvancementAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterContainerBreakAction/title",
          "value": "NSControlCharacterContainerBreakAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterContainerBreakAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterContainerBreakAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/title",
          "value": "NSLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterHorizontalTabAction/title",
          "value": "NSControlCharacterHorizontalTabAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterHorizontalTabAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterHorizontalTabAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManagerDelegate/title",
          "value": "NSLayoutManagerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManagerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManagerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterWhitespaceAction/title",
          "value": "NSControlCharacterWhitespaceAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterWhitespaceAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterWhitespaceAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterLineBreakAction/title",
          "value": "NSControlCharacterLineBreakAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterLineBreakAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterLineBreakAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/1619233-control-characters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/1619233-control-characters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
