{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/about-the-gesture-recognizer-state-machine"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/about-the-gesture-recognizer-state-machine"]}],"sections":[],"kind":"article","primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Gesture recognizers are driven by a state machine, which UIKit uses to ensure the proper handling of events. The state machine determines several important behaviors:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether a continuous gesture recognizer is allowed to enter the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/began"},{"type":"text","text":" state"}]}]},{"content":[{"inlineContent":[{"text":"Whether a discrete gesture recognizer is allowed to enter the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended","isActive":true,"type":"reference"},{"text":" state","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"When calls to attached action handlers occur"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When implementing a custom gesture recognizer, you must update its state machine at appropriate times. A gesture recognizer always starts in the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/possible","isActive":true},{"type":"text","text":" state, which indicates that it is ready to start processing events. From that state, discrete and continuous gesture recognizers follow different paths until they reach the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/failed","isActive":true},{"type":"text","text":", or "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/cancelled","isActive":true},{"type":"text","text":" state. A gesture recognizer remains in one of those final states until the current event sequence ends, at which point UIKit resets the gesture recognizer and returns it to the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/possible","isActive":true},{"type":"text","text":" state."}]},{"level":3,"type":"heading","text":"Managing State Transitions for a Discrete Gesture Recognizer","anchor":"Managing-State-Transitions-for-a-Discrete-Gesture-Recognizer"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When implementing a discrete gesture recognizer, you change the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/state-swift.property"},{"type":"text","text":" property to one of two possible values: "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/failed"},{"type":"text","text":". The following image shows the state diagram for these transitions. When incoming events successfully match your gesture, change the state to "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended"},{"type":"text","text":". When events do not match your intended gesture, change the state to "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/failed"},{"type":"text","text":" as soon as you detect the failure."}]},{"type":"paragraph","inlineContent":[{"identifier":"media-3004409","type":"image"}]},{"type":"paragraph","inlineContent":[{"text":"When your gesture recognizer transitions to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended"},{"text":" state, UIKit calls the action methods of any associated target objects. UIKit does not call any action methods when the gesture recognizer transitions to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/failed"},{"text":" state.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"For an example of how to implement a discrete gesture recognizer, see ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/implementing-a-discrete-gesture-recognizer","type":"reference"},{"text":".","type":"text"}]},{"level":3,"type":"heading","text":"Managing State Transitions for a Continuous Gesture Recognizer","anchor":"Managing-State-Transitions-for-a-Continuous-Gesture-Recognizer"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The following image shows the state diagram for a continuous gesture recognizer. The state transitions you make can be broken down into three general phases:"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"The initial event sequence moves the gesture recognizer to the ","type":"text"},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/began","isActive":true},{"text":" or ","type":"text"},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/failed","isActive":true},{"text":" state.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Subsequent events move the gesture recognizer to the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/changed","isActive":true,"type":"reference"},{"text":" or ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/cancelled","isActive":true,"type":"reference"},{"text":" state.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A final event moves the gesture recognizer to the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended","type":"reference"},{"text":" state.","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"media-3004408"}]},{"type":"paragraph","inlineContent":[{"text":"When your gesture recognizer is in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/possible"},{"text":" state, if the initial event sequence does not match your gesture, move your gesture recognizer to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/failed"},{"text":" state immediately. UIKit normally permits only one gesture recognizer at a time to notify its client. Moving your custom gesture recognizer to the failed state gives other gesture recognizers an opportunity to handle their gestures.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the initial event sequence matches your gesture, move your gesture recognizer to the "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/began","type":"reference","isActive":true},{"type":"text","text":" state. For any subsequent events, repeatedly move your gesture recognizer to the "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/changed","type":"reference","isActive":true},{"type":"text","text":" state to indicate that the event information has changed. (Always set the gesture recognizer’s "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/state-swift.property","type":"reference","isActive":true},{"type":"text","text":" property to "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/changed","type":"reference","isActive":true},{"type":"text","text":" for each new event, even if the property is already set to that value. Setting that property triggers calls to the associated action methods.) When an event indicates the successful completion of your gesture, change the state to "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended","type":"reference","isActive":true},{"type":"text","text":". However, if an event indicates the unsuccessful completion of your gesture, change the state to "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/cancelled","type":"reference","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When your gesture recognizer transitions to the "},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/began","type":"reference"},{"type":"text","text":", "},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/changed","type":"reference"},{"type":"text","text":", or "},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended","type":"reference"},{"type":"text","text":" states, UIKit calls the action methods of any associated targets. UIKit does not call any action methods when your gesture recognizer transitions to other states."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For an example of how to implement a continuous gesture recognizer, see "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/implementing-a-continuous-gesture-recognizer","isActive":true},{"type":"text","text":"."}]},{"level":3,"type":"heading","text":"Handling Cancellation","anchor":"Handling-Cancellation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Cancellation of a gesture occurs automatically when the current event sequence is interrupted by a system event, such as an incoming phone call. You can also cancel a gesture programmatically based on event information or on conditions in your app. Cancellation prevents the gesture recognizer from performing tasks that the user didn’t intend."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the system cancels a gesture, UIKit calls the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponder/touchesCancelled(_:with:)"},{"type":"text","text":" or "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/pressesCancelled(_:with:)"},{"type":"text","text":" method of your gesture recognizer. When that happens, move your gesture recognizer to the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/cancelled"},{"type":"text","text":" state immediately. When you move your gesture recognizer to the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/cancelled"},{"type":"text","text":" state, UIKit calls the gesture recognizer’s action methods one final time before resetting it."}]},{"level":3,"type":"heading","text":"Resetting the Gesture Recognizer State Machine","anchor":"Resetting-the-Gesture-Recognizer-State-Machine"},{"type":"paragraph","inlineContent":[{"text":"Implement the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/reset()","type":"reference"},{"text":" method and use it to return your gesture recognizer to its initial configuration. For example, use this method to return your gesture recognizer’s custom properties to their starting values. Before delivering events in a new event sequence, UIKit calls the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/reset()","type":"reference"},{"text":" method of every gesture recognizer that received touches or is in the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/failed","type":"reference"},{"text":", ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/cancelled","type":"reference"},{"text":", or ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended","type":"reference"},{"text":" state. In addition to calling the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/reset()","type":"reference"},{"text":" method, UIKit automatically changes each gesture recognizer’s ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/state-swift.property","type":"reference"},{"text":" property back to ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/possible","type":"reference"},{"text":" so that it can respond to new event sequences.","type":"text"}]}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/about-the-gesture-recognizer-state-machine","interfaceLanguage":"swift"},"abstract":[{"text":"Learn about the states and transitions of the state machine that underlies gesture recognizers.","type":"text"}],"metadata":{"role":"article","modules":[{"name":"UIKit"}],"title":"About the Gesture Recognizer State Machine","roleHeading":"Article"},"seeAlsoSections":[{"generated":true,"title":"Creating Custom Gesture Recognizers","identifiers":["doc://com.apple.uikit/documentation/UIKit/implementing-a-discrete-gesture-recognizer","doc://com.apple.uikit/documentation/UIKit/implementing-a-continuous-gesture-recognizer"],"anchor":"Creating-Custom-Gesture-Recognizers"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures","doc://com.apple.uikit/documentation/UIKit/implementing-a-custom-gesture-recognizer"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended","kind":"symbol","navigatorTitle":[{"text":"UIGestureRecognizerStateEnded","kind":"identifier"}],"type":"topic","title":"UIGestureRecognizer.State.ended","url":"/documentation/uikit/uigesturerecognizer/state-swift.enum/ended","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ended","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The gesture recognizer has received touches recognized as the end of a continuous gesture."}]},"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/failed":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/failed","type":"topic","abstract":[{"type":"text","text":"The gesture recognizer has received a multi-touch sequence that it can’t recognize as its gesture."}],"url":"/documentation/uikit/uigesturerecognizer/state-swift.enum/failed","navigatorTitle":[{"text":"UIGestureRecognizerStateFailed","kind":"identifier"}],"title":"UIGestureRecognizer.State.failed","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/changed":{"navigatorTitle":[{"text":"UIGestureRecognizerStateChanged","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/changed","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changed","kind":"identifier"}],"url":"/documentation/uikit/uigesturerecognizer/state-swift.enum/changed","abstract":[{"text":"The gesture recognizer has received touches recognized as a change to a continuous gesture.","type":"text"}],"title":"UIGestureRecognizer.State.changed","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/state-swift.property":{"type":"topic","role":"symbol","title":"state","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":".","kind":"text"},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIGestureRecognizerState"}],"navigatorTitle":[{"text":"state","kind":"identifier"}],"abstract":[{"type":"text","text":"The current state of the gesture recognizer."}],"url":"/documentation/uikit/uigesturerecognizer/state-swift.property","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/state-swift.property","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/reset()":{"url":"/documentation/uikit/uigesturerecognizer/reset()","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/reset()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reset"}],"abstract":[{"type":"text","text":"Overridden to reset internal state when a gesture recognition attempt completes."}],"kind":"symbol","type":"topic","title":"reset()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reset"},{"kind":"text","text":"()"}]},"doc://com.apple.uikit/documentation/UIKit/UIResponder/touchesCancelled(_:with:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchesCancelled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":">, ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent"},{"text":"?)","kind":"text"}],"url":"/documentation/uikit/uiresponder/touchescancelled(_:with:)","title":"touchesCancelled(_:with:)","navigatorTitle":[{"text":"touchesCancelled:withEvent:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponder/touchesCancelled(_:with:)","abstract":[{"text":"Tells the responder when a system event (such as a system alert) cancels a touch sequence.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/pressesCancelled(_:with:)":{"abstract":[{"text":"Sent to the receiver when a system event (such as a low-memory warning) cancels a press event.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pressesCancelled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"text":"UIPress","preciseIdentifier":"c:objc(cs)UIPress","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIPressesEvent","preciseIdentifier":"c:objc(cs)UIPressesEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uigesturerecognizer/pressescancelled(_:with:)","title":"pressesCancelled(_:with:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pressesCancelled:withEvent:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/pressesCancelled(_:with:)","role":"symbol"},"media-3004408":{"type":"image","alt":"The states of continuous gesture","identifier":"media-3004408","variants":[{"traits":["2x","light"],"url":"https://docs-assets.developer.apple.com/published/86d0d5900211f1645a04880a66ddbc28/media-3004408@2x.png"}]},"doc://com.apple.uikit/documentation/UIKit/implementing-a-continuous-gesture-recognizer":{"role":"article","identifier":"doc://com.apple.uikit/documentation/UIKit/implementing-a-continuous-gesture-recognizer","kind":"article","title":"Implementing a Continuous Gesture Recognizer","type":"topic","abstract":[{"type":"text","text":"For gestures that do not easily match a specific pattern, or when you want to use a gesture recognizer to gather touch input, create a continuous gesture recognizer."}],"url":"/documentation/uikit/implementing-a-continuous-gesture-recognizer"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/implementing-a-custom-gesture-recognizer":{"abstract":[{"text":"Discover when and how to build your own gesture recognizers.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/implementing-a-custom-gesture-recognizer","role":"collectionGroup","type":"topic","title":"Implementing a custom gesture recognizer","kind":"article","url":"/documentation/uikit/implementing-a-custom-gesture-recognizer"},"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/cancelled":{"abstract":[{"type":"text","text":"The gesture recognizer has received touches resulting in the cancellation of a continuous gesture."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/cancelled","type":"topic","title":"UIGestureRecognizer.State.cancelled","kind":"symbol","role":"symbol","url":"/documentation/uikit/uigesturerecognizer/state-swift.enum/cancelled","navigatorTitle":[{"kind":"identifier","text":"UIGestureRecognizerStateCancelled"}]},"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/began":{"role":"symbol","abstract":[{"type":"text","text":"The gesture recognizer has received touch objects recognized as a continuous gesture."}],"navigatorTitle":[{"kind":"identifier","text":"UIGestureRecognizerStateBegan"}],"type":"topic","url":"/documentation/uikit/uigesturerecognizer/state-swift.enum/began","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/began","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"began"}],"title":"UIGestureRecognizer.State.began"},"media-3004409":{"type":"image","alt":"The states of a discrete gesture.","identifier":"media-3004409","variants":[{"traits":["2x","light"],"url":"https://docs-assets.developer.apple.com/published/9727ff45763a2d8025ecdb5a2bf93dc4/media-3004409@2x.png"}]},"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/possible":{"navigatorTitle":[{"kind":"identifier","text":"UIGestureRecognizerStatePossible"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"possible"}],"type":"topic","abstract":[{"text":"The gesture recognizer hasn’t yet recognized its gesture, but may be evaluating touch events.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/possible","title":"UIGestureRecognizer.State.possible","url":"/documentation/uikit/uigesturerecognizer/state-swift.enum/possible","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures":{"title":"Touches, presses, and gestures","type":"topic","kind":"article","identifier":"doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures","role":"collectionGroup","abstract":[{"text":"Encapsulate your app’s event-handling logic in gesture recognizers so that you can reuse that code throughout your app.","type":"text"}],"url":"/documentation/uikit/touches-presses-and-gestures"},"doc://com.apple.uikit/documentation/UIKit/implementing-a-discrete-gesture-recognizer":{"role":"article","identifier":"doc://com.apple.uikit/documentation/UIKit/implementing-a-discrete-gesture-recognizer","kind":"article","title":"Implementing a Discrete Gesture Recognizer","type":"topic","abstract":[{"type":"text","text":"If your gesture involves a specific pattern of events, consider implementing a discrete gesture recognizer for it."}],"url":"/documentation/uikit/implementing-a-discrete-gesture-recognizer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/topicSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/implementing-a-discrete-gesture-recognizer","doc://com.apple.uikit/documentation/UIKit/implementing-a-continuous-gesture-recognizer"],"title":"Creating Custom Gesture Recognizers","anchor":"Creating-Custom-Gesture-Recognizers","generated":true}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1ended/title","op":"replace","value":"UIGestureRecognizerStateEnded"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1ended/fragments","op":"replace","value":[{"text":"UIGestureRecognizerStateEnded","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1failed/title","op":"replace","value":"UIGestureRecognizerStateFailed"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1failed/fragments","op":"replace","value":[{"text":"UIGestureRecognizerStateFailed","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1changed/title","op":"replace","value":"UIGestureRecognizerStateChanged"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1changed/fragments","op":"replace","value":[{"kind":"identifier","text":"UIGestureRecognizerStateChanged"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1state-swift.property/title","op":"replace","value":"state"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1state-swift.property/fragments","op":"replace","value":[{"text":"state","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1reset()/title","op":"replace","value":"reset"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1reset()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reset"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1touchesCancelled(_:with:)/title","op":"replace","value":"touchesCancelled:withEvent:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1touchesCancelled(_:with:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesCancelled:withEvent:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1pressesCancelled(_:with:)/title","op":"replace","value":"pressesCancelled:withEvent:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1pressesCancelled(_:with:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pressesCancelled:withEvent:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1cancelled/title","op":"replace","value":"UIGestureRecognizerStateCancelled"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1cancelled/fragments","op":"replace","value":[{"text":"UIGestureRecognizerStateCancelled","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1began/title","op":"replace","value":"UIGestureRecognizerStateBegan"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1began/fragments","op":"replace","value":[{"kind":"identifier","text":"UIGestureRecognizerStateBegan"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1possible/title","op":"replace","value":"UIGestureRecognizerStatePossible"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1possible/fragments","op":"replace","value":[{"text":"UIGestureRecognizerStatePossible","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}