{
  "abstract": [
    {
      "text": "Enhance interactions with your app by handling raw keyboard events, writing custom keyboard shortcuts, and working with gesture recognizers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/keyboards-and-input"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/adding-hardware-keyboard-support-to-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Adding hardware keyboard support to your app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC20 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc20/10109/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "bfc5b86dd67e/AddingHardwareKeyboardSupportToYourApp.zip": {
      "checksum": "bfc5b86dd67ebbbed2c24e618cd6e37f434a4ef1268e821bf44f9539b3894890199801db5042ccfd0e465d46e0b5060ab11f1b78eca2c41b6cc9c61a84afbca4",
      "identifier": "bfc5b86dd67e/AddingHardwareKeyboardSupportToYourApp.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/bfc5b86dd67e/AddingHardwareKeyboardSupportToYourApp.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKey": {
      "abstract": [
        {
          "text": "An object that provides information about the state of a keyboard key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKey"
        }
      ],
      "role": "symbol",
      "title": "UIKey",
      "type": "topic",
      "url": "/documentation/uikit/uikey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage": {
      "abstract": [
        {
          "text": "A set of HID usage codes that identify the keys of a USB keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsage"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard": {
      "abstract": [
        {
          "text": "Detect when someone presses and releases keys on a physical keyboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard",
      "kind": "article",
      "role": "article",
      "title": "Handling key presses made on a physical keyboard",
      "type": "topic",
      "url": "/documentation/uikit/handling-key-presses-made-on-a-physical-keyboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/keyboards-and-input": {
      "abstract": [
        {
          "text": "Configure the system keyboard, create your own keyboards to handle input, or detect key presses on a physical keyboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/keyboards-and-input",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keyboards and input",
      "type": "topic",
      "url": "/documentation/uikit/keyboards-and-input"
    },
    "doc://com.apple.uikit/documentation/UIKit/navigating-an-app-s-user-interface-using-a-keyboard": {
      "abstract": [
        {
          "text": "Navigate between user interface elements using a keyboard and focusable UI elements in iPad apps and apps built with Mac Catalyst.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/navigating-an-app-s-user-interface-using-a-keyboard",
      "kind": "article",
      "role": "sampleCode",
      "title": "Navigating an app’s user interface using a keyboard",
      "type": "topic",
      "url": "/documentation/uikit/navigating-an-app-s-user-interface-using-a-keyboard"
    },
    "https://developer.apple.com/wwdc20/10109/": {
      "identifier": "https://developer.apple.com/wwdc20/10109/",
      "title": "10109: Hardware Keyboard Best Practices",
      "titleInlineContent": [
        {
          "text": "10109: Hardware Keyboard Best Practices",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc20/10109/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "bfc5b86dd67e/AddingHardwareKeyboardSupportToYourApp.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Physical-keyboards",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard",
        "doc://com.apple.uikit/documentation/UIKit/navigating-an-app-s-user-interface-using-a-keyboard",
        "doc://com.apple.uikit/documentation/UIKit/UIKey",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage"
      ],
      "title": "Physical keyboards"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/title",
          "value": "UIKeyboardHIDUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKey/title",
          "value": "UIKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/adding-hardware-keyboard-support-to-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
