{
  "abstract": [
    {
      "text": "Provide quick access to useful actions by adding menus and keyboard shortcuts to your Mac app built with Mac Catalyst.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/mac-catalyst"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts",
        "doc://com.apple.uikit/documentation/UIKit/UICommand"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts",
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts",
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts",
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/adding-menus-and-shortcuts-to-the-menu-bar-and-user-interface"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Adding menus and shortcuts to the menu bar and user interface"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample project demonstrates how to add menu commands and keyboard shortcuts to the menu bar. The sample app uses its ",
              "type": "text"
            },
            {
              "code": "MenuController",
              "type": "codeVoice"
            },
            {
              "text": " object to insert a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuSystem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that adds the following menus:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "New: Appears at the beginning of the File menu and contains the two operations New Date Item and New Text Item, which add items to the table view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Cities: Contains a group of UICommand and UIKeyCommand objects.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Navigation: Contains a group of UIKeyCommand objects for command-key navigation.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Style: Contains a group of UICommand objects that have checkmark states. This grouping looks like a font-style menu for text formatting.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Tools: Contains a group of UICommand objects.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The sample project also shows you how to add contextual menus to views, and how to handle menu-command selection using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Xcode, select your development team on the iOS target’s Signing and Capabilities tab.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-menus-to-the-menu-bar",
          "level": 3,
          "text": "Add menus to the menu bar",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create ",
              "type": "text"
            },
            {
              "code": "UIMenu",
              "type": "codeVoice"
            },
            {
              "text": " objects and use them to construct the menus and submenus. This sample adds menus to the menu bar when it runs on macOS, and key command elements in those menus also appear in the discoverability heads-up display (HUD) on iPad when the user presses the command key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Mac version of an iPad app comes with a standard menu bar. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuSystem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class, an object that represents the main or contextual menu system, to modify the menu bar.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample uses ",
              "type": "text"
            },
            {
              "code": "UIMenuSystem",
              "type": "codeVoice"
            },
            {
              "text": " to add menus and key commands to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuSystem/main",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " system menu by implementing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResponder/buildMenu(with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "code": "AppDelegate",
              "type": "codeVoice"
            },
            {
              "text": ". This function receives a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuBuilder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that the sample then uses to add and remove menus. Because menus can exist with no window or view hierarchy, the system only consults ",
              "type": "text"
            },
            {
              "code": "UIApplication",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "UIApplicationDelegate",
              "type": "codeVoice"
            },
            {
              "text": " to build the app’s menu bar.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Menu commands consist of ",
              "type": "text"
            },
            {
              "code": "UICommand",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "UIKeyCommand",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects that are grouped in a ",
              "type": "text"
            },
            {
              "code": "UIMenu",
              "type": "codeVoice"
            },
            {
              "text": " container.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-menu-commands-to-the-file-menu",
          "level": 3,
          "text": "Add menu commands to the file menu",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample inserts a ",
              "type": "text"
            },
            {
              "code": "UIKeyCommand",
              "type": "codeVoice"
            },
            {
              "text": " called Command-O into the File Menu and creates a corresponding keyboard shortcut:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class func openMenu() -> UIMenu {",
            "    let openCommand =",
            "        UIKeyCommand(title: NSLocalizedString(\"OpenTitle\", comment: \"\"),",
            "                     image: nil,",
            "                     action: #selector(AppDelegate.openAction),",
            "                     input: \"o\",",
            "                     modifierFlags: .command)",
            "    let openMenu =",
            "        UIMenu(title: \"\",",
            "               image: nil,",
            "               identifier: .openMenu,",
            "               options: .displayInline,",
            "               children: [openCommand])",
            "    return openMenu",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Notice that the ",
              "type": "text"
            },
            {
              "code": "UIKeyCommand",
              "type": "codeVoice"
            },
            {
              "text": " title is a localized string using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nslocalizedstring",
              "isActive": true,
              "overridingTitle": "NSLocalizedString",
              "overridingTitleInlineContent": [
                {
                  "code": "NSLocalizedString",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " function, which can display the menu name in multiple languages.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample inserts the Open command into the middle of the menu bar’s File menu:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "builder.insertChild(MenuController.openMenu(), atStartOfMenu: .file)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Mac apps also typically include a Print menu command in the File menu. This sample includes both Print and Export as PDF menu commands in the File Menu. These menu commands are automatically inserted when the ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " contains the ",
              "type": "text"
            },
            {
              "code": "UIApplicationSupportsPrintCommand",
              "type": "codeVoice"
            },
            {
              "text": " key whose value is set to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ". The application responds to these print commands by implementing ",
              "type": "text"
            },
            {
              "code": "UIResponder's",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "printContent(_ sender: Any?)",
              "type": "codeVoice"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Contribute-to-the-edit-menu",
          "level": 3,
          "text": "Contribute to the edit menu",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Editing operations, such as cut, copy, paste, and delete, are commonly used in most apps. This sample app provides these operations through the Edit menu, where the user can edit the sample’s left-side content or its primary table-view content. These operations represent the first-responder functions ",
              "type": "text"
            },
            {
              "code": "cut(_ sender: Any?)",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "copy(_ sender: Any?)",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "paste(_ sender: Any?)",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "delete(_ sender: Any?)",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample implements ",
              "type": "text"
            },
            {
              "code": "canPerformAction:withSender:",
              "type": "codeVoice"
            },
            {
              "text": " to determine if these edit operations are supported.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func canPerformAction(_ action: Selector, withSender sender: Any?) -> Bool {",
            "    if action == #selector(printContent) {",
            "        // Allow for printing if a table view cell is selected.",
            "        return tableView.indexPathForSelectedRow != nil",
            "    } else if action == #selector(newAction(_:)) {",
            "        // User wants to perform a New operation.",
            "        return true",
            "    } else {",
            "        switch (tableView.indexPathForSelectedRow, action) {",
            "        ",
            "        // These Edit commands are supported.",
            "        case let (_?, action) where action == #selector(cut(_:)) ||",
            "                                    action == #selector(copy(_:)) ||",
            "                                    action == #selector(delete(_:)):",
            "            return true",
            "        case (_?, _):",
            "            // Allow the nextResponder to make the determination.",
            "            return super.canPerformAction(action, withSender: sender)",
            "            ",
            "        // Paste is supported if the pasteboard has text.",
            "        case (.none, action) where action == #selector(paste(_:)):",
            "            return (UIPasteboard.general.string != nil) ? true :",
            "                // Allow the nextResponder to make the determination.",
            "                super.canPerformAction(action, withSender: sender)",
            "        case (.none, _):",
            "            return false",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Add-commands-to-control-the-user-interface",
          "level": 3,
          "text": "Add commands to control the user interface",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In the sample, you can change the primary or left-side table view’s selection by using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". These key commands are connected to the up and down arrow keys and are added directly to the table view. The following example shows how to add the down arrow key as a ",
              "type": "text"
            },
            {
              "code": "UIKeyCommand",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let downArrowCommand =",
            "    UIKeyCommand(input: UIKeyCommand.inputDownArrow,",
            "                 modifierFlags: [],",
            "                 action: #selector(PrimaryViewController.downArrowAction(_:)))",
            "addKeyCommand(downArrowCommand)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The sample also demonstrates how to add menu commands as command-key equivalents. The following example shows how to create a menu with all four arrow keys as command keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class func navigationMenu() -> UIMenu {",
            "    let keyCommands = [ UIKeyCommand.inputRightArrow,",
            "                        UIKeyCommand.inputLeftArrow,",
            "                        UIKeyCommand.inputUpArrow,",
            "                        UIKeyCommand.inputDownArrow ]",
            "    let arrows = Arrows.allCases",
            "    ",
            "    let arrowKeyChildrenCommands = zip(keyCommands, arrows).map { (command, arrow) in",
            "        UIKeyCommand(title: arrow.localizedString(),",
            "                     image: nil,",
            "                     action: #selector(AppDelegate.navigationMenuAction(_:)),",
            "                     input: command,",
            "                     modifierFlags: .command,",
            "                     propertyList: [CommandPListKeys.ArrowsKeyIdentifier: arrow.rawValue])",
            "    }",
            "    ",
            "    let arrowKeysGroup = UIMenu(title: \"\",",
            "                  image: nil,",
            "                  identifier: .arrowsMenu,",
            "                  options: .displayInline,",
            "                  children: arrowKeyChildrenCommands)",
            "    ",
            "    return UIMenu(title: NSLocalizedString(\"NavigationTitle\", comment: \"\"),",
            "                  image: nil,",
            "                  identifier: .navMenu,",
            "                  options: [],",
            "                  children: [arrowKeysGroup])",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Display-contextual-menus",
          "level": 3,
          "text": "Display contextual menus",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample displays a contextual menu through the use of ",
              "type": "text"
            },
            {
              "code": "UIContextMenuInteractionDelegate",
              "type": "codeVoice"
            },
            {
              "text": ", an interaction object used to display relevant actions for the content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For macOS, the user control-clicks or right-clicks the ",
              "type": "text"
            },
            {
              "code": "DetailViewController",
              "type": "codeVoice"
            },
            {
              "text": ". For iPadOS, the user taps and holds the ",
              "type": "text"
            },
            {
              "code": "DetailViewController",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The sample uses ",
              "type": "text"
            },
            {
              "code": "UIContextMenuInteractionDelegate",
              "type": "codeVoice"
            },
            {
              "text": " to display Cut, Copy, Paste, Delete, Rename, and Share commands. This kind of contextual menu is a grouping of ",
              "type": "text"
            },
            {
              "code": "UIAction",
              "type": "codeVoice"
            },
            {
              "text": " objects. ",
              "type": "text"
            },
            {
              "code": "UIAction",
              "type": "codeVoice"
            },
            {
              "text": " is a menu element that performs its action in a closure. In iOS, optionally customize this contextual menu’s highlight preview by using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate/contextMenuInteraction(_:previewForHighlightingMenuWithConfiguration:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This delegate function returns a primary view controller. Override this function to enable menu commands based on the table view state or the state of the pasteboard.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Adjust-the-style-menu",
          "level": 3,
          "text": "Adjust the style menu",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample implements ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResponder/validate(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", where it can adjust the Style menu as the user selects between one or more font styles: plain, bold, italic, underline.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// The font style menu item check marks used in the Style menu.",
            "var fontMenuStyleStates = Set<String>()",
            "",
            "// Update the state of a given command by adjusting the Style menu.",
            "// Note: Only command groups that are added will be called to validate.",
            "override func validate(_ command: UICommand) {",
            "    // Obtain the plist of the incoming command.",
            "",
            "    if let fontStyleDict = command.propertyList as? [String: String] {",
            "        // Check if the command comes from the Style menu.",
            "        if let fontStyle = fontStyleDict[MenuController.CommandPListKeys.StylesIdentifierKey] {",
            "            // Update the Style menu command state (checked or unchecked).",
            "            command.state = fontMenuStyleStates.contains(fontStyle) ? .on : .off",
            "        }",
            "    } else {",
            "        // Validate the disabled command. This keeps the menu item disabled.",
            "        if let commandPlistString = command.propertyList as? String {",
            "            if commandPlistString == MenuController.disabledCommand {",
            "                command.attributes = .disabled",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Add-a-preferences-menu",
          "level": 3,
          "text": "Add a preferences menu",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Mac apps typically display app-specific preferences using a preferences window. The sample adds a preferences window by adding a Settings bundle to the Xcode project’s target. The window automatically becomes available to the user through the Preferences menu command in the Application menu. To learn more about preferences, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/displaying-a-preferences-window",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "5e60ae06106d/AddingMenusAndShortcutsToTheMenuBarAndUserInterface.zip": {
      "checksum": "5e60ae06106da9837513f99e107ac25c158c2af55a88519710461b2584a853b039699b371389fcba40cd1aa0bb80a3c793cd2a9977cb6536fa3d44751b692b33",
      "identifier": "5e60ae06106d/AddingMenusAndShortcutsToTheMenuBarAndUserInterface.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/5e60ae06106d/AddingMenusAndShortcutsToTheMenuBarAndUserInterface.zip"
    },
    "doc://com.apple.documentation/documentation/foundation/nslocalizedstring": {
      "abstract": [
        {
          "text": "Returns a localized version of a string from the default table, which Xcode autogenerates when exporting localizations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nslocalizedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLocalizedString",
      "type": "topic",
      "url": "/documentation/foundation/nslocalizedstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAction": {
      "abstract": [
        {
          "text": "A menu element that performs its action in a closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAction"
        }
      ],
      "role": "symbol",
      "title": "UIAction",
      "type": "topic",
      "url": "/documentation/uikit/uiaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICommand": {
      "abstract": [
        {
          "text": "A menu element that performs its action in a selector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICommand"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICommand"
        }
      ],
      "role": "symbol",
      "title": "UICommand",
      "type": "topic",
      "url": "/documentation/uikit/uicommand"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction": {
      "abstract": [
        {
          "text": "An interaction object that you use to display relevant actions for your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContextMenuInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContextMenuInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIContextMenuInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate": {
      "abstract": [
        {
          "text": "The methods for providing the set of actions to perform on your content, and for customizing the preview of that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContextMenuInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContextMenuInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIContextMenuInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate/contextMenuInteraction(_:previewForHighlightingMenuWithConfiguration:)": {
      "abstract": [
        {
          "text": "Returns the source view to use when animating the appearance of the preview interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextMenuInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIContextMenuInteraction",
          "text": "UIContextMenuInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "previewForHighlightingMenuWithConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIContextMenuConfiguration",
          "text": "UIContextMenuConfiguration"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedPreview",
          "text": "UITargetedPreview"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate/contextMenuInteraction(_:previewForHighlightingMenuWithConfiguration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contextMenuInteraction:previewForHighlightingMenuWithConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "contextMenuInteraction(_:previewForHighlightingMenuWithConfiguration:)",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteractiondelegate/contextmenuinteraction(_:previewforhighlightingmenuwithconfiguration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer that interprets pointer movement over a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIHoverGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIHoverGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UIHoverGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uihovergesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand": {
      "abstract": [
        {
          "text": "An object that specifies a key press perform on a hardware keyboard and the resulting action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyCommand"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyCommand"
        }
      ],
      "role": "symbol",
      "title": "UIKeyCommand",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenuBuilder": {
      "abstract": [
        {
          "text": "An interface for adding and removing menus from a menu system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMenuBuilder"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMenuBuilder"
        }
      ],
      "role": "symbol",
      "title": "UIMenuBuilder",
      "type": "topic",
      "url": "/documentation/uikit/uimenubuilder"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenuSystem": {
      "abstract": [
        {
          "text": "An object representing a main or contextual menu system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMenuSystem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMenuSystem"
        }
      ],
      "role": "symbol",
      "title": "UIMenuSystem",
      "type": "topic",
      "url": "/documentation/uikit/uimenusystem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenuSystem/main": {
      "abstract": [
        {
          "text": "The main menu system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "main"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenuSystem",
          "text": "UIMenuSystem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuSystem/main",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mainSystem"
        }
      ],
      "role": "symbol",
      "title": "main",
      "type": "topic",
      "url": "/documentation/uikit/uimenusystem/main"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIResponder/buildMenu(with:)": {
      "abstract": [
        {
          "text": "Asks the receiving responder to add and remove items from a menu system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buildMenu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIMenuBuilder",
          "text": "UIMenuBuilder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResponder/buildMenu(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buildMenuWithBuilder:"
        }
      ],
      "role": "symbol",
      "title": "buildMenu(with:)",
      "type": "topic",
      "url": "/documentation/uikit/uiresponder/buildmenu(with:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIResponder/validate(_:)": {
      "abstract": [
        {
          "text": "Asks the receiving responder to validate the command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICommand",
          "text": "UICommand"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResponder/validate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateCommand:"
        }
      ],
      "role": "symbol",
      "title": "validate(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiresponder/validate(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/displaying-a-preferences-window": {
      "abstract": [
        {
          "text": "Provide a Preferences window in your Mac app built with Mac Catalyst so users can manage app preferences defined in a Settings bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/displaying-a-preferences-window",
      "kind": "article",
      "role": "article",
      "title": "Displaying a Preferences window",
      "type": "topic",
      "url": "/documentation/uikit/displaying-a-preferences-window"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard": {
      "abstract": [
        {
          "text": "Detect when someone presses and releases keys on a physical keyboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard",
      "kind": "article",
      "role": "article",
      "title": "Handling key presses made on a physical keyboard",
      "type": "topic",
      "url": "/documentation/uikit/handling-key-presses-made-on-a-physical-keyboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/mac-catalyst": {
      "abstract": [
        {
          "text": "Create a version of your iPad app that users can run on a Mac device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/mac-catalyst",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts": {
      "abstract": [
        {
          "text": "Simplify interactions with your app using menu systems, contextual menus, Home Screen quick actions, and keyboard shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Menus and shortcuts",
      "type": "topic",
      "url": "/documentation/uikit/menus-and-shortcuts"
    },
    "doc://com.apple.uikit/documentation/UIKit/navigating-an-app-s-user-interface-using-a-keyboard": {
      "abstract": [
        {
          "text": "Navigate between user interface elements using a keyboard and focusable UI elements in iPad apps and apps built with Mac Catalyst.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/navigating-an-app-s-user-interface-using-a-keyboard",
      "kind": "article",
      "role": "sampleCode",
      "title": "Navigating an app’s user interface using a keyboard",
      "type": "topic",
      "url": "/documentation/uikit/navigating-an-app-s-user-interface-using-a-keyboard"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "5e60ae06106d/AddingMenusAndShortcutsToTheMenuBarAndUserInterface.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/navigating-an-app-s-user-interface-using-a-keyboard",
        "doc://com.apple.uikit/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard",
        "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer"
      ],
      "title": "User interactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard",
                "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer"
              ],
              "title": "User interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/title",
          "value": "UIAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand/title",
          "value": "UIKeyCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICommand/title",
          "value": "UICommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1buildMenu(with:)/title",
          "value": "buildMenuWithBuilder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1buildMenu(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "buildMenuWithBuilder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1validate(_:)/title",
          "value": "validateCommand:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1validate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateCommand:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction/title",
          "value": "UIContextMenuInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate~1contextMenuInteraction(_:previewForHighlightingMenuWithConfiguration:)/title",
          "value": "contextMenuInteraction:previewForHighlightingMenuWithConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate~1contextMenuInteraction(_:previewForHighlightingMenuWithConfiguration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contextMenuInteraction:previewForHighlightingMenuWithConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate/title",
          "value": "UIContextMenuInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuBuilder/title",
          "value": "UIMenuBuilder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuBuilder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuBuilder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverGestureRecognizer/title",
          "value": "UIHoverGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIHoverGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIHoverGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuSystem~1main/title",
          "value": "mainSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuSystem~1main/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mainSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuSystem/title",
          "value": "UIMenuSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuSystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuSystem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/adding-menus-and-shortcuts-to-the-menu-bar-and-user-interface"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/adding-menus-and-shortcuts-to-the-menu-bar-and-user-interface"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
