{
  "abstract": [
    {
      "text": "Adopt Dark Mode in your iOS app by using dynamic colors and visual effects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/appearance-customization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/adopting-ios-dark-mode"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Adopting iOS Dark Mode"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC 2019 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc19/214",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "01d83ac2d393/AdoptingIOSDarkMode.zip": {
      "checksum": "01d83ac2d393d6bd55afa17650840d110768d8f6ba9d772cbeba82a7f9e9ca025a6fa0da0be6dbd0c26df4f125eca644864e205e7331a84612b3dc0215b4d491",
      "identifier": "01d83ac2d393/AdoptingIOSDarkMode.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/01d83ac2d393/AdoptingIOSDarkMode.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/appearance-customization": {
      "abstract": [
        {
          "text": "Add Dark Mode support to your app, customize the appearance of bars, and use appearance proxies to modify your UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/appearance-customization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Appearance customization",
      "type": "topic",
      "url": "/documentation/uikit/appearance-customization"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-dark-mode-in-your-interface": {
      "abstract": [
        {
          "text": "Update colors, images, and behaviors so that your app adapts automatically when Dark Mode is active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-dark-mode-in-your-interface",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Supporting Dark Mode in Your Interface",
      "type": "topic",
      "url": "/documentation/uikit/supporting-dark-mode-in-your-interface"
    },
    "https://developer.apple.com/wwdc19/214": {
      "identifier": "https://developer.apple.com/wwdc19/214",
      "title": "214: Implementing Dark Mode on iOS",
      "titleInlineContent": [
        {
          "text": "214: Implementing Dark Mode on iOS",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc19/214"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "01d83ac2d393/AdoptingIOSDarkMode.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Dark-Mode",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-dark-mode-in-your-interface"
      ],
      "title": "Dark Mode"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Dark-Mode",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/supporting-dark-mode-in-your-interface"
              ],
              "title": "Dark Mode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/adopting-ios-dark-mode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/adopting-ios-dark-mode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
