{
  "abstract": [
    {
      "text": "Learn how to use a delegate object to allow detection of more than one gesture at a time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures",
        "doc://com.apple.uikit/documentation/UIKit/coordinating-multiple-gesture-recognizers"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/allowing-the-simultaneous-recognition-of-multiple-gestures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Allowing the simultaneous recognition of multiple gestures"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There are times when it makes sense to allow the simultaneous recognition of multiple gestures. The following image shows an app that allows people to drag, scale, and rotate three views onscreen. Each view maintains its own unique set of pan, pinch, and rotate gesture recognizers, and it’s possible for all three of a view’s gesture recognizers to perform their actions simultaneously.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2880130",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To allow a gesture recognizer to operate simultaneously with other gestures, assign a delegate object that implements the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizerDelegate/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to it. UIKit calls this method for pairs of gesture recognizers attached to the same view. Returning true allows both gestures to process events simultaneously.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizerDelegate/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method from the app shown in the previous image. This method returns true when the gesture recognizers are attached to the same view. If the gesture recognizers are attached to different views, or if one of the objects is a long press gesture recognizer, this method returns false.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer,",
            "       shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer)",
            "        -> Bool {",
            "   // If the gesture recognizer's view isn't one of the squares, do not",
            "   // allow simultaneous recognition.",
            "   if gestureRecognizer.view != self.yellowView && ",
            "            gestureRecognizer.view != self.cyanView && ",
            "            gestureRecognizer.view != self.magentaView {",
            "      return false",
            "   }",
            "   // If the gesture recognizers are on diferent views, do not allow",
            "   // simultaneous recognition.",
            "   if gestureRecognizer.view != otherGestureRecognizer.view {",
            "      return false",
            "   }",
            "   // If either gesture recognizer is a long press, do not allow",
            "   // simultaneous recognition.",
            "   if gestureRecognizer is UILongPressGestureRecognizer || ",
            "          otherGestureRecognizer is UILongPressGestureRecognizer {",
            "      return false",
            "   }",
            " ",
            "   return true",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about the sample, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/samplecode/Touches/Introduction/Intro.html#//apple_ref/doc/uid/DTS40007435",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizerDelegate/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)": {
      "abstract": [
        {
          "text": "Asks the delegate if two gesture recognizers should be allowed to recognize gestures simultaneously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gestureRecognizer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGestureRecognizer",
          "text": "UIGestureRecognizer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldRecognizeSimultaneouslyWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGestureRecognizer",
          "text": "UIGestureRecognizer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizerDelegate/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"
        }
      ],
      "role": "symbol",
      "title": "gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uigesturerecognizerdelegate/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/attaching-gesture-recognizers-to-uikit-controls": {
      "abstract": [
        {
          "text": "Learn how gesture recognizers interact with UIKit controls such as buttons switches and sliders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/attaching-gesture-recognizers-to-uikit-controls",
      "kind": "article",
      "role": "article",
      "title": "Attaching gesture recognizers to UIKit controls",
      "type": "topic",
      "url": "/documentation/uikit/attaching-gesture-recognizers-to-uikit-controls"
    },
    "doc://com.apple.uikit/documentation/UIKit/coordinating-multiple-gesture-recognizers": {
      "abstract": [
        {
          "text": "Discover how to use multiple gesture recognizers on the same view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/coordinating-multiple-gesture-recognizers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Coordinating multiple gesture recognizers",
      "type": "topic",
      "url": "/documentation/uikit/coordinating-multiple-gesture-recognizers"
    },
    "doc://com.apple.uikit/documentation/UIKit/preferring-one-gesture-over-another": {
      "abstract": [
        {
          "text": "Use a gesture recognizer delegate object to determine the order in which gestures are recognized in your views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/preferring-one-gesture-over-another",
      "kind": "article",
      "role": "article",
      "title": "Preferring one gesture over another",
      "type": "topic",
      "url": "/documentation/uikit/preferring-one-gesture-over-another"
    },
    "doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures": {
      "abstract": [
        {
          "text": "Encapsulate your app’s event-handling logic in gesture recognizers so that you can reuse that code throughout your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Touches, presses, and gestures",
      "type": "topic",
      "url": "/documentation/uikit/touches-presses-and-gestures"
    },
    "https://developer.apple.com/library/archive/samplecode/Touches/Introduction/Intro.html#//apple_ref/doc/uid/DTS40007435": {
      "identifier": "https://developer.apple.com/library/archive/samplecode/Touches/Introduction/Intro.html#//apple_ref/doc/uid/DTS40007435",
      "title": "Handling Touches Using Responder Methods and Gesture Recognizers",
      "titleInlineContent": [
        {
          "text": "Handling Touches Using Responder Methods and Gesture Recognizers",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/samplecode/Touches/Introduction/Intro.html#//apple_ref/doc/uid/DTS40007435"
    },
    "media-2880130": {
      "alt": "A screenshot of an app that demonstrates how a person can use rotation, pinch and pan gestures simultaneously to control the appearance of a pink square.",
      "identifier": "media-2880130",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8559fcb4402d0499f4e131301b8d0e58/media-2880130@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Simultaneous-gestures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/preferring-one-gesture-over-another",
        "doc://com.apple.uikit/documentation/UIKit/attaching-gesture-recognizers-to-uikit-controls"
      ],
      "title": "Simultaneous gestures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Simultaneous-gestures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/preferring-one-gesture-over-another",
                "doc://com.apple.uikit/documentation/UIKit/attaching-gesture-recognizers-to-uikit-controls"
              ],
              "title": "Simultaneous gestures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizerDelegate~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)/title",
          "value": "gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizerDelegate~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/allowing-the-simultaneous-recognition-of-multiple-gestures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/allowing-the-simultaneous-recognition-of-multiple-gestures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
