{
  "abstract": [
    {
      "text": "Provide feedback to users using view-based animations and haptics.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Animation and haptics"
  },
  "references": {
    "Unifying-your-app-s-animations-PageImage-card.png": {
      "alt": null,
      "identifier": "Unifying-your-app-s-animations-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3559438f813d2163ecacac3918dbff5f/Unifying-your-app-s-animations-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/db26bd6bfe171a450c126a68c3bd92d4/Unifying-your-app-s-animations-PageImage-card@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/ApplePencil/playing-haptic-feedback-in-your-app": {
      "abstract": [
        {
          "text": "Provide tactile feedback when people perform certain actions in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ApplePencil/playing-haptic-feedback-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Playing haptic feedback in your app",
      "type": "topic",
      "url": "/documentation/ApplePencil/playing-haptic-feedback-in-your-app"
    },
    "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro": {
      "abstract": [
        {
          "text": "Provide custom animated content for ProMotion displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro",
      "kind": "article",
      "role": "article",
      "title": "Optimizing ProMotion refresh rates for iPhone 13 Pro and iPad Pro",
      "type": "topic",
      "url": "/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Unifying-your-app-s-animations": {
      "abstract": [
        {
          "text": "Create a consistent UI animation experience across SwiftUI, UIKit, and AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Unifying-your-app-s-animations",
      "images": [
        {
          "identifier": "Unifying-your-app-s-animations-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Unifying your app’s animations",
      "type": "topic",
      "url": "/documentation/SwiftUI/Unifying-your-app-s-animations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator": {
      "abstract": [
        {
          "text": "A concrete feedback generator subclass that creates haptics to indicate events on a drawing canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICanvasFeedbackGenerator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICanvasFeedbackGenerator"
        }
      ],
      "role": "symbol",
      "title": "UICanvasFeedbackGenerator",
      "type": "topic",
      "url": "/documentation/uikit/uicanvasfeedbackgenerator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator": {
      "abstract": [
        {
          "text": "The abstract superclass for all feedback generators.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFeedbackGenerator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFeedbackGenerator"
        }
      ],
      "role": "symbol",
      "title": "UIFeedbackGenerator",
      "type": "topic",
      "url": "/documentation/uikit/uifeedbackgenerator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator": {
      "abstract": [
        {
          "text": "A concrete feedback generator subclass that creates haptics to simulate physical impacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImpactFeedbackGenerator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImpactFeedbackGenerator"
        }
      ],
      "role": "symbol",
      "title": "UIImpactFeedbackGenerator",
      "type": "topic",
      "url": "/documentation/uikit/uiimpactfeedbackgenerator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator": {
      "abstract": [
        {
          "text": "A concrete feedback generator subclass that creates haptics to communicate successes, failures, and warnings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UINotificationFeedbackGenerator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINotificationFeedbackGenerator"
        }
      ],
      "role": "symbol",
      "title": "UINotificationFeedbackGenerator",
      "type": "topic",
      "url": "/documentation/uikit/uinotificationfeedbackgenerator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator": {
      "abstract": [
        {
          "text": "A concrete feedback generator subclass that creates haptics to indicate a change in selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISelectionFeedbackGenerator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISelectionFeedbackGenerator"
        }
      ],
      "role": "symbol",
      "title": "UISelectionFeedbackGenerator",
      "type": "topic",
      "url": "/documentation/uikit/uiselectionfeedbackgenerator"
    },
    "doc://com.apple.uikit/documentation/UIKit/appearance-customization": {
      "abstract": [
        {
          "text": "Add Dark Mode support to your app, customize the appearance of bars, and use appearance proxies to modify your UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/appearance-customization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Appearance customization",
      "type": "topic",
      "url": "/documentation/uikit/appearance-customization"
    },
    "doc://com.apple.uikit/documentation/UIKit/motion-effects": {
      "abstract": [
        {
          "text": "Add subtle motion to views to provide a 3D appearance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/motion-effects",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Motion effects",
      "type": "topic",
      "url": "/documentation/uikit/motion-effects"
    },
    "doc://com.apple.uikit/documentation/UIKit/property-based-animations": {
      "abstract": [
        {
          "text": "Create animations by changing the properties of a view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/property-based-animations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property-based animations",
      "type": "topic",
      "url": "/documentation/uikit/property-based-animations"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-dynamics": {
      "abstract": [
        {
          "text": "Apply physics-based animations to your views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-dynamics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit Dynamics",
      "type": "topic",
      "url": "/documentation/uikit/uikit-dynamics"
    },
    "doc://com.apple.uikit/documentation/UIKit/view-controller-transitions": {
      "abstract": [
        {
          "text": "Define custom transitions from one view controller to another.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/view-controller-transitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View controller transitions",
      "type": "topic",
      "url": "/documentation/uikit/view-controller-transitions"
    },
    "doc://com.apple.uikit/documentation/UIKit/view-controllers": {
      "abstract": [
        {
          "text": "Manage your interface using view controllers and facilitate navigation around your app’s content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/view-controllers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View controllers",
      "type": "topic",
      "url": "/documentation/uikit/view-controllers"
    },
    "doc://com.apple.uikit/documentation/UIKit/view-layout": {
      "abstract": [
        {
          "text": "Use stack views to lay out the views of your interface automatically. Use Auto Layout when you require precise placement of your views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/view-layout",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View layout",
      "type": "topic",
      "url": "/documentation/uikit/view-layout"
    },
    "doc://com.apple.uikit/documentation/UIKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and define the interactions allowed with that content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and controls",
      "type": "topic",
      "url": "/documentation/uikit/views-and-controls"
    },
    "doc://com.apple.uikit/documentation/UIKit/windows-and-screens": {
      "abstract": [
        {
          "text": "Provide a container for your view hierarchies and other content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/windows-and-screens",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Windows and screens",
      "type": "topic",
      "url": "/documentation/uikit/windows-and-screens"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
        "doc://com.apple.uikit/documentation/UIKit/view-controllers",
        "doc://com.apple.uikit/documentation/UIKit/view-layout",
        "doc://com.apple.uikit/documentation/UIKit/appearance-customization",
        "doc://com.apple.uikit/documentation/UIKit/windows-and-screens"
      ],
      "title": "User interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Content-animations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/property-based-animations",
        "doc://com.apple.uikit/documentation/UIKit/view-controller-transitions",
        "doc://com.apple.documentation/documentation/SwiftUI/Unifying-your-app-s-animations",
        "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
      ],
      "title": "Content animations"
    },
    {
      "anchor": "Physics-based-animations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/uikit-dynamics"
      ],
      "title": "Physics-based animations"
    },
    {
      "anchor": "Parallax-effects",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/motion-effects"
      ],
      "title": "Parallax effects"
    },
    {
      "anchor": "Haptic-feedback",
      "identifiers": [
        "doc://com.apple.documentation/documentation/ApplePencil/playing-haptic-feedback-in-your-app",
        "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator",
        "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator",
        "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator",
        "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator",
        "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator"
      ],
      "title": "Haptic feedback"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Content-animations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/property-based-animations",
                "doc://com.apple.uikit/documentation/UIKit/view-controller-transitions",
                "doc://com.apple.documentation/documentation/SwiftUI/Unifying-your-app-s-animations",
                "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
              ],
              "title": "Content animations"
            },
            {
              "anchor": "Physics-based-animations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/uikit-dynamics"
              ],
              "title": "Physics-based animations"
            },
            {
              "anchor": "Parallax-effects",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/motion-effects"
              ],
              "title": "Parallax effects"
            },
            {
              "anchor": "Haptic-feedback",
              "identifiers": [
                "doc://com.apple.documentation/documentation/ApplePencil/playing-haptic-feedback-in-your-app",
                "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator",
                "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator",
                "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator",
                "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator",
                "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator"
              ],
              "title": "Haptic feedback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
                "doc://com.apple.uikit/documentation/UIKit/view-controllers",
                "doc://com.apple.uikit/documentation/UIKit/view-layout",
                "doc://com.apple.uikit/documentation/UIKit/appearance-customization",
                "doc://com.apple.uikit/documentation/UIKit/windows-and-screens"
              ],
              "title": "User interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator/title",
          "value": "UIFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator/title",
          "value": "UIImpactFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImpactFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImpactFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISelectionFeedbackGenerator/title",
          "value": "UISelectionFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISelectionFeedbackGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISelectionFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISelectionFeedbackGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISelectionFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICanvasFeedbackGenerator/title",
          "value": "UICanvasFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICanvasFeedbackGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICanvasFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICanvasFeedbackGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICanvasFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINotificationFeedbackGenerator/title",
          "value": "UINotificationFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINotificationFeedbackGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINotificationFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINotificationFeedbackGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINotificationFeedbackGenerator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/animation-and-haptics"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/animation-and-haptics"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
