{
  "abstract": [
    {
      "text": "Manage life-cycle events and your app’s UI scenes, and get information about traits and the environment in which your app runs.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/app-and-environment"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "App and environment"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 13 and later, a person can create and manage multiple instances of your app’s user interface simultaneously, and switch between them using the app switcher. On iPad, a person can also display multiple instances of your app side by side. Each instance of your UI displays different content, or displays the same content in a different way. For example, a person can display one instance of the Calendar app showing a specific day, and another showing an entire month.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "UIKit communicates details about the current environment using ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "trait collections",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", which reflect a combination of device settings, interface settings, and user preferences. For example, you use traits to detect whether Dark Mode is active for the current view or view controller. Consult the current trait collection of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object when you want to customize its contents based on the current environment. Adopt the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol in other objects when you want them to receive trait notification changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/guidedAccessRestrictionState(forIdentifier:)": {
      "abstract": [
        {
          "text": "Returns the restriction state for the specified guided access restriction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "guidedAccessRestrictionState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIGuidedAccessRestrictionState",
          "text": "GuidedAccessRestrictionState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/guidedAccessRestrictionState(forIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGuidedAccessRestrictionStateForIdentifier"
        }
      ],
      "role": "symbol",
      "title": "guidedAccessRestrictionState(forIdentifier:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/guidedaccessrestrictionstate(foridentifier:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate": {
      "abstract": [
        {
          "text": "A set of methods that, in conjunction with a presentation controller, determine how to respond to trait changes in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAdaptivePresentationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAdaptivePresentationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIAdaptivePresentationControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiadaptivepresentationcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps running in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "role": "symbol",
      "title": "UIApplication",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate": {
      "abstract": [
        {
          "text": "A set of methods to manage shared behaviors for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationMain(_:_:_:_:)-1yub7": {
      "abstract": [
        {
          "text": "Creates the application object and the application delegate and sets up the event cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplicationMain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationMain(_:_:_:_:)-1yub7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationMain"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationMain(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationmain(_:_:_:_:)-1yub7"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICGFloatTraitDefinition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICGFloatTraitDefinition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICGFloatTraitDefinition",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICGFloatTraitDefinition",
      "type": "topic",
      "url": "/documentation/uikit/uicgfloattraitdefinition"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentContainer": {
      "abstract": [
        {
          "text": "A set of methods for adapting the contents of your view controllers to size and trait changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        }
      ],
      "role": "symbol",
      "title": "UIContentContainer",
      "type": "topic",
      "url": "/documentation/uikit/uicontentcontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice": {
      "abstract": [
        {
          "text": "A representation of the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDevice"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDevice"
        }
      ],
      "role": "symbol",
      "title": "UIDevice",
      "type": "topic",
      "url": "/documentation/uikit/uidevice"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessRestrictionDelegate": {
      "abstract": [
        {
          "text": "A set of methods you use to add custom restrictions for the Guided Access feature in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGuidedAccessRestrictionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessRestrictionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGuidedAccessRestrictionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIGuidedAccessRestrictionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiguidedaccessrestrictiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5": {
      "abstract": [
        {
          "text": "A mutable container of traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMutableTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMutableTraits"
        }
      ],
      "role": "symbol",
      "title": "UIMutableTraits",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-13ja5"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIMutableTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIMutableTraits",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINSIntegerTraitDefinition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UINSIntegerTraitDefinition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINSIntegerTraitDefinition",
      "kind": "symbol",
      "role": "symbol",
      "title": "UINSIntegerTraitDefinition",
      "type": "topic",
      "url": "/documentation/uikit/uinsintegertraitdefinition"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIObjectTraitDefinition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIObjectTraitDefinition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIObjectTraitDefinition",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIObjectTraitDefinition",
      "type": "topic",
      "url": "/documentation/uikit/uiobjecttraitdefinition"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarManager": {
      "abstract": [
        {
          "text": "An object that describes the configuration of the status bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStatusBarManager"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStatusBarManager"
        }
      ],
      "role": "symbol",
      "title": "UIStatusBarManager",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITrait-1dbah": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITrait"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITrait-1dbah",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITrait",
      "type": "topic",
      "url": "/documentation/uikit/uitrait-1dbah"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITrait-9423": {
      "abstract": [
        {
          "text": "A type representing a trait in a trait collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITrait"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITrait-9423",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITrait"
        }
      ],
      "role": "symbol",
      "title": "UITrait",
      "type": "topic",
      "url": "/documentation/uikit/uitrait-9423"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-7qoet"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection": {
      "abstract": [
        {
          "text": "A collection of data that represents the environment for an individual element in your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitCollection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitCollection"
        }
      ],
      "role": "symbol",
      "title": "UITraitCollection",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitDefinition-3572h": {
      "abstract": [
        {
          "text": "A type representing a trait in a trait collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitDefinition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitDefinition-3572h",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitDefinition",
      "type": "topic",
      "url": "/documentation/uikit/uitraitdefinition-3572h"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitDefinition-64c15": {
      "abstract": [
        {
          "text": "A type representing a trait in a trait collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitDefinition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitDefinition-64c15",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitDefinition"
        }
      ],
      "role": "symbol",
      "title": "UITraitDefinition",
      "type": "topic",
      "url": "/documentation/uikit/uitraitdefinition-64c15"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uitraitenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/app-extensions": {
      "abstract": [
        {
          "text": "Extend your app’s basic functionality to other parts of the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/app-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App extensions",
      "type": "topic",
      "url": "/documentation/uikit/app-extensions"
    },
    "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking": {
      "abstract": [
        {
          "text": "Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Automatic trait tracking",
      "type": "topic",
      "url": "/documentation/uikit/automatic-trait-tracking"
    },
    "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app": {
      "abstract": [
        {
          "text": "Optimize your iPad app’s user experience by adopting desktop-class enhancements for multitasking with Stage Manager, document interactions, text editing, search, and more in iPadOS 16.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app",
      "kind": "article",
      "role": "article",
      "title": "Building a desktop-class iPad app",
      "type": "topic",
      "url": "/documentation/uikit/building-a-desktop-class-ipad-app"
    },
    "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard": {
      "abstract": [
        {
          "text": "Organize your app’s data and share that data on the pasteboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Documents, data, and pasteboard",
      "type": "topic",
      "url": "/documentation/uikit/documents-data-and-pasteboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar": {
      "abstract": [
        {
          "text": "Provide a compact, ergonomic tab bar for quick access to key parts of your app, and a sidebar for in-depth navigation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar",
      "kind": "article",
      "role": "article",
      "title": "Elevating your iPad app with a tab bar and sidebar",
      "type": "topic",
      "url": "/documentation/uikit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar"
    },
    "doc://com.apple.uikit/documentation/UIKit/interprocess-communication": {
      "abstract": [
        {
          "text": "Display activity-based services to people.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/interprocess-communication",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interprocess communication",
      "type": "topic",
      "url": "/documentation/uikit/interprocess-communication"
    },
    "doc://com.apple.uikit/documentation/UIKit/mac-catalyst": {
      "abstract": [
        {
          "text": "Create a version of your iPad app that users can run on a Mac device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/mac-catalyst",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/managing-your-app-s-life-cycle": {
      "abstract": [
        {
          "text": "Respond to system notifications when your app is in the foreground or background, and handle other significant system-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/managing-your-app-s-life-cycle",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Managing your app’s life cycle",
      "type": "topic",
      "url": "/documentation/uikit/managing-your-app-s-life-cycle"
    },
    "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad": {
      "abstract": [
        {
          "text": "Implement multitasking APIs to seamlessly integrate your app with iPadOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multitasking on iPad",
      "type": "topic",
      "url": "/documentation/uikit/multitasking-on-ipad"
    },
    "doc://com.apple.uikit/documentation/UIKit/resource-management": {
      "abstract": [
        {
          "text": "Manage the images, strings, storyboards, and nib files that you use to implement your app’s interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/resource-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resource management",
      "type": "topic",
      "url": "/documentation/uikit/resource-management"
    },
    "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv": {
      "abstract": [
        {
          "text": "Change images and resources dynamically when the screen gamut on your device changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv",
      "kind": "article",
      "role": "article",
      "title": "Responding to changing display modes on Apple TV",
      "type": "topic",
      "url": "/documentation/uikit/responding-to-changing-display-modes-on-apple-tv"
    },
    "doc://com.apple.uikit/documentation/UIKit/responding-to-the-launch-of-your-app": {
      "abstract": [
        {
          "text": "Initialize your app’s data structures, prepare your app to run, and respond to any launch-time requests from the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/responding-to-the-launch-of-your-app",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Responding to the launch of your app",
      "type": "topic",
      "url": "/documentation/uikit/responding-to-the-launch-of-your-app"
    },
    "doc://com.apple.uikit/documentation/UIKit/scenes": {
      "abstract": [
        {
          "text": "Manage multiple instances of your app’s UI simultaneously, and direct resources to the appropriate instance of your UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/scenes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Scenes",
      "type": "topic",
      "url": "/documentation/uikit/scenes"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-desktop-class-features-in-your-ipad-app": {
      "abstract": [
        {
          "text": "Enhance your iPad app by adding desktop-class features and document support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-desktop-class-features-in-your-ipad-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting desktop-class features in your iPad app",
      "type": "topic",
      "url": "/documentation/uikit/supporting-desktop-class-features-in-your-ipad-app"
    },
    "doc://com.apple.uikit/documentation/UIKit/updating-your-app-from-32-bit-to-64-bit-architecture": {
      "abstract": [
        {
          "text": "Ensure that your app behaves as expected by adapting it to support later versions of the operating system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/updating-your-app-from-32-bit-to-64-bit-architecture",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Updating your app from 32-bit to 64-bit architecture",
      "type": "topic",
      "url": "/documentation/uikit/updating-your-app-from-32-bit-to-64-bit-architecture"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-structure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
        "doc://com.apple.uikit/documentation/UIKit/resource-management",
        "doc://com.apple.uikit/documentation/UIKit/app-extensions",
        "doc://com.apple.uikit/documentation/UIKit/interprocess-communication",
        "doc://com.apple.uikit/documentation/UIKit/mac-catalyst"
      ],
      "title": "App structure"
    }
  ],
  "topicSections": [
    {
      "anchor": "Life-cycle",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/managing-your-app-s-life-cycle",
        "doc://com.apple.uikit/documentation/UIKit/responding-to-the-launch-of-your-app",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate",
        "doc://com.apple.uikit/documentation/UIKit/scenes"
      ],
      "title": "Life cycle"
    },
    {
      "anchor": "Device-environment",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDevice",
        "doc://com.apple.uikit/documentation/UIKit/UIStatusBarManager"
      ],
      "title": "Device environment"
    },
    {
      "anchor": "Adaptivity",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking",
        "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv",
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection",
        "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5",
        "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIContentContainer"
      ],
      "title": "Adaptivity"
    },
    {
      "anchor": "Custom-traits",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5",
        "doc://com.apple.uikit/documentation/UIKit/UITrait-9423",
        "doc://com.apple.uikit/documentation/UIKit/UITraitDefinition-64c15"
      ],
      "title": "Custom traits"
    },
    {
      "anchor": "iPad",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app",
        "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar",
        "doc://com.apple.uikit/documentation/UIKit/supporting-desktop-class-features-in-your-ipad-app",
        "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad"
      ],
      "title": "iPad"
    },
    {
      "anchor": "Guided-Access",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessRestrictionDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/guidedAccessRestrictionState(forIdentifier:)"
      ],
      "title": "Guided Access"
    },
    {
      "anchor": "Architecture",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/updating-your-app-from-32-bit-to-64-bit-architecture",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationMain(_:_:_:_:)-1yub7"
      ],
      "title": "Architecture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Life-cycle",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/managing-your-app-s-life-cycle",
                "doc://com.apple.uikit/documentation/UIKit/responding-to-the-launch-of-your-app",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate",
                "doc://com.apple.uikit/documentation/UIKit/scenes"
              ],
              "title": "Life cycle"
            },
            {
              "anchor": "Device-environment",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDevice",
                "doc://com.apple.uikit/documentation/UIKit/UIStatusBarManager"
              ],
              "title": "Device environment"
            },
            {
              "anchor": "Adaptivity",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking",
                "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv",
                "doc://com.apple.uikit/documentation/UIKit/UITraitCollection",
                "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
                "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet",
                "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o",
                "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIContentContainer"
              ],
              "title": "Adaptivity"
            },
            {
              "anchor": "Custom-traits",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITrait-1dbah",
                "doc://com.apple.uikit/documentation/UIKit/UITraitDefinition-3572h",
                "doc://com.apple.uikit/documentation/UIKit/UIObjectTraitDefinition",
                "doc://com.apple.uikit/documentation/UIKit/UICGFloatTraitDefinition",
                "doc://com.apple.uikit/documentation/UIKit/UINSIntegerTraitDefinition"
              ],
              "title": "Custom traits"
            },
            {
              "anchor": "iPad",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app",
                "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar",
                "doc://com.apple.uikit/documentation/UIKit/supporting-desktop-class-features-in-your-ipad-app",
                "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad"
              ],
              "title": "iPad"
            },
            {
              "anchor": "Guided-Access",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessRestrictionDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/guidedAccessRestrictionState(forIdentifier:)"
              ],
              "title": "Guided Access"
            },
            {
              "anchor": "Architecture",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/updating-your-app-from-32-bit-to-64-bit-architecture",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationMain(_:_:_:_:)-1yub7"
              ],
              "title": "Architecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-structure",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
                "doc://com.apple.uikit/documentation/UIKit/resource-management",
                "doc://com.apple.uikit/documentation/UIKit/app-extensions",
                "doc://com.apple.uikit/documentation/UIKit/interprocess-communication",
                "doc://com.apple.uikit/documentation/UIKit/mac-catalyst"
              ],
              "title": "App structure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/title",
          "value": "UIContentContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarManager/title",
          "value": "UIStatusBarManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/title",
          "value": "UITraitCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/title",
          "value": "UIViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/title",
          "value": "UITraitEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessRestrictionDelegate/title",
          "value": "UIGuidedAccessRestrictionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessRestrictionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessRestrictionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessRestrictionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessRestrictionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice/title",
          "value": "UIDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/title",
          "value": "UIApplicationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAdaptivePresentationControllerDelegate/title",
          "value": "UIAdaptivePresentationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAdaptivePresentationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAdaptivePresentationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAdaptivePresentationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAdaptivePresentationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationMain(_:_:_:_:)-1yub7/title",
          "value": "UIApplicationMain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationMain(_:_:_:_:)-1yub7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationMain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title",
          "value": "UIApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1guidedAccessRestrictionState(forIdentifier:)/title",
          "value": "UIGuidedAccessRestrictionStateForIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1guidedAccessRestrictionState(forIdentifier:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessRestrictionStateForIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/app-and-environment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/app-and-environment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
