{
  "abstract": [
    {
      "text": "Handle user interactions like double tap and squeeze on Apple Pencil.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/apple-pencil-interactions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Apple Pencil interactions"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apple Pencil interactions let a person perform certain actions in your app by double-tapping or squeezing an Apple Pencil. Support Apple Pencil interactions to give people a quick way to perform their preferred action, such as switching between drawing tools, or a custom action that you define in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4403818",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To learn more about supporting double-tap and squeeze interactions, read ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/ApplePencil/handling-double-taps-from-apple-pencil",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/ApplePencil/handling-squeezes-from-apple-pencil",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To learn more about handling touches, read ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-input-from-apple-pencil",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To learn more about incorporating hand-drawn content in your app, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/PencilKit/drawing-with-pencilkit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Only Apple Pencil Pro supports squeeze interactions. The first-generation Apple Pencil doesn’t support Apple Pencil interactions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/ApplePencil/handling-double-taps-from-apple-pencil": {
      "abstract": [
        {
          "text": "Detect and respond to double taps a person makes on Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ApplePencil/handling-double-taps-from-apple-pencil",
      "kind": "article",
      "role": "article",
      "title": "Handling double taps from Apple Pencil",
      "type": "topic",
      "url": "/documentation/ApplePencil/handling-double-taps-from-apple-pencil"
    },
    "doc://com.apple.documentation/documentation/ApplePencil/handling-squeezes-from-apple-pencil": {
      "abstract": [
        {
          "text": "Detect and respond to squeezes a person makes on Apple Pencil Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ApplePencil/handling-squeezes-from-apple-pencil",
      "kind": "article",
      "role": "article",
      "title": "Handling squeezes from Apple Pencil",
      "type": "topic",
      "url": "/documentation/ApplePencil/handling-squeezes-from-apple-pencil"
    },
    "doc://com.apple.documentation/documentation/PencilKit/drawing-with-pencilkit": {
      "abstract": [
        {
          "text": "Add expressive, low-latency drawing to your app using PencilKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PencilKit/drawing-with-pencilkit",
      "kind": "article",
      "role": "sampleCode",
      "title": "Drawing with PencilKit",
      "type": "topic",
      "url": "/documentation/PencilKit/drawing-with-pencilkit"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PencilDoubleTapGestureValue": {
      "abstract": [
        {
          "text": "Describes the value of an Apple Pencil double-tap gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PencilDoubleTapGestureValue"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PencilDoubleTapGestureValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "PencilDoubleTapGestureValue",
      "type": "topic",
      "url": "/documentation/SwiftUI/PencilDoubleTapGestureValue"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PencilHoverPose": {
      "abstract": [
        {
          "text": "A value describing the location and distance of an Apple Pencil hovering in the area above a view’s bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PencilHoverPose"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PencilHoverPose",
      "kind": "symbol",
      "role": "symbol",
      "title": "PencilHoverPose",
      "type": "topic",
      "url": "/documentation/SwiftUI/PencilHoverPose"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PencilPreferredAction": {
      "abstract": [
        {
          "text": "An action that the user prefers to perform after double-tapping their Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PencilPreferredAction"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PencilPreferredAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "PencilPreferredAction",
      "type": "topic",
      "url": "/documentation/SwiftUI/PencilPreferredAction"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGesturePhase": {
      "abstract": [
        {
          "text": "Describes the phase and value of an Apple Pencil squeeze gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PencilSqueezeGesturePhase"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGesturePhase",
      "kind": "symbol",
      "role": "symbol",
      "title": "PencilSqueezeGesturePhase",
      "type": "topic",
      "url": "/documentation/SwiftUI/PencilSqueezeGesturePhase"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGestureValue": {
      "abstract": [
        {
          "text": "Describes the value of an Apple Pencil squeeze gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PencilSqueezeGestureValue"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGestureValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "PencilSqueezeGestureValue",
      "type": "topic",
      "url": "/documentation/SwiftUI/PencilSqueezeGestureValue"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/onPencilDoubleTap(perform:)": {
      "abstract": [
        {
          "text": "Adds an action to perform after the user double-taps their Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onPencilDoubleTap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI27PencilDoubleTapGestureValueV",
          "text": "PencilDoubleTapGestureValue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onPencilDoubleTap(perform:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "onPencilDoubleTap(perform:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/onPencilDoubleTap(perform:)"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/onPencilSqueeze(perform:)": {
      "abstract": [
        {
          "text": "Adds an action to perform when the user squeezes their Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onPencilSqueeze"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI25PencilSqueezeGesturePhaseO",
          "text": "PencilSqueezeGesturePhase"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onPencilSqueeze(perform:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "onPencilSqueeze(perform:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/onPencilSqueeze(perform:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilHoverPose": {
      "abstract": [
        {
          "text": "An object that describes the hover pose of Apple Pencil during an interaction like double tap or squeeze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilHoverPose"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilHoverPose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilHoverPose"
        }
      ],
      "role": "symbol",
      "title": "UIPencilHoverPose",
      "type": "topic",
      "url": "/documentation/uikit/uipencilhoverpose"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction": {
      "abstract": [
        {
          "text": "An interaction that tells your app when a person double-taps or squeezes Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIPencilInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Phase": {
      "abstract": [
        {
          "text": "Constants that describe the phases of an interaction on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Phase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "role": "symbol",
      "title": "UIPencilInteraction.Phase",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteraction/phase"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Squeeze": {
      "abstract": [
        {
          "text": "An interaction that represents a squeeze on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Squeeze"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Squeeze",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Squeeze"
        }
      ],
      "role": "symbol",
      "title": "UIPencilInteraction.Squeeze",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteraction/squeeze"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Tap": {
      "abstract": [
        {
          "text": "An interaction that represents a double tap on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Tap"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Tap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Tap"
        }
      ],
      "role": "symbol",
      "title": "UIPencilInteraction.Tap",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteraction/tap"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate": {
      "abstract": [
        {
          "text": "The interface an object implements to handle double taps or squeezes a person makes on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIPencilInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit": {
      "abstract": [
        {
          "text": "Make your UIKit apps accessible to everyone who uses iOS and tvOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for UIKit",
      "type": "topic",
      "url": "/documentation/uikit/accessibility-for-uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/drag-and-drop": {
      "abstract": [
        {
          "text": "Bring drag and drop to your app by using interaction APIs with your views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/drag-and-drop",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drag and drop",
      "type": "topic",
      "url": "/documentation/uikit/drag-and-drop"
    },
    "doc://com.apple.uikit/documentation/UIKit/focus-based-navigation": {
      "abstract": [
        {
          "text": "Navigate the interface of your UIKit app using a remote, game controller, or keyboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/focus-based-navigation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Focus-based navigation",
      "type": "topic",
      "url": "/documentation/uikit/focus-based-navigation"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-input-from-apple-pencil": {
      "abstract": [
        {
          "text": "Learn how to detect and respond to touches from Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-input-from-apple-pencil",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Handling input from Apple Pencil",
      "type": "topic",
      "url": "/documentation/uikit/handling-input-from-apple-pencil"
    },
    "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts": {
      "abstract": [
        {
          "text": "Simplify interactions with your app using menu systems, contextual menus, Home Screen quick actions, and keyboard shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Menus and shortcuts",
      "type": "topic",
      "url": "/documentation/uikit/menus-and-shortcuts"
    },
    "doc://com.apple.uikit/documentation/UIKit/pointer-interactions": {
      "abstract": [
        {
          "text": "Support pointer interactions in your custom controls and views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/pointer-interactions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pointer interactions",
      "type": "topic",
      "url": "/documentation/uikit/pointer-interactions"
    },
    "doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures": {
      "abstract": [
        {
          "text": "Encapsulate your app’s event-handling logic in gesture recognizers so that you can reuse that code throughout your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Touches, presses, and gestures",
      "type": "topic",
      "url": "/documentation/uikit/touches-presses-and-gestures"
    },
    "media-4403818": {
      "alt": "Two illustrations showing a hand double-tapping Apple Pencil with the index finger and a hand squeezing Apple Pencil near the tip.",
      "identifier": "media-4403818",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8e17660a264e7968650999ab74dedbf6/media-4403818@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1e9ae3e9a198f3eede7e0f4cc4a46f6b/media-4403818~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures",
        "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts",
        "doc://com.apple.uikit/documentation/UIKit/drag-and-drop",
        "doc://com.apple.uikit/documentation/UIKit/pointer-interactions",
        "doc://com.apple.uikit/documentation/UIKit/focus-based-navigation",
        "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit"
      ],
      "title": "User interactions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/ApplePencil/handling-double-taps-from-apple-pencil",
        "doc://com.apple.documentation/documentation/ApplePencil/handling-squeezes-from-apple-pencil",
        "doc://com.apple.uikit/documentation/UIKit/handling-input-from-apple-pencil"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Apple-Pencil-interactions-in-SwiftUI",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/View/onPencilDoubleTap(perform:)",
        "doc://com.apple.documentation/documentation/SwiftUI/PencilDoubleTapGestureValue",
        "doc://com.apple.documentation/documentation/SwiftUI/View/onPencilSqueeze(perform:)",
        "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGesturePhase",
        "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGestureValue",
        "doc://com.apple.documentation/documentation/SwiftUI/PencilPreferredAction",
        "doc://com.apple.documentation/documentation/SwiftUI/PencilHoverPose"
      ],
      "title": "Apple Pencil interactions in SwiftUI"
    },
    {
      "anchor": "Apple-Pencil-interactions-in-UIKit",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Tap",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Squeeze",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Phase",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilHoverPose"
      ],
      "title": "Apple Pencil interactions in UIKit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/ApplePencil/handling-double-taps-from-apple-pencil",
                "doc://com.apple.documentation/documentation/ApplePencil/handling-squeezes-from-apple-pencil",
                "doc://com.apple.uikit/documentation/UIKit/handling-input-from-apple-pencil"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Apple-Pencil-interactions-in-UIKit",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Tap",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Squeeze",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Phase",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilHoverPose"
              ],
              "title": "Apple Pencil interactions in UIKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures",
                "doc://com.apple.uikit/documentation/UIKit/menus-and-shortcuts",
                "doc://com.apple.uikit/documentation/UIKit/drag-and-drop",
                "doc://com.apple.uikit/documentation/UIKit/pointer-interactions",
                "doc://com.apple.uikit/documentation/UIKit/focus-based-navigation",
                "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit"
              ],
              "title": "User interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilHoverPose/title",
          "value": "UIPencilHoverPose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilHoverPose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilHoverPose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilHoverPose/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilHoverPose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Phase/title",
          "value": "UIPencilInteractionPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Phase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Phase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Squeeze/title",
          "value": "UIPencilInteractionSqueeze"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Squeeze/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionSqueeze"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Squeeze/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionSqueeze"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Tap/title",
          "value": "UIPencilInteractionTap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Tap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Tap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate/title",
          "value": "UIPencilInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction/title",
          "value": "UIPencilInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteraction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/apple-pencil-interactions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/apple-pencil-interactions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
